### ISSUE TITLE
Assignment submission issue with LastPass password manager

### ISSUE THREAD

**Issue by zxlin** [instructure/canvas-lms#1000]
### Summary:

If the LastPass password manager is enabled in Chrome, then the assignment submissions page cannot submit the assignment as expected.

### Steps to reproduce:

 1. Download and install Chrome.
 2. Download and enable the LastPass extension on Chrome browser. 
 3. Go to an assignment submissions page.
 4. Open Chrome Developer Tools and switch to the console tab.
 5. Upload any file to an assignment submission and watch the console outputs.
 6. See the TypeError thrown printed in the console.

### Expected behavior:

File should be submitted without error.

### Additional notes:

It seems that the file is being uploaded because the POST goes through, but the user cannot get an acknowledgement that the assignment was correctly submitted. 

Stack trace:
```
Uncaught TypeError: Cannot read property 'errors' of undefined
    at HTMLIFrameElement.w (common-9e1a5d4b84.js:56)
    at HTMLIFrameElement.<anonymous> (common-9e1a5d4b84.js:56)
    at HTMLIFrameElement.dispatch (common-9e1a5d4b84.js:2)
    at HTMLIFrameElement.s (common-9e1a5d4b84.js:2)
    at Object.trigger (common-9e1a5d4b84.js:2)
    at init.triggerHandler (common-9e1a5d4b84.js:2)
    at HTMLIFrameElement.onload (4331613:1)
```

**Comment by simonista** [comment]
Hey @zxlin, thanks for the report.  I checked with our support team and as of today it looks like lastpass has updated their extension to fix this issue.  Try updating your browser extension and see if that fixes it.  Thanks!
