### ISSUE TITLE
Custom JS Not Working 

### ISSUE THREAD

**Issue by kazhuyo** [instructure/canvas-lms#1002]
### Summary:
When using latest stable, custom CSS and JS doesn't work

Inspect element javascript getting error "Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)"

**Comment by etsikt** [comment]
Which browser did you use, chrome? I get the error when using chrome but not firefox. The production.log files indicate that this has to do with cross origin problems. When uploading a new theme with Chrome I get this in the log file:

Sent file /opt/canvas-lms/tmp/files/0000/0009/consolelog.js (0.9ms)
Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.
ActionController::InvalidCrossOriginRequest (Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.):
  /opt/canvas-lms/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/request_forgery_protection.rb:225:in `verify_same_origin_request'

When using Firefox, I get this in the log file:
Sent file /opt/canvas-lms/tmp/files/0000/0010/consolelog.js (1.8ms)
Completed 200 OK in 178ms (ActiveRecord: 15.2ms)

**Comment by simonista** [comment]
We're aware of this problem for local file hosting, see https://github.com/instructure/canvas-lms/pull/945 for a potential fix, we're still evaluating the best long term strategy to fix it.

**Comment by etsikt** [comment]
Thank you for your feedback.

**Comment by jagobrown** [comment]
Thanks for comments above - useful to read.  Last 2 weeks I've had issues applying the custom JS file on our test.instructure.com site using Chrome.  Today all seems to work fine on the test & production using Chrome? (It was setting all global css colours to black! on save/apply)

When I've time i'll try and find documentation about changing the module navigation item text on the mobile Apps if it exists?

Kind regards

Jago
