### ISSUE TITLE
There was an error parsing `Gemfile`. Bundler cannot continue.

### ISSUE THREAD

**Issue by phxlin** [instructure/canvas-lms#1003]
### Summary:
While I was going through Quick Start Installation, I ran into a problem with Bundler and RubyGems (I'm not sure which one exactly). Here's the error message:

[!] There was an error parsing Gemfile: Please run `gem update --system` to bring RubyGems to 2.6.9 or newer for use with Bundler 1.14 or newer.. Bundler cannot continue.

from /Users/*****/canvas-lms/Gemfile.d/_before.rb:23

Error installing required gems.  Please run `bundle install` manually and try again

### Additional notes:
I tried `bundle install`, but I got this:
'Could not locate Gemfile'

**Comment by subssn21** [comment]
What was the fix for this, I am having the same issue?

**Comment by ccutrer** [comment]
Either run the `gem update --system` as the error message suggests, or update to Ruby 2.4.1 which includes the newer RubyGems.

**Comment by subssn21** [comment]
First time I ran gem update --system it did a bunch of work but I was still getting the same error.
ran it a second time and everything worked.

Thanks for your help

**Comment by malikshoaib715** [comment]
gem install --system worked for me, thanks for the solution :)

**Comment by davidkhanpk** [comment]
I'm getting error with following command.
**Command:** bundle install --without pulsar
**Error:** There was an error evaluating Gemfile: ruby_version must match the :engine_version for MRI. Bundler cannot continue.

**Comment by spydaspider** [comment]
I am getting this error:] There was an error parsing `Gemfile`: The `branch` option for `gem 'sqlite3'` is not allowed. Only gems with a git source can specify a branch. Bundler cannot continue.

**Comment by 4fasad** [comment]
I am getting this error:]
[!] There was an error parsing `Gemfile`: undefined method `untaint' for "/home/kotlyar/Polifasad/OnlinePolifasad-master/Gemfile":String

      block.call(path.dup.untaint)
                         ^^^^^^^^. Bundler cannot continue.

**Comment by biniyam69** [comment]
There was an error parsing `Gemfile`:  - [!] There was an error parsing `Gemfile`: libruby.so.3.1: cannot open shared object file: No such file or directory - /var/canvas/vendor/bundle/ruby/3.1.0/gems/psych-5.1.2/lib/psych.so. Bundler cannot continue.

I am getting this error help
