### ISSUE TITLE
Users API search_term - search on login_id

### ISSUE THREAD

**Issue by mattmcnabb** [instructure/canvas-lms#1005]
### Summary:
It would benefit us greatly if we were able to search via the api on the domain name of the login_id property. The [current documentation](https://canvas.instructure.com/doc/api/users.html) states that this searches on the Sis_id, name, and email address. Our user base is split into a few different domains and it would be nice to be able to enumerate them based on the domain rather than querying all of them and filtering after, which takes a long time.

Thanks!

**Comment by simonista** [comment]
Hey @mattmcnabb, thanks for the suggestion.  Would you mind submitting it as a feature request over at our community site https://community.canvaslms.com/community/ideas?  That'll get it in front of product managers who can make the call about prioritizing something like this.  We try to keep github issues specific to bug reports from open source users.

https://community.canvaslms.com/ideas/1126 looks like it might match what you're doing, you could add your vote of support to that idea.

Thanks!

**Comment by mattmcnabb** [comment]
@simonista 

Thanks, but for some reason I can't log in to the Canvas Ideas portal. The Idea you linked above is similar, but is really about using the admin panel in the Canvas portal. I leverage the REST API for several management tasks and so I thought it might be more appropriate to add the issue here.

Anyway, thanks for the consideration - I'll ask someone else on my team if they are able to log in to the Ideas portal to make the request.

**Comment by simonista** [comment]
After talking with @ccutrer, it sounds like this is a straightforward change, we'll try to get it into one of the next releases.

**Comment by mattmcnabb** [comment]
Excellent! I'll keep an eye out for the release notes. Thanks!

**Comment by mattmcnabb** [comment]
I saw this feature in the Beta release notes the other day. Thanks!

**Comment by ccutrer** [comment]
👍
