### ISSUE TITLE
dist/brandable_css/c1a8880e8fd2168752e253ce8dd4c8d3/new_styles_normal_contrast/bundles/common-.css” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

### ISSUE THREAD

**Issue by sharathkumar** [instructure/canvas-lms#1009]
### Summary:
I am facing an issue regarding brandable css  " dist/brandable_css/c1a8880e8fd2168752e253ce8dd4c8d3/new_styles_normal_contrast/bundles/common-7d132b6bcd.css” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff)." 

Node version : v6.2.2
npm version : 3.9.5

Please help me ASAP.

**Comment by omarkhan** [comment]
Hi! Have you tried asking for help on [IRC](http://webchat.freenode.net/?channels=canvas-lms) or the [mailing list](http://groups.google.com/group/canvas-lms-users)?

**Comment by simonista** [comment]
I haven't heard of this before, but apparently

> Blocks a request if the requested type is "style" and the MIME type is not "text/css"
> 
> -- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

Can you tell what mime type is being sent for that file?
