### ISSUE TITLE
Error opening Conversation message sent from account group context

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#1010]
### Summary:
If a user is a member of an account-level group and sends a message to another member of that group, the recipient will not be able to open the message. The message will fail to load, and an exception will be logged. 

### Steps to reproduce:

 1. Create an account-level group. 
 2. Add yourself and one other user as members of the group.
 3. Compose a new message. From the "Course" menu, select the group from the "Groups" submenu. In the "To" field, select the other group member. Send the message. 
<img width="479" alt="screen shot 2017-03-23 at 1 04 15 pm" src="https://cloud.githubusercontent.com/assets/618034/24260102/3fc89b68-0fc9-11e7-89f7-3ca921ede8c3.png">
 4.  Try to open the message in the "Sent" messages, or try to open the message as the recipient. 

### Expected behavior:
The message should load. 

### Additional notes:
It appears that the method [`Conversation#replies_locked_for?`](https://github.com/instructure/canvas-lms/blob/stable/app/models/conversation.rb#L718) expects either `self.context` or `self.context.context` to be a `Course` object. In this case, `self.context.context` will be an `Account` object. The error occurs on line 718 when trying to call `course.admin_enrollments`. 

**Stack trace:** (note that this Canvas instance was last updated December 20th, so line number may differ from current master)

```
/var/www/canvas/shared/bundle/ruby/2.3.0/gems/activemodel-4.2.7.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
/var/www/canvas/releases/20161220163749/app/models/conversation.rb:719:in `replies_locked_for?'
/var/www/canvas/releases/20161220163749/lib/api/v1/conversation.rb:54:in `conversation_json'
/var/www/canvas/releases/20161220163749/app/controllers/conversations_controller.rb:544:in `show'

```

**Comment by simonista** [comment]
Hey @christopher-b, looks like this was fixed in e93bd734173f1b859445fc4fb50320676ca823d0, which is in the 2017-01-28 release.  Thanks for the report!
