### ISSUE TITLE
Uploading custom JS files with Chrome fails when using local storage

### ISSUE THREAD

**Issue by etsikt** [instructure/canvas-lms#1011]
### Summary:
When using Chrome to upload custom JS files in theme editor, it fails with a 422 unprocessable entity error. This is because Chrome uploads the attachment as text/javascript, and 
gems/actionpack-4.2.7.1/lib/action_controller/metal/request_forgery_protection.rb 
has a check against this:

# Check for cross-origin JavaScript responses.
      def non_xhr_javascript_response?
        content_type =~ %r(\Atext/javascript) && !request.xhr?
      end

Since the javascript is loaded with the following code, in the web page, the xhr test above also fails:
          require(['jquery'], function fnCanvasUsesToLoadAccountJSAfterJQueryIsReady () {
            ["https:\/\/localhost\/accounts\/1\/files\/31\/download?verifier=D3R4F3onxO17hNXRkdWOcxEy12uUpMzDonAJl3Pu"].forEach(function (src) {
              var s = document.createElement('script');
              s.src = src;
              document.body.appendChild(s);
            });
          });

Inspecting the attachment table in the database shows that files uploaded with chrome and firefox are stored with different content types. Below, the attachment with id 21 was uploaded with firefox, and the attachement with id 31 that was uploaded with chrome and corresponds to the code above: 
 id | context_id | context_type | size | folder_id |       content_type       |   filename    |                   uuid                   | display_name  |         created_at         |         updated_at         | workflow_state | user_id | locked | file_state | deleted_at | position | lock_at | unlock_at | last_lock_at | l
ast_unlock_at | could_be_locked | root_attachment_id | cloned_item_id | migration_id | namespace | media_entry_id | md5 | encoding | need_notify | upload_error_message | replacement_attachment_id | usage_rights_id |        modified_at         | viewed_at 
----+------------+--------------+------+-----------+--------------------------+---------------+------------------------------------------+---------------+----------------------------+----------------------------+----------------+---------+--------+------------+------------+----------+---------+-----------+--------------+--
--------------+-----------------+--------------------+----------------+--------------+-----------+----------------+-----+----------+-------------+----------------------+---------------------------+-----------------+----------------------------+-----------
 21 |          1 | Account      |   19 |         2 | application/x-javascript | consolelog.js | 2AjQTFrnoHZtUJbWjmXK7sU8X4F9n9S6jTyREKDF | consolelog.js | 2017-03-24 09:56:07.469571 | 2017-03-24 09:56:07.469571 | processed      |         | f      | available  |            |       21 |         |           |              |  
              |                 |                    |                |              | account_1 |                |     | UTF-8    |             |                      |                           |                 | 2017-03-24 09:56:07.447681 | 
 31 |          1 | Account      |   19 |         2 | text/javascript          | consolelog.js | D3R4F3onxO17hNXRkdWOcxEy12uUpMzDonAJl3Pu | consolelog.js | 2017-03-24 11:27:26.290397 | 2017-03-24 11:27:26.290397 | processed      |         | f      | available  |            |       31 |         |           |              |  
              |                 |                    |                |              | account_1 |                |     | UTF-8    |             |                      |                           |                 | 2017-03-24 11:27:26.238893 | 

Changing the content_type for the attachment with id 32 to application/x-javascript makes the 422 unprocessable entity go away.

Uploading from chrome works for amazon storage, because it is included like this in the web page:
          require(['jquery'], function fnCanvasUsesToLoadAccountJSAfterJQueryIsReady () {
            ["https:\/\/instructure-uploads-eu.s3-eu-west-1.amazonaws.com\/account_47170000000000001\/attachments\/544\/consolelog.js"].forEach(function (src) {
              var s = document.createElement('script');
              s.src = src;
              document.body.appendChild(s);
            });
          });

Since the file is not requested from the Canvas server, the forgery protection in the action controller is not used.

### Steps to reproduce:

 1. Install Canvas server with local storage.
 2. Upload a JS file in theme editor with Chrome. I uploaded a file with a simple "console.log("HELLO");" statement.
 3. Preview your changes.
 4. You get 422 unprocessable entity when Chrome tries to load the file.

### Expected behavior:
It should be possible to upload javascript files to the local storage in theme editor using any web browser.
This used to work in a previous version of Canvas (around may 2016). I am not sure when the behaviour changed or what is the best fix!

### Additional notes:
The test non_xhr_javascript_response in forgery protection in the action controller gem seems to be outdated according to the specification: http://stackoverflow.com/questions/9664282/difference-between-application-x-javascript-and-text-javascript-content-types

Furthermore, the FormData upload sent in handleFormData in app/jsx/theme_editor/ThemeEditor.jsx causes Chrome to specify text/javascript for the file:
 
 ------WebKitFormBoundaryZMEGRFqFTaVTJ5x7
Content-Disposition: form-data; name="js_overrides"; filename="consolelog.js"
Content-Type: text/javascript

Whereas Firefox sends it with application/x-javascript:
-----------------------------219779118155763386132662809
Content-Disposition: form-data; name="mobile_js_overrides"; filename="consolelog.js"
Content-Type: application/x-javascript

**Comment by grahamb** [comment]
See #945 for a workaround. We've been running with this in production at our site for months with no issue.

**Comment by etsikt** [comment]
This error only seem to occur when using the latest version of Chrome on mac. I've posted a question about this here: http://stackoverflow.com/questions/43061144/why-does-chrome-on-mac-upload-javascript-files-with-obsolete-content-type-text-j

I used a workaround based on #945 like Graham suggested, but I had to add the following line:

protect_from_forgery except: :show
