### ISSUE TITLE
Bundle Issue in Ubuntu 16.04 | Ruby 2.2

### ISSUE THREAD

**Issue by gdgeorge** [instructure/canvas-lms#1012]
### Steps to reproduce:

 1. Follow the setup guide at https://github.com/instructure/canvas-lms/wiki/Production-Start
 2. Installation with Ruby 2.3 does not run.  
 3. Installation with Ruby 2.2 is problematic to compile (see Additional notes).
### Expected behavior:
At some point I really thought that the whole thing would compile and run...
### Additional notes:
Attempted Bundle with Ruby 2.2 fails with version error from Gemfile (expected Ruby 2.3)
Version statements in Gemfile statements seem to be ignored. If the _before.rb file is edited to allow Ruby 2.2, Bundle then fails on gems switchman, inst-jobs, and canvas_statsd.  (Scripted versions require Ruby 2.3.) Changing them to versions compatible with Ruby 2.2 allows Bundle to run `RAILS_ENV=production bundle exec rake canvas:compile_assets` 
fails on canvas_statsd which requires version 2.0 which supports Ruby 2.3.

I've clearly missed something,  please advise.

**Comment by gdgeorge** [comment]
Quick update. I changed tactics and went back to trying an install with Ruby 2.3 and ran into similar problems with the Bundler version and then the pg gem.

**Comment by ccutrer** [comment]
Do you have the actual error from bundler? Canvas definitely does not work under Ruby 2.2 (there are known bugs). You may want to try the recently released ruby 2.4.1 instead.

**Comment by gdgeorge** [comment]
Ahhh. That explains some of the issue.  Is there a list of specific versions needed to build Canvas available anywhere? I've been working from several that are outdated.  I'd like to update the setup guide.

Thanks!

**Comment by ccutrer** [comment]
The definitive source is https://github.com/instructure/canvas-lms/blob/stable/Gemfile.d/_before.rb, which is also enforced by the app.

**Comment by gdgeorge** [comment]
Thanks for this. It doesn't specify the non-Ruby packages though.  I'll continue to march.  We can close this.

**Comment by davidkhanpk** [comment]
I'm getting error with following command.
**Command:** bundle install --without pulsar
**Error:** There was an error evaluating `Gemfile`: ruby_version must match the :engine_version for MRI. Bundler cannot continue.
