### ISSUE TITLE
Theme preview is not working

### ISSUE THREAD

**Issue by sharathkumar** [instructure/canvas-lms#1013]
### Summary:
I'm trying to setup latest version of canvas lms. All the steps are mentioned in production start is completed without any issues. But I am facing an issue with theme editor preview. As per the doc I tried with node versions 6.2.2 and 6.2.1. But it is failing every time. I wand to fix it ASAP. Can you please help anyone to fix this.

### Dependencies
ruby 2.3.1p112
node v6.2.2
canvas-lms@0.0.0 /u01/var/canvas
├─┬ brandable_css@0.0.67
│ └── node-sass@3.13.1 
└── node-sass@3.4.0  extraneous

### Error log
`  Error running BrandableCSS CLI: ./node_modules/.bin/brandable_css --brand-id 4c92bab9b128ade3a46568c65fa2b357

/u01/var/canvas/lib/brandable_css.rb:279:in `block in run_cli!'
/home/ubuntu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
/home/ubuntu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/open3.rb:190:in `popen2e'
/u01/var/canvas/lib/brandable_css.rb:265:in `run_cli!'
/u01/var/canvas/lib/brandable_css.rb:249:in `compile_brand!'
/u01/var/canvas/app/models/brand_config.rb:191:in `compile_css!'`

**Comment by simonista** [comment]
6.2 should be okay, although we use 6.9 in production.  if you run `./node_modules/.bin/brandable_css --brand-id 4c92bab9b128ade3a46568c65fa2b357` directly from your canvas root directory, do you get a more helpful error message?

**Comment by sharathkumar** [comment]
@simonista  When we do precompile, compiling custom brands just starting and ending. not showing any logs and no files are compiling 

ubuntu@ip-172-31-42-254:/u01/var/canvas$ RAILS_ENV=production bundle exec rake canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
node is: v6.2.1 (/home/ubuntu/.nvm/versions/node/v6.2.1/bin/node)
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
--> Finished: 'Making sure node_modules are up to date' in 21.16998763603624
--> Starting: 'compile css (including custom brands)'
--> Finished: 'compile css (including custom brands)' in 3.2566637190175243

**Comment by simonista** [comment]
Hey @sharathkumar, sorry for the delay, did you get this worked out?

**Comment by dimitriacosta** [comment]
I tried to use that command but I haven't get it to work yet

**Comment by shawniverson** [comment]
Check out latest updates to Production Start
https://github.com/instructure/canvas-lms/wiki/Production-Start

I've been fighting this issue for a long time and finally figured out what was going on.

At some point, public/stylesheets/compiled became obsolete

The stylesheet compilation actually happens in app/stylesheets, so the canvas user that Passenger and Delayed Jobs run as must have write access to a few things in there, as well as all files in /public/dist/brandable_css.
