### ISSUE TITLE
Inline preview for document link not available

### ISSUE THREAD

**Issue by sharathkumar** [instructure/canvas-lms#1017]
### Summary:
I wand to show the inline preview of a document link. But the checkbox option for enable preview is not available. Please any one help me to implement this.
### Screenshot
![canvas inline preview](https://cloud.githubusercontent.com/assets/3734452/24607420/307df382-188f-11e7-84e9-792f49f09e90.png)

**Comment by omarkhan** [comment]
We use github issues for bug reports only. Please ask on [the mailing list](http://groups.google.com/group/canvas-lms-users) or at [#canvas-lms](http://webchat.freenode.net/?channels=canvas-lms) on Freenode.
