### ISSUE TITLE
Assignment score displayed in module page, even assignment is muted.

### ISSUE THREAD

**Issue by samuels410** [instructure/canvas-lms#1020]
### Summary:
When the assignment is muted the excepted behaviour is LMS will not show the the grade of the particular assignment but when the student hover the little icon in the module page, the current assignment score is getting displayed.
### Steps to reproduce:

 1.Create a assignment
 2.Make the assignment part of the the module and set requirement in the module, saying some score should be get in-order to complete the module.
 3.Now mute the assignment 
 4.The student should submit the assignment.
 5.Now grade the student from the grader
 6.This time the student hover over the small icon in the assignment row, the pop over will be show the message "you scored a 60, must score at least a 80"

![img_10042017_110228_0](https://cloud.githubusercontent.com/assets/3351088/24928317/ad1aed00-1f1f-11e7-9980-ab258a6a2bef.png)

**Comment by omarkhan** [comment]
Thanks for the report @samuels410! We will look into this and get back to you soon.

**Comment by samuels410** [comment]
@omarkhan Thanks
