### ISSUE TITLE
External tool launch not including custom parameters requested in ContentItemSelection response

### ISSUE THREAD

**Issue by cbothner** [instructure/canvas-lms#1025]
I'm building a Tool Provider which provides a content item selection assignment placement. I need to specify some custom parameters to be included with the launch request. Following the [IMS information model](https://www.imsglobal.org/specs/lticiv1p0/specification-3), I'm sending back a response that looks like this.

```
lti_message_type='ContentItemSelectionRequest'
lti_version='LTI-1p0'
content_items='{
  "@context": "http://purl.imsglobal.org/ctx/lti/v1/ContentItem",
  "@graph": [
    {
      "@type": "LtiLinkItem",
      "url": "https://localhost:3000/authentication_strategies/auth/lti/callback",
      "mediaType": "application/vnd.ims.lti.v1.ltilink",
      "placementAdvice": {"presentationDocumentTarget": "window"},
      "custom": {"redirect": "https://localhost:3000/cases/tesla-powerwall"}
    }
  ]
}'
```

I am expecting the LTI launch to include a parameter `custom_redirect`, but no such parameter is included.  Is this the intended functionality? Is there a better way to request the inclusion of custom parameters that vary based on the content item the user selected?

**Comment by mcwqy9** [comment]
Great question. We do not currently support custom parameters for content item. This feature is on our roadmap. As a workaround, many developers use GET params in the content item url to distinguish between different content items. 

This might look like this
```lti_message_type='ContentItemSelectionRequest'
lti_version='LTI-1p0'
content_items='{
  "@context": "http://purl.imsglobal.org/ctx/lti/v1/ContentItem",
  "@graph": [
    {
      "@type": "LtiLinkItem",
      "url": "https://localhost:3000/authentication_strategies/auth/lti/callback?redirect=https%3A%2F%2Flocalhost%3A3000%2Fcases%2Ftesla-powerwall",
      "mediaType": "application/vnd.ims.lti.v1.ltilink",
      "placementAdvice": {"presentationDocumentTarget": "window"}
    }
  ]
}'
```

If you go down that road, be aware that Canvas will copy the get params into the post body when doing the content item launch. If that is undesirable (for instance it can cause oauth signing issues), consider the oauth_compliant option documented here: https://canvas.instructure.com/doc/api/external_tools.html and here https://canvas.instructure.com/doc/api/file.tools_xml.html under "Launch URL's containing query parameters"

**Comment by cbothner** [comment]
The oauth signing issues were exactly why I had considered that option (my first choice) unworkable, but I will investigate those resources. Thank you.

**Comment by SuseeHarini** [comment]
where do we add the files to change the custom parameters of the LTI components?

**Comment by RoChess** [comment]
The ability to reference a course content-item ID that Canvas will automatically update when the course gets copied would be extremely useful as well.

**Comment by karendolan** [comment]
Can anyone provide a link to where this might be on the roadmap?

**Comment by rhodgkins** [comment]
Any update on this - will custom parameters ever be included in the launch request after being specified in a `Content-Item`?

**Comment by tim1mw** [comment]
I'm encountering this problem as well. This bug basically means that an LTI tool that conforms to the specification and uses custom parameters as part of its launch will never work with Canvas. I'm not a fan of having to put in platform-specific work-around's to cope with implementations that don't conform with the spec, I'm amazed that this still hasn't been dealt with.
