### ISSUE TITLE
getting the errors like /var/canvas/lib/tasks/js.rake:127:in `block (2 levels) while running RAILS_ENV=production bundle exec rake canvas:compile_assets

### ISSUE THREAD

**Issue by prashanthpola** [instructure/canvas-lms#1027]
I am running "RAILS_ENV=production bundle exec rake canvas:compile_assets" command in my aws server. I am getting the following errors.

### Expected behavior:
I want to customise(branding) the canvas-lms for that i have changed some images in "canvas-lms/app/stylesheets/brandable_variables.json" like below.

  {
    "variable_name": "ic-brand-header-image",
    "type": "image",
    "accept": "image/png,image/gif,image/jpeg,image/svg",
    "default": "/images/svg-icons/my_custom_logo.jpg"  # here i changed image
  }

to reflect these changes i am running "RAILS_ENV=development bundle exec rake canvas:compile_assets" command.

### Additional notes:
Here is the full error description.

ubuntu@ip-172-31-27-77:/var/canvas$ RAILS_ENV=production bundle exec rake canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
node is: v6.10.2 (/usr/bin/node)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN eslint-config-airbnb@14.1.0 requires a peer of eslint@^3.15.0 but none was installed.
npm WARN eslint-config-airbnb-base@11.1.3 requires a peer of eslint@^3.19.0 but none was installed.
npm WARN i18nliner-handlebars@0.2.0 requires a peer of i18nliner@~0.1.5 but none was installed.
--> Finished: 'Making sure node_modules are up to date' in 11.00746729131788
--> Starting: 'compile css (including custom brands)'
--> Finished: 'compile css (including custom brands)' in 4.077910020947456
working in 2 processes
--> Starting: 'css:styleguide'
--> Starting: 'compile coffee/jsx, js i18n, r.js optimizer'
--> Starting: 'js:generate'
--> creating styleguide
Building client app 'canvas_quizzes'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb:393:in `block in replace_bin_path': can't find executable dress_code (Gem::Exception)
	from /usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb:419:in `block in replace_bin_path'
	from bin/dress_code:16:in `<main>'
npm WARN canvas_quizzes@1.0.0 No license field.
	Running 'npm run build'...
Client app 'canvas_quizzes' was built successfully.
--> Compiling React JSX
--> Creating ember app bundles
--> Pre-compiling ember handlebars templates
--> Generating plugin extensions
--> Pre-compiling handlebars templates
--> Generating plugin extensions finished in 0.0009524701163172722
--> Creating ember app bundles finished in 0.0041527580469846725
--> Pre-compiling ember handlebars templates finished in 2.299009159207344
--> Pre-compiling handlebars templates finished in 3.63535488396883
--> Compiling React JSX finished in 27.070187725126743
/var/canvas/vendor/bundle/ruby/2.3.0/bundler/gems/rails-bff1f05813d0/activesupport/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- coffee-script (LoadError)
	from /var/canvas/vendor/bundle/ruby/2.3.0/bundler/gems/rails-bff1f05813d0/activesupport/lib/active_support/dependencies.rb:274:in `block in require'
	from /var/canvas/vendor/bundle/ruby/2.3.0/bundler/gems/rails-bff1f05813d0/activesupport/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /var/canvas/vendor/bundle/ruby/2.3.0/bundler/gems/rails-bff1f05813d0/activesupport/lib/active_support/dependencies.rb:274:in `require'
	from /var/canvas/lib/tasks/js.rake:127:in `block (2 levels) in <top (required)>'
	from /var/canvas/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
	from /var/canvas/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
	from /var/canvas/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
	from /var/canvas/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
	from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /var/canvas/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
	from /var/canvas/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
	from /var/canvas/lib/tasks/js.rake:48:in `block (4 levels) in <top (required)>'
	from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	from /var/canvas/lib/tasks/js.rake:47:in `block (3 levels) in <top (required)>'
rake aborted!
Parallel::DeadWorker: Parallel::DeadWorker
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:71:in `rescue in work'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:68:in `work'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:362:in `block (4 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:473:in `with_instrumentation'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:361:in `block (3 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:349:in `loop'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:349:in `block (2 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:203:in `block (2 levels) in in_threads'
EOFError: end of file reached
/var/canvas/vendor/bundle/ruby/2.3.0/bundler/gems/rails-bff1f05813d0/activesupport/lib/active_support/core_ext/marshal.rb:6:in `load'
/var/canvas/vendor/bundle/ruby/2.3.0/bundler/gems/rails-bff1f05813d0/activesupport/lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
/var/canvas/gems/canvas_ext/lib/canvas_ext/marshal.rb:8:in `load'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:69:in `work'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:362:in `block (4 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:473:in `with_instrumentation'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:361:in `block (3 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:349:in `loop'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:349:in `block (2 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.10.0/lib/parallel.rb:203:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
ubuntu@ip-172-31-27-77:/var/canvas$

**Comment by omarkhan** [comment]
Hi @prashanthpola - have you tried asking for help on [IRC](http://webchat.freenode.net/?channels=canvas-lms) or the [mailing list](http://groups.google.com/group/canvas-lms-users)?

**Comment by simonista** [comment]
Hi @prashanthpola, as mentioned in our [contributing guidelines](https://github.com/instructure/canvas-lms/blob/stable/CONTRIBUTING.md#filing-issues), we try to reserve github issues for bugs in using the product, and try to direct people to irc or the mailing list for help with config/deployment issues.

That said, it looks like the relevant line in your error report is `can't find executable dress_code (Gem::Exception) from /usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb:419`  Looks like something isn't correct with your installed gems.
