### ISSUE TITLE
glymcons are not working properly. showing wrong Icons. after running bundle exec rake canvas:compile_assets command in AWS Server. 

### ISSUE THREAD

**Issue by prashanthpola** [instructure/canvas-lms#1028]
### Summary:
In canvas production in aws server I ran  bundle exec rake canvas:compile_assets. after running this command all my icons symbols showing wrong icons 

### Expected behavior:
Icons should show the correct icons not the wrong icons. i dont know how to fix this. or is there any way to rollback the " bundle exec rake canvas:compile_assets" command?

**Comment by omarkhan** [comment]
Hi @prashanthpola - have you tried asking for help on [IRC](http://webchat.freenode.net/?channels=canvas-lms) or the [mailing list](http://groups.google.com/group/canvas-lms-users)?

**Comment by prashanthpola** [comment]
Yes.

**Comment by omarkhan** [comment]
I can't reproduce this. Can you post some screenshots? Which version of canvas are you running? How is it deployed?

**Comment by simonista** [comment]
I've never been able to reproduce this consistently, but have seen it before, and deleting `public/dist` and then running `bundle exec rake canvas:compile_assets` again has cleared it up for me.

**Comment by wolever** [comment]
I can consistently reproduce this issue with the docker development image.

To recreate:

1. Use docker-compose to get Canvas running

2. Run `bundle update` then `bundle exec rake canvas:compile_assets`

3. Open Canvas and notice that the icons are all wrong (this is from a course settings page, but they're wrong everywhere):

![2017-08-02_11-18-47](https://user-images.githubusercontent.com/59575/28880893-64f19576-7774-11e7-9b39-91e4009f8a3e.png)


Just tested with rev: d6b2dc25a117433203408ca1c7250db2594fd8a1

**Comment by omarkhan** [comment]
Confirmed, thanks providing the steps to reproduce! Here's a workaround for now:

```
docker-compose rm web jobs webpack
docker volume rm canvaslms_generated_2
docker-compose run --rm web bundle exec rake canvas:compile_assets
```

**Comment by geekfly2016** [comment]
Yeah, I also encountered the same problem. I deleted the` public/dist` directory and recompiled, then canvas returned to normal.
`sudo RAILS_ENV=production bundle exec rake canvas:compile_assets`
