### ISSUE TITLE
Glyphicons replaced with special and extended characters.

### ISSUE THREAD

**Issue by lsornanathan** [instructure/canvas-lms#1031]
For quite something I found that Canvas has been displaying glyphicons as special and extended characters. On average, this happens once every 30 to 40 page loads.  We initially noticed it happening in the open source version of the Canvas. However, we have also found the hosted (sandpit) version to have the same behavior. I've included screenshots of both the open source and hosted version having this issue.

![opensource_sandpit_screenshot](https://cloud.githubusercontent.com/assets/21029312/25598568/168f2e1e-2f19-11e7-9763-d8d26600cda3.png)

![instructure_sandpit_screenshot](https://cloud.githubusercontent.com/assets/21029312/25598570/1b754472-2f19-11e7-8261-c99055242838.png)

**Comment by tierra** [comment]
Just to get some additional context, can you mention what browser(s) this has shown up in, which versions of those browsers, what system locale (language) you're using, and Canvas user account / course language you have set (though it looks like it's English (US), just want to confirm though).

Is there any kind of errors in your browser console or perhaps network issues (fetching the font icon resources for example)? Is this just what you see when the font fails to load?

**Comment by lsornanathan** [comment]
There is no error(s) in the browser console. I do not think it's a network issue because I have come across this issue while accessing the Canvas site from different networks. Normally, after you refresh the page the icons appear correctly. Here are the additional info that you asked for:

**Open Source Version**
---
Browser: Chrome (v56 & v57)
System Locale: English (Australia)
Account Language: English (US)
Course Language: English (US)

**Hosted Version**
---
Browser: Chrome (v56 & v57)
System Locale: English (Australia)
Account Language: English (Australia)
Course Language: English (Australia)

**Comment by ally1** [comment]
Hello,

I am experiencing almost the same issue with the exception of the icons visualization.
Here is the screenshot how they are displaying:
https://www.screencast.com/t/T2G1bXNtQ3

The reveal arrow to the left of the module name has become a minus sign in a circle, the cloud has become the Greek letter mu in a circle, the plus sign has become something different and the gearwheel has also become something different.

This happened after updating Canvas LMS from origin/stable/2017-06-03 > origin/stable/2017-06-24.
Does anybody has explanation of the above?

Thanks.
