### ISSUE TITLE
Could not load apps in account

### ISSUE THREAD

**Issue by phongdatgl** [instructure/canvas-lms#1032]
### Summary:
Old version, i can see apps loaded in account setting but new version i can't see it.

### Steps to reproduce:

 1. In left panel, click Admin -> select one account. 
 2. Click setting on bottom submenu. 
 3. In main tab, click Applications. 

### Additional notes:
In old version, list apps will be loaded: 
![canvas old version](http://image.prntscr.com/image/f33c5796fcbe44acafb57219f98fb6ac.png)

In new version, list apps can not load: 
![canvas new version](http://image.prntscr.com/image/18278632b1a6416f976da2570b739fdd.png)

View in console, i see this: 
![error in console](http://image.prntscr.com/image/986eda7573ce4cfc910682ec34cae221.png)

I've try to rebuild assets but it can not worked too.

**Comment by simonista** [comment]
Hey @phongdatgl, I can't reproduce this, the Apps page is working fine for me.  Maybe check `/error_reports` and see if there's a backend error being reported?
