### ISSUE TITLE
Page can be made to hang when adding new assignment 

### ISSUE THREAD

**Issue by elmarti** [instructure/canvas-lms#1035]
### Summary:

When creating an assignment, the Save & Publish button uses a confirm dialog, for which if you click cancel. the assignment creation page hangs forever. Even if you click cancel the assignment is created. I think that this should be removed and replaced with a more appropriate HTML based dialog. 

This issue created a lot of uncertainty at the point of creating an assignement. 

### Steps to reproduce:

 1. Create an assignment
 2.1 (Worth noting that all I was doing was adding a title and linking Canvas to an external service)
 2.2 Click save & publish
 3. Click cancel on the dialog
 4. Page will hang forever, even though the assignment was created. 

### Expected behavior:
As the assignment is created at the point of clicking Save & Publish, the dialog should be removed or replaced with something more suitable and explanatory. 

### Additional notes:
This could be achieved by removing the onbeforeunload functionality: 
``` window.onbeforeunload = null; ```
and attaching events to the router and submit buttons to handle situations in which the user can lose data.

**Comment by simonista** [comment]
Can you clarify which dialog you are speaking of?  I don't get a dialog when I click "Save & Publish"

**Comment by elmarti** [comment]
I can't recreate now sorry, must've been something I did
