### ISSUE TITLE
Unable to lock quizzes

### ISSUE THREAD

**Issue by berga** [instructure/canvas-lms#1036]
### Summary:

Quizzes can't be locked anymore from web interface menu item "Lock this quiz now"

### Steps to reproduce:

 1. Create a new Quiz
 2. click on menu item "Lock this quiz now"
 3. a notification shows "Quiz successfully updated"
 4. the menu item still shows label "Lock this quiz now" and the Quiz doesn't appear to be locked

### Expected behavior:

Updating a Quiz via UI interface with attribute "locked=true" should lock the quiz and the attribute locked_at should be filled up as working before 

### Additional notes:

It seems to be introduced since release 2017-03-11.24 where strong_params have been removed
a9fab4f4af26c468c6196351ccca7ef499730aa5
Also reported by users in https://community.canvaslms.com/thread/15630-lock-this-quiz-now

**Comment by simonista** [comment]
Merged here: 9861e5faea4e5e0e5824fb966718691bfe4980be
