### ISSUE TITLE
Student: Can see grade if assignment is muted.

### ISSUE THREAD

**Issue by kbohinski** [instructure/canvas-lms#1039]
### Summary:
Through some trickery, students can see their assignment grades even if muted.

### Steps to reproduce:

 1. Have an assignment muted with an actual grade.
 2. Have student click the mute icon, then the escape key.
 3. The class categories and average is now updated.
(No idea how the teacher side of things works, I'm a student...)

**Comment by simonista** [comment]
Hey @kbohinski, thanks a lot for the report, this is indeed clever.  Our grading team is planning to dig into it, we'll keep you posted.

**Comment by ktgeek** [comment]
A fix for this is working itself through our QA process now!  Thanks for bringing it to our attention, @kbohinski

**Comment by ktgeek** [comment]
This was merged to master and hotfixed into production on Tuesday.  Sorry I forgot to update this here.
