### ISSUE TITLE
/login/oauth2/accept Internal Server Error

### ISSUE THREAD

**Issue by vladimirk85** [instructure/canvas-lms#1042]
### Summary:
Hi all. While using canvas lms I am getting an error. I am trying to get user token using some xml.

### Steps to reproduce:
https://mydomain.com:3001/login/oauth2/accept
my request url is looks like this, and an error is 

> 500 Internal Server Error

also in the response part of the request I see

> You need to have JavaScript enabled in order to access this site.

### Expected behavior:

Actually I dont know how does this work, but I expect it should return the page from my xml with authentication token and other settings, which I need to use to work with canvas lms api in my local. 

do you have any ideas how to solve this?

**Comment by ccutrer** [comment]
You'll need to add more details on exactly what you're doing, and logs from your server showing the error. IIRC that URL should only be used by Canvas itself, when they're approving a token. It definitely requires a POST, not a GET, which I'm guessing is why you're getting an error.

**Comment by vladimirk85** [comment]
Actually I see that the request is POST. Maybe I need to install some module to use "accept"?

**Comment by vladimirk85** [comment]
I found the canvas log file. Here is the link https://drive.google.com/open?id=0ByjWatrzonfvdDZxdGQ5R0RIaWs, please take a look.
Actually I need to get an access token from canvas lms api, using october cms, token request is working but after canvas making his own 'acceps' request, which is returning an error.

**Comment by ccutrer** [comment]
`Redis is not enabled for this install` is your error. Using the OAuth flow in Canvas requires that Redis be configured.
