### ISSUE TITLE
autorization_code not found

### ISSUE THREAD

**Issue by vladimirk85** [instructure/canvas-lms#1046]
### Summary:
I am trying to get access token
here is my request:
https://domain.com:3001/login/oauth2/auth?client_id=10000000000006&response_type=code&redirect_uri=https%3A%2F%2Fdomain.com%2Foctobercms%2FsaveUserInfo%3Flti%3D5%26role%3D3%26approver%3DInstructor
after this it redirects to:
https://domain.com:3001/login/oauth2/token?client_id=10000000000006&client_secret=SPuGP6IiPCyTIaDY34WA0E2vewwkjFl4JDxgLFFnvBersJf9T7P2iWVISvW0fE8m&code=756a9747d7075fcb291efb55b0734e5763ace5b2153f4895b05f49eac6af73666fe4e439b6a5590066f93c993d7584b9d9a416169f3f536789ed3b9b77caf61e

### Expected behavior:
it should return me access token, so that can use it for my local env, but instead I am getting this error:
{"error":"invalid_grant","error_description":"authorization_code not found"}

please can you tell me what I am doing wrong?

**Comment by ToeBee** [comment]
Your second request seems to be missing the `grant_type=authorization_code` parameter:
https://canvas.instructure.com/doc/api/file.oauth.html#oauth2-flow-3

P.S. Your client secret isn't secret any more :)

**Comment by brandav** [comment]
I am also receiving this "invalid_grant" error, even with the `grant_type=authorization_code` parameter

**Comment by wdci-dev** [comment]
@brandav @vladimirk85 have you guys found any solution for this? or any workaround yet. Seems this issue is still there.

**Comment by brandav** [comment]
@wdci-dev no idea if this will work for you but this is what I've been using. Also make sure to use SSL-encrypted domains (https) for redirect uris

[oauth_post.txt](https://github.com/instructure/canvas-lms/files/4625480/oauth_post.txt)

**Comment by wdci-dev** [comment]
Thanks @brandav Thanks for your help  
cheers!

**Comment by buckett** [comment]
I *think* I saw this if you didn't have Redis up and running on a local copy of Canvas.

**Comment by wdci-dev** [comment]
@buckett spot on, Redis is the culprit. We have got it working after resolving that. Thanks!

**Comment by shotaars** [comment]
@brandav I'm looking for the solution. Did you succeeded here? Or maybe any hint about how to solve that?

**Comment by qiongcheng5** [comment]
I got the same error report: {"error":"invalid_grant"} Not sure how to resolve it.

**Comment by kishan92** [comment]
Getting the following error just like most others:

{"error":"invalid_grant","error_description":"authorization_code not found"}

Any pointers on this would be great

**Comment by kishan92** [comment]
In my case, this was due to the quick expiration of the code and hence when I generated the code quickly(within the span of 10 minutes) and used it to retrieve the access token, the issue was resolved. The [oauth website](https://www.oauth.com/oauth2-servers/authorization/the-authorization-response/#:~:text=The%20authorization%20code%20must%20expire,the%20codes%20should%20be%20documented) suggests the following:


"The authorization code must expire shortly after it is issued. The OAuth 2.0 spec recommends a maximum lifetime of 10 minutes,"

**Comment by rodriguez-rodrigo** [comment]
In my case i was able to solve this adding header content type, and property redirect

```
    const accessToken = await fetch(
      `${canvas_url}/login/oauth2/token`,
      {
        method: "POST",
        body: JSON.stringify({
          client_id: canvas_api_key,
          client_secret: canvas_api_secret,
          code,
          grant_type: "authorization_code",
          redirect_uri: config.backend,
        }),
        headers: {
          "Content-Type": "application/json",
        },
        redirect: "follow",
      }
    );
```
