### ISSUE TITLE
problem with docker-compose build

### ISSUE THREAD

**Issue by lvalladares** [instructure/canvas-lms#1052]
### Summary:

When i try to follow the instructions for docker developing using the docker-compose provided in this repo (cloned just today) i get an error and cant continue.

### Steps to reproduce:

 1. Clone the repository
 2. Follow the steps in here: https://github.com/instructure/canvas-lms/tree/stable/doc/docker
 3. On the second step (docker-compose run --rm web bash -c "bundle install") wait some time and you will get this error: ERROR: Service 'web' failed to build: unauthorized: authentication required

### Expected behavior:
It should create all the containers in order to work with canvas

### Additional notes:
A picture of the problem:
https://drive.google.com/file/d/0B30mnsjsqOliWVN0SUE3VHdrZzg/view?usp=sharing
Linux Mint
Kernel: 4.4.0-79-generic
Docker version 1.12.6, build 78d1802
docker-compose version 1.13.0, build 1719ceb

**Comment by tierra** [comment]
Looks like it stops right in the middle of downloading the base image. This image is hosted on Docker Hub, and doesn't require authentication, and if it did, it would have failed well before you managed to download the first 10 layers or so. If this isn't just a random network error (and it continues to fail at *exactly* the same spot in the middle of the download), I would suggest that you verify that your docker host has enough disk space available for the docker image.

**Comment by lvalladares** [comment]
Yeah sorry, youre right, this was caused by my internet connection, i didnt check that before posting. Im closing this but now im having this issue #1051
