### ISSUE TITLE
backup development content

### ISSUE THREAD

**Issue by dimitriacosta** [instructure/canvas-lms#1058]
Is there a way to backup what I have in my development environment and restore it in my production environment? I need to restore the theme I made and a couple of courses.

I tried backing up postgres and restoring in the production env but my custom theme doesn't work and some sections of the courses are not working at all

**Comment by dimitriacosta** [comment]
Never mind, I already found a way

**Comment by leasonliu** [comment]
Do you still remember how to backup and restore? I have the same requirement now.
