### ISSUE TITLE
Problems with adding an image to a course card.

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#1059]
Hello Canvas LMS community,

When I try to updated the image of my course as it shown here: 
https://community.canvaslms.com/docs/DOC-10097

I got next error:
"There was an error uploading image"
https://www.screencast.com/t/7myHuLx9YY

The most interesting parts of the problem are:
- there are no any errors at the Canvas's LMS production.log file
- the image file uploads to the canvas and appears at the "File" section under "course_image" folder:
https://www.screencast.com/t/S5GUKu5011

In general the issue is related to this post:
https://community.canvaslms.com/thread/15297-problems-uploading-photo
that is why I have truied to use the latest version of Chrome, Safari, Opera, Firefox and Explorer browsers without luck.

The canvas LMS version: origin/stable/2017-06-03

Thanks.

**Comment by shawniverson** [comment]
Looks like https://github.com/instructure/canvas-lms/issues/1064

**Comment by ally1** [comment]
Hello @shawniverson,
Yes you are right, the #1059 and #1064 are the same issue.

**Comment by ally1** [comment]
Hi there,

The issue was resolved in #1064. 
Closed this thread as solved.
