### ISSUE TITLE
Production Start Guide Installation: Results in displaying a directory in the browser

### ISSUE THREAD

**Issue by denslova** [instructure/canvas-lms#1065]
### Summary:
I followed all the production guide steps and in the final step after restarting apache, I get a directory when I navigate in the browser to the server domain: [canvas.fxlongterm.com]
[https://cdn.pbrd.co/images/3D7XkfOug.png]
As I understand I am meant to see a log-in page for admin to login. Please help, I have installed it twice with the same result. 
Daemonising process is running:
sudo /etc/init.d/canvas_init start
Delayed jobs running, pool PID: 31953

Virtual machine on google cloud: Ubuntu 14.04.5 (trusty)
The display in the browser:
Index of /

[ICO]	Name	Last modified	Size	Description
[TXT]	422.html	2017-07-01 02:05	930	 
[TXT]	500.html	2017-07-01 02:05	2.5K	 
[   ]	_crossdomain.xml	2017-07-01 02:05	101	 
[IMG]	apple-touch-icon.png	2017-07-01 02:05	5.8K	 
[DIR]	assets/	2017-07-01 02:37	-	 
[TXT]	dimdim_welcome.html	2017-07-01 02:05	1.3K

**Comment by shawniverson** [comment]
Sounds to me that Passenger is either not installed, enabled, or running.

**Comment by denslova** [comment]
Thanks, @shawniverson 
Passenger is installed, however, when I manually start it I get some error that "/home/[user]/public/index.html" is not found (2: No such file or directory), I am not sure why it is requesting home/user/public/index.html when the production guide directs to install canvas as sudo into /var/canvas. Currently, the /var/canvas/public directory without any index.html inside is served by Apache. What should I do?

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
2017/07/02 13:37:12 [error] 2334#0: *4 "/home/[user]/public/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: _, request: "HEAD / HTTP/1.1", host: "0.0.0.0"
[ 2017-07-02 13:37:14.0390 2318/7f965e937700 age/Cor/SecurityUpdateChecker.h:356 ]: Security update check: no update found (next check in 24 hours)

**Comment by denslova** [comment]
I reinstalled passenger and I got the /login/canvas, thank you @shawniverson  
I also ran a validation sudo /usr/bin/passenger-config validate-install for passenger and apache2 which gave green ticks.
