### ISSUE TITLE
Unknown Client Trying to use Google Apps LTI on Latest Stable

### ISSUE THREAD

**Issue by shawniverson** [instructure/canvas-lms#1067]
### Summary:
When trying to register the LTI at https://google-drive-lti-iad-prod.instructure.com, the following message appears when attempting to authorize Google Drive:

```
while(1);{"error":"invalid_client","error_description":"unknown client"}
```

### Steps to reproduce:

 1.  Set up a Canvas LMS Instance using latest stable
 2.  Add Google Apps LTI (https://www.eduappcenter.com/apps/641#.WVf3MogrI2x)  
 3.  Browse to Google Drive in Course on Navigation Panel and click Authorize

### Expected behavior:
Google should present an oAuth prompt.

### Additional notes:
URL:  https://canvas.rushville.k12.in.us/login/oauth2/auth?client_id=170000000000401&redirect_uri=https%3A%2F%2Fgoogle-drive-lti-iad-prod.instructure.com%2Fcanvas_users%2Fauth%2Fcanvas%2Fcallback&response_type=code&state=<redacted>

**Comment by shawniverson** [comment]
As evidenced with the https://community.canvaslms.com/docs/DOC-4473 for Canvas Commons, the LTI Provider would need a way to know a developer ID and Key of the instance, since the client_id 170000000000401 is foreign to a self-hosted instance and appears to be specific to instructure.com.

So, the question then becomes, will Instructure allow us self-hosted folks to register a developer ID and Key to use the LTI?

**Comment by shawniverson** [comment]
According to my sources, just for reference in case anyone runs across this, the answer is no.

**Comment by joehobson** [comment]
Very disappointing. Any plans for Instructure to expand this to the open source community? Or maybe Google has a universal LTI app that works with all LMSs?

**Comment by Revelation1714** [comment]
Any movement on this?
I know this thread is little old, but I am running into similar issue. When I click Configure on step 19 in [this PDF](http://www.peru.k12.in.us/canvaslti/InstructureSelfHostedCanvasCommonsSetup.pdf), I am getting this error:
Configuration Error
Sorry, there is a problem in your Canvas/Commons configuration.
Please notify your Canvas administrator.

There appears to be several self-hosted instances that got this working.

**Comment by joehobson** [comment]
@Revelation1714 I don't think it's possible to use the Instructure Google LTI with self-hosted Canvas. We worked with some developers to create an OSS Google Drive connector which is working fairly well on a few self-hosted Canvas systems that we manage -- https://github.com/learningtapestry/canvas-google-drive-connector
