### ISSUE TITLE
Invalid Windows Characters in File Names

### ISSUE THREAD

**Issue by CreepyGnome** [instructure/canvas-lms#1070]
There are three files with colons in their names end up not being written to a Windows computer. Windows computers should be able to clone a valid environment to edit source on to push to a linux based docker environment. 

canvas-lms/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/
urn:RespondusAPI.rb
urn:RespondusAPIMappingRegistry.rb
urn:RespondusAPIServant.rb

When files are cloned to a Windows system all invalid characters are stripped from file names. So the files above just become a single file "urn" which has a length of zero. 

Git sees the files as deleted and wants you to commit the changes to delete them from source, and it sees the new file urn as new and wants it to be added.

It would be nice if this could be fixed so that the colon was just removed from the file name or replaced with a hyphen or underscore.

**Comment by tierra** [comment]
I have submitted a change to fix this internally, and it's being reviewed now.

**Comment by CreepyGnome** [comment]
When will stable be updated to include to fix this breaking issue once its approved?

**Comment by tpickett66** [comment]
@CreepyGnome I'll check with our QA department about getting it pulled into our 7-15 release (currently the beta branch) which will get promoted to stable at the end of the week.

**Comment by tpickett66** [comment]
Our QA team has declined to pick it onto the beta branch citing insufficient test coverage in that part of the code. It is on the master branch if you wan to develop against it.

**Comment by CreepyGnome** [comment]
@tpickett66 that would be great thanks
