### ISSUE TITLE
Preview Your Changes Error

### ISSUE THREAD

**Issue by anup2017** [instructure/canvas-lms#1071]
![screenshot from 2017-07-06 11-25-52](https://user-images.githubusercontent.com/26286192/27899901-bd1ec88a-6249-11e7-99e9-d9e024a8435a.png)

Whenever i'm trying to change the color , uploading css ,  or change image the progress bar stop proceeding 

![screenshot from 2017-07-06 11-27-30](https://user-images.githubusercontent.com/26286192/27899945-eb3d9b06-6249-11e7-9f27-a50030a31738.png)

**Comment by shawniverson** [comment]
Usually permissions related.

What user are Passenger and delayed jobs running as?

Does this user have write access to the following areas?

app/stylesheets/brandable_css_brands
app/stylesheets/_brandable_variables_defaults_autogenerated.scss
public/dist/brandable_css
