### ISSUE TITLE
Cassandra db:migrate fail with exception undefined method `db' for nil:NilClass when referencing cassandra.db

### ISSUE THREAD

**Issue by breiter** [instructure/canvas-lms#1072]
### Summary:
Running the rake db:migrate task fails with Cassandra 3.11.

### Steps to reproduce:

 1. Install Cassandra 3.11. 
 2. Configure `conf/cassandra.yml`
 3. Add analytics repo to `gems/plugins/analytics`
 3. run `RAILS_ENV=production bundle exec rake db:migrate`

Canvas is commit 58e4df2.

### Expected behavior:

Migration proceeds without error.

### Additional notes:

What actually happens is an exception thrown out of the `self.runnable?` method of [`db/migrate/20140224212705_remove_cassandra_page_views_contributed.rb`](https://github.com/instructure/canvas-lms/blob/stable/db/migrate/20140224212705_remove_cassandra_page_views_contributed.rb) on this line:

```
server_version = cassandra.db.connection.describe_version()
```

NoMethodError: undefined method `db' for nil:NilClass

```
RAILS_ENV=production bundle exec rake db:migrate
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
1: production:public
rake aborted!
NoMethodError: undefined method `db' for nil:NilClass
/opt/var/canvas/db/migrate/20140224212705_remove_cassandra_page_views_contributed.rb:30:in `runnable?'
/opt/var/canvas/config/initializers/active_record.rb:1196:in `runnable?'
/opt/var/canvas/config/initializers/active_record.rb:1230:in `select'
/opt/var/canvas/config/initializers/active_record.rb:1230:in `runnable'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:72:in `block (6 levels) in shardify_task'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:72:in `each'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:72:in `block (5 levels) in shardify_task'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/database_server.rb:99:in `unshackle'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:71:in `block (4 levels) in shardify_task'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:372:in `block (2 levels) in with_each_shard'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:584:in `block in activate'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:86:in `activate'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:583:in `activate'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:370:in `block in with_each_shard'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:366:in `with_each_shard'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:66:in `block (3 levels) in shardify_task'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/database_server.rb:99:in `unshackle'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:63:in `block (2 levels) in shardify_task'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/shackles.rb:22:in `activate'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:62:in `block in shardify_task'
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by jenseng** [comment]
@breiter have you run the `CREATE KEYSPACE ...` commands described in config/cassandra.yml.example? If the keyspaces don't exist, migrations will fail with the error you posted.

Note that cassandra 3+ is not officially supported for canvas, so there could also be something else going on here.

**Comment by lukfugl** [comment]
As Jon says there could certainly still be issues with cassandra 3+ that I'm not aware of, but that doesn't appear to the the issue here. Tracing through the code, it appears that `Canvas::Cassandra::DatabaseBuilder.from_config('page_views')` is returning nil unexpectedly. The most likely cause of that is if your `config/cassandra.yml` doesn't have a key for the `page_views` database. If it does have that configured, it shouldn't be returning nil without at a minimum printing an error to the Rails.logger.

**Comment by lukfugl** [comment]
Actually, we got past the migration's `runnable?` check, which would have confirmed `Canvas::Cassandra::DatabaseBuilder.configured?('page_views')` is true. So I'm guessing you do have it configured.

The likely error in that case is then that [lib/canvas/cassandra/database_builder.rb:50](https://github.com/instructure/canvas-lms/blob/stable/lib/canvas/cassandra/database_builder.rb#L50) is raising an error, probably due to Cassandra 3+, and so line 53 is returning nil. If so, there should be an error in your rails log (surprised it didn't go to STDOUT, too) starting with `Failed to create cassandra connection`.

**Comment by breiter** [comment]
I do have the page_views key in the yml file and I created the keyspaces. 

What is a stable version of Cassandra that is expected to work? I assumed current stable was appropriate but it sounds like it isn't.

**Comment by breiter** [comment]
I tried downgrading to cassandra 22x and still had the same issue. This entry in `canvas/log/production.log` pointed me to the solution to the issue.

>  SQL ActiveRecord::SchemaMigration Load (0.6ms)  SELECT "schema_migrations".* FROM "schema_migrations"  [production:1 deploy]
> [- -] Failed to create cassandra connection for ["page_views", "production"]: No live servers in [#<ThriftHelpers::Server:0x0000001003d058 @connection_string="127.0.0.1:9160", @client_class=CassandraCQL::Thrift::Client, @options={:protocol=>Thrift::BinaryProtocol, :protocol_extra_params=>[], :transport=>Thrift::Socket, :transport_wrapper=>Thrift::FramedTransport, :raise=>true, :defaults=>{}, :exception_classes=>[IOError, Thrift::Exception, Thrift::ApplicationException, Thrift::TransportException], :exception_class_overrides=>CassandraCQL::Thrift::InvalidRequestException, :retries=>0, :server_retry_period=>1, :server_max_requests=>nil, :retry_overrides=>{}, :wrapped_exception_classes=>[Thrift::ApplicationException, Thrift::TransportException], :connect_timeout=>5, :timeout=>1, :timeout_overrides=>{}, :cached_connections=>false}, @cached=false, @marked_down_til=2017-07-26 11:48:48 +0000, @connection=#<ThriftHelpers::Connection::Socket:0x0000000ff697d0 @transport=#<Thrift::FramedTransport:0x0000000ff69438 @transport=#<Thrift::Socket:0x0000000ff69550 @host="127.0.0.1", @port=9160, @timeout=5, @desc="127.0.0.1:9160", @handle=nil>, @rbuf="", @wbuf="", @read=true, @write=true, @index=0>, @transport_wrapper=Thrift::FramedTransport, @server="127.0.0.1:9160", @timeout=5>, @client=nil>].

The story is that the Thrift protocol RPC listener is not running by default, even though Cassandra is running and accepts connections from `nodetool` and `cqlsh`. That means it is not listening on port 9160 for rpc connections. The solution is to edit `/etc/cassandra/cassandra.yml` and set `start_rpc: true` then restart the cassandra service.

Once that is done,  the `bundle exec rake db:migrate` task completes without an issue.

**Comment by swforeman** [comment]
I am having a similar issue, but I get a connection. I get the following error in my production log file "Failed to create cassandra connection for ["page_views", "production"]: You have not logged in". Do I need to define user and password credentials in the cassandra.yml file?

**Comment by akshay-monadinfotech** [comment]
@breiter work for me thanks
