### ISSUE TITLE
People of Mozilla has been retired the woff-code-latest.zip file not available 

### ISSUE THREAD

**Issue by CreepyGnome** [instructure/canvas-lms#1073]
The people.mozilla.org and its forwarded domain people-mozilla.org have been retired by Mozilla which you have hard coded download linked in your docker files.

Asked them on Twitter and here is their reply informing me they retired it.
https://twitter.com/asadotzler/status/883045941170774016

This URL:
https://people-mozilla.org/~jkew/woff/woff-code-latest.zip

Is hard coded in these two files:

 instructure/canvas-lms/Dockerfile
 instructure/canvas-lms/build/Dockerfile.template

It was causing some issues when the site went down yesterday, and as a temporary workaround I just pointed it to:

http://pkgs.fedoraproject.org/repo/pkgs/woff/woff-code-latest.zip/1dcdbc9a7f48086185740c185d822279/woff-code-latest.zip

However, that is from 2009 and I am not sure if the one you were using was newer or not.

**Comment by tierra** [comment]
We've actually already merged a fix for this on the master branch (902fca8)

**Comment by CreepyGnome** [comment]
Okay we are only running from stable, when will stable be updated to include to fix this breaking issue?

**Comment by ccutrer** [comment]
Our normal release schedule is 3 weeks between branching the next release from master, and it becoming the new stable branch. So depending on timing of commits, it could take between ~3 (if submitted just before a branch) and ~6 (if submitted just after a branch) weeks between a commit being submitted, and it being on stable.  The next branch occurs on July 17.

**Comment by CreepyGnome** [comment]
Thanks @ccutrer  for the details that is great to know!!

**Comment by wget** [comment]
For those of you falling on this link after some Google-fu researches, I revived the sfnt2woff project at https://goo.gl/d4uZbb

**Comment by ng-0** [comment]
@wget Another option is Debian as a down-upstream: https://packages.debian.org/source/sid/woff-tools
Or do you intend to work on woff?

**Comment by wget** [comment]
@ng-0 I plan to fix a few issues with it yes.
