### ISSUE TITLE
CSS file for mobile login page issue.

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#1074]
### Summary:
Hello,

I am trying to upload a CSS file for mobile login page (custom.css) 
.html#a {
background-image: none !important;
}

Changes applied well for custom desktop css but not for custom mobile css.
Thanks for any help.

**Comment by ccutrer** [comment]
I'm not sure how well documented it is, but the CSS for mobile applies only to using the API for fetching content (such as mobile apps use), not to mobile browsers. If you want to target special styling for your mobile browsers, you should use a media query in your regular CSS file.

**Comment by agsdot** [comment]
Thanks for the insight there: "If you want to target special styling for your mobile browsers, you should use a media query in your regular CSS file."
