### ISSUE TITLE
undefined method `shard' for #<Object:0x000000112ec8e8>

### ISSUE THREAD

**Issue by jakesorce** [instructure/canvas-lms#1082]
### Steps to reproduce:

 1. rebased to the latest code on origin/stable
 2. ran through the Production Start guide to get stuff all setup
 3. running db:migrate or db:initial_setup throws the error
 4. also when refreshing the server all I see is the file index of public not the site

### Expected behavior:
1. db:migrate to succeed
2. site to render

### Additional notes: screenshots attached
<img width="840" alt="screen shot 2017-07-26 at 9 25 32 pm" src="https://user-images.githubusercontent.com/801470/28653178-5714a27a-7249-11e7-99d8-fab4bf54a84e.png">
<img width="1680" alt="screen shot 2017-07-26 at 9 28 21 pm" src="https://user-images.githubusercontent.com/801470/28653183-5dea293a-7249-11e7-809e-63f9d137ce50.png">

**Comment by simonista** [comment]
Hey @jakesorce, sorry for never responding to this.  I've run `db:initial_setup` recently without issue, so I don't think this is a problem anymore.
