### ISSUE TITLE
Error on delayed_job: SessionPersistenceToken.delete_all

### ISSUE THREAD

**Issue by fred-bict** [instructure/canvas-lms#1083]
Error on delayed_job: SessionPersistenceToken.delet_all
wrong number of arguments (given 1, expected 0)

Steps to reproduce:
 1. start $ RAILS_ENV=production script/canvas_init start 
 2.

Additional notes:
Table session_persistence_tokens is empty.

![canvas delayed_job sessionperstencetoken](https://user-images.githubusercontent.com/9447563/28676913-462d1732-72ec-11e7-8ff0-862b506c5970.png)

**Comment by simonista** [comment]
Hi @fred-bict, thanks for the report, this is fixed in 507b2c3d3da28fd038b40b59e5f099d3563f614e!
