### ISSUE TITLE
Location of canvas login page

### ISSUE THREAD

**Issue by jatinparmar11** [instructure/canvas-lms#1088]
I have setup canvas lms and now would like to remove the instructure logo from login page.

How it can be done?

Would you please assist me?

**Comment by grahamb** [comment]
Hi @jatinparmar11! Canvas allows you to customize the login page, as well as a ton of other theming options. You can find this at http[s]://yourcanvas/accounts/default/brand_configs. See https://community.canvaslms.com/docs/DOC-10891-4214418311 for the official documentation.

Note that the theme editor doesn't affect the mobile version of the login page; if you want to monkey with that, you'll need to [enable custom JS & CSS](https://community.canvaslms.com/docs/DOC-10862-4214724282) on your installation, and create and upload (through the theme editor) a custom CSS file that overrides the `#f1_container { background-image }` property.

Good luck!

**Comment by sdb1228** [comment]
Hey @jatinparmar11 Looks like @grahamb gave you a good start! Let us know if you still experience issues!
