### ISSUE TITLE
Teachers cannot add people to the course

### ISSUE THREAD

**Issue by Bicet** [instructure/canvas-lms#1089]
### Summary:
After building from latest git. As teachers, we can no longer add students to the course.

### Steps to reproduce:

 1. Be a teacher
 2. Add a student by email
 3. An error like in screen-teacher appear
<img width="784" alt="screen-teacher" src="https://user-images.githubusercontent.com/265162/28813465-a29618ec-7699-11e7-93f3-e5abe5344fbf.png">

### Expected behavior:
A screen like screen-admin should appear
<img width="779" alt="screen-admin" src="https://user-images.githubusercontent.com/265162/28813477-b18d417c-7699-11e7-9d2f-048bc1d3cd66.png">

### Additional notes:

**Comment by Bicet** [comment]
Was it fixed?

**Comment by sdb1228** [comment]
Hey @Bicet This should be fixed on master.  Please let us know if you are still experiencing this problem and we can reopen.
