### ISSUE TITLE
FAQ states Commercial Licensing and Professional Services are Available and apparently this is not the case

### ISSUE THREAD

**Issue by CreepyGnome** [instructure/canvas-lms#1091]
I was reading your FAQ page:

https://github.com/instructure/canvas-lms/wiki/FAQ

And I then clicked the "our website" link under the pro services and support question.  Then used your contact form on your Instructure site. I inquired about support and licensing options and was told you have no support or licensing for the open source Canvas LMS. That all paid services are only via the hosted solution.

If this is true that you do not offer these things, I would recommend changing the following questions responses.

What open-source license is Canvas released under?
-I would remove the note that states you sell commercial licenses as well, and replace it with a mention that you offer a paid hosted solution, as you do not provide commercial licenses for the open source version.

How do I get professional services and support?
-I would just change the answer to be no, and point people to your paid hosted solution.

HOWEVER, if these statements are true in the FAQ I would suggest educating the people who respond to your inquiries from your contact page on your main site or provide a direct form that can be filled out about getting specific details about it. As I would be interested in learning more about your commercial licensing options for the open source Canvas LMS and professional service engagement rates.

**Comment by jimmynwade** [comment]
Or at least add a footnote that says "Commercial support for open source Canvas LMS only available if you are Simon Fraser University."

**Comment by jimmynwade** [comment]
Won'tfix? Really? It's an FAQ. Is it really so difficult to make clarifying changes?

**Comment by ccutrer** [comment]
@jimmynwade : no, it's not difficult to update the FAQ, and I have done so. Apparently this ticket got missed when it was originally filed. And I have no idea why even stalebot ignored it for two years.
