### ISSUE TITLE
Canvas loads image over http even when loaded over https

### ISSUE THREAD

**Issue by newperson1746** [instructure/canvas-lms#1093]
### Summary:
While using canvas (loaded over https), and after logging in, a certain image (/images/messages/avatar-50.png) is loaded over http, and viewing the source of the generated html page confirms that the image url uses http.
### Steps to reproduce:

 1. Login to canvas with any username
 2. Notice that there is no green secure bar in google chrome (and there is a gray i to tell you that not all resources were loaded securely), or that there is no lock in safari, even though they both show their respective "100% loaded with https" icon in the login page.
 3. Confirm that the image was loaded over http by checking the html source and finding the url
 "img src="http://(url-to-canvas)/images/messages/avatar-50.png" alt="Admin" /> or using the chrome developer console and looking for the warning "Mixed Content: The page at XXXX was loaded over https, but requested an insecure image '<image_url>'"

### Expected behavior:
All page resources are loaded via https, and browsers show the appropriate icon indicating that all resources were loaded securely.
### Additional notes:
I am running canvas on macOS Sierra 10.12.3 with ruby 2.4.1, passenger 5.1.7, and nginx 1.13.3 compiled from source. ssl: true is specified in domain.yml under production.

**Comment by grahamb** [comment]
Hi @newperson1746. This isn't exected behaviour, and I can't replicate it on my self-hosted site. avatar-50.png is loading over HTTPS for me.

<img width="1049" alt="screen shot 2017-08-25 at 15 50 20" src="https://user-images.githubusercontent.com/146111/29734054-69021758-89ad-11e7-864c-1ff9bb51d589.png">
<img width="781" alt="screen shot 2017-08-25 at 15 51 20" src="https://user-images.githubusercontent.com/146111/29734055-690330f2-89ad-11e7-87a6-32b0e3869222.png">

All of the references to `avatar-50.png` in the Canvas code refer to it with relative URLs (`/images/messages/avatar-50.png`), not absolute. 

Couple of questions for you:

- What Canvas release are you running?
- Did you previously have `ssl: false` in your domain.yml file? If so, it's possible that views cached in Redis have the old HTTP url set. If so, you can try flushing your redis cache (kill redis and restart, or connect with `redis-cli` and issue a `FLUSHALL` command.

**Comment by newperson1746** [comment]
Yes, you had put a command to clear the passenger cache (I don't remember it) and that fixed it. It is no longer in your comment, but whatever it was, it fixed it. I had to reinstall canvas and am facing a different issue, but it fixed the http issue here. Thanks! I think that it would be useful for other users to have the command to clear the cache as the answer here, but I don't remember it.

**Comment by juniorb2ss** [comment]
Hello.

I have the same problem. I am using docking, s3 and cloudfront.

When accessed on the platform, the content is mixed because some URLs are generated in the http environment at the https address.

Solutions?

**Comment by hsuperman** [comment]
Hi, how did you guys resolve this?  I'm facing the same issue with the avatar image.  In addition, /dashboard-sidebar is loaded over https as well.

I'm using Cloudfront for the SSL, wondering if that could be a factor

**Comment by juniorb2ss** [comment]
@hsuperman 

I had the same problem using the cloudfront for ssl.

Canvas see the header x_forwarded_proto to estabilish ssl connection.

But, cloudfront remove this header from request, and put the header CloudFront-Forwarded-Proto

I fix this problem put a nginx in front to make forward proxy with x_forwarded_proto header.

CloudFront (same protocol) > nginx (with header x_forwarded_proto[https)(443 or 80) > canvas application (80)
