### ISSUE TITLE
No Documentation On Running Canvas Tests

### ISSUE THREAD

**Issue by CreepyGnome** [instructure/canvas-lms#1094]
I cannot find any documentation on running your various tests you have for Canvas LMS.  I see several rake tasks and files related to tests, CI/CD and so forth but I have not been able to get them to run reliably almost all of them always fail. 

If you have documentation someplace that I have not found please let me know I would appreciate it, if not I would love to know how do run all your tests against the stable branch of this repository.

I reason why we or anyone would want to do this is if they are making changes and want to make sure they do not break anything that already exists. This would be good to know for some who may be planning to makes a pull request for a feature or bug. Would be great to have documentation on around it.

Also is do Unit Tests exist and Integration tests or are they all just Integration Tests? If there is a separation how can only one set or the other or all be ran?

**Comment by grahamb** [comment]
Hi @CreepyGnome! I believe that improving the test suite for open-source users is something Instructure is currently working on. @omarkhan, can you add anything?

**Comment by omarkhan** [comment]
Sorry for the late reply @CreepyGnome! Up until recently our tests relied on some proprietary plugins to pass, but they should now pass without any plugins installed. We are adding a 'no plugins' build to our CI to prevent this from happening again.

Try downloading a fresh clone of canvas-lms (master branch, not stable), and following the instructions in [doc/docker/developing_with_docker.md](https://github.com/instructure/canvas-lms/blob/stable/doc/docker/developing_with_docker.md).

Let us know if you find any tests that are still failing!
