### ISSUE TITLE
Student User : Courses home page is breaking

### ISSUE THREAD

**Issue by AbithaVek** [instructure/canvas-lms#1096]
### Steps to reproduce:

 1. Log in as Student
 2.Click on any course from dashboard
 3.Courses Home page is breaking and giving error.

### Expected behavior:
The courses home page must display the information of the course
### Additional notes:
All other links of the course is loading only the home page is not working.

**Comment by tierra** [comment]
@AbithaVek Can you provide any more details about the issue? What error do you see? Is this self-hosted Canvas, and if so, what version are you running? What browser are you using? Is there anything special about the course you're trying to load that we should know? (do you know if it's course home page is set as the modules list, wiki page, assignments list, or something else?

**Comment by srinivasanlr** [comment]
Hi Tierra,

@tierra : Attached the Error page ScreenShot for Reference , we could see the "500 Interval Server" when we do Inspect Element.

**Answers for your Question :**
1. Yes this is self-hosted Environment.
2.we are using Chrome , Mozilla Firefox.
3.There is No special about course , we just created a Course and it doesn't have any content.
4.Please let us know how to identify the Version of the Canvas running?

![student_view_error](https://user-images.githubusercontent.com/31071950/29369611-155a74f8-8271-11e7-914e-975a4630a490.png)

Regards
sri

**Comment by tierra** [comment]
For self-hosted, you should be able to access `/error_reports` in your URL to see the error in more detail. That would help out immensly here.

For version, I'm mostly asking if you have a certain release tag deployed, or maybe you're running the `stable` branch, or possibly (though not recommended) running the `master` branch.

**Comment by srinivasanlr** [comment]
Hi Tierra,

Thanks for your reply , we got the below Error from the /error_reports  page  , Please guide us to fix this.

account: Companyname
category: PG::UndefinedTable
created at: 2017-08-16 15:30:00 -0600
user: srinivasan
request context id: dc19639c-3cb5-4fd7-bc20-9281c4ebdb1d

HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
HTTP_ACCEPT_ENCODING: gzip, deflate, br
HTTP_HOST: URL of the Envrionment
HTTP_REFERER: URL of the Envrionment/?login_success=1
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
PATH_INFO: /courses/234
QUERY_STRING: ?
REMOTE_ADDR: 198.176.80.34
REQUEST_METHOD: GET
REQUEST_URI: URL of the Envrionment/courses/234
SERVER_NAME: URL of the Envrionment
SERVER_PORT: 443
SERVER_PROTOCOL: HTTP/1.1
format: text/html
hostname: ip-10-179-157-34
path_parameters: {:controller=>"courses", :action=>"show", :id=>"234"}
pid: 19823
query_parameters: {}
request_parameters: {}
response_code: 500
type: 

 ERROR:  relation "submission_comment_participants" does not exist
LINE 3:                 FROM "submission_comments", "submission_comm...
         ^
 /var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/sharded_instrumenter.rb:20:in `instrument'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/active_record/abstract_adapter.rb:37:in `log'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/active_record/query_cache.rb:58:in `block in select_all'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/active_record/query_cache.rb:92:in `cache_sql'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/active_record/query_cache.rb:58:in `select_all'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/querying.rb:39:in `find_by_sql'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation.rb:639:in `exec_queries'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/shackles/relation.rb:11:in `exec_queries'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation.rb:515:in `load'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation.rb:243:in `to_a'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/call_super.rb:12:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/call_super.rb:12:in `call_super'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/active_record/relation.rb:53:in `block in to_a'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/active_record/relation.rb:77:in `activate'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/active_record/relation.rb:53:in `to_a'
/var/canvas/app/models/user.rb:1898:in `block (3 levels) in submissions_for_context_codes'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/lib/switchman/shackles.rb:22:in `activate'
/var/canvas/app/models/user.rb:1871:in `block (2 levels) in submissions_for_context_codes'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:299:in `block in fetch'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:585:in `block in save_block_result_to_cache'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:547:in `block in instrument'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:547:in `instrument'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:584:in `save_block_result_to_cache'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:299:in `fetch'
/var/canvas/app/models/user.rb:1868:in `block in submissions_for_context_codes'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/app/models/switchman/shard_internal.rb:584:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/app/models/switchman/shard_internal.rb:85:in `activate'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/switchman-1.9.5/app/models/switchman/shard_internal.rb:583:in `activate'
/var/canvas/app/models/user.rb:1867:in `submissions_for_context_codes'
/var/canvas/app/models/user.rb:1919:in `recent_feedback'
/var/canvas/app/controllers/courses_controller.rb:1704:in `show'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/var/canvas/app/controllers/application_controller.rb:364:in `block in enable_request_cache'
/var/canvas/lib/temp_cache.rb:7:in `enable'
/var/canvas/app/controllers/application_controller.rb:363:in `enable_request_cache'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/var/canvas/app/controllers/application_controller.rb:357:in `set_locale'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
/var/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:61:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/canvas/app/middleware/request_throttle.rb:59:in `block in call'
/var/canvas/app/middleware/request_throttle.rb:257:in `reserve_capacity'
/var/canvas/app/middleware/request_throttle.rb:54:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
/var/canvas/app/middleware/request_context_session.rb:25:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
/var/canvas/app/middleware/load_account.rb:12:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:22:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
/var/canvas/app/middleware/request_context_generator.rb:49:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
/var/canvas/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/var/canvas/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by tierra** [comment]
It sounds like you're running old code with newer migrations. The missing table was intentionally removed around May/June. You should verify that you're running the same (up-to-date) code on all servers.

**Comment by srinivasanlr** [comment]
Hi Tierra,

submission_comment_participants is the table that we are missing? Pls let me know.

https://github.com/instructure/canvas-lms ---> Is this the place where we can get latest Code?

**Comment by tierra** [comment]
Yes, you should ensure that all servers are running the latest `stable` branch. Here's a guide for upgrading:
https://github.com/instructure/canvas-lms/wiki/Upgrading

**Comment by AbithaVek** [comment]
hello tierra we are able to get the course home page after upgrading the code. Thank you for the information.Appreciate it!!

**Comment by AbithaVek** [comment]
hello tierra apologies to open this up!! We have a couple of questions. And since its related to same topic  I am continuing the same thread.
We could still the tables submission_comment_participants in the database after downloading the packages though its not giving error. Can you please let us know about this?

Is there a way we can find the release tag before deploying so that we can keep tracking it.

Thanks!!

**Comment by tierra** [comment]
> We could still the tables submission_comment_participants in the database after downloading the packages though its not giving error. Can you please let us know about this?

Have you run the database migrations, and were they completed successfully?

> Is there a way we can find the release tag before deploying so that we can keep tracking it.

Rather than doing a git reset on `origin/master`, you can do this with any of the git release tags:
https://github.com/instructure/canvas-lms/releases

**Comment by srinivasanlr** [comment]
Hi tierra,

You are asking from the below URL , whethere the Databas Migrations Commands has been ran successfully or not? is that right .

 https://github.com/instructure/canvas-lms/wiki/Upgrading

Database migrations :
Often, there is some minor database migration that needs to happen for all of the latest Canvas features to work. There is a built in Rails command to do this:

$GEM_HOME/bin/bundle exec rake db:migrate
If you are running a production environment, you will probably want to specify that. In addition, to ensure less downtime, you can run "predeploy" migrations (changes to schema required for the new version, but backwards compatible with old, currently running code) separately prior to rolling the code out to your full production environment.

<from a location with access to the production database, but not currently serving web requests or running jobs>
RAILS_ENV=production $GEM_HOME/bin/bundle exec rake db:migrate:predeploy
<deploy new code to running web servers and job servers>
RAILS_ENV=production $GEM_HOME/bin/bundle exec rake db:migrate

**Comment by srinivasanlr** [comment]
Hi Tierra
Any updates/inputs on this would be most welcome.

**Comment by jenseng** [comment]
@srinivasanlr, yes you need to run the database migration commands as outlined on that page. If you haven't done that, or if they did not complete successfully, you will likely continue to see that error.

**Comment by jenseng** [comment]
Just to clarify; every time you update the code, you should ALWAYS run the database migrations, otherwise parts (or all) of Canvas may not work

**Comment by srinivasanlr** [comment]
Thanks Jenseng for the info.

**Comment by potru** [comment]
Hi,
 i'am having problem with outgoing emails from canvas lms from an instance of AWS. i detail the configuration file:
production:
   address: "email-smtp.us-east-1.amazonaws.com"
   port: "25"
   tls: "true"
  delivery_method: "sendmail"
  user_name: "xxxx@xxx.com"
  password: "password"
  authentication: "plain" # plain, login, or cram_md5
  domain: "ip-x.x.x"
  outgoing_address: "xxxx@xxx.com"
  default_name: "Canvas"

Here i given username and password of my own canvas site details.
domain name was ip address of my instance
And delayed jobs also running but it's giving error like 

Net::OpenTimeout - execution expired 

SMTP port 25 is enabled but when i tried with telnet to smtp  cannot connecting 
$telnet email-smtp.us-east-1.amazonaws.com 25
Trying 54.221.247.194...

We are not able to send an emails from my canvas site.  Any ideas why i am not able to send an email.

Thanks,
Suresh
