### ISSUE TITLE
Uploading profile picture 

### ISSUE THREAD

**Issue by AbithaVek** [instructure/canvas-lms#1097]
### Summary
Not able to upload avatar image. Not able to upload image in the profile picture.When trying to upload the page hangs up.
### Steps to reproduce:

 1.Log into Canvas Application
 2.Click on settings
 3.Upload a Profile Picture
Any help is appreciated!!
### Expected behavior:
The picture should be uploaded
### Additional notes:
This is a self hosted cloud application

**Comment by claydiffrient** [comment]
@AbithaVek Are you using the local storage option?  or are you using S3 as your files backend?

If you are using local storage there is a known issue where uploads fail.  See #1011 and  #945 for more information.

**Comment by AbithaVek** [comment]
hello claydiffrient we are using s3

**Comment by beniamerican** [comment]
+1
