### ISSUE TITLE
Issue with the Home work submission placement

### ISSUE THREAD

**Issue by arunkottol** [instructure/canvas-lms#1099]
### Summary:

Canvas LMS does not seem to honor the URL specified under homework_submission placement.

### Steps to reproduce:

1. Go to Course -> Settings -> App

2. Click View App Configurations  -> Click  +App button.

3.  Select Configuration type as "Paste XML".

4. Add the required parameters. Paste your XML in the XML Configuration text area, (Here is a snippet of the XML I use. Note that it has a "homework_submission" placement and a "course_navigation" and the primary _**_**blti:launch_url**_**_ specified)

5. The course navigation link appears on the left.  Click this link and the correct URL specified under the "course_navigation" placement launches as expected.

6. Click Assignments and create a new Assignment.  Add the required information. Under the "**Submission Type**" use External tool and select the tool added in the steps above.

7. Click the newly created Assignment.  The URL specified under **_blti:launch_url_** launches.

### Expected behavior: 
The URL specified under "homework_submission" placement should launch.

### Additional notes:

I hope that the issue and the replication steps are clear.  I have observed this behavior both on Canvas.instructure.com and a custom installation on Canvas LMS.

**Comment by smakagon** [comment]
@arunkottol could you provide XML snippet you use for configuration?

**Comment by arunkottol** [comment]
Hello @smakagon  Attached is the complete LTI APP XML that I use. As indicated, when I try to set the homework submission to an external tool in my assignment, the link that shows up is the primary blti:launch_url and not the home work submission URL. Thanks for your help.
[sample_lti.txt](https://github.com/instructure/canvas-lms/files/1561612/sample_lti.txt)

**Comment by rivernate** [comment]
@arunkottol I just tried out the sample XML you provided. The homework_submission launch for me was going to "https://mydomain.com/assignment" which is what is configured in the XML.

**Comment by arunkottol** [comment]
@smakagon  - Here's what I do:

1. What I did is that I added the app to the course from settings using the XML.
2. I created a new Assignment. In the Submission type, I selected "External Tool" and from the options selected tool I added in step 1.
3. I still see the blti:launch_url being displayed in the URL.

Maybe I am doing something wrong. Can you please explain how you do this? Thanks.
