### ISSUE TITLE
"redirect_uri does not match client settings" error when Redirect URIs field is used instead of Redirect URI (Legacy)

### ISSUE THREAD

**Issue by seanh** [instructure/canvas-lms#1100]
### Summary:

(I'm currently able to reproduce this issue, for example, on our hypothesis.instructure.com Canvas instance)

When adding a developer key in Canvas the user is presented with a form including fields labeled Redirect URI (Legacy) and Redirect URIs:

![screenshot from 2017-08-25 15-38-18](https://user-images.githubusercontent.com/22498/29718750-ad3dc37e-89ab-11e7-9a38-8ea01db9acb7.png)

If the user enters the app's redirect URI in the Redirect URIs field only, and leaves Redirect URI (Legacy) empty, then when they try to launch the app they will get this error message from Canvas:

> while(1);{"error":"invalid_request","error_description":"redirect_uri does not match client settings"}

(this text appears in the user's browser)

To get Canvas to launch the app it seems that the user must enter the redirect URI in the Redirect URI (Legacy) field. But some users, when they see _legacy_, will skip it and use the other field instead.

I think the solution should be for Canvas to proceed with the launch as long as the correct redirect URI is in _either_ field?

**Comment by ccutrer** [comment]
The difference is that the legacy redirect URI is far more lenient in how it will match during the OAuth flow (and presents possible security problems). With the Redirect URIs field, one of the configured URI must match *exactly* with the passed redirect_uri (including query params). Looking at the logs for the last 24 hours, I see that you have a tool configured with a legacy redirect URI of https://redacted_domain/token_callback, but when you hit the OAuth flow you're passing https://redacted_domain/refresh_callback, which obviously does not match exactly. The legacy redirect URI field is ignoring the path portion, and allowing the match.

**Comment by seanh** [comment]
Thanks @ccutrer ! I've opened an issue on our repo to get that fixed

**Comment by fako** [comment]
Why is this implemented in this way? The library that I use adds a state to the redirect_uri. Obviously a developer key setting can't match what that library generates. However as far as I know the state parameter is added as an extra security measure to prevent replay attacks. Why is Canvas blocking such redirect_uris and deprecates the setting that does allow this with the idea that that would be somehow more secure?

**Comment by fako** [comment]
If you read section 3.1.2.2 https://tools.ietf.org/html/rfc6749#section-3.1.2 about "registration requirements" you see that: "The authorization server SHOULD require the client to provide the complete redirection URI (the client MAY use the "state" request parameter to achieve per-request customization)"

The library is including the state parameter in the redirect uri in order to check the state with providers that do not add state to the redirect uri themselves. The library supports over 70 providers and I think this feature makes sense.

It's good that Canvas adds the state and Canvas is not obliged to follow the standard with allowing a state to be set by the client in the redirect uri.  I'll see what I can do with the library. Not a solution I'd be willing to share I'm afraid. Thank you for providing the information.

**Comment by ccutrer** [comment]
Yes, I've read it. Along with the entire spec. https://tools.ietf.org/html/rfc6749#section-4.1.1 - state is explicitly a sibling param of redirect_uri, and not intended to be stuffed into redirect_uri. https://tools.ietf.org/html/rfc6749#section-10.12 gives more details on how this interaction is expected to work.

https://developers.facebook.com/blog/post/2017/12/18/strict-uri-matching/ is a blog post about Facebook enforcing stricter redirect URI matching. 

Google is so strict, it actually parses the redirect URI and rejects it if the redirect_uri itself includes a state parameter. That's a good idea, and would help cut down on confusion.

**Comment by fako** [comment]
That library works with Google and Facebook. It makes a distinction between Google+ and Google though. Maybe I'm missing something. Will look into this further soon. Thanks for the clarification.
