### ISSUE TITLE
Please open CORS for Files API downloads

### ISSUE THREAD

**Issue by seanh** [instructure/canvas-lms#1104]
### Summary:

The [Canvas Files API](https://canvas.instructure.com/doc/api/files.html) returns URLs like `http://www.example.com/files/569/download?download_frd=1&verifier=c6HdZmxOZa0Fiin2cbvZeI8I5ry7yqD7RChQzb6P` for downloading the files, but these URLs can't be downloaded by a Canvas app's client-side JavaScript code running in the app's iframe inside Canvas.

The reason is that said iframe will be on a different origin than the file download URL, and Canvas doesn't support CORS (doesn't respond to the browser's `OPTIONS` preflight request with a suitable `Access-Control-Allow-Origin` header) for these file downloads, so the browser refuses to allow the JavaScript `fetch()` or `XMLHttpRequest`.

For example in Chrome I get this error: `No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mycanvasapp.com' is therefore not allowed access.`

### Steps to reproduce:

From a Canvas app's client-side JavaScript code that runs inside the app's iframe in Canvas:

 1. `fetch('http://www.example.com/files/569/download?download_frd=1&verifier=c6HdZmxOZa0Fiin2cbvZeI8I5ry7yqD7RChQzb6P').then(function(response) { console.log(response); });`

You'll also get the same result if you use `XMLHttpRequest`.

### Expected behavior:

The fetch should succeed and download the file from the Canvas Files API.

### Additional notes:

What I'm trying to do is render PDF.js inside my Canvas app's iframe, and have PDF.js rendering a PDF file that has been uploaded to the Canvas course. [PDF.js does an `XMLHttpRequest` to get the PDF file](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr) and therefore requires CORS support from the server hosting the file.

Without this CORS support from Canvas it looks like I would have to have my app's server download the PDF file from the Canvas API, and then have PDF.js (running inside my app's iframe in Canvas) request the file from my app's server instead of from Canvas directlly. My app's server would support the necessary CORS headers to allow this request to go through. In other words I'd be implementing a CORS proxy for the Canvas Files API on my server. It'd be so much simpler and better if I didn't have to do this.

Thanks

**Comment by omarkhan** [comment]
Thanks for this @seanh. I don't think this is something we have a need for currently, but if you submit a pull request we will consider it.

**Comment by seanh** [comment]
Thanks. We ended up going with a different solution that doesn't require this (we proxy the files instead). Since you don't have a need for it either, I'll close this issue

**Comment by HoldYourWaffle** [comment]
I just encountered this issue, and it's preventing me from keeping the app fully client-side.

I would love to take a shot at a PR for this, but I have literally no idea where to start...
Maybe somebody can give me a pointer on where to look?
