### ISSUE TITLE
inquiry about api

### ISSUE THREAD

**Issue by MrFaisal100** [instructure/canvas-lms#1106]
Hello,

this is a question not an issue
does the open source version have a rest api, that I can develop custom integrations with?
if yes how can I access the documentation about it
I appreciate your support?

Regards,

### Steps to reproduce:

 1.
 2.
 3.

### Additional notes:

**Comment by bootstraponline** [comment]
https://canvas.instructure.com/doc/api/index.html may be what you're looking for.

**Comment by simonista** [comment]
The link @bootstraponline posted is the link to our build of the api docs.  The api in the open source repo will be mostly the same, although there are a few endpoints that are only available in the hosted version.  You can build the api docs yourself by running `bundle exec rake doc:api`, and then navigating to `<your-canvas>/doc/api/index.html`.  Hope that helps!.

**Comment by MrFaisal100** [comment]
Thanks alot @bootstraponline @simonista 
then I will check the local api on my local version
