### ISSUE TITLE
Quizzes migration issue.

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#1110]
### Summary:
Hello community,

I am not able to import the Quizzes from one course to another via "Import content into this course" function.

### Steps to reproduce:
Below steps describe the try to import the all quizzes from Course2 into Course1:

Pick a course - let’s use Course1.
Navigate to: Settings > Import Content into this Course:
Content Type - Copy a Canvas Course
Check the Box - Include completed courses
Search for a Course - Course2
Content - Select Specific Content
Don’t adjust events and due dates
Click the blue IMPORT button
Then on the next screen - Select Content - choose Quizzes and select content
It’s Ques, it Runs, it says Completed 
Hit Quizzes in the left navigation bar (in Course1) - and there only my previous quizzes and no one from Course2.

### Expected behavior:
The Quizzes from Course2 should be imported into Quizzes of Course1.

### Additional notes:
I have tried a few attempts without luck. It (status) shows as "Completed" but in reality the Quizzes did not import.
https://www.screencast.com/t/MIbStvi4I

Also I did not notice any error in the production.log or delayed_job.log log file.
All what I noticed int delayed_job.log file is the next:
##########################
`[server3.clrcdata.com:24249 2535639] Processing Canvas::Migration::Worker::CourseCopyWorker {"priority":20,"attempts":0,"created_at":"2017-09-10T09:27:36Z","tag":"Canvas::Migration::Worker::CourseCopyWorker#perform","max_attempts":1,"strand":"migrations:import_content\/10000000000001","source":null}
[server3.clrcdata.com:24249 2535639] Completed Canvas::Migration::Worker::CourseCopyWorker 1800ms
[server3.clrcdata.com:24249 2535639] [STAT] 823568 823568 0 1.4800000000000004 0.050000000000000044`
##########################

Canvas LMS version: origin/stable/2016-12-10
Ruby version: ruby 2.2.6p396

Would be glad for any help.
Regards.

**Comment by simonista** [comment]
It sounds like you might be missing the QTIMigrationTool plugin, see https://github.com/instructure/canvas-lms/wiki/Production-Start#qtimigrationtool for more details.
