### ISSUE TITLE
Unable to get the Docker container running

### ISSUE THREAD

**Issue by pzduniak** [instructure/canvas-lms#1111]
### Summary:

Every single time I try to get Canvas running using Docker images I run into the following error:

```
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning Pattern ["jquery@https://github.com/ryankshaw/jquery.git#1.7.2-with-AMD-and-CommonJS"] is trying to unpack in the same destination "/home/docker/.cache/yarn/v1/npm-jquery-1.7.2-a755a3e9c99d5a70d8ea570836f94ae1ba56046d" as pattern ["jquery@>=1.7.1","jquery@>=1.5","jquery@>=1.2.6"]. This could result in a non deterministic behavior, skipping.
error An unexpected error occurred: "https://github.com/ryankshaw/jquery.git: Request failed \"406 Not Acceptable\"".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'webpack' failed to build: The command '/bin/sh -c bundle install --jobs 8   && yarn install --pure-lockfile' returned a non-zero code: 1
```

### Steps to reproduce:

I tried both ways:

 1. Follow the docs/docker guide on an unchanged repo.
   - `docker-compose run --rm web bash -c "bundle install"`
   - `docker-compose run --rm web bash -c "bundle exec rake db:create db:initial_setup"`
   - `docker-compose up` - results in the above

Or:

Apply the following changes:
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 1bed746b7a..153175d131 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -2,8 +2,7 @@
 version: '2'
 services:
   web: &WEB
-    build:
-      context: .
+    image: instructure/canvas-lms:stable
     links:
       - postgres
       - redis
```

1. `docker-compose run --rm web bash -c "bundle install"`
2. `docker-compose run --rm web bash -c "bundle exec rake db:create db:initial_setup"`
3. `docker-compose up` - results in the above

### Expected behavior:

It should start up.

### Additional notes:

Running Docker in VM using Docker for OSX or however it's called, `Docker version 17.06.2-ce, build cec0b72`

**Comment by jenseng** [comment]
Hi @pzduniak, this was just fixed today on the `master` branch, sorry about that :(

See here: https://github.com/instructure/canvas-lms/commit/6d8d6abdd48e34d4b3b7ead48bb3ec3295dbb269

You could cherry-pick that commit to fix it, or just wait till it lands on `stable` (< 1 week)
