### ISSUE TITLE
web container under docker-compose always timeouts

### ISSUE THREAD

**Issue by pzduniak** [instructure/canvas-lms#1113]
### Summary:

I still can't get it working :/

```
web_1       | [ E 2017-09-12 17:50:25.0865 16/Tq age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /usr/src/app: An error occurred while starting up the preloader: it did not write a startup response in time. If your app needs more time to start you can increase the Passenger start timeout config option.
web_1       |   Error ID: c88836f9
web_1       |   Error details saved to: /tmp/passenger-error-ZnIBaM.html
web_1       |   Message from application: An error occurred while starting up the preloader: it did not write a startup response in time. If your app needs more time to start you can increase the Passenger start timeout config option. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
web_1       | <h2>Raw process output:</h2>
web_1       | <pre>
web_1       | /home/docker/.gem/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
web_1       | /home/docker/.gem/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
web_1       | /home/docker/.gem/ruby/2.4.0/gems/redis-3.3.1/lib/redis/client.rb:459: warning: constant ::Fixnum is deprecated
web_1       | /home/docker/.gem/ruby/2.4.0/gems/redis-3.3.1/lib/redis/client.rb:459: warning: constant ::Fixnum is deprecated
web_1       | /home/docker/.gem/ruby/2.4.0/gems/redis-3.3.1/lib/redis/client.rb:459: warning: constant ::Fixnum is deprecated
web_1       | /home/docker/.gem/ruby/2.4.0/gems/redis-3.3.1/lib/redis/client.rb:459: warning: constant ::Fixnum is deprecated
web_1       | </pre>
```

### Steps to reproduce:

 1. Clone the repo.
 2. cp the configuration files
 3. `docker-compose run --rm web bundle install`
 4. `docker-compose run --rm web bundle exec rake db:create db:initial_setup`
 5. `docker-compose run --rm web bundle exec rake canvas:compile_assets`
 6. `docker-compose up`

### Expected behavior:
It should simply load... something?

### Additional notes:
8GB of ram, 8 vCPUs are assigned to the Docker VM. Everything's simply using Docker for Mac with port mappings to access :80 of web.

**Comment by pzduniak** [comment]
Apparently it takes 3 minutes to start up the web container with 8 vCPUs :^) Please note it somewhere.

**Comment by redice44** [comment]
@pzduniak How did you increase the timeout? I believe I'm running into the same issue, and I can't seem to find the place to increase it. Thanks!

**Comment by omarkhan** [comment]
We have had problems with slow startup times with remote debugging enabled. Ensure that the `REMOTE_DEBUGGING_ENABLED` environment variable is not set and try again. If you still don't see any improvements please try the [mailing list](http://groups.google.com/group/canvas-lms-users) or [IRC](http://webchat.freenode.net/?channels=canvas-lms).

**Comment by pzduniak** [comment]
I added `ENV PASSENGER_STARTUP_TIMEOUT "3600"` to `Dockerfile`, that's how it starts up. I am mostly using it on an underpowered "local cloud" device, so tbh I wouldn't be surprised if it was _that_ slow in real environment, though slow startups in a powerful VM surprised me quite a bit.

Would the `REMOTE_DEBUGGING_ENABLED` be enabled by default? I'm simply using `FROM instructure/canvas-lms:stable` in my `Dockerfile`, I don't think that it'd make sense.

**Comment by tierra** [comment]
I would suggest adding that `PASSENGER_STARTUP_TIMEOUT` to your docker-compose.local override. That lets you change it just for your local development environment without changing the default for the image.
