### ISSUE TITLE
Outgoing E-mails not working in Canvas-Lms

### ISSUE THREAD

**Issue by potru** [instructure/canvas-lms#1114]
### Summary: 
Mails are not getting delivered from Canvas to the the users. Any notification emails are not getting sent to the given email address of the users. We tried configuring outgoing.yml file. We are not sure what would be the user_name and password would be here. We are getting this error 'Net::OpenTimeout - execution expired' currently.
**Outgoing.yml Config:**
address: "email-smtp.us-east-1.amazonaws.com"
port: "25"
tls: "true"
delivery_method: "sendmail"
user_name: "xxxx@xxx.com"
password: "password"
authentication: "plain" # plain, login, or cram_md5
domain: "ip-x.x.x"
outgoing_address: "xxxx@xxx.com"
default_name: "Canvas"
### Steps to reproduce:

 1.Click on any course and enroll an user as a student/teacher
 2.Create any notification or announcements
 3.Check if the user has received email on the same

### Expected behavior:
Email on the notification has to be sent to the users's registered email ids.
### Additional notes:

Kindly guide us here!

Thanks,
Suresh

**Comment by omarkhan** [comment]
Thanks for the report Suresh. We are using github issues for bugs only, for configuration issues please try asking on the [mailing list](http://groups.google.com/group/canvas-lms-users) or [IRC](http://webchat.freenode.net/?channels=canvas-lms). Thanks!

**Comment by itsthejoker** [comment]
As someone who is currently trying to debug this issue on prod with no prior knowledge of the software, answers like this are _incredibly_ unhelpful.

**Comment by lawrencetungsten** [comment]
Hi, after configuring outgoing yml. How can i restart the service?

**Comment by waynetunmyint** [comment]
port 25 is disable by default is EC2
