### ISSUE TITLE
Sections API only returns first ten sections

### ISSUE THREAD

**Issue by wolever** [instructure/canvas-lms#1115]
### Summary:

The `/courses/:course_id/sections` API only returns the first 10 sections.

### Steps to reproduce:

 1. Create a course with more than 10 sections
 2. Request a list of the sections
 3. Notice that only the first 10 are returned

This is not mentioned in the documentation: https://canvas.instructure.com/doc/api/sections.html

**Comment by ccutrer** [comment]
Please see https://canvas.instructure.com/doc/api/file.pagination.html. It's not mentioned on that specific API because _every_ API is paginated, and will only return the first few results (the number varies based on the installation, where settings can change).

**Comment by wolever** [comment]
Ahh okay!

It'd be really nice if there was some mention of that in the documentation. For example, even just changing `Returns the list of sections for this course.` to `Returns _a paginated_ list of sections for this course.`

Otherwise it's not at all obvious that the result is paginated, and it's not mentioned anywhere that the "basics" section is required reading for anyone modifying an existing API integration.

**Comment by wolever** [comment]
Here we go: https://github.com/instructure/canvas-lms/pull/1116
