### ISSUE TITLE
Issue with latest Canvas LMS installation.

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#1118]
### Summary:

I was not able to install Canvas LMS into Ubuntu 14.04  due to 'yarn' issue.

### Steps to reproduce:

- walk through the steps at https://github.com/instructure/canvas-lms/wiki/Production-Start
- the issue appears when typing 'yarn install':

here is screenshot with the error:
https://www.screencast.com/t/ONa7uPaqlf

`warning Pattern ["jquery@https://github.com/ryankshaw/jquery.git#1.7.2-with-AMD-and-CommonJS"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v1/npm-jquery-1.7.2-a755a3e9c99d5a70d8ea570836f94ae1ba56046d" as pattern ["jquery@>=1.7.1","jquery@>=1.5","jquery@>=1.2.6"]. This could result in a non deterministic behavior, skipping.
error An unexpected error occurred: "https://github.com/ryankshaw/jquery.git: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?".
info If you think this is a bug, please open a bug report with the information provided in "/root/canvas/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`
### Expected behavior:
The yarn should install all packages.

**Comment by pzduniak** [comment]
Happens on both `master` and `stable`.

**Comment by pzduniak** [comment]
```apt-get install --allow-downgrades -y yarn=0.27.5-1``` might help. Documentation is outdated it seems.

**Comment by ally1** [comment]
Hello @pzduniak,

Thank you for the tip. I was not able to use '--allow-downgrade' option but I downloaded the yarn_0.27.5_all.deb file from https://github.com/yarnpkg/yarn/releases , installed it, and it did the trick.

Thank you!

**Comment by pzduniak** [comment]
IMO you should keep the issue open to remind the developers to update the docs (or finally fix the yarn files). Setting up Canvas is very frustrating right now, you're supposed to figure out a ton of stuff yourself.

**Comment by tierra** [comment]
That's mostly because there's several different ways to install, configure, and run Canvas. Some people don't use Docker in their infrastructure at all, and don't want, or need to see those instructions. There's some assumptions here that you understand how to install and configure Rails applications in general.

**Comment by pzduniak** [comment]
Yeah, the difference is that after you follow Docker guides you end up with a timeout page of Passenger and when you follow the "Production Start" guide you aren't able to install it, because of an issue that was only fixed in the Dockerfile (and not in the docs).

**Comment by ally1** [comment]
I am agree with @pzduniak so I re-open the ticket. It would be great if devs fix the issue with yarn.

**Comment by shawniverson** [comment]
Production start updated in wiki to use yarn 0.27.5-1

**Comment by ally1** [comment]
Hello @shawniverson ,

Thank you for the updating of "Production Start" guide.
Closing this ticket.
