### ISSUE TITLE
Peer Review Rubrics in Speed Grader [UI BUG]

### ISSUE THREAD

**Issue by ptyork** [instructure/canvas-lms#1122]
### Summary:

When an assignment has a peer review component and a rubric, both students and the instructor are expected to fill out the rubric. If a student submission already has had a peer review completed, the speed grader shows the rubric for the peer review. Clicking on the View Rubric button SHOULD allow the instructor to add a NEW rubric. However, instead, it loads the student peer review content. The instructor must overwrite the peer review content and save the response. This is VERY confusing.

### Steps to reproduce:

 1. Create an assignment with a rubric and peer reviews
 2. Assign peer reviews
 3. Wait for one or more peer reviews to be submitted
 4. Open Speed Grader and navigate to a submission with a completed peer review
 5. Click on View Rubric

### Expected behavior:

Speed grader should not show peer reviews at all. Grading assignments and assessing peer reviews are separate tasks entirely. If the speed grader must show peer reviews for some reason, then there should be no way of editing a student's review. The View Rubric button should ONLY allow for editing of the instructor's rubric.

### Additional notes:

This has been a known issue (at least on Canvas Community) for a long while. The direct link is: [https://community.canvaslms.com/thread/10020](https://community.canvaslms.com/thread/10020).

**Comment by omarkhan** [comment]
Thanks for this @ptyork, and sorry for the late reply. I checked with some people more familiar with this part of Canvas, they said that this is not on the roadmap at present. If you would like to open a pull request we will consider it, as long as the change is opt-in and doesn't break anyone's current workflow.
