### ISSUE TITLE
compiling assets error

### ISSUE THREAD

**Issue by NNagato** [instructure/canvas-lms#1123]
### Summary:
I'm following quick start guide.
node -v
v6.11.3
### Steps to reproduce:

 1. ./CODES.sh
 2. Manual run: `$GEM_HOME/bin/bundle exec rake canvas:compile_assets`

### Additional notes:
The complete error log is as follows :
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
yarn install v0.27.5
$ script/gem_npm install
running yarn install for gems/canvas_i18nliner/package.json
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.33s.
running yarn install for gems/selinimum/package.json
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.23s.
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
rake aborted!
error running yarn install
/home/gin/canvas/lib/tasks/js.rake:55:in `block (2 levels) in <top (required)>'
/home/gin/canvas/lib/tasks/canvas.rake:55:in `block (3 levels) in <top (required)>'
/home/gin/canvas/lib/tasks/canvas.rake:7:in `log_time'
/home/gin/canvas/lib/tasks/canvas.rake:54:in `block (2 levels) in <top (required)>'
/home/gin/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/gin/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks1.9.1:15:in `eval'
/home/gin/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks1.9.1:15:in `<main>'
Tasks: TOP => js:yarn_install
(See full trace by running task with --trace)

**Comment by simonista** [comment]
Hi @NNagato, thanks for the report.  Can you try again on the latest master, and if it's still happening can you remove `--frozen-lockfile` from https://github.com/instructure/canvas-lms/blob/stable/lib/tasks/js.rake#L52 and report back what changes in the lockfile?  Thanks!
