### ISSUE TITLE
Bug with submitting response to discussion

### ISSUE THREAD

**Issue by martha** [instructure/canvas-lms#1125]
### Steps to reproduce:

 1. Hit the "Reply" button to respond to a class discussion
 2. Click "Cancel"
 3. Click "Reply" again

### Expected behavior:

Clicking "Reply" for a second time should yield a result consistent with the first time, i.e., the familiar response-post input box should show up.

### Additional notes:
[interface error.mov.zip](https://github.com/instructure/canvas-lms/files/1315800/interface.error.mov.zip)

**Comment by bkirkby** [comment]
thanks @marthakedwards! i'm planning on looking into this in the next sprint cycle.
