### ISSUE TITLE
File Generation: Rake aborted due to yarn

### ISSUE THREAD

**Issue by matthiasfromm** [instructure/canvas-lms#1126]
### Summary:

I'm trying to install Canvas on a freshly setup server running Ubuntu 14.04. I'm following the production start guide. Running `yarn install` [for the first time in the install process ](https://github.com/instructure/canvas-lms/wiki/Production-Start#file-generation) fails, yarn needs to be installed using another command (apt-get install cmdtest). When in the next step generating the files using yarn the rake aborts.

### Steps to reproduce:

 1. Follow installation guide until "[File Generation](https://github.com/instructure/canvas-lms/wiki/Production-Start#file-generation)"
 2. Run `yarn install` throws error
"The program 'yarn' is currently not installed. You can install it by typing:
apt-get install cmdtest"
 3. Install yarn by running `apt-get install cmdtest`
 4. Ten run `RAILS_ENV=production bundle exec rake canvas:compile_assets`, which fails with error (see additional notes for log).

### Expected behavior:

Run without abortion.

### Additional notes:

Commands and outputs from terminal:

.....:/var/canvas# RAILS_ENV=production bundle exec rake canvas:compile_assets
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
--> Starting: 'Making sure node_modules are up to date'
node is: v6.11.3 (/usr/bin/node)
Usage: yarn [options]

yarn: error: no such option: --frozen-lockfile

rake aborted!
error running yarn install
/var/canvas/lib/tasks/js.rake:55:in `block (2 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:55:in `block (3 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:7:in `log_time'
/var/canvas/lib/tasks/canvas.rake:54:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => js:yarn_install
(See full trace by running task with --trace)

**Comment by matthiasfromm** [comment]
Here's the terminal output, running the task with --trace:

.......:/var/canvas# RAILS_ENV=production bundle exec rake canvas:compile_assets --trace
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
** Invoke canvas:compile_assets (first_time)
** Execute canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
** Invoke js:yarn_install (first_time)
** Execute js:yarn_install
node is: v6.11.3 (/usr/bin/node)
Usage: yarn [options]

yarn: error: no such option: --frozen-lockfile

rake aborted!
error running yarn install
/var/canvas/lib/tasks/js.rake:55:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/var/canvas/lib/tasks/canvas.rake:55:in `block (3 levels) in <top (required)>'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/var/canvas/lib/tasks/canvas.rake:7:in `log_time'
/var/canvas/lib/tasks/canvas.rake:54:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/bin/rake:22:in `load'
/var/canvas/vendor/bundle/ruby/2.4.0/bin/rake:22:in `<main>'
Tasks: TOP => js:yarn_install

**Comment by shawniverson** [comment]
Did you actually do this step?

https://github.com/instructure/canvas-lms/wiki/Production-Start#yarn-installation

**Comment by matthiasfromm** [comment]
Yes, @shawniverson, I did. This install process ran through and also provided an small error at the end:

E: Command line option --allow-downgrades is not understood

**Comment by shawniverson** [comment]
Ahh ok...must be specific to 14.04

Try it without --allow-downgrades

**Comment by matthiasfromm** [comment]
@shawniverson, running `sudo apt-get update && sudo apt-get install yarn=0.27.5-1` also gave back an error:

.....
The following NEW packages will be installed:
  yarn
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 622 kB of archives.
After this operation, 3,805 kB of additional disk space will be used.
Get:1 https://dl.yarnpkg.com/debian/ stable/main yarn all 0.27.5-1 [622 kB]
Fetched 622 kB in 0s (1,845 kB/s)
(Reading database ... 98146 files and directories currently installed.)
Preparing to unpack .../archives/yarn_0.27.5-1_all.deb ...
Unpacking yarn (0.27.5-1) ...
dpkg: error processing archive /var/cache/apt/archives/yarn_0.27.5-1_all.deb (--unpack):
 trying to overwrite '/usr/bin/yarn', which is also in package cmdtest 0.10-1
Errors were encountered while processing:
 /var/cache/apt/archives/yarn_0.27.5-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by shawniverson** [comment]
@matthiasfromm 

You need to remove the cmdtest you previously installed

**Comment by matthiasfromm** [comment]
@shawniverson 

Removing cmdtest and then running `sudo apt-get update && sudo apt-get install yarn=0.27.5-1` seems to have worked.

**Comment by shawniverson** [comment]
Updated Production Start instructions

**Comment by matthiasfromm** [comment]
@shawniverson 

Thanks. I am currently running `RAILS_ENV=production bundle exec rake canvas:compile_assets`. Seems to take a while, currently it's been doing nothing after "Finished ´rev´for several minutes now, and it's also not returning back to the prompt line. Not sure whether this crashed or just takes so long.

**Comment by shawniverson** [comment]
@matthiasfromm It takes a while.

**Comment by matthiasfromm** [comment]
Seems like that solved the problem. Thanks for the immediate support @shawniverson! Greatly appreciated!
