### ISSUE TITLE
Submitting grades from external applications results in incorrect submitted_at date

### ISSUE THREAD

**Issue by moorecp** [instructure/canvas-lms#1127]
### Summary:
Recently-ish, when submitting a grade back via LTI (hitting the `grade_passback` route) Submissions are getting a `submitted_at` date that isn't quite right. The date seems to be the `updated_at` date of the unsubmitted Submission that is created when either the assignment is published or the student enrolls in the course (whichever is later). This only seems to be happening with grade passback grades.

### Steps to reproduce:

 1. Create a course
 2. Enroll a user in that course
 3. Create an `external_tool` assignment the utilizes grade passback for submitting a grade for that course with a point value and due date
 4. Add the assignment to a module and publish it
 5. You can note that there exists a Submission for that user for that assignment that has a `workflow_state` of `unsubmitted`
 6. As the user created in step 2, complete the assignment you created

### Expected behavior:
The `unsubmitted` Submission should be updated with a `submitted_at` time equal to the time at which the grade was passed back via the API. Instead, what you'll see is `submitted_at` will be equal to `updated_at` before the grade was submitted.

### Initial Submission (Step 5):
```ruby
{
 id: 123,
 workflow_state: "unsubmitted",
 submitted_at: nil,
 created_at: "2017-09-22 20:00:00",
 updated_at: "2017-09-22 20:00:00"
}
```

### Expected Submission (Step 6)
```ruby
{
 id: 123,
 workflow_state: "graded",
 submitted_at: "2017-09-22 20:15:00",
 created_at: "2017-09-22 20:00:00",
 updated_at: "2017-09-22 20:15:00"
}
```

### Actual Submission (Step 6)
```ruby
{
 id: 123,
 workflow_state: "graded",
 submitted_at: "2017-09-22 20:00:00",
 created_at: "2017-09-22 20:00:00",
 updated_at: "2017-09-22 20:15:00"
}
```

**Comment by omarkhan** [comment]
Thanks for the report @moorecp. I don't think we've seen this before. Could you write a test that reproduces the bug?
