### ISSUE TITLE
The require_sequential_progress not getting updated as expected via API

### ISSUE THREAD

**Issue by kenfdev** [instructure/canvas-lms#1129]
### Summary:
Would like to update the requirements of the module via API so students have to progress sequentially inside modules.

I am creating a PUT request like the one below.

`PUT /api/v1/courses/1/modules/1?module[require_sequential_progress]=1`

And the response is like the one below.

```
{
    "id": 1,
    "position": 1,
    "name": "Some Module",
    "unlock_at": null,
    "require_sequential_progress": true,
    "publish_final_grade": false,
    "prerequisite_module_ids": [],
    "published": true,
    "items_count": 14,
    "items_url": "<URL>",
    "publish_warning": false
}
```

The `require_sequential_progress` does get updated but if you look at the UI, it still says `Student must complete one of these requirements` .

### Steps to reproduce:

 1. Request a `PUT /api/v1/courses/1/modules/1?module[require_sequential_progress]=1` to an existing module. 
 2. Check the module's status via the Canvas LMS UI

### Expected behavior:
I was expecting `Students must complete all of these requirements` and `Students must move through requirements in sequential order` checked.

### Additional notes:
I'm assuming it has something to do with `requirement_count` .  because requests via the UI include them as `blank` .

![default](https://user-images.githubusercontent.com/3941889/30846058-fe84e9b8-a2d0-11e7-85f1-fdf9d14dfc6a.png)

And requests via API are filtering them out.

https://github.com/instructure/canvas-lms/blob/stable/app/controllers/context_modules_api_controller.rb#L514

https://github.com/instructure/canvas-lms/blob/stable/app/controllers/context_modules_api_controller.rb#L574

Thanks in advance!

**Comment by omarkhan** [comment]
We try to use github issues for end-user bugs only. Can you try asking about this on the [mailing list](http://groups.google.com/group/canvas-lms-users) or [IRC](http://webchat.freenode.net/?channels=canvas-lms)? Thanks!
