### ISSUE TITLE
Cannot compile / run Canvas using the Dockerfile

### ISSUE THREAD

**Issue by BLTSandwich** [instructure/canvas-lms#1130]
### Summary:
Cannot compile / run Canvas using the Dockerfile. I'm using Stable, but I did add the Yarn versioning fix from Beta. 

### Steps to reproduce:

 1. Use the default dockerfile (not prod)
 2. Attempt docker-compose run --rm web bash -c "bundle install"
 3. Error occurs (ERROR: Service 'web' failed to build: The command '/bin/sh -c COMPILE_ASSETS_NPM_INSTALL=0 bundle exec rake canvas:compile_assets' returned a non-zero code: 1)

### Expected behavior:
1. Dockerfile should successfully run 

### Additional notes:
I don't need quizzes at all, so if there's some easy / quick way to just remove this from trying to build, that'd be a super workaround. Ultimately though it should work for anyone who tries this. 

Here is the trace:

        Running 'yarn run build'...
r.js build failure: { Error: Error: Loader plugin did not call the load callback in the build:
jsx:
  jsx!canvas_quizzes/apps/statistics/views/app_unnormalized3
  jsx!canvas_quizzes/apps/statistics/views/app
  jsx!canvas_quizzes/apps/statistics/views/summary
  jsx!canvas_quizzes/apps/statistics/views/summary/score_percentile_chart
  jsx!canvas_quizzes/apps/statistics/views/questions/multiple_choice
  jsx!canvas_quizzes/apps/statistics/views/charts/correct_answer_donut
  jsx!canvas_quizzes/apps/statistics/views/questions/answer_table
  jsx!canvas_quizzes/apps/statistics/views/questions/short_answer
  jsx!canvas_quizzes/apps/statistics/views/questions/fill_in_multiple_blanks
  jsx!canvas_quizzes/apps/statistics/views/questions/essay
  jsx!canvas_quizzes/apps/statistics/views/questions/calculated
  jsx!canvas_quizzes/apps/statistics/views/questions/file_upload
Module loading did not complete for: canvas_quizzes/apps/statistics/main, canvas_quizzes/apps/statistics/core/delegate, canvas_quizzes/apps/statistics/views/app, canvas_quizzes/apps/statistics/views/summary, canvas_quizzes/apps/statistics/views/summary/score_percentile_chart, d3, canvas_quizzes/apps/statistics/views/questions/multiple_choice, canvas_quizzes/apps/statistics/views/charts/correct_answer_donut, canvas_quizzes/apps/statistics/views/questions/answer_table, canvas_quizzes/apps/statistics/views/questions/short_answer, canvas_quizzes/apps/statistics/views/questions/fill_in_multiple_blanks, canvas_quizzes/apps/statistics/views/questions/essay, canvas_quizzes/apps/statistics/views/questions/calculated, canvas_quizzes/apps/statistics/views/questions/file_upload
    at Function.build.checkForErrors (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:26695:19)

    at /usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:25150:19
    at /usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:3056:39
    at /usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:2996:25
    at Function.prim.nextTick (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:24901:9)
    at Object.errback (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:2995:26)
    at Object.callback (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:2981:23)
    at Object.then (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:3035:23)
    at build (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:25107:12)
    at runBuild (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:27115:17)
    at Object.execCb (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:1943:33)
  originalError:
   Error: Loader plugin did not call the load callback in the build:
   jsx:
     jsx!canvas_quizzes/apps/statistics/views/app_unnormalized3
     jsx!canvas_quizzes/apps/statistics/views/app
     jsx!canvas_quizzes/apps/statistics/views/summary
     jsx!canvas_quizzes/apps/statistics/views/summary/score_percentile_chart
     jsx!canvas_quizzes/apps/statistics/views/questions/multiple_choice
     jsx!canvas_quizzes/apps/statistics/views/charts/correct_answer_donut
     jsx!canvas_quizzes/apps/statistics/views/questions/answer_table
     jsx!canvas_quizzes/apps/statistics/views/questions/short_answer
     jsx!canvas_quizzes/apps/statistics/views/questions/fill_in_multiple_blanks
     jsx!canvas_quizzes/apps/statistics/views/questions/essay
     jsx!canvas_quizzes/apps/statistics/views/questions/calculated
     jsx!canvas_quizzes/apps/statistics/views/questions/file_upload
   Module loading did not complete for: canvas_quizzes/apps/statistics/main, canvas_quizzes/apps/statistics/core/delegate, canvas_quizzes/apps/statistics/views/app, canvas_quizzes/apps/statistics/views/summary, canvas_quizzes/apps/statistics/views/summary/score_percentile_chart, d3, canvas_quizzes/apps/statistics/views/questions/multiple_choice, canvas_quizzes/apps/statistics/views/charts/correct_answer_donut, canvas_quizzes/apps/statistics/views/questions/answer_table, canvas_quizzes/apps/statistics/views/questions/short_answer, canvas_quizzes/apps/statistics/views/questions/fill_in_multiple_blanks, canvas_quizzes/apps/statistics/views/questions/essay, canvas_quizzes/apps/statistics/views/questions/calculated, canvas_quizzes/apps/statistics/views/questions/file_upload
       at Function.build.checkForErrors (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:26695:19)
       at Function.build.traceDependencies (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:26579:19)
       at /usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:25335:38
       at /usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:3089:24
       at /usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:3038:37
       at /usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:2986:25
       at Function.prim.nextTick (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:24901:9)
       at Object.callback (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:2985:26)
       at Object.then (/usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:3035:23)
       at /usr/src/app/client_apps/canvas_quizzes/node_modules/requirejs/bin/r.js:3088:29 }
rake aborted!
Build script failed for client app canvas_quizzes
/usr/src/app/lib/tasks/js.rake:27:in `block (4 levels) in <top (required)>'
/usr/src/app/lib/tasks/js.rake:12:in `chdir'
/usr/src/app/lib/tasks/js.rake:12:in `block (3 levels) in <top (required)>'
/usr/src/app/lib/tasks/js.rake:9:in `each'
/usr/src/app/lib/tasks/js.rake:9:in `block (2 levels) in <top (required)>'
/usr/src/app/lib/tasks/canvas.rake:75:in `block (2 levels) in <top (required)>'
/home/docker/.gem/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => js:build_client_apps

**Comment by omarkhan** [comment]
Thanks for the report @BLTSandwich. Can you reproduce this on master?

We're trying to use github issues for end-user bugs rather than setup or configuration issues; if you're still having problems with master can you try asking on the [mailing list](http://groups.google.com/group/canvas-lms-users) or [irc](http://webchat.freenode.net/?channels=canvas-lms)?

Thanks, good luck!

**Comment by BLTSandwich** [comment]
I can reproduce this on Master, yes. I haven't done any custom configuration or anything, so, very strange that it's not working.

I'll try on the Google group though, thank you.
