### ISSUE TITLE
Installation error:RAILS_ENV=production bundle exec rake db:initial_setup

### ISSUE THREAD

**Issue by basheernavas991** [instructure/canvas-lms#1131]
### Summary:
I'm on ubuntu 16.04.

### Steps to reproduce:
 1.execute RAILS_ENV=production bundle exec rake db:initial_setup

### stack trace:
/usr/lib/ruby/vendor_ruby/mime/type.rb:56: warning: already initialized constant MIME::Type::VERSION
/var/canvas/vendor/bundle/ruby/2.4.0/gems/mime-types-1.25.1/lib/mime/types.rb:36: warning: previous definition of VERSION was here
/usr/lib/ruby/vendor_ruby/mime/type.rb:61: warning: already initialized constant MIME::Type::MEDIA_TYPE_RE
/var/canvas/vendor/bundle/ruby/2.4.0/gems/mime-types-1.25.1/lib/mime/types.rb:40: warning: previous definition of MEDIA_TYPE_RE was here
/usr/lib/ruby/vendor_ruby/mime/type.rb:64: warning: already initialized constant MIME::Type::PLATFORM_RE
/var/canvas/vendor/bundle/ruby/2.4.0/gems/mime-types-1.25.1/lib/mime/types.rb:43: warning: previous definition of PLATFORM_RE was here
/usr/lib/ruby/vendor_ruby/mime/type.rb:71: warning: already initialized constant MIME::Type::IANA_URL
/var/canvas/vendor/bundle/ruby/2.4.0/gems/mime-types-1.25.1/lib/mime/types.rb:50: warning: previous definition of IANA_URL was here
/usr/lib/ruby/vendor_ruby/mime/type.rb:72: warning: already initialized constant MIME::Type::RFC_URL
/var/canvas/vendor/bundle/ruby/2.4.0/gems/mime-types-1.25.1/lib/mime/types.rb:51: warning: previous definition of RFC_URL was here
/usr/lib/ruby/vendor_ruby/mime/type.rb:73: warning: already initialized constant MIME::Type::DRAFT_URL
/var/canvas/vendor/bundle/ruby/2.4.0/gems/mime-types-1.25.1/lib/mime/types.rb:52: warning: previous definition of DRAFT_URL was here
/usr/lib/ruby/vendor_ruby/mime/type.rb:74: warning: already initialized constant MIME::Type::CONTACT_URL
/var/canvas/vendor/bundle/ruby/2.4.0/gems/mime-types-1.25.1/lib/mime/types.rb:54: warning: previous definition of CONTACT_URL was here
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
** Invoke db:initial_setup (first_time)
** Invoke db:generate_security_key (first_time)
** Execute db:generate_security_key
** Execute db:initial_setup
** Invoke db:migrate:predeploy (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `deprecated' for MIME::Types:Class
Did you mean?  deprecate
/usr/lib/ruby/vendor_ruby/mime/type.rb:413:in `url='
/var/canvas/config/initializers/mime_types.rb:38:in `block in <top (required)>'
/var/canvas/config/initializers/mime_types.rb:37:in `each'
/var/canvas/config/initializers/mime_types.rb:37:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `block in load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:648:in `block in load_config_initializer'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:166:in `instrument'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:647:in `load_config_initializer'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:611:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:44:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/2.4.0/tsort.rb:415:in `call'
/usr/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.4.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.4.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:54:in `run_initializers'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/application.rb:352:in `initialize!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `public_send'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `method_missing'
/var/canvas/config/environment.rb:28:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/application.rb:328:in `require_environment!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/var/canvas/lib/tasks/db_load_data.rake:239:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/bin/rake:23:in `load'
/var/canvas/vendor/bundle/ruby/2.4.0/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate:predeploy => environment

### Additional notes:

**Comment by omarkhan** [comment]
We try to keep github issues for end-user bugs. Please ask about configuration issues on [the mailing list](http://groups.google.com/group/canvas-lms-users) or [IRC](http://webchat.freenode.net/?channels=canvas-lms). Thanks!
