### ISSUE TITLE
Documentation Request: *why* are we setting GEM_HOME to ~/.gems

### ISSUE THREAD

**Issue by brandondrew** [instructure/canvas-lms#1132]
### Summary:

This seems odd to me, but the documentation does not offer any rationale.  Also, the location is not standard, AFAIK.

### Steps to reproduce:

 1.  Read the Quick Start guide
 2.  Look at the section on setting GEM_HOME
 3. Please explain why we need to do this?

### Expected behavior:

I don't think I've ever had to manually set GEM_HOME.  And I certainly wouldn't do it in my .bashrc (or .zshrc) file, which is global, for a single project.  This is not production, so setting GEM_HOME globally could botch other projects.   As far as I know "~/.gems" (with an "s") is not a standard location.  

I would really love to know why this is included.  It may be a mistake, or it may simply need some more explanation.

### Additional notes:

Thanks!

**Comment by omarkhan** [comment]
Thanks for this @brandondrew. My guess is that setting `GEM_HOME` helps to avoid permissions issues when installing gems. I'll ask around.

If you are looking for a setup that does not require changes to your system, I would suggest trying the [docker setup](https://github.com/instructure/canvas-lms/blob/master/doc/docker/developing_with_docker.md).

**Comment by omarkhan** [comment]
I asked around, setting `GEM_HOME` doesn't appear to be necessary. I have removed that section from the quickstart guide. Thanks for bringing this up!

**Comment by brandondrew** [comment]
Thanks!
