### ISSUE TITLE
Undefined method login_canvas_url , It should be canvas_login_url 

### ISSUE THREAD

**Issue by samuels410** [instructure/canvas-lms#1138]
When we have entries in the AccountAuthorizationConfig model table for canvas auth type, When logout it getting redirected the below method, there we have mentioned login_canvas_url there is no routes for this and its **giving error while log out**. 
I think it should be canvas_login_url.

Fresh canvas install we cannot reproduce this issue, I am wondering how the canvas cloud version not facing this issue.

https://github.com/instructure/canvas-lms/blob/efca6576213ca08b86e6cae373fe374ee80e6122/app/models/account_authorization_config/canvas.rb#L55

**Comment by ccutrer** [comment]
Does spec/controllers/login_controller_spec.rb pass for you? It works because both are valid names for routes, though only one is explicitly named. Either way, I'll switch it since it should't be a problem, and "canvas_login_url" reads better anyway.

**Comment by ccutrer** [comment]
fixed in cbec323a7d5c90a03f559439ea2aca11e8c406f6
