### ISSUE TITLE
Have to Zoom Out to See "View Feedback" Link

### ISSUE THREAD

**Issue by hangyao** [instructure/canvas-lms#1143]
### Summary:

In Chrome and Safari, one has to zoom out the browser window to see the "View Feedback" link of graded assignments. In Chrome, one has to zoom out to 90% of the original scale. Under 100% zoom view, the link just disappears.

![screenshot](https://user-images.githubusercontent.com/19369631/32068359-bb97b0ee-ba4b-11e7-8d11-c2ea218917ba.jpg)

**Comment by omarkhan** [comment]
Thanks for the report @hangyao. We have added this to our backlog, and should have a fix up soon.

**Comment by simonista** [comment]
Fixed in 0fd44f6fd8acf7c32527df658cd6bbf9603d52db
