### ISSUE TITLE
Assignment Submit Tabs

### ISSUE THREAD

**Issue by GrantSommer** [instructure/canvas-lms#1148]
### Summary:
When you turn in an assignment, if you have Google Drive linked, you will have a "Google Docs" tab, that should be renamed to "Google Drive".

Folders in your Google Drive show all in the same place, so if you have a folder named "abc" and create a folder named "xyz" in "abc," folder xyz will show in the same directory as folder abc.

### Steps to reproduce:

 1. Go to an assignment
 2. Press submit assignment

### Expected behavior:
* "Google Docs" tab should be called "Google Drive"
* Folders should be in their parent folders

**Comment by omarkhan** [comment]
Hi @GrantSommer - this looks like a feature request, we encourage you to submit this on our [community site](https://community.canvaslms.com/) for discussion. Thanks!
