### ISSUE TITLE
Help button in Canvas self hosted app Global Menu

### ISSUE THREAD

**Issue by AbithaVek** [instructure/canvas-lms#1150]
### Summary:
We are running a self hosted canvas app on cloud. We were wondering if we could add "Help" icon with links on some basic guidelines/FAQs on the usage of canvas. Kindly let us know if its possible to add one.

### Additional notes:
PFA a screenshot of 'Help' button we might require in our application.
![canvashelp](https://user-images.githubusercontent.com/31066816/32324458-870ac68a-bff1-11e7-903b-34d8a7c6909b.png)

Thanks!!

**Comment by omarkhan** [comment]
Hi @AbithaVek! This looks like a feature request, we encourage you to submit this on our [community site](https://community.canvaslms.com/) for discussion. Thanks!

**Comment by GTMtremolo** [comment]
Help button now display on global navigation and help option not show in account setting. Please tell me how to turn on it!
