### ISSUE TITLE
Issue while importing a course to canvas

### ISSUE THREAD

**Issue by AbithaVek** [instructure/canvas-lms#1151]
### Summary:
We are unable to upload/migrate large file common cartridge 1.2 file which is of 10GB size from black board to canvas. The jobs seem to be stuck and not progressing. Kindly guide us what we are missing here. Any help appreciated. Thanks!!
### Steps to reproduce:

 1. Login to blackboard and go the course.
2. Select Common Cartridge 1.2 and Click on submit button. It will generate imscc file to export.
5. Download the file.
6. Login in to Canvas and go the sub-account where course should be created and create a new course.
7. click on settings and then click on Import course content.
8. Then from dropdown select common cartridge package 1.x and select all content.
9. browse the file and submit it. Click on import.

### Expected behavior:
After successful processing all the course content from BB should be migrated to canvas.
### Additional notes:
We have increased the course quota to 10 GB(size of the actual common cartridge file) 
![canvascourse](https://user-images.githubusercontent.com/31066816/32325350-9f6cb14a-bff4-11e7-8feb-cd178fd67365.JPG)

Thanks!!

**Comment by omarkhan** [comment]
Thanks @AbithaVek. There are some issues with common cartridge imports. Can you provide a small example file that reproduces the issue?
