### ISSUE TITLE
Documentation seems to be out of date regarding dockerized quick start

### ISSUE THREAD

**Issue by darrensiegel** [instructure/canvas-lms#1152]
### Summary:

The documentation in the quick start guide mentions that after git clone one can execute
the ./script/docker_dev_setup.sh script.  Looking around in the scripts directory, I see similar
files to that, but not that exact file.  I see:

docker_first_time_build.sh 
docker_pull_image.sh
docker_update_build.sh  

I suspect that I need to execute docker_first_time_build.sh.  

### Steps to reproduce:

 1. Git clone
 2. Look in ./scripts directory
 3.Notice there isn't a docker_dev_setup.sh script

**Comment by omarkhan** [comment]
That script was recently committed to the master branch. A fresh canvas-lms clone will default to the stable branch, which is a few weeks behind. Try:

```
git checkout master
./script/docker_dev_setup.sh
```

**Comment by darrensiegel** [comment]
Thanks.  I was able to switch to master and use that script.
