### ISSUE TITLE
Error during migration: you need to run `gulp rev` first

### ISSUE THREAD

**Issue by n3rve** [instructure/canvas-lms#1153]
### Summary:
I get the following error during migration: you need to run `gulp rev` first

### Steps to reproduce:
 1. Setup dependencies according to production start guide
 2. Execute `RAILS_ENV=production bundle exec rake db:initial_setup`

### Expected behavior:
Migrations should finish running and I should see the interactive prompt for configuration

### Additional Information
My Ruby version:
`ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]`
Should I downgrade to Ruby 2.4.0?

**Comment by omarkhan** [comment]
@n3rve see 79a06e9fc6c for context. Try running:

```
bundle exec rake brand_configs:generate_and_upload_all
```

If that doesn't work I would suggest asking on [IRC](http://webchat.freenode.net/?channels=canvas-lms) or the [mailing list](http://groups.google.com/group/canvas-lms-users) (we use github issues for bug reports only, not configuration/setup issues).

**Comment by ally1** [comment]
Hello community,

I encountered the same error, on both Ubuntu 16 and 14. 
It seems like the issue related to the Canvas LMS code.

My Canvas LMS version:

`git show`
treesame commit of origin/stable/2017-10-28
Treesame-Commit-Id: 20697d5d1ca6b4a8c7664d39c9ace4f093e71935

The commands:
`bundle exec rake brand_configs:generate_and_upload_all` 
or 
`RAILS_ENV=production bundle exec rake brand_configs:generate_and_upload_all` 
did not resolve the issue.

**Comment by matthewcoupe** [comment]
Hey, we're really struggling with this. Our production environment crashed and we can't get past this step to rebuild. I went on the IRC but didn't really get anywhere. Did anyone manage to work around this issue? Thanks

**Comment by omarkhan** [comment]
I checked with a Canvas engineer who suggested running `gulp rev` first. Does that help?

**Comment by tp9106** [comment]
I had the same issue.

For me it is resolved by running the following command first:
`RAILS_ENV=production bundle exec rake canvas:compile_assets`

**Comment by matthewcoupe** [comment]
Thanks, the compile_assets helped for us. We now have it all restored but have hit what looks like one last issue. The files uploaded to courses are complete inaccessible and we aren't able to upload any files to courses either.

What could cause that?
Thanks!

**Comment by shajilal** [comment]
Got fixed by running "npm install gulp-rev"as canvas user used for deploying the code.
