### ISSUE TITLE
Canvas LMS into cPanel Hosting server

### ISSUE THREAD

**Issue by saydulk** [instructure/canvas-lms#1156]
### Steps to reproduce:

 1. Quick Start setup installation instruction Canvas LMS into cPanel Hosting server
 2. youtube video installation Canvas LMS into cPanel Hosting server

### Additional notes:

**Comment by simonista** [comment]
Hey @saydulk, we're not doing anything to specifically support or exclude cPanel, if someone else wanted to maintain cPanel installation instructions that would be fine, but we're going to keep our instructions here more general purpose.  Thanks!

**Comment by abudaana** [comment]
Hi there,
i need your help to install canvas lms on cpanel using file manager 
thanks in advance 
regards
frjani
