### ISSUE TITLE
Unable to Re-Grade Quiz Question After Modified and/or Unable To Give Full-Credit for Quiz Question

### ISSUE THREAD

**Issue by danieldjewell** [instructure/canvas-lms#1157]
### Summary:
Once a quiz question has been modified, it's impossible to re-grade all existing quizzes to give full-credit. 

Ultimate goal: Need to always have the ability to "throw out" a quiz question and give everyone full credit for the response. This is not the same as simply deleting the question.
### Steps to reproduce:

 1. Change quiz question after at least 1 student submission
 2. Try to re-grade question and assign full points
 3. Fail

### Expected behavior:
Ability to grant full-points on a particular quiz question for *all students* for those who have taken it and those who will take it - regardless of whether or not the question has been edited.

### Additional notes:

**Comment by simonista** [comment]
Hey @danieldjewell, thanks for the bug report, can you say more about what "Fail" means?  What happens when you try?
