### ISSUE TITLE
KTH header blocks file preview header

### ISSUE THREAD

**Issue by fippli** [instructure/canvas-lms#1158]
### Summary:
KTH header blocks file preview header on some screen sizes.
I encountered this as *student user*.

### Steps to reproduce:

 1. Log in as kth user (in my case student)
 2. Open / preview a PDF file in canvas

### Expected behavior:
![screen shot 2017-11-14 at 16 08 59](https://user-images.githubusercontent.com/2800451/32882097-8229a3a8-cab3-11e7-8258-31bf046fb92b.png)

### Additional notes:
This will be different depending on how the window is resized.

**Comment by simonista** [comment]
Hi @fippli, I'm not familiar with KTH, is it https://www.kth.se/?  From what I can gather it is the school you attend? You probably want to reach out to your school technical support, as they're the ones that are overlaying that banner on top of Canvas.

As a short term work around, if you're in Chrome, you may be able to right click on the bar and click "Inspect", and then right click on the HTML code highlighted in blue and click "Delete Element" to remove it temporarily to access the content you are trying to use, or you  may be able to use something like https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en to add some CSS to the page to hide the bar.

Hope that helps!

**Comment by fippli** [comment]
Hi thanks for the response! I realize now that this is of course a problem with KTH's implementation of canvas, not canvas itself.

Best regards!
