### ISSUE TITLE
HTML5 Audio tag "controls" property is getting sanitized

### ISSUE THREAD

**Issue by dslusser** [instructure/canvas-lms#1159]
### Summary:

Trying to insert HTML5 audio tag into canvas via the TinyMCE editor works as desired.  Upon save, Canvas sanitizes out the "controls" property of the tag, which in turn causes the audio player to not render on the page.  I believe this may have been an oversight at some point during a previous commit because the HTML5 video tag property of "controls" does not get sanitized.

### Steps to reproduce:

 1.  Using the TinyMCE editor, create an HTML5 audio tag that includes the "controls" property.

Basic use example:
<audio controls>
  <source src="https://www.w3schools.com/html/horse.mp3" type="audio/mpeg" />
  <source src="https://www.w3schools.com/html/horse.ogg" type="audio/ogg" />
  Your browser does not support the audio element.
</audio> 

 2.  Save the page and notice that the audio player does not render.  Upon further inspection of the page, notice that the audio tag is still present on the page, but the "controls" property has been sanitized.  

### Expected behavior:

I would expect that the "controls" property of the audio tag does not get sanitized so that the audio player is able to be rendered on the page.

### Additional notes:

canvas-lms/gems/canvas_sanitize/lib/canvas_sanitize/canvas_sanitize.rb

**Comment by simonista** [comment]
Hey @dslusser, you're right, we should add controls to the whitelist.  I'll see if I can get that in in the next couple days.  Thanks for the report!

**Comment by dslusser** [comment]
Awesome! Thanks for looking into that @simonista !
