### ISSUE TITLE
Rake aborted during initial database setup on fresh install of canvas

### ISSUE THREAD

**Issue by pas-sean** [instructure/canvas-lms#1160]
### Steps to reproduce:

 1. Proceed through the steps in Production Start to "Database Population"
 2. Run the command to have rake do the initial database setup (

### Expected behavior:
Database should be set up with the initial tables and data.

But, I get an error and rake is aborted. Here's the stacktrace I'm seeing when running the command with --trace:

`canvas@Canvas:/var/canvas$ RAILS_ENV=production bundle exec rake db:initial_setup --trace
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
** Invoke db:initial_setup (first_time)
** Invoke db:generate_security_key (first_time)
** Execute db:generate_security_key
** Execute db:initial_setup
** Invoke db:migrate:predeploy (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 3 column 1
/usr/lib/ruby/2.4.0/psych.rb:377:in `parse'
/usr/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
/usr/lib/ruby/2.4.0/psych.rb:325:in `parse'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:149:in `load'
/var/canvas/config/application.rb:169:in `load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb:29:in `safe_load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb:12:in `load_with_options'
/var/canvas/lib/config_file.rb:45:in `load'
/var/canvas/lib/canvas.rb:71:in `cache_store_config_for'
/var/canvas/config/initializers/cache_store.rb:28:in `block in <top (required)>'
/var/canvas/config/initializers/cache_store.rb:70:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `block in load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:648:in `block in load_config_initializer'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:166:in `instrument'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:647:in `load_config_initializer'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:611:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:44:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/2.4.0/tsort.rb:415:in `call'
/usr/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.4.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.4.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/initializable.rb:54:in `run_initializers'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/application.rb:352:in `initialize!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `public_send'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `method_missing'
/var/canvas/config/environment.rb:28:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/application.rb:328:in `require_environment!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/var/canvas/lib/tasks/db_load_data.rake:239:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/redis-rack-2.0.3/bin/rake:17:in `load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/redis-rack-2.0.3/bin/rake:17:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/bin/rake:23:in `load'
/var/canvas/vendor/bundle/ruby/2.4.0/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate:predeploy => environment
`
I'm new to Ruby and Rake and not seeing any specific problems.. any ideas what I can do to get past this?

**Comment by ccutrer** [comment]
Check your `config/cache_store.yml` for syntax errors.

**Comment by pas-sean** [comment]
Awesome, thanks.. It took me a few tries to find the space but I got it and it's running the db setup now!
