### ISSUE TITLE
canvas_init start - is not working

### ISSUE THREAD

**Issue by anup2017** [instructure/canvas-lms#1163]
Trying to install canvas on my local computer (Ubuntu 16.04) by following  https://github.com/instructure/canvas-lms/wiki/Production-Start

```
anup@Ultron:/var/canvas$ sudo /etc/init.d/canvas_init start
/var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/settings.rb:67:in `read': Permission denied @ rb_sysopen - /var/canvas/config/delayed_jobs.yml (Errno::EACCES)
	from /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/settings.rb:67:in `worker_config'
	from /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/cli.rb:64:in `load_and_apply_config!'
	from /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/cli.rb:27:in `run'
	from /var/canvas/script/delayed_job:11:in `<main>'

```

And also when i'm running https://localhost/ on my local computer, it looks like

![screenshot from 2017-11-23 17-36-57](https://user-images.githubusercontent.com/26286192/33172284-84287da6-d075-11e7-8bdf-b26e48ae5bea.png)

What i have to do?, 
please help

Thank you!

**Comment by simonista** [comment]
The error you posted is probably the problem: `Permission denied @ rb_sysopen - /var/canvas/config/delayed_jobs.yml (Errno::EACCES)`.  Check out file permissions.
