### ISSUE TITLE
Proper page view is not coming

### ISSUE THREAD

**Issue by anup2017** [instructure/canvas-lms#1165]
![screenshot from 2017-11-24 11-06-56](https://user-images.githubusercontent.com/26286192/33197161-bbfb79ba-d109-11e7-9c41-3522a2cdc609.png)

Can anyone give me some suggestions please.

Thank You

**Comment by simonista** [comment]
Hey @anup2017, if I had to guess just from the screenshot, it looks like apache isn't configured correctly.  We try to keep github issues focused just on canvas functionality bugs, you might try the [mailing list](https://github.com/instructure/canvas-lms/wiki#getting-help) to get more eyes on this issue.
