### ISSUE TITLE
Error when merging users who have attachments

### ISSUE THREAD

**Issue by va7map** [instructure/canvas-lms#1166]
### Summary:

When merging a user who has at least an attachment into another user, a Page Error occurs. The underlying error is a violation of this unique constraint in the database:

> `index_user_merge_data_records_on_context_id_and_context_type`

The merge operation halts and remains incomplete. For example, the previous user was not deleted.

### Steps to reproduce:

 1. Enroll two new users (A and B) into two courses
 2. As user A, upload a file to their personal space
 3. As an admin, merge user A into user B

### Expected behavior:

Canvas successfully merges user A into user B.

### Additional notes:

I traced the problem to [line 130 of `lib/user_merge.rb`](https://github.com/instructure/canvas-lms/blob/579ea9305f6d2d7420293d84a3594031c4fb603b/lib/user_merge.rb#L130), when it's recording the migration of the previous user's attachments. Inexplicably, the `UserMergeDataRecord` for the context (i.e. attachment),  previous user, and `UserMergeData` — which should be unique for each merge attempt — already exists.

I was only able to reproduce this in an open-source Canvas instance. Canvas Cloud seems to be unaffected.

**Comment by simonista** [comment]
Hey @va7map, that's odd.  @roor0, any thoughts?

**Comment by roor0** [comment]
I have no idea what could be going on, that is really weird.
@va7map you can reproduce this every time with new users?
if you were to modify line 129 to be `attachments = Attachment.where(user_id: from_user).uniq`
does that solve the issue?

129 is supposed to get all the attachments for a user. I have no idea how more than one would be returned right there. 
130 takes the attachments and stores a record of them
it should be unique per [:context_id, :context_type, :user_merge_data_id, :previous_user_id]
in this case context is attachment, and I there is no where else that we are passing them into there.

**Comment by va7map** [comment]
Hi @roor0, thanks for looking into this.

Adding `.uniq` or `.distinct` to line 129 does not solve the issue. The former gave a deprecation error, and the latter resulted in the same error as before — duplicate key value violates unique constraint.

I looked more closely at the Rails server output and found that it was `INSERT`-ing the same `UserMergeDataRecord` for the same attachment more than once. Not only that, it was actually running a lot of the same SQL statements again. Then I realized everything was in a `Shard.with_each_shard` block that began on line 56.

Now this wouldn't be a problem if on subsequent iterations the attachment is no longer associated with `from_user`, but [`Attachment::migrate_attachments`](https://github.com/instructure/canvas-lms/blob/579ea9305f6d2d7420293d84a3594031c4fb603b/app/models/attachment.rb#L1797) doesn't seem to change the `user_id` of the original attachment. I'm not too familiar with shards, so I'm just guessing here: When it gets to line 130 a second time, **if** `from_context` and `to_context` both exist on the same shard, the migrated attachment will have the same `user_id`, and line 130 will blindly created another `UserMergeDataRecord` with the same attachment.

**Comment by va7map** [comment]
This is still happening to us in the 2018-03-10.19 release.

Are you able to replicate this at all?

**Comment by grahamb** [comment]
We've been able to narrow this down to the `Shard.with_each_shard` call in [`lib/user_merge.rb:56`](https://github.com/instructure/canvas-lms/blob/master/lib/user_merge.rb#L56). In our open-source instance, without Instructure's Special Sharding Sauce™ plugin, the concatenated list of shards generated by `from_user.associated_shards + from_user.associated_shards(:weak) + from_user.associated_shards(:shadow)` is an array of three identical shards (the default shard). So, when the loop runs, the first one succeeds and the files are moved, but on the second pass it tries to move the same files with the same IDs and it throws the PG duplicate key violation error.

The quick fix is to `uniq` the list of shards being passed to `Shard.with_each_shard`. [This commit](https://github.com/sfu/canvas-lms/commit/2c56c1e05efc13737232fbb645e480e09fa95562) on our fork shows the change.

I can open a PR if this is something you'd like to take upstream. I'm still trying to write a spec that fails to merge a user with attachments (without the fix), but I'm not having much luck with it.

**Comment by ccutrer** [comment]
strong work, @grahamb. the assumption from the Special Sauce™ plugin is that any particular shard is only associated to a user under one strength (strong, weak, shadow). I'm pushing up a commit that makes User#associated_shards return an empty array for all associations except for strong, to preserve this assumption, and possibly fix any other code that makes the same. If you want to keep working on a spec to verify this particular case, though, that would be greatly appreciated.

**Comment by grahamb** [comment]
@ccutrer I'll keep an eye out for that commit. I spent most of last Friday trying to get a spec to work, but I think I'm running into a problem with how sharding works in the specs. I've tried adding an attachment to a user, but I can't get the test to fail. There's already a test in place that to my mind should be failing as it includes attachments [`it "should move user attachments and handle duplicates"`](https://github.com/sfu/canvas-lms/blob/2c56c1e05efc13737232fbb645e480e09fa95562/spec/lib/user_merge_spec.rb#L474), but it also passes.

**Comment by grahamb** [comment]
Ah, just saw the commit. Yeah, we were wondering about the `associated_shards` method and how it appeared to be ignoring its arguments.

**Comment by ccutrer** [comment]
ah. unless the spec is in a `describe` block that includes `specs_require_sharding` at the top, Switchman won't be initialized, and `Shard.with_each_shard` will ignore whatever arguments you pass it: https://github.com/instructure/switchman/blob/master/app/models/switchman/shard_internal.rb#L162
