### ISSUE TITLE
Cannot adopt Chinese (Traditional) locale when inferring locale from browser

### ISSUE THREAD

**Issue by tp9106** [instructure/canvas-lms#1167]
### Summary:
When setting language to be System Default in canvas and visiting canvas pages with browser language set to Chinese (Traditional), the pages shows in Chinese (Simplified) or English instead of Chinese (Traditional)

### Steps to reproduce:
1. In canvas, set Language to be System Default
2. In browser, set the language to be Chinese (Traditional)
3. Visit any canvas page

### Expected behavior:
Canvas pages should show with Chinese (Traditional) locale

### Additional notes:
I’ve tried several browsers and the inferred locale behaviors are summarized as below:

Browser | Accept-Language Header | Inferred Locale
-- | -- | --
Chrome v62.0.3202.94 | zh-TW,zh;q=0.9,en;q=0.8,en-US;q=0.7 | Chinese (Simplified)
Firefox v57.0 | zh-TW,zh;q=0.8,en-US;q=0.5,en;q=0.3 | Chinese (Simplified)
IE v11.0.9600.18837 | zh-TW | English at Login Page, Chinese (Simplified) at Other pages

The code dealing with inferred locale seems to be at https://github.com/instructure/canvas-lms/blob/stable/lib/locale_selection.rb#L63

After experimenting with rails console, I have the following observations:
1. `zh-TW` won’t match any root key at `config/locales/*.yml`.
2. `zh` will match both `zh-Hans` and `zh-Hant`, but `zh-Hans` always take precedence after sorting.

In my local instance this is resolved by change the keys in `config/locales/locales.yml` and `config/locales/zh-Hant.yml` from `zh-Hant` to `zh-TW`. Cloud version seems have the same issue.

Not sure if it is the standard but `zh-TW` and `zh-CN` seems compatible to most browsers.

**Comment by simonista** [comment]
Hi @tp9106, thanks for the report, we're looking into this.
