### ISSUE TITLE
Importing of QTI file ignores rubricBlock elements

### ISSUE THREAD

**Issue by CreepyGnome** [instructure/canvas-lms#1168]
### Summary:
When you import a QTI zip file that has rubricBlock elements as specified in the QTI 2 spec canvas ignores them without any warnings on the import, and when viewing the question the instructions are missing that are in a rubricBlock.  rubricBlocks can be in test parts, sections and item bodies.

### Steps to reproduce:

1. Create a new empty course
2. Go to course settings
3. Select Import Course Content
4. Choose QTI .zip file from content type drop down
5. Select the source to be the QTI Without any RubricBlocks.zip file attached
6. Click Import and it will be successful
7. Go to Quizzes 
8. Click Preview
9. Notice the first question's instructions are "Its True" 
10. Repeat the above steps in a new course and use the QTI With RubricBlock on first Question.zip file attached
11. You will notice the first question's instructions are empty.

### Expected behavior:
That all QTI 2 specs are followed, and that rubricBlocks would be imported as instructions in their corresponding locations.

### Additional notes:

[QTI Without any RubricBlocks.zip](https://github.com/instructure/canvas-lms/files/1511776/QTI.Without.any.RubricBlocks.zip)

[QTI With RubricBlock on first Question.zip](https://github.com/instructure/canvas-lms/files/1511777/QTI.With.RubricBlock.on.first.Question.zip)

**Comment by simonista** [comment]
Hi @CreepyGnome, thanks for the report.  Let me see if I can track someone down who can speak to this more intelligently than I can.
