### ISSUE TITLE
Email Notifications send too many emails at once.

### ISSUE THREAD

**Issue by The-Wolf312** [instructure/canvas-lms#1169]
**Request**
When using canvas and setting email notifications to on too many emails are sent at once. For instance, when instructors post multiple grades at once with this system individual emails are sent for each grade by default or if an instructor posts a plethora of announcements each announcement gets its own email.
I propose an option to suppress email notifications after the system sends a user-defined number of email notifications. This could be expanded upon by extending this to push notifications as well.

**Comment by simonista** [comment]
Hi @The-Wolf312, thanks for the feature request. We do have some per-user controls of how frequently notifications get sent, per category and channel, see https://guides.instructure.com/m/4212/l/710344-how-do-i-set-my-canvas-notification-preferences-as-a-student.

If you're suggesting something else, the best place for feature requests is in the canvas community: https://community.canvaslms.com/community/ideas.  That'll get the most eyes on it, both from others in the community that might have a similar issue, and from canvas product managers.
