### ISSUE TITLE
Submission Upload Causes Failure

### ISSUE THREAD

**Issue by austince** [instructure/canvas-lms#1172]
### Summary:
Submitting assignments via upload sometimes fails on Chrome, and JS error is thrown.

### Steps to reproduce:

 1. Go to an assignment
 2. Click choose file 
 3. Click Submit

### Expected behavior:

Uploading a submission shouldn't fail.

### Additional notes:

My system:  
- Google Chrome 63.0.3239.70
- Ubuntu 17.04

The Error is:
```
Uncaught TypeError: Cannot read property 'errors' of undefined
    at HTMLIFrameElement.A (vendor.bundle-4e4b4c4a29.js:1)
    at HTMLIFrameElement.<anonymous> (vendor.bundle-4e4b4c4a29.js:1)
    at HTMLIFrameElement.dispatch (vendor.bundle-4e4b4c4a29.js:1)
    at HTMLIFrameElement.s (vendor.bundle-4e4b4c4a29.js:1)
    at Object.trigger (vendor.bundle-4e4b4c4a29.js:1)
    at init.triggerHandler (vendor.bundle-4e4b4c4a29.js:1)
    at HTMLIFrameElement.onload (95450:1)
```

On Firefox, however, I get no such error.

Please let me know if this is a known error! Thanks!

**Comment by simonista** [comment]
Hey @austince, thanks for the bug report.  unfortunately, since the js code is minified, that stack trace isn't very useful. You say "sometimes"... any way to narrow that down to be more reproducible? Or if not, how often would you say "sometimes" is?

**Comment by skeetidot** [comment]
This issue also happens when uploading attachments to an email in the Inbox.

**Comment by austince** [comment]
Hey @simonista, apologies for the late response - back at school now. Yes, for every upload on Chrome it fails.

**Comment by simonista** [comment]
Hi @austince and @skeetidot.  I'm not able to reproduce this. I just tested uploading a file to an assignment in Chrome 64 on our production instance and it worked just fine.  I think chrome extensions are a possible culprit -- you might try disabling one by one and testing to see if you can find a culprit.  I think you'll also have more luck getting help through the normal help channel (see https://guides.instructure.com/m/4212/l/710328-how-do-i-get-help-with-canvas-as-a-student).  That channel sees lots of help requests like this and may have more ideas or have seen patterns recently.

Hope that helps!
