### ISSUE TITLE
User profile page the link for messaging the student is overlapping.

### ISSUE THREAD

**Issue by samuels410** [instructure/canvas-lms#1173]
In the below code the data "data-tooltip" tags not closed properly, that leading to text overlapping above the message Icon and not aligned properly.

By visiting student profile page we can reproduce this issue.
Eg: http://localhost:3000/courses/4/users/14

![tool_tip_bug](https://user-images.githubusercontent.com/3351088/33624177-7c4ec3e4-da19-11e7-95e1-0cb49f7649cd.png)

https://github.com/instructure/canvas-lms/blob/0810498363bf52fe60a067123962634bdab7c496/app/views/shared/_profile.html.erb#L61-L66

**Comment by simonista** [comment]
Hey @samuels410, can you say more about the invalid tags?  it looks to me like `data-tooltip` is a valid boolean attribute (see http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes).

I also can't reproduce this locally.  What browser and version are you using? Do you have any custom js/css running? Have you modified any of the view templates? Maybe try re-compiling your cs/jss?
