### ISSUE TITLE
Install not possible on a 4gb machine

### ISSUE THREAD

**Issue by mckernanin** [instructure/canvas-lms#1177]
### Summary:
I've been trying to install Canvas on both AWS Lightsail and Digital Ocean. The docs say that 4GB of ram is recommended, however I haven't been able to complete `bundle exec rake canvas:compile_assets` on either platform's $40/month plans. I was able to complete the compile on a $80/month Digital Ocean droplet, which is 8gb/ram and 4 CPU cores. If this is the min spec to setup canvas, that should be reflected in the README. If this is not intentional, then the task needs to be looked at to see why it won't run on a lesser machine.

### Steps to reproduce:

 1. Try to install canvas on the recommended specs, 4gb of ram
 2. Asset compilation fails

### Expected behavior:
I should be able to setup canvas on a 4gb server, like the readme says

**Comment by simonista** [comment]
Hey @mckernanin, thanks for the issue. Can you say more about whether it actually failed (and presumably the error was OOM?) or just never finished?

**Comment by mckernanin** [comment]
Yep, it failed when it ran out of memory. On the 8GB machine, it took less than 10 minutes. I ran the following command to run the task in the background, and log the output to files:
`RAILS_ENV=production bundle exec rake canvas:compile_assets 2> debug_output.txt 1> stdio.txt &`

You should be able to replicate this by following the Production Install instructions on a 4gb server, and use the above command to get a text file of the errors encountered.

**Comment by tierra** [comment]
There's some configuration settings you can tune that might help you accomplish this a little more reliably with less memory. We certainly recommend at least 4GB ram, but if you're right at that limit, you might still need to play with some of these settings:

- `CANVAS_BUILD_CONCURRENCY=2` - If this isn't defined, Canvas inspects how many CPU cores you have (in your case, 4), and spins up that many processes to build assets concurrently. However, more concurrent processes mean more memory. Try defining this environment variable as 2 instead. Half the memory, but it will take approximately twice as long to compile.

- `DISABLE_HAPPYPACK=1` - HappyPack is another threaded optimization for asset transpilation that speeds up builds significantly, but at the cost of more memory. Define this to disable HappyPack.

- Both `RAILS_ENV` and `NODE_ENV` affect what features are enabled when compiling assets. One of the biggest memory and speed costs of compiling assets is whether you've configured Canvas to build source maps for all bundles. In production mode (as you seem to be using), you can disable source maps by using `JS_BUILD_NO_UGLIFY=1`. This might be very helpful for you.

There might be other settings as well, though I'm not really familiar with them myself

**Comment by karasjoh000** [comment]
I did the above suggestions and I got: 

`[BABEL] Note: The code generator has deoptimised the styling of "/var/canvas/public/javascripts/translations/gradebook.js" as it exceeds the max of "500KB".
internal/child_process.js:328
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at exports.spawn (child_process.js:370:9)
    at Object.exports.fork (child_process.js:59:10)
    at fork (/var/canvas/node_modules/worker-farm/lib/fork.js:12:35)
    at Farm.startChild (/var/canvas/node_modules/worker-farm/lib/farm.js:106:16)
    at Farm.setup (/var/canvas/node_modules/worker-farm/lib/farm.js:68:12)
    at farm (/var/canvas/node_modules/worker-farm/lib/index.js:16:15)
    at Object.processAssets (/var/canvas/node_modules/webpack-parallel-uglify-plugin/lib/uglifier.js:71:16)
    at Compilation.compilation.plugin (/var/canvas/node_modules/webpack-parallel-uglify-plugin/index.js:29:16)
    at Compilation.applyPluginsAsyncSeries (/var/canvas/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/var/canvas/node_modules/webpack/lib/Compilation.js:664:10)
    at Compilation.applyPluginsAsyncSeries (/var/canvas/node_modules/tapable/lib/Tapable.js:195:46)
    at sealPart2 (/var/canvas/node_modules/webpack/lib/Compilation.js:660:9)
    at Compilation.applyPluginsAsyncSeries (/var/canvas/node_modules/tapable/lib/Tapable.js:195:46)
    at Compilation.seal (/var/canvas/node_modules/webpack/lib/Compilation.js:603:8)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:508:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:505:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:475:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rake aborted!
Parallel::UndumpableException: RuntimeError: Error running js:webpack: 
ABORTING
/var/canvas/lib/tasks/js.rake:47:in `block (2 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:69:in `block (5 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:7:in `log_time'
/var/canvas/lib/tasks/canvas.rake:69:in `block (4 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:486:in `call_with_index'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:342:in `block (2 levels) in work_in_threads'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:495:in `with_instrumentation'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:341:in `block in work_in_threads'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:206:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)`

**Comment by ausbin** [comment]
I had the same problem, OP. I ended up creating a big swapfile:

    $ sudo fallocate -l 4G /swapfile
    $ sudo mkswap /swapfile
    $ sudo swapon /swapfile

then once it finishes,

    $ sudo swapoff /swapfile
    $ sudo rm -f /swapfile

Someday I will be web scale enough to have 8+ gig of RAM to spare for "asset processing" with node.js

**Comment by huangdengpan** [comment]
I had the same problem, I tried to do it as @ausbin said, It ran well.
ops,..
Canvas out of service at some times.
There is no response of Canvas and after 1 minute, it shows an error page, after 5 minutes later, it runs.

4G内存的服务器中，可以运行，但是经常无响应后报错。等待5分钟后，canvas又恢复了服务。
