### ISSUE TITLE
Error with database population in production start

### ISSUE THREAD

**Issue by karasjoh000** [instructure/canvas-lms#1179]
### Summary:
Ran the command **RAILS_ENV=production bundle exec rake db:initial_setup** and got this error:
`/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
rake aborted!
Psych::SyntaxError: (/var/canvas/config/security.yml): mapping values are not allowed in this context at line 3 column 17
/var/canvas/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:149:in `load'
/var/canvas/config/application.rb:159:in `load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:157:in `block in load_file'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:157:in `open'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:157:in `load_file'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb:33:in `safe_load_file'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb:22:in `load_file_with_options'
/var/canvas/lib/tasks/db_load_data.rake:22:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/karasjoh000/.rvm/gems/ruby-2.4.0/bin/bundle:23:in `load'
/home/karasjoh000/.rvm/gems/ruby-2.4.0/bin/bundle:23:in `<main>'
/home/karasjoh000/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/karasjoh000/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:initial_setup => db:generate_security_key
(See full trace by running task with --trace)`
### Steps to reproduce:

 1.RAILS_ENV=production bundle exec rake db:initial_setup

### Expected behavior:
Needs to prompt CANVAS_LMS_ADMIN_EMAIL, CANVAS_LMS_ADMIN_PASSWORD, etc..
### Additional notes:

**Comment by tierra** [comment]
This means your `config/security.yml` file is improperly formatted for YAML. You may want to validate that config file to see what's wrong with it.

**Comment by karasjoh000** [comment]
Yes thanks, fixed the security file. Canvas is running for me.
