### ISSUE TITLE
Change domain of docker canvas install

### ISSUE THREAD

**Issue by karasjoh000** [instructure/canvas-lms#1180]
### Summary:
I installed canvas with docker but it is running on "canvas.docker" (which does not exist) and I want it running on localhost. What files need to be modified? 

I am running a 8G DigitalOcean ubuntu server. I do not know where I can access the app. The docker install script has successfully finished.

**Comment by tierra** [comment]
The docker-compose configuration for Canvas is primarily meant for local development environments. You may want to setup your server using the Production Start guide instead:

https://github.com/instructure/canvas-lms/wiki/Production-Start
