### ISSUE TITLE
TypeError: t is undefined during file submission

### ISSUE THREAD

**Issue by rvolosatovs** [instructure/canvas-lms#1184]
### Summary:
University I study in uses canvas LMS(https://canvas.tue.nl/).
When I try to submit a file, the page keeps refreshing and nothing happens(except for the error in console)
### Steps to reproduce:

 1. Go to submission page
 2. Choose file, press submit
 3. Wait indefinetly, page just keeps refreshing.
```log
TypeError: t is undefined  vendor.bundle-bb01dde2dd.js:1:259505
```
appears in the JS console.
### Expected behavior:
File is submitted
### Additional notes:
Browser is Mozilla Firefox 57.0.2

**Comment by rvolosatovs** [comment]
Turned out, the issue was related to an extension.

**Comment by simonista** [comment]
oh good! glad you got it sorted out

**Comment by simonista** [comment]
In the future, you should probably use the "Help" link in-app.  That will get you routed to dedicated support for canvas for your school's instance.

**Comment by rvolosatovs** [comment]
Cool, will do!
