### ISSUE TITLE
[BABEL] Note: The code generator has deoptimised the styling

### ISSUE THREAD

**Issue by dev2me** [instructure/canvas-lms#1187]
### Summary:
When I compile the assets, there comes a time when I get the message of Babel with the phrase: 
[BABEL] Note: The code generator has deoptimised the styling of "/home/develop/canvas-lms/public/javascripts/translations/gradebook.js" as it exceeds the max of "500KB". Arriving to take two hours in that process. Any solution regarding this?. Thanks!
### Steps to reproduce:

 1. RAILS_ENV=production bundle exec rake canvas:compile_assets
 2.
 3.

### Additional notes:

<img width="890" alt="captura de pantalla 2017-12-22 a la s 02 47 23" src="https://user-images.githubusercontent.com/13855165/34291585-7c3878d6-e6c2-11e7-9580-2a02dd1043f7.png">

**Comment by simonista** [comment]
Hey @dev2me, is your issue that it's taking forever to finish?  If so maybe take a look at https://github.com/instructure/canvas-lms/issues/1177?  Or is your issue specifically about the "code generator has deoptimised the styling..." message?

**Comment by dev2me** [comment]
Hey @simonista, My problem is probably related to the issue you mention. But I've already tried to try the solution they give in the comments of that issue but it does not work

**Comment by chaseWillden** [comment]
I'm seeing the issue too.

**Comment by hushino** [comment]
my solution:
options: {
                    compact: true
                }

**Comment by BobLisa** [comment]
I had to seen this issue,and as this error:The code generator has deoptimised the styling of "xxx/xxx/templates.js  as it exceeds the max of 500KB " when a templates.js document was packaged for webpack.So I found some method to resolve it.  I know a  truthful thing Because we could use the different program frames.
You can find gulpfile.js and search the word "babelify", exmaple :

bundler.transform("babelify", { "compact": false,presets: ["es2015"] }); 

you can see above setting ,I only added "compact":false, Hope to help you.

**Comment by omarkhan** [comment]
Is this still happening? Does it actually cause any problems?

**Comment by jcyh0120** [comment]
I saw this note too

`[BABEL] Note: The code generator has deoptimised the styling of "D:/xxx/app.bundle.min.js" as it exceeds the max of "500KB".`

I don't know if it  breaks anything.

**Comment by jaysire** [comment]
@dev2me I'm also getting the same message but it's not breaking my project. I read it's not necessarily a ''bad' error. They even went ahead and suggested changing my code on the exclude to include node_modules but for some reason my project must be compiling the node_modules files as well thus exceeding the '500kb' limit, but babel fixes it for you by deoptimizing the style in bundle.js file  `loader: [exclude: /(node_modules|bower_components)/]`
<img width="1280" alt="screen shot 2018-06-02 at 1 38 00 am" src="https://user-images.githubusercontent.com/37417123/40872167-280d53c0-6607-11e8-8d96-60536d6faef2.png">

**Comment by nemixe** [comment]
i have the same error, this doesn't break anything when you run on localhost but i have a trouble when i deploy it to heroku and zeit now, it break my pwa configuration, the sw.js file link to wrong precaching file so the pwa isn't working anymore

**Comment by nemixe** [comment]
i have just fix the warning, but my pwa still broken, i'm sure the warning is not break anything

**Comment by Goran7777** [comment]
Old rule,dont look at warnings,look and solve only the errors.

**Comment by semz-ui** [comment]
i'm having this issue. Anyone who could help please??
