### ISSUE TITLE
Getting all students in a view has less data if using recommend api endpoint instead of deprecated endpoint

### ISSUE THREAD

**Issue by me97esn** [instructure/canvas-lms#1188]
### Summary:
When using the api to get info about all the students in a course I started using the deprecated endpoint GET /api/v1/courses/:course_id/students.
This worked fine, I get data like this for every user:
`[
    {
        "id": 1268,
        "name": "Def Abc",
        "sortable_name": "Abc, def",
        "short_name": "Abc, def",
        "sis_user_id": "123123123",
        "integration_id": null,
        "sis_login_id": "abc@kth.se",
        "sis_import_id": 12021,
        "login_id": "qwerty"
    },`

If I instead change to the following endpoint for the same course: GET /api/v1/courses/:course_id/users?enrollment_type[]=student
then a lot of the fields are missing. I only get the following fields for some of the users:

`[{
        "id": 1268,
        "name": "Def Abc",
        "sortable_name": "Abc, def",
        "short_name": "Abc, def"
    },`

### Steps to reproduce:

 1. query the endpoint GET /api/v1/courses/:course_id/students 
 2. query the endpoint GET /api/v1/courses/:course_id/users?enrollment_type[]=student
 3. Compare the results between the two responses

### Expected behavior:
The deprecated endpoint and the recommended endpoint returns the same data.
### Additional notes:

**Comment by ccutrer** [comment]
The non-deprecated endpoint doesn't include login information for users that are only invited to the course. Once the student accepts the invitation and is actively enrolled in the course, it will include the additional information (assuming you have permission to see it - which you presumably do since you're seeing it in the deprecated version).

**Comment by me97esn** [comment]
Thanks @ccutrer , that explains everything.
