### ISSUE TITLE
Get last_login of a student account

### ISSUE THREAD

**Issue by rahuleager** [instructure/canvas-lms#1190]
### Summary:
I am using canvas api to `GET /api/v1/users/self/profile` & `GET /api/v1/users/self` where I expect the `last_login` field (although optional) to show up as a part of the User object https://canvas.instructure.com/doc/api/users.html

### Steps to reproduce:
 1. Use https://www.hurl.it/
 2. GET `URL /api/v1/users/self`
 3. Add header - `Authorization with Bearer <canvas_token_id>`

### Expected behavior:
Return last_login in a response like 
```
// A Canvas user, e.g. a student, teacher, administrator, observer, etc.
{
  // The ID of the user.
  "id": 2,
  // The name of the user.
  "name": "Sheldon Cooper",
  // The name of the user that is should be used for sorting groups of users, such as
  // in the gradebook.
  "sortable_name": "Cooper, Sheldon",
  // A short name the user has selected, for use in conversations or other less
  // formal places through the site.
  "short_name": "Shelly",
  // The SIS ID associated with the user.  This field is only included if the user
  // came from a SIS import and has permissions to view SIS information.
  "sis_user_id": "SHEL93921",
  // The id of the SIS import.  This field is only included if the user came from a
  // SIS import and has permissions to manage SIS information.
  "sis_import_id": 18,
  // The integration_id associated with the user.  This field is only included if the
  // user came from a SIS import and has permissions to view SIS information.
  "integration_id": "ABC59802",
  // The unique login id for the user.  This is what the user uses to log in to
  // Canvas.
  "login_id": "sheldon@caltech.example.com",
  // If avatars are enabled, this field will be included and contain a url to
  // retrieve the user's avatar.
  "avatar_url": "https://en.gravatar.com/avatar/d8cb8c8cd40ddf0cd05241443a591868?s=80&r=g",
  // Optional: This field can be requested with certain API calls, and will return a
  // list of the users active enrollments. See the List enrollments API for more
  // details about the format of these records.
  "enrollments": null,
  // Optional: This field can be requested with certain API calls, and will return
  // the users primary email address.
  "email": "sheldon@caltech.example.com",
  // Optional: This field can be requested with certain API calls, and will return
  // the users locale in RFC 5646 format.
  "locale": "tlh",
  // Optional: This field is only returned in certain API calls, and will return a
  // timestamp representing the last time the user logged in to canvas.
  "last_login": "2012-05-30T17:45:25Z",
  // Optional: This field is only returned in certain API calls, and will return the
  // IANA time zone name of the user's preferred timezone.
  "time_zone": "America/Denver",
  // Optional: The user's bio.
  "bio": "I like the Muppets."
}
```

### Additional notes:
In case you don't have Canvas Access token already you can create a new one inside your profile settings

**Comment by spencerolson** [comment]
Hi @rahuleager , unfortunately it looks like those 2 endpoints do not support returning `last_login`. However, the following endpoints will give you `last_login` and might be nice alternatives:

For a single user:
`api/v1/courses/:course_id/users/self?include[]=last_login` (https://canvas.instructure.com/doc/api/courses.html#method.courses.user)

For multiple users:
`api/v1/accounts/:account_id/users?include[]=last_login` (https://canvas.instructure.com/doc/api/users.html#method.users.index)
`api/v1/courses/:course_id/recent_students` (https://canvas.instructure.com/doc/api/courses.html#method.courses.recent_students)
`api/v1/courses/:course_id/users?include[]=last_login` (https://canvas.instructure.com/doc/api/courses.html#method.courses.users)

Thanks,
Spencer

**Comment by rahuleager** [comment]
Thanks @spencerolson 
Although in most of the cases I tested, the response is either null or 401 unauthorized but I will try to test more accounts. I am testing only from a student's account currently with the authorization token
