### ISSUE TITLE
MakeWikiPageContextNotNull migration fails with context_type fields all null

### ISSUE THREAD

**Issue by breiter** [instructure/canvas-lms#1193]
### Summary:
Performing an in-place  migration of canvas from an earlier 2017 stable build to the current stable build fails because  wiki_pages table has columns context_id and context_type which are all null and there is a data migration that attempts to set those columns not null without ensuring that there is data.

### Steps to reproduce:

Running `rake db:migrate` fails.

```
==  MakeWikiPageContextNotNull: migrating =====================================
-- change_column_null(:wiki_pages, :context_type, false)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::NotNullViolation: ERROR:  column "context_type" contains null values
: ALTER TABLE "wiki_pages" ALTER "context_type" SET NOT NULL
```

I'm trying to perform an in-place update of canvas and I'm running into a problem where the context_type field for every row in the wiki_pages table is null, which causes the data migration to fail.

I can see that there is a class `/lib/data_fixup/populate_context_on_wiki_pages.rb` that should populate context_id and context_type, but it isn't quite obvious to me how to determine and manually correct values context_id and context_type on the wiki_pages table.

### Expected behavior:
Migration should fill the columns with appropriate data where they fields are null.

**Comment by simonista** [comment]
Hey @breiter, sorry for the trouble.

Those columns were added in https://github.com/instructure/canvas-lms/blob/stable/db/migrate/20170714191148_add_context_to_wiki_pages.rb and that data fixup job should have been queued to run in https://github.com/instructure/canvas-lms/blob/stable/db/migrate/20170714192323_populate_context_on_wiki_pages.rb.

It may be that this migration ran and queued the data_fixup but the job hasn't had a chance to run yet. So it may be as simple as just starting jobs and letting them run.  Or you could manually run `DataFixup::PopulateContextOnWikiPages` from a production rails console.

We should probably turn this into a synchronous action to prevent this issue for users updating from further back like you.  I'll talk to some people internally about that.

**Comment by breiter** [comment]
I imported the changed `db/migrate/20170714192323_populate_context_on_wiki_pages.rb` from commit 4b670e093f920967e277f342c2e30a6b07a83514 and ran the migration again. 

```
$  RAILS_ENV=production bundle exec rake db:migrate:redo VERSION=20170714192323
```
This populated the context_id and context_type.

And then, the normal migration continues past this point but again fails. This time on a check constriant.

```
$ RAILS_ENV=production bundle exec rake db:migrate

...

==  AddNotNullConstraintToScoresCourseScore: migrating ========================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

PG::CheckViolation: ERROR:  check constraint "course_score_not_null" is violated by some row
```

This is migration `db/migrate/20171013185152_add_not_null_constraint_to_scores_course_score.rb`

I think the problem is that `db/migrate/20170816172211_populate_course_score_on_scores.rb` also runs delayed and this change fixes the issue:

```ruby
class PopulateCourseScoreOnScores < ActiveRecord::Migration[5.0]
  tag :postdeploy

  def up
    DataFixup::PopulateScoresCourseScore.run
  end

  def down
  end
end
```

```
$ RAILS_ENV=production bundle exec rake db:migrate:redo VERSION=20170816172211
(in /opt/var/canvas)
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/opt/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
1: production:public
Revert migration PopulateCourseScoreOnScores (20170816172211) ? [y/N/a] > y
==  PopulateCourseScoreOnScores: reverting ====================================
==  PopulateCourseScoreOnScores: reverted (0.0000s) ===========================

1: production:public
==  PopulateCourseScoreOnScores: migrating ====================================
==  PopulateCourseScoreOnScores: migrated (0.0326s) ===========================
```

Running the normal migration still fails because even though the migration 20171013185152_add_not_null_constraint_to_scores_course_score.rb failed because the check constraint was violated, it did actually create the check constraint object. 

```
Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateObject: ERROR:  constraint "course_score_not_null" for relation "scores" already exists
:       ALTER TABLE "scores"
       ADD CONSTRAINT course_score_not_null CHECK (course_score IS NOT NULL) NOT VALID;

...

 Caused by:
PG::DuplicateObject: ERROR:  constraint "course_score_not_null" for relation "scores" already exists
```

I manually rant this DDL statement to bring the actual schema into the same state as expected by migrations:

```
ALTER TABLE "scores"
DROP CONSTRAINT course_score_not_null
```

Now `RAILS_ENV=production bundle exec rake db:migrate` runs to completion.

**Comment by srdurai** [comment]
Hi brieter,

I ran into the same problem and stuck in the last step of your solution. I am also new to canvas and postgres. Could you please brief how to execute the following step. Thanks in advance.

> _I manually rant this DDL statement to bring the actual schema into the same state as expected by migrations:
> ALTER TABLE "scores"
> DROP CONSTRAINT course_score_not_null_

Do you mean you drop the table from psql? Tried them on psql, got the following error:

> _postgres=# ALTER TABLE "scores" DROP CONSTRAINT course_score_not_null;
> ERROR:  relation "scores" does not exist_
Or we have to edit the file: db/migrate/20171013185152_add_not_null_constraint_to_scores_course_score.rb
