### ISSUE TITLE
Rubric feedback contents should be saved in case of error.

### ISSUE THREAD

**Issue by sinistersnare** [instructure/canvas-lms#1197]
### Summary:

Currently, when filling out a rubric evaluation, if the page closes for any reason, all progress on the rubric will also be lost.

Is there any way to save the data in the rubric so that data is not lost?

### Steps to reproduce:

 1. Start filling in evaluation rubric
 2. Quit page (Ctrl/Cmd + T)
 3. Reopen page (Ctrl/Cmd + Shift + T)
4. Reopen Rubric evaluation.
5. form is now empty.

### Expected behavior:

The rubric should reopen where you left off.

**Comment by omarkhan** [comment]
I don't think this is something we are planning to implement. Could you submit a pull request with the proposed changes?
