### ISSUE TITLE
Email Notification

### ISSUE THREAD

**Issue by AbithaVek** [instructure/canvas-lms#1209]
### Summary:
We are running a self-hosted canvas application. We have enabled the email notification for the user while creating an user/enrolling to a course/announcements etc. We have downloaded the canvas code base version as of April 2017. We are receiving an email but the HTML is not rendering. It just comes as a plain text with HTML tags.
### Steps to reproduce:

 1.Create an user
 2.Opt for email Notification
 3.Email is received

### Expected behavior:
Email should be aligned as per the html structure. We have customized the email template and we see the html not getting rendered in our OUTLOOK/Gmail mail boxes.
### Additional notes:
With the latest code base of canvas we are not facing this issue.

Any help appreciated here!

Thanks!
![error](https://user-images.githubusercontent.com/31066816/34987308-b1cd66b4-fae0-11e7-855f-3b68a12223c7.png)

**Comment by srinivasanlr** [comment]
As an update we are using the canvas code version as : release/2017-04-22.05 repository cloned from Git hub

**Comment by shyammohankanojia** [comment]
@AbithaVek  as per your additional Note, you can update it.

**Comment by omarkhan** [comment]
Closing as this issue is not present on latest master.
