### ISSUE TITLE
Page in unpublished module gives message saying "not unlocked", rather than "not published"

### ISSUE THREAD

**Issue by ChristopherKingChemist** [instructure/canvas-lms#1211]
### Summary
A link to a page in an unpublished module gives the students the message, "This page is part of the module _Chapter Assignment Pages_ and hasn't been unlocked yet."  Unlocking the module or assignment does nothing, since neither the module nor the assignment was locked.  The message would be more helpful if it said "...and hasn't been published yet."
### Steps to reproduce

 1.  Go to a module containing a page that has been published.  Make the state of the module "unpublished".  Add a link to that page in another page, such as the "Home" page.
 2.  In "Settings", click on student view.
 3.  Click on the link that was created.  A message like the following message is displayed regarding that page:
"This page is part of the module _Chapter Assignment Pages_ and hasn't been unlocked yet."

### Expected behavior
The message should say:
"This page is part of the module _Chapter Assignment Pages_, which hasn't been published yet."

### Additional notes

**Comment by omarkhan** [comment]
Fair point. Could you submit a pull request for this change?

**Comment by ChristopherKingChemist** [comment]
The fix for this will involve two files:

- lib/canvas/lock_explanation.rb
- public/javascripts/content_locks.js

Notes in those two files state that, when one is changed, the other should be similarly modified.
It is possible that the following file should also be modified, since it also contains the search term, "This page is part of the module".
spec/selenium/wiki_pages_spec.rb
In lock_explanation.rb, the "lock message" is generated by checking the following criteria, in order:
- the current time is before the "lock_at" time
- the current time is after the "lock_until" time
- the object's module has its workflow_state set to unpublished.
- the object's module is locked because the current time is not between "lock_at" and "lock_until".
- none of the above.
The issue arises because the quiz ends up in the last category, which gives the misleading message.  Ideally, an additional criteria would be added:  object is not published, but is in a published module.  
Perhaps someone else would be willing to work on this.  I've not yet figured out how to determine if an assignment is unpublished.  (I don't want to spend all of spring break learning ruby, and the Canvas code!)
