### ISSUE TITLE
Change rubric trashcan icon tooltip from "Delete rubric" to "Remove rubric"

### ISSUE THREAD

**Issue by ChristopherKingChemist** [instructure/canvas-lms#1212]
### Summary
An assignment containing a rubric has a trashcan icon with a tooltip that says "delete rubric".  Clicking the icon removes the rubric from the assignment, but does not delete the rubric.  If the tooltip said "remove rubric", users would not have to go to the help pages to make sure the rubric is still available after clicking that icon.
### Steps to reproduce

 1.  In an assignment, click "+ Rubric" to add a rubric to the assignment.  Click "Find a Rubric" to locate a rubric to use, then click on "Use this rubric".
 2.  The rubric will have in the upper right corner a trashcan icon.  Hold the mouse cursor over that trashcan, and the tooltip, "Delete rubric" appears.

### Expected behavior
The tooltip should say "Remove rubric".
### Additional notes
The point is that removing a rubric from an assignment does not delete the rubric from the collection of available rubrics.

**Comment by omarkhan** [comment]
Fair point. Could you submit a pull request with the proposed change?
