### ISSUE TITLE
Question regarding incoming_mail.yml

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#1213]
Hello, 

### **I have to see my e-mails corresponence inside Canvas LMS (Inbox button). What is the best way to do this? 
I tried to use config/incoming_mail.yml file with my local SMTP/IMAP/POP3 credentials and I got next error inside log/delayed_job.log:**

`INSERT INTO "error_reports" ("backtrace", "message", "created_at", "updated_at", "email", "data", "category") VALUES ('/usr/lib/ruby/2.4.0/net/imap.rb:1490:in `connect''
/usr/lib/ruby/2.4.0/net/imap.rb:1490:in `start_tls_session''
/usr/lib/ruby/2.4.0/net/imap.rb:1083:in `initialize''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/imap_mailbox.rb:42:in `new''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/imap_mailbox.rb:42:in `block in connect''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:162:in `block in timeout_method''
/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout''
/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch''
/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch''
/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch''
/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout''
/home/canvas/public_html/lib/canvas.rb:251:in `short_circuit_timeout''
/home/canvas/public_html/lib/canvas.rb:220:in `timeout_protection''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:161:in `timeout_method''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/configurable_timeout.rb:68:in `with_timeout''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/imap_mailbox.rb:42:in `connect''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:252:in `process_mailbox''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:82:in `block in process''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:78:in `each''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:78:in `process''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/performable_method.rb:23:in `perform''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/backend/base.rb:248:in `block in invoke_job''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:66:in `block in initialize''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:71:in `execute''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:44:in `run_callbacks''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/backend/base.rb:245:in `invoke_job''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:152:in `block (2 levels) in perform''
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:146:in `block in perform''
/home/canvas/public_html/config/initializers/delayed_job.rb:140:in `block (2 levels) in <top (required)>''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:81:in `batch''
/home/canvas/public_html/config/initializers/delayed_job.rb:139:in `block in <top (required)>''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:84:in `block (2 levels) in add''
/home/canvas/public_html/config/initializers/delayed_job.rb:103:in `block (2 levels) in <top (required)>''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:75:in `time''
/home/canvas/public_html/config/initializers/delayed_job.rb:102:in `block in <top (required)>''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:84:in `block (2 levels) in add''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:66:in `block in initialize''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:84:in `block in add''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:84:in `block in add''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:71:in `execute''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:44:in `run_callbacks''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:143:in `perform''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:116:in `block (2 levels) in run''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:212:in `block in configure_for_job''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:37:in `running_job''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:208:in `configure_for_job''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:115:in `block in run''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:66:in `block in initialize''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:71:in `execute''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:44:in `run_callbacks''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:108:in `run''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:94:in `block (2 levels) in start''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:93:in `loop''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:93:in `block in start''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:66:in `block in initialize''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:71:in `execute''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:44:in `run_callbacks''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:92:in `start''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:97:in `block in spawn_worker''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:108:in `block in fork_with_reconnects''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:105:in `fork''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:105:in `fork_with_reconnects''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:96:in `spawn_worker''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:74:in `block (2 levels) in spawn_all_workers''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:74:in `times''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:74:in `block in spawn_all_workers''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:73:in `each''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:73:in `spawn_all_workers''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:32:in `start''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/cli.rb:96:in `start''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/cli.rb:48:in `run''
/home/canvas/public_html/script/delayed_job:11:in `<main>''', 'SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed', '2018-01-23 14:16:00.764022', '2018-01-23 14:16:00.764022', 'unknown-canvas-nhcpr-com@instructure.example.com', '---
exception_message: ''SSL_connect returned=1 errno=0 state=SSLv3 read server certificate
 B: certificate verify failed''
hostname: my_server.com
pid: 8471
', 'incoming_message_processor') RETURNING "id"`

**### Also I tried to use my google's email test account but got next errors:**

`INSERT INTO "error_reports" ("backtrace", "message", "created_at", "updated_at", "email", "data", "category") VALUES ('/usr/lib/ruby/2.4.0/net/imap.rb:1194:in `get_tagged_response''
/usr/lib/ruby/2.4.0/net/imap.rb:1248:in `block in send_command''
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize''
/usr/lib/ruby/2.4.0/net/imap.rb:1230:in `send_command''
/usr/lib/ruby/2.4.0/net/imap.rb:434:in `login''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/configurable_timeout.rb:92:in `block (3 levels) in wrap_with_timeout''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:162:in `block in timeout_method''
/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout''
/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch''
/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch''
/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch''
/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout''
/home/canvas/public_html/lib/canvas.rb:251:in `short_circuit_timeout''
/home/canvas/public_html/lib/canvas.rb:220:in `timeout_protection''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:161:in `timeout_method''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/configurable_timeout.rb:68:in `with_timeout''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/configurable_timeout.rb:92:in `block (2 levels) in wrap_with_timeout''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/imap_mailbox.rb:44:in `connect''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:252:in `process_mailbox''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:82:in `block in process''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:78:in `each''
/home/canvas/public_html/gems/incoming_mail_processor/lib/incoming_mail_processor/incoming_message_processor.rb:78:in `process''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/performable_method.rb:23:in `perform''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/backend/base.rb:248:in `block in invoke_job''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:66:in `block in initialize''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:71:in `execute''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:44:in `run_callbacks''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/backend/base.rb:245:in `invoke_job''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:152:in `block (2 levels) in perform''
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:146:in `block in perform''
/home/canvas/public_html/config/initializers/delayed_job.rb:140:in `block (2 levels) in <top (required)>''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:81:in `batch''
/home/canvas/public_html/config/initializers/delayed_job.rb:139:in `block in <top (required)>''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:84:in `block (2 levels) in add''
/home/canvas/public_html/config/initializers/delayed_job.rb:103:in `block (2 levels) in <top (required)>''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:75:in `time''
/home/canvas/public_html/config/initializers/delayed_job.rb:102:in `block in <top (required)>''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:84:in `block (2 levels) in add''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:66:in `block in initialize''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:84:in `block in add''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:84:in `block in add''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:71:in `execute''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:44:in `run_callbacks''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:143:in `perform''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:116:in `block (2 levels) in run''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:212:in `block in configure_for_job''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:37:in `running_job''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:208:in `configure_for_job''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:115:in `block in run''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:66:in `block in initialize''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:71:in `execute''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:44:in `run_callbacks''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:108:in `run''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:94:in `block (2 levels) in start''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:93:in `loop''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:93:in `block in start''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:66:in `block in initialize''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:71:in `execute''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/lifecycle.rb:44:in `run_callbacks''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/worker.rb:92:in `start''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:97:in `block in spawn_worker''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:108:in `block in fork_with_reconnects''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:105:in `fork''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:105:in `fork_with_reconnects''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:96:in `spawn_worker''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:74:in `block (2 levels) in spawn_all_workers''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:74:in `times''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:74:in `block in spawn_all_workers''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:73:in `each''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:73:in `spawn_all_workers''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/pool.rb:32:in `start''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/cli.rb:96:in `start''
/home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.13.6/lib/delayed/cli.rb:48:in `run''
/home/canvas/public_html/script/delayed_job:11:in `<main>''', ' Invalid credentials (Failure)', '2018-01-23 14:09:02.846782', '2018-01-23 14:09:02.846782', 'unknown-canvas-nhcpr-com@instructure.example.com', '---
exception_message: " Invalid credentials (Failure)"
hostname: my_server.com
pid: 8146
', 'incoming_message_processor') RETURNING "id"  [production:1 master]
`
Thanks.

**Comment by omarkhan** [comment]
We use github issues for bugs, see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help) for support. Good luck!
