### ISSUE TITLE
Javascript error in Speedgrader in concluded courses

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#1214]
### Summary:
```
Uncaught Error: unmountComponentAtNode(...): Target container is not a DOM element.
    at invariant (invariant.js:39)
    at Object.unmountComponentAtNode (ReactMount.js:609)
    at unmountCommentTextArea (speed_grader.js:678)
    at renderCommentTextArea (speed_grader.js:684)
    at initCommentBox (speed_grader.js:702)
    at Object.domReady (speed_grader.js:1192)
    ...
```
When a teacher opens SpeedGrader for an assignment in a concluded course, the page generates Javascript errors and the page fails to load properly. The teacher must have an enrollment_state of "completed" for this error to trigger. 

The problem seems to be here 
https://github.com/instructure/canvas-lms/blob/4f50397869637c2aca4046b5e4cfb6369b82c895/app/views/gradebooks/speed_grader.html.erb#L321-L323
and here
https://github.com/instructure/canvas-lms/blob/4f50397869637c2aca4046b5e4cfb6369b82c895/public/javascripts/speed_grader.js#L564-L567

When the course is concluded (in my case, because the term end date has passed), @context_enrollement.completed? will be true, and `<div id="speedgrader_comment_textarea_mount_point">` will not be created. `node` will be null, and the error will trigger. 

### Steps to reproduce:

 1. Create a course with a student and an assignment
 2. Set the course's term to a term with an end date in the past
 3. Open the SpeedGrader as a teacher in the course. 

I cannot reproduce this at canvas.instructure.com because I'm not sure how to get a completed enrollment. 

### Expected behavior:
The page should load without errors

### Additional notes:
This seems to be triggering  a second error: 
```
speed_grader.js:1362 Uncaught TypeError: Cannot read property 'hasClass' of null
    at Object.handleStudentChanged (webpack:///./public/javascripts/speed_grader.js?:1362:33)
    at HTMLSelectElement.eval (webpack:///./public/javascripts/speed_grader.js?:470:10)
    ...
```

**Comment by spencerolson** [comment]
Hi @christopher-b , can you try pulling down the most recent changes and checking again? This commit should fix that issue https://github.com/instructure/canvas-lms/commit/1e0edac43f6cd1a2d66d0032c5618f29126bb03c (and that commit was just pulled in via this treesame commit https://github.com/instructure/canvas-lms/commit/2084af1744b6f8c22d8c9d8fe2292aa84e408fcc)

Thanks,
Spencer

**Comment by christopher-b** [comment]
Yes, that did the trick. Thanks.

**Comment by spencerolson** [comment]
Glad to hear it! Thanks for bringing this to our attention.
