### ISSUE TITLE
AccountAuthorizationConfig 

### ISSUE THREAD

**Issue by mahsanaja** [instructure/canvas-lms#1218]
### Summary:
Hi, I am new to ruby. 

When I tried to run 
"bundle exec rails server", in my local host,  I got this error: 

ActiveRecord::RecordNotFound - Couldn't find AccountAuthorizationConfig with [WHERE "account_authorization_configs"."account_id" = $1 AND "account_authorization_configs"."auth_type"
 
  in the quick start, there is no set up for authentication config.
I am wondering how I can solve this problem. 

= $2 AND (workflow_state <> 'deleted')]:
### Steps to reproduce:

 1.=> Booting Puma
=> Rails 5.0.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
 2. Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.1-p111), codename: Russell's Teapot
* Min threads: 0, max threads: 1
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
Started GET "/" for ::1 at 2018-01-25 15:01:13 -0500
 3. ....

ActiveRecord::RecordNotFound - Couldn't find AccountAuthorizationConfig with [WHERE "account_authorization_configs"."account_id" = $1 AND "account_authorization_configs"."auth_type"

### Additional notes:

**Comment by GGDesigan** [comment]
I'm Having the same issue. Any suggestions would be helpful.

**Comment by omarkhan** [comment]
To set up a local development environment, I recommend running `script/docker_dev_setup.sh`. If you still have problems, see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help) - we use github issues for bugs, not support requests.
