### ISSUE TITLE
Bundle install fails in docker

### ISSUE THREAD

**Issue by codeprefect** [instructure/canvas-lms#1221]
### Summary:
running `docker-compose run --rm web bundle install` for a docker deployment fails with the error message below.
There was an error while trying to write to `/usr/src/app/Gemfile.lock`. It is likely that you need to grant write permissions for that path.

### Steps to reproduce:
 1. Checkout source code
 2. run `docker-compose run --rm web bundle install`
 3. fails with error *There was an error while trying to write to `/usr/src/app/Gemfile.lock`. It is likely that you need to grant write permissions for that path.*

### Expected behavior:
Bundle installed successfully 2** gems installed.

### Additional notes:
Operating System - Ubuntu 16.04
RAM: 16GB
Docker: 1.17ce

**Comment by tierra** [comment]
When using docker with linux (without the more common dinghy on OSX), the docker containers don't have write permission to the bind-mounted volume containing the your git checkout of the code.

You can work around this by making the lock file writable in your checkout:

```
touch Gemfile.lock
chmod a+w Gemfile.lock
```

**Comment by codeprefect** [comment]
@tierra, that didn't work either. I had to use `root` all through for now. Hoping I get a fix soon.

**Comment by tierra** [comment]
So those are really the only two known "fixes" to this issue. There's nothing we can change in Canvas to address this, it's just the way docker containers and bind-mounted volumes work. If you have other suggestions for fixes, please feel free to re-open, but I'm just closing this for now.

**Comment by codeprefect** [comment]
Hello @tierra, below is my Dockerfile
```
# GENERATED FILE, DO NOT MODIFY!
# To update this file please edit the relevant template and run the generation
# task `build/dockerfile_writer.rb`

# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
FROM instructure/ruby-passenger:2.4

ENV APP_HOME /usr/src/app/
ENV RAILS_ENV "production"
ENV NGINX_MAX_UPLOAD_SIZE 10g
ENV YARN_VERSION 1.3.2-1

# Work around github.com/zertosh/v8-compile-cache/issues/2
# This can be removed once yarn pushes a release including the fixed version
# of v8-compile-cache.
ENV DISABLE_V8_COMPILE_CACHE 1

USER root
WORKDIR /root
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
  && printf 'path-exclude /usr/share/doc/*\npath-exclude /usr/share/man/*' > /etc/dpkg/dpkg.cfg.d/01_nodoc \
  && echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
  && curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
  && apt-get update -qq \
  && apt-get install -qqy --no-install-recommends \
       nodejs \
       yarn="$YARN_VERSION" \
       libxmlsec1-dev \
       python-lxml \
       libicu-dev \
       postgresql-client-9.5 \
       unzip \
       fontforge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir -p /home/docker/.gem/ruby/$RUBY_MAJOR.0

RUN if [ -e /var/lib/gems/$RUBY_MAJOR.0/gems/bundler-* ]; then BUNDLER_INSTALL="-i /var/lib/gems/$RUBY_MAJOR.0"; fi \
  && gem uninstall --all --ignore-dependencies --force $BUNDLER_INSTALL bundler \
  && gem install bundler --no-document -v 1.15.2 \
  && find $GEM_HOME ! -user docker | xargs chown docker:docker

# We will need sfnt2woff in order to build fonts
COPY build/vendor/woff-code-latest.zip ./
RUN unzip woff-code-latest.zip -d woff \
  && cd woff \
  && make \
  && cp sfnt2woff /usr/local/bin \
  && cd - \
  && rm -rf woff*

WORKDIR $APP_HOME

COPY Gemfile      ${APP_HOME}
COPY Gemfile.d    ${APP_HOME}Gemfile.d
COPY config       ${APP_HOME}config
COPY gems         ${APP_HOME}gems
COPY script       ${APP_HOME}script
COPY package.json ${APP_HOME}
COPY yarn.lock    ${APP_HOME}
RUN find gems -type d ! -user docker -print0 | xargs -0 chown -h docker:docker

# Install deps as docker to avoid sadness w/ npm lifecycle hooks
USER docker
RUN bundle install --jobs 8 \
  && yarn install --pure-lockfile
USER root

COPY . $APP_HOME
RUN mkdir -p .yardoc \
             app/stylesheets/brandable_css_brands \
             client_apps/canvas_quizzes/node_modules \
             gems/canvas_i18nliner/node_modules \
             gems/selinimum/node_modules \
             log \
             node_modules \
             public/dist \
             public/doc/api \
             public/javascripts/client_apps \
             public/javascripts/compiled \
             tmp \
             /home/docker/.bundler/ \
             /home/docker/.cache/yarn \
             /home/docker/.gem/ \
  && find ${APP_HOME} /home/docker ! -user docker -print0 | xargs -0 chown -h docker:docker

RUN touch Gemfile.lock && chown docker:docker ${APP_HOME}Gemfile.lock

USER docker
# TODO: switch to canvas:compile_assets_dev once we stop using this Dockerfile in production/e2e
RUN COMPILE_ASSETS_NPM_INSTALL=0 bundle exec rake canvas:compile_assets
```

It still don't work

**Comment by codeprefect** [comment]
OK. It now works.

I only did a simple create of Gemfile.lock in my app directory before running the bundle install.

**Comment by elquimista** [comment]
@codeprefect Try this:
```Dockerfile
COPY --chown=docker:docker Gemfile.lock ./
```

**Comment by joaodiogocosta** [comment]
This happened to me when before running `bundle install` on the host.

**Comment by sijpkes** [comment]
> ```dockerfile
> COPY --chown=docker:docker Gemfile.lock ./
> ```

This is not working for me, neither are any of the other suggestions and the script won't let you run it as root.  Am I missing something?

**Comment by vmunduri** [comment]
> OK. It now works.
> 
> I only did a simple create of Gemfile.lock in my app directory before running the bundle install.

This worked for me
Thanks.

**Comment by synapticloop** [comment]
Here are my notes for my install on `Ubuntu 24.04.1 LTS x86_64`

For the git clone - the clone directory has to be `/usr/src/app`  - either I missed that part, am unaware of the 'normal' installation directory, or am little behind the times...

Your instance may be a little different

I created a user `canvaslms` and add the user to the `docker` group and `sudoers`

as `root`
```
cd /usr/src/

git clone --depth 1 https://github.com/instructure/canvas-lms.git app

chown -R camvaslms:canvaslms app
```

To fix the Ruby Gemfile permissioning, this is what I did:

as `canvaslms`

```
touch Gemfile.lock
chmod a+w Gemfile.lock

# change permissions on the working directory - this means ANYBODY can write to the directory - use with caution
chmod a+w .

# go through and find all Gemfile.lock files and make them world writable
find . -name Gemfile.*.lock | while read i; do chmod a+w $i; done
```

That seemed to fix the `Bundle install...` phase

Then came the fun with `Yarn install...` phase

I lost count of the directories that had an error of:

> `error An unexpected error occurred: "EACCES: permission denied, mkdir '<dir_name_here>'".`

Even running the script as `root` (commenting out the check in the `./script/docker_dev_setup.sh` file) to no avail, am now stuck on   

> `error An unexpected error occurred: "EACCES: permission denied, mkdir '/usr/src/app/node_modules/@instructure/k5uploader/node_modules'".`

I have manually created the directory, permissioned the directory, deleted the directory, all to no avail.

**Comment by nigelsim** [comment]
@synapticloop I had the same issue. But, I found that there is an undocumented parameter called `CANVAS_SKIP_DOCKER_USERMOD` that is referenced in `script/common/utils/common.sh:188` which will set the container UID to your UID, meaning that all the files will have the correct permissions. To make this have any effect you need to clear `CANVAS_SKIP_DOCKER_USERMOD=''` in `script/docker_dev_setup.sh`.

Also, because I had a few failed previous attempts in this environment, I also had a bunch of Docker compose volumes with the wrong UID, which I deleted using `docker compose rm -v`.

All in all I had to make these 3 changes to make it work on Debian Bookworm, but, it's up and running now. Well, I also had to add a `ports` section to the `docker-compose.override.yml` so I could access the site.

```diff
diff --git a/script/common/os/linux/dev_setup.sh b/script/common/os/linux/dev_setup.sh
index a63c2e2a2b..57545e6201 100755
--- a/script/common/os/linux/dev_setup.sh
+++ b/script/common/os/linux/dev_setup.sh
@@ -2,7 +2,7 @@
 source script/common/utils/common.sh
 source script/common/os/linux/impl.sh
 source script/common/utils/dory_setup.sh
-dependencies='docker,docker-compose 1.20.0'
+dependencies='docker'
 DOCKER_COMMAND="docker compose"
 
 message "It looks like you're using Linux. Let's set that up."
@@ -10,6 +10,6 @@ message "It looks like you're using Linux. Let's set that up."
 set_service_util
 check_dependencies
 check_for_dory
-start_docker_daemon
+#start_docker_daemon
 setup_docker_as_nonroot
 [[ ${skip_dory:-n} == 'y' ]] || start_dory
diff --git a/script/docker_dev_setup.sh b/script/docker_dev_setup.sh
index 533e2bc423..999fc618e9 100755
--- a/script/docker_dev_setup.sh
+++ b/script/docker_dev_setup.sh
@@ -10,7 +10,7 @@ LOG="$(pwd)/log/docker_dev_setup.log"
 SCRIPT_NAME="$0 $@"
 OS="$(uname)"
 DOCKER='true'
-CANVAS_SKIP_DOCKER_USERMOD='true'
+CANVAS_SKIP_DOCKER_USERMOD=''
 
 _canvas_lms_opt_in_telemetry "$SCRIPT_NAME" "$LOG"
```

**Comment by moltenform** [comment]
I kept receiving the error `There was an error while trying to write to /usr/src/app/Gemfile.lock. It is likely that you need to grant write permissions for that path.`

First I created an empty file at `/usr/src/app/Gemfile.lock`. And then I gave permissions to that directory with `sudo chmod -R a+rwx /usr/src/app`. But still got the same error. I tried with CANVAS_SKIP_DOCKER_USERMOD enabled and tried with it disabled, and still got the same error.

I was able to get things to work by following the tip on this page: https://github.com/instructure/canvas-lms/tree/master/doc/docker

```
setfacl -Rm u:9999:rwX,g:9999:rwX .
setfacl -dRm u:9999:rwX,g:9999:rwX .
sudo addgroup --gid 9999 docker-instructure
sudo usermod -a -G docker-instructure $USER
```

In my case, because I was running Fedora, I replaced the addgroup line with this.

```
sudo groupadd --gid 9999 docker-instructure
```

When asked about migrate or drop, I had to choose migrate because drop failed with an error about other processes using the database.

(I disagree with synapticloop, it worked for me to clone in a subdirectory of my home directory).

I was able to get the Canvas processes starting successfully.
