### ISSUE TITLE
File-type module items created via API are unavailable to students

### ISSUE THREAD

**Issue by merichar** [instructure/canvas-lms#1222]
### Summary:
File-type module items, when created through the API, appear to course staff as available to students, but are clearly not when viewing the modules page as a student. It also happens to be that when a member of the course staff clicks through the module item for the first time, the module item is then made available to students.

### Steps to reproduce:
 0. Upload a file to a course and publish it
 1. Create a module under that course
 2. Create a module item in the module above, using the API, and pointing to the file from the first step
 3. Enter Student View; module item will appear unavailable
 4. Leave Student View; item will appear to be available 
 5. Click on the module item
 6. Enter Student View; module item will now be available

### Expected behavior:
The publication status icons next to a module item should correctly reflect a module item's publication status.
 File-type module items created through the API, when pointing to available files, should themselves be available.

### Additional notes:
https://www.youtube.com/watch?v=vsSdO2yefj8

**Comment by omarkhan** [comment]
Closing as this was fixed in edce417
