### ISSUE TITLE
Unable to change Feature Options

### ISSUE THREAD

**Issue by SofiaSousa** [instructure/canvas-lms#1223]
### Summary:
Can't change Admin Feature Options on Settings. 
### Steps to reproduce:

 1. After login, go to Admin > Settings > Feature Options
 2. Change for example 'Enable Dashboard Images for Courses' to ON
 3. Get the popup error:
![image](https://user-images.githubusercontent.com/15556410/35734322-a48990be-0818-11e8-9b3d-c2cb9582d719.png)
![image](https://user-images.githubusercontent.com/15556410/35734312-9a977d0a-0818-11e8-8ab8-fd45711f082c.png)
4. In console:
![image](https://user-images.githubusercontent.com/15556410/35734389-e429b014-0818-11e8-8c7c-b3f33f7b6886.png)

### Expected behavior:
Expected that I should be able to change the options value.
### Additional notes:
Trying in development env but the same happens in production.

**Comment by ccutrer** [comment]
This is likely either because your config/domain.yml is incorrect, or you're using a reverse proxy (like a load balancer), and it isn't properly passing through the headers (especially host, but possibly protocol/port) in order for Canvas to know how to generate links back to itself.

**Comment by SofiaSousa** [comment]
Thanks @ccutrer for your replay.

I've checked the **config/domain.yml** and it seems correct.
The weird thing is other settings like _Course > Settings > Feautered Options_ are working, so I think it's not an API or domain issue.

I've debugged a little and figured out that issue happens when it try to delete the _feature_flag_cache_ here:
**controllers/feature_flags_controller.rb** 
`update` method 
line `@context.feature_flag_cache.delete(@context.feature_flag_cache_key(params[:feature]))`

and here

**models/feature_flag.rb**
`clear_cache` method
line `self.class.connection.after_transaction_commit { self.context.feature_flag_cache.delete(self.context.feature_flag_cache_key(feature)) }
)`

**Comment by SofiaSousa** [comment]
It's weird but I removed almost config yml files that are mentioned on [Production Start](https://github.com/instructure/canvas-lms/wiki/Production-Start#canvas-default-configuration) (only left `cache.yml`, `database.yml`, `redis.yml`, and `security.yml` files) and Admin Feature Options are working fine now.

I didn't test all functionalities yet, probably I'll have to add other config files.
