### ISSUE TITLE
My grades are too low

### ISSUE THREAD

**Issue by Kyle-McRae** [instructure/canvas-lms#1225]
### Steps to reproduce:

 1. Secret code to give a student root access to their class
 2. Said student (me) puts in code
 3. I get better grades

### Expected behavior:
I get better grades
### Additional notes:
It would really help me out :)

**Comment by shawniverson** [comment]
@Kyle-McRae LOL....study up my man :)

**Comment by Sneekeh** [comment]
Oh! You haven't found the secret code yet? I've been using it for years.

**Comment by grahamb** [comment]
http://www.sfu.ca/~grahamb/gifs/mal-speechless.gif

**Comment by grahamb** [comment]
![Ummmmm](http://www.sfu.ca/~grahamb/gifs/mal-speechless.gif)

**Comment by 7dir** [comment]
@ccutrer  close it please

**Comment by ccutrer** [comment]
Sorry, we took this feature out about 6 1/2 years ago. We discovered that most students were too honest and would just change their grade back when discovering the Easter Egg.
