### ISSUE TITLE
DocViewer Not Coming in SpeedGrader 

### ISSUE THREAD

**Issue by SushnatLexis** [instructure/canvas-lms#1227]
We are running a self-hosted canvas application. And we  are facing an issue: DocViewer is not coming up while grading the assignment in speed grader.
We are using canvas code version as : release/2017-04-01.18 repository cloned from Git hub. Please guide us how we can add canvas DocViewer to our application. 

### Steps to reproduce:

 1. Create a course and then create an assignment in the course.
 2. Enroll a student user.
 3. Submit a document in the assignment as student.
4. Login as faculty and open the grading in SpeedGrader for the above created course.
![docviewer](https://user-images.githubusercontent.com/36159711/35806634-315d69e0-0aa6-11e8-9ac9-f81c0ef4625f.JPG)
.

### Expected behavior:
DocViewer should come at the top of the document.
### Additional notes:
![docviewer](https://user-images.githubusercontent.com/36159711/35806659-4852eb3e-0aa6-11e8-8f37-cc23ce93f040.JPG)

**Comment by nkokkos** [comment]
Hello. 

Have you seen this: https://github.com/instructure/canvas-lms/wiki/FAQ#are-there-any-code-differences-between-the-open-source-and-hosted-offerings

DocViewer is not available in opensource version
