### ISSUE TITLE
bundle install always failing in docker

### ISSUE THREAD

**Issue by codeprefect** [instructure/canvas-lms#1230]
### Summary:
trying to build the docker containers always fails at bundle install

### Steps to reproduce:

 1. clone the canvas-lms repository
 2. run `cp docker-compose/config config`
 3. run `docker-compose run --rm web bundle install`

### Expected behavior:
200 gems installed successfully

### What I get:
```/home/docker/.gem/ruby/2.4.0/bin/bundle:23:in `load': cannot load such file -- /usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)
        from /home/docker/.gem/ruby/2.4.0/bin/bundle:23:in `<main>'
```

### Additional notes:
Ubuntu 16.04
16GB RAM

**Comment by tierra** [comment]
This has been fixed on master branch in 150dfe1bb96e6e87738bb5c4ec1190179649fdc6

**Comment by andrew-gardener** [comment]
I didn't realize that the stable branch is deprecated? Is your master stable enough to build off of?

**Comment by claydiffrient** [comment]
@andrew-gardener The stable is not deprecated.  It is our stable branch.  We run that in production environments.  Master is what we develop off of and that branch gets rolled to the beta branch every 3 weeks. Beta gets rolled to production 3 weeks later. Master generally changes daily and is considered cutting edge.

**Comment by andrew-gardener** [comment]
@claydiffrient sorry, got confused. meant to reply to https://github.com/instructure/canvas-lms/issues/1245#issuecomment-370941746
