### ISSUE TITLE
Boolean flags mismanaged during assignment creation and update

### ISSUE THREAD

**Issue by jessemcbride** [instructure/canvas-lms#1232]
### Summary:

When creating or updating an assignment, the API unexpectedly treats the string `"False"` as `true`  when setting `peer_reviews` and `omit_from_final_grade`. I've noticed similar issues in the past (see #837). Fortunately, they seem easy enough to resolve using [value_to_boolean()](https://github.com/instructure/canvas-lms/blob/b84306350d74f8f7da24b09cf051bebb84f6c644/spec/support/boolean_translator.rb).

### Steps to reproduce:
1. Send a POST / PUT request to create or update an assignment and include the parameters `peer_reviews=False` or `omit_from_final_grade=False`. 
2. Observe that the response comes back as `true`.

### Expected behavior:
The string should be properly converted to `false`.

### Additional notes:

It seems `value_to_boolean()` could be used as it is in [process_published_parameters](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics_controller.rb#L983) to solve the problem.

**Comment by omarkhan** [comment]
Good catch @jessemcbride, that is indeed confusing behavior. Could you submit a pull request to fix this?
