### ISSUE TITLE
Clarify editor button icon url

### ISSUE THREAD

**Issue by hibikutek** [instructure/canvas-lms#1237]
https://github.com/instructure/canvas-lms/blob/765f0a700a1d4630c347e64b60ce0f2a9087ce78/app/controllers/external_tools_controller.rb#L688

Should be clarified that editor_button[icon_url] needs to be set if icon_url is not set for the main tool configuration.  Similar to how it is explained in the Settings section here: https://github.com/instructure/canvas-lms/blob/stable/doc/api/editor_button_tools.md

**Comment by omarkhan** [comment]
Thanks for this @hibikutek! Could you open a pull request with the proposed changes?
