### ISSUE TITLE
::int4[] should be ::int8[] to support bigints - causes several pages to error due to number out of int range

### ISSUE THREAD

**Issue by frankyrumple** [instructure/canvas-lms#1238]
https://github.com/instructure/canvas-lms/blob/f0d712f4505e87954c2c81554dbbf5f3e765fae8/app/models/assignment.rb#L2477

Error report - server id sequences set to 282000000000

#282000000010 PG::NumericValueOutOfRange: ERROR: value "282000000000" is out of range for type integer LINE 1: SELECT DISTINCT subs.assignment_id FROM unnest('{28200000000... ^ : SELECT DISTINCT subs.assignment_id FROM unnest('{282000000000,282000000001,282000000002,282000000003,282000000004,282000000005,282000000006,282000000007}'::int4[]) as subs (assignment_id) WHERE (EXISTS (SELECT "submissions".* FROM "submissions" WHERE (submissions.workflow_state <> 'deleted') AND (submissions.submission_type IS NOT NULL) AND (submissions.assignment_id=subs.assignment_id))) caused by PG::NumericValueOutOfRange: ERROR: value "282000000000" is out of range for type integer LINE 1: SELECT DISTINCT subs.assignment_id FROM unnest('{28200000000... ^ : SELECT DISTINCT subs.assignment_id FROM unnest('{282000000000,282000000001,282000000002,282000000003,282000000004,282000000005,282000000006,282000000007}'::int4[]) as subs (assignment_id) WHERE (EXISTS (SELECT "submissions".* FROM "submissions" WHERE (submissions.workflow_state <> 'deleted') AND (submissions.submission_type IS NOT NULL) AND (submissions.assignment_id=subs.assignment_id))) caused by ERROR: value "282000000000" is out of range for type integer LINE 1: SELECT DISTINCT subs.assignment_id FROM unnest('{28200000000... ^
account: "Open Prison Education"
category: ActionView::Template::Error
created at: 2018-02-14 22:34:02 -0700
user: admin@ed
request context id: 759e7605-a884-4808-a097-fdddecc68edf

HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8 
HTTP_ACCEPT_ENCODING: gzip, deflate, br 
HTTP_HOST: canvas.ed 
HTTP_REFERER: https://canvas.ed/courses/282000000000/quizzes 
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36 
PATH_INFO: /courses/282000000000 
QUERY_STRING: ? 
REMOTE_ADDR: 172.17.0.3 
REQUEST_METHOD: GET 
REQUEST_PATH: /courses/282000000000 
REQUEST_URI: https://canvas.ed/courses/282000000000 
SERVER_NAME: canvas.ed 
SERVER_PORT: 443 
SERVER_PROTOCOL: HTTP/1.1 
format: text/html 
hostname: 62bfb67d613d 
path_parameters: {:controller=>"courses", :action=>"show", :id=>"282000000000"} 
pid: 184 
query_parameters: {} 
request_parameters: {} 
response_code: 500 
type: 
        PG::NumericValueOutOfRange: ERROR:  value "282000000000" is out of range for type integer
LINE 1: SELECT DISTINCT subs.assignment_id FROM unnest('{28200000000...
                                                       ^
: SELECT DISTINCT subs.assignment_id FROM unnest('{282000000000,282000000001,282000000002,282000000003,282000000004,282000000005,282000000006,282000000007}'::int4[]) as subs (assignment_id) WHERE (EXISTS (SELECT "submissions".* FROM "submissions" WHERE (submissions.workflow_state <> 'deleted') AND (submissions.submission_type IS NOT NULL) AND (submissions.assignment_id=subs.assignment_id))) caused by PG::NumericValueOutOfRange: ERROR:  value "282000000000" is out of range for type integer
LINE 1: SELECT DISTINCT subs.assignment_id FROM unnest('{28200000000...
                                                       ^
: SELECT DISTINCT subs.assignment_id FROM unnest('{282000000000,282000000001,282000000002,282000000003,282000000004,282000000005,282000000006,282000000007}'::int4[]) as subs (assignment_id) WHERE (EXISTS (SELECT "submissions".* FROM "submissions" WHERE (submissions.workflow_state <> 'deleted') AND (submissions.submission_type IS NOT NULL) AND (submissions.assignment_id=subs.assignment_id))) caused by ERROR:  value "282000000000" is out of range for type integer
LINE 1: SELECT DISTINCT subs.assignment_id FROM unnest('{28200000000...
                                                       ^

        <Caused>
<Caused>
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
/home/docker/.gem/ruby/2.4.0/gems/switchman-1.11.4/lib/switchman/sharded_instrumenter.rb:20:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/home/docker/.gem/ruby/2.4.0/gems/switchman-1.11.4/lib/switchman/active_record/abstract_adapter.rb:37:in `log'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/query_cache.rb:93:in `block in select_all'
/home/docker/.gem/ruby/2.4.0/gems/switchman-1.11.4/lib/switchman/active_record/query_cache.rb:85:in `cache_sql'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/query_cache.rb:93:in `select_all'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/calculations.rb:172:in `pluck'
/home/docker/.gem/ruby/2.4.0/gems/switchman-1.11.4/lib/switchman/call_super.rb:14:in `call'
/home/docker/.gem/ruby/2.4.0/gems/switchman-1.11.4/lib/switchman/call_super.rb:14:in `call_super'
/home/docker/.gem/ruby/2.4.0/gems/switchman-1.11.4/lib/switchman/active_record/calculations.rb:10:in `block in pluck'
/home/docker/.gem/ruby/2.4.0/gems/switchman-1.11.4/lib/switchman/active_record/relation.rb:74:in `activate'
/home/docker/.gem/ruby/2.4.0/gems/switchman-1.11.4/lib/switchman/active_record/calculations.rb:8:in `pluck'
/usr/src/app/app/models/assignment.rb:2479:in `assignment_ids_with_submissions'
/usr/src/app/app/helpers/context_modules_helper.rb:78:in `preload_can_unpublish'
/usr/src/app/app/helpers/context_modules_helper.rb:110:in `preload_modules_content'
/usr/src/app/app/views/context_modules/_content_next.html.erb:93:in `block in _app_views_context_modules__content_next_html_erb__2291898982660919682_157641260'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/helpers/cache_helper.rb:231:in `write_fragment_for'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/helpers/cache_helper.rb:220:in `fragment_for'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/helpers/cache_helper.rb:155:in `cache'
/usr/src/app/app/helpers/application_helper.rb:543:in `cache'
/usr/src/app/app/views/context_modules/_content_next.html.erb:92:in `_app_views_context_modules__content_next_html_erb__2291898982660919682_157641260'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:159:in `block in render'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:166:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:354:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:157:in `render'
/usr/src/app/config/initializers/i18n.rb:260:in `render'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/partial_renderer.rb:310:in `render'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/renderer.rb:47:in `render_partial'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/renderer.rb:21:in `render'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/usr/src/app/app/views/courses/show.html.erb:174:in `_app_views_courses_show_html_erb__896690522926207495_92415560'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:159:in `block in render'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:166:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:354:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:157:in `render'
/usr/src/app/config/initializers/i18n.rb:260:in `render'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/template_renderer.rb:14:in `render'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/renderer.rb:42:in `render_template'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/renderer.rb:23:in `render'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:104:in `_render_template'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:83:in `render_to_body'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/rendering.rb:26:in `render'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rendering.rb:36:in `render'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:43:in `render'
/usr/src/app/app/controllers/application_controller.rb:1948:in `render'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/implicit_render.rb:36:in `default_render'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:188:in `process_action'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:126:in `call'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/docker/.gem/ruby/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:81:in `batch'
/usr/src/app/app/controllers/application_controller.rb:443:in `batch_statsd'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/usr/src/app/lib/temp_cache.rb:28:in `enable'
/usr/src/app/app/controllers/application_controller.rb:439:in `enable_request_cache'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/usr/src/app/app/controllers/application_controller.rb:433:in `set_locale'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
/home/docker/.gem/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:126:in `process'
/home/docker/.gem/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:30:in `process'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:190:in `dispatch'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:262:in `dispatch'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:39:in `block in serve'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `each'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `serve'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:725:in `call'
/usr/src/app/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:78:in `call'
/home/docker/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
/home/docker/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
/home/docker/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/usr/src/app/app/middleware/request_throttle.rb:60:in `block in call'
/usr/src/app/app/middleware/request_throttle.rb:272:in `reserve_capacity'
/usr/src/app/app/middleware/request_throttle.rb:55:in `call'
/usr/src/app/app/middleware/request_context_session.rb:25:in `call'
/home/docker/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/home/docker/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/usr/src/app/app/middleware/load_account.rb:29:in `call'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/home/docker/.gem/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:36:in `call_app'
/home/docker/.gem/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:26:in `call'
/home/docker/.gem/ruby/2.4.0/gems/request_store-1.4.0/lib/request_store/middleware.rb:19:in `call'
/usr/src/app/app/middleware/request_context_generator.rb:49:in `call'
/home/docker/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/usr/src/app/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
/home/docker/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
/home/docker/.gem/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/docker/.gem/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/static.rb:136:in `call'
/home/docker/.gem/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/home/docker/.gem/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:522:in `call'
/home/docker/.gem/ruby/2.4.0/gems/puma-3.11.0/lib/puma/configuration.rb:225:in `call'
/home/docker/.gem/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:624:in `handle_request'
/home/docker/.gem/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:438:in `process_client'
/home/docker/.gem/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:302:in `block in run'
/home/docker/.gem/ruby/2.4.0/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by ccutrer** [comment]
Do you have any idea how you are using a shard with ID other than 1? This query should never be using global IDs, so this shouldn't be a problem.

**Comment by frankyrumple** [comment]
All models in canvas use bigint ids. The shard digit is 10 trillion digit. As 32bit integers only hit 2.1 billion, the shard id is well beyond the 32bit (int4) mark. As such, this is a bug even if only one shard is in use.

10_000_000_000_000  - Shard digit
0*_**2_147_483_647   - End of 32 bit number - 3 more digits before you hit shard id, loss of precision.

*** Digits cut out

It is clearly a bug to convert native datatypes down where there will be a loss of data, regardless of assumptions.

In our particular case, we assign a school id into those digits. I work with inmate education and we use canvas to provide online services in an offline/secure environment (https://github.com/operepo/ope). We have been doing this with IDs for almost a year and this is the only place that hasn't been able to handle the 64 bit integers and causes page errors.
The locally patched system (to int8) works great.

**Comment by ccutrer** [comment]
Ohhh, I see now. I've trained myself so much to assumed the leading digit in front of a bunch of zeros is automatically the shard ID, that I didn't notice the number in your query is _less_ than Shard::IDS_PER_SHARD. While you certainly have an... interesting... system, you are correct that it is still a bug that a normal Canvas user could run in to if they theoretically reached 4 billion submissions in a single shard. I'll get a fix pushed up ASAP.

**Comment by frankyrumple** [comment]
It is easy to get lost in all the zeros. We push the ids out so our school id allows us to merge replicate between servers over a USB drive without ID conflicts. E.g. offline prison, I can't grade from home, so I want to fix that. We also have secure laptops that we are in the middle of launching that will let us sync w canvas to work offline in a prison cell.

**Comment by omarkhan** [comment]
Closing this as @ccutrer has merged a fix
