### ISSUE TITLE
Submission Upload Failure

### ISSUE THREAD

**Issue by afrozaky** [instructure/canvas-lms#1240]
### Summary:
When I try to submit a tar file for my computer science class, the Mozilla firefox submission just displays it as uploading/submitting but never completely does. This has led to me missing a few deadlines, but thankfully timestamps still allowed me to turn them in as on time. I have noticed this issue does not happen in chrome, after a small delay, the tar file uploads as normal.
### Steps to reproduce:

 1. I am submitting a tar file for a computer science class, the file's extension is .tar.
 2. I am using Mozilla Firefox version is 58.0.2 (64-bit) and  Windows 10, version 1709.
 3. The tar file is transferred from a Linux environment to my machine using a sftp client.

### Expected behavior:
The file should upload.

### Additional notes:
Here is the error logs from console
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.js:3527
TypeError: t is undefined [Learn More] jquery.instructure_forms.js:171:14
A jquery.instructure_forms.js:171:14
pwv1UBr9wT/s.default.fn.formSubmit/</< jquery.instructure_forms.js:256:12
dispatch jquery.js:3331
l jquery.js:2941
trigger jquery.js:3210
triggerHandler jquery.js:3874
onload https://utk.instructure.com/courses/45006/assignments/229435:1:1

**Comment by roor0** [comment]
do you have any browser extensions that are blocking this?

**Comment by afrozaky** [comment]
AdBlock Plus which I don't think is. And the only other one that would be
is called MetaMask. I will try uploading them with the extensions them
disabled.

**Comment by omarkhan** [comment]
Any luck uploading a submission without browser extensions @afrozaky?

**Comment by afrozaky** [comment]
Yes, I was able to upload my most recent lab tar with the extensions
disabled.

Thanks, Zaky Hussein

**Comment by omarkhan** [comment]
Great, closing
