### ISSUE TITLE
Issue while Integrating View Box API services to canvas lms

### ISSUE THREAD

**Issue by SushnatLexis** [instructure/canvas-lms#1242]
### Summary:
We are having a self hosted canvas application and we are planning to integrate View Box APIs. We ave created a developers account with Box and generated an API key. But when we are enabling the plugin canvadocs with Box API key and Base url it is showing unauthorized error. We have tried two base urls
1. https://view-api.box.com/1
2. https://api.box.com/2.0/
But with both the urls we are getting the same error. Please guide us how to get the correct base url or how we can resolve this issue. Any help appreciated!
### Steps to reproduce:

 1. create a developers account with box and create an application with Authorization type App token  
 2. Generate the API key and Primary access token.
 3. Enable the plugin in canvas using the API key and base url.

### Expected behavior:
Annotation tools should come while grading the assignment in canvas.
### Additional notes:

**Comment by Bicet** [comment]
For the sake of been complete, here's the error report:
` HTTP Error 400: 

        /var/canvas/lib/canvadocs.rb:147:in `api_call'
/var/canvas/lib/canvadocs.rb:103:in `session'
/var/canvas/lib/canvadocs/session.rb:14:in `block in canvadocs_session_url'
/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/var/canvas/lib/canvas.rb:251:in `short_circuit_timeout'
/var/canvas/lib/canvas.rb:220:in `timeout_protection'
/var/canvas/lib/canvadocs/session.rb:13:in `canvadocs_session_url'
/var/canvas/app/controllers/canvadoc_sessions_controller.rb:43:in `show'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:188:in `process_action'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:126:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:81:in `batch'
/var/canvas/app/controllers/application_controller.rb:419:in `batch_statsd'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/var/canvas/lib/temp_cache.rb:28:in `enable'
/var/canvas/app/controllers/application_controller.rb:415:in `enable_request_cache'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/var/canvas/app/controllers/application_controller.rb:409:in `set_locale'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:126:in `process'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:30:in `process'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:190:in `dispatch'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:262:in `dispatch'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:39:in `block in serve'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `serve'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:725:in `call'
/var/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:78:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/var/canvas/app/middleware/request_throttle.rb:60:in `block in call'
/var/canvas/app/middleware/request_throttle.rb:272:in `reserve_capacity'
/var/canvas/app/middleware/request_throttle.rb:55:in `call'
/var/canvas/app/middleware/request_context_session.rb:25:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/var/canvas/app/middleware/load_account.rb:29:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:36:in `call_app'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:26:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
/var/canvas/app/middleware/request_context_generator.rb:49:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/var/canvas/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:522:in `call'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `public_send'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
      `

**Comment by omarkhan** [comment]
Hi @SushnatLexis! We're trying to use github issues for bugs only. For support see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help).
