### ISSUE TITLE
Box integration for Canvas LMS

### ISSUE THREAD

**Issue by SushnatLexis** [instructure/canvas-lms#1243]
### Summary:
We are having a self hosted canvas application and we are planning to integrate New View Box APIs. Which canvas-lms code version will support the New Box APIs?. Please help in getting the correct information. 
Link to refer: https://developer.box.com/docs/getting-started-with-new-box-view

**Comment by ccutrer** [comment]
Canvas doesn't currently integrate with the new Box View APIs (and has no plans to in the future). If you want to do so, you'll have to write the integration yourself.

**Comment by LordRatte** [comment]
Do I understand correctly, then, that this section of the wiki is outdated?
https://github.com/instructure/canvas-lms/wiki/Canvas-Integration#box-view
