### ISSUE TITLE
Steps to configure the 'Inbox'.

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#1244]
Hello community,

I'd like to configure IMAP for Canvas LMS to be able to watch the emails from Canvas UI 'Inbox' button.
Is anybody has an tips/steps how to configure it?

Thanks.

**Comment by omarkhan** [comment]
Hi @ally1! We use github issues for bugs only. For support see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help).
