### ISSUE TITLE
grading_standard_id cannot be updated via a PUT to /courses

### ISSUE THREAD

**Issue by jcallaway** [instructure/canvas-lms#1248]
### Steps to reproduce:

See the attached Python program for a demonstration.  Note that I had to name it "update_course_grading_standard_id_bug.py.txt" because github won't accept attachments with a ".py" extension.

### Additional notes:

[update_course_grading_standard_id_bug.py.txt](https://github.com/instructure/canvas-lms/files/1772692/update_course_grading_standard_id_bug.py.txt)

**Comment by spencerolson** [comment]
Hi @jcallaway , if i'm looking at the example you provided correctly, it looks like you were trying to set the grading_standard_id to "0". The grading_standard_id must be a number that represents the ID of an actual grading_standard that you want to use.

**Comment by jcallaway** [comment]
Thanks for the quick response.  Zero is the default grading standard for our organization.  But you can try setting the number to any non-zero value, and you will see that the bug remains the same--grading_standard_id remains null.

**Comment by spencerolson** [comment]
Okay, thanks @jcallaway I'll look into this and get back to you. Thanks for providing the example 👍🏼

**Comment by jcallaway** [comment]
Hey I'm closing this issue because I figured out what I was doing wrong.  3 is the id of the default grading scheme at our institution.  When I *create* (POST) a course, if I set grading_standard_id to 0, it uses the default grading scheme for some reason, but when I issue a PUT to /courses I need to set it to 3 for it to take effect.  A little confusing, but no worries.

**Comment by spencerolson** [comment]
OK, glad you figured it out! Yeah, i just tested this out locally and everything worked for me 👍🏼. When 'POST'ing, my guess would be that it uses the default grading scheme if you pass "0" because it can't find a grading scheme with that ID, so it falls back to the default.
