### ISSUE TITLE
Compile Assets takes a long time (hangs?)

### ISSUE THREAD

**Issue by pengc99** [instructure/canvas-lms#1254]
### Summary:
Compile assents takes a very long time - takes hours. Compiling in a virtual machine with 8GB of RAM and SSD backed storage. It sits at --> Finished: 'js:webpack_development' in 63.41711617200053 and doesn't display any more output, with several node processes running at 100% on the processor.

### Steps to reproduce:

 1.  Run RAILS_ENV=production bundle exec rake canvas:compile_assets

### Expected behavior:

Expecting compile assents to finish in a reasonable amount of time. Waited a few hours. Host machine running the guest is a i7-6850

### Additional notes:

**Comment by omarkhan** [comment]
Hi @pengc99! This is something we are very much aware of, we compile assets all the time 😄 

We have tried to optimize things somewhat, but it's an ongoing process. If you have any ideas on how to speed things up please do open a pull request. In the meantime I will close this issue as we don't have a clear path forward.

**Comment by ibnIrshad** [comment]
@omarkhan so what is the expected compilation time? Should I assume it doesn't work after 3 hours? 10 hours?

**Comment by tierra** [comment]
Well, you are compiling in a VM, which more than doubles the expected time. Additionally, 8GB ram is barely the cut off for how much I've seen asset compilation take lately (I've monitored ram usage of just webpack, growing to north of 8GB just a couple weeks ago). So that's a bit of a tight fit, but should still be adequate. Based on your processor, assuming all 6 cores are properly assigned to your VM (have you verified this btw? VMs on VirtualBox default to only using one or two cores, even if your system has 8). Given all that, I'd expect as much as about 10 minutes, maybe 20 max.

**Comment by ibnIrshad** [comment]
@tierra Thanks, your estimate was spot-on. Took about 20 minutes.

**Comment by mdjasper** [comment]
just to add a datapoint, here are my production and non production build 

```
>time RAILS_ENV=production bundle exec rake canvas:compile_assets
>Finished compiling assets in 666.3760589999999. parallelism saved 28.546474999999987 (95.89213565493618%)
RAILS_ENV=production bundle exec rake canvas:compile_assets  2854.83s user 689.88s system 492% cpu 12:00.10 total
```

```
>time bundle exec rake canvas:compile_assets
>Finished compiling assets in 92.31431500000008. parallelism saved 29.68469799999957 (75.66808347867564%)
bundle exec rake canvas:compile_assets  321.37s user 35.33s system 217% cpu 2:44.33 total
```

**So about 1.5 minutes for non-prod, and 11 minutes for prod.**

Machine specs: 2016 MPB (16GB ram, 2.7 GHz Intel Core i7) not using a vm or docker (canvas installed "locally")

**Comment by lecuong35** [comment]
> just to add a datapoint, here are my production and non production build
> 
> ```
> >time RAILS_ENV=production bundle exec rake canvas:compile_assets
> >Finished compiling assets in 666.3760589999999. parallelism saved 28.546474999999987 (95.89213565493618%)
> RAILS_ENV=production bundle exec rake canvas:compile_assets  2854.83s user 689.88s system 492% cpu 12:00.10 total
> ```
> 
> ```
> >time bundle exec rake canvas:compile_assets
> >Finished compiling assets in 92.31431500000008. parallelism saved 29.68469799999957 (75.66808347867564%)
> bundle exec rake canvas:compile_assets  321.37s user 35.33s system 217% cpu 2:44.33 total
> ```
> 
> **So about 1.5 minutes for non-prod, and 11 minutes for prod.**
> 
> Machine specs: 2016 MPB (16GB ram, 2.7 GHz Intel Core i7) not using a vm or docker (canvas installed "locally")

In my VM, version 2022, 2023 still work, but canvas version 2021 not running(i've waited for 30 minutes). Can u show me a solution?
