### ISSUE TITLE
The "File Removed" PDF has a typo

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#1255]
### Summary:
The File Removed PDF at https://github.com/instructure/canvas-lms/blob/997f766c94463e76e6a37967bfbe1d8d518e8030/public/file_removed/file_removed.pdf has text that reads: 

"The admin has removed this file please contact them for more information."

This should be two sentences:

"The admin has removed this file. Please contact them for more information."

**Comment by omarkhan** [comment]
Thanks for this @christopher-b. Could you submit a pull request with the proposed change?

**Comment by bootstraponline** [comment]
https://github.com/instructure/canvas-lms/commit/8335f8bdf1deab5c67f92cb3d89f642eb5345261 has been merged to master. The file was generated from the original source.
