### ISSUE TITLE
[FATAL tini (1)] Unexpected error when forwarding signal: 'Operation not permitted'

### ISSUE THREAD

**Issue by lexuantrung1612** [instructure/canvas-lms#1257]
### Summary:
[FATAL tini (1)] Unexpected error when forwarding signal: 'Operation not permitted'
### Steps to reproduce:

 1. After down all containers,  and run: docker-compose up -d. I cannot start app on local at: 'canvas.docker'. I'm not sure this error from nginx. Please help me. Thanks.
 2. Error's message: '[FATAL tini (1)] Unexpected error when forwarding signal: 'Operation not permitted'
'
 3.

### Additional notes:

**Comment by tierra** [comment]
Can you provide any more details about your Docker environment? What version of Docker and Docker Compose are you using? What host OS are you running?

**Comment by TxusBlack** [comment]
I have the same issue with a VPS in Vultr

**Comment by rizkyekoputra** [comment]
How to solve this issue @lexuantrung1612 ??

**Comment by UniWrighte** [comment]
@lexuantrung1612 Yeah how did you solve it? @rizkyekoputra did you ever figure it out?

**Comment by ro-calderon** [comment]
Same Issue
