### ISSUE TITLE
Bounce Notifications in LMS canvas

### ISSUE THREAD

**Issue by AbithaVek** [instructure/canvas-lms#1263]
### Summary:
We have a self-hosted canvas app. We are having trouble with email bounce notifications. We have configured SQS monitoring bounced emails and configured the SQS queue URL in the canvas configuration files. We are able to receive the bounced notification in the SQS. But the email bounce is not notified back to the canvas. Please guide what we change we need to do receive bounce notifications from canvas. Any help is appreciated.

### Steps to reproduce:

 1. Register an user with invalid email address
 2. Able to receive bounce notification from SQS
 3.

### Expected behavior:
I believe email bounce notification code changes are available along with the canvas package. 
### Additional notes:

**Comment by omarkhan** [comment]
Hi @AbithaVek - we use github issues for bugs only, for support see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help). Thanks!
