### ISSUE TITLE
Cannot assign requested address - connect(2) for "localhost" port 8500 

### ISSUE THREAD

**Issue by huangdengpan** [instructure/canvas-lms#1264]
Does anyone know the problem?

When I change the setting options, it shows the error:

![image](https://user-images.githubusercontent.com/16663404/37959876-c2125812-31e6-11e8-855c-0052e795f4aa.png)

Ajax Error: 500
{"errors":[{"message":"An error occurred.","error_code":"internal_server_error"}],"error_report_id":"27"}

Cannot assign requested address - Cannot assign requested address - connect(2) for "localhost" port 8500 (localhost:8500) caused by Cannot assign requested address - connect(2) for "localhost" port 8500

HTTP_ACCEPT: application/json, text/javascript, application/json+canvas-string-ids, */*; q=0.01 
HTTP_ACCEPT_ENCODING: gzip, deflate, br 
HTTP_HOST: asjk.canvaslms.net 
HTTP_REFERER: https://asjk.canvaslms.net/accounts/1/settings 
HTTP_USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 
PATH_INFO: /api/v1/accounts/1/features/flags/section_specific_announcements 
QUERY_STRING: ? 
REMOTE_ADDR: 210.22.126.190 
REQUEST_METHOD: PUT 
REQUEST_URI: https://asjk.canvaslms.net/api/v1/accounts/1/features/flags/section_specific_announcements 
SERVER_NAME: asjk.canvaslms.net 
SERVER_PORT: 443 
SERVER_PROTOCOL: HTTP/1.1 
format: application/json 
hostname: iZ2zeap06av7ci1wwvumjnZ 
path_parameters: {:format=>"json", :controller=>"feature_flags", :action=>"update", :account_id=>"1", :feature=>"section_specific_announcements"} 
pid: 5379 
query_parameters: {} 
request_parameters: {"state"=>"allowed", "_method"=>"PUT", "authenticity_token"=>"95ek00KQAYFSy5tXrLtjOSHPfVTe0Ujsx8R0wm28yHedx5SiK+Rb9n292CHe8RJXFZYcAJroMp2eq0CuOPajMw=="} 
response_code: 500

**Comment by bedmison** [comment]
@huangdengpan What was the root cause of this? I've encountered it too and I can't get it sorted.

**Comment by huangdengpan** [comment]
@bedmison 
I installed the newest version of master, there are some problems with this version. 
So, choose the stable version is a good choice.
