### ISSUE TITLE
Canvas Communication channel bounce_count not getting updated

### ISSUE THREAD

**Issue by SushnatLexis** [instructure/canvas-lms#1267]
### Summary:
Hi, 
We have a self hosted canvas app running on AWS. We have configured SQS for bounced emails notification and set up the bounce_notifications.yml file and passing secret key, access key, region and bounce queue name so that canvas can read the SQS and update the bounce_count field and communication_channels table. But it is not getting updated. Are we missing any step or configuration? Please help us in resolving this issue.

### Expected behavior:
bounce_count should be updated for invalid email addresses.
### Additional notes:

**Comment by omarkhan** [comment]
Hi @SushnatLexis. We use github issues for bugs only, for support please see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help). Thanks!
