### ISSUE TITLE
Discussion: Default branch changing to master

### ISSUE THREAD

**Issue by bootstraponline** [instructure/canvas-lms#1268]
To improve the pull request experience on Canvas LMS, the default branch will be changing to master. This allows us to update the documentation in the repo faster compared to stable. By default, pull requests will target the correct branch.

If you rely on stable being the default branch, you'll want to update your scripts to checkout stable explicitly.

- `git clone https://github.com/instructure/canvas-lms.git`
- `cd canvas-lms`
- `git checkout stable`

If there are any problems with this change happening, comment and let us know.

**Comment by grahamb** [comment]
SFU has no problems with this.

**Comment by christopher-b** [comment]
This won't cause any disruption for us at OCADU. Thanks for the heads-up.

**Comment by bootstraponline** [comment]
The default branch has been updated to master.

Another benefit of this change is that GitHub issues will be closed automatically when fixes land to master. Previously issues didn't auto close because stable was the default branch.
