### ISSUE TITLE
script/console command to make a user a Site Admin does not work

### ISSUE THREAD

**Issue by ibnIrshad** [instructure/canvas-lms#1269]
### Summary:

I need to make a user a Site Admin. How can I do that? I tried the Rails console.

I tried this command referenced by Cody in this old support thread: https://groups.google.com/forum/#!topic/canvas-lms-users/rxO2wDaP61Y

But the command `Account.site_admin.add_user(User.find(<your canvas user id>))` does not work anymore. 

### Steps to reproduce:

 1. Open rails console `RAILS_ENV=production ./scripts/rails console`
 2. Try running Account.site_admin.add_user(User.find(<your canvas user id>))
 3. spits an error: Account.site_admin.adduser not found

### Expected behavior:

Should make the canvas user id a Site Admin.

### Additional notes:

Is there another way of making a user a Site Admin from the console or directly in the database? I have full server/db access.

**Comment by roor0** [comment]
add_user was a helper method that was removed a while belack because of confusion with it being a regular user. Use Account.site_admin.account_users.create!(user: User.find())
