### ISSUE TITLE
Misleading error message for assignment ``due_at``

### ISSUE THREAD

**Issue by ngoue** [instructure/canvas-lms#1272]
### Summary: 

When creating an assignment, the API returns a single error message for an invalid `due_at` value:
```
{
    'errors': {
        'due_at': [{
            'type': 'cannot be blank when Post to Sis is checked', 
            'attribute': 'due_at', 
            'message': 'cannot be blank when Post to Sis is checked'
        }]
    }
}
     
```

### Steps to reproduce:

 1. Make a post request to `/api/v1/courses/:course_id/assignments`
 2. Pass a `due_at` value that is *NOT* between `unlock_at` and `lock_at`

### Expected behavior:

Receive an error message indicating the `due_at` value is out of the `unlock_at` and `lock_at` range.

**Comment by roor0** [comment]
looks like that is addressed in https://github.com/instructure/canvas-lms/commit/3af5109cdfe25949dd9666cbb3e282e4cdd3abf4
