### ISSUE TITLE
API documentation: Missing include option for course list API calls

### ISSUE THREAD

**Issue by ToeBee** [instructure/canvas-lms#1273]
I believe this is just an omission in documentation. When calling the [`/api/v1/courses`](https://canvas.instructure.com/doc/api/courses.html#method.courses.index) endpoint (and also the [`/api/v1/accounts/:account_id/courses`](https://canvas.instructure.com/doc/api/accounts.html#method.accounts.courses_api) endpoint) the API will accept the option `include[]=subaccount` and if provided it will add a `subaccount_name` property in the returned Course object. However this option is not included in the documented list of optional includes.

**Comment by spencerolson** [comment]
Hi @ToeBee , thanks for pointing this out! At a cursory glance, it does look like we're missing that option in the documentation. I'll double-check tomorrow and then I can prepare a commit to get this documentation added.

**Comment by roor0** [comment]
@ToeBee I changed it again. This will be on our next stable for our beta on Monday.
