### ISSUE TITLE
Passenger startup error after production installation

### ISSUE THREAD

**Issue by dalareo** [instructure/canvas-lms#1275]
### Summary:
Application is not starting

### Steps to reproduce:

 1. Follow production installation instructions
 2. Access URL from the browser

### Additional notes:
[ 2018-04-13 14:33:36.0305 3525/7f9e90573700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/canvas: An error occurred while starting up the preloader: it did not write a startup response in time.
  Error ID: bd84ffc1
  Error details saved to: /tmp/passenger-error-tMEtJZ.html
  Message from application: An error occurred while starting up the preloader: it did not write a startup response in time. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
<pre>
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
</pre>

`[ 2018-04-13 14:33:36.0656 3525/7f9e93fff700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is bd84ffc1. Please see earlier logs for details about the error.
[ 2018-04-13 14:33:36.0657 3525/7f9e937fe700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is bd84ffc1. Please see earlier logs for details about the error.`

**Comment by tierra** [comment]
Hi @dalareo . We use github issues for bugs only, for support please see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help). Thanks!

This is a pretty generic error that can be triggered by many different things. You should inspect the Rails logs to see why it failed to start up.

**Comment by dalareo** [comment]
It was a timeout issue. I think it would be nice to indicate in the install instructions this thing related to the first execution time

**Comment by tierra** [comment]
Yeah, that's a little tough considering the wide variety of runtime environments Canvas is setup and configured in. Some people are running it in local development, inside a virtual machine with highly limited hardware and resources, and some are running it natively on production servers with adequate hardware.

**Comment by dalareo** [comment]
Using an 8GB RAM Scaleway machine needed more than 90 timeout seconds...

**Comment by tierra** [comment]
That does sound pretty unusual, and maybe you have misconfigured something somewhere.

**Comment by abhigyanranjan** [comment]
How was this resolved?

**Comment by thoughtafter** [comment]
I'd be happy to open a new issue on this. The issue is startup takes > 90 seconds and that hits the default timeout of Passenger. It can be fixed by raising the timeout in apache or nginx:
https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems

The issue I have is that for all of the logging that canvas does, startup seems to be sparse, not giving enough information to debug what is causing the slow startup.

**Comment by ccutrer** [comment]
There's not much to say here. Canvas is huge. Startup _does_ take > 90s, especially on an underpowered machine. You'll probably need to adjust the startup timeout in passenger. If it's taking more than say 5 minutes, then yes, there might be a problem.
