### ISSUE TITLE
SCORM LTI Option Enabling in Self hosted Canvas App

### ISSUE THREAD

**Issue by srinivasanlr** [instructure/canvas-lms#1277]
Hi ,
 
We are having **Self hosted Canvas App** to which we want to know the Steps/procedures to Enable the SCORM LTI.
 
Please guide us on this.
 
Reference Forum : https://community.canvaslms.com/docs/DOC-10312-4152340211
Notes:
•         The SCORM LTI must be enabled in External Apps at the account level before it can be used in courses. If you are an administrator, please contact your Customer Success Manager for assistance.
•         If you delete a SCORM assignment from the Assignments, Discussions, or Quizzes pages, the assignment will still appear on the SCORM page, and if you try to open the assignment, Canvas will generate an error. However, if you delete the assignment from the SCORM page, the assignment will also be deleted from all other applicable Canvas locations.
•         Canvas supports the following versions of SCORM: SCORM 1.2 and SCORM 2004 (2nd, 3rd, and 4th Edition).

**Comment by tierra** [comment]
Hi @subratrout . We use github issues for bugs only, for support please see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help). Thanks!
