### ISSUE TITLE
Getting Error while configuring SCORM

### ISSUE THREAD

**Issue by SushnatLexis** [instructure/canvas-lms#1280]
Hi ,

We have a self hosted canvas app and we are trying to integrate SCORM. We have configured the LTI in external apps at account level and we able to get the SCORM tab in course navigation. But on click it is redirecting to error page. We checked the error reports it is showing "URL required for generating LTI content" but we have passed launch url while configuring the LTI. Please help us in getting SCORM integrated.
![scorm](https://user-images.githubusercontent.com/36159711/38807485-5e94f01a-419a-11e8-861f-4ff74c388162.JPG)

### Steps to reproduce:

 1.
 2.
 3.

**Comment by tierra** [comment]
Hi @SushnatLexis , can you provide any more details about what LTI tool you've configured in Canvas, and how you've configured it? What URL did you use for the launch URL? Did you use the XML URL to configure your tool? Have you tried contacting the author of the LTI tool you're trying to configure for help with getting this setup?
