### ISSUE TITLE
[1/5] Validating package.json... error canvas-lms@0.0.0: The engine "yarn" is incompatible with this module. Expected version "1.5.1".

### ISSUE THREAD

**Issue by kevin-og** [instructure/canvas-lms#1281]
n 8.9.3
yarn install

with package.json set yarn 1.5.1, this error is still apparent:

[1/5] Validating package.json...
error canvas-lms@0.0.0: The engine "yarn" is incompatible with this module. Expected version "1.5.1".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by kevin-og** [comment]
Switch to node 8.10.0, problem still persists:

root@ip-10-0-0-172:/var/canvas# node --version
v8.10.0
root@ip-10-0-0-172:/var/canvas# yarn install
yarn install v1.6.0
$ script/local-yarn install
running yarn install for gems/canvas_i18nliner/package.json w/ NODE_ENV=production
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.07s.
running yarn install for gems/selinimum/package.json w/ NODE_ENV=production
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.47s.
running yarn install for packages/canvas-planner/package.json w/ NODE_ENV=development
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @instructure/ui-presets@4.7.1" has unmet peer dependency "chai@*".
warning " > @instructure/ui-presets@4.7.1" has unmet peer dependency "sinon@*".
warning "@instructure/ui-presets > @instructure/ui-themes@4.7.1" has unmet peer dependency "@instructure/ui-themeable@^4.7.1".
warning "@instructure/ui-presets > karma-chai-sinon@0.1.5" has unmet peer dependency "chai@*".
warning "@instructure/ui-presets > karma-chai-sinon@0.1.5" has unmet peer dependency "sinon-chai@*".
warning "@instructure/ui-presets > karma-chai-sinon@0.1.5" has unmet peer dependency "sinon@*".
warning "@instructure/ui-presets > @instructure/ui-testbed > chai-enzyme@0.8.0" has unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x || 1.0.0-rc.1".
[4/4] Building fresh packages...
$ yarn build
yarn run v1.6.0
$ ./scripts/build
############################################################
# Building fully Babelified CommonJS version of the module #
############################################################
$ BABEL_ENV=production babel src --out-dir lib --ignore spec.js,test.js,demo.js --quiet
[transform-themeable]: src/components/BadgeList/styles.css
[transform-themeable]: BadgeList
[transform-themeable]: src/components/CompletedItemsFacade/styles.css
[transform-themeable]: CompletedItemsFacade
[transform-themeable]: src/components/Day/styles.css
[transform-themeable]: Day
[transform-themeable]: src/components/Grouping/styles.css
[transform-themeable]: Grouping
[transform-themeable]: src/components/Opportunities/styles.css
[transform-themeable]: Opportunities
[transform-themeable]: src/components/Opportunity/styles.css
[transform-themeable]: Opportunity
[transform-themeable]: src/components/PlannerEmptyState/styles.css
[transform-themeable]: PlannerEmptyState
[transform-themeable]: src/components/PlannerHeader/styles.css
[transform-themeable]: PlannerHeader
[transform-themeable]: src/components/PlannerItem/styles.css
[transform-themeable]: PlannerItem
[transform-themeable]: src/components/ShowOnFocusButton/styles.css
[transform-themeable]: ShowOnFocusButton
[transform-themeable]: src/components/StickyButton/styles.css
[transform-themeable]: StickyButton
[transform-themeable]: src/components/UpdateItemTray/styles.css
[transform-themeable]: UpdateItemTray
Done in 6.90s.
Done in 15.92s.
[1/5] Validating package.json...
error canvas-lms@0.0.0: The engine "yarn" is incompatible with this module. Expected version "1.5.1".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by simonista** [comment]
Should be as simple as changing this line to 1.6.0: https://github.com/instructure/canvas-lms/blob/master/package.json#L7. We have a patchset up to test that change, it just hasn't been merged yet. Should probably go through in the next day or two. Or you could downgrade to yarn 1.5.1

**Comment by kevin-og** [comment]
That worked, thank you.
