### ISSUE TITLE
error canvas-lms@0.0.0: The engine "yarn" is incompatible with this module (1.6.1). Expected version "1.5.1".

### ISSUE THREAD

**Issue by gautamchawla81** [instructure/canvas-lms#1282]
Summary:
I am getting the errors while installation of canvas lms production start.
https://github.com/instructure/canvas-lms/wiki/Production-Start

### Steps to reproduce:

 1. Install every steps till Bundler and Canvas dependencies
 2. When you install Yarn then it shows the error, yarn 1.6.1 is not compatible with canvas-lms@0.0.0
Also i have search how to install yarn 1.5.1 but i am unable to install that version. Please help. I am stuck in-between. 
Please reply if this can be resolved.

Thanks

**Comment by tierra** [comment]
Please see: https://github.com/instructure/canvas-lms/issues/1281#issuecomment-381819800

**Comment by gautamchawla81** [comment]
Thank You, It works :)
