### ISSUE TITLE
LTI-2- 404 Error after disabling and re-enabling the app from the Navigation bar

### ISSUE THREAD

**Issue by ahmadhasankhan** [instructure/canvas-lms#1283]
### Summary:
I am using LTI-2p0 and getting 404 error after disabling and re-enabling the app from the Navigation bar.

### Steps to reproduce:
1) install site-wide
2) disable the app within a course by visiting Settings>Navigation, clicking the gear, then click disable
3) re-enable the app by clicking the gear and clicking enable
### Expected behavior:
It should show my app.

### Actual behavior:
Not Found
`The requested URL /courses/message_handler_id/137/lti/basic_lti_launch_request/resource_link_fragment/nav.course_id/1 was not found on this server.`

**Comment by westonkd** [comment]
Thanks for bringing this issue to our attention!

Just to make sure I'm following correctly In step 2 of the 'steps to reproduce': Are you navigating to `/courses/:course_id/settings` when you are disabling the LTI 2 tool that was installed at an account level?

LTI 2 tools can only be enabled/disabled in the course or account they were installed in. This means that step 2 of the 'steps to reproduce' is not possible. 

If you are seeing an option to disable the tool from `/courses/:course_id/settings` it may be that the tool was accidentally installed in the course _and_ the account.

**Comment by ahmadhasankhan** [comment]
@westonkd Yes, I am disabling from `/courses/4/settings` (Navigation).

It is reproducible in both cases either I install it on account level or course level, it doesn't work once you disable & enable  (disable->save->enable->save reshresh `404`).

> If you are seeing an option to disable the tool from /courses/:course_id/settings it may be that the tool was accidentally installed in the course and the account.

Sorry, what do you mean by ` accidentally installed in the course and the account`?
Is there any other place where we install the app?

**Comment by westonkd** [comment]
Thanks for the clarification. I misunderstood and thought the tool was installed at the account level but you were attempting to disable it from the course settings page. That would not be possible unless the tool was installed in both the course _and_ the account.

I've run through the reproduction steps on the latest release of Canvas in a course and account but am unable to reproduce the behavior. 

Are there any details about the tool you are using or you Canvas environment you can share to help us reproduce the issue? Thanks.

**Comment by westonkd** [comment]
The LTI 2 tool I tested with was https://lti-tool-provider-example.herokuapp.com/

**Comment by ahmadhasankhan** [comment]
Try this:

Go to https://canvas.instructure.com/courses/1300408

```
user: test@mailinator.com
pwd: test@mailinator.com
```
There is already an app which is throwing `404` inside `DevTest` course if you want to have a look.

Or add a new one: https://lti-tool-provider-example.herokuapp.com/register and follow the previously given steps to reproduce.

Please let me know if you are still unable to reproduce it.

**Comment by westonkd** [comment]
Great, thanks, that helps give some insight on what might be going on. I'm creating a bug ticket for us to work on now.

**Comment by ahmadhasankhan** [comment]
Cool, thanks :)

**Comment by westonkd** [comment]
We (and IMS) now recommend using [LTI 1.3](https://www.imsglobal.org/spec/lti/v1p3/) for building integrations that use LTI.

For details on using LTI 1.3 see https://canvas.instructure.com/doc/api/file.tools_intro.html and linked pages.
