### ISSUE TITLE
Request failed with status code 500 

### ISSUE THREAD

**Issue by Novusityneil** [instructure/canvas-lms#1290]
### Summary:
issue with uploading file
### Steps to reproduce:

Get the new version setup. tried to upload file for test. It got error message says   "Failed with status code 500" . any thought?
![image](https://user-images.githubusercontent.com/14044556/39537638-0cc0bda8-4def-11e8-9cb9-4202c5a2d38e.png)

**Comment by omarkhan** [comment]
Hi @Novusityneil - we use github issue for bugs only, for support please see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help). Thanks
