### ISSUE TITLE
canvas:compile_assets task throws SIGABRT and produces core dumps on RHEL/CentOS (stable & master)

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#1291]
### Summary:

The `canvas:compile_assets` rake task throws a SIGABRT and produces core dumps when run on RedHat Enterprise Linux and CentOS. This issue is present on both `stable` and `master`, but not on previous releases.

### Steps to reproduce:

 1. Clone the repository, switch to either stable or master
 2. Run `bundle install` and `yarn install` 
 3. Run `bundle exec rake canvas:compile_assets`

### Expected behavior:

Asset compilation should complete without any issues.

### Actual behavior:

Asset compilation fails with exit code 134 and produces core dump(s).

```
........
[jD/9TzA1ms] ./app/coffeescripts/bundles/legacy/submissions_show_preview_media.coffee 454 bytes {94} [built]
[s7W9AF6Em0] ./app/coffeescripts/bundles/legacy/user_outcome_results.coffee 567 bytes {160} [built]
[zdgz0nIWsp] ./app/jsx/bundles/course_statistics.js 1.81 kB {107} [built]
    + 5963 hidden modules
$ es-check es5 ./public/dist/**/*.js
ES-Check: there were no ES version matching errors!  🎉
Done in 720.50s.
--> Finished: 'js:webpack_production' in 721.6713633798063
--> Finished: 'run i18n:generate_js, js:webpack_development, js:webpack_production' in 775.205895293504
Finished compiling assets in 775.9628252871335. parallelism saved 38.034220019355416 (95.32747443757187%)
Aborted (core dumped)
```

### Additional notes:

This problem just came up as we started testing the 2018-01-21 release. Previous releases do not have the same issue. I've been able to reproduce this on both RHEL 6 & 7, and CentOS 7. 

Oddly, the workaround seems to be to invoke all the tasks called by `compile_assets` manually; I have not been able to get any individual task to SIGABRT.

```
yarn run gulp rev
bundle exec rake js:yarn_install
bundle exec rake css:compile
bundle exec rake css:styleguide
bundle exec rake js:build_client_apps
bundle exec rake i18n:generate_js
bundle exec rake js:webpack_development
bundle exec rake js:webpack_production
bundle exec rake doc:api
```

I've tried running `compile_assets` with `CANVAS_BUILD_CONCURRENCY=1` and `DISABLE_HAPPYPACK=1` to disable parallelism but it still aborts and produces core dumps.

Ruby versions:
RHEL6: ruby 2.4.1p111 (2017-03-22 revision 58053)
RHEL7 & CentOS 7: ruby 2.4.4p296 (2018-03-28 revision 63013)

I can provide sample core dumps if necessary.

**Comment by grahamb** [comment]
Confirmed from another user on the Google Group that this is an issue:

-------

Hi All,
During production install on a digital ocean droplet I am getting following errors when running
RAILS_ENV=production bundle exec rake canvas:compile_assets
I am using 2cpu and 4GB RAM droplet with 20GB disk size.

Please help..

Thanks you.

v8::internal::JSWeakCollection::Set(v8::internal::Handle<v8::internal::JSWeakCollection>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [/usr/bin/node]
17: v8::internal::Runtime_WeakCollectionSet(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
18: 0x244741f23918
Aborted (core dumped) 344/420 modules 76 active ...pts/media_comments/js_uploader.coffee
error An unexpected error occurred: "Command failed.
Exit code: 134
Command: sh
Arguments: -c NODE_ENV=production gulp rev & node --max_old_space_size=4096 $(yarn bin)/webpack --color --config webpack.production.config.js
Directory: /var/canvas
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/var/canvas/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.



Also yarn-error.log has following at its end.


Trace:
  Error: Command failed.
  Exit code: 134
  Command: sh
  Arguments: -c NODE_ENV=production gulp rev & node --max_old_space_size=4096 $(yarn bin)/webpack --color --config w$
  Directory: /var/canvas
  Output:

      at ProcessTermError.MessageError (/usr/share/yarn/lib/cli.js:186:110)
      at new ProcessTermError (/usr/share/yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/share/yarn/lib/cli.js:30281:17)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by omarkhan** [comment]
Hi @grahamb! My guess is that it's running out of memory while trying to run those commands in parallel. That would explain why it works when you run them individually. I would suggest trying with a beefier machine. 8GB of memory should do it.

**Comment by tierra** [comment]
> I've tried running compile_assets with CANVAS_BUILD_CONCURRENCY=1 and DISABLE_HAPPYPACK=1 to disable parallelism but it still aborts and produces core dumps.

Pretty sure he's saying it doesn't work even when run individually.

**Comment by omarkhan** [comment]
Ah yes I must have skipped over that part. Any thoughts @tierra?

**Comment by grahamb** [comment]
Hi Omar,

I’m running this on machines with upwards of 12GB of RAM. I’ve also disabled parallelism. I don’t think that’s the issue. 

I can provide core dumps if needed. 

— Graham

**Comment by tierra** [comment]
I'm not really sure, but suspect issues with the distribution version of Node. Can you shed any light about what RedHat / CentOS provides for Node.js @grahamb ? I'm not seeing versions mentioned.

Obviously, as pointed out, this only started happening with changes in Canvas, but without bisecting on changes (and even with that), it'll be hard to nail down why Graham's version of Node.js segfaults, and even if we do figure out what caused it, it's likely possible we can't work around it just for distro-specific versions of Node.js.

**Comment by tierra** [comment]
Yeah, I'd guess this probably boils down to native extensions in one of our NPM dependencies, likely making bad assumptions about provided glibc version or something.

**Comment by grahamb** [comment]
So, what gets used in the parent compile_assets task and not in the child tasks? There isn’t much.

**Comment by grahamb** [comment]
I don't think it's specifically a gcc issue. I'm able to successfully build using the `instructure/ruby-passenger:2.4` image, which ships with gcc 4.8.4. My two RHEL boxes (6.3 and 7.5) have gcc 4.8.3 and 4.8.5, respectively.

GCC versions:

RHEL 6.3 (installed via the devtoolset-2 package):
```
[grahamb@atlassian ~]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/rh/devtoolset-2/root/usr --mandir=/opt/rh/devtoolset-2/root/usr/share/man --infodir=/opt/rh/devtoolset-2/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/cloog-install --with-mpc=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)
```

RHEL 7.5 (installed via yum groupinstall "Development Tools"):
```
[grahamb@bamboo ~]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)
```

Ubuntu 14.04 (from the `instructure/ruby-passenger:2.4` image):
```
root@c551b63ebdb4:/usr/src/app# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.4' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)
```

**Comment by grahamb** [comment]
We tracked this down to an issue with the latest versions of the `ffi` gem, which was bumped in Canvas in be37267. Reverting it back to 1.9.18 resolved the segfaults in both running compile_assets, as well as with exporting Gradebook CSVs.

There's an open issue on ffi for this: https://github.com/ffi/ffi/issues/621. It may be worthwhile to revert be37267 for the time being.
