### ISSUE TITLE
legacy/collaborations_forms is missing

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#1292]
### Summary:
When loading the course collaborations page (/courses/:course_id/collaborations), a 404 is thrown in the console for `/dist/webpack-production/legacy/collaborations_forms.js`. 

### Steps to reproduce:

 1. Load the collaborations page for a course

### Expected behavior:

It should not throw a 404 for `/dist/webpack-production/legacy/collaborations_forms.js` in the console

### Actual behavior:

- It throws a 404 for `/dist/webpack-production/legacy/collaborations_forms.js` in the console. 
- The `#google_docs_description` element remains hidden and the explanatory text is not visible. 

### Additional notes:

This appears to have been introduced in 514e991 when `app/coffeescripts/bundles/legacy/collaborations_forms.coffee` was [deleted](https://github.com/instructure/canvas-lms/commit/514e9912294110aa793c6233ecc0c06886a0db06#diff-d4547a70d4809af899ccda912277a618). The bundle is still being called in the [collaborations form template](https://github.com/instructure/canvas-lms/blob/master/app/views/collaborations/_forms.html.erb#L141).

cc: @ryankshaw

**Comment by omarkhan** [comment]
Thanks for the bug report @grahamb! This was fixed in 70c6d02
