### ISSUE TITLE
bundle exec rake js:webpack_development or bundle exec rake js:webpack_production produces yarn error

### ISSUE THREAD

**Issue by subratrout** [instructure/canvas-lms#1293]
Summary:
The canvas:compile_assets rake task throws an error.

Steps to reproduce:

    Clone the repository, switch to either stable or master
    Run bundle install and yarn install
    Run bundle exec rake canvas:compile_assets

Expected behavior:

Asset compilation should complete without any issues.

Actual behavior:
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
DEPRECATION WARNING: ActionView::Template::Handlers::Erubis is deprecated and will be removed from Rails 5.2. Switch to ActionView::Template::Handlers::ERB::Erubi instead. (called from <top (required)> at /var/canvas/gems/i18n_extraction/lib/i18n_extraction/i18nliner_extensions.rb:21)
--> Building DEVELOPMENT webpack bundles
yarn run v1.5.1
$ gulp rev & webpack --progress --color
[01:45:10] Using gulpfile /var/canvas/gulpfile.js
[01:45:11] Starting 'rev'...
Happy[babel]: Version: 3.1.0. Using cache? Yes. Threads: 4 (shared pool)
Happy[babel]: No cache was found, starting fresh.
Happy[babel]: All set; signaling webpack to proceed.
Happy[coffee]: Version: 3.1.0. Using cache? Yes. Threads: 4 (shared pool)
Happy[coffee]: No cache was found, starting fresh.
Happy[coffee]: All set; signaling webpack to proceed.
Happy[handlebars-i18n]: Version: 3.1.0. Using cache? Yes. Threads: 4 (shared pool)
Happy[handlebars-i18n]: No cache was found, starting fresh.
Happy[handlebars-i18n]: All set; signaling webpack to proceed.
Happy[handlebars-ember]: Version: 3.1.0. Using cache? Yes. Threads: 4 (shared pool)
Happy[handlebars-ember]: No cache was found, starting fresh.
Happy[handlebars-ember]: All set; signaling webpack to proceed.
 13% building modules 25/102 modules 77 active ...cripts/custom_moment_locales/mi_nz.js[01:45:14] Finished 'rev' after 3.46 s
 90% chunk assets processing
<--- Last few GCs --->

[27693:0x33cd6f0]   262667 ms: Scavenge 222.7 (373.4) -> 208.3 (373.9) MB, 21.5 / 3.8 ms  allocation failure
[27693:0x33cd6f0]   269361 ms: Scavenge 223.0 (373.9) -> 209.3 (374.9) MB, 16.0 / 1.6 ms  allocation failure
[27693:0x33cd6f0]   272943 ms: Scavenge 226.2 (377.3) -> 217.8 (377.8) MB, 22.1 / 2.2 ms  allocation failure
[27693:0x33cd6f0]   275115 ms: Scavenge 227.5 (377.8) -> 220.7 (377.8) MB, 27.1 / 1.3 ms  allocation failure

<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: NewSpace::Rebalance Allocation failed - process out of memory
 1: node::Abort() [node]
 2: 0x11e7fec [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: 0xad2f0b [node]
 6: v8::internal::MarkCompactCollector::Evacuate() [node]
 7: v8::internal::MarkCompactCollector::CollectGarbage() [node]
 8: v8::internal::Heap::MarkCompact() [node]
 9: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
10: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
11: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
12: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
13: v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [node]
14: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
15: v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
16: v8::internal::Builtin_JsonStringify(int, v8::internal::Object**, v8::internal::Isolate*) [node]
17: 0x3b60ebb0697d
Aborted (core dumped)
error An unexpected error occurred: "Command failed.
Exit code: 134
Command: sh
Arguments: -c gulp rev & webpack --progress --color
Directory: /var/canvas
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/var/canvas/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rake aborted!
Error running js:webpack_development:
ABORTING
/var/canvas/lib/tasks/js.rake:42:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => js:webpack_development
(See full trace by running task with --trace)

Additional notes:
I am using Ubuntu droplet on a digitalocean server. Ubuntu: 16.04.4

I have also tried following breakdown steps below and it creates same error on  webpack_development step.

yarn run gulp rev
bundle exec rake js:yarn_install
bundle exec rake css:compile
bundle exec rake css:styleguide
bundle exec rake js:build_client_apps
bundle exec rake i18n:generate_js
bundle exec rake js:webpack_development
bundle exec rake js:webpack_production
bundle exec rake doc:api

**Comment by sdb1228** [comment]
Hey @subratrout have you tried using yarn v1.6.0?

**Comment by subratrout** [comment]
@sdb1228 . I changed the Yarn version to 1.6.0 and now upon running bundle exec rake js:webpack_development I am getting following error.
I am using digitalocean droplet of 4GB RAM and 2 vCPU and 80GB disk space.

/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
DEPRECATION WARNING: ActionView::Template::Handlers::Erubis is deprecated and will be removed from Rails 5.2. Switch to ActionView::Template::Handlers::ERB::Erubi instead. (called from <top (required)> at /var/canvas/gems/i18n_extraction/lib/i18n_extraction/i18nliner_extensions.rb:21)
--> Building DEVELOPMENT webpack bundles
yarn run v1.6.0
$ gulp rev & webpack --progress --color
[18:48:42] Using gulpfile /var/canvas/gulpfile.js
[18:48:42] Starting 'rev'...
Happy[babel]: Version: 3.1.0. Using cache? Yes. Threads: 4 (shared pool)
Happy[babel]: No cache was found, starting fresh.
Happy[babel]: All set; signaling webpack to proceed.
Happy[coffee]: Version: 3.1.0. Using cache? Yes. Threads: 4 (shared pool)
Happy[coffee]: No cache was found, starting fresh.
Happy[coffee]: All set; signaling webpack to proceed.
Happy[handlebars-i18n]: Version: 3.1.0. Using cache? Yes. Threads: 4 (shared pool)
Happy[handlebars-i18n]: No cache was found, starting fresh.
Happy[handlebars-i18n]: All set; signaling webpack to proceed.
Happy[handlebars-ember]: Version: 3.1.0. Using cache? Yes. Threads: 4 (shared pool)
Happy[handlebars-ember]: No cache was found, starting fresh.
Happy[handlebars-ember]: All set; signaling webpack to proceed.
[18:48:46] Finished 'rev' after 3.67 s3 active ...vascripts/vendor/i18n_js_extension.js
 68% building modules 4135/4218 modules 83 active ...les/graphiql/dist/utility/debounce.js
<--- Last few GCs --->

[24603:0x29bf6f0]   114058 ms: Scavenge 255.9 (294.1) -> 247.8 (295.6) MB, 96.2 / 0.9 ms  allocation failure
[24603:0x29bf6f0]   117133 ms: Scavenge 258.5 (295.6) -> 251.1 (301.1) MB, 110.1 / 11.7 ms  allocation failure
[24603:0x29bf6f0]   121208 ms: Scavenge 263.7 (301.1) -> 255.4 (304.6) MB, 267.7 / 19.4 ms  allocation failure
[24603:0x29bf6f0]   123580 ms: Scavenge 267.4 (304.6) -> 262.8 (304.6) MB, 1294.6 / 1.9 ms  allocation failure


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: NewSpace::Rebalance Allocation failed - process out of memory
 1: node::Abort() [node]
 2: 0x11e7fec [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: 0xad2f0b [node]
 6: v8::internal::MarkCompactCollector::Evacuate() [node]
 7: v8::internal::MarkCompactCollector::CollectGarbage() [node]
 8: v8::internal::Heap::MarkCompact() [node]
 9: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
10: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
11: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [node]
12: v8::internal::DescriptorArray::Allocate(v8::internal::Isolate*, int, int, v8::internal::PretenureFlag) [node]
13: v8::internal::JSObject::MigrateSlowToFast(v8::internal::Handle<v8::internal::JSObject>, int, char const*) [node]
14: v8::internal::JSObject::MakePrototypesFast(v8::internal::Handle<v8::internal::Object>, v8::internal::WhereToStart, v8::internal::Isolate*) [node]
15: v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [node]
16: v8::internal::Runtime_StoreIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [node]
17: 0xd17ab8042fd
Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rake aborted!
Error running js:webpack_development:
ABORTING
/var/canvas/lib/tasks/js.rake:42:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => js:webpack_development
(See full trace by running task with --trace)

**Comment by shawniverson** [comment]
@subratrout I am finding in my testing that 4GB of RAM is not enough (it used to be, but I think it has grown since then)

**Comment by sdb1228** [comment]
@subratrout @shawniverson is correct.  You will need some more RAM.  You may be able to get away with 6GB of RAM but usually when we build our assets locally we have our VMs use 8GB

**Comment by subratrout** [comment]
I have upgraded the droplet to 8 GB and it has solved the issue.

**Comment by premmohantyagi** [comment]
Yes, Increased the Memory more or equal to 8 GB, It will fix
