### ISSUE TITLE
Production start installation problem | Generating assets error | xslt.c error

### ISSUE THREAD

**Issue by Geravant** [instructure/canvas-lms#1296]
### Summary:
Hello! I'm trying to install canvas on a local vr machine. But I keep getting this error:
func=xmlSecTransformXsltInitialize:file=xslt.c:line=109:obj=unknown:subj=g_xslt_default_security_prefs == NULL:error=100:assertion: 
It appears during the assets generation and remains in passenger logs, while preventing me from canvas launch.
### Steps to reproduce:

 1. Install canvas according to https://github.com/instructure/canvas-lms/wiki/Production-Start

### Expected behavior:
Set Up production version of canvas-lms
### Actual behavior:
The web pages are unreachable.
### Additional notes:
Ubuntu 16.04, ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux-gnu], npm 5.6.0, yarn 1.6.0, Bundler version 1.13.6

Passenger Raw Process output:
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
func=xmlSecTransformXsltInitialize:file=xslt.c:line=109:obj=unknown:subj=g_xslt_default_security_prefs == NULL:error=100:assertion: 

The error appears at the step 
bundle exec rake css:compile (tracked mannually).

Will be glad for any help.

**Comment by omarkhan** [comment]
Hi @Geravant! We use github issues for bugs only, for support see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help).
