### ISSUE TITLE
Report Image is a terrible UI decision

### ISSUE THREAD

**Issue by NoMan2000** [instructure/canvas-lms#1298]
### Steps to reproduce:

 1. Click a user's photo on a profile.
 2. It will then flag the image with only a confirmation window.

### Expected behavior:
Every other social networking site has taught people that clicking an image of someone means you view a larger image, not that you wish to flag/report an image.

If there is no stored image of a larger file from the uploads, then disable clicking.  Move the report function out to fall in line with expected user behavior.
### Actual behavior:
It displays a pop-up that asks you to confirm the flagged image.

**Comment by omarkhan** [comment]
Hi @NoMan2000 - we use github issues for bugs only, please post feature requests on our [community site](https://community.canvaslms.com/community/ideas).

**Comment by NoMan2000** [comment]
You don't define a feature that doesn't work as intended and results in unintended spam with no way to unflag the spam to be a bug?

**Comment by omarkhan** [comment]
No, it works as intended. If you'd like to change the way it works, you're welcome to start a discussion on our community site, and/or open a pull request with your proposed changes.
