### ISSUE TITLE
Enroll a user: enrollment_state: active cannot be overwritten

### ISSUE THREAD

**Issue by OmarTellers** [instructure/canvas-lms#1299]
### Summary:
POST Enrollment (POST /api/v1/courses/:course_id/enrollments and POST /api/v1/sections/:section_id/enrollments) allows the enrollment state to be set using the API. The state can be changed from: 
- invited to inactive
- invited to active
- inactive to invited
- inactive to active

As well as several undocumented states such as: 'completed' and 'deleted'.
However when the enrollment state is active, it cannot be changed to any other state using the same call. 

### Steps to reproduce:

 1. Enroll a user with the enrollment_state: inactive
 2. Enroll the same user with the enrollment_state: active
 3. Enroll the same user with the enrollment_state: inactive

### Expected behavior:
The enrollment_state is changed from inactive to active back to inactive.
### Actual behavior:
The enrollment_state is changed from inactive to active, the final call does not change the enrollment_state.
### Additional notes:
This issue requires our integration to make use of the specific enrollment delete functionality, which requires input information unknown to our source systems (enrollment id).

**Comment by omarkhan** [comment]
Thanks @OmarTellers! I have passed this on to a product manager for review. I'll keep you posted.
