### ISSUE TITLE
Configuring Postgres documentation issue 

### ISSUE THREAD

**Issue by chrgrd** [instructure/canvas-lms#1303]
### Summary:
The Configuring Postgres  paragraph at https://github.com/instructure/canvas-lms/wiki/Production-Start pasted below:
<pre>
You'll want to set up a Canvas user inside of Postgres. 
Note that in the below commands, you'll want to replace localhost with the hostname
of the server Canvas is running on, 
if Canvas is running on a different server than Postgres.

# createuser will prompt you for a password for database user
sysadmin@dbserver:~$ sudo -u postgres createuser canvas --no-createdb \
   --no-superuser --no-createrole --pwprompt
sysadmin@dbserver:~$ sudo -u postgres createdb canvas_production --owner=canvas
</pre>

may need to be updated: 
- the hostname is part of the unix prompt (versus the command) 
- running sudo -u postgres createdb canvas_production --owner=canvas causes the following error: 
could not change directory to "blah.../work/canvas": Permission denied

Tested on ubuntu 18.04

**Comment by omarkhan** [comment]
Thanks for this @chrgrd. What commands worked for you here?

**Comment by shawniverson** [comment]
@chrgrd Cannot reproduce on Ubuntu 18.04. I am to execute the commands in Production Start as-is.

**Comment by chrgrd** [comment]
I am not able to reproduce the error above. When I run sudo -u postgres createdb canvas_production --owner=canvas, I get createdb: database creation failed: ERROR:  database "canvas_production" already exists
I would need to perform an uninstall to test again.
