### ISSUE TITLE
Upgrade Error: TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by n3rve** [instructure/canvas-lms#1305]
Hello,

I get the following error attempting a Canvas LMS upgrade. I upgraded yarn to version 1.6.0 and node to version 8. I also bundle installed all dependencies succesfully. I get the following when I execute `yarn install`. Is this a bug with the current version or an error with my setup? Any help is appreciated.

```
root@ip-172-31-5-208:/var/www/canvas# git fetch
root@ip-172-31-5-208:/var/www/canvas# git reset --hard origin/stable
HEAD is now at 433333e treesame commit of origin/stable/2018-06-02
root@ip-172-31-5-208:/var/www/canvas# cd /var/www/canvas/
root@ip-172-31-5-208:/var/www/canvas# yarn install
yarn install v1.6.0
$ script/uncache-packages && script/local-yarn install && script/local-yarn build:canvas
TypeError: Cannot read property 'filter' of undefined
    at main (/var/www/canvas/script/remove-packages-from-yarn-integriry:18:49)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@ip-172-31-5-208:/var/www/canvas# 
```

**Comment by simonista** [comment]
Hey @n3rve, reading through https://github.com/instructure/canvas-lms/blob/stable/script/remove-packages-from-yarn-integriry, it looks like it's finding a `node_modules/.yarn-integrity` file but it is not the format it expects.  I'd try moving that file out of the way and trying again. It looks like the script handles it not existing, but doesn't handle it being the wrong format.

You could also just try running https://github.com/instructure/canvas-lms/blob/stable/script/nuke_node.sh to wipe our all existing node modules and re-installing them from scratch.

**Comment by n3rve** [comment]
Thanks @simonista - Using the nuke script helped.
