### ISSUE TITLE
Specify External Tool by ID When Creating Assignment via API

### ISSUE THREAD

**Issue by samhinshaw** [instructure/canvas-lms#1315]
### Summary:

Cannot specify external tool when creating assignment via Canvas API.

### Steps to reproduce:

This issue can be reproduced either via the Canvas API or the Canvas web interface.

 -	Via the Canvas API
     1. Create assignment via Canvas API (`POST /api/v1/courses/:course_id/assignments`).
     2. Specify URL for external tool that requires LTI Authentication.
 - Via the Canvas Web Interface
     1. Create an assignment
     2. In the "Submission Type" section, select "External Tool". 
     3. Input the URL for the external tool manually (do not use "Find").

### Expected behavior:

I would expect to be able to specify an external tool that was added to the course by its ID (obtained via Canvas API - `GET /api/v1/courses/:course_id/external_tools`) so that the launch request contains that tool's consumer key, similar to the way clicking the "Find" button in the web interface works.

### Actual behavior:

I can only specify the URL, and thus the launch request contains a dummy consumer key. 

### Additional notes:

Potentially related to: #630, #297

**Comment by ttimbers** [comment]
@claydiffrient @codekitchen @maneframe @jstanley0 - Can any of you comment on this? It really seems like one should be able to do this using the API and not have to do this manually from the UI inside  the course. This is particularly important for use cases like those of @samhinshaw and mine as our external tool requires a very long URL with custom parameters (a different one for each assignment). So without this fix there remains great potential for errors. This seems like it would be a general error/bug for anyone who would like to use the Canvas API to create assignments using an external tool using a URL with custom parameters.

**Comment by ttimbers** [comment]
@wbhumphrey - thinking you might be able to comment/help with this too perhaps?

**Comment by samhinshaw** [comment]
It turns out this is possible, it is just undocumented. 

The external tool can be specified with the following fields:

```json
{
  "assignment": {
    "external_tool_tag_attributes": {
      "content_id": 1234,
      "content_type": "context_external_tool"
    }
  }
}
```

⚠️ WARNING: These parameters are undocumented for a reason, and are subject to change! Proceed with caution.
