### ISSUE TITLE
discussion-toolbar issues in the discussions page

### ISSUE THREAD

**Issue by vinnyasa** [instructure/canvas-lms#1316]
### Steps to reproduce:

 1. In Groups > Discussions > 
 2. Create a discussion, we also have one reply at the moment
 3.  Scroll down so that the cell touches the top of the browser
4. In the card where the initial discussion is.  The cell where the 'search entries or author' field is and the green Subscribed button is. 

### Expected behavior: 
That cell should stay within its boundaries. It should not be doing that. 

### Actual behavior: 
 starts vibrating and expanding like crazy when scrolling down and the scroll reaches its limit. 

### Additional notes:
Hope that helps. Also, when I opened my developer tools in the browser it stops, only when Canvas is full width it happens.

**Comment by sdb1228** [comment]
hey @vinnyasa is there anyway you can create a screencast or video recording?  I am having a hard time reproducing this behavior on master.
