### ISSUE TITLE
Explicitly listing items in yarn workspaces prevents third-party gems/plugins from building

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#1323]
### Summary:
Canvas started using [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) in e415eaa. In that commit, the `workspaces` property in [package.json](https://github.com/instructure/canvas-lms/blob/e415eaa96119a521b012cd593642ae04db52a7bb/package.json#L10-L21) used fairly liberal wildcard globs to match everything in `./gems` and `./gems/plugins`. This meant that an open-source installation of Canvas could have its own plugins (with node dependencies) in `./gems/plugins` and yarn would install their deps during `yarn install`.

In 7efc1a5, these wildcard globs [were replaced](https://github.com/instructure/canvas-lms/commit/7efc1a5a387cc9274cd1d06e835619dc989d7359#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) with explicit listings for three items in `./gems` and `./gems/plugins`. This means that a gem with node dependencies that is *not* included in this list will not have its dependencies installed by `yarn install` and the subsequent webpack build will fail.

### Steps to reproduce:

 1. Install a gem with node dependencies into `./gems/plugins` (e.g. https://github.com/sfu/canvas-spaces).
 2. Run `yarn`. 
 3. Run `RAILS_ENV=production bundle exec rake canvas:compile_assets`

### Expected behaviour:

Canvas should build normally.
### Actual behaviour:

The webpack build fails as it can not resolve dependencies in the gem. For example:

```

ERROR in ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/alt.js
Module not found: Error: Can't resolve 'alt' in '/path/to/canvas/gems/plugins/canvas_spaces/app/jsx/pages/MySpaces'
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/alt.js 7:11-25
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/actions/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/bundles/spaces.js

ERROR in ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/stores/index.js
Module not found: Error: Can't resolve 'alt-utils/lib/makeHot' in '/path/to/canvas/gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/stores'
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/stores/index.js 19:15-47
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/bundles/spaces.js

ERROR in ./gems/plugins/canvas_spaces/app/jsx/utils/api.js
Module not found: Error: Can't resolve 'cookies-js' in '/path/to/canvas/gems/plugins/canvas_spaces/app/jsx/utils'
 @ ./gems/plugins/canvas_spaces/app/jsx/utils/api.js 11:17-38
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/actions/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/bundles/spaces.js

ERROR in ./gems/plugins/canvas_spaces/app/jsx/index.js
Module not found: Error: Can't resolve 'react-router-dom' in '/path/to/canvas/gems/plugins/canvas_spaces/app/jsx'
 @ ./gems/plugins/canvas_spaces/app/jsx/index.js 11:22-49
 @ ./gems/plugins/canvas_spaces/app/jsx/bundles/spaces.js

ERROR in ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/index.js
Module not found: Error: Can't resolve 'react-router-dom' in '/path/to/canvas/gems/plugins/canvas_spaces/app/jsx/pages/MySpaces'
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/index.js 15:22-49
 @ ./gems/plugins/canvas_spaces/app/jsx/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/bundles/spaces.js

ERROR in ./gems/plugins/canvas_spaces/app/jsx/shared/CommonHeader.js
Module not found: Error: Can't resolve 'react-router-dom' in '/path/to/canvas/gems/plugins/canvas_spaces/app/jsx/shared'
 @ ./gems/plugins/canvas_spaces/app/jsx/shared/CommonHeader.js 15:22-49
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/bundles/spaces.js

ERROR in ./gems/plugins/canvas_spaces/app/jsx/utils/api.js
Module not found: Error: Can't resolve 'superagent' in '/path/to/canvas/gems/plugins/canvas_spaces/app/jsx/utils'
 @ ./gems/plugins/canvas_spaces/app/jsx/utils/api.js 7:18-39
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/actions/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/pages/MySpaces/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/index.js
 @ ./gems/plugins/canvas_spaces/app/jsx/bundles/spaces.js
error Command failed with exit code 2.
```
### Additional notes:

We can work around this in our fork by [adding `gems/plugins/canvas_spaces` to the `workspaces` property in `package.json`](https://github.com/sfu/canvas-lms/commit/188d7602bc92a8320703038d268d1cb8f946c969); however, this is less than desirable as it will likely lead to merge conflicts whenever package.json changes.

**Comment by ryankshaw** [comment]
I think we can fix this by changing it back to 'gems/plugins/*' in the "workspaces" field in package.json. so it would be:

"workspaces": {
     "packages": [
      "gems/canvas_i18nliner",
      "gems/selinimum",
-      "gems/plugins/analytics",
+      "gems/plugins/*",
       "packages/*",
       "client_apps/*"
     ],

does that sound good to you @grahamb ?

**Comment by ryankshaw** [comment]
that just means that any time anyone `yarn install`s they will see these errors:

> Warning: gems/plugins/academic_benchmark is a directory, but has no package.json
Warning: gems/plugins/account_reports is a directory, but has no package.json
Warning: gems/plugins/canvas_geoip is a directory, but has no package.json
Warning: gems/plugins/demo_site is a directory, but has no package.json
Warning: gems/plugins/instructure_misc_plugin is a directory, but has no package.json
Warning: gems/plugins/moodle_importer is a directory, but has no package.json
Warning: gems/plugins/qti_exporter is a directory, but has no package.json
Warning: gems/plugins/respondus_soap_endpoint is a directory, but has no package.json
Warning: gems/plugins/simply_versioned is a directory, but has no package.json

**Comment by grahamb** [comment]
@ryankshaw yep, putting the gems/plugins/* back into workspaces would be great. I can live with yarn warnings.
