### ISSUE TITLE
warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by johnkarasev** [instructure/canvas-lms#1328]
### Summary:
Starting to populate databases and get this:
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated

### Steps to reproduce:

 1. install ruby 2.4.0
 2. follow install steps
 3. do RAILS_ENV=production bundle exec rake db:initial_setup

### Expected behavior:
no warnings
### Actual behavior:
warnings
### Additional notes:
pops out in more places like when running ./scripts/railes console

**Comment by sdb1228** [comment]
Hey @johnkarasev looks like the soap4r library is aware of this warning and has a fix https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889713  I would ignore the warnings until we can get around to updating the dependency.  You can also submit a pull request if you have the time :).
