### ISSUE TITLE
SAML entityID Update

### ISSUE THREAD

**Issue by n3rve** [instructure/canvas-lms#1336]
I've just upgraded our Canvas LMS instance to the latest version successfully. Thanks to all the contributors for the wonderful work you're doing. 

I have cloned our instance to setup a staging environment that will use a different Identity Provider for SAML authentication. However, the entityID displayed on the authentication page (http://canvas-site.com/accounts/1/authentication_providers) is still referencing the old domain. 

I have updated web server URLs and the domain.yml file with the new domain name. I can use the new domain to access Canvas without issue, however the entityID has still not reflected the updated URL. This has resulted in errors at the IdP. 

Can someone tell me how to update the entityID for Canvas?

**Comment by ccutrer** [comment]
Question has been answered on the mailing list.

**Comment by jonathan-russo** [comment]
@ralphotowo @ccutrer 

Can you guys please state the solution to this or point to where I can find the answer on your mailing list?

Having the same issue now (Canvas SP Metadata is setting entityID to the public ip of the host)

**Comment by ralphotowo** [comment]
Hi @jonathan-russo: https://groups.google.com/forum/#!topic/canvas-lms-users/0P2_kng17oY

**Comment by jonathan-russo** [comment]
Thank you @ralphotowo !!!

**Comment by huangdengpan** [comment]
@ralphotowo perfect!
