### ISSUE TITLE
Chrome is blocking LTI external tool redirects

### ISSUE THREAD

**Issue by decademoon** [instructure/canvas-lms#1337]
### Summary:

Recent versions of Chrome are blocking LTI external tools from being launched unless "Load in a new tab" is checked.

### Steps to reproduce:

 1. Add an external tool item with "Load in a new tab" unchecked.
 2. Click the external tool item.

### Expected behavior:

The page should redirect to the external tool.

### Actual behavior:

No redirect occurs, Canvas remains on screen with a blank page and no error message.

### Additional notes:

Chrome displays a small notice in the address bar that the redirect was blocked. This notice is easy to miss and people clicking the button may not realise that Chrome is blocking the redirect and they think the page is broken.

There is something particular about the way Canvas is doing the LTI redirect that Chrome is blocking. Chrome thinks it is an non-user-initiated redirect.

<img width="452" alt="Screenshot" src="https://user-images.githubusercontent.com/5779055/44634020-f7c86100-a9d6-11e8-9590-4edd0410e74c.png">

**Comment by decademoon** [comment]
Here's some additional info in the console about why the redirect was blocked, looks like it is a cross-origin/CORS/framebusting issue:

<img width="717" alt="Screenshot" src="https://user-images.githubusercontent.com/5779055/44634162-40811980-a9d9-11e8-82a0-da1564158192.png">

**Comment by decademoon** [comment]
Actually I'm closing this because I realised that this may not be an issue with Canvas. Our LTI connect endpoint was returning a HTML page which redirects the top window to break out of the iframe a la:

```javascript
top.location.href = "...";
```

Since this is a cross origin iframe, Chrome prevents the iframe from redirecting the top window.

We'll have to figure out some other workaround for our situation.

**Comment by parv25** [comment]
Hi decademoon, were you able to find a solution to this problem? we have currently in a similar solution where the google chrome is blocking the LTI redirect.

**Comment by parv25** [comment]
Thank you! That's really helpful
