### ISSUE TITLE
Rubric scopes are missing

### ISSUE THREAD

**Issue by Boudewijn26** [instructure/canvas-lms#1341]
### Summary:
It's impossible to add the `url:POST|/v1/api/courses/:course_id/rubrics` and `url:PUT|/v1/api/courses/:course_id/rubrics/:id` scopes to a developer key

### Steps to reproduce:

 1. Make sure the 'Developer key management and scoping' feature option is enable
 1. Create or edit a developer key
 2. Enable enforce scopes
 3. Try to add `url:POST|/v1/api/courses/:course_id/rubrics` and `url:PUT|/v1/api/courses/:course_id/rubrics/:id`

### Expected behavior:
The `url:POST|/v1/api/courses/:course_id/rubrics` and `url:PUT|/v1/api/courses/:course_id/rubrics/:id` are available under Rubrics.

### Actual behavior:
The aforementioned scopes are missing.
![image](https://user-images.githubusercontent.com/2896917/45297485-d488d000-b505-11e8-91a9-e87f9d3d626f.png)

### Additional notes:
While these endpoint [aren't documented](https://canvas.instructure.com/doc/api/rubrics.html) they provide very useful functionality for tools that want to send extended grading information.

**Comment by Boudewijn26** [comment]
@ccutrer Would it be possible to give something of an indication here?

**Comment by ccutrer** [comment]
Are you trying to add /api/v1, or /v1/api?

**Comment by Boudewijn26** [comment]
My apologies, /api/v1/ indeed
