### ISSUE TITLE
Incoming mail is not being processed

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#1344]
### Summary:
The August 4 release of Canvas appears to have an issue where incoming mail is not being processed. Delayed jobs are running, the `IncomingMailProcessor::IncomingMessageProcessor#process` job is being queued and run, no errors are visible in the logs or in /error_reports. Messages are not being retrieved from the POP mailbox.

Manually running the processor from a rails console (`IncomingMailProcessor::IncomingMessageProcessor.new(IncomingMail::MessageHandler.new, ErrorReport::Reporter.new).process) seems to work.

### Steps to reproduce:

 1. Set up open-source canvas on the Aug 4 release
 2. Set up incoming_mail.yml to point at a mailbox
 3. Send mail to that mailbox (e.g. reply to notifications from Canvas)

### Expected behavior:
Mail should be retreived from the mailbox and processed by Canvas.

### Actual behavior:
Nothing.

### Additional notes:
Both SFU and OCADU (@christopher-b) are seeing this issue. We're both on the same release. SFU does have the Aug 25 release running in a test environment but it does not process mail.

**Comment by simonista** [comment]
Not sure if it's relevant yet, but 6109d6e72e86ce51a49939ccf4891dc4b0dd1055 did go out with that release.

**Comment by grahamb** [comment]
@simonista yeah, we noticed that too. Stepping through it to see if there's any clues.

**Comment by grahamb** [comment]
Per IRC: temporary workaround is setting `run_current_region_asynchronously` to `false` in the affected periodic jobs (e.g. https://github.com/sfu/canvas-lms/commit/773919857a05f25fe3a52737ccc912201d2af960)

**Comment by christopher-b** [comment]
Glad I'm not crazy. Thanks for the workaround.

**Comment by christopher-b** [comment]
Hi Folks, 
We're still experiencing this issue. We have a cronjob in place to run IncomingMailProcessor::IncomingMessageProcessor#process, but the periodic job does not work.

Could @grahamb's fix, or a fix for the underlying issue make it into stable?

**Comment by simonista** [comment]
Hey @christopher-b, I thought we had fixed this in https://github.com/instructure/canvas-lms/commit/b73b213908f7d8ad86632811d9a391eb0595ad12, which is in release `2018-10-27`. are you running that version yet, or have you tried cherry-picking that commit?

**Comment by christopher-b** [comment]
Whoops, I'm still on `2018-10-06`. We will deploy `2018-10-27` on Nov 16th, so I'll check back then. Thanks for the info.
