### ISSUE TITLE
Why does redirecting to login with self enrollment require delegated authentication?

### ISSUE THREAD

**Issue by tastycode** [instructure/canvas-lms#1351]
We need to support self enrollment links while specifying the authentication provider to use for login. It seems this isn't possible unless we make our SAML authentication provider our first priority login (https://github.com/instructure/canvas-lms/blob/a8fc7bbcfff0c6c5309508e26a36d18b7cb980c8/app/models/account.rb#L1115). Why do we only check the first authentication provider for delegated_authentication when there are so many cases when we may override the provider? Should we lookup the authentication provider specified in `SelfEnrollmentsController#new` and see if that provider is delegated?

https://github.com/instructure/canvas-lms/blob/a8fc7bbcfff0c6c5309508e26a36d18b7cb980c8/app/controllers/self_enrollments_controller.rb#L32

**Proposed change**

```ruby
 def new
    @domain_root_account.reload
    js_env :PASSWORD_POLICY => @domain_root_account.password_policy
    @login_label_name = t("email")

    login_handle_name = @domain_root_account.login_handle_name_with_inference
    @login_label_name = login_handle_name if login_handle_name
    authentication_provider = @domain_root_account.authentication_providers.active.find_by(auth_type: params[:authentication_provider])
    
    if !@current_user && authentication_provider.is_a?(AuthenticationProvider::Delegated) && !(params[:authentication_provider] == 'canvas')
      store_location
      return redirect_to login_url(params.permit(:authentication_provider))
    end
  end
```

**Comment by ccutrer** [comment]
You should open a pull request with your change. I support it in concept. You just need to handle the case where the authentication_provider param isn't provided (i.e. falling back to the old behavior).
