### ISSUE TITLE
Can't access Settings Page after Rich Content Editor Sidebar Enhancements Setting

### ISSUE THREAD

**Issue by pouxol** [instructure/canvas-lms#1353]
### Summary:
Hi Canvas LMS community,

My Canvas LMS was working fine until I changed some settings.
I change some settings in Admin > Settings > Feature Options including the Rich Content Editor Sidebar Enhancements Setting.

After that I was not able to access the Admin > Settings page as well as other pages that include Rich Content I think.

### Steps to reproduce:

 1. Admin > Settings > Feature Options > ACTIVATE Rich Content Editor Sidebar Enhancements

### Expected behavior:

Rick Content Editor Sidebar Enhancements

### Actual behavior:

Page Error and no access to the settings page.

### Additional notes:

Canvas is running on via Bitnami on AWS.

I found this: https://github.com/instructure/canvas-lms/issues/1141
and this: https://github.com/instructure/canvas-lms/issues/1076

Which sound similar.
I was able to find the Setting in the PostgreSQL and change it to off.

Also I deleted the redis dump file.
And I copied the dynamic_settings.yml.example to dynamic_settings.yml

But I still have no access.

Do I have to change something in rich_content.rb ?
Or in dynamic_settings.yml ?

Thank you a lot.

**Comment by athyg** [comment]
@pouxol Hi there, I'm currently having the same problem with my self-hosted Canvas instance. I noticed you closed this issue - has it been resolved? If you have a solution, I'd be very grateful for any information you could pass on. Thanks!

**Comment by kamalmpatel** [comment]
> @pouxol Hi there, I'm currently having the same problem with my self-hosted Canvas instance. I noticed you closed this issue - has it been resolved? If you have a solution, I'd be very grateful for any information you could pass on. Thanks!

@athyg  
Hi, did you find the solution of the problem that you have posted here?

**Comment by athyg** [comment]
Hi @kamalmpatel - it's been a while so I don't recall exactly, but if memory serves I believe this was resolved by upgrading. Hope this helps.
