### ISSUE TITLE
"docker-compose up" lasts too long

### ISSUE THREAD

**Issue by leasonliu** [instructure/canvas-lms#1358]
### Summary:
after I run the command "docker-compose up", the logs keep printing for 30 minutes and seems never gonna stop...

### Steps to reproduce:

 1. run "./script/docker_dev_setup.sh"
 2. run "docker-compose up"

### Expected behavior:
successfully up and can access to "http://canvas.docker/"
### Actual behavior:
keep printing logs, doesn't stop
### Additional notes:

jobs_1      | [21d874b96d1c:17 213] Processing periodic: IncomingMailProcessor::IncomingMessageProcessor#process {"priority":20,"attempts":0,"created_at":"2018-10-12T21:44:01Z","tag":"periodic: IncomingMailProcessor::IncomingMessageProcessor#process","max_attempts":1,"strand":"periodic: IncomingMailProcessor::IncomingMessageProcessor#process","source":null}
jobs_1      | [21d874b96d1c:17 213]   SQL  (0.2ms)  BEGIN  [development:1 master]
jobs_1      | [21d874b96d1c:17 213]   SQL  (0.3ms)  SELECT pg_advisory_xact_lock("half_md5_as_bigint"('periodic: IncomingMailProcessor::IncomingMessageProcessor#process'))  [development:1 master]
jobs_1      | [21d874b96d1c:17 213]   SQL Delayed::Backend::ActiveRecord::Job Load (0.4ms)  SELECT "delayed_jobs".* FROM "delayed_jobs" WHERE "delayed_jobs"."strand" = 'periodic: IncomingMailProcessor::IncomingMessageProcessor#process' AND "delayed_jobs"."locked_at" IS NULL ORDER BY "delayed_jobs"."id" ASC LIMIT 1  [development:1 master]
jobs_1      | [21d874b96d1c:17 213]   SQL  (0.2ms)  SELECT pg_advisory_xact_lock("half_md5_as_bigint"('periodic: IncomingMailProcessor::IncomingMessageProcessor#process'))  [development:1 master]
jobs_1      | [21d874b96d1c:17 213]   SQL SQL (0.5ms)  INSERT INTO "delayed_jobs" ("priority", "handler", "queue", "run_at", "created_at", "updated_at", "tag", "max_attempts", "strand", "shard_id") VALUES (20, '--- !ruby/Delayed::Periodic IncomingMailProcessor::IncomingMessageProcessor#process
jobs_1      | ...
jobs_1      | ', 'canvas_queue', '2018-10-12 21:46:00', '2018-10-12 21:45:01.653672', '2018-10-12 21:45:01.653672', 'periodic: IncomingMailProcessor::IncomingMessageProcessor#process', 1, 'periodic: IncomingMailProcessor::IncomingMessageProcessor#process', 1) RETURNING "id"  [development:1 master]
jobs_1      | [21d874b96d1c:17 213]   SQL  (0.6ms)  COMMIT  [development:1 master]
jobs_1      | [21d874b96d1c:17 213]   SQL  (0.1ms)  BEGIN  [development:1 master]
jobs_1      | [21d874b96d1c:17 213]   SQL SQL (0.5ms)  DELETE FROM "delayed_jobs" WHERE "delayed_jobs"."id" = 213  [development:1 master]
jobs_1      | [21d874b96d1c:17 213]   SQL  (0.6ms)  COMMIT  [development:1 master]
jobs_1      | [21d874b96d1c:17 213] Completed periodic: IncomingMailProcessor::IncomingMessageProcessor#process 9ms
jobs_1      | [21d874b96d1c:17 213] [STAT] 734248 734248 0 0.020000000000000462 0.0
jobs_1      | [- -]   SQL Delayed::Backend::ActiveRecord::Job Load (1.2ms)  WITH limited_jobs AS (SELECT id, ROW_NUMBER() OVER () AS row_number FROM (SELECT "delayed_jobs".* FROM "delayed_jobs" WHERE (run_at<='2018-10-12 21:45:01.659808' AND locked_at IS NULL AND next_in_strand='t') AND ("delayed_jobs"."priority" BETWEEN 0 AND 1000000) AND "delayed_jobs"."queue" = 'canvas_queue' ORDER BY "delayed_jobs"."priority" ASC, "delayed_jobs"."run_at" ASC, "delayed_jobs"."id" ASC LIMIT 1 FOR UPDATE) subquery) UPDATE "delayed_jobs" SET locked_by = CASE row_number WHEN 1 THEN '21d874b96d1c:17' END, locked_at = '2018-10-12 21:45:01.660272' FROM limited_jobs WHERE limited_jobs.id="delayed_jobs".id RETURNING "delayed_jobs".*  [development:1 master]
jobs_1      | [21d874b96d1c:17 214] Processing SummaryMessageConsolidator.process() {"priority":40,"attempts":0,"created_at":"2018-10-12T21:45:01Z","tag":"SummaryMessageConsolidator.process","max_attempts":1,"strand":"SummaryMessageConsolidator.process:development","source":null}
jobs_1      | [21d874b96d1c:17 214]   SQL  (0.4ms)  SELECT DISTINCT "delayed_messages"."communication_channel_id", "delayed_messages"."root_account_id" FROM "delayed_messages" WHERE (workflow_state = 'pending' AND send_at <= '2018-10-12 21:45:01')  [development:1 slave]
jobs_1      | [21d874b96d1c:17 214]   SQL  (0.1ms)  BEGIN  [development:1 master]
jobs_1      | [21d874b96d1c:17 214]   SQL SQL (0.5ms)  DELETE FROM "delayed_jobs" WHERE "delayed_jobs"."id" = 214  [development:1 master]
jobs_1      | [21d874b96d1c:17 214]   SQL  (0.6ms)  COMMIT  [development:1 master]
jobs_1      | [21d874b96d1c:17 214] Completed SummaryMessageConsolidator.process() 5ms
jobs_1      | [21d874b96d1c:17 214] [STAT] 734248 734248 0 0.0 0.020000000000000018
jobs_1      | [- -]   SQL Delayed::Backend::ActiveRecord::Job Load (1.4ms)  WITH limited_jobs AS (SELECT id, ROW_NUMBER() OVER () AS row_number FROM (SELECT "delayed_jobs".* FROM "delayed_jobs" WHERE (run_at<='2018-10-12 21:45:01.690563' AND locked_at IS NULL AND next_in_strand='t') AND ("delayed_jobs"."priority" BETWEEN 0 AND 1000000) AND "delayed_jobs"."queue" = 'canvas_queue' ORDER BY "delayed_jobs"."priority" ASC, "delayed_jobs"."run_at" ASC, "delayed_jobs"."id" ASC LIMIT 1 FOR UPDATE) subquery) UPDATE "delayed_jobs" SET locked_by = CASE row_number WHEN 1 THEN '21d874b96d1c:17' END, locked_at = '2018-10-12 21:45:01.691102' FROM limited_jobs WHERE limited_jobs.id="delayed_jobs".id RETURNING "delayed_jobs".*  [development:1 master]
jobs_1      | [21d874b96d1c:17 216] Processing SisBatchError.cleanup_old_errors() {"priority":40,"attempts":0,"created_at":"2018-10-12T21:45:01Z","tag":"SisBatchError.cleanup_old_errors","max_attempts":1,"strand":"SisBatchError.cleanup_old_errors:development","source":null}
jobs_1      | [21d874b96d1c:17 216]   SQL SisBatchError Exists (0.4ms)  SELECT 1 AS one FROM "sis_batch_errors" WHERE (created_at < '2018-09-12 21:45:01.717268') LIMIT 1  [development:1 master]
jobs_1      | [21d874b96d1c:17 216]   SQL  (0.1ms)  BEGIN  [development:1 master]
jobs_1      | [21d874b96d1c:17 216]   SQL SQL (0.5ms)  DELETE FROM "delayed_jobs" WHERE "delayed_jobs"."id" = 216  [development:1 master]
jobs_1      | [21d874b96d1c:17 216]   SQL  (0.7ms)  COMMIT  [development:1 master]
jobs_1      | [21d874b96d1c:17 216] Completed SisBatchError.cleanup_old_errors() 5ms
jobs_1      | [21d874b96d1c:17 216] [STAT] 734248 734248 0 0.010000000000000675 0.009999999999999787
jobs_1      | [- -]   SQL Delayed::Backend::ActiveRecord::Job Load (1.3ms)  WITH limited_jobs AS (SELECT id, ROW_NUMBER() OVER () AS row_number FROM (SELECT "delayed_jobs".* FROM "delayed_jobs" WHERE (run_at<='2018-10-12 21:45:01.722220' AND locked_at IS NULL AND next_in_strand='t') AND ("delayed_jobs"."priority" BETWEEN 0 AND 1000000) AND "delayed_jobs"."queue" = 'canvas_queue' ORDER BY "delayed_jobs"."priority" ASC, "delayed_jobs"."run_at" ASC, "delayed_jobs"."id" ASC LIMIT 1 FOR UPDATE) subquery) UPDATE "delayed_jobs" SET locked_by = CASE row_number WHEN 1 THEN '21d874b96d1c:17' END, locked_at = '2018-10-12 21:45:01.722719' FROM limited_jobs WHERE limited_jobs.id="delayed_jobs".id RETURNING "delayed_jobs".*  [development:1 master]
jobs_1      | [21d874b96d1c:17 218] Processing AccountReport.delete_old_rows_and_runners() {"priority":40,"attempts":0,"created_at":"2018-10-12T21:45:01Z","tag":"AccountReport.delete_old_rows_and_runners","max_attempts":1,"strand":"AccountReport.delete_old_rows_and_runners:development","source":null}
jobs_1      | [21d874b96d1c:17 218]   SQL  (0.5ms)  SELECT "account_report_rows".id FROM "account_report_rows" WHERE (created_at<'2018-09-12 21:45:01.748803') ORDER BY "account_report_rows".id LIMIT 10000  [development:1 master]
jobs_1      | [21d874b96d1c:17 218]   SQL  (0.3ms)  SELECT "account_report_runners".id FROM "account_report_runners" WHERE (created_at<'2018-09-14 21:45:01.750410') ORDER BY "account_report_runners".id LIMIT 10000  [development:1 master]
jobs_1      | [21d874b96d1c:17 218]   SQL  (0.1ms)  BEGIN  [development:1 master]
jobs_1      | [21d874b96d1c:17 218]   SQL SQL (0.5ms)  DELETE FROM "delayed_jobs" WHERE "delayed_jobs"."id" = 218  [development:1 master]
jobs_1      | [21d874b96d1c:17 218]   SQL  (0.7ms)  COMMIT  [development:1 master]
jobs_1      | [21d874b96d1c:17 218] Completed AccountReport.delete_old_rows_and_runners() 6ms
jobs_1      | [21d874b96d1c:17 218] [STAT] 734248 734248 0 0.0 0.020000000000000018
jobs_1      | [- -]   SQL Delayed::Backend::ActiveRecord::Job Load (1.3ms)  WITH limited_jobs AS (SELECT id, ROW_NUMBER() OVER () AS row_number FROM (SELECT "delayed_jobs".* FROM "delayed_jobs" WHERE (run_at<='2018-10-12 21:45:01.755325' AND locked_at IS NULL AND next_in_strand='t') AND ("delayed_jobs"."priority" BETWEEN 0 AND 1000000) AND "delayed_jobs"."queue" = 'canvas_queue' ORDER BY "delayed_jobs"."priority" ASC, "delayed_jobs"."run_at" ASC, "delayed_jobs"."id" ASC LIMIT 1 FOR UPDATE) subquery) UPDATE "delayed_jobs" SET locked_by = CASE row_number WHEN 1 THEN '21d874b96d1c:17' END, locked_at = '2018-10-12 21:45:01.755824' FROM limited_jobs WHERE limited_jobs.id="delayed_jobs".id RETURNING "delayed_jobs".*  [development:1 master]
jobs_1      | [21d874b96d1c:17 220] Processing SisBatchRollBackData.cleanup_expired_data() {"priority":40,"attempts":0,"created_at":"2018-10-12T21:45:01Z","tag":"SisBatchRollBackData.cleanup_expired_data","max_attempts":1,"strand":"SisBatchRollBackData.cleanup_expired_data:development","source":null}

**Comment by mdjasper** [comment]
Thank you for the report @leasonliu. Actually this is the correct behavior for `docker compose up`. What you are seeing there are the web application logs being output from canvas and other services started (like jobs).

> The docker-compose up command aggregates the output of each container (essentially running docker-compose logs -f). When the command exits, all containers are stopped. Running docker-compose up -d starts the containers in the background and leaves them running.

https://docs.docker.com/compose/reference/up/

**Comment by mdjasper** [comment]
Just to clarify after re-reading my last comment, `docker compose up` is not a build step that executes and finishes. That is the command that starts canvas and the related services then shows the ongoing logs. If it quits logging, then that means the services have stopped. Hope that is helpful!

**Comment by leasonliu** [comment]
> Just to clarify after re-reading my last comment, `docker compose up` is not a build step that executes and finishes. That is the command that starts canvas and the related services then shows the ongoing logs. If it quits logging, then that means the services have stopped. Hope that is helpful!

thanks for the reply, but I can't access to "http://canvas.docker/" after I run 'docker-compose up'
