### ISSUE TITLE
LTI apps can submit grades past the Available Until deadline

### ISSUE THREAD

**Issue by russross** [instructure/canvas-lms#1359]
### Summary:

The "Available until" deadline for an assignment is not enforced for grade submissions from an LTI app.

### Steps to reproduce:

 1. An instructor connects a course to an external LTI tool that posts grades back to Canvas
 2. The instructor creates an assignment in that course with submission type of "External Tool" that is linked to the LTI app
 3. The instructor sets an "Available until" deadline for the assignment
 4. A student uses the LTI tool to submit a grade after the deadline has passed

### Expected behavior:

Canvas rejects the submission and grade since it was posted past the "Available until" deadline, just as it forbids students to submit anything past that deadline through the main Canvas website.

### Actual behavior:

Canvas accepts the submission and the student's grade is updated to reflect the newly-posted assignment grade.

### Additional notes:

The effect is that there is no obvious way for an instructor to set a hard deadline for an assignment if grades for the assignment are submitted via LTI

**Comment by dobesv** [comment]
I would advocate against this as not everything gets a final grade immediately when the student submits it.  The teacher should still be able to change the grade after the student has submitted if they need to.  Some assignments must be graded by the teacher, and it is common that this grading process takes place AFTER the deadline, e.g. as with an examination.

I think the proper solution is that the LTI tool itself must refuse to submit grades after the deadline.

It might be nice if there was a deadline set within Canvas that this would be easily visible to the LTI tool during this process, if it does want to enforce a timeline.

How exacly to achieve that I'm not sure, but I'm definitely against the solution proposed above.

**Comment by russross** [comment]
@dobesv makes a good point--for tools like mine where students are submitting work in real time, having a cutoff is essential, but for other tools using the same mechanism that do not operate in real time this would cause problems.

I'm going to close this issue for three reasons:

1. It has been completely ignored for two years and I don't see the point in keeping it open further
2. There is now a workaround with Canvas extensions to LTI that let the tool discover the deadlines
3. The issue @dobesv raised
