### ISSUE TITLE
docker build using Dockerfile-production throws exception

### ISSUE THREAD

**Issue by lidorcg** [instructure/canvas-lms#1361]
### Summary:
when trying to build production image:
`docker build -f ./Dockerfile-production -t instructure/canvas-lms:prod .`
the exception below is thrown.

### Steps to reproduce:

 1.`git clone ...`
 2.`git checkout stable`
 3.`docker build ...`

### Expected behavior:
slim production image built

### Actual behavior:
```
[5/5] Building fresh packages...
success Saved lockfile.
$ yarn build:packages
yarn run v1.9.4
$ yarn workspace-run build:canvas
$ r() { wsrun $@ --fast-exit --exclude-missing --collect-logs --report; exit $?; } && r build:canvas
/bin/sh: 1: wsrun: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c bash -c '   set -e;     sudo -u docker -E env HOME=/home/docker PATH=$PATH bundle install --jobs 8;   yarn install --pure-lockfile;   COMPILE_ASSETS_NPM_INSTALL=0 bundle exec rake canvas:compile_assets;     sudo -u docker -E env HOME=/home/docker PATH=$PATH bundle install --without test development;   sudo -u docker -E env HOME=/home/docker PATH=$PATH bundle clean --force;   yarn install --prod;     rm -rf     /home/docker/.bundle/cache     $GEM_HOME/cache     $GEM_HOME/bundler/gems/*/{.git,spec,test,features}     $GEM_HOME/gems/*/{spec,test,features}     `yarn cache dir`     /root/.node-gyp     /tmp/phantomjs     .yardoc     client_apps/canvas_quizzes/{tmp,node_modules}     config/locales/generated     gems/*/node_modules     gems/plugins/*/node_modules     log     public/dist/maps     public/doc/api/*.json     public/javascripts/translations     tmp-*.tmp'' returned a non-zero code: 1
```

### Additional notes:
I tried installing `wsrun` but then the next exception is: command `build:canvas` not found.

**Comment by rizkyekoputra** [comment]
got this issue too

**Comment by breiter** [comment]
This is still the case in Jan 2020 in the `stable` brach.. `Dockerfile-production` is clearly unmaintained.

**Comment by simonista** [comment]
Hm, that may well be the case, I don't know that we use the `Dockerfile-production` anywhere internally, although I'm double checking on that. I'll try to sort this out, sorry for the trouble.

**Comment by simonista** [comment]
Okay, I've confirmed that nothing is currently using this internally, which is probably why it has fallen into disrepair. It was originally added to try to provide a lighter-weight image for our test runner to speed things up, but things changed and our tests went a different direction. We're still hoping to get back to this image in the future, but for now we'd recommend just using the `Dockerfile` for development or putting together something yourself for production use.
