### ISSUE TITLE
Cannot open http://canvas.docker

### ISSUE THREAD

**Issue by leasonliu** [instructure/canvas-lms#1371]
### Summary:
try to access to http://canvas.docker from ssh, the canvas-lms is running on docker on a virtual machine.

Cannot open http://canvas.docker after successfully installed, but can open using ip address with domain error: **"jquery.js:1574 GET http://canvas.docker/courses/1/files/1/download?verifier=xxxx net::ERR_CONNECTION_REFUSED."**

### Steps to reproduce:

 1. run "./script/docker_dev_setup.sh" in virtual machine, succssfully installed
 2. open http://canvas.docker

### Expected behavior:
can access to http://canvas.docker
### Actual behavior:
This site can’t be reached
canvas.docker’s server IP address could not be found.
ERR_NAME_NOT_RESOLVED

**Comment by romualdleuga** [comment]
Hello All,
This is still an issue. Do you have any link to point us to please?
