### ISSUE TITLE
NoMethodError (undefined method `lti_guid' for #<Account:0x00000000142bfb10>):

### ISSUE THREAD

**Issue by geekfly2016** [instructure/canvas-lms#1374]
I followed the quick start to install the canvas, the following error occurred, how can I solve it? Thanks~
----------------------------------
Installation Environment：
        os：Ubuntu 14.04, 18.04
       ruby：2.4.4
       gem: 2.6.14.1
       rails：5.1.6
       yarn：1.10.1
       postgresql：9.5
       npm：6.4.1
----------------------------------
Redis (0.326ms) evalsha - [127.0.0.1:6379]

NoMethodError (undefined method `lti_guid' for #<Account:0x00000000142bfb10>):
  /var/lib/gems/2.4.0/gems/activemodel-5.1.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
  /home/canvas/canvas/app/controllers/application_controller.rb:2310:in `setup_live_events_context'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `block in make_lambda'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:198:in `block in halting'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `block in invoke_before'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `each'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `invoke_before'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:106:in `block in run_callbacks'
  /home/canvas/canvas/app/controllers/application_controller.rb:464:in `report_to_datadog'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  /var/lib/gems/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:81:in `batch'

**Comment by shriram-cd** [comment]
@geekfly2016 were you able to solve this issue?

**Comment by ecornellnick** [comment]
I'm also having this issue.
