### ISSUE TITLE
Canvas installation fails on "Database population": Connection refused on port 8500

### ISSUE THREAD

**Issue by dugokontov** [instructure/canvas-lms#1415]
### Summary:
I wanted to install canvas locally using this guide: https://github.com/instructure/canvas-lms/wiki/Quick-Start.
When I run:

```bash
$ bundle exec rails db:initial_setup
```
a lot of migrations got executed, but at some point this error occurs: `Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 8500`

(full log can be seen here: https://gist.github.com/dugokontov/2a6965ef1273bbd7b53fda8332b4aa7b)

This is info about my system:

|   program    |         version         |
|--------------|-------------------------|
| Linux        | 4.4.0-53-generic x86_64 |
| Mint         | 18.1                    |
| ruby         | 2.4.4p296               |
| node         | 10.14.2                |
| Redis server | 3.0.7                   |
| psql         | 9.5.7                   |
| yarn | 1.12.3 |

I haven't installed `consul`, but I have copied dynamic settings configuration (as per instructions in quick start):
``` bash
$ cp config/dynamic_settings.yml.example config/dynamic_settings.yml
```

Things I did different than those described in quick start guide were: I installed ruby 2.4.4 using rvm and node using nvm.

**Comment by jesseocon** [comment]
I'm having the same issue. Have you made any progress?

**Comment by ccutrer** [comment]
Port 8500 is consul, so you probably have a config/consul.yml when you shouldn't. Even if you have config/dynamic_settings.yml, it is ignore if you have a config/consul.yml.

**Comment by dugokontov** [comment]
When i try to find any file that has `consul` in it's name I get following:

```sh
➜  canvas git:(stable) find . -name "*consul*"  
./docker-compose/config/consul.yml
./docker-compose/consul.override.yml
./config/initializers/_consul.rb
./config/consul.yml.example
./doc/docker/consul.md
./script/consume_consul_events
./spec/initializers/consul_initializer_spec.rb
```

If I remove `./docker-compose/config/consul.yml` file I still get same error: `Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 8500`

**Comment by ejubkadric94** [comment]
I have got the same issue. 
```
func=xmlSecTransformXsltInitialize:file=xslt.c:line=109:obj=unknown:subj=g_xslt_default_security_prefs == NULL:error=100:assertion: 
default: development
==  AddCrocodocIdToUsers: migrating ===========================================
-- add_column(:users, :crocodoc_id, :int)
   -> 0.0008s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Connection refused - Connection refused - connect(2) for "localhost" port 8500 (localhost:8500)
```

**Comment by ejubkadric94** [comment]
I have found a solution.

All I needed to do, to evade the consul error - was to delete the configuration file `config/consul.yml`, which I previously created with `cp config/database.yml.example config/database.yml`. Therefore, you should consider updating the wiki Quick start guide with valid instructions. 

After that, I had to run:
```
bundle exec rails canvas:compile_assets
```
and then, the script executed with `$ bundle exec rails db:initial_setup` worked.

**Comment by rizkyekoputra** [comment]
I got the same issue too, after removing follow @ejubkadric94 instruction, I got this error now

```default: development
==  AddCrocodocIdToUsers: migrating ===========================================
-- add_column(:users, :crocodoc_id, :int)
   -> 0.0027s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

getaddrinfo: nodename nor servname provided, or not known```

when running `$ bundle exec rails db:initial_setup `

**Comment by rizkyekoputra** [comment]
Solved, my issue cause of my Redis.yml, I solve this with remove all line on Redis.yml

**Comment by simonista** [comment]
Hi @dugokontov, thanks for including the stack trace. I figured out what's going on here. If you have ha_cache configured in dynamic settings, it needs a connection to consul even if you are using dynamic_settings.yml to populate settings instead of consul. It uses consul to invalidate cache keys across nodes (see https://github.com/instructure/canvas-lms/blob/master/lib/active_support/cache/ha_store.rb#L41).

I've added some extra text trying to explain this to the quick start guide, hopefully that will help those hitting it in the future: https://github.com/instructure/canvas-lms/wiki/Quick-Start/_compare/f28c27511f838414c11a0b235d237a447e6f4fd6...b6768d95fffb1a8255fa5dfecde5a368ffb7e88d

**Comment by HamzaBinSarfraz** [comment]
Hi, i tried @ejubkadric94  and @rizkyekoputra solution
Nothing seems to work for me.
Still getting this error

> Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 8500

After running this command

> bundle exec rails db:initial_setup

i am using 

| Node | 10.15.3 |
| Yarn |  1.21.1 |
| PostgreSQL | 10.12 |
| ruby | 2.4.9p362 |
| OS | Ubuntu 18.04 |

**Comment by GeovannyLopez** [comment]
Commenting the line:
consul_event: "canvas/dev/invalidate_ha_cache"
in the dynamic.settings.yml file solved the problem for me.

**Comment by annhienktuit** [comment]
I solved the problem by delete `dynamic_settings.yml.example`

**Comment by annhienktuit** [comment]
I solved the problem by delete the file `dynamic_settings.yml`
