### ISSUE TITLE
enable Self Registration in development environment  

### ISSUE THREAD

**Issue by aakashkag** [instructure/canvas-lms#1419]
You need to enable Self Registration. Start script/console, and run the following:

a = Account.default
a.settings[:self_registration] = true
a.save!

_Originally posted by @ccutrer in https://github.com/instructure/canvas-lms/issues/324#issuecomment-20150406_

I am running development environment using docker. 
I can't find script/console.
how to enable  Self Registration

**Comment by grahamb** [comment]
@aakashkag You're referencing an issue from six years ago and it no longer applies. To get into a rails console, you can do the following:

```
cd /path/to/your/canvas/installation
bin/rails c
```

That will (eventually, it takes a bit of time) land you at a Rails console. From then you can issue the commands (assuming they're still current; I haven't checked).

**Comment by aakashkag** [comment]
thanks :+1:
