### ISSUE TITLE
Development server fails to build webpack.

### ISSUE THREAD

**Issue by dnapier** [instructure/canvas-lms#1429]
### Summary:
OS X 10.14.3 fails to build webpack.

### Steps to reproduce:

 1. git clone https://github.com/instructure/canvas-lms
 2. cd canvas-lms
 3. ./script/tdocker_dev_setup.sh .  EDIT: Removed 's' from 'scripts'

### Expected behavior:
Working development installation of canvas-lms.

### Actual behavior:
ERROR: Service 'webpack' failed to build: lstat /mnt/sda1/var/lib/docker/overlay2/ddb04a5680b7003a9fdd6d88c38fdd55c4c0feb3e6fbffddf82f63f73eea7f72-init/merged/0f47acb39661c72db239f42b6a90fec5ad867236be762362171f3c83f97f0cc5/diff/etc: stale NFS file handle

### Additional notes:

**Comment by binoysmail** [comment]
I did a clone of the repo. The path in the repo is `/script/docker_dev`_setup.sh and not `/scripts` an extra 's' is added in the post

**Comment by nikoma** [comment]
Was this ever solved? I just encountered the same issue.

**Comment by simonista** [comment]
`stale NFS file handle` sounds like a docker error to me. I'd try restarting docker or restarting the system to get NFS into a happier state.
