### ISSUE TITLE
Developer keys with enforced scopes can't be used to log out

### ISSUE THREAD

**Issue by UniversalSuperBox** [instructure/canvas-lms#1430]
### Summary:

It isn't possible to use `DELETE /login/oauth2/token` to log out an access token from a developer key which has "Enforce scopes" enabled. The scope `url:DELETE|/login/oauth2/token` doesn't seem to exist in the scope list.

### Steps to reproduce:

 1. Create a developer key with "Enforce scopes" enabled and your preferred scopes
 1. Create a refresh, then access token using the developer key
 1. Attempt to delete the refresh key using `DELETE /login/oauth2/token` with your access token in the Authorization header

### Expected behavior:

I receive a HTTP 200 and neither the refresh key nor access token are authorized

### Actual behavior:

I receive a HTTP 401 and both keys are still authorized. Canvas returns the "Something broke" error page HTML.

### Additional notes:

There are a couple workarounds for this issue but I don't really like them:

* Disable "Enforce scopes" on the developer key and don't send scopes when requesting an access token (I dislike a token having that much power)
* Disable "Enforce scopes" on the developer key and add the `url:DELETE|/login/oauth2/token` scope when requesting an access token (The key still has all the power, plus #1343 makes it difficult to recommend this to other developers)

This issue could be fixed (in my mind, not controlling you :D ) by either adding the `DELETE /login/oauth2/token` scope to the "Enforce scopes" checklist or always allowing access to the endpoint, even to enforced keys.

**Comment by ccutrer** [comment]
I have a strong preference for the last solution - a token should always have implicit permission to delete itself.

**Comment by rivernate** [comment]
https://github.com/instructure/canvas-lms/commit/276e35aec704464e6d4a53f9ff2dd5f4fb6432c2 fixes this.
