### ISSUE TITLE
896c367 breaks course settings

### ISSUE THREAD

**Issue by newperson1746** [instructure/canvas-lms#1431]
### Summary:
On a new Canvas install with postgres/nginx/passenger/Ubuntu 19.04, the "Visibility" option in the "Settings" menu on a course's sidebar is blank, and clicking "Update Course Details" fails with "Unexpected error, ID: XX" (some two digit number) shown in browser, and an `ArgumentError` in console.
### Steps to reproduce:

 1. Install Canvas normally
 2. Login as a user with privilege to edit a course's settings
 3. Click "Update Course Details"

### Expected behavior:
Canvas saves course settings, and the Visibility option shows a dropdown menu.
### Actual behavior:
Canvas fails to save course settings, and the Visibility option shows a blank menu.

### Additional notes:
I have traced the problematic commit to 896c367157f34016a270f337b97ddcef0ea5d537, and manually reverting its changes (followed by an nginx reload, of course) fixes the issue and makes the Visibility option show a dropdown menu like normal, and saving works again. 
![Screenshot from 2019-04-05 23-46-05](https://user-images.githubusercontent.com/19787725/55664589-5ae86480-57fe-11e9-8417-1175d709ae37.png)
![Screenshot from 2019-04-05 23-47-57](https://user-images.githubusercontent.com/19787725/55664592-5f148200-57fe-11e9-8480-fce8ba6c0768.png)
Full error traceback: 
[canvastraceback.txt](https://github.com/instructure/canvas-lms/files/3050126/canvastraceback.txt)

**Comment by ccutrer** [comment]
Fixed by https://github.com/instructure/canvas-lms/commit/1ccb7a06582bb2e698b3c15a2669b2a3a82917f6
