### ISSUE TITLE
Integration with OpenId Identity provider is exposing private data

### ISSUE THREAD

**Issue by jcmedeiros** [instructure/canvas-lms#1435]
### Summary:
I'm integrating Canvas with another system, using the OpenId Connect to authenticate a Canvas user. While debugging the process on the OpenId Provider side, I've noticed that additional parameters were being passed in the get token request. Furthermore, the extra parameter is exposing a password that is not directly related with the OpenId Connect protocol.
 
### Steps to reproduce:
The issue is reproducible on the OpenId Connect identity provider side (the authorisation server), but can be tracked on Canvas side.
Canvas is using the Authorisation Code Flow to get the user identity ([Section 3.1](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth)). When requiring the token ([section 3.1.3.1](https://openid.net/specs/openid-connect-core-1_0.html#TokenRequest)), according to OpenId documentation and [OAuth spec, section 4.1.3](https://tools.ietf.org/html/rfc6749#section-4.1.3), the request parameters should be: `grant_type`, `code`, `redirect_uri` and `client_id`.

These parameters are correctly being sent but, additionally, a `client_secret` is being passed. The content of this parameter does not match the client secret, provided in the OpenId Connect settings placed in the Authentication tab of the account administrator. Instead, the sub-account admin password is being sent.

According to the documentation I believe this parameter should not be sent and, if some credentials were to be sent, they should match some settings on the OpenId provider and not a Canvas user.

### Additional notes:
I'm testing my integration using a [Bitnami virtual machine](https://bitnami.com/stack/canvaslms/virtual-machine), version 2019.03.09.20-0, Canvas version 2019.03.09.20, according to the [change log](https://bitnami.com/stack/canvaslms/changelog.txt).

**Comment by Sneekeh** [comment]
Hello,

We've been attempting to reproduce this behavior internally at instructure this morning and have been unable to do so. Can you please email security@instructure.com with more details?

**Comment by ccutrer** [comment]
Please see also the OAuth spec: https://tools.ietf.org/html/rfc6749#section-2.3.1. It is required that the OAuth client authenticate itself to the authorization server, using its client_secret. This may either be done using an Authorization header with Basic auth, or via client_id and client_secret request params. Canvas just happens to use the latter.

**Comment by jcmedeiros** [comment]
Cody,

I'm aware of these confidential clients. However, authorisation server and
client server should share a secret for this authentication process to
occur. And, actually, in Canvas, when we set up an OpenId integration, we
define a client secret that is being used to sign the JWT ID token.
Nevertheless, the secret that is being sent is not this one: it's the
password of the sub-account admin.
I don't know if I'm doing anything wrong, but this is what I'm getting.
Perhaps you should double check this behaviour on Canvas side.
Regards,
José Medeiros

**Comment by ccutrer** [comment]
I have checked the Canvas behavior :). That's how I confirmed that we _are_ sending the client_secret. I just pushed a commit to update to the latest version of the OAuth2 gem, which will default to sending the client credentials in the header, rather than the post body.

However, I'm unable to reproduce, or even fathom, how Canvas could be sending the subaccount admin's password. Canvas does not even store user password in a from that can be restored to the its original cleartext form.

How about trying this: change the admin's password, and then see if Canvas sends the new password as the client_secret.

**Comment by jcmedeiros** [comment]
Cody,

You have a very good point! Perhaps the problem is related with the Bitnami
VM setup. The secret I'm getting matches the password that was defined by
the Bitnami setup to the default admin account. Moreover, I'm not being
able to change the password. I guess I'll setup a new development
environment and I'll get back to you if I can find the source of the
problem.
Sorry to waste your time.
Regards,
José Medeiros

**Comment by jcmedeiros** [comment]
I've just found out what was happening. The problem was that I was using 2
different secrets: The secret that I had set up in Canvas was not the same
that I was using to sign the JWT token. My bad.
However, please note that this also means that Canvas is not validating the
returned JWT signature.

**Comment by ccutrer** [comment]
That is correct. Canvas does not currently validate JWTs, as they are not a required part of the OpenID Connect Core spec. We _do_ validate TLS certificates, so it's assumed you're setting it up over TLS, and that you have a valid certificate.
