### ISSUE TITLE
database initialization issue

### ISSUE THREAD

**Issue by fillorkill** [instructure/canvas-lms#1444]
during database initialization
`bundle exec rails db:initial_setup`
got
`/var/lib/gems/2.5.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/lib/gems/2.5.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
rails aborted!
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 75 column 7
/var/lib/gems/2.5.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:149:in `load'
/home/derek/dev/canvas/config/application.rb:197:in `load'
/var/lib/gems/2.5.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb:29:in `safe_load'
/var/lib/gems/2.5.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb:12:in `load_with_options'
/home/derek/dev/canvas/lib/config_file.rb:45:in `load'
/home/derek/dev/canvas/lib/canvas/dynamic_settings.rb:75:in `root_fallback_proxy'
/home/derek/dev/canvas/lib/canvas/dynamic_settings.rb:113:in `find'
/home/derek/dev/canvas/lib/canvas.rb:87:in `cache_store_config_for'
/home/derek/dev/canvas/config/initializers/cache_store.rb:28:in `block in <top (required)>'
/home/derek/dev/canvas/config/initializers/cache_store.rb:70:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:286:in `load'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:286:in `block in load'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:286:in `load'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/engine.rb:655:in `block in load_config_initializer'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:168:in `instrument'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/engine.rb:654:in `load_config_initializer'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/engine.rb:611:in `each'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/engine.rb:611:in `block in <class:Engine>'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:59:in `block in run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:48:in `each'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:48:in `tsort_each_child'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/initializable.rb:58:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/application.rb:353:in `initialize!'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/railtie.rb:185:in `public_send'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/railtie.rb:185:in `method_missing'
/home/derek/dev/canvas/config/environment.rb:28:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/application.rb:329:in `require_environment!'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/home/derek/dev/canvas/lib/tasks/db_load_data.rake:206:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/command.rb:46:in `invoke'
/var/lib/gems/2.5.0/gems/railties-5.1.6.2/lib/rails/commands.rb:16:in `<top (required)>'
/home/derek/dev/canvas/bin/rails:9:in `require'
/home/derek/dev/canvas/bin/rails:9:in `<top (required)>'
/var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/var/lib/gems/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/home/derek/dev/canvas/bin/spring:13:in `require'
/home/derek/dev/canvas/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate:predeploy => environment
(See full trace by running task with --trace)
`

**Comment by UniWrighte** [comment]
@fillorkill did you figure out what was wrong?
