### ISSUE TITLE
Dockerfile issue during quick start

### ISSUE THREAD

**Issue by jldinh** [instructure/canvas-lms#1451]
### Summary:

The quick start setup fails while building the docker image at https://github.com/instructure/canvas-lms/blob/ee673b19262f1dad47bb12548b8bde721e04739c/Dockerfile#L102

### Steps to reproduce:

 1. Clone the repository
 2. Run `./script/docker_dev_setup.sh`

### Expected behavior:

The setup should succeed.

### Actual behavior:

It seems the syntax used there is not parsed correctly by Docker when it passes it on to the shell, as it works fine when run in `sh` directly, but returns the following error during the Docker build:

```
Step 30/31 : RUN [[ -f Gemfile.lock || -f Gemfile.lock.52 ]] && bundle lock --update
 ---> Running in 910b8269e197
/bin/sh: 1: [[: not found
/bin/sh: 1: -f: not found
ERROR: Service 'webpack' failed to build: The command '/bin/sh -c [[ -f Gemfile.lock || -f Gemfile.lock.52 ]] && bundle lock --update' returned a non-zero code: 127
```

### Additional notes:

My docker version: Docker version 18.09.5, build e8ff056

Seems introduced by b3826e0d88b5e7ced17c450813a9c9299679262a

**Comment by djbender** [comment]
should be good to go! thanks for reporting!
