### ISSUE TITLE
uninitialized constant after canvas update: CanvasStatsd

### ISSUE THREAD

**Issue by gicosens** [instructure/canvas-lms#1470]
### Summary:

After canvas update from Git working through asset compiling and GEM update we come across the following error - Site in development mode.

server 500 error:
uninitialized constant CanvasStatsd (NameError)
  /var/canvas/config/initializers/canvas_statsd.rb:21:in `block in <top (required)>'

### Steps to reproduce:

$ sudo RAILS_ENV=development bundle exec rake canvas:compile_assets --trace
~~
~~
** Invoke css:compile (first_time)
** Execute css:compile
--> Starting: 'css:compile'
** Invoke brand_configs:write (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: NoMethodError

**Comment by djbender** [comment]
hey there! we removed that gem and config file as part of c013ee4396bb46139ad6b54b689e1e10a38bdb7f. 

Are you on the latest master commit and have you reinstalled dependencies with `bundle install`, and restarted the rails process?

**Comment by gicosens** [comment]
Yep have tried that, and no change. I wonder if we have missed something in the way we have updated our files from Git. We've done the rebase into ~/canvas (which we marked marked stable at original install) and then copied all those files into the /var/canvas folder to update the assets etc.

**Comment by djbender** [comment]
is `config/initializers/canvas_statsd.rb` still present in `/var/canvas`?

**Comment by gicosens** [comment]
yes

**Comment by djbender** [comment]
OK! If I had to wager a guess it sounds like maybe the copy step you mentioned isn't deleting files in /var/canvas that have been removed in ~/canvas with git?

**Comment by gicosens** [comment]
After my second post I suddenly thought that may be the case. Is there a 'best practice' solution for this in the upgrade process?

**Comment by djbender** [comment]
A simple solution would be to run canvas out of a git repo. If you are interested in what others are up to you can check out our user group here: https://groups.google.com/forum/#!forum/canvas-lms-users

I'm marking this as closed now since this is now outside the scope of our issue tracker.
