### ISSUE TITLE
Wrong anonymous peer review links in Dashboard To Do

### ISSUE THREAD

**Issue by va7map** [instructure/canvas-lms#1475]
### Summary:

Anonymous peer review reminders in the To Do section of the Dashboard (Card View) incorrectly link to the reviewee's submissions, rather than anonymized submissions.

### Steps to reproduce:

 1. As a teacher, create an assignment that requires anonymous peer review.
 2. Make a submission as two students, then assign peer reviews as a teacher.
 3. As one of those students, go to the Dashboard and switch to Card View.
 4. Click on the Peer Review assignment under To Do in the sidebar.

### Expected behavior:

The student should see a page where they can complete the peer review process.

The URL of the page should be `/courses/:course_id/assignments/:assignment_id/anonymous_submissions/:anonymous_id`.

### Actual behavior:

The student sees this error message:

> Access Denied
> You don't have access to view this resource.

The URL of the page is `/courses/:course_id/assignments/:assignment_id/submissions/:reviewee_user_id`.

### Additional notes:

Not only does this prevent the student from reviewing the submission, this also exposes the `user_id` of the reviewee. This issue is only reproducible when using Card View; List View links with correctly anonymized URLs.

I believe this is caused by `AssessmentRequestPresenter` not anonymizing the URL in `#submission_path`.

**Comment by ktgeek** [comment]
We just merged c1eafebe28529d53646f26ad349c596026e5b6db which should address this.  Thanks for the report!
