### ISSUE TITLE
Issues related to running canvas in heroku

### ISSUE THREAD

**Issue by railsfactory-rajeshrs** [instructure/canvas-lms#148]
I wish to run canvas-lms as a site in heroku.  When I do a heroku db:initial_setup it shows the following error:

rake aborted!
An error has occurred, this and all later migrations canceled:

PGError: ERROR:  language "plpgsql" does not exist
HINT:  Use CREATE LANGUAGE to load the language into the database.
: CREATE FUNCTION enrollments_after_insert_row_when_new_workflow_state_active__tr()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.workflow_state = 'active' THEN
        UPDATE assignments
        SET needs_grading_count = needs_grading_count + 1
        WHERE id IN (SELECT assignment_id
                     FROM submissions
                     WHERE user_id = NEW.user_id
                       AND context_code = 'course_' || NEW.course_id
                       AND ( submissions.submission_type IS NOT NULL AND ( submissions.score IS NULL OR NOT submissions.grade_matches_current_submission OR submissions.workflow_state IN ('submitted', 'pending_review') ) )
                    );
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

Tasks: TOP => db:initial_setup => db:migrate

Is this error fixable?

How can this create function be run ? Kindly help

**Comment by chrisjoywebb** [comment]
Has anyone attempted to deploy a recent build of Canvas to Heroku? We're working through this process and would love to know if anyone else has had success. Thanks!

**Comment by gelojavonitalla** [comment]
Bump. I would also like to know if anyone succeed in deploying the recent build to Heroku. Thanks!

**Comment by sshaginyan** [comment]
👍

**Comment by bootstraponline** [comment]
Canvas is developed to run on AWS. As a result, Heroku is not supported.

**Comment by leeish** [comment]
+1

**Comment by Git-Leon** [comment]
> @randomor @mswilkison I was able to get the saml-mod gem working on heroku, for a different project, I post about it here: http://www.codingfoo.com/posts/ruby-saml-mod-on-heroku.html

The new URL can be found here:
https://www.codingfoo.com/posts/ruby-saml-mod-on-heroku/
