### ISSUE TITLE
Stale[bot] is evil

### ISSUE THREAD

**Issue by shawniverson** [instructure/canvas-lms#1481]
### Steps to reproduce:

 1. Open an issue
 2. Wait a few
 3. Stale[bot] closes the issue

### Expected behavior:

Stale[bot] leaves me alone and someone helps me

### Actual behavior:

Stale[bot] attacks and closes issue before someone can help me

### Additional notes:

Stale[bot] is evil.

**Comment by djbender** [comment]
Hey @shawniverson please let us know if you have a specific concern in a stale/closed ticket?

**Comment by shawniverson** [comment]
@djbender Stale[bot] failed me! This ticket disproves the evilness of Stale[bot].
