### ISSUE TITLE
How To Create Advertisement Display Space on Canvas LMS

### ISSUE THREAD

**Issue by UbuntuEvangelist** [instructure/canvas-lms#1482]
I believe there is a way to modify the javascript so as to cusotmize the main page that is displayed to students. On this page I want to place on the side of the page a custom advertisment. I will then use this space to sell add space to companies so that they can advertise on our platform.

**Comment by simonista** [comment]
Have a look at the this guide about the theme editor: https://guides.instructure.com/m/4214/l/724282-how-do-i-upload-custom-javascript-and-css-files-to-an-account
