### ISSUE TITLE
The GET login/oauth2/auth endpoint does not follow the auth2 spec when responding to invalid scopes

### ISSUE THREAD

**Issue by hmstepanek** [instructure/canvas-lms#1483]
### Summary:
The GET login/oauth2/auth endpoint does not follow the auth2 spec when responding to invalid scopes.
 
### Steps to reproduce:
 1. Create a scoped developer token. 
https://user-images.githubusercontent.com/22498/61131730-e20a4000-a4b1-11e9-889e-ce770be5762a.gif
 2. Issue a login/oauth2/auth request with a scope that does not match the scopes on the developer token created in step 1 and a valid redirect uri.
```https://hypothesis.instructure.com/login/oauth2/auth?client_id=<developer token id>&response_type=code&redirect_uri=https://hypothes.is/canvas_oauth_callback&state=<jwt>&scope=url:GET|/api/v1/courses/:course_id/folders```
 3.  It raises a HTTP 400 error.  {"error":"invalid_scope","error_description":"A requested scope is invalid, unknown, malformed, or exceeds the scope granted by the resource owner."}`.

### Expected behavior:
According to the [OAuth 2 spec](https://tools.ietf.org/html/rfc6749#section-4.1.2.1) authorization errors other than an invalid redirect URI are supposed to be handled by redirecting but with error details in the query params.

### Actual behavior:
Instead it currently raises an error.
![image](https://user-images.githubusercontent.com/30059933/62235726-67cb2e00-b382-11e9-9ab0-b533831759f7.png)

### Additional notes:
It would be helpful if the error message included which scopes exceeded the developer key's scope that way admins and application users know which scopes they are missing.

**Comment by ohgabbey** [comment]
Hi. Were you able to find a solution?

**Comment by ccutrer** [comment]
This was fixed in 96b6be4d2dff9f106d022487743e7bca1fdec86b
