### ISSUE TITLE
Cant run new Canvas releases locally with Quick Start guide

### ISSUE THREAD

**Issue by SamMalcolm** [instructure/canvas-lms#1496]
### Summary:

I run Canvas locally to test with and I set that up using the quick start guide. The problem is whenever I use a recent release, or master, the server throws an error every time I try to use it. So I am forced to use an old release. 

### Steps to reproduce:

 1. Follow steps in the quick start guide and the steps to set up the prepare script
 2. checkout master branch and run prepare
 3. run bundle exec rails server

### Expected behavior:

Canvas to be accessible

### Actual behavior:

Canvas throws this error: `undefined method 'shard'`

<img width="1135" alt="Screen Shot 2019-08-19 at 12 35 03 pm" src="https://user-images.githubusercontent.com/28941757/63236039-89338180-c27f-11e9-896d-4952dbaec280.png">

### Additional notes:

This is possibly not a bug and maybe something ommited from the quick start steps to mitigate this issue, advice appreciated

**Comment by ccutrer** [comment]
I’m fairly certain you need to clear your cache. Are you running beta, or stable? (There are two possible causes)

**Comment by SamMalcolm** [comment]
> I’m fairly certain you need to clear your cache. Are you running beta, or stable? (There are two possible causes)

As in the system cache? Im just trying to run the master branch, which I presume is beta stuff. Should I just be checking out the stable branch?

**Comment by ccutrer** [comment]
The Redis cache. And the master branch would be even ahead of beta. If you're not doing development on Canvas, the stable branch is likely what you want to run.

**Comment by SamMalcolm** [comment]
Cleared redis cache with
```bash
redis-cli FLUSHALL
```
Pulled stable branch and prepared it with:
```bash
prepare stable
```

And it works, thanks @ccutrer
