### ISSUE TITLE
Not able to access membership

### ISSUE THREAD

**Issue by stephaniegiang** [instructure/canvas-lms#1497]
Hello 👋 I'm from GitHub Education and I have been working on LTI integration with GitHub Classroom. 

A lot of our users were able to connect to Canvas and import their roster. However, suddenly a lot of our users are facing membership issues when importing. The common thing between these users are that they are using Canvas hosted on Instructure. I was just curious if something has changed since about a few days ago.

Thanks!

**Comment by derigible** [comment]
Hi @stephaniegiang - it looks like your tool is using LTI 1.1, which does not have an integration for rostering like LTI 1.3 does. We would encourage you to upgrade to LTI 1.3 at your earliest convenience to take advantage of the integrations created for tools like Github Classroom.

That being said, what mechanism does Github Classroom use to import membership data? Is it an api call, a data report that is used to ingest sis information, something else?

**Comment by westonkd** [comment]
@stephaniegiang Do you know if the API that is being used to retrieve enrollment information has a route that looks like this `courses/:course_id/membership_service` ? Just want to confirm that's the service that is having issues.

**Comment by westonkd** [comment]
If that is the correct service, have you been able to narrow down any sympotoms that are causing the issues in the LTI integration? (500s when you are making requests, incorrect or incomplete enrollment information in the response, etc) Thanks!

**Comment by stephaniegiang** [comment]
We currently use `ims-lti` gem to handle everything. 

To answer your first question, I don't have the answer for that just yet as I wasn't able to reproduce this issue. We don't have an account on Instructure and have our own spin-off of Canvas. I'm going to add some more logging to hopefully I'll have some more information for you 😄 

We have tested with our own spin up with the latest Canvas on AWS and was able to import the roster.

**Comment by tierra** [comment]
You might be able to reproduce the issue using our Free For Teacher hosted Canvas instance, where you should be able to configure your GitHub Classroom LTI tool as a course-level LTI app:

https://www.instructure.com/canvas/login/free-for-teacher

**Comment by stephaniegiang** [comment]
I tried using the free account, however I'm not able to turn on the Membership service configuration needed for GitHub Classroom.

**Comment by westonkd** [comment]
The membership service config lives behind a feature flag and I don't think we want to turn that on for the Free for Teacher account.

Thanks for the further details above! A couple more things that would be helpful as we try to figure out what's going on:

- ims-lti gem vesrion
- the class/method being used from the ims-lti gem to access the canvas Membership service

Once you have more logging in place it will also be good to see the Membership service responses you are getting from Canvas (So we can see if the issue is incorrect formatting or missing data). 

Thanks!

**Comment by stephaniegiang** [comment]
Hello 👋 I was able to grab some more data to share! 

`courses/:course_id/membership_service` is the route we are hitting. So everything looks good! 

The `ims-lti` version we are using is 2.2.3. We are using LTI version 1.1. For the `ims-lti` we are using, we are creating the request ourselves using Faraday.

For the errors we have been experiencing, I'm going to wait another day or two to grab more data since I don't think the set I have right now tells us a lot. 

I have also tested the integration with other LMSs and didn't have an issue with importing rosters.

**Comment by westonkd** [comment]
Thanks for the additional details! Let us know once you find out the specific details of the errors you are experiencing. At that point we should be able to get to the bottom of the issue fairly quickly.

**Comment by stephaniegiang** [comment]
Is it possible to turn the flag on my free account for testing and to grab some more data on this error?

**Comment by stephaniegiang** [comment]
I was able to identify the issue. We were unable to find the membership subject within the JSON returned giving us a `JSON::ParserError`. Has the response body changed?

**Comment by stephaniegiang** [comment]
@ccutrer Ahh thanks! That is something we were not expecting from the response. We have fixed the problem 😄
