### ISSUE TITLE
Canvas LMS install in ubuntu 18.04

### ISSUE THREAD

**Issue by Fathulo** [instructure/canvas-lms#1505]
HELP ME Please!!!!!!!!!!!!!!!!!!!!!!!
I tried to install Canvas-LMS, but when installing yarn v1.10.1, I got this error:

[5/5] Building fresh packages ...
[1/15] ? node-sass
[6/15] ? uglifyjs-webpack-plugin
[7/15] ? spawn-sync
[8/15] ? fetch-mock
error / home / canvas / canvas-lms / node_modules / @ sentry / cli: Command failed.
Exit code: 1
Command: node scripts / install.js
Arguments:
Directory: / home / canvas / canvas-lms / node_modules / @ sentry / cli
Output:

I do not understand what the problem is. Please help with this, I could not understand and it has been several days.

**Comment by halyihev** [comment]
I don't see where anyone has replied to this, but I can say I've had the same problem.  I finally got past the node-sass issue by using node.js 6.11.3, yarn 1.10.1, and editing package.json to reflect those two versions.  And doing npm cache clean -f then npm uninstall node-gyp then npm reinstall node-gyp.  Also did apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
My problem now is that it errors out on webpack all the time.  I've tried everything I can find and can't seem to get past it.

**Comment by simonista** [comment]
@Fathulo : if you're still having trouble, check out the comments on https://github.com/instructure/canvas-lms/issues/1386 to see if they help!

**Comment by Kulgar** [comment]
Hello, I had the same issue today, for other people that may see this message, a too recent node version seems to be the culprit. 
I tried with node v12 and had an issue with node-sass compilation on Ubuntu 18.
Everything worked fine with latest node v10  (v10.19.0) and latest yarn v1 (1.22.4).
