### ISSUE TITLE
canlendar_events API call shows the description of assignments that are not yet available.

### ISSUE THREAD

**Issue by anagp** [instructure/canvas-lms#1506]
### Summary:
The _calendar_events API_ returns the description of Assignments that are not available.

### Steps to reproduce:

 1. Create an assignment with an unlock_at date in the future.
 2. Publish it
 3. Log in as a student.
 4. Go to calendar

### Expected behavior:
The assignment is shown and there is no possibility of accessing the description.

### Actual behavior:
The assignment is shown and in the calendar itself it is not possible to see the description but if one opens Developer Tools in the browser and navigates to the API call, the description is readable.

![calender](https://user-images.githubusercontent.com/4036235/65047242-679ee600-d962-11e9-881e-76b2598703ff.png)

**Comment by vimalloc** [comment]
Thanks for the report. This is now fixed in f09f271b5a55e9d38a6d5a9061c9e122de9be0c8. It will be going out to production in the near future. :+1:

**Comment by anagp** [comment]
Thanks for the fix! :smiley:
Is it possible to find out what release it will be in?

**Comment by vimalloc** [comment]
It will be part of the 2019-09-25 release :+1:

**Comment by anagp** [comment]
Thanks!
