### ISSUE TITLE
CSS for quizzes in SpeedGrader™, Course Wizard not loading

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#1508]
### Summary: 

CSS for both quiz grading in SpeedGrader™ and the Course Setup Checklist are not loading in self-hosted Canvas installations. This affects both the 2019-08-28 and 2019-09-11 releases. 

#### SpeedGrader issue:

 1. Stand up a self-hosted Canvas installation (docker in development mode is sufficient)
 2. As a teacher or admin, take create a course, and a quiz within the course.
 3. As a student (Student View is sufficient), take and submit the quiz.
4. As a teacher or admin, view the student's submission in SpeedGrader™

#### Course Setup Checklist issue:

 1. Stand up a self-hosted Canvas installation (docker in development mode is sufficient)
 2. As a teacher or admin, take create a course.
3. View the Course Setup Checklist.

#### SpeedGrader issue:

SpeedGrader should render properly (e.g. as on Cloud Canvas):

![Screenshot 2019-09-25 11 17 28](https://user-images.githubusercontent.com/146111/65628352-2459fe00-df86-11e9-8291-7bee211935a3.png)

#### Course Setup Checklist issue:

The Course Setup Checklist should render normally (e.g. as on Cloud Canvas):

![Screenshot 2019-09-25 11 19 35](https://user-images.githubusercontent.com/146111/65628484-5cf9d780-df86-11e9-867c-55d66d1f9551.png)

### Actual behavior:

Neither SpeedGrader or the Course Setup Checklist render properly. CSS bundles are not being included in the rendered templates.

SpeedGrader:
![Screenshot 2019-09-25 11 22 19](https://user-images.githubusercontent.com/146111/65630262-ec54ba00-df89-11e9-95b4-f370207e69ac.png)

Course Setup Checklist:
![Screenshot 2019-09-25 11 20 31](https://user-images.githubusercontent.com/146111/65628671-c7127c80-df86-11e9-8d84-bde6f41ac4a1.png)

### Additional notes:
Some preliminary research indicates that this has something to do with recent changes made to allow something called "template streaming". In f888621, for example, changes were made to several QuizzesController methods to call `render stream: can_stream_template?`. In the `history` method, which is the method responsible for rendering the left-hand iframe of SpeedGrader, there is no call to `css_bundle` as there is in other methods.

If I view source on the rendered iframe on our cloud instance (sfu.instructure.com), I can see the quizzes CSS bundle being loaded in the `<head>` of the page:

```
﻿<link rel="stylesheet" media="all" href="https://du11hjcvx0uqb.cloudfront.net/br/dist/brandable_css/new_styles_normal_contrast/bundles/quizzes-cd81e4f694.css" />
```

On a self-hosted instance, this file is not being included.

If we add `css_bundle :quizzes` after line 743 in app/controllers/quizzes/quizzes_controller.rb (after the call to `js_bundle`), SpeedGrader renders properly, and a `<link>` tag loading the quizzes CSS bundle is included in the `<head>` of the page.

I suspect the Course Setup Wizard issue is similar; on cloud, the course home page includes `<link rel="stylesheet" media="all" href="https://du11hjcvx0uqb.cloudfront.net/br/dist/brandable_css/new_styles_normal_contrast/bundles/course_wizard-811d45111c.css" />` in the head; it does not on self-hosted.

This does not appear to be related to any custom CSS or JS in our theme; I have verified this issue on a dev docker instance without those customizations.

**Comment by christopher-b** [comment]
We are experiencing the same issue. Thanks for reporting it Graham.

**Comment by ryankshaw** [comment]
looking...

**Comment by ryankshaw** [comment]
in the meantime you can turn of streaming on those endpoints with something like `Setting.set("disable_template_streaming_for_#{controller_name}/#{action_name}", "true")` (and replace `controller_name` and `action_name` with the rails controller & action of those pages.  still looking into the permanent fix though

**Comment by grahamb** [comment]
@ryankshaw that seems to have worked for quizzes ("disable_template_streaming_for_quizzes/history`) but not for the course setup checklist (disable_template_streaming_for_courses/show`)

**Comment by grahamb** [comment]
Spoke too soon; it worked on my dev environment, but not in production (unless this requires a restart).

**Comment by grahamb** [comment]
Tried on one of our non-prod environments that only has one redis server; doing `Setting.set("disable_template_streaming_for_quizzes/history", "true")` and reloading the page works there.

**Comment by grahamb** [comment]
OK - it took an app restart, but that has resolved both issues for now.

**Comment by ryankshaw** [comment]
I've got a commit that fixes the root problem in review new. should be merged on monday

**Comment by grahamb** [comment]
Awesome, thanks!
