### ISSUE TITLE
Web application not starting up

### ISSUE THREAD

**Issue by izayd2** [instructure/canvas-lms#1512]
This is the second time this has happened to me:
Error:
Web application could not be started
Error ID:
ffe7811a
Details:
Web application could not be started by the Phusion Passenger application server.

Please read the Passenger log file (search for the Error ID) to find the details of the error.

You can also get a detailed report to appear directly on this page, but for security reasons it is only provided if Phusion Passenger is run with environment set to development and/or with the friendly error pages option set to on.

For more information about configuring environment and friendly error pages, see:

Nginx integration mode
Apache integration mode
Standalone mode

Is there anything I should look into?

**Comment by izayd2** [comment]
I'm using Bitnami on Azure

**Comment by simonista** [comment]
Hi @izayd2, sorry to be slow getting back to you. I don't really have enough to go on here, unfortunately. We usually use Github for application level bugs, so if you're still having trouble I'd look at the archives or reach out on our google group (https://groups.google.com/forum/#!forum/canvas-lms-users) or on IRC (#canvas-lms on Freenode). You might have better luck finding someone else who has struggled with something similar there.

**Comment by AirFusion45** [comment]
got this error on ubuntu 20.04 LTS (not on bitnami). for those with the same error, check your apache logs in /var/log/apache2/error.log - it will point you to what went wrong.

for me (i followed a mix of [this guide](https://www.linode.com/docs/guides/install-canvas-lms-on-ubuntu-2004/#delighted) and the production guide in the wiki in this repo) the err was 
```
You have already activated strscan 1.0.3, but your Gemfile requires strscan 3.0.6. Since strscan is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports strscan as a default gem. (Gem::LoadError)
```
to resolve: just force strscan 3.0.6 to be default (having 2 defaults doesn't affect it)
