### ISSUE TITLE
Improve error messaging in the create enrollments API

### ISSUE THREAD

**Issue by wgwz** [instructure/canvas-lms#1514]
### Summary:

When making a request to the create enrollments API, I found the error messaging not as helpful as it could be.

https://canvas.instructure.com/doc/api/enrollments.html#method.enrollments_api.create

### Actual behavior:

Send a request with some sis_user_id rather than a canvas_user_id
```
$ curl https://<canvas>/api/v1/courses/<cid>/enrollments -X POST -F "enrollment[user_id]=<some-sis-user-id>" -F "enrollment[type]=StudentEnrollment" -F "enrollment[role_id]=<some-id>" -F "enrollment[notify]=true" -H "Authorization: Bearer <redacted>"
```
Observe this error message:
```
{"errors":[{"message":"The specified resource does not exist."}]}
```

### Expected behavior:

Send a request with some sis_user_id rather than a canvas_user_id
```
$ curl https://<canvas>/api/v1/courses/<cid>/enrollments -X POST -F "enrollment[user_id]=<some-sis-user-id>" -F "enrollment[type]=StudentEnrollment" -F "enrollment[role_id]=<some-id>" -F "enrollment[notify]=true" -H "Authorization: Bearer <redacted>"
```
Observe this error message:
```
{"errors":[{"message":"User with specified canvas user id does not exist."}]}
```

### Additional notes:

It would be terrific if this was documented as well:

https://community.canvaslms.com/thread/16184-add-enrollment-via-sis-id-or-login-id-instead-of-canvas-user-id#comment-66707

**Comment by simonista** [comment]
Hey @wgwz, thanks for the report. That syntax _is_ actually documented here: https://canvas.instructure.com/doc/api/file.object_ids.html

I agree that we could do a lot better with error messages across our whole API. The current architecture doesn't lend itself super well to that, because it's exception based (see https://github.com/instructure/canvas-lms/blob/master/app/controllers/application_controller.rb#L1517). But let me think a little more if there's something simple we could do here before we get around to a more major refactor of API errors.

**Comment by wgwz** [comment]
Hey @simonista, thanks for getting back to me! Ah ha! I actually missed that documentation even though it was posted in the answer I found in the Canvas community. That does help, but I might argue it's still kind of hard to find. I do see the difficulty of the problem though, it's nice to have DRY docs as well.

I think a more findable place would be in the parameter description field of the API docs here: 
https://canvas.instructure.com/doc/api/enrollments.html#method.enrollments_api.create

enrollment[user_id] | Required | string | The ID of the user to be enrolled in the course. sis_user_id:<sis id> format applicable.
-- | -- | -- | --

Obviously this breaks DRY documentation to some degree.

I'd like to point out one other issue with the documentation here:
https://canvas.instructure.com/doc/api/file.object_ids.html

It's not immediately obvious to me that these can be applied to more than just URLs (that's the only documented example):

```The following objects support SIS IDs in the API:

    sis_account_id
    sis_course_id
    sis_group_id
    sis_group_category_id
    sis_integration_id (for users)
    sis_login_id
    sis_section_id
    sis_term_id
    sis_user_id
```

Maybe there is a notion of an "object" that I am missing but to me that is very general and I don't know what is meant.

**Comment by wgwz** [comment]
It does look like a tricky problem to solve, at least with the way the code is currently set up. Maybe you could move some instances of the exception handling a bit "closer" to the controller for this API endpoint. But this is an off-the-cuff suggestion and I'm sure it's less than ideal.
