### ISSUE TITLE
error on unbundle a gem file 

### ISSUE THREAD

**Issue by Blummer92** [instructure/canvas-lms#1517]
### Summary:
I am trying to unbundle gems with in my canvas folder 
### Steps to reproduce:

 1. 
`sudo gem install bundler -v 1.13.6`
`ERROR:  Could not find a valid gem 'bundler' (= 2.4) in any repository
ERROR:  Possible alternatives: bundler
Zacharys-MBP:canvas zachscomputer$ ~/canvas$ bundle config build.eventmachine --with-cppflags=-I/usr/local/opt/openssl/include`

 2.
then I tried 
`bundle install`
 `Your Ruby version is 2.3.7, but your Gemfile specified 2.4.0
`

### Expected behavior:
for the gem file to be bundled
### Actual behavior:
will not bundle

**Comment by simonista** [comment]
Hey @Blummer92, I think the error is there in your output, that you're trying to run on an older and unsupported ruby version (2.3.7). Try upgrading your ruby version to at least 2.4.0!
