### ISSUE TITLE
Quiz Statistics endpoint doesn't include user ids

### ISSUE THREAD

**Issue by andrew-gardener** [instructure/canvas-lms#1522]
### Summary:
The [quiz statistics endpoint](https://canvas.instructure.com/doc/api/quiz_statistics.html#method.quizzes/quiz_statistics.index) includes a `user_names` field for each answer but doesn't include the student ids (making it impossible to uniquely identify which responses were chosen by students). This seems like an oversight considering that student names are already present.

**Comment by simonista** [comment]
Hi @andrew-gardener, I agree this seems kinda strange. I don't know this part of the code very well, but looking at git history, it seems like user_ids were in an early version of quiz stats, then removed, and then user_names were added later.

I don't think it would be too hard to add user_ids back in, I think you could use the user_names commit (ff10b28e43d9972af53e74b987c82d287437d383) as an example, but just do the ruby side.

**Comment by andrew-gardener** [comment]
@simonista Please see #1534

I ran the test in `canvas_quizzes` but couldn't get the tests running for the `client_apps` statistics running (there was actually a parse error in there that I fixed so not sure if they were runnable before).

Anyways, tested out the quiz statistics api with all question types and it seems to work well for me. Please let me know if there is anything missing/needed to be changed.

Thanks
