### ISSUE TITLE
Live Event learning_outcome_result_created.mastery passes wrong value

### ISSUE THREAD

**Issue by robert-carroll** [instructure/canvas-lms#1526]
### Summary:
Canvas Data `learning_outcome_result_fact.mastery` is defined as:

> Boolean indicating whether user achieved mastery

https://portal.inshosteddata.com/docs#learning_outcome_result_fact

Live Event `learning_outcome_result_created.mastery` is passing `learning_outcome_id`
same with `learning_outcome_result_updated.mastery`

https://github.com/instructure/canvas-lms/blob/master/spec/lib/canvas/live_events_spec.rb#L1151
https://github.com/instructure/canvas-lms/blob/master/spec/lib/canvas/live_events_spec.rb#L1173

### Expected behavior:
Expecting boolean value of student mastery of the learning outcome.

### Actual behavior:
INT of learning outcome id

**Comment by simonista** [comment]
Thanks @robert-carroll :)

**Comment by westonkd** [comment]
Thanks @robert-carroll ! I have a fix in the works.

**Comment by westonkd** [comment]
Fixed by fd70765
