### ISSUE TITLE
Scroll jump in Safari

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#1528]
### Summary: 
On an assignment page with attached rubric, the scroll position will jump back to zero every ten seconds.

### Steps to reproduce:
 1. In Safari, visit an assignment detail page. Make sure the assignment has a rubric attached. 
 2. Scroll down. 
 3. Wait up to ten seconds. 

### Expected behavior:
Nothing 

### Actual behavior:
The page scrolls back to the top 

### Additional notes:
Illustrated [here](https://canvas.instructure.com/courses/800915/assignments/3912543).

**Comment by simonista** [comment]
Fixed in 7908c5fd411f81ea690d4abcf5e1c33d1cae365b
