### ISSUE TITLE
Create Course/Section Race Condition?

### ISSUE THREAD

**Issue by jack0x539** [instructure/canvas-lms#1530]
#1422 # Summary:
Creating a course, then creating a section within said course sometimes fails with the error "The specified resource does not exist.".

When informed on the error, I repeat the exact same POST to create the section and it works.

This has happened previously with custom_data values immediately after creating a user as well, but i believe that has been fixed.

### Steps to reproduce:

 1. Create a course.
 2. Immediately create a section.
 3. It sometimes errors.

### Expected behavior:
Return the created section, within the new course.

### Actual behavior:
Course is created, but the create for the section errors with "The specified resource does not exist.".

### Additional notes:
**[13/11/2019 (Wed) 11:01:38.934]**
**POST** https://canvas.ljmu.ac.uk/api/v1/accounts/1/courses
**BODY** `{"course":{"course_code":"Quality monitoring and improvement in Health and Social Care","name":"70912HMADV-201920-SUM","sis_course_id":"70912HMADV-201920-SUM","integration_id":"124626-201920-SUM","start_at":"2019-08-01T00:00:00","end_at":"2020-10-31T00:00:00","is_public":false,"open_enrollment":false,"self_enrollment":false},"offer":false,"enable_sis_reactivation":true}`
**[13/11/2019 (Wed) 11:01:40.372]**
**RESP** `{"id":43101,"name":"70912HMADV-201920-SUM","account_id":1,"uuid":"sz7PFNIMtqAR3CcJMmZbyD2IqrczyVQyDtSSTswN","start_at":"2019-07-31T23:00:00Z","grading_standard_id":null,"is_public":false,"created_at":"2019-11-13T11:01:39Z","allow_student_forum_attachments":true,"course_code":"Quality monitoring and improvement in Health and Social Care","default_view":"modules","root_account_id":1,"enrollment_term_id":1,"open_enrollment":false,"allow_wiki_comments":null,"self_enrollment":false,"license":null,"restrict_enrollments_to_course_dates":false,"grade_passback_setting":null,"end_at":"2020-10-31T00:00:00Z","public_syllabus":false,"public_syllabus_to_auth":false,"storage_quota_mb":3000,"is_public_to_auth_users":false,"hide_final_grades":false,"apply_assignment_group_weights":false,"calendar":{"ics":"https://canvas.ljmu.ac.uk/feeds/calendars/course_sz7PFNIMtqAR3CcJMmZbyD2IqrczyVQyDtSSTswN.ics"},"time_zone":"Europe/London","blueprint":false,"sis_course_id":"70912HMADV-201920-SUM","sis_import_id":null,"integration_id":"124626-201920-SUM","workflow_state":"unpublished"}`

**[13/11/2019 (Wed) 11:01:40.372]** 
**POST** https://canvas.ljmu.ac.uk/api/v1/courses/43101/sections
**BODY** `{"course_section":{"name":"70912HMADV-201920-SUM","sis_section_id":"DESSECTION:70912HMADV-201920-SUM","integration_id":"DESSECTION:70912HMADV-201920-SUM_INT"}}`
**[13/11/2019 (Wed) 11:01:40.465]**
**RESP** `{"errors":[{"message":"The specified resource does not exist."}]}`

**Comment by simonista** [comment]
Hey @jack0x539, my guess as to what is happening here is that the second requests tries to look up the course context from the read replica database (to reduce load on the main database). You can see that happening here: https://github.com/instructure/canvas-lms/blob/master/app/controllers/application_controller.rb#L779

This replication is usually only a few milliseconds behind, but can sometimes get a second or two behind when things are especially busy. I think for us, this is an acceptable tradeoff to keep load away from the main DB, so handling the retry as you are is probably what you'll need to keep doing. Thanks for letting us know though!

**Comment by jack0x539** [comment]
@simonista Cheers, I've implemented retry at our end!
