### ISSUE TITLE
[Bug] Dockerfile for postgres missing /wait-for-it.sh

### ISSUE THREAD

**Issue by danielblignaut** [instructure/canvas-lms#1531]
### Summary:
When installing manually via Docker, following the instructions as set out here: https://github.com/instructure/canvas-lms/blob/master/doc/docker/developing_with_docker.md

this command fails: ```docker-compose run --rm web bundle install```

The reason for failure is: ```ERROR: Service 'postgres' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder778018731/wait-for-it: no such file or directory```

After briefly reviewing the git history, it seems ```COPY /wait-for-it /``` was recently added to ```docker-compose/postgres/Dockerfile```.

I fixed the issue by copying ```build/docker-compose/postgres/9.5/wait-for-it.sh``` into ```/docker-compose/postgres/wait-for-it.sh```

### Steps to reproduce:

 1.``` git clone https://github.com/instructure/canvas-lms```
 2. ```echo "COMPOSE_FILE=docker-compose.yml:docker-compose.override.yml:docker-compose.local.`whoami`.yml" >> .env```
 3. ```echo "version: '2'" > docker-compose.local.`whoami`.yml```
4. ```cp -R docker-compose/config/ config/```
5. ```docker-compose run --rm web bundle install```

### Expected behavior:

Build the container as specified in the postgres Dockerfile

### Actual behavior:

```ERROR: Service 'postgres' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder778018731/wait-for-it: no such file or directory```

**Comment by jbutte** [comment]
Looking into this. Seems we left out a file.

**Comment by jbutte** [comment]
fixed in a05b932c34
