### ISSUE TITLE
Bug in (or documentation error for) Assignments REST API.

### ISSUE THREAD

**Issue by fredrikekre** [instructure/canvas-lms#1539]
### Summary:
 - `Assignment.integration_data` returns `"object"` instead of (as documented) a `"string"`: https://github.com/instructure/canvas-lms/blob/eaa9fd10071711f9db248ed08c0bee33297fa3e6/app/controllers/assignments_api_controller.rb#L417-L421
 - `Assignment.possible_points` returns `"number"` instead of (as documented an `"integer"`: https://github.com/instructure/canvas-lms/blob/eaa9fd10071711f9db248ed08c0bee33297fa3e6/app/controllers/assignments_api_controller.rb#L426-L430

### Steps to reproduce:

```
curl -H "Authorization: Bearer ${CANVAS_TOKEN}" ${CANVAS_URL}/api/v1/courses/:course_id/assignments/:assignment_id
```
returns
```
{...,"points_possible":3.0,...,"integration_data":{},...}
```

### Additional notes:

If this is just an error in the docs I can submit a PR, but would be good if someone could confirm whether this is a mistake in the docs or the implementation.

**Comment by simonista** [comment]
Hi @fredrikekre, thanks for the issue, both appear to be issues with the documentation.
