### ISSUE TITLE
SpeedGrader launches LTI apps with the wrong consumer key and secret

### ISSUE THREAD

**Issue by seanh** [instructure/canvas-lms#1545]
# Summary:

To reproduce this you need an LTI app that submits launch URLs as assignment outcomes, using [Canvas's Result Data LTI extension](https://canvas.instructure.com/doc/api/file.assignment_tools.html). For example, you can use the [Hypothesis LTI app](https://web.hypothes.is/help/installing-the-lms-app-for-canvas-course-level/) to reproduce this issue.

If more than one instance of the same LTI app is installed within a single Canvas instance (same domain/launch URL but different consumer key and secret) then SpeedGrader will sometimes launch a submission created by LTI app instance A with the consumer key and secret of instance B.

### Steps to reproduce:

1. Add a first instance of a given external app to a course, using consumer key XXX
2. Add a second instance of the same app to the course, using consumer key YYY
3. Create an assignment in the course using _External tool_ as the submission type, and selecting the first (XXX) app instance as the external tool
4. Launch the assignment as a learner and submit the assignment. The LTI app submits a launch URL to Canvas
5. As an instructor launch the assignment in SpeedGrader and navigate to the student. Canvas launches the LTI app using the launch URL that was submitted in step 4 above

### Expected behavior:

SpeedGrader should launch LTI apps using the same consumer key and secret that were used to submit the launch URL.

### Actual behavior:

SpeedGrader launches the LTI app with consumer key YYY and the corresponding secret, but the assignment and submission belong to consumer key XXX

### Additional notes:

This causes all sorts of unexpected behaviors when our app is launched by SpeedGrader. To give just one example:

* Let's say that the user who created application instance XXX also registered a Canvas API developer key and secret with us so that our app can use the Canvas API on their behalf. We save that API key and secret alongside consumer key XXX in our database.
* The user who created app instance YYY did not give us a developer key: API-based features aren't enabled for YYY
* And let's say that the assignment in question needs to use the Canvas API when launched in SpeedGrader (e.g. to download a file from Canvas).
* Since SpeedGrader launches XXX's assignment with consumer key YYY rather than XXX, we cannot retrieve XXX's developer key and secret in order to use the Canvas API when we're launched by SpeedGrader. Our app receives no indication that the LTI launch belongs to consumer key XXX (in fact the signed launch params contain YYY)

**Comment by seanh** [comment]
@westonkd Are you planning to fix this? Wondering whether it's worth my time implementing a workaround for it in our LTI app. If it's going to be fixed in Canvas anyway, I might just wait for that fix

**Comment by westonkd** [comment]
@seanh :wave: Thanks for bringing the issue up! This is behavior that we are aware of, but I'm chatting with a few folks to see what kind of changes we could potentially make. The challenge for us is making sure we keep the way Canvas does "tool lookups" in line with what the IMS specification outlines.

I'll keep you posted on the conversation we are having, thanks!

**Comment by seanh** [comment]
Thanks! Much appreciated

**Comment by westonkd** [comment]
@seanh Just wanted to give you an update: We are still having some discussions about what changes we can make here. LTI 1.3 is potentially changing the way Canvas does "tool lookups," so we are waiting for that to settle a bit.

In the past, we have not heard much of a request from tool providers to support multiples of the same tool being installed in the same context (course or account). Having multiples of the same tool is what leads to the behavior you saw.

It sounds like you have a use-case for your tool being installed multiple times in the same context. Can you share what that use-case is? I'll pass along the info to our team's product manager, who is helping make the decision.

Thanks again!

**Comment by seanh** [comment]
Hi,

I think there are two use-cases that're causing us to run into this:

1. Our own test/QA Canvas instance has multiple installations of our app for convenient testing. We have an installation with a developer key and secret; one without a key and secret; installations with different corresponding configurations in our DB; one with an incorrect LTI shared secret; etc etc. We just give each instance a different name. It's convenient for testing different circumstances.

2. Our actual users sometimes create multiple installations, for various reasons, even though we don't actively encourage it. For example they might create an instance without a developer key and secret and then, when they realise they want the API-based features, they register and install a _new_ instance this time with a key and secret, and don't delete the old one. Or they create one broken installation somehow (e.g. they pasted in the consumer key incorrectly) so they just do another installation from the start, and don't delete the original one. Etc.

   We don't encourage it but it's a thing that seems to happen for various reasons and it's undesirable for us to have to insist that our users make sure they never have two installations and always clean up their old installations, or to often have to ask users who're having problems to check that they don't have multiple installations. Especially since the SpeedGrader problems that can be caused by multiple instances can vary quite widely and can be pretty confusing.

Thanks for considering it!

**Comment by westonkd** [comment]
Hey @seanh,

Thanks again for these use-cases! I was able to chat with the team about it, here are our thoughts:

**Use-case 1** 
During the development of an LTI tool, we recommend not installing duplicates within the same context. Instead, LTI tool providers typically install them in separate sub-accounts (or even courses) to keep them isolated. This is actually what our team does when we are building LTI tools.

**Use-case 2**
This is a good point that we've been thinking about for a while now too. Currently in Canvas, if a user attempts to install a duplicate tool in a context, a warning modal is presented to them. This warning allows them to proceed with the installation, or cancel the installation.

One change we've been considering is having a third, default action available in that warning modal: "Replace existing tool." We feel like this would help to reduce the number of accidental duplicate installations.

It's unlikely that we will make changes to support duplicate tools in the same context in the near future. While it would not technically break our LTI specification compliance, it would add a new layer of canvas-specific behavior for tool providers to worry about (which we typically avoid when possible).

Any thoughts? Thanks!

**Comment by westonkd** [comment]
Closing for now. Let us know if you have any thoughts on those two use cases.
