### ISSUE TITLE
Error thrown by webpack when running docker-compose run web

### ISSUE THREAD

**Issue by jojo787898** [instructure/canvas-lms#1557]
### Summary:
An error was thrown by webpack when running docker-compose run web:
Service 'web' failed to build: The command '/bin/sh -c COMPILE_ASSETS_NPM_INSTALL=0 bundle exec rake canvas:compile_assets' returned a non-zero code: 1

### Steps to reproduce:
 1. ./scripts/docker_dev_setup.sh
 2. docker-compose run --rm web bundle install

### Expected behavior:
Docker build succeeds

### Actual behavior:
Service 'web' failed to build.

internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at Object.fork (child_process.js:113:10)
    at fork (/usr/src/app/node_modules/worker-farm/lib/fork.js:17:36)
    at Farm.startChild (/usr/src/app/node_modules/worker-farm/lib/farm.js:107:16)
    at Farm.processQueue (/usr/src/app/node_modules/worker-farm/lib/farm.js:288:10)
    at Farm.<anonymous> (/usr/src/app/node_modules/worker-farm/lib/farm.js:98:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
--> Finished: 'js:webpack_development' in 68.84302558299999
rake aborted!
Parallel::UndumpableException: RuntimeError: Error running js:webpack_production: 
ABORTING
/usr/src/app/lib/tasks/js.rake:50:in `block (2 levels) in <top (required)>'
/usr/src/app/lib/tasks/canvas.rake:76:in `block (5 levels) in <top (required)>'
/usr/src/app/lib/tasks/canvas.rake:7:in `log_time'
/usr/src/app/lib/tasks/canvas.rake:76:in `block (4 levels) in <top (required)>'
/home/docker/.gem/ruby/2.4.0/gems/parallel-1.18.0/lib/parallel.rb:506:in `call_with_index'
/home/docker/.gem/ruby/2.4.0/gems/parallel-1.18.0/lib/parallel.rb:360:in `block (2 levels) in work_in_threads'
/home/docker/.gem/ruby/2.4.0/gems/parallel-1.18.0/lib/parallel.rb:515:in `with_instrumentation'
/home/docker/.gem/ruby/2.4.0/gems/parallel-1.18.0/lib/parallel.rb:359:in `block in work_in_threads'
/home/docker/.gem/ruby/2.4.0/gems/parallel-1.18.0/lib/parallel.rb:209:in `block (3 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
ERROR: Service 'web' failed to build: The command '/bin/sh -c COMPILE_ASSETS_NPM_INSTALL=0 bundle exec rake canvas:compile_assets' returned a non-zero code: 1

**Comment by maths22** [comment]
The `spawn ENOMEM` makes me think your docker VM/computer doesn't have enough RAM available. Do you have at least 8GB of RAM?  Unfortunately the production image requires a substantial amount of memory to build, so that's the most likely culprit.

**Comment by jojo787898** [comment]
Thank you, that was indeed the problem. I only have 8 GB of ram and created a VM with 4GB RAM instead when asked in docker_dev_setup.sh. I was able to work around this by reducing the max_old_space_size flag value in the webpack tasks in package.json.
