### ISSUE TITLE
'Reset Multi-Factor Authentication' feature doesn't work

### ISSUE THREAD

**Issue by SofiaSousa** [instructure/canvas-lms#1558]
### Summary:
Admin can't reset users' multi-factor authentication. I think the same happens if users try to reset their own multi-factor authentication.

### Steps to reproduce:

 1. Login as admin
 2. Select the correct account on the Admin side menu
 3. Go to People tab and select the user that has multi-factor authentication
 4. Click 'Reset Multi-Factor Authentication'

### Expected behavior:
Resets the user multi-factor authentication and reload the page

### Actual behavior:
Redirects to 'Page not Found'

### Additional notes:
As we can see here https://github.com/instructure/canvas-lms/blob/ebbd9ebd6375d87d71020739d557c920ed4919b8/config/routes.rb#L800 this route expects a DELETE HTTP request, but when we click 'Reset Multi-Factor Authentication' link, it executes a GET (and there is no 'users/:user_id/mfa' route set for GET).

**Comment by simonista** [comment]
Hi @SofiaSousa, thanks for the report. This sounds very familiar to me, I think we may have fixed this once before (which if true, would be extra sad if it then broke again!) Let me go poke around a bit and look.

**Comment by simonista** [comment]
Okay, yes, c68ad8f93088d1c325b816a623656ea4731c47eb is what I was thinking of. Specifically, the link is supposed to get caught by javascript here: https://github.com/instructure/canvas-lms/blob/master/public/javascripts/user_logins.js#L216. Let me see if I can get things running and figure out why that wouldn't be working.

**Comment by SofiaSousa** [comment]
Oh, I didn't see the javascript assigned to the link. I'm realizing now that I have an old version of canvas-lms (release/2018-02-17.08) where the `event.preventDefault()` is after the ajax call (the fix was done after that).

Anyway, thanks for your time @simonista.
