### ISSUE TITLE
ModuleItem/LockInfo/CreateModule field conflict

### ISSUE THREAD

**Issue by RailRunner166** [instructure/canvas-lms#1568]
### Summary:
When I navigate to the self hosted canvas instance's website it takes forever to load and eventually loads an error page. when I check my logs, I find this:
```
App 13705 output: ModuleItem's `field :module` conflicts with a built-in method, use `resolver_method:` to pick a different resolver method for this field (for example, `resolver_method: :resolve_module` and `def resolve_module`)
App 13705 output: 
App 13705 output: ModuleItem's `field :next` conflicts with a built-in method, use `resolver_method:` to pick a different resolver method for this field (for example, `resolver_method: :resolve_next` and `def resolve_next`)
App 13705 output: 
App 13705 output: LockInfo's `field :module` conflicts with a built-in method, use `resolver_method:` to pick a different resolver method for this field (for example, `resolver_method: :resolve_module` and `def resolve_module`)
App 13705 output: 
App 13705 output: CreateModule's `field :module` conflicts with a built-in method, use `resolver_method:` to pick a different resolver method for this field (for example, `resolver_method: :resolve_module` and `def resolve_module`)
App 13705 output: 
App 13705 output: CreateModulePayload's `field :module` conflicts with a built-in method, use `resolver_method:` to pick a different resolver method for this field (for example, `resolver_method: :resolve_module` and `def resolve_module`)
App 13705 output: 
[ E 2020-01-27 01:13:21.3475 13630/Tc age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/canvas: A timeout occurred while starting a preloader process.
```

### Steps to reproduce:

 1. Use the Canvas Production install guide in the wiki on Ubuntu 18.04 LTS (server)

### Expected behavior:
It should load the page and run canvas fine

### Actual behavior:
It takes forever to load and eventually fails

### Additional notes:
I did mess up the users and databases in postgres, but eventually reset the database and fixed those issues

**Comment by simonista** [comment]
Hey @RailRunner166, thanks for the report, I've never seen that before.  What version of Ruby are you using?

**Comment by RailRunner166** [comment]
well, @simonista, I'm pretty sure its like 2.x something but let me check. Thanks for the quick response!

**Comment by RailRunner166** [comment]
My ruby version is
```
ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-linux-gnu]
```

**Comment by RailRunner166** [comment]
whoops, didn't mean to close this lol

**Comment by danielnewell** [comment]
@simonista Related to this, (I'm working on Rail with this), I noticed a problem that Fixnum is deprecated. Can we remove deprecated deps?

**Comment by simonista** [comment]
@RailRunner166: I don't know what would cause that output, you might have better luck posting in our [google group](https://groups.google.com/forum/#!forum/canvas-lms-users), or IRC, where others in the community that also use nginx might be able to help. It feels like an issue with the nginx setup to me, and the graphql type output seems unrelated, but I could be wrong.

@danielnewell: Yes, we're always up for fixing deprecation warnings, the one's I'm aware of (re: Fixnum) are in https://rubygems.org/gems/soap4r-ruby1.9 which I doubt will be upgraded, so we need to decide whether to remove that dependency or fork and take over maintenance, and it hasn't been a priority.

**Comment by RailRunner166** [comment]
@simonista thanks for the input, I will head over to IRC and post there. this does not use nginx though. we're using the same setup as in the production start guide (apache).

**Comment by simonista** [comment]
Oops, sorry, I misread my quick google results.

**Comment by RailRunner166** [comment]
no worries :) taking it to IRC later today

**Comment by RailRunner166** [comment]
@simonista is it #canvas-lms on Freenode? I'm not sure because I've never used IRC before and i seem to be able to change the channel settings... That doesn't seem right to me.

**Comment by RailRunner166** [comment]
oh, never mind, I see u there :)

**Comment by simonista** [comment]
Hey @RailRunner166 , I'm going to close this since IRC seems to have been a better avenue for working through this. Feel free to comment back on what actually solved it, in case it's helpful for someone else in the future, if you have time.
