### ISSUE TITLE
Canvas not scaling correctly on Firefox

### ISSUE THREAD

**Issue by RossComputerGuy** [instructure/canvas-lms#1589]
### Summary:

Class page is not scaling correctly, I didn't zoom and Firefox has default scaling.

### Steps to reproduce:

 1. Open Firefox
 2. Go to Canvas
 3. Open a class

### Expected behavior:

The whitespace on the right should be used up

### Actual behavior:

There's whitespace on the right

### Additional notes:

Screenshot (**censored for privacy**):
![canvas](https://user-images.githubusercontent.com/19699320/76561084-d23b6500-645f-11ea-9b0d-0ac3003ceb42.png)

**Comment by Ardena** [comment]
I'm not seeing the same behavior in my sandbox instance of Canvas in Firefox: https://screencast.com/t/aEdPHMN4fS

But it also looks like you have some other differences to what my page looks like.  Is this an open-source install?  Also, do you have custom javascript or CSS on the page?  You can try adding "?global_includes=0" to your URL to temporarily remove the custom js and css on the page to see if that helps.

**Comment by RossComputerGuy** [comment]
This is an install my school is running.

**Comment by Ardena** [comment]
Without more detail there's not a lot I can look at, but your school may have something custom set up that is causing this.  Have you contacted Canvas support through the help menu?  That will either go to your school admins to have them check anything custom, or go to our Canvas support team with more information than can be given over Github.

**Comment by RossComputerGuy** [comment]
It's under .instructure.com so I don't know what the setup is like.

-------- Original Message --------

**Comment by Ardena** [comment]
Since it is under .instructure.com, you should contact Canvas support through the help menu.  Your admins or our support team will have the appropriate detail to troubleshoot this that I do not have from Github.
