### ISSUE TITLE
I can't install with Automated Setup

### ISSUE THREAD

**Issue by hygjob** [instructure/canvas-lms#1595]
### Summary:
can't install 
### Steps to reproduce:

 1. In Quick start I did Automated Setup
./script/docker_dev_setup.sh
my enviroment - ubuntu 18.04 LTS
### Expected behavior:
install complete 
### Actual behavior:
Step 1/2 : FROM busybox:latest
ERROR: Service 'githook_installer' failed to build: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by hygjob** [comment]
It's systemd-resolved problem. I solve it. Thank you.

**Comment by kulemantu** [comment]
Problem solution that worked for me: 
https://github.com/instructure/canvas-lms/issues/1396#issuecomment-448010774
