### ISSUE TITLE
Inherited Tab is blank in Developer key

### ISSUE THREAD

**Issue by narendraqa** [instructure/canvas-lms#1597]
### Summary:
I am trying to enable Canvas Data Services/Canvas data Portal in Open source canvas LMS as per canvas document but the Inherited tab is blank. 
### Steps to reproduce:

 1. Click on Admin --> SiteName --> Developer Key ---> Inherited Tab

### Additional notes:
Please find reference snapshot.
![image](https://user-images.githubusercontent.com/30430627/78156909-043b5800-745d-11ea-8f1b-f8ce47d3bd48.png)

**Comment by grahamb** [comment]
That's expected; Inherited Developer Keys are part of hosted Canvas; they basically have certain developer keys at the root account and they can be inherited by individual customer accounts.

Canvas Data is not available to open-source Canvas.

**Comment by Wandimi** [comment]
Sure got the same error and this is what they said
"Hi Wandimi,
Thank you for your recent communication with our team.
I understand you are looking to integrate Microsoft applications with Canvas LMS through LTI apps.
At this stage, the self-hosted system only allows limited administrative features.
If you were looking to add this feature, we would need to have a discussion regarding the adoption of a premium Canvas subscription.
Please see a PDF below, which highlights the differences between the free vs the paid versions.
Please let me know, should you wish to explore a premium Canvas platform, and I'd be happy to ask you some questions about your use case to understand if it would be the right fit for you."
