### ISSUE TITLE
Help required after installation with Docker

### ISSUE THREAD

**Issue by anwarbashir** [instructure/canvas-lms#1609]
I am trying to install canvas-lms using the instructions provided under the doc/docker section. I have 4core 32Gb Ram virtual server running Debian9/Stretch. I run the ./script/docker_dev_setup.sh. This seems to have completed successfully, but then I needed to:-

**$bundle install** 

I am now getting the following, not sure from checking the log files why it fails

_An error occurred while installing pg (1.2.2), and Bundler cannot
continue.
Make sure that `gem install pg -v '1.2.2' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  canvas_partman was resolved to 2.0.0, which depends on
    pg_

But when I run gem 

**$install pg -v '1.2.2' --source 'https://rubygems.org/'** 

I get:

_Building native extensions. This could take a while...
ERROR:  Error installing pg:
        ERROR: Failed to build gem native extension.

    current directory: /home/anwarbashir/.rvm/gems/ruby-2.4.0/gems/pg-1.2.2/ext
/home/anwarbashir/.rvm/rubies/ruby-2.4.0/bin/ruby -I /home/anwarbashir/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0 -r ./siteconf20200421-2101-1odjjq2.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/anwarbashir/.rvm/rubies/ruby-2.4.0/bin/$(RUBY_BASE_NAME)
        --with-pg
        --without-pg
        --enable-windows-cross
        --disable-windows-cross
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/anwarbashir/.rvm/gems/ruby-2.4.0/extensions/x86_64-linux/2.4.0/pg-1.2.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/anwarbashir/.rvm/gems/ruby-2.4.0/gems/pg-1.2.2 for inspection.
Results logged to /home/anwarbashir/.rvm/gems/ruby-2.4.0/extensions/x86_64-linux/2.4.0/pg-1.2.2/gem_make.out_

Can anyone suggest a way forward - thanks.

**Comment by Ardena** [comment]
It looks like you ran the docker set up, but then did bundle install outside of docker?  If you need to do a bundle install for docker only, try docker-compose run --rm web bundle install.

**Comment by anwarbashir** [comment]
Hi Ardena,

Thank you, I re-ran the installation

/canvas-lms$ ./script/docker_dev_setup.sh

this time I did not get the message to install bundler, however when I ran

/canvas-lms$docker-compose up  # I got into a never ending cycle so I aborted and tried

/canvas-lms$docker-compose run --rm web bundle install #as per your comment, this appear to work so tried again

/canvas-lms$docker-compose up #i stll get into this nerver ending loop

jobs_1               |  from /home/docker/.gem/ruby/2.4.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
jobs_1               |  from /home/docker/.gem/ruby/2.4.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
jobs_1               |  from /home/docker/.gem/ruby/2.4.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
jobs_1               |  from /home/docker/.gem/ruby/2.4.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
jobs_1               |  from /home/docker/.gem/ruby/2.4.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
jobs_1               |  from /home/docker/.gem/ruby/2.4.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
jobs_1               |  from /home/docker/.gem/ruby/2.4.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
jobs_1               |  from /home/docker/.gem/ruby/2.4.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
jobs_1               |  from /home/docker/.gem/ruby/2.4.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
jobs_1               |  from /home/docker/.gem/ruby/2.4.0/bin/bundle:23:in `load'
jobs_1               |  from /home/docker/.gem/ruby/2.4.0/bin/bundle:23:in `<main>'

Any idea's?

**Comment by anwarbashir** [comment]
I have decided to abandon this and try and install using quick installation instructions.
