### ISSUE TITLE
LTI Key issue: Public JWK URL doesn't work

### ISSUE THREAD

**Issue by dmitry-viskov** [instructure/canvas-lms#1613]
I have no experience with Ruby but looks like the issue is in this block:

https://github.com/instructure/canvas-lms/blob/master/lib/canvas/oauth/client_credentials_provider.rb#L86

```
    def get_jwk_from_url(jwt = nil)
      pub_jwk_from_url = HTTParty.get(key.public_jwk_url)
      JSON::JWT.decode(jwt, JSON::JWK::Set.new(pub_jwk_from_url.parsed_response))
    rescue JSON::JWT::Exception => e
      errors << e
      raise JSON::JWS::VerificationFailed
    end
```

Key works correctly in case if it is set as **Public JWK**:
```
{
    "e": "AQAB",
    "n": "uvEnCaUOy1l9gk3wjW3Pib1dBc5g92-6rhvZZOsN1a77fdOqKsrjWG1lDu8kq2nL-wbAzR3DdEPVw_1WUwtr_Q1d5m-7S4ciXT63pENs1EPwWmeN33O0zkGx8I7vdiOTSVoywEyUZe6UyS-ujLfsRc2ImeLP5OHxpE1yULEDSiMLtSvgzEaMvf2AkVq5EL5nLYDWXZWXUnpiT_f7iK47Mp2iQd4KYYG7YZ7lMMPCMBuhej7SOtZQ2FwaBjvZiXDZ172sQYBCiBAmOR3ofTL6aD2-HUxYztVIPCkhyO84mQ7W4BFsOnKW4WRfEySHXd2hZkFMgcFNXY3dA6de519qlcrL0YYx8ZHpzNt0foEzUsgJd8uJMUVvzPZgExwcyIbv5jWYBg0ILgULo7ve7VXG5lMwasW_ch2zKp7tTILnDJwITMjF71h4fn4dMTun_7MWEtSl_iFiALnIL_4_YY717cr4rmcG1424LyxJGRD9L9WjO8etAbPkiRFJUd5fmfqjHkO6fPxyWsMUAu8bfYdVRH7qN_erfGHmykmVGgH8AfK9GLT_cjN4GHA29bK9jMed6SWdrkygbQmlnsCAHrw0RA-QE0t617h3uTrSEr5vkbLz-KThVEBfH84qsweqcac_unKIZ0e2iRuyVnG4cbq8HUdio8gJ62D3wZ0UvVgr4a0",
    "alg": "RS256",
    "kid": "NtQYzsKs_TWLQ0p3bLmfM7fOwY0nEBVVH3z3Q-zJ06Y",
    "kty": "RSA",
    "use": "sig"
}
```

But in case of using **Public JWK URL** we always get `JSON::JWK::Set::KidNotFound` Exception. And as a consequence:
```
HTTP response [http://canvas.test/login/oauth2/token]: 400 - {"error":"invalid_request","error_description":"JWS signature invalid."}
```

The response from JWK URL:
```
{
   "keys":[
      {
         "e":"AQAB",
         "kid":"NtQYzsKs_TWLQ0p3bLmfM7fOwY0nEBVVH3z3Q-zJ06Y",
         "kty":"RSA",
         "n":"uvEnCaUOy1l9gk3wjW3Pib1dBc5g92-6rhvZZOsN1a77fdOqKsrjWG1lDu8kq2nL-wbAzR3DdEPVw_1WUwtr_Q1d5m-7S4ciXT63pENs1EPwWmeN33O0zkGx8I7vdiOTSVoywEyUZe6UyS-ujLfsRc2ImeLP5OHxpE1yULEDSiMLtSvgzEaMvf2AkVq5EL5nLYDWXZWXUnpiT_f7iK47Mp2iQd4KYYG7YZ7lMMPCMBuhej7SOtZQ2FwaBjvZiXDZ172sQYBCiBAmOR3ofTL6aD2-HUxYztVIPCkhyO84mQ7W4BFsOnKW4WRfEySHXd2hZkFMgcFNXY3dA6de519qlcrL0YYx8ZHpzNt0foEzUsgJd8uJMUVvzPZgExwcyIbv5jWYBg0ILgULo7ve7VXG5lMwasW_ch2zKp7tTILnDJwITMjF71h4fn4dMTun_7MWEtSl_iFiALnIL_4_YY717cr4rmcG1424LyxJGRD9L9WjO8etAbPkiRFJUd5fmfqjHkO6fPxyWsMUAu8bfYdVRH7qN_erfGHmykmVGgH8AfK9GLT_cjN4GHA29bK9jMed6SWdrkygbQmlnsCAHrw0RA-QE0t617h3uTrSEr5vkbLz-KThVEBfH84qsweqcac_unKIZ0e2iRuyVnG4cbq8HUdio8gJ62D3wZ0UvVgr4a0",
         "alg":"RS256",
         "use":"sig"
      }
   ]
}
```

**Comment by westonkd** [comment]
:wave: Hi @dmitry-viskov!

Thank you for posting this issue! We do have several LTI Advantage tools in production that successfully retrieve access tokens, so I wonder if there may be an issue in the `client_assertion` parameter your tool sends to the the Canvas `/login/oauth2/token` endpoint.

Can you confirm that the `kid` header in the `client_assertion` JWT your tool sends exactly matches the `kid` in your public JWKs endpoint?

Here is an example of a public JWKs endpoint that is currently working for a tool we having running in production Canvas: https://8axpcl50e4.execute-api.us-east-1.amazonaws.com/main/jwks

**Comment by dmitry-viskov** [comment]
Thanks @westonkd ! You a right - I missed `kid` in the jwt headers. My mistake.
In this case looks odd that **Public JWK** (not URL) somehow works without this check?

```
    def decoded_jwt(jwt = nil)
      @decoded_jwt ||= if key.public_jwk_url.present?
          get_jwk_from_url(jwt)
        else
          JSON::JWT.decode(jwt, JSON::JWK.new(key.public_jwk), :RS256)
        end
    rescue JSON::JWS::VerificationFailed, JSON::JWS::UnexpectedAlgorithm
      @invalid_key = true
    end
```
 Th

**Comment by westonkd** [comment]
Great!

Yes, a hard-coded JWK will always work (assuming the key pair has been generated correctly). This is because the tool is providing a single key to Canvas, so Canvas knows exactly what key to use for verification.

When a JWKs URL is proved, the tool is actually giving an array of possible public keys to Canvas. Canvas uses the kid to find the correct public key to verify the client assertion.

This is the case even when the JWKs URL contains an array with only a single key (like in the example you shared).

**Comment by dmitry-viskov** [comment]
got it. thanks for explanation @westonkd !

**Comment by westonkd** [comment]
No problem!
