### ISSUE TITLE
Linking to external JS

### ISSUE THREAD

**Issue by ismaelrumzan** [instructure/canvas-lms#1615]
### Summary:
I'm trying to add live chat from helpscout in our instance which 2 JS scripts
### Steps to reproduce:
The code should be inserted in the body of the html. I'm not sure where to do that.
I could not do it in the upload of the theme editor as this only allows for pure JS code
Something like this (I replaced the id with "myid")

<script type="text/javascript">!function(e,t,n){function a(){var e=t.getElementsByTagName("script")[0],n=t.createElement("script");n.type="text/javascript",n.async=!0,n.src="https://beacon-v2.helpscout.net",e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],"complete"===t.readyState)return a();e.attachEvent?e.attachEvent("onload",a):e.addEventListener("load",a,!1)}(window,document,window.Beacon||function(){});</script>
<script type="text/javascript">window.Beacon('init', 'myid')</script>

Is there a template file in the back-end code I can do this?

**Comment by amireh** [comment]
You can still do it using the theme editor if you remove the surrounding HTML (`<script />`): you will then end up with the JavaScript code to inject. Otherwise, you could insert the snippet in `app/views/layouts/_head.html.erb` since it appears that you have access to the code.

Hope that helps!

**Comment by ismaelrumzan** [comment]
I had tried removing the html and putting the JS only but that did not work. Putting it the template file worked like a charm. Thanks!

**Comment by Jewe11** [comment]
Next time @ismaelrumzan you can ask in the canvas developer group for external code and user scriptshttp://community.canvaslms.com/groups/canvas-developers/
