### ISSUE TITLE
QR for Mobile Login does not work

### ISSUE THREAD

**Issue by luqiuyuan** [instructure/canvas-lms#1617]
### Summary:

I am using my own canvaslms instance. However, after enabling QR for Mobile Login feature, the QR image did not show. A 404 error occurred.

### Steps to reproduce:

 1. Log in with admin account
 2. Click Admin->[Organization Name]->Settings->Feature Options
 3. Find QR for Mobile Login, turn it on
 4. Click Admin->[Admin Name]->Settings->Feature Options
 5. Find QR for Mobile Login, turn it On
 6. Log in with a normal account
 7. Click Account->QR for Mobile Login

### Expected behavior:

For a normal user, after clicking on QR for Mobile Login, the QR image should show.

### Actual behavior:

For a normal user, after click on QR for Mobile Login, an error notification kept popping up saying that "An error occurred while retrieving your QR Code". In development console, the chrome browser gave and error saying that "doFetchApi.js:51 POST https://online.cornerstoneschools.ca/canvas/login.png 404 (Not Found)"

### Additional notes:

My investigation: It seems that the frontend tries to POST https://domain/canvas/login.png. However, in config/routes.rb, there is no route defined for canvas/login.png.

My environment:
1. Canvaslms version: release/2020-04-25.05
2. Server OS: Ubuntu 18.04

Below is a screenshot of this bug:
<img width="1280" alt="Screen Shot 2020-04-29 at 4 57 41 PM" src="https://user-images.githubusercontent.com/27582026/80646550-f288a880-8a3a-11ea-9ec4-3b8090209b31.png">

**Comment by ccutrer** [comment]
The (Instructure published) mobile applications are not available for open source, so the QR code generation is also not included in open source.

**Comment by luqiuyuan** [comment]
OK I see. I suggest that it should be removed from the open source version if it is not actually supported.

**Comment by luqiuyuan** [comment]
Thanks anyway.

**Comment by cvkline** [comment]
That's a reasonable request. I'll write a commit to hide this functionality unless the relevant proprietary mobile applications are available. Should be a couple of days.

> OK I see. I suggest that it should be removed from the open source version if it is not actually supported.
