### ISSUE TITLE
Duplicate nonce detected causing error message to WeBWorK via LTI

### ISSUE THREAD

**Issue by mathriddle** [instructure/canvas-lms#1635]
We have been integrating WeBWorK as an external tool with Canvas via LTI. Students access their WeBWorK problem sets as a Canvas assignment, grade the problems in WeBWorK, then have the scores sent back to the Canvas gradebook. This was working fine until Saturday, May 16. On that day I was testing some WeBWorK problems for an upcoming summer course. Everything was going smoothly until that evening when all of a sudden WeBWorK started reporting that it was unsuccessful in sending the score to the LMS (i.e. Canvas). I believe this was because when WeBWorK tried to send the score to Canvas, it received the error message "Duplicate nonce detected". A problem I graded at 10:43 p.m. had the score successfully recorded in the Canvas gradebook. A problem I graded at 10:46 p.m. failed to have the score recorded in the Canvas gradebook. And every problem since then has not had the grade sent back to Canvas. How can this be fixed?

I have attached the debugging information generated when clicking the link in Canvas to WeBWorK, and the LTI debugging info when WeBWorK tries to report the score back to Canvas

[Canvas-Webwork error.txt](https://github.com/instructure/canvas-lms/files/4705868/Canvas-Webwork.error.txt)

**Comment by holapozy** [comment]
hI Instructure/Canvas-Lms

Hope you are staying well and keeping safe in these trying times
Please I need to install canvas as LMS for my students as learning platform
I need help.

Thank you

*Signed*
*Olaposi Olaniyi*
*IT/Network & Systems Administrator*
*_______________________________________________________________________________*

**Comment by mathriddle** [comment]
This issue has finally been resolved. Canvas was able to identify that our WeBWorK server was posting times that were more than 1 minute ahead of the timestamp Canvas had. Apparently Canvas only allows for 1 minute ahead and 5 minutes behind. After syncing the time on the WeBWorK server (as of today it was about 90 seconds ahead of the "official" time), I was able to grade a problem in WeBWorK and have the score successfully sent to the LMS. I guess on May 16 between 10:43 pm and 10:46 pm when grade feedback stopped working, our WW server's time must have crossed over the 1 minute ahead threshold.
