### ISSUE TITLE
Canvas without redis

### ISSUE THREAD

**Issue by ismaelrumzan** [instructure/canvas-lms#1641]
Hi
I'm using Canvas with redis turned off. The only problem is that OAuth does not work which makes sense as from what I understand redis is used for both caching and OAuth
Is it possible to configure Canvas to have redis be used ONLY for OAuth and NOT caching?
Because I need OAuth to be configured for LTI apps. Or maybe something else could be used for OAuth?

**Comment by ccutrer** [comment]
yes, if you configure redis in config/redis.yml, but keep config/cache_store.yml configured to not use redis, it will only be used for the few features that require more advanced use of redis (oauth, request throttling, login lockouts are what come to mind).

**Comment by tierra** [comment]
I believe it might be required for LTI nonce replay attack protection as well btw.

**Comment by ismaelrumzan** [comment]
Excellent, thank you. Is there a documentation for the possible settings of the redis.yml file or if you could let me know what the settings should be for disabling the cache and allowing oauth for LTI, that would be awesome!

**Comment by ismaelrumzan** [comment]
I found in the cache_store example file that it could be set to mem_cache_store
I guess that are the only 2 options, redis or mem_cache - If I enable mem_cache, then I need to set up a mem_cache server correct, which would be done in the mem_cache.yml.

**Comment by ccutrer** [comment]
mem_cache is no longer supported (and is not referenced in the cache_store.yml.example on master). you can use `nil_store` to explicitly disable caching

**Comment by ismaelrumzan** [comment]
Thanks for that. Do you know from which version "nil_store" is supported. We're running 2018-09 version of canvas (we have not got around to upgrading yet because it requires a point upgrade of the database as well which is tricky to do with a production system). I tried the nil_store and I got passenger error "We're sorry, but something went wrong"

**Comment by ccutrer** [comment]
I don't know off-hand, no. You can also try "null_store"
