### ISSUE TITLE
Error in Quick Start

### ISSUE THREAD

**Issue by beatloose** [instructure/canvas-lms#1643]
I want to use Quick Start in Canvas to launch my application.
The "bundle exec rails" that exists in Quick Start in Canvas Canvas:compile_assets" gives me the following error. It looks like the error is caused by the fact that the babel is not installed. If you run "babel -version", the babel itself seems to be installed. It is.

Is there any way to resolve this error?
I'm sorry if you know of any, but please let me know.

--------------log------------------------------------------------
WARNING: Nokogiri was built against LibXML version 2.9.10, but has dynamically loaded 2.9.4
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
--> Starting: 'Making sure node_modules are up to date'
node is: v14.2.0 (/Users/user/.nodebrew/current/bin/node)
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > reshake@1.2.1" has unmet peer dependency "styled-components@3.x || 4.x".
[4/4] 🔨  Building fresh packages...
$ npm run lib
npm WARN lifecycle The node binary used for scripts is /var/folders/14/zd0hxx3x2cb4hpqw8_4y2kqh0000gn/T/yarn--1591622882515-0.6606556218512558/node but npm is using /Users/user/.nodebrew/node/v14.2.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @instructure/reactour@2.0.0 prelib /Users/user/Library/Caches/Yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare
> rimraf dist

> @instructure/reactour@2.0.0 lib /Users/user/Library/Caches/Yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare
> rollup -c

src/index.js → dist/reactour.cjs.js, dist/reactour.esm.js...
[!] (plugin babel) Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/user/Library/Caches/Yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/user/Library/Caches/Yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/preset-env/lib/index.js
- /Users/user/Library/Caches/Yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/user/Library/Caches/Yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/core/lib/config/files/index.js
- /Users/user/Library/Caches/Yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/core/lib/index.js
- /Users/user/Library/Caches/Yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js
- /Users/user/Library/Caches/Yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/rollup.config.js
- /Users/user/Library/Caches/Yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/rollup/dist/bin/rollup
src/index.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @instructure/reactour@2.0.0 lib: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @instructure/reactour@2.0.0 lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-06-08T13_28_12_721Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
rails aborted!
error running yarn install
/Volumes/dev/lerning/canvas/canvas/lib/tasks/js.rake:58:in `block (2 levels) in <top (required)>'
/Volumes/dev/lerning/canvas/canvas/lib/tasks/canvas.rake:31:in `block (3 levels) in <top (required)>'
/Volumes/dev/lerning/canvas/canvas/lib/tasks/canvas.rake:7:in `log_time'
/Volumes/dev/lerning/canvas/canvas/lib/tasks/canvas.rake:30:in `block (2 levels) in <top (required)>'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
/Volumes/dev/lerning/canvas/canvas/bin/rails:9:in `require'
/Volumes/dev/lerning/canvas/canvas/bin/rails:9:in `<top (required)>'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/Volumes/dev/lerning/canvas/canvas/vendor/bundle/ruby/2.5.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/Volumes/dev/lerning/canvas/canvas/bin/spring:13:in `require'
/Volumes/dev/lerning/canvas/canvas/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => js:yarn_install
(See full trace by running task with --trace)

**Comment by inthebrilliantblue** [comment]
@beatloose I have been struggling with getting canvas to work on a production setup, and the guides on this github are either out of date or written without any testing. And looking at how they reply to people and guide them to the google groups mailing list, you are probably not going to get help here.

**Comment by alexanderson1993** [comment]
Pardon the delay. I made a change to the @instructure/reactour repository which should resolve this issue. Try installing dependencies again and let me know how it goes.

**Comment by reckerswartz** [comment]
@alexanderson1993 still same 

```bash
yarn install --network-concurrency 1 --scripts-prepend-node-path
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > reshake@1.2.1" has unmet peer dependency "styled-components@3.x || 4.x".
[4/4] Building fresh packages...
$ npm run lib
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1596335597528-0.2254536153212512/node but npm is using /home/aventum/.nvm/versions/node/v14.7.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @instructure/reactour@2.0.0 prelib /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare
> rimraf dist


> @instructure/reactour@2.0.0 lib /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare
> rollup -c


src/index.js → dist/reactour.cjs.js, dist/reactour.esm.js...
[!] (plugin babel) Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/preset-env/lib/index.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/core/lib/config/files/plugins.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/core/lib/config/files/index.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/core/lib/index.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/rollup.config.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/rollup/dist/bin/rollup
src/index.js
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/preset-env/lib/index.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/core/lib/config/files/plugins.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/core/lib/config/files/index.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/core/lib/index.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/rollup.config.js
- /home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/aventum/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.71a498ae033056b6649bad95d4080323df2b9a4a.prepare/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @instructure/reactour@2.0.0 lib: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @instructure/reactour@2.0.0 lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aventum/.npm/_logs/2020-08-02T02_33_21_757Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by elledoir** [comment]
Also getting the same errror:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @instructure/reactour@2.0.0 lib: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @instructure/reactour@2.0.0 lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

when trying to run command : bundle exec rails canvas:compile_assets  to setup canvas on Ubuntu 18.04

**Comment by aleckretch** [comment]
> Also getting the same errror:
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @instructure/reactour@2.0.0 lib: `rollup -c`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @instructure/reactour@2.0.0 lib script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> when trying to run command : bundle exec rails canvas:compile_assets to setup canvas on Ubuntu 18.04

I'm getting this same error on macOS.

**Comment by AlineNascimento** [comment]
I'm getting this same error on macOS.

**Comment by slaughter550** [comment]
This issue was fixed by https://github.com/instructure/canvas-lms/commit/45cb519d526c5b2c04990fc8e277c70e51f1e67e
