### ISSUE TITLE
Running docker_dev_setup.sh within container does not setup canvas in container

### ISSUE THREAD

**Issue by lcundiff** [instructure/canvas-lms#1660]
# Summary:
When running docker image, it will not start up automatically. And when running docker_setup (Quick Start Guide) Docker setup will not install dory, but will attempt to and "re-login" before asking to install dory again. This loops endlessly until you reply "n" to installing dory. 

### Steps to reproduce:
 1. docker run --name canvas -p 127.0.0.1:80:8080/tcp instructure/canvas-lms:stable
 2. docker exec -u 0 -it canvas /bin/bash
3. cd /usr/src/app
4. ./script/docker_dev_setup.sh
5. "y" to installing dependencies 
6. "y" to installing dory 
### Expected behavior:
Installs dory and continues installing Canvas
### Actual behavior:
Asks to add docker user, then asks to login, then asks to install dory again. Loops forever. 
### Additional notes:
Hosted on Container Optimized OS on Google Cloud. Here is info from the server: 
Static hostname: n/a
Transient hostname: canvas
Operating System: Container-Optimized OS from Google
      Kernel: Linux 4.14.145+
      Architecture: x86-64

**Comment by grahamb** [comment]
The `docker_dev_setup.sh` script is meant to be run from the host, not from within a docker container. Have you reviewed https://github.com/instructure/canvas-lms/blob/master/doc/docker/developing_with_docker.md?

**Comment by lcundiff** [comment]
Hi @grahamb thank you for responding! 

Yes I read over that, but didn't realize setup.sh had to be ran outside the docker container. I'm a newbie at docker, but I can look into trying to run it outside the docker container. How will I be able to follow the setup guide if I run the file from outside the container?

**Comment by grahamb** [comment]
You just run the script from your host computer. It'll do the rest.

– Graham

**Comment by lcundiff** [comment]
Hi @grahamb 

I am trying to run it after pulling the docker image, not the github repo. So I cannot run the script from host since the script is within a docker container. 

I understand you said it is not meant to run in a docker container, but I do not have the script outside of the docker container, so how do I run setup on canvas within a docker image?

**Comment by grahamb** [comment]
Can you explain exactly what it is you're trying to accomplish? If all you want is a Canvas dev environment, then you should be following the directions at https://github.com/instructure/canvas-lms/blob/master/doc/docker/developing_with_docker.md: <https://github.com/instructure/canvas-lms/blob/master/doc/docker/developing_with_docker.md:> 

- clone the repo
- run ./script/docker_dev_setup.sh

– Graham

**Comment by lcundiff** [comment]
My apologies, I pulled the docker container from https://hub.docker.com/r/instructure/canvas-lms

I started the container and was wondering if there is a way setup from there?

**Comment by lcundiff** [comment]
@grahamb To provide clarity, I am stating that running the Canvas docker image is not running canvas when using "docker run" command. I then tried following instructions listed (which you also linked above) and it states to run the setup file. If the setup file is not meant to be ran within docker container, then what is the process for getting "docker run canvas" working. 

Thank you!

**Comment by lcundiff** [comment]
@grahamb Apologies, should've closed this issue a couple of years ago. Like you stated docker_dev_setup is to be ran after pulling the canvas repo. I was attempting to get canvas container working out of the box by simply pulling the image and building it. If anyone would like this functionality, you can pull this image which I have used for a few years for testing: https://hub.docker.com/r/lbjay/canvas-docker

(However note that it is not being maintained and is 6 years out of date)

Still it would be nice to get canvas working in a similar way as the docker image linked above, instead of downloading the full repo and running a setup script. I will check other issues, if this has already been brought up as an idea.
