### ISSUE TITLE
Adding a new course with a lot of subaccounts, subaccount field very slow to load

### ISSUE THREAD

**Issue by jonespm** [instructure/canvas-lms#1673]
### Summary:
It was reported that when adding a new course (+Course) on an account with a lot of subaccounts (we have almost 1000) it is inefficiently querying the subaccounts 10 at a time and takes almost a minute before this field is usable. Each network call takes about 0.3s. I believe that if the per_page was set higher with less network calls this field would load a lot faster, but I don't know where to set it or how to get this populated quicker.

![image](https://user-images.githubusercontent.com/27447/87806793-68740300-c825-11ea-99f5-af8d23dae3d9.png)

### Steps to reproduce:

 1. Click +Course on a site that has a lot of subaccounts. (At least Hundreds or a thousand)
 2. Note that the Subaccount field doesn't work until all of the network calls are complete.

### Expected behavior:
 1. Subaccount form field should be usable faster

### Actual behavior:
 1. Subaccount form field takes up to a minute to load

### Additional notes:

It's noted that this slowness may have been part of a recent release and wasn't always like this. I saw [this change](https://github.com/instructure/canvas-lms/commit/d94205986f3a9c367d0f05fb8fba7968d93b756a) that may have been related.

**Comment by cvkline** [comment]
Looks like an inadvertent side-effect of an improvement to searching. It should be an easy fix.

**Comment by cvkline** [comment]
We were relying on the default value for page size when pulling down the paginated list of subaccounts, which is woefully small for this case. I've increased it by a factor of 20.

**Comment by cvkline** [comment]
Fixed here. [https://github.com/instructure/canvas-lms/commit/054742002e258e54623f68480a0e5cbfd804561c](url)
