### ISSUE TITLE
gem install error

### ISSUE THREAD

**Issue by SnrtIevg** [instructure/canvas-lms#1695]
### Summary:
Gem::InstallError: prawn requires Ruby version ~> 2.5.
An error occurred while installing prawn (2.3.0), and Bundler cannot continue.
Make sure that `gem install prawn -v '2.3.0'` succeeds before bundling.
### Steps to reproduce:

do as production start

**Comment by SnrtIevg** [comment]
please update production start document and be careful about dependceny's version

**Comment by davidkhanpk** [comment]
> please update production start document and be careful about dependceny's version

With the application start documentation, everything is installed by default(of course latest version). But in config files older versions. That's why try to run application with documentation is giving errors.
