### ISSUE TITLE
calendar doesnt work with locales other than english

### ISSUE THREAD

**Issue by ayyurek** [instructure/canvas-lms#170]
Both the full page and sidebar calendars are broken, when any non-english language is selected. It loads correctly, but when the user begins to navigate around months, month names get broken. Sidebar calendar, continues to work with broken month names, but the full page calendar event does not allow to navigate around months.

Also if you have an undated event listed just below the sidebar calendar, the number of undated events indicator is getting increased by one, every time user clicks on a day.

And a final bug, when user enters the calendar page, in the calendar event create form, dates chosen from the picker are in English. etc. Nov  8, 2012, but when the user clicks the show more options link in the modal box, the form in the new window shows the month short name in other language. in my example Kas  8, 2012. And gives a validation error, ''That's not a date!''

**Comment by claydiffrient** [comment]
@dgilperez @ayyurek I'm sorry that discussion fell off on this.  I believe this problem has been resolved. I can't seem to reproduce it.  I'm going to close the issue, but if it's still a problem let us know.
