### ISSUE TITLE
 undefined method `filter' for []:Array in Submission model

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#1707]
### Summary:

The [submission model](https://github.com/instructure/canvas-lms/blob/stable/app/models/submission.rb#L2543) contains a call to Array#filter in the `visible_rubric_assessments_for` method. `Array#filter` was added as an alias to `Array#select` in Ruby 2.6. According to a message posted to the Canvas mailling list by @ccutrer, Canvas will not require Ruby 2.6 until the October 7 deploy.

It looks like this was introduced by @apackel in 3184e7d89dab1828b278e41c1f4dea7e3becccb5.

**Comment by maths22** [comment]
This will be backported to `2020-09-09` and `2020-09-23`, but not to `2020-10-07` since `2020-10-07` and beyond will not boot on ruby < 2.6.
