### ISSUE TITLE
New Analytics not shown at all

### ISSUE THREAD

**Issue by Ahmed-Salama96** [instructure/canvas-lms#1726]
### Summary:
I have turned on the new analytics flags in site admin and its enabled on the course too, But no button for it and not shown at all.

### Steps to reproduce:

 1. Go to site admin, then settings, Then Feature options.
 2. search for the feature 'New Course and User Analytics' and turn it on.
 3. search for the feature 'New Analytics API Access' and turn it on.
4. go to course settings page, Then feature option, You will find that ' New Course and User Analytics ' is turned on by default.

### Expected behavior:
The New Analytics button and tab are shown in the course.

### Actual behavior:
The New Analytics button and tab are not shown anywhere in the system ( Also after waiting for more than 24H )

**Comment by Ahmed-Abd-elhamid** [comment]
you should install Analytics module https://github.com/instructure/analytics

**Comment by Ahmed-Salama96** [comment]
I tried to install it before but this is not the new analytics tool, New Analytics tool in a commercial tool in canvas lms and not offered in the open-source 
check: [](https://github.com/instructure/canvas-lms/wiki/FAQ#are-there-any-code-differences-between-the-open-source-and-hosted-offerings)
