### ISSUE TITLE
install canvas on unbuntu18.04 "RAILS_ENV=production bundle exec rake db:initial_setup"   An error occurred

### ISSUE THREAD

**Issue by zxc916684603** [instructure/canvas-lms#1729]
### Steps to reproduce:

 1.   RAILS_ENV=production bundle exec rake db:initial_setup
 2.   
 3. 

### Expected behavior:
      Database initialization completed
### Actual behavior:
      /data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
1: production:public
1: production:public
==  InvalidateBuiltInRoleCaches: migrating ====================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `clear_downstream_caches' for nil
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/performable_method.rb:4:in `initialize'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/message_sending.rb:35:in `new'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/message_sending.rb:35:in `send_later_enqueue_args'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/delayed/message_sending.rb:7:in `send_later_enqueue_args'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/message_sending.rb:75:in `send_later_if_production_enqueue_args'
/data/wwwroot/canvas/db/migrate/20200914184302_invalidate_built_in_role_caches.rb:40:in `up'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:817:in `exec_migration'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:797:in `block in migrate'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:796:in `migrate'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:608:in `migrate'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:977:in `migrate'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1345:in `ddl_transaction'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/data/wwwroot/canvas/config/initializers/active_record.rb:1462:in `execute_migration_in_transaction'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `each'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `block in migrate'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `migrate'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1036:in `up'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1011:in `migrate'
/data/wwwroot/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:172:in `migrate'

### Additional notes:
     I don't know what to do ,I  need your help.

**Comment by zxc916684603** [comment]
I need your help

**Comment by simonista** [comment]
Hi, sorry about this, I'm working on a fix right now, but you can get past it by changing this line: https://github.com/instructure/canvas-lms/blob/master/db/migrate/20200914184302_invalidate_built_in_role_caches.rb#L38 to `if Shard.current.default? && Account.site_admin`

**Comment by zxc916684603** [comment]
Thanks for your help!

**Comment by sepl99** [comment]
Hi, I'm experiencing a similar issue using an Ubuntu 16.04 server. Essentially the same output but beginning with "undefined method `global_id' for nil:NilClass". 

When I try to connect to the login page in my browser I just get a blank page (which I assume is because of the issue executing RAILS_ENV=production bundle exec rake db:initial_setup)

Changing the "if Shard.current.default?" line didn't seem to have any effect for me, is there anything else I could try?

**Comment by dengcen** [comment]
I am meeting this trouble for production version? Hope you can fix it  as soon as possbile.

**Comment by ErnestStaug** [comment]
I am having the same issue...

**Comment by simonista** [comment]
This is fixed now in stable here: 361391a4794e4bbdb9bee3895ade6695cab537e2

**Comment by dengcen** [comment]
thank you for your help , I will download chenk it again right now .


















At 2020-10-28 03:43:26, "Simon Williams" <notifications@github.com> wrote:

This is fixed now in stable here: 361391a
