### ISSUE TITLE
Ubuntu 18.04 Ruby 2.6 db setup error

### ISSUE THREAD

**Issue by amg-web** [instructure/canvas-lms#1731]
#Summary:
starting db migrate have error:
```
==  AddAnonymousGradingToAssignments: migrating ===============================
-- add_column(:assignments, :anonymous_grading, :boolean, {})
   -> 0.0014s
-- change_column_default(:assignments, :anonymous_grading, {:from=>nil, :to=>false})
   -> 0.0067s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `jobs_held' for #<Switchman::Shard:0x0000556271a71bc8>
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/attribute_methods.rb:430:in `method_missing'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/delayed/backend/base.rb:77:in `current_shard='
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/attribute_assignment.rb:51:in `public_send'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/attribute_assignment.rb:43:in `each'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/attribute_assignment.rb:43:in `_assign_attributes'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/attribute_assignment.rb:23:in `_assign_attributes'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/core.rb:315:in `initialize'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/aroi-0.0.7/lib/aroi/instrumentation/active_record.rb:34:in `block in initialize'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/aroi-0.0.7/lib/aroi/instrumentation/active_record.rb:33:in `initialize'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/inheritance.rb:66:in `new'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/inheritance.rb:66:in `new'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/backend/active_record.rb:31:in `create'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/backend/base.rb:76:in `enqueue'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/delayed/backend/base.rb:21:in `block (2 levels) in enqueue'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/guard_rail.rb:6:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/delayed/backend/base.rb:21:in `block in enqueue'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/delayed/backend/base.rb:40:in `block in enqueue'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:628:in `block in activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:96:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:627:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/delayed/backend/base.rb:39:in `enqueue'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/message_sending.rb:35:in `send_later_enqueue_args'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/delayed/message_sending.rb:7:in `send_later_enqueue_args'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/message_sending.rb:75:in `send_later_if_production_enqueue_args'
/home/canvas/public_html/db/migrate/20180312105008_add_anonymous_grading_to_assignments.rb:28:in `block (2 levels) in change'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:699:in `up'
/home/canvas/public_html/db/migrate/20180312105008_add_anonymous_grading_to_assignments.rb:27:in `block in change'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:735:in `block in reversible'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:956:in `execute_block'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:735:in `reversible'
/home/canvas/public_html/db/migrate/20180312105008_add_anonymous_grading_to_assignments.rb:26:in `change'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:814:in `exec_migration'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:797:in `block in migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:796:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:608:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:977:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/switchman/active_record/base.rb:49:in `transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1343:in `ddl_transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/canvas/public_html/config/initializers/active_record.rb:1462:in `execute_migration_in_transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `each'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `block in migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `migrate'
/home/canvas/public_html/lib/tasks/canvas.rake:191:in `block (3 levels) in <top (required)>'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:87:in `block (6 levels) in shardify_task'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:87:in `each'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:87:in `block (5 levels) in shardify_task'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/switchman/database_server.rb:107:in `unguard'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:86:in `block (4 levels) in shardify_task'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:376:in `block (2 levels) in with_each_shard'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:628:in `block in activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:96:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:627:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:374:in `block in with_each_shard'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:370:in `with_each_shard'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:71:in `block (3 levels) in shardify_task'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/switchman/database_server.rb:107:in `unguard'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:68:in `block (2 levels) in shardify_task'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/switchman/guard_rail.rb:22:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/guard_rail.rb:8:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:67:in `block in shardify_task'
/home/canvas/public_html/lib/tasks/db_load_data.rake:207:in `block (2 levels) in <top (required)>'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
```
### Steps to reproduce:

 1.
 2.
 3.

**Comment by simonista** [comment]
Thanks for the report, we'll look into it.

**Comment by simonista** [comment]
I'm pretty sure this is an issue with the order in which migrations run. I haven't tested this yet but I think one quick thing you could do to unblock yourself is to rename `db/migrate/20200826160818_add_on_hold_to_switchman_shards.rb` to `db/migrate/20180226160818_add_on_hold_to_switchman_shards.rb`

**Comment by simonista** [comment]
Actually, here's a better change, change: https://github.com/instructure/canvas-lms/blob/master/db/migrate/20180312105008_add_anonymous_grading_to_assignments.rb#L28-L34 to just

```
        DataFixup::BackfillNulls.run(Assignment, :anonymous_grading)
```

I'll work on getting that into a commit and merged.

**Comment by amg-web** [comment]
Thanks. can not check now.

this is from clean initial setup U18.04 ruby 2.6 latest stable git:
RAILS_ENV=production bundle exec rake db:initial_setup
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
1: production:public
1: production:public
==  InvalidateBuiltInRoleCaches: migrating ====================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `clear_downstream_caches' for nil
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/performable_method.rb:4:in `initialize'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/message_sending.rb:35:in `new'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/message_sending.rb:35:in `send_later_enqueue_args'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/delayed/message_sending.rb:7:in `send_later_enqueue_args'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/inst-jobs-0.16.0/lib/delayed/message_sending.rb:75:in `send_later_if_production_enqueue_args'
/home/canvas/public_html/db/migrate/20200914184302_invalidate_built_in_role_caches.rb:40:in `up'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:817:in `exec_migration'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:797:in `block in migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:796:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:608:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:977:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1345:in `ddl_transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/canvas/public_html/config/initializers/active_record.rb:1462:in `execute_migration_in_transaction'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `each'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `block in migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1036:in `up'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1011:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:87:in `block (6 levels) in shardify_task'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:87:in `each'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:87:in `block (5 levels) in shardify_task'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/switchman/database_server.rb:107:in `unguard'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:86:in `block (4 levels) in shardify_task'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:376:in `block (2 levels) in with_each_shard'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:628:in `block in activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:96:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:627:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:374:in `block in with_each_shard'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/app/models/switchman/shard.rb:370:in `with_each_shard'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:71:in `block (3 levels) in shardify_task'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/switchman/database_server.rb:107:in `unguard'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:68:in `block (2 levels) in shardify_task'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/switchman/guard_rail.rb:22:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-2.0.0/lib/switchman_inst_jobs/guard_rail.rb:8:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.0/lib/tasks/switchman.rake:67:in `block in shardify_task'
/home/canvas/public_html/lib/tasks/db_load_data.rake:210:in `block (2 levels) in <top (required)>'
/home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

**Comment by simonista** [comment]
The fix for that one is mentioned here, and is also making it's way into stable today: https://github.com/instructure/canvas-lms/issues/1729
