### ISSUE TITLE
On LTI - Deeplinking launch, lineItem object sent by the tool is being ignored.

### ISSUE THREAD

**Issue by GreenOn** [instructure/canvas-lms#1749]
### Summary: 
Canvas Instructure seems to ignore the lineitem object that is sent along with the [lti resource link](https://www.imsglobal.org/spec/lti-dl/v2p0#lti-resource-link).

### Steps to reproduce:

We use a library called [LTIJS](https://cvmcosta.me/ltijs/#/deeplinking?id=contentitems-parameter) to make a deeplinking launch request where we are providing lineItem as part of the parameter for assignments. However, Canvas Instructure seems to create a default lineitem ignoring the scoreMax and the label parameters we are passing as part of the lineitem.

### Expected behavior:
Canvas Instructure should follow the IMS standards to accept lineitem parameters that is sent by the tool.
### Actual behavior:
Canvas Instructure ignores lineitem parameter sent by the tool.

**Comment by Ardena** [comment]
If you are on open source Canvas, there are several siteadmin feature flags that can be turned on to allow this option.  In https://<siteadmin_url>/accounts/self/settings#tab-features if you turn on LTI Deep Linking Line Items, LTI Deep Linking Line Items on Assignment Edit page (which may be buggy as it has an update coming soon), and probably LTI Multiple Deep Linking Assignments, that should cover the behavior.
