### ISSUE TITLE
Clipboard API has been blocked because of a Feature Policy applied to the current document. iframe on Chrome

### ISSUE THREAD

**Issue by dvitrium** [instructure/canvas-lms#1767]
### Summary:

Our LTI app canvas extension has a "copy" button that allows users to copy links, for ease of use, as requested by our users. This function is not working on Chrome because it is inside an iframe without the allowed permissions, the following code:

`navigator.clipboard.writeText("My Text!")
`

Results in the following DOMException:

> Uncaught (in promise) DOMException: The Clipboard API has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.

### Steps to reproduce:

 1.  Create an lti app with the following code and add it as an extension into a canvas course:

`navigator.clipboard.writeText("My Text!")`

 2. Execute the code `navigator.clipboard.writeText("My Text!")` on Chrome
 3. Verify that nothing was copied to your clipboard, but there was a DOMException in the console

### Expected behavior:

For the text to be added to the users clipboard as if they copied it, so they can paste it, on Chrome. This works in Firefox.

### Actual behavior:

Uncaught (in promise) DOMException: The Clipboard API has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.

### Additional notes:

I suspect we may need changes similar to these https://github.com/instructure/canvas-lms/commit/fcae49e4e556a07c0a9b49ee6fe25fd914ab1058

**Comment by buckett** [comment]
While you can use https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand to workaround this it's deprecated and really anything that's being written today should be using the much better clipboard API.

**Comment by buckett** [comment]
I think this got fixed in 706cae4bdce2d2b5c196b14c21955d25eea11b12
