### ISSUE TITLE
Discussions - page coming soon

### ISSUE THREAD

**Issue by amg-web** [instructure/canvas-lms#1787]
it was problem of settings

**Comment by zjr** [comment]
Fix for me was turning off the "Update announcement/discussion edit page to use react/instui" account setting.

**Comment by geekfly2016** [comment]
Update announcement/discussion edit page to use react/instui    open turning on

**Comment by geekfly2016** [comment]
I was turning on "Update announcement/discussion edit page to use react/instui"，and turning off  "Discussion Create/Edit Page React Update"
