### ISSUE TITLE
Database Population Error

### ISSUE THREAD

**Issue by darkness4life14** [instructure/canvas-lms#1792]
### Steps to reproduce:

 1. Followed production steps to install canvas LMS
 2. Populate DB
 3. Getting this error:
`var/canvas/vendor/bundle/ruby/2.6.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.6.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
1: production:public
1: production:public
==  AddReplicaIdentityForDeveloperKeys: migrating =============================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `id' for nil:NilClass
/var/canvas/db/migrate/20201125000002_add_replica_identity_for_developer_keys.rb:25:in `up'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:817:in `exec_migration'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:797:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/switchman/connection_pool_proxy.rb:15:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:796:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-3.1.1/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:608:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:977:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1345:in `ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/canvas/config/initializers/active_record.rb:1460:in `execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1036:in `up'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1011:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:87:in `block (6 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:87:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:87:in `block (5 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/switchman/database_server.rb:109:in `unguard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:86:in `block (4 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:378:in `block (2 levels) in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:630:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:98:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:629:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:376:in `block in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:372:in `with_each_shard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:71:in `block (3 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/switchman/database_server.rb:109:in `unguard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:68:in `block (2 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/switchman/guard_rail.rb:24:in `activate'/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-3.1.1/lib/switchman_inst_jobs/guard_rail.rb:8:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:67:in `block in shardify_task'
/var/canvas/lib/tasks/db_load_data.rake:210:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

Caused by:
NoMethodError: undefined method `id' for nil:NilClass
/var/canvas/db/migrate/20201125000002_add_replica_identity_for_developer_keys.rb:25:in `up'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:817:in `exec_migration'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:797:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/switchman/connection_pool_proxy.rb:15:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:796:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-3.1.1/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:608:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:977:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1345:in `ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/canvas/config/initializers/active_record.rb:1460:in `execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1036:in `up'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1011:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:87:in `block (6 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:87:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:87:in `block (5 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/switchman/database_server.rb:109:in `unguard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:86:in `block (4 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:378:in `block (2 levels) in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:630:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:98:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:629:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:376:in `block in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/app/models/switchman/shard.rb:372:in `with_each_shard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:71:in `block (3 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/switchman/database_server.rb:109:in `unguard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:68:in `block (2 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/switchman/guard_rail.rb:24:in `activate'/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-3.1.1/lib/switchman_inst_jobs/guard_rail.rb:8:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.2/lib/tasks/switchman.rake:67:in `block in shardify_task'
/var/canvas/lib/tasks/db_load_data.rake:210:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace) `

### Additional notes:
Please help me fix this, I tried many times and still doesn’t work.

**Comment by ccutrer** [comment]
2b427c3567c1b0948737d1c88c85ad509895b5d2 fixes this (assuming you're running master, since the error was only introduced yesterday).

**Comment by darkness4life14** [comment]
Thanks, this is now fixed.
