### ISSUE TITLE
Getting "shell level too high" when starting automatic jobs

### ISSUE THREAD

**Issue by darkness4life14** [instructure/canvas-lms#1797]
### Summary:
I can't start the automated jobs process, the error below always appears and it won't start.
I have a 16 GB RAM server with 6 CPU cores running this.
### Steps to reproduce:

 1. Start the automated jobs process
 2. /bin/bash: warning: shell level (1000) too high, resetting to 1 appears

**Comment by Gao-Jun** [comment]
Try
`script/delayed_job start`

**Comment by darkness4life14** [comment]
Already found the fix, I used another user other than root and got it working.
