### ISSUE TITLE
Inconsistent Production install Wiki  page

### ISSUE THREAD

**Issue by youneszeboudj** [instructure/canvas-lms#1798]
The file:

> https://github.com/instructure/canvas-lms/blob/master/package.json#L7

indicates
> ...
>    "name": "canvas-lms",
>   "license": "AGPL-3.0",
>   "version": "0.0.0",
>   "engines": {
>     "node": ">=12.5.0",
>     "yarn": "^1.19.1"
>  ...

while the Wiki page here for installing canvas 

> https://github.com/instructure/canvas-lms/wiki/Production-Startc

indicates taht yarn 1.10.1-1 and node 10 should be used.

This creates an error when running the 'yarn install' command... namely

canvas-lms@0.0.0: The engine "yarn" is incompatible with this module. Expected version XXX
canvas-lms@0.0.0: The engine "node" is incompatible with this module. Expected version XXX

something like that.

**Comment by zavaab** [comment]
Run the following command To install version 1.22.5 , It works
***sudo apt-get install yarn***
Then run the following command
***yarn install***

**Comment by Thyroxine** [comment]
Yarn 1.22.5 requires nodejs 12 now.
I had to replace
`curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
with
`curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -`

**Comment by simonista** [comment]
Thanks, you are right, I've updated the wiki. And just fyi, Node 14 is right around the corner as well.
