### ISSUE TITLE
How to hide the download option, where to find the html code for the download option?

### ISSUE THREAD

**Issue by apexali** [instructure/canvas-lms#1804]
First of all, I am sorry because I don't know if it's the right place to post such kind of a question here. Secondly, ty for your time.
My client asked me to hide the download option (I know users can still download stuff but my client wants to make it hard for the people), what I know is if I would be able to access the code I can just remove this part of the line from the code what I dont know is where the code is located. The path says this http://canvas.paratuscourses.com/courses/18/files/791/download?download_frd=1, I have looked into many directories and still unable to find it, I am using Filezilla to access the files. Canva lms is installed on a centos7
![Capture](https://user-images.githubusercontent.com/69515004/106393870-3883fa00-641b-11eb-8c25-b43bba8d7f76.PNG)

**Comment by AncestorHunter06** [comment]
I believe the file you are looking for can be found here:

`./app/views/files/show.html.erb`

Please, let me know if this is correct or not.

~ Ashley

**Comment by apexali** [comment]
> I believe the file you are looking for can be found here:
> 
> `./app/views/files/show.html.erb`
> 
> Please, let me know if this is correct or not.
> 
> ~ Ashley

You were right and it worked like a charm. I don't know my way around ruby so what I just did is I commented out this line <% = link_to "Download #{@attachment.display_name}", download_url %> and problem solved. Thank for your help Ashley.
