### ISSUE TITLE
Problem in  Kaltura setup instructions

### ISSUE THREAD

**Issue by jerryshen** [instructure/canvas-lms#181]
Hey, I followed 'Kaltura setup instructions' and created a self-hosted server.

But after I finished the configurations on canvas-domain/plugins/kaltura, and I open record video, it says conection error, try it again. I don't know why, but I can see the log in kaltura self-hosted server that canvas requested.

Player UI Conf ID: 	1727897
KCW UI Conf ID: 	1727883
Uploader UI Conf ID: 	1727897

Anyone can help me to figure it out? thanks

**Comment by claydiffrient** [comment]
@jerryshen I'm sorry that we haven't responded to this.  I hope the issue has been resolved for you.  I'm going to close the issue, but feel free to reopen if it's still a problem for you.

**Comment by KiranPurbey1993** [comment]
Hello everyone,
I have an account in kmc.kaltura.com , Please can anyone tell me from where I will get Player UI Conf ID , 
KCW UI Conf ID and Uploader UI Conf ID.

**Comment by KiranPurbey1993** [comment]
Hello Everyone ,
I have self hosted kaltura (http://kaltura.glicc.jp) and self hosted canvas (https://canvas.glicc.jp)
 I configure kaltura with canvas and putting all values in plugins setting of canvas  and when i put notification url in kmc , url is https://canvas.glicc.jp/media_objects/kaltura_notifications , it fails to ping. And  when i read production log, it is showing me error.
I am attaching plugins setting and error log.
Please help me to figure it out.
![error](https://cloud.githubusercontent.com/assets/22252684/21537472/078dd658-cdb8-11e6-9d62-f78c80814ed0.png)
![plugin](https://cloud.githubusercontent.com/assets/22252684/21537474/105e4e48-cdb8-11e6-9490-e46a8c93a16a.png)
