### ISSUE TITLE
Suggestions on which image to use on docker hub?

### ISSUE THREAD

**Issue by boblauer** [instructure/canvas-lms#1825]
### Summary:

I tried walking through the Docker setup instructions, but couldn't get dinghy to start in VirtualBox. I'm instead looking through dockerhub to see if there are any images I can use instead.

I see there is an `instructure/canvas-lms` image, but it was updated 2 years ago. Does that mean the image is using code that's 2 year old? If so, are there plans to update that image at some point?

**Comment by LastedGuide** [comment]
I don't think a docker hub image would work. I don't use dinghy, but if you wont get dinghy working, you might be out of luck. Try running this on a different computer, or a full linux vm.

**Comment by boblauer** [comment]
If anyone stumbles upon this in the future, I took an alternative route and used the virtual image from https://bitnami.com/stack/canvaslms/virtual-machine. That worked like a charm.
