### ISSUE TITLE
disable bitnami banner on canvas bitnami

### ISSUE THREAD

**Issue by Waleed-Ramadan** [instructure/canvas-lms#1828]
dear all

i'm running this version of canvas bitnami 2020.12.16.47-1 and i'm trying to disable the bitnami banner with this command below: 

sudo /opt/bitnami/apps/canvaslms/bnconfig.disabled --disable_banner 1
 
and it gave me this error :
sudo: /opt/bitnami/apps/canvaslms/bnconfig.disabled: command not found

what should i do to disable it 

many thanks

**Comment by simonista** [comment]
Hi @Waleed-Ramadan, we have no connection with the bitnami version, we don't maintain it and aren't familiar with any customizations they may have done, you'll need to check with them. Sorry.
