### ISSUE TITLE
Bundler version

### ISSUE THREAD

**Issue by fernandochile** [instructure/canvas-lms#1840]
Hi,

I am trying to install Canvas LMS on a VPS server running Ubuntu 16.04. The problem I have is that when I try to install bundler, I get an error with the version and I don't know if there is compatibility with a more current one.

Greetings.
![Captura de Pantalla 2021-04-02 a la(s) 15 17 02](https://user-images.githubusercontent.com/30675519/113442619-c140f700-93c6-11eb-9c45-a8744023d94a.png)

**Comment by ojhaashish13** [comment]
If possible please post your solution. I am stuck on same error.

**Comment by ccutrer** [comment]
The error is that a new version of bundler is required. So `gem install bundler -v 2.2.17 && bundle _2.2.17_ install`

**Comment by ccutrer** [comment]
(Or possibly a slightly older version, depending on what branch you're on. from the error in the original post, 2.2.11 would be the newest allowed)

**Comment by ojhaashish13** [comment]
Thanks, it worked. I have used the newer version 2.2.14 and it worked for me.

**Comment by tuantiensiu** [comment]
> The error is that a new version of bundler is required. So `gem install bundler -v 2.2.17 && bundle _2.2.17_ install`

It work with me, thank you. I use ruby 2.6
