### ISSUE TITLE
PG::DuplicateTable: ERROR:  relation "auditor_authentication_records_2021_3" already exists

### ISSUE THREAD

**Issue by yapwenbin** [instructure/canvas-lms#1853]
### Steps to reproduce:

 1. Follow the steps in https://github.com/instructure/canvas-lms/wiki/Production-Start
 2. Problem occurs during Database population stage, https://github.com/instructure/canvas-lms/wiki/Production-Start#database-population

### Expected behavior:
Database populated without any errors

### Actual behavior:
PG::DuplicateTable: ERROR:  relation "auditor_authentication_records_2021_3" already exists

### Additional notes:
Installed on Ubuntu 20.04, with PostgreSQL 12.6
[error.txt](https://github.com/instructure/canvas-lms/files/6329188/error.txt)

**Comment by huangdengpan** [comment]
I saw the errors, too.

**Comment by yapwenbin** [comment]
Looks like doing a fresh install today with a fresh copy of the source code solved the issue.

**Comment by huangdengpan** [comment]
i am updating canvas , the problem still exists.

**Comment by cc-masao** [comment]
I have the same issue with both stable and master branch as of today.
On Ubuntu 20.04 & PostgreSQL 12.6

**Comment by yapwenbin** [comment]
I make some changed in this part, I'm not sure if this is even related:
https://github.com/instructure/canvas-lms/wiki/Production-Start#bundler-and-canvas-dependencies

I change the version number from 2.1.4 to 2.2.11

```
sysadmin@appserver:/var/canvas$ sudo gem install bundler --version 2.2.11
sysadmin@appserver:/var/canvas$ bundle _2.2.11_ install --without pulsar --path vendor/bundle
```

**Comment by huangdengpan** [comment]
any updates ?

**Comment by AlexKichkailo** [comment]
Same issue when trying to install Canvas from the latest Bitnami installer.

**Comment by woncode** [comment]
still same problem when fresh install from the latest Bitnami installer.

**Comment by dengcen** [comment]
I aslo have this issue, pls to sloves.

**Comment by dengcen** [comment]
> I make some changed in this part, I'm not sure if this is even related:
> https://github.com/instructure/canvas-lms/wiki/Production-Start#bundler-and-canvas-dependencies
> 
> I change the version number from 2.1.4 to 2.2.11
> 
> ```
> sysadmin@appserver:/var/canvas$ sudo gem install bundler --version 2.2.11
> sysadmin@appserver:/var/canvas$ bundle _2.2.11_ install --without pulsar --path vendor/bundle
> ```

the same change. but I think the change no related this issue.

**Comment by dengcen** [comment]
Which experts can solve this problem?? everyone still wait for solving.

**Comment by simonista** [comment]
If it's failing on line 31 of `db/migrate/20200414193317_create_auditors_partitions.rb`, you just need to mark the migration as already run (`INSERT INTO schema_migrations (version) VALUES ('20200414193317');`). The migration has already run and created the initial partitions.

If it's failing on line 36, you should change it to `partman.create_partition(current_partition_time, graceful: true)`. I'll push up a commit to make this change as well.

**Comment by dengcen** [comment]
> 
> 
> If it's failing on line 31 of `db/migrate/20200414193317_create_auditors_partitions.rb`, you just need to mark the migration as already run (`INSERT INTO schema_migrations (version) VALUES ('20200414193317');`). The migration has already run and created the initial partitions.
> 
> If it's failing on line 36, you should change it to `partman.create_partition(current_partition_time, graceful: true)`. I'll push up a commit to make this change as well.
it is line 36,but if I change db/migrate/20200414193317_create_auditors_partitions.rb,like this :partman.create_partition(current_partition_time, graceful: true) in stable version, It will have new isseue:
undefined method `global_id' for nil:NilClass
...........

/var/ikep/app/models/course.rb:314:in `ensure_dummy_course'
/var/ikep/db/migrate/20210511200919_ensure_dummy_course.rb:23:in `up'
[error (2).txt](https://github.com/instructure/canvas-lms/files/6538481/error.2.txt)

**Comment by simonista** [comment]
Hey @dengcen , that is a totally different issue than the rest of this thread. That looks to be a bug that snuck through our testing and we’re working on a fix, but for I believe you should be able to comment out the line (around 249 in app/models/course.rb) that says "after_create :copy_from_course_template”. And that should get the migration past that error.

**Comment by dengcen** [comment]
> 
> 
> Hey @dengcen , that is a totally different issue than the rest of this thread. That looks to be a bug that snuck through our testing and we’re working on a fix, but for I believe you should be able to comment out the line (around 249 in app/models/course.rb) that says "after_create :copy_from_course_template”. And that should get the migration past that error.

Thank you very much simonista. do you have some doc about db design?? can you send me?? thank you

**Comment by simonista** [comment]
I don't have any DB design docs to share, sorry. It's a large database, around ~200 tables, and the data is mostly normalized. The core models are:
- User (represents a person using the system)
- Account (forms a tree for organizing courses)
- Course (Where all the learning content goes)

Users belong to root Accounts via a Pseudonym, which contains their login information, and belong to courses via Enrollment objects. Authorization happens with Role and RoleOverride objects

Exploring the api documentation (https://canvas.instructure.com/doc/api/index.html) and especially the SIS documentation (https://canvas.instructure.com/doc/api/file.sis_csv.html) might be helpful as well

**Comment by dengcen** [comment]
think you so much, simonista.
