### ISSUE TITLE
Flash uploader failure with authenticity token

### ISSUE THREAD

**Issue by jackc** [instructure/canvas-lms#187]
I am experiencing a problem uploading files. The first upload after the browser is started will succeed. Subsequent upload attempts will fail with ActionController::InvalidAuthenticityToken. If I quit and restart the browser I can upload another file. Drag-and-drop file upload works perfectly. I added some logging statements to ApplicationController#verify_authenticity_token and found that the Flash uploader is not sending the authenticity_token with the POST on the failing uploads (or to be precise -- it isn't there by the time it gets to the controller -- I suppose it could be getting lost somewhere in between). I have observed this behavior with both Firefox and Chrome (Internet Explorer 9 won't even let me choose a file). I just updated to the latest stable branch today. This may be the same as issue 151 (https://github.com/instructure/canvas-lms/issues/151) except I am running the latest code base and still have the problem.

    Processing FilesController#create to text (for xxx.xxx.xxx.xxx at 2012-07-27 14:57:01) [POST]
      Parameters: {"Filename"=>"show.html.erb", "attachment"=>{"folder_id"=>"5", "unattached_attachment_id"=>"50"}, "folder"=>"/courses/13/5", "action"=>"create", "Upload"=>"Submit Query", "content-type"=>"text/rhtml", "acl"=>"private", "Policy"=>"eyJhdHRhY2htZW50X2lkIjo1MCwiY29uZGl0aW9ucyI6W3siYnVja2V0Ijoibm8tYnVja2V0In0seyJrZXkiOiIvdmFyL3d3dy9pbGVzaV9jYW52YXMvcmVsZWFzZXMvMjAxMjA3MjcxNTQ3MDAvdG1wL2ZpbGVzLzAwMDAvMDA1MC9zaG93Lmh0bWwuZXJiIn0seyJhY2wiOiJwcml2YXRlIn0sWyJzdGFydHMtd2l0aCIsIiRGaWxlbmFtZSIsIiJdLFsic3RhcnRzLXdpdGgiLCIkZm9sZGVyIiwiIl0sWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMSwxMDczNzQxODI0MF0seyJzdWNjZXNzX2FjdGlvbl9zdGF0dXMiOiIyMDEifSx7ImNvbnRlbnQtdHlwZSI6InRleHQvcmh0bWwifSx7InBzZXVkb255bV9pZCI6MX1dLCJleHBpcmF0aW9uIjoiMjAxMi0wNy0yN1QyMDoyNzowMVoifQ==", "success_action_status"=>"201", "file"=>#<File:/tmp/RackMultipart27476-0>, "format"=>"text", "course_id"=>"13", "controller"=>"files", "key"=>"/var/www/ilesi_canvas/releases/20120727154700/tmp/files/0000/0050/show.html.erb", "check_quota_after"=>"1", "Signature"=>"lxUfX0SDvuugPj9rdF3raI9aRcg="}

    ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
      app/controllers/application_controller.rb:875:in `verify_authenticity_token'
      app/controllers/application_controller.rb:107:in `set_locale'
      lib/authentication_methods.rb:48:in `load_pseudonym_from_policy'
      /var/www/ilesi_canvas/shared/bundle/ruby/1.8/gems/compass-rails-1.0.2/lib/compass-rails/railties/2_3.rb:9:in `process'
      sass (3.1.20) rails/./lib/sass/../sass/plugin/rack.rb:54:in `call'
      lib/request_context_generator.rb:34:in `call'
      app/middleware/prevent_non_multipart_parse.rb:32:in `call'
      app/middleware/load_account.rb:12:in `call'
      /var/www/ilesi_canvas/shared/bundle/ruby/1.8/gems/encrypted_cookie_store-instructure-1.0.1/lib/encrypted_cookie_store.rb:32:in `call'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/rack/application_spawner.rb:171:in `send'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/rack/application_spawner.rb:171:in `handle_spawn_application'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/utils.rb:479:in `safe_fork'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_server.rb:180:in `start'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/spawn_manager.rb:253:in `spawn_rack_application'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/spawn_manager.rb:246:in `spawn_rack_application'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
      /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.11/helper-scripts/passenger-spawn-server:99

**Comment by claydiffrient** [comment]
@jackc @checkraiser @dpaukste I'm sorry that this has been an issue for you.  I'm also sorry that we've been silent.  I believe this should be resolved in the latest releases.  If it's still causing problems for you check out the new files interface by turning the Better File Browsing feature flag on.  You shouldn't get any of these problems there.  I'm going to close the issue, but if it's still a problem feel free to open it again.
