### ISSUE TITLE
Box-and-whisker plot is not actually a box-and-whisker plot

### ISSUE THREAD

**Issue by Benjamin-L** [instructure/canvas-lms#1871]
The help text says that the score distribution view for an assignment is a box-and-whisker plot (although it says the center line is mean rather than median). The actual display shows only the mean and min/max.

**Comment by max-niederman** [comment]
+1 This is very confusing. Literally unusable.

**Comment by Benjamin-L** [comment]
Looks like there was a previous PR for this (#1139) that got dropped a few years ago waiting on the "Canvas Analytics experience". Any chance of resurrecting it since the student display doesn't seem to have improved since then?

At the very least the help text should be changed to be accurate.
