### ISSUE TITLE
Canvas LMS with Redis

### ISSUE THREAD

**Issue by hieple-13499** [instructure/canvas-lms#1873]
### Summary: Hello everyone, im having troubles with redis. My canvas-lms works correctly without redis. But when i enable start redis, some fuctions seem like to not work as usual. For ex, when i update my password at profile settings page, with redis since i click update button, it redirects to the login page and requires me to log in again for a new session, i think. But without it, it redirect to the profile page and not requires me to log in again.
And sometimes with redis, logging into another user, canvas shows me the cookies requires page or flash the successfully message but not redirect to dashboard.
Have anyone met those issues?
Plz help me, thank you a lot.
Sorry for my bad English

### Steps to reproduce:

 1. Set up canvas with redis
 2. Login

### Additional notes:

![image](https://user-images.githubusercontent.com/74241034/118430021-4ecd7180-b6fd-11eb-9f9d-554ed15edd77.png)

![image](https://user-images.githubusercontent.com/74241034/118430066-6ad11300-b6fd-11eb-9396-4e27ea1340ae.png)

**Comment by ccutrer** [comment]
What is `/login/lms`? That is not a path that is part of Canvas. It seems like Redis probably isn't the root cause, but it could still be exposing some other issue. Are you running another authentication thing on the same server? Are you trying to host Canvas not at the root of a domain? Are you using an actual domain name (as configured in domain.yml)? Have configured the session_store.yml to use something besides encrypted_cookie_store? The Cookies required message is pretty simple logic that you just completed a login, but the session is not available, but sessions aren't (normally) stored in Redis.

**Comment by hieple-13499** [comment]
> What is `/login/lms`? That is not a path that is part of Canvas. It seems like Redis probably isn't the root cause, but it could still be exposing some other issue. Are you running another authentication thing on the same server? Are you trying to host Canvas not at the root of a domain? Are you using an actual domain name (as configured in domain.yml)? Have configured the session_store.yml to use something besides encrypted_cookie_store? The Cookies required message is pretty simple logic that you just completed a login, but the session is not available, but sessions aren't (normally) stored in Redis.

tks for your reply
![image](https://user-images.githubusercontent.com/74241034/118579065-8993e000-b7b7-11eb-8263-75f9f8958d8d.png)
routes.rb, line 748, here is the /login/lms
literally, im trying to host canvas on my local server and i do nothing with session_store
i know that for some reasons redis cannot store the session, but still idk why

**Comment by ccutrer** [comment]
those lines do not exist in canvas. this is what they actually look like: https://github.com/instructure/canvas-lms/blob/a6ea5fa1b284369beea52d704782d260cf4a7f35/config/routes.rb#L752

Which tells me your code has been modified in unknown ways. please try to reproduce with vanilla canvas

and I repeat, canvas does _not_ store sessions in redis

**Comment by hieple-13499** [comment]
> those lines do not exist in canvas. this is what they actually look like:
> 
> https://github.com/instructure/canvas-lms/blob/a6ea5fa1b284369beea52d704782d260cf4a7f35/config/routes.rb#L752
> 
> Which tells me your code has been modified in unknown ways. please try to reproduce with vanilla canvas
> 
> and I repeat, canvas does _not_ store sessions in redis

i just change the route name
every action stays the same
i configure my canvas by following the production start
and when i try to change themes, the theme i choose do not applied immediately, it needs a canvas restart or flush redis data
im still so confused
so sorry for my  annoying issues

**Comment by hieple-13499** [comment]
Try to clear all cache and canvas works fine now
Hope not to run into this problem again.
