### ISSUE TITLE
I am so sorry for accidentally deleted---https://github.com/instructure/canvas-lms/wiki/Production-Start

### ISSUE THREAD

**Issue by dengcen** [instructure/canvas-lms#1888]
### Steps to reproduce:

 1. I have one mistake for Production-Start

### Expected behavior:
 recovery Production-Start
### Actual behavior:
 I have one mistake for deleteing the Production-Start, have somebody recovery it. Thks so much!

**Comment by hkpanchani** [comment]
Anyone has local copy cloned?? I really need it

**Comment by anestores** [comment]
I need it too! Was just in the middle of following it.

**Comment by dengcen** [comment]
I am so sorry!!

**Comment by dengcen** [comment]
I want to optimize a parameter,and want delete one middle status`s tag,but delte all,I really need it,too; pls anyone recovery it 。

**Comment by hkpanchani** [comment]
> 
> 
> I want to optimize a parameter,and want delete one middle status`s tag,but delte all,I really need it,too; pls anyone recovery it 。

Recovered now can you make your changes

**Comment by dengcen** [comment]
thank you  so much!!!

**Comment by dengcen** [comment]
I will to check it again.

**Comment by hkpanchani** [comment]
Can you update production start for deploying automated jobs on separate instance.
I am not sure how we can do that. If you can help me out.
