### ISSUE TITLE
Feature request: 'Reply to' field in error reports

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#189]
It would be great if, when a user sends an email using the help / report a problem form, the email was delivered with the user's email address in the Reply To header. So one could just reply to the email to respond to the user's question.

Thanks.

**Comment by claydiffrient** [comment]
@christopher-b Thanks for the request. I'll pass this along to our product team and see if we can get this prioritized.

**Comment by christopher-b** [comment]
This was changed a few months ago. Thanks.
