### ISSUE TITLE
Errors while running bundle install：pulsar-client

### ISSUE THREAD

**Issue by huangdengpan** [instructure/canvas-lms#1907]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /opt/canvas/vendor/bundle/ruby/2.6.0/gems/pulsar-client-2.6.1.pre.beta.2/ext/bindings
/usr/bin/ruby2.6 -I /usr/lib/ruby/2.6.0 -r ./siteconf20210630-32281-1pg3pv1.rb extconf.rb
creating Makefile

current directory: /opt/canvas/vendor/bundle/ruby/2.6.0/gems/pulsar-client-2.6.1.pre.beta.2/ext/bindings
make "DESTDIR=" clean

current directory: /opt/canvas/vendor/bundle/ruby/2.6.0/gems/pulsar-client-2.6.1.pre.beta.2/ext/bindings
make "DESTDIR="
compiling bindings.cpp
In file included from bindings.cpp:3:0:
message.hpp:8:10: fatal error: pulsar/Client.h: No such file or directory
 #include <pulsar/Client.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:300: recipe for target 'bindings.o' failed
make: *** [bindings.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/canvas/vendor/bundle/ruby/2.6.0/gems/pulsar-client-2.6.1.pre.beta.2 for inspection.
Results logged to /opt/canvas/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/pulsar-client-2.6.1.pre.beta.2/gem_make.out

An error occurred while installing pulsar-client (2.6.1.pre.beta.2), and Bundler cannot continue.
Make sure that 
gem install pulsar-client -v '2.6.1.pre.beta.2' --source 'https://rubygems.org/' succeeds before bundling.

In Gemfile:
  pulsar-client

 **Could anyone help me on this ?**

**Comment by zhuoxl** [comment]
```
export PULSAR_VERSION=2.6.1
export PULSAR_CLIENT_SHA512=90fdb6e3ad85c9204f2b20a9077684f667f84be32df0952f8823ccee501c9d64a4c8131cab38a295a4cb66e2b63211afcc24f32130ded47e9da8f334ec6053f5
export PULSAR_CLIENT_DEV_SHA512=d0cc58c0032cb35d4325769ab35018b5ed823bc9294d75edfb56e62a96861be4194d6546107af0d5f541a778cdc26274aac9cb7b5ced110521467f89696b2209
```

```
cd "$(mktemp -d)" && \
    curl -SLO 'http://archive.apache.org/dist/pulsar/pulsar-'$PULSAR_VERSION'/DEB/apache-pulsar-client.deb' && \
    curl -SLO 'http://archive.apache.org/dist/pulsar/pulsar-'$PULSAR_VERSION'/DEB/apache-pulsar-client-dev.deb' && \
    echo $PULSAR_CLIENT_SHA512 '*apache-pulsar-client.deb' | shasum -a 512 -c -s - && \
    echo $PULSAR_CLIENT_DEV_SHA512 '*apache-pulsar-client-dev.deb' | shasum -a 512 -c -s - && \
    apt install ./apache-pulsar-client*.deb && \
    rm ./apache-pulsar-client*.deb && \
    rm /usr/lib/libpulsarnossl.so* && \
    rm /usr/lib/libpulsar.a && \
    rm /usr/lib/libpulsarwithdeps.a
```

Maybe can help you

**Comment by huangdengpan** [comment]
@zhuoxl 
Thank you very much , i will try.

**Comment by Git-Leon** [comment]
> 
> 
> ```
> export PULSAR_VERSION=2.6.1
> export PULSAR_CLIENT_SHA512=90fdb6e3ad85c9204f2b20a9077684f667f84be32df0952f8823ccee501c9d64a4c8131cab38a295a4cb66e2b63211afcc24f32130ded47e9da8f334ec6053f5
> export PULSAR_CLIENT_DEV_SHA512=d0cc58c0032cb35d4325769ab35018b5ed823bc9294d75edfb56e62a96861be4194d6546107af0d5f541a778cdc26274aac9cb7b5ced110521467f89696b2209
> ```
> 
> ```
> cd "$(mktemp -d)" && \
>     curl -SLO 'http://archive.apache.org/dist/pulsar/pulsar-'$PULSAR_VERSION'/DEB/apache-pulsar-client.deb' && \
>     curl -SLO 'http://archive.apache.org/dist/pulsar/pulsar-'$PULSAR_VERSION'/DEB/apache-pulsar-client-dev.deb' && \
>     echo $PULSAR_CLIENT_SHA512 '*apache-pulsar-client.deb' | shasum -a 512 -c -s - && \
>     echo $PULSAR_CLIENT_DEV_SHA512 '*apache-pulsar-client-dev.deb' | shasum -a 512 -c -s - && \
>     apt install ./apache-pulsar-client*.deb && \
>     rm ./apache-pulsar-client*.deb && \
>     rm /usr/lib/libpulsarnossl.so* && \
>     rm /usr/lib/libpulsar.a && \
>     rm /usr/lib/libpulsarwithdeps.a
> ```
> 
> Maybe can help you

I first exected `sudo -s` to ensure I ran as `root` user; otherwise the above operations failed on my end.
Further investigation is needed, but for now this is a needed milestone.
Excellent. Thank you for this!

**Comment by MIbtehajNasar** [comment]
I faced the same issue on mac OS Monterey, so fixed this issue with

`brew install libpulsar`

**Comment by rahuljadhavbsft** [comment]
@Git-Leon Do we have any other solution for this? The above ones are not working for me.

**Comment by ccutrer** [comment]
Canvas no longer relies on pulsar-client (since Jan. 2022).

**Comment by lecuong35** [comment]
> @Git-Leon Do we have any other solution for this? The above ones are not working for me.

Did u find the solution? Please, tell me

**Comment by huangdengpan** [comment]
bundle config set --local path 'vendor/bundle'
bundle config set --local without 'pulsar'
cd   /opt/canvas/vendor/bundle/ruby/2.6.0/gems/pulsar-client-2.6.1.pre.beta.2/bin
./setup
bundle install

@lecuong35

**Comment by lecuong35** [comment]
> bundle config set --local path 'vendor/bundle' bundle config set --local without 'pulsar' cd /opt/canvas/vendor/bundle/ruby/2.6.0/gems/pulsar-client-2.6.1.pre.beta.2/bin ./setup bundle install
> 
> @lecuong35

thanks, but it don't work for me <3. I use first solution again and it run.

**Comment by adar5h** [comment]
Is there any other workaround for this? The above solution didn't work for me. I'm using Rails 7.1.4 with Ruby 3.3.0
