### ISSUE TITLE
Production deployment with docker

### ISSUE THREAD

**Issue by Sparkenstein** [instructure/canvas-lms#1921]
### Summary:
The development setup worked quiet well with Linux, had some issues on Mac, the scripts look outdated especially where we check if some tool exists or not like Dinghy.

So I tried setting up on Debian stretch, everything worked really well with just one command. Now I want to install it on production, but the steps for production given in the wiki are manual. Is there docker image available for production deployment? 

Or any extra steps that I can take to convert dev setup to prod, whichever works

**Comment by dylanjamesdev** [comment]
bump

**Comment by ssilverm** [comment]
What was the one command you used to get it up and running on Stretch?

**Comment by kingjuk** [comment]
bump

**Comment by simonista** [comment]
There is not currently a supported docker image available for production deployment.
