### ISSUE TITLE
Change request: Maintain course published status when removed/added via SIS import

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#193]
We've been having problems with our SIS imports, where we occasionally, accidentally send empty courses lists. Because we're in batch mode, all courses are deleted. When we re-run the SIS import with the full list of courses, they are all restored exactly as they were, except that any courses that were previously published are now unpublished. All our instructors have to re-publish their courses. 

It would be nice if the import process could remember the published state of the course and restore it to that state after being restored. Thanks.

**Comment by claydiffrient** [comment]
@christopher-b Is this still happening for you?  If it still is the case I'm happy to send it along to the proper team to have it prioritized.

**Comment by christopher-b** [comment]
Well, we're no longer accidentally sending empty SIS imports, so I'm not sure if it's still happening. Feel free to close the issue, although I still think it would be good to fix this if it's still happening.

**Comment by claydiffrient** [comment]
Okay.  That sounds good.  I'm going to go ahead and close the issue, but we'll keep an eye out for this problem in the future.
