### ISSUE TITLE
messages_YEAR_N tables are not created

### ISSUE THREAD

**Issue by nathanielb** [instructure/canvas-lms#1945]
### Summary:

Emails are not going out (broken record I know) but after some digging this one might be a different issue. The messages_2021_39 table, for example, is not being created then I end up with an error like:

ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "public.messages_2021_39" does not exist

If I create that table manually (or rename an older one and remove the constraints) the email is delivered successfully.

### Steps to reproduce:

I'm not sure how to reproduce or what caused the error to begin with.

### Expected behavior:

It looks like the table should be created automatically?

### Actual behavior:

It looks like the messages_YEAR_N tables are not being created and that causes email failure.

### Additional notes:

I'm still digging around but in app/models/message.rb I found a note including messages_2020_35.

This is happening on an older site ~2019 and an upgraded version of the site (most recent stable version to date 09-28-2021).

**Comment by roor0** [comment]
you can open a rails console and run `Messages::Partitioner.process` to manually create the tables that are missing. Typically these are created with a delayed_job
