### ISSUE TITLE
SpeedGrader launches LTI apps with the wrong `resource_link_id`

### ISSUE THREAD

**Issue by seanh** [instructure/canvas-lms#1952]
### Summary:

When launching an external tool assignment in SpeedGrader Canvas passes the assignment's `context_id` as the value of the `resource_link_id` parameter.

In combination with https://github.com/instructure/canvas-lms/issues/1975 this means that Canvas doesn't pass _any_ unique ID for an assignment when the assignment is launched in SpeedGrader.

### Steps to reproduce:

 1. Create an external tool assignment
 2. Launch the assignment and note the values of the `resource_link_id` and `context_id` LTI launch params as received by the external tool
 3. Launch the same assignment in SpeedGrader and note the values of the `resource_link_id` and `context_id` params again

### Expected behavior:

The external tool should receive the same `resource_link_id` param when launched in SpeedGrader as when the same assignment is launched outside of SpeedGrader.

### Actual behavior:

When launched in SpeedGrader the `resource_link_id` and `context_id` params have the same value. They're both set to the value of the `context_id` param from the non-SpeedGrader launch. 

### Additional notes:

My understanding is that `context_id` is a unique ID for the course whereas `resource_link_id` is a unique ID for the assignment. If you create multiple external tool assignments in the same course the LTI app will receive the same `context_id` whenever any of these assignments is launched (because the assignments are in the same course) but will receive a different `resource_link_id` for each assignment.

If SpeedGrader launches don't include the assignment's unique `resource_link_id` (because they're using the `context_id` as the value for the `resource_link_id` param) then LTI apps have no way of knowing which assignment is being launched in SpeedGrader. For example the assignment's configuration may be stored in the LTI app's database and keyed by the `resource_link_id`, so the LTI app can't find the configuration in its DB.

**Comment by Ardena** [comment]
This is valid issue in Canvas, and there is an internal ticket open to address this for LTI 1.3 tools. However there are not any current plans to change this behavior for LTI 1.1 tools. There is concern that changing the behavior for 1.1 this late in its life cycle could cause issues for existing vendors.

**Comment by Ardena** [comment]
Since launches from SpeedGrader exclusively point to URLs given by the LTI tool provider for the user's submissions, our LTI 1.1 providers have previously used their own unique URL information to link back to the correct content.
