### ISSUE TITLE
Unsupported: yarn install --pure-lockfile (from Canvas Depenencies)!

### ISSUE THREAD

**Issue by KynnedySimone** [instructure/canvas-lms#1953]
### Summary: 

`yarn install --pure-lockfile` is unsupported on my device/current yarn installation

### Steps to reproduce:

 1. navigate to the Canvas application root
 2. install all of the Canvas dependencies using Bundler.

### Expected behavior: 

Dependencies install without error

### Actual behavior:

`unsupported option name --pure-lockfile`

### Additional notes:

I am following the quick start instructions for Canvas, and whenever I try to run` yarn install --pure-lockfile`, I get errors on my computer. I a using a virtual machine running the newest version of Ubuntu. I was able to install the new version of Yarn perfectly fine, but running the `--pure-lockfile` command gives me this error notice: 

`unsupported option name --pure-lockfile`

I've looked the error up online extensively, reinstalled yarn multiples times, but I have not found. I cannot do the next steps for the Data Setup and canvas default configurations because the terminal will run yarn and I will get the same lock file error. 

Could someone please help me?

**Comment by Ardena** [comment]
You can skip the flag and just do `yarn install` (or even just `yarn`).  The flag isn't required, though you may occasionally see differences in your compiled files without.  (We try to make sure the lock file matches, though, so they should get resolved).

I saw some references to the possibility that this might be an option that yarn got rid of (in favor of doing it as the default), but it still works for me, and I don't see anything for this on the actual yarn documentation.  What version of yarn are you using?  (I'm on 1.22.0 and it still works for me.)

I've also seen some issues for Debian about installing the wrong yarn.  That theoretically shouldn't be an issue with Ubuntu, but try just `yarn install` and make sure it's actually installing the npm packages.
