### ISSUE TITLE
Users count lost for "All Sections" announcements and discussions

### ISSUE THREAD

**Issue by GeoffreyTrang** [instructure/canvas-lms#1962]
### Steps to reproduce:

Visit a course's Announcements page, the Discussions page, an individual announcement, or an individual discussion.

### Additional notes:
Two ways to fix this:

- Revert https://github.com/instructure/canvas-lms/commit/9614a5fbff8754e6e4132cc1888a81a3395bbc69.
- Append the number of users to the end of the "All Sections" text, so if a course has 4 users, the text would say "All Sections (4 Users)." A benefit of this is that the count is still visible even on a tablet or mobile device.

**Comment by davishyer** [comment]
Hi @GeoffreyTrang, thanks for opening this issue. Given the change that you link to in your recommended revert, this does not appear to be an issue but rather a feature request. If you would like to propose a change in functionality, feel free to open a pull request with the changes and our product team can evaluate if that is something they would like to include into Canvas. If that's not something you're able to do, you can also create a post in the [Canvas Community](https://community.canvaslms.com/t5/Idea-Conversations/idb-p/ideas).
