### ISSUE TITLE
using docker, http is redirected to https and fails

### ISSUE THREAD

**Issue by jrichardsz** [instructure/canvas-lms#1963]
### Summary:

After a success `docker-compose up -d` when I enter to **http://localhost** I'm redirected to **https://localhost/** and fails

### Steps to reproduce:

 1. Clone this repository
 2. perform `docker-compose up -d`
 3. go to http://localhost using some browser

### Expected behavior:

Load the main page of canvas

### Actual behavior:

https://localhost does not work.

Here the log of canvas_web container

```
/usr/src/nginx/nginx.conf: generated.
/usr/src/nginx/main.d/env.conf: generated.
[ N 2021-10-30 00:12:13.2282 12/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2021-10-30 00:12:13.2555 15/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-10-30 00:12:13.2556 15/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-10-30 00:12:13.2696 15/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 15
2021/10/30 00:12:15 [error] 27#27: *1 directory index of "/usr/src/app/public/" is forbidden, client: 127.0.0.1, server: app.invalid, request: "HEAD / HTTP/1.1", host: "app.invalid"
127.0.0.1 - - [30/Oct/2021:00:12:15 +0000] "HEAD / HTTP/1.1" 403 0 "-" "Passenger Prespawn Script"
[ N 2021-10-30 00:12:16.3871 15/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
```

### Additional question:

Is there any option to startup the canvas without https, just http for local testing?

Thanks

**Comment by Ardena** [comment]
Using docker with Canvas, Mac users (using dinghy-http-proxy) would hit http://canvas.docker to go to the login page, and Linux users (using Traefik) would hit (I believe) http://web.canvas.docker.  It's defined in the docker-compose.override.yml file as a virtual_host.  I'm not sure what your set up is, but I am not familiar with a set up of using localhost to access Canvas inside of Docker.

You should ensure you are using the docker-compose.overrides.yml file and try to access Canvas through the virtual host URL.
