### ISSUE TITLE
Big Sur - documented solutions to thrift error do not work.

### ISSUE THREAD

**Issue by drscottlobo** [instructure/canvas-lms#1969]
### Summary:

I'm running OS Big Sur and Ruby 2.7.2. During bundle install I'm getting the thrift error as mentioned in the docs. I've tried applying both solutions listed: 

`bundle config build.thrift --with-cppflags='-D_FORTIFY_SOURCE=0'`

And 

`gem install thrift -v 0.8.0 -- --with-cppflags=\"-D_FORTIFY_SOURCE=0 -Wno-shift-negative-value\"`

Neither seems to work on Big Sur. *Note on bundler --without seems to be deprecated. 

### Actual behavior:

Error listed is:
```
Gem files will remain installed in /Users/lobomacpro/.rvm/gems/ruby-2.7.2/gems/thrift-0.9.3.0 for inspection.
Results logged to /Users/lobomacpro/.rvm/gems/ruby-2.7.2/extensions/x86_64-darwin-20/2.7.0/thrift-0.9.3.0/gem_make.out

An error occurred while installing thrift (0.9.3.0), and Bundler cannot continue.
Make sure that `gem install thrift -v '0.9.3.0' --source 'https://rubygems.org/'` succeeds before bundling.
```

If I run gem install thrift -v '0.9.3.0' --source 'https://rubygems.org/' I get the following: 

```
ERROR:  Error installing thrift:
	ERROR: Failed to build gem native extension.

    current directory: 
checking for strlcpy() in string.h... yes
creating Makefile
make "DESTDIR=" clean
make "DESTDIR="
compiling binary_protocol_accelerated.c
binary_protocol_accelerated.c:404:68: error: '(' and '{' tokens introducing statement expression appear in different macro expansion contexts [-Werror,-Wcompound-token-split-by-macro]
  VALUE thrift_binary_protocol_class = rb_const_get(thrift_module, rb_intern("BinaryProtocol"));
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/*****/.rvm/rubies/ruby-2.7.2/include/ruby-2.7.0/ruby/ruby.h:1847:23: note: expanded from macro 'rb_intern'
        __extension__ (RUBY_CONST_ID_CACHE((ID), (str))) : \
                      ^
binary_protocol_accelerated.c:404:68: note: '{' token is here
  VALUE thrift_binary_protocol_class = rb_const_get(thrift_module, rb_intern("BinaryProtocol"));                                          \
    ^
binary_protocol_accelerated.c:404:68: error: '}' and ')' tokens terminating statement expression appear in different macro expansion contexts [-Werror,-Wcompound-token-split-by-macro]
  VALUE thrift_binary_protocol_class = rb_const_get(thrift_module, rb_intern("BinaryProtocol"));
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_protocol_accelerated.c:404:68: note: ')' token is here
  VALUE thrift_binary_protocol_class = rb_const_get(thrift_module, rb_intern("BinaryProtocol"));
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       ^
binary_protocol_accelerated.c:406:68: error: '(' and '{' tokens introducing statement expression appear in different macro expansion contexts [-Werror,-Wcompound-token-split-by-macro]
  VERSION_1 = rb_num2ll(rb_const_get(thrift_binary_protocol_class, rb_intern("VERSION_1")));
                                                                   ^~~~~~~~~~~~~~~~~~~~~~

                      ^
binary_protocol_accelerated.c:406:68: note: '{' token is here
  VERSION_1 = rb_num2ll(rb_const_get(thrift_binary_protocol_class, rb_intern("VERSION_1")));
                             
                              ^~~~~~~~~~~~~~~~~~~~~~

                                                       
10 errors generated.
make: *** [binary_protocol_accelerated.o] Error 1

make failed, exit code 2

```        

### Additional notes:

It would be great to find a solution to this. Or if there is one, that the docs would be updated with the latest solution. 

Thanks!

**Comment by maths22** [comment]
I recommend just installing with `bundle install --without cassandra` unless you are attempting to actively developing against cassandra.  Please let me know if that doesn't work for you.

**Comment by drscottlobo** [comment]
Wow, thanks for the incredibly fast reply! Unfortunately that did not work. I got the same error. Looks like cassandra is a dependency of two other packages (see below), is it safe to try --without audits? 

audits was resolved to 0.1.0, which depends on
    event_stream was resolved to 0.1.0, which depends on
      canvas_cassandra was resolved to 0.1.0, which depends on
        cassandra-cql was resolved to 1.2.3, which depends on
          thrift_client was resolved to 0.9.3, which depends on
            thrift

Thanks!

**Comment by maths22** [comment]
Well that is unfortunate.  Sadly I don't think that method will then work.   I'd try:
```
gem install thrift -v 0.9.3.0 -- --with-cppflags="-Wno-compound-token-split-by-macro"
```
(That works for me, so hopefully that works for you)

**Comment by drscottlobo** [comment]
Thanks Jacob! I think that worked! (At least up to a successful bundle install ;)

Steps:

1. I made a new clone of the Canvas repository just to be safe
2. It looks like the bundler version went up slightly in the Gem file to 2.2.30, installed that version of bundler and then ran 'bundle install --without pulsar', it gave the usual thrift error
3.  Then install worked correctly after adding your solution below:

```
gem install thrift -v 0.9.3.0 -- --with-cppflags="-Wno-compound-token-split-by-macro"
```

Thanks so much for your help! Perhaps adding another solution to the Docs mentioning the same problem with your solution for Big Sur could help some others?
