### ISSUE TITLE
Canvas sends an empty `ext_lti_assignment_id` when creating on assignment from the Modules tab

### ISSUE THREAD

**Issue by seanh** [instructure/canvas-lms#1973]
### Summary:

Usually when you create an external tool assignment Canvas includes an `ext_lti_assignment_id` in the LTI launch params. But if you create an external tool assignment from the _Modules_ tab Canvas passes an empty string as the value for `ext_lti_assignment_id`. Since Canvas never passes a `resource_link_id` when creating an assignment this means that Canvas fails to pass _any_ unique assignment ID when creating an assignment on the _Modules_ tab.

### Steps to reproduce:

On a course's **Modules** tab click the <kbd>+</kbd> button, select "External tool" from the dropdown menu, and select an external tool:

https://user-images.githubusercontent.com/22498/142014868-0dd3810e-6727-461f-abdb-5902ece83399.mp4

### Expected behavior:

When Canvas launches the external tool it should include an `ext_lti_assignment_id` parameter that uniquely identifies the assignment.

### Actual behavior:

The LTI launch from Canvas contains `ext_lti_assignment_id: ""`.

### Additional notes:

There are two other ways (that I know of) to create an external tool assignment in Canvas. Both of these methods result in an LTI launch with no `resource_link_id` parameter, but with a non-empty `ext_lti_assignment_id` parameter.

You can use the `[ Create assignment ]` item like this:

https://user-images.githubusercontent.com/22498/142015614-3e9344d4-efdd-4376-86e7-24ddba73941d.mp4

Or you can create an assignment from the **Assignments** tab instead of the **Modules** tab, like this:

https://user-images.githubusercontent.com/22498/142015833-964c0273-97c7-4ff9-ae22-a6567345e559.mp4

**Comment by Ardena** [comment]
The reproduction steps shared here do not create a gradable item (Canvas assignment), so we would not expect ext_lti_assignment_id to be populated.
​
A Canvas course has two LTI resource types:
- [an assignment](https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-add-an-assignment-using-an-external-app/ta-p/656)
- [module item](https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-add-an-external-tool-as-a-module-item/ta-p/1146)

Only assignments are gradable, so assignment/grade related parameters will not be included when a module item is launched.

**Comment by seanh** [comment]
@Ardena to clarify Canvas is actually including this parameter in the launch params:

```
ext_lti_assignment_id: ""
```

So there **is** an `ext_lti_assignment_id` param but its value is the empty string.
