### ISSUE TITLE
External tool assignments created as module items don't receive an `ext_lti_assignment_id` param

### ISSUE THREAD

**Issue by seanh** [instructure/canvas-lms#1974]
### Summary:

If you create an external tool assignment from a course's **Modules** tab rather than from its **Assignments** tab then when you open the assignment and Canvas launches the external tool Canvas doesn't pass an `ext_lti_assignment_id` parameter to the external tool.

### Steps to reproduce:

On a course's **Modules** tab click the <kbd>+</kbd> button, select "External tool" from the dropdown menu, and select an external tool:

https://user-images.githubusercontent.com/22498/142014868-0dd3810e-6727-461f-abdb-5902ece83399.mp4

### Expected behavior:

When Canvas launches the external tool it should include an `ext_lti_assignment_id` parameter that uniquely identifies the assignment.

### Actual behavior:

The LTI launch from Canvas does not include an `ext_lti_assignment_id` parameter.

**Comment by Ardena** [comment]
This seems to be the same question as https://github.com/instructure/canvas-lms/issues/1973

**Comment by seanh** [comment]
Hi @Ardena, these are two separate issues:

1. When doing the content item selection launch while _creating_ a module item Canvas _does_ include the `ext_lti_assignment_id` param but its value is an empty string. That's https://github.com/instructure/canvas-lms/issues/1973

2. When _launching_ a module item (that you have already created) there's no `ext_lti_assignment_id` param at all. That's this issue (https://github.com/instructure/canvas-lms/issues/1974)
