### ISSUE TITLE
SpeedGrader launches LTI apps without an `ext_lti_assignment_id`

### ISSUE THREAD

**Issue by seanh** [instructure/canvas-lms#1975]
### Summary:

When launching an external tool assignment in SpeedGrader Canvas does includevvvvvvv `ext_lti_assignment_id` parameter to the LTI launch params

In combination with https://github.com/instructure/canvas-lms/issues/1952 this means that Canvas doesn't pass _any_ unique ID for an assignment when the assignment is launched in SpeedGrader.

### Steps to reproduce:

 1. Create an external tool assignment
 2. Launch the assignment. One of the LTI launch params that Canvas will pass to the external tool is an `ext_lti_assignment_id` that uniquely identifies the assignment
 3. Launch the same assignment in SpeedGrader. The `ext_lti_assignment_id` is missing from the launch params that Canvas passes to the external tool

### Expected behavior:

The external tool should receive the same `ext_lti_assignment_id` param when launched in SpeedGrader as when the same assignment is launched outside of SpeedGrader.

### Actual behavior:

When launched in SpeedGrader the `ext_lti_assignment_id` param is missing.

**Comment by Ardena** [comment]
When a tool is launched from SpeedGrader, it is an independent LTI resource distinct from the Assignment. Therefore it shouldn't necessarily include the assignment's identifying information. Any change to this behavior should go through Instructure's standard feature-request workflow.

**Comment by seanh** [comment]
@Ardena SpeedGrader actually *does* include the assignment (or "resource link")'s identifying information in the launch params currently. SpeedGrader launches include the `resource_link_title` param (the title of the assignment), the `resource_link_description` param (description of the assignment) and the `resource_link_id` param (the unique ID of the assignment, although this currently has the wrong value, see: https://github.com/instructure/canvas-lms/issues/1952).
