### ISSUE TITLE
Canvas redirects OAuth clients to themselves

### ISSUE THREAD

**Issue by seanh** [instructure/canvas-lms#1976]
### Summary:

If an OAuth client makes an invalid request to Canvas's access token endpoint (`POST /login/oauth2/token`) (for example maybe the request contains an invalid `code`) then Canvas responds with a 302 redirect _to the client's own `redirect_url`_. This instructs the client server to make an HTTP request to itself which is incorrect (violates the OAuth 2 spec) and can trigger very confusing behavior from unsuspecting clients.

### Steps to reproduce:

Make a `POST` request to Canvas's `/login/oauth2/token` endpoint with (for example) a correct `grant_type`, `client_id`, `client_secret` and `redirect_uri` but an **incorrect** `code`:

```terminal
$ curl -X POST 'https://FOOBAR.instructure.com/login/oauth2/token?grant_type=authorization_code&client_id=***&client_secret=***&code=foo&redirect_uri=http%3A%2F%2Flocalhost%3A8001%2Fcanvas_oauth_callback'
```

### Expected behavior:

Canvas should respond with an HTTP 400 with a JSON body containing an `error` parameter whose value is an OAuth 2 error code such as `invalid_grant`, as described in [section 5.2 of the OAuth spec](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2).

The request that the client is making in this case is called an **Access Token Request** in the OAuth spec: <https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3>. According to the spec the [Access Token Response](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.4) section of the spec:

> If the request client authentication failed or is invalid, the authorization server returns an error response as described in [Section 5.2](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2).

### Actual behavior:

Canvas responds with a 302 redirect whose location header directs the LTI app to make a request to itself.

Redirecting to the client's `redirect_uri` isn't an appropriate response to an access token request. The `redirect_uri` is meant for the authorization server to redirect the _user agent_ (browser) to when the client directs the browser to make the authorization request, see: https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1

**Comment by Ardena** [comment]
We have opened a ticket internally to confirm if there are any issues with our error handling, and make any needed corrections.
