### ISSUE TITLE
Mixed messages from Canvas when passing back a score of 0 to Canvas via LTI Advantage

### ISSUE THREAD

**Issue by kreut** [instructure/canvas-lms#1977]
### Summary: 

When passing back a grade of 0 using LTI Advantage, Canvas accepts the grade (as I think it should), but marks the passed back assignment as something that needs to be graded.  This can be confusing to the instructors as they are unsure whether the grade was passed back or not. 

### Steps to reproduce:

Use LTI Advantage 1.3 to pass back the grade

### Expected behavior:

I would expect that receiving a score of 0 would be valid and be considered "graded".

### Actual behavior:

Canvas makes it looks like the assignment still needs to be graded
<img width="526" alt="Screen Shot 2021-11-17 at 6 53 17 AM" src="https://user-images.githubusercontent.com/909129/142224527-524b6f86-8b1e-4088-aebb-c756cf605a8a.png">
<img width="389" alt="Screen Shot 2021-11-17 at 6 51 20 AM" src="https://user-images.githubusercontent.com/909129/142224537-868df933-bfcb-43bb-9eb6-4a7c406318a5.png">

## But if you look at the header, the student has a score of 0/1 and it is marked as graded:

<img width="1292" alt="Screen Shot 2021-11-17 at 6 51 36 AM" src="https://user-images.githubusercontent.com/909129/142224531-a4f6bbaf-515f-4659-b5a9-497085bd1c54.png">

**Comment by Ardena** [comment]
The SpeedGrader image is showing that the student is not graded.  If the student was graded, it should show a 0 in the box under "grade out of 10".  The header is showing that 0 out of 1 student are graded, and you are viewing student 1 of 1.

It looks to me like the grade didn't go through at all.

**Comment by kreut** [comment]
Hi Ardena,

My apologies!  You are correct in that my example is not highlighting the issue in the correct way.  What I should have done was to state that Canvas is sending back this as a message:

https://some-school.instructure.com/api/lti/courses/123/line_items/456/results/789

(numbers made up)

This would indicate that the grade pass back was successful; when it's not successful, Canvas sends back an error.  To me, this is evidence that the score was received by Canvas yet it's being displayed in Canvas as something that needs to be graded.

**Comment by Ardena** [comment]
Sorry, I didn't notice this update.  We have been working on giving better error messages when things are failing.  I'm not sure if I've seen this one, but that does not sound like a great way of letting you know there was a failure. :)
