### ISSUE TITLE
Canvas doesn't pass `resource_link_id` when creating or editing external tool assignments

### ISSUE THREAD

**Issue by seanh** [instructure/canvas-lms#1978]
### Summary:

While creating an external tool assignment using an external tool that supports LTI "content item selection" Canvas doesn't include the `resource_link_id` in the LTI launch params for the content item selection launch

### Steps to reproduce:

1. Go to `https://YOUR_SITE.instructure.com/courses/<COURSE_ID>/assignments/new`
2. Under _Submission type_ select _External tool_ then click _Find_
3. Select an external tool that supports LTI content item selection
4. Canvas launches the external tool, doing a content item selection launch

### Expected behavior:

Canvas should include the `resource_link_id` param.

### Actual behavior:

There's no `resource_link_id` in the launch params.

If you continue and create the assignment then when you launch the created assignment (doing a basic LTI launch) the `resource_link_id` will be included. But if you then edit the assignment the `resource_link_id` will again be missing from the content item selection launch when editing.

### Additional notes:

I suspect there may be some logic to this since, during the assignment creation process, the assignment (or "resource link") hasn't actually been created yet so there is no `resource_link_id`.

Nonetheless I think Canvas could generate the `resource_link_id` that *will* be used when/if the user finishes creating the assignment and could include that `resource_link_id` in the launch params. I'm guessing that `resource_link_id`'s are UUIDs so there won't be any collisions.

This would be convenient for LTI apps because during the content item selection launch we could save the assignment configuration in our DB keyed by the `resource_link_id` and then in subsequent basic LTI launches we could look up the assignment configuration using the `resource_link_id`.

It would be especially convenient when a user _edits_ an assignment if Canvas could include the `resource_link_id` in the launch params as then we could know which assignment configuration (keyed by `resource_link_id`) to look up and modify in our DB.

I've noticed that Canvas _does_ pass a different ID: `ext_lti_assignment_id`. In theory LTI apps could use this ID instead of the `resource_link_id`. But this complicates code and harms compatibility with other LMS's, and Canvas's `ext_lti_assignment_id` has a number of issues: https://github.com/instructure/canvas-lms/issues/1975, https://github.com/instructure/canvas-lms/issues/1974, https://github.com/instructure/canvas-lms/issues/1973.

It would be really nice if we could just use the `resource_link_id` all the time and forget about `ext_lti_assignment_id`.

**Comment by Ardena** [comment]
https://github.com/instructure/canvas-lms/issues/1978
​
The Content-Item specification explicitly states that a Tool Consumer (Canvas) should not include this information:
https://www.imsglobal.org/specs/lticiv1p0/specification
section 3.3.1, under "Additional Fields"
*"The following parameters should not be passed: `resource_link_id`"*
 
Alternatively however, the `ext_lti_assignment_id` parameter is included during the resource selection launch, and may be a viable option for a tool to leverage.
