### ISSUE TITLE
Microsoft Team sync issue in Canvas

### ISSUE THREAD

**Issue by ror-prem** [instructure/canvas-lms#1985]
### Summary: I am trying to integrate Microsoft Teams in canvas. I have created an microsoft office free admin account and added my Tenant Name , Login Attribute, Active Directory Lookup Attribute. 
![Screenshot from 2021-12-11 11-19-21](https://user-images.githubusercontent.com/89960683/145665777-1db9ffd1-e231-4dfd-b101-b60e2482c420.png)
### Steps to reproduce:
1. Dashboard-> Admin -> Settings -> Integrations
2. Add details
3. Turn on toogle
4. Click on Grant Access

### Expected Behaivour:
Successful Mircosoft-Team Sync

### Actual Behaiviour:
AADSTS50000: There was an error issuing a token or an issue with our sign-in service.

![Screenshot from 2021-12-11 11-21-45](https://user-images.githubusercontent.com/89960683/145665833-a3775f76-833b-4026-a5db-e09f12a7a259.png)

### Here is documentation I followed: https://docs.microsoft.com/en-us/microsoft-365/lti/teams-meetings-with-canvas?view=o365-worldwide

Please suggest what i can do to make it work?

**Comment by Ardena** [comment]
Since the error is a Microsoft error and not a Canvas error and we don't have access to the results of the API call either from the Canvas end or from the Microsoft end, I think you will have to contact them for assistance.

**Comment by Ardena** [comment]
Just noticed: https://docs.microsoft.com/en-us/microsoft-365/lti/teams-meetings-with-canvas?view=o365-worldwide says "Your tenant must have an Microsoft Education license."  You specified that your account was a free account.  So it will not have the correct permission.
