### ISSUE TITLE
How do i get Inherited Keys in canvas?

### ISSUE THREAD

**Issue by ror-prem** [instructure/canvas-lms#1988]
### Steps to reproduce:

 1. Dashboard
 2. Admin
 3. Settings
 4. Developer Keys
 5. Inherited

### Expected behavior:
<img width="500" alt="interited_tab" src="https://user-images.githubusercontent.com/89960683/145987284-a813e60c-ec71-4e98-a8f5-fe0d17d0c00c.png">

### Actual behavior:
![Screenshot from 2021-12-14 16-30-58](https://user-images.githubusercontent.com/89960683/145987144-7757e36d-74ff-4206-9e6f-251c256f673a.png)

**Comment by Ardena** [comment]
If you are a Canvas customer (as the 1700~ suggests in the screenshot), then it should already be available to you, and if it is not, you will need to contact our support team directly.  If you host your own Canvas, you'll need to get an LTI key and secret from Microsoft for it and install it in the developer keys section either your Siteadmin account or your regular root account.

**Comment by Wandimi** [comment]
Sure got the same error and this is what they said
"Hi Wandimi,
Thank you for your recent communication with our team.
I understand you are looking to integrate Microsoft applications with Canvas LMS through LTI apps.
At this stage, the self-hosted system only allows limited administrative features.
If you were looking to add this feature, we would need to have a discussion regarding the adoption of a premium Canvas subscription.
Please see a PDF below, which highlights the differences between the free vs the paid versions.
Please let me know, should you wish to explore a premium Canvas platform, and I'd be happy to ask you some questions about your use case to understand if it would be the right fit for you."
