### ISSUE TITLE
Wrong bundle version

### ISSUE THREAD

**Issue by damianoognissanti** [instructure/canvas-lms#2002]
### Summary:

To compile assets for Canvas one must use bundler version 2.2.19-2.2.30, i.e.

`RAILS_ENV=production bundle _2.2.19_ exec rake canvas:compile_assets`

When starting passenger I received the error `superclass mismatch for class StringIO (TypeError)` which seems to be related to a bug in bundler 2.2.19 and 2.2.30 (I tested both). The only thing that worked was to remove the old bundler versions and install bundler 2.3.5 instead (even though it couldn't be used in the compilation).

### Steps to reproduce:

 1. RAILS_ENV=production bundle _2.2.19_ exec rake canvas:compile_assets
 2. Try to start Passenger

### Expected behavior:

Passenger starts

### Actual behavior:

Passenger does not start because of `superclass mismatch for class StringIO (TypeError)`

**Comment by ccutrer** [comment]
Latest Canvas uses bundler 2.3.26
