### ISSUE TITLE
Scanning a malformed QR code changes my canvas default language

### ISSUE THREAD

**Issue by nobody5050** [instructure/canvas-lms#2008]
### Summary:
The title is not a joke, and I’m honestly hoping that I’m going crazy and this bug doesn’t really exist but I’ve been dealing with it over the past few days and I’m starting to loose my mind. 

You see, two days ago a friend of mine showed me a supposed canvas logout QR code, which when scanned using the iOS camera app would either present itself as a canvaslms link or prompt the user to open with student, seemingly at random. I, being of sound mind and judgement concluded that this was just a mobile login code and was as such harmless, so I scanned it. I have come to regret that decision with my whole soul and am beginning to wonder if I should seek therapy.

You see, as far as I can tell the QR code *was* a simple mobile login code, however an extremely old one. Apon picking apart the code it has the following link: `https://sso.canvaslms.com/canvas/login?code_android=b9cdcdba8c8a3e7c937773f8897eecf11c8566cc7dabb683b0c8128104d42c3f60f84a3aac022d979c41f26b8b0a5964911fa73a1f6e8ce906c46e4f40f01876&code_ios_teacher=d05f824cff47860a755cacec0e477df4ef19c8d169743185165079e2e9fe3b9ed4f24f4d67d2731e6efaaba2af49b361742e412af053567ac9aef9a1516b93c5&code_android_teacher=3007f557f550f10f8dd67f1d501994cd1b4bdbf913288fb55c6e1ada8757d56e74689a5ebb29a05b0d4d0d33721b59edef8e7bb34d2691de1bb8a492cc87b8c7&code_ios_parent=0e1bca7e402038e6d794fe4649d8daeef693f182272778271e252902bc9480b0da9408e74554714e1ed8cf751b636184e67e83af59a05707783860af247f48f5&code_android_parent=6b9faa7c4838a455ddd8abbdf701e44244e27c68117e5b47eef6b7e2d00c4e2f92e0a799d9ee22a9ec9d73b4cf66948e55857f71b78d2cb322dd1e53b954f612&code=f701cd38f2971cd9f0d623164f9a2a75dd96270f89d4c041432f4020def7f778d3e210a275d9c6cab27f8a5ded89ffdbe8ea10c46eb59a04093ed13e8464e884&domain=esko.instructure.com` which when scanned redirects to esko.instructure.com’s login page, my institution.

And of course when scanning it, as promised it logs you out which is expected behavior. The issue comes when you log back in. This is where I’m going to start to sound crazy, and I really don’t want you to dismiss me as a troll using a fake story. I’ve scanned the code multiple times and been able to reproduce the following symptoms:

1. Language changes from device default to Arabic (or Farsi as the case may be)
2. My todo list gets cleared (I’m gonna miss some assignments because of this one)
3. My display name, and other user settings pertaining to my personal data are modified usually to contain extra vowels or swap vowels
4. My profile picture got deleted
5. All uploaded files disappeared from the canvas file explorer (although they are still accessible via link)
6. Unenrolled from most courses

The biggest problem and part of the reason I expect this issue to be closed is that my first step to reproduce is to have an account at our school. I’m hoping there’s some way to tell what’s wrong from the url and reproduce it on test institutions but we’ll see.

### Steps to reproduce:

 1. Log into a canvas account using Student for iOS
 2. Scan QR code (provided below) with your iOS camera app
 3. If it shows canvaslms link, open it and watch yourself get logged out
 4. Log back in and notice no changes immediately
 5. Sometime in the next few hours you’ll start to see the signs listed above

### Expected behavior:
I honestly don’t know what the expected behavior should be, but I can sure say this isn’t it. I don’t know how a QR code has the ability to modify my user settings but this sure isn’t normal

### Actual behavior:
Listed above
### Additional notes:
The QR code I used, for helping to reproduce
![9781CEBD-31F1-47C8-B6A0-23C1F46B8E37](https://user-images.githubusercontent.com/32989720/151497485-2958aafd-93af-4ff9-9901-525e388dab9b.png)

Also just want to state again that I’m not crazy, this has been bugging me and I figured an issue here was the best place. Let me know if it should be moved!

**Comment by nobody5050** [comment]
Update: I was also unenrolled from most courses

**Comment by f873** [comment]
Bruh Lmao L + RATIO

**Comment by jbmagination** [comment]
I had a whole response / explanation as to how this process works... but then I realized that *your friend sent you a QR code.* Most likely, they just wanted you to scan it so that they could enter your account and mess with you. This would explain why there were no immediate changes, and it happened gradually over time.

I know it's been a month, but if you haven't figured it out yet, here you go.
