### ISSUE TITLE
Math Equations/Formulas not showing in Pages

### ISSUE THREAD

**Issue by Higherings** [instructure/canvas-lms#2015]
### Summary:
Starting on February 10th, images of formulas/equations are not showing correctly. The images can not be loaded.

### Steps to reproduce:

 1. Create a Page and put some latex formulas
 2. The pase will show a broken page icon and the text, not the image

### Expected behavior:
![image1](https://user-images.githubusercontent.com/15874205/153633295-9dccb8ac-630e-4d51-83b4-0b0adf9e9c4e.png)

### Actual behavior:
![image2](https://user-images.githubusercontent.com/15874205/153633317-dad17022-6176-4cd2-bc58-2d5099784b5b.png)

### Additional notes:
The URL of the images finally resolves to something link this: `https://latex.codecogs.com/gif.latex?%5Csqrt%5B2%5D%7B5%7D`
The service in latex.codecogs.com is down or not working.

This is a self-hosted Canvas and I don't recall configuring nothing to use latex.codecogs.com, nor know how to use another service.

**Comment by Ardena** [comment]
The latex codecogs service is used by default in app/controllers/equation_images_controller.rb:47.  I'm sorry the service was down for a bit.  It does look like it is working again right now, though.

**Comment by Higherings** [comment]
As the latex.codecogs.com service has been unstable, is there an alternative to use that you recommend?

**Comment by Ardena** [comment]
Try /plugins/mathman.  I'm not sure what the transition is like, though, so I recommend you test it first.
