### ISSUE TITLE
Feature Request: "Mark All As Read" for notifications

### ISSUE THREAD

**Issue by tdooner** [instructure/canvas-lms#204]
Hello. We're managing a large class with Canvas. Naturally, the class generates a lot of notifications. Most of them do not need to be read (since they are boring, like people submitting files).

It would be extremely convenient to have a "Mark All As Read" button to lower the signal-to-noise ratio for future notifications.

Thanks!

**Comment by paerbac** [comment]
this is still not a thing in the year 2022 for some reason
