### ISSUE TITLE
Login API with username & password 

### ISSUE THREAD

**Issue by rahul-ecsion** [instructure/canvas-lms#2041]
### Summary:

Hi Canvas lms Team,

I am working customised canvas lms mobile application. 

I searched on google and canvas API documentation, didn't found Login API with username and password.
Wanted to use it for Initial login without using the Authentication Token. 

**Queries**

1. Can someone please help me with the Login API if its available?

2. And if it's not available the please help me how we can  create it for our customised canvas lms mobile application?

3. After POST url using web view it is asking for login again in relaunch. How can we overcome this issue ?

Thank you in advance.

**Comment by maths22** [comment]
The canvas API only supports token based authentication.  If you are making a customized mobile application, you should be using the OAuth flow to generate tokens: https://canvas.instructure.com/doc/api/file.oauth.html#oauth2-flow
