### ISSUE TITLE
POST Quiz Question answer_comments does not function

### ISSUE THREAD

**Issue by tomsant** [instructure/canvas-lms#2045]
### Summary:
Unable to POST quiz question with answer comments.

I have successfully built a script to create a quiz and quiz questions using python and the canvas API. I'm able to successfully create quiz questions and weights, 

### Steps to reproduce:

 1. POST quiz question including option parameter for answer_comments
 2. View quiz in canvas
 3. See everything else but the answer_comments

### Expected behavior:
Answer comments should be attached to each quiz question answer

### Actual behavior:
They do not appear

### Additional notes:
Here is the json I'm sending through. Again, note answer_text and answer_weight are correctly handled by the API, but answer_comments is not.

`question = {
        'question[question_text]' : question_prompt,
        'question[question_type]' : question_type,
        'question[points_possible]' : 2,
        'question[answers][0][answer_text]' : correct_answer,
        'question[answers][0][answer_weight]' : 100,
        'question[answers][0][answer_comments]' : '',
        'question[answers][1][answer_text]' : wrong_answer_1,
        'question[answers][1][answer_weight]' : 0,
        'question[answers][1][answer_comments]' : wrong_answer_1_feedback,
        'question[answers][2][answer_text]' : wrong_answer_2,
        'question[answers][2][answer_weight]' : 0,
        'question[answers][2][answer_comments]' : wrong_answer_2_feedback,
        'question[answers][3][answer_text]' : wrong_answer_3,
        'question[answers][3][answer_weight]' : 0,
        'question[answers][3][answer_comments]' : wrong_answer_3_feedback
    }`

**Comment by tomsant** [comment]
Solved! After updating the answer comment and inspecting network traffic, I discovered the API documentation is incorrect here. The field is `question[answers][#][answer_comment_html]`.

**Comment by haimeo1201** [comment]
Hey i got the same error can you pls help me?
![Capture](https://github.com/user-attachments/assets/799f9ad6-79d7-4ee5-8e57-64533a45fe2d)
I cannot add answer to a quizz
