### ISSUE TITLE
Bundle coun't find compatible versons for bundler

### ISSUE THREAD

**Issue by Musicminion** [instructure/canvas-lms#2047]
### Summary:
![image](https://user-images.githubusercontent.com/84625273/163783212-2bf08b6f-558a-4819-ad28-4c6a84c5e0fe.png)

### Steps to reproduce:
Verson Ubuntu 18.04 
Verson Branch: [stable/2021-11-10](https://github.com/instructure/canvas-lms/tree/stable/2021-11-10)

 1.Follow the instruction of the Production Start
 2.Execute `canvas_init start`
 3.Failer

I try execute bundler -v, and find my verson is excatly 2.2.19, which meets the GEMFILE requirement!

So, did anyone meet this probelm, to? All in all, this problem will not affect the open of this website, however ,Automated jobs can't do totally!

### Expected behavior:
Start succeed

### Actual behavior:
ERROR

**Comment by Musicminion** [comment]
Hopefully I can change my gemfile? Or there is something woring with the SYSTEM ENVIRONMENT？
I can't tell， and I am also confused with the output of `bundle -v` , which tells the verson are not compatible.

**Comment by amg-web** [comment]
first check your bundle version:
bundle -v

if it's wrong search about changing default bundler version

**Comment by Musicminion** [comment]
> first check your bundle version: bundle -v
> 
> if it's wrong search about changing default bundler version

thanks! After input bundle -v cmd, it shows 2.2.19, I am considering if I need to change my  Gemfile?

I didn't install any other verson of bundle, I am quite sure!

**Comment by Musicminion** [comment]
> first check your bundle version: bundle -v
> 
> if it's wrong search about changing default bundler version

![image](https://user-images.githubusercontent.com/84625273/164480483-09e266e3-9b88-438d-b13b-6eae4f1db026.png)

**Comment by Musicminion** [comment]
> changing default bundler version

So, is there anything woring?

![image](https://user-images.githubusercontent.com/84625273/164480893-1c339f71-03fa-4c3d-92a1-361f816de3cf.png)

**Comment by amg-web** [comment]
check: gem list bundler
and bundler version at the bottom of Gemfile.lock

**Comment by amg-web** [comment]
try to set default bundler:
gem install bundler --version 2.2.19 --default

**Comment by Musicminion** [comment]
> try to set default bundler: gem install bundler --version 2.2.19 --default

Amazing！ why 2.1.4？

![image](https://user-images.githubusercontent.com/84625273/164484096-4716688e-536e-42cf-94e1-b363f0067314.png)

**Comment by amg-web** [comment]
gem env

**Comment by Musicminion** [comment]
> gem env

![image](https://user-images.githubusercontent.com/84625273/164485447-301509df-a605-4fe1-b30f-9243ad510943.png)

**Comment by amg-web** [comment]
https://stackoverflow.com/questions/54761120/rails-how-to-change-bundler-default-version

**Comment by Musicminion** [comment]
Problem Solved, Thanks @amg-web

**Comment by Musicminion** [comment]
从 Windows 版邮件发送

发件人: anmg
发送时间: 2022年4月21日 22:47
收件人: instructure/canvas-lms
抄送: Musicminion; Author
主题: Re: [instructure/canvas-lms] Bundle coun't find compatible versonsfor bundler (Issue #2047)

gem env
