### ISSUE TITLE
Error during step 3 of LTI 1.3 launch "The launch has either expired or already been consumed

### ISSUE THREAD

**Issue by drscottlobo** [instructure/canvas-lms#2049]
### Summary: 

I'm receiving an error at Step 3 of the LTI 1.3 flow. Canvas is running on localhost:3000 and my LTI is running with a self-signed certificate on https://localhost:8000. The OIDC launch successfully launches the tool and then I send a redirect back to my local instance of Canvas http://localhost:3000/api/lti/authorize_redirect

### Steps to reproduce:

 1.
 2.
 3.

**Comment by Soumyaranjanpal** [comment]
Hi @drscottlobo , How you solved this issue ?
