### ISSUE TITLE
New LTI launch sizing issue

### ISSUE THREAD

**Issue by claydiffrient** [instructure/canvas-lms#2052]
### Summary:
New LTI assignment launches show in a squished view and scroll within the iframe on the page.  This also happens when we modify existing assignment launches that aren't broken (prior to ~1.5 weeks ago).  Removing the `custom_height` class from the iframe makes the problem go away.

### Steps to reproduce:

 1. Create an assignment using an LTI tool (Derivita in our case)
 2. Launch the assignment
 3. Notice that it's squished

### Expected behavior:
<img width="1792" alt="Screen Shot 2022-04-27 at 12 08 31 PM" src="https://user-images.githubusercontent.com/606262/165592840-b53a115b-dcfa-4b99-a872-4c66b5dfa95d.png">

### Actual behavior:
<img width="1772" alt="Screen Shot 2022-04-27 at 12 07 31 PM" src="https://user-images.githubusercontent.com/606262/165592900-f38efdce-2b1e-4c8f-9b9b-e29d05254b9b.png">

### Additional notes:
As far as we can tell we've done nothing different on our side to make this behavior happen.  Our LTI launches are happening the same as always.

**Comment by stephendgilbert** [comment]
This has happened to us as well. Viewing the source of the generated pages, the LTI-launch iframe now has this style:
`style="height:px;width:px"`
Prior to about two weeks ago, the style was:
`style="height:100%;width:100%"`
