### ISSUE TITLE
GraphQL assignments connection doesn't work

### ISSUE THREAD

**Issue by gor-gevorgyan** [instructure/canvas-lms#2054]
query MyQuery {
  course(id: "117") {
    assignmentGroupsConnection {
      nodes {
        _id
        name
        state
        groupWeight
        assignmentsConnection {
          nodes {
            _id
            name
          }
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}

assignments connection doesn't return any data for any course
<img width="1646" alt="Screen Shot 2022-05-03 at 09 23 36" src="https://user-images.githubusercontent.com/20685134/166408027-b7611764-8168-4725-9fce-d3570dc011db.png">

**Comment by Ardena** [comment]
gor-gevorgyan - in canvas-lms/app/graphql/interfaces/assignments_connection_interface.rb:50

If you don't supply a grading_period_id for assignments, it uses the current grading period id.  Since neither of your grading periods is currently active, it appears it's not giving you anything.

**Comment by gor-gevorgyan** [comment]
thank you @Ardena
