### ISSUE TITLE
app/models/message.rb:308: warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by amg-web** [instructure/canvas-lms#2074]
error message in delayed_job.log:

`/home/canvas/public_html/app/models/message.rb:308: warning: URI.escape is obsolete`

**Comment by newbee1905** [comment]
try replacing URI.escape with this 
```ruby
p = URI::Parser.new
p.escape(s)
```
source: https://stackoverflow.com/questions/65423458/ruby-2-7-says-uri-escape-is-obsolete-what-replaces-it

**Comment by ccutrer** [comment]
This has been fixed on master.
