### ISSUE TITLE
TinyChat Plugin

### ISSUE THREAD

**Issue by TBK0000** [instructure/canvas-lms#208]
TinyChat doesn't provide an API any longer, so the plugin should be removed. The link leads to nowhere - http://tinychat.com/developer/dashboard

It could be replaced with something like http://www.tokbox.com/

**Comment by claydiffrient** [comment]
I'm going to go ahead and close this issue. It appears that TinyChat isn't in the plugin list anymore.  Any future discussion about chat integration can be tracked with #469
