### ISSUE TITLE
Unable to download and preview files. 

### ISSUE THREAD

**Issue by minitriga** [instructure/canvas-lms#2081]
### Summary:
Unable to display images. When uploading an image it will complete uploading and then when completed you are unable to preview or download the image.

### Steps to reproduce:

 1. Upload Image
 2. Preview Image
 3. Image fails to load
![image](https://user-images.githubusercontent.com/26367336/183080584-6f29045a-8d45-478d-85ae-e5c2bc807d78.png)

### Expected behavior:
I would expect the image to be able to preview. 

### Actual behavior:
Images and other files are not downloadable or viewable. 

### Additional notes:
When inspecting the network tab it looks like the image there but its using a domain that is no longer in use. we use training.axians-uk.cloud now instead of canvas.axians-uk.cloud

![image](https://user-images.githubusercontent.com/26367336/183080904-9452392c-c571-42a2-b21a-0676aea9cbbd.png)

I have checked all config files using grep and cannot find canvas.axians-uk.cloud configured anywhere.

**Comment by cesar23** [comment]
for that I see that in my canvas installation they used a service in nodejs

**Comment by johntheocs** [comment]
I have the same problem. Unable to preview and download files.

**Comment by johntheocs** [comment]
@minitriga @cesar23 Have you found a way to work around?

**Comment by jeus1609** [comment]
Please how did you solve it
