### ISSUE TITLE
Add dependency the specified version of switchman-inst-jobs in Gemfile

### ISSUE THREAD

**Issue by mayng0702** [instructure/canvas-lms#2083]
### Summary:
How to solve the version of switchman-inst-jobs in Gemfile 
### Steps to reproduce:

 1. cd gems/plugins/academic_benchmark/
 2. nano academic_benchmark.gemspec
 3. Add (spec.add_dependency "switchman-inst-jobs", "4.0.9") line to academic_benchmark.gemspec

### Expected behavior:
Add dependency the specified version of switchman-inst-jobs

### Actual behavior:
```
<!--[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice
with different version requirements.
You specified: switchman-inst-jobs (= 4.0.8) and switchman-inst-jobs (= 4.0.9).
Bundler cannot continue.
# from /var/canvas/Gemfile.d/../gems/plugins/analytics/Gemfile.d/app.rb:26
# -------------------------------------------
# require File.expand_path("config/canvas_rails_switcher", __dir__)
>
# Dir.glob(File.join(File.dirname(__FILE__), "Gemfile.d", "*.rb")).sort.each
do |file|
# -------------------------------------------
```

**Comment by ccutrer** [comment]
I'm not sure what you're trying to accomplish here. switchman-inst-jobs is already listed in Gemfile.d/app.rb, so cannot be listed elsewhere.

**Comment by mayng0702** [comment]
Noted with thanks. Thanks for your checking.

在 2023年8月27日週日 10:46，Cody Cutrer ***@***.***> 寫道：
