### ISSUE TITLE
Broken New Quiz builder on Safari, Firefox and Chrome, on Mac and iPad Pro

### ISSUE THREAD

**Issue by corei8** [instructure/canvas-lms#2099]
### Summary:

There is a ```div``` or some other element that is obscuring half the screen for the new quiz builder.

### Steps to reproduce:

 1. Choose the new quiz builder, rather than the classic.
 2. Use Safari, Firefox or Chrome on macOS Monterey
 3. Enter the builder for the quizzes.

### Expected behavior:

To see the entire viewport filled with the builder.

### Actual behavior:

Less than half of the viewport height is taken up by the builder.

### Additional notes:

<img width="1972" alt="image" src="https://user-images.githubusercontent.com/38426287/192410369-ab83a76c-2dab-43a4-9aae-8c5473a49c78.png">

**Comment by Ardena** [comment]
As it appears you are an Instructure customer, I recommend if you are still having this issue to contact our support team.  I, personally, am not seeing the issue for that course/quiz combination, and this is not a very good forum for further troubleshooting.
