### ISSUE TITLE
Safari private browsing JS errors

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#210]
When using Safari private browsing, the following error is generated on some pages (ex: Calendar): 

`QUOTA_EXCEEDED_ERR: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.`

On common.js line:112

The result is that some UI elements stop working: the courses dropdown doesn't drop down, the calendar feed link doesn't display it's modal, etc. 

This is on Safari 6.0 (7536.25)

Thanks.

**Comment by claydiffrient** [comment]
@christopher-b I'm sorry for the long wait time on this issue.  After digging in it looks like Private Browsing mode prohibits the use of LocalStorage in the browser, which we use for persisting some user settings.  I wish I could say a fix to this was on the way, but I don't see a real workaround at this point other than a message indicating that the application isn't fully supported when using Safari's Private Browsing feature.  We would welcome any pull request that might address this, but I can't say we'll have bandwidth to work on this for the near future. Thanks for reporting it though.  I'm going to close this issue for now, but feel free to reopen it if you feel it's merited.
