### ISSUE TITLE
Side Scroll Bar

### ISSUE THREAD

**Issue by sprintup** [instructure/canvas-lms#2109]
### Summary:
![image](https://user-images.githubusercontent.com/10011204/195461407-124d9032-b15a-4cb7-8adf-7ee29db58ab5.png)
### Steps to reproduce:

 1.
 2.
 3.

**Comment by Ardena** [comment]
What are you expecting?  It looks like you're assuming there shouldn't be a scroll bar, but there are a lot of items in that list, so they just wouldn't show without a scroll bar.

**Comment by Ardena** [comment]
Just looked at the page and you're right that there's no scrollbar on the side bar, but the main scrollbar scrolls the whole sidebar, so I'm not sure why you'd want to add another scrollbar.  Plus extra scrollbars like that can be hard for assistive technologies to use.
