### ISSUE TITLE
Cannot see +People button in the people page

### ISSUE THREAD

**Issue by huangdengpan** [instructure/canvas-lms#2128]
Help !

Using master account to view People page, the "+People" button has gone.
No errors show in control panel of google chrome.
Tried to add a teacher into the course, cannot see it, too.

canvas-lms version by 11.25 

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/16663404/205079350-e0425caf-8479-4405-a8ac-4b0402a0fd91.png">

**Comment by brandonfranzke** [comment]
I see you marked this as closed.  I am having the same issue... "master" account, checked permissions, etc.

Were you able to resolve?  If so what was the fix?
