### ISSUE TITLE
ActiveRecord::InvalidForeignKey in Login::CanvasController#create

### ISSUE THREAD

**Issue by emmanuelpineda** [instructure/canvas-lms#2144]
### Summary:

After doing the installation on my local computer, when I logged in for the first time, I got this error:

![image](https://user-images.githubusercontent.com/45979790/213490544-3573d9b8-d5b7-4c73-a076-3e9009276aee.png)

### Steps to reproduce:

1. Download the repository
2. Run the command: ./script/docker_dev_setup.sh
3. Run the initial setup script (https://community.canvaslms.com/t5/Canvas-Question-Forum/Unable-to-get-Login-Credentials-When-install-canvas-using-docker/td-p/503423)
4. Go to http://canvas.docker/login/canvas from the browser
5. Login

### Expected behavior:

Allow login

### Actual behavior:

Does not allow login

### Additional notes:

During the installation, I chose the option to migrate database

**Comment by emmanuelpineda** [comment]
After restarting the Docker container, it worked fine.

**Comment by jeroenhabets** [comment]
BTW: still encountered this issue a couple of times in March 2025 but indeed restarting the dockers helped...

Pasting the following as text for SEO, i.e. so people facing this error can more easily find this issue and its workaround.

```
ActiveRecord::InvalidForeignKey in Login::CanvasController#create
PG::ForeignKeyViolation: ERROR: insert or update on table "terms_of_services" violates foreign key constraint "fk_rails_337ba633a9" DETAIL: Key (account_id)=(10000000000002) is not present in table "accounts".
```
