### ISSUE TITLE
Large numeric id is returned incorrectly in Canvas API

### ISSUE THREAD

**Issue by ziktar** [instructure/canvas-lms#2148]
### Summary:

A student with a large numeric id, 74140000000062630, gets incorrectly truncated to 74140000000062620 instead.

### Steps to reproduce:

 1. Create a student whose student_id is over the Javascript Number.MAX_SAFE_INTEGER
 2. Call an API that returns this student id, such as /api/v1/courses/{course}/users
 3. See that the student id is returned incorrectly

### Expected behavior:

The id should be returned correctly, without rounding.

### Actual behavior:

The id is rounded due to being above the maximum safe integer size

**Comment by Ardena** [comment]
Add an accept header like this:
Accept: "application/json+canvas-string-ids"
