### ISSUE TITLE
Canvas LMS error syntax error while running the command "./script/docker_dev_setup.sh"

### ISSUE THREAD

**Issue by Aadil25** [instructure/canvas-lms#2169]
### Summary: I am getting an error while running the command "./script/docker_dev_setup.sh"  after clone the canvas-lms from git.
can anyone help me to resolve the syntax error? 
Below is the error which I get:
"Checking Dependencies...
script/common/utils/common.sh: line 159: ((: 0
0
0
1 : syntax error in expression (error token is "0
0
1 ")

> Starting dory...
Traceback (most recent call last):
	1: from /usr/local/bin/dory:23:in `<main>'
/usr/local/bin/dory:23:in `load': cannot load such file -- /var/lib/gems/2.7.0/gems/dory-1.2.0/bin/dory (LoadError)
Traceback (most recent call last):
	1: from /usr/local/bin/dory:23:in `<main>'
/usr/local/bin/dory:23:in `load': cannot load such file -- /var/lib/gems/2.7.0/gems/dory-1.2.0/bin/dory (LoadError)

> Something went wrong with dory! Exiting script.

  /o\ Something went wrong. Check /var/www/html/canvas-lms/log/docker_dev_setup.log for details."

### Steps to reproduce:

 1. 
 2.
 3.

### Expected behavior:
"Welcome! This script will guide you through the process of setting up a
Canvas development environment with docker and dinghy/dory.

When you git pull new changes, you can run ./scripts/docker_dev_update.sh
to bring everything up to date."

### Actual behavior:
Welcome! This script will guide you through the process of setting up a
Canvas development environment.
  Log file is /var/www/html/canvas-lms/log/docker_dev_setup.log

> It looks like you're using Linux. Let's set that up.

> Checking Dependencies...
script/common/utils/common.sh: line 159: ((: 0
0
0
1 : syntax error in expression (error token is "0
0
1 ")

> Starting dory...
Traceback (most recent call last):
	1: from /usr/local/bin/dory:23:in `<main>'
/usr/local/bin/dory:23:in `load': cannot load such file -- /var/lib/gems/2.7.0/gems/dory-1.2.0/bin/dory (LoadError)
Traceback (most recent call last):
	1: from /usr/local/bin/dory:23:in `<main>'
/usr/local/bin/dory:23:in `load': cannot load such file -- /var/lib/gems/2.7.0/gems/dory-1.2.0/bin/dory (LoadError)

> Something went wrong with dory! Exiting script.

  /o\ Something went wrong. Check /var/www/html/canvas-lms/log/docker_dev_setup.log for details.

**Comment by cgravatt** [comment]
This is caused by docker-compose outputting multiple lines of versions when we only care about the first

```
$ eval docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.6
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
```
