### ISSUE TITLE
How to generate access token 

### ISSUE THREAD

**Issue by tuantiensiu** [instructure/canvas-lms#2181]
I want to manually generate access token for user account with admin token, can I do this?

### Example step

 1. Send API with admin token, user id client or email client
 2. Response access token client

**Comment by ccutrer** [comment]
No, it is not possible to generate an access token for a user. You either need to set up a Developer Key, and have each user go through the OAuth flow (https://canvas.instructure.com/doc/api/file.oauth.html), or if you will maintain control of the access token, and just need to make API requests as if you were a particular user, you can use your admin access token and masquerade as a user (https://canvas.instructure.com/doc/api/file.masquerading.html).

**Comment by tuantiensiu** [comment]
I see admin doesn't have permission to create access token for user with masquerade
