### ISSUE TITLE
Canvas Enrollments API is no longer returning inactive enrollments by default

### ISSUE THREAD

**Issue by MakotoTheKnight** [instructure/canvas-lms#2190]
### Summary:

When making an API call to pull back enrollments through the [Enrollments API](https://canvas.instructure.com/doc/api/enrollments.html#method.enrollments_api.index), my team and I are observing that enrollments that are inactive are not being returned.

We believe that this is the contract that is being violated when attempting to reach out to Canvas:

> Enrollments scoped to a course context will include inactive states by default if the caller has account admin authorization and the `state[]` parameter is omitted.

Note:  This is only occurring in the Beta environment for Canvas, but we observed that this is slated for a future release sometime in early May.

### Steps to reproduce:

 1. Create separate account with admin privileges 
 2. Generate an access token for said account
 3. Invoke `/api/v1/sections/<sis_id>/enrollments?sis_user_id[]=<sis_id>`, ensuring that the aforementioned account has a few inactive enrollments

### Expected behavior:

All enrollments, including inactive ones, are returned

### Actual behavior:

Only active enrollments are returned.

### Additional notes:

If the change to the API does mandate that it not bring back inactive records by default, then the [filters introduced by this commit](https://github.com/instructure/canvas-lms/commit/6ef3b7e7bc3411f0bdac7054e586fe74ebea34d1#diff-6cf52104b49180bc9d0cee7c4033e2372b75f38d6c77be820e75e7d5702bd6d7R457) are overly restrictive and should be loosened up somehow.

**Comment by augiethornton** [comment]
@MakotoTheKnight We now default to returning the old behavior of inactive enrollments if the state param is not included in the request. You should see the change reflected in the Beta environment.

**Comment by MakotoTheKnight** [comment]
Thank you @augiethornton!  I'm able to confirm that the behavior is now consistent with what we originally expected.

I'll go ahead and close this out now.  Thanks again!
