### ISSUE TITLE
Canvas Speed Grader use LTI 1.1 for LTI Links on LTI 1.3 assignments

### ISSUE THREAD

**Issue by jegj** [instructure/canvas-lms#2192]
### Summary:
Hi, I having problem with Speed Grader when I try to show the submission preview for an Assignment created on an external tool using LTI 1.3 (Deeplink). I created the submission with the type **basic_lti_launch** and i got a successful response from the API but when I open Speed Grader to see the preview from the student, Canvas is sending a request with a payload following the LTI-1p0 specification to my backend 

### Steps to reproduce:

 1. Create an assignment on an external tool using LTI 1.3
 2. Submit score on the tool using AGS/Canvas API using the type **basic_lti_launch**
 3. Open Speedgrader to see the previews

### Expected behavior:
Speedgrader should send a request with a payload following the LTI 1.3 specs

### Actual behavior:
Speedgrader send request with a payload from LTI-1p0 version

**Comment by jegj** [comment]
Closing this issue because i got an answer from the support team. SpeedGrader does not work with LTI 1.3 but you can make it "compatible".

**Comment by fahad-curriki** [comment]
@jegj Can you elaborate how you can make SpeedGrader "compatible" with LTI 1.3 ?
