### ISSUE TITLE
Duplicate notifications from all my courses

### ISSUE THREAD

**Issue by BeethovenKodar** [instructure/canvas-lms#2195]
### Summary:
Whenever I get a notification from the Canvas iOS app i get two or three of them. I have iOS 16.4.1 and the Canvas app is the latest version. I'm sure that this is not the course's fault, there is just one announcement when I open the app.

### Steps to reproduce:
None

### Expected behavior:
Just one notification

### Actual behavior:
![IMG_7772](https://user-images.githubusercontent.com/55529498/234016394-1f9dd292-792e-49ac-8b6a-f224d89fe10e.jpeg)

### Additional notes:
No

**Comment by i-am-gizm0** [comment]
I've also been experiencing this for a while on the Android app.

**Comment by BeethovenKodar** [comment]
Reinstall the app after deleting its full storage trace on your device. That solved it for me.
