### ISSUE TITLE
ChatGpt Implement to canvas lms

### ISSUE THREAD

**Issue by potru** [instructure/canvas-lms#2198]
### Steps to reproduce:

Hi,

We are planning to Implement Chatgpt in our own canvas lms platform so could you please any suggestion on me.

Note: Our canvas platform deployed from open source.

**Comment by dustin-cowles** [comment]
Hi @potru! It is exciting to hear that you are planning on contributing to Canvas LMS, however this is not the correct venue for this type of question. There is both a mailing list and irc channel in the [Getting Help](https://github.com/instructure/canvas-lms/wiki/Getting-Help)  section of our wiki that may be a better place for this type of conversation.
