### ISSUE TITLE
default user_name and password?

### ISSUE THREAD

**Issue by burningTyger** [instructure/canvas-lms#220]
I just installed a local dev environment, started up and now I'm confronted with missing credentials. How do I set a valid username and password for the admin?

**Comment by sarbazx** [comment]
Hi, I have installed canvas using automated script docker_dev_setup.sh and it didn't prompt for user and password. So what will be the default email and password? I have run script for the fourth time still no prompt for default user.

**Comment by djbender** [comment]
@sarbazx hey there! Could you please post your question to our [mailing list](https://groups.google.com/forum/#!forum/canvas-lms-users)? thanks!
