### ISSUE TITLE
Pressing Escape during page load breaks everything

### ISSUE THREAD

**Issue by pikapower9080** [instructure/canvas-lms#2205]
### Summary:
When I press escape on certain pages like the home page while it's loading I get a bunch of error alerts and everything fails to load.

### Steps to reproduce:

 1. Start loading homeroom page
 2. Press escape while everything is gray boxes

### Expected behavior:
Pressing escape should not affect loading behavior.

### Actual behavior:
Pressing escape causes a bunch of Failed to fetch errors.

### Additional notes:
Issue was experienced in my school's version of canvas and I don't know if it happens in canvas for other schools.

**Comment by rmsy** [comment]
Hello,

Thanks for the issue. This is intended, as pressing the escape key in a browser causes any in-flight network requests to be canceled (and the page load to be stopped).
