### ISSUE TITLE
Migrate to Ruby version > 2.7

### ISSUE THREAD

**Issue by muscle-hamster** [instructure/canvas-lms#2207]
### Summary:
Ruby 2.7 has reached its EOL and poses security risks moving forward. Is there a timeline on the migration to a Ruby version greater than 2.7? Currently the production docs state "Canvas now requires Ruby 2.7, as of the 2021-11-10 release. Ruby 3.0+ support is untested.". If this is inaccurate I would be more than happy to submit a PR to fix the documentation.

### Steps to reproduce:

 1.
 2.
 3.

**Comment by maths22** [comment]
Canvas is now running on ruby 3.1 in the SAAS production deployment and can be run on 3.1 everywhere.  I'll go update the docs to reflect that.
