### ISSUE TITLE
canvas_init start - is not working

### ISSUE THREAD

**Issue by fangchongde** [instructure/canvas-lms#2221]
Trying to install canvas on my local computer (Ubuntu 22.04) by following https://github.com/instructure/canvas-lms/wiki/Production-Start
fcd@canvas:/var/canvas$ sudo /etc/init.d/canvas_init start
<img width="867" alt="image" src="https://github.com/instructure/canvas-lms/assets/5442961/ca59ff78-500b-4bf5-ac5c-d0588f71256d">

**Comment by nosadcoder** [comment]
1, It looks like a syntax error
2, Check ruby version. Maybe the right version is ruby3.1
