### ISSUE TITLE
Proper Nginx Setup

### ISSUE THREAD

**Issue by P1xelC0da** [instructure/canvas-lms#2238]
I was wondering if Canvas could be ran using Nginx? I'm running off of Nginx (8+ sites currently) so it'd be a chore to migrate to apache2

**Comment by maths22** [comment]
Canvas should run fine on nginx (and I believe it already does inside our docker-based setup)

**Comment by P1xelC0da** [comment]
Getting Canvas to run with the dev docker container is such a chore. 
Turnkey linux does it just fine. Got it running, thank you anyway

**Comment by nosadcoder** [comment]
use proxy_pass from nginx to apache
