### ISSUE TITLE
npm ERR! code EBADENGINE

### ISSUE THREAD

**Issue by abel-haj** [instructure/canvas-lms#2252]
### Summary:
Building docker images fails in this command `RUN npm install -g npm@latest && npm cache clean --force`
I am trying to run canvas locally on macOS, and I am following the [Quickstart guide](https://github.com/instructure/canvas-lms/wiki/Quick-Start#automated-setup)
Please help!

### Steps to reproduce:

 1. Execute `./script/docker_env_setup.sh`
 2. Yes for `OK to run 'cp docker-compose/config/*.yml config/'?`

### Additional notes:
[docker_dev_setup.log](https://github.com/instructure/canvas-lms/files/12522051/docker_dev_setup.log)

**Comment by Vybeu** [comment]
I was able to solve this problem by commenting out this line in the Dockerfile:
`RUN npm install -g npm@latest && npm cache clean --force`

Then ran the `./script/docker_env_setup.sh`

I hope it works for you too!

**Comment by abel-haj** [comment]
> I was able to solve this problem by commenting out this line in the Dockerfile: `RUN npm install -g npm@latest && npm cache clean --force`
> 
> Then ran the `./script/docker_env_setup.sh`
> 
> I hope it works for you too!

Thank you so much! That works, no more errors encountered!

**Comment by jakeoeding** [comment]
[This commit](https://github.com/instructure/canvas-lms/commit/0f5c22ae8198520ea4197e87e8c361bb39fbffd7) was made to correct this issue. There was a day or two period where the build was broken, but if you pull the latest master branch it should be fixed now.
