### ISSUE TITLE
smtp oauth2 office365

### ISSUE THREAD

**Issue by amg-web** [instructure/canvas-lms#2254]
Microsoft deprecated Basic authentication in Exchange Online
https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online

I think I can use legacy endpoint.

but is it possible to add oauth2 for smtp ?

possible gems
https://gitlab.com/oauth-xx/oauth2/
https://github.com/ekohe/ruby-office365

**Comment by maths22** [comment]
Instructure will not be implementing support for oauth2-based SMTP auth
