### ISSUE TITLE
Unassigned group unavailable after students are assigned, previous work done is lost

### ISSUE THREAD

**Issue by cjwit** [instructure/canvas-lms#2262]
### Summary:

Discussion posts made by students who are not assigned to a group are inaccessible after assigning the student to a group.

### Steps to reproduce:

 1. Instructor creates groups with discussions, leaving one out (in my case, a student added a class late)
 2. Student posts to the assignment, posts are made to a "group" of any students who are not assigned to a group
 3. Instructor moves the student into a group
 4. Previous discussion is no longer available since the "unassigned" group no longer exists

### Expected behavior:

Posts migrate with the student to the assigned group or the unassigned group's discussion board remains accessible (I assume this would also happen with other group tasks)

### Actual behavior:

Unassigned group is lo longer present

**Comment by ktheory** [comment]
Hi @cjwit,

Thanks for raising this issue, and I understand how in some cases it’s helpful for a student’s posts to migrated from the course discussion to a group discussion.

That said, we believe that the current behavior to start fresh in a group discussion is the safest behavior.

The student’s post may reference other posts that are not in the new group discussion and be confusing out of context. And if the discussion is graded, the instructor’s expectations are ambiguous: would they prefer the student to post again, or grade their existing post from the course discussion?

On balance, we decided it’s safer for group discussions to start fresh.
