### ISSUE TITLE
Codespace container creation fails /var/lib/docker missing

### ISSUE THREAD

**Issue by GhostInTheMachines** [instructure/canvas-lms#2268]
### Summary:
Container creation fails with the following error found in Codespace Creation Log
```Error: Command failed: docker-compose -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config```

When I go to the terminal and look for /var/lib/docker it seems to be missing

### Steps to reproduce:

 1. Fork repository
 2. Select "Create codespace on master"
 3. Error thrown``` "Codespace is running in recovery mode due to a configuration error"```
 4. Open log to find error ```2023-10-18 12:21:54.006Z: Exit code 1
2023-10-18 12:21:54.013Z: {"outcome":"error","message":"Command failed: docker-compose -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config","description":"An error occurred retrieving the Docker Compose configuration."}```

### Expected behavior:
Expected container to be created and to be able to enter the container command shell to complete next steps which are
1. run the command ```sudo apt-get update```

### Actual behavior:
Container is running in recovery mode and command fails with error 

### Additional notes:
see creation.log
[creation.log](https://github.com/instructure/canvas-lms/files/13024866/creation.log)

**Comment by ccutrer** [comment]
We don't currently plan on supporting GitHub Codespaces. We have started to add support for developing with the Docker extensions inside VSCode, and so now have a .devcontainer.json, so we may get to this at some point in the future.
