### ISSUE TITLE
About media preview

### ISSUE THREAD

**Issue by kenxt** [instructure/canvas-lms#2271]
### Summary:
we have a self-hosted canvas lms([stable/2023-08-30](https://github.com/instructure/canvas-lms/tree/stable/2023-08-30))，I uploaed a mp4 file to context files，when I open the mp4 file,  I can't not preview it. 
### Steps to reproduce:

 1.upload mp4 files to context files
 2.open the mp4 file
 3.can not  preview  the  mp4 file，if it is a picture, you can see preview it

### Expected behavior:
always can preview media files
### Actual behavior:
can not  preview  the  mp4 file
### Additional notes:
noting

Temporary Changes：
edit app/views/file_preview/media_preview.html.erb, according to img_ Preview.html.erb file:
[source.txt](https://github.com/instructure/canvas-lms/files/13174692/source.txt)
to:
[modified.txt](https://github.com/instructure/canvas-lms/files/13174704/modified.txt)

**Comment by ccutrer** [comment]
Media previews in Canvas rely on an external component - usually Kaltura, or something that is API compatible with Kaltura.

**Comment by kenxt** [comment]
> Media previews in Canvas rely on an external component - usually Kaltura, or something that is API compatible with Kaltura.

Thanks a lot, we have no Kaltura support our canvas,  so I think this method can be more friendly
