### ISSUE TITLE
How to generate a new key JWK

### ISSUE THREAD

**Issue by luongtu996** [instructure/canvas-lms#2275]
### Summary:
we have a self-hosted canvas lms. I dont know how to generate new jwk base on instruction in file `dynamic_settings.yml`.
<img width="841" alt="Screen Shot 2023-10-27 at 15 42 03" src="https://github.com/instructure/canvas-lms/assets/26574116/6f9da67d-3f4b-4d63-b2c1-94724b97ee3c">

### Steps to reproduce:

 1.
 2.
 3.

**Comment by luongtu996** [comment]
i found out. Just run

```
bundle exec rails console

# then

key = OpenSSL::PKey::RSA.generate(2048)
key.public_key.to_jwk(kid: Time.now.utc.iso8601).to_json


```

**Comment by prb01-work** [comment]
@luongtu996 I'm in a similar situation with trying to setup Canvas to test an LTI 1.3 tool. With regard to the private key that you generate in the first step, does that need to be added anywhere as well? How do you ensure that Canvas uses that private key to sign it's outgoing messages?

Any help appreciated!
