### ISSUE TITLE
export packages stay forever

### ISSUE THREAD

**Issue by amg-web** [instructure/canvas-lms#2295]
I noticed that export packages like **some-course-export.imscc** is not removed from file system or s3 after 30 days and stay in storage forever.

is it normal behavior? 

especially if space is limited or you pay for each used Gigabyte on s3

70% of them small but for some courses it can be up to **1Gb** of size.

same to files like **exported_data_cm_97.zip**

**Comment by Ardena** [comment]
There were plans to get these deleted on s3, but they weren't completed.

**Comment by amg-web** [comment]
it's strange for me
link removed in 30 days, but file does not. 

so, is it safe to remove such files older then 30 days at least if local file storage?
