### ISSUE TITLE
.JPEG and .JPG are Treated as Different File Types When Restricting Assignment's Upload File Types

### ISSUE THREAD

**Issue by NateLevin1** [instructure/canvas-lms#2301]
### Summary:

When a student tries to submit a `.JPG` to an assignment that has been restricted to only `.JPEG`s, the student is blocked from doing so. Because both of these file extensions are used to represent the same image format, either should be allowed. Teachers should not have to remember to always add `jpeg` and `jpg` every time they want to allow an assignment to be submitted with the JPEG image format.

### Steps to reproduce:

 1. Create a new assignment
 2. Choose a Submission Type of "File Uploads"
 3. Check off Restrict Upload File Types
 4. Under "Allowed File Extensions", add in `jpeg`
 5. Go to submit the assignment as a student account
 6. Attempt to upload a file with the `.jpg` extension

### Expected behavior:

The `.jpg` is uploaded & submitted.

### Actual behavior:

Canvas prevents the user from uploading their submission.

### Additional notes:

See also: [JPG vs. JPEG: Is There a Difference?](https://www.indeed.com/career-advice/career-development/jpg-vs-jpeg)

**Comment by maths22** [comment]
Canvas does not intend to maintain a list of all file extensions that are equivalent for all file types.  While we could make a special-case for jpg/jpeg, we are not going to do this at this time.
