### ISSUE TITLE
Invalid Authenticity Token on Login

### ISSUE THREAD

**Issue by JamesKainer** [instructure/canvas-lms#2319]
### Summary:

Login page shows "Invalid Authenticity Token" when logging in with no other information or errors in logs after going through the production startup instructions. All services are up and running

### Steps to reproduce:

 1. Follow the https://github.com/instructure/canvas-lms/wiki/Production-Start
 2.:Log in with the user created during installation

### Expected behavior:
1. Expect to log in or have some feedback on the error to fix

### Actual behavior:
Invalid authenticity token error popup with nothing in logs

### Additional notes:

Tried all suggestions I could find on the Canvas community or otherwises. No change in behaviour.

**Comment by JamesKainer** [comment]
If anyone runs into this, it can be the SSL configuration.

**Comment by kersta-staden** [comment]
I ran into the same problem. Do you remember how you fixed it?
