### ISSUE TITLE
message popover cannot be closed after sending a message since commit c638a66949f34ba7d438964687047985a20d5ada

### ISSUE THREAD

**Issue by breiter** [instructure/canvas-lms#2365]
### Summary:

https://github.com/instructure/canvas-lms/commit/c638a66949f34ba7d438964687047985a20d5ada fixes a jquery issue where the attachment button did not work and logged javascript exceptions in issue #2343.

The commit resolves the attachment problem but introduces a problem:

Prior to sending a message you can close the message popover by clicking "cancel" or "x". After a message is sent the popover does not close and cannot be closed by the user. The "cancel" and "x" do not work. Also the attachment icon does not work at this point.

### Steps to reproduce:

 1. Compose a message
 2. Send a message (message sent briefly appears)
 3. Message compose remains visually unchanged and does not go away on its own. Additionally, the "cancel", "x", and attachment buttons no longer work.

### Expected behavior:

Message window should close or alternatively be reset to compose a new message. If the message window does not close on its own the "x", "cancel", and attachment buttons should work.

### Actual behavior:

Compose window remains after sending and retains state. User can send the message over and over but cannot close the window. 

### Additional notes:

This broken UX results in users generating many duplicate messages.

**Comment by omarpr** [comment]
Any particular reason on why you are using the legacy inbox when we are now using the new react_inbox?

**Comment by breiter** [comment]
I don't think there is a strong reason other than the site admin not having enabled it. Will that setting resolve the problem?

**Comment by breiter** [comment]
Enabling "Update Inbox page to use react/instui" does not solve this problem.

**Comment by omarpr** [comment]
That's odd. It should solve the issue since the new React Inbox doesn't depend on jQuery. We would recommend to do that since we also have plans on removing soon the code for legacy inbox which we now consider dead code.

If after this you think the functionality you are accessing is visible even when using the new feature flag, can you expand the repro steps so we can take a closer look?

**Comment by breiter** [comment]
Inbox.

<img width="1214" alt="image" src="https://github.com/instructure/canvas-lms/assets/3965197/c2235573-426d-4787-ae66-e5269439fcc7">

Click compose message.

<img width="1214" alt="image" src="https://github.com/instructure/canvas-lms/assets/3965197/82f93e01-7051-40ff-b8e7-35ba987d5f76">

Click send.
<img width="1214" alt="image" src="https://github.com/instructure/canvas-lms/assets/3965197/3abf7da7-f71b-48ce-9ad5-4e6810c05824">

X, cancel, and attachment buttons now do not work. Compose window remains with the same content.

<img width="1214" alt="image" src="https://github.com/instructure/canvas-lms/assets/3965197/fcccbece-f749-4ad5-8406-9367c149af4c">

I discovered that I can click on the compose button in the "layer" behind the compose message  window. 

<img width="1214" alt="image" src="https://github.com/instructure/canvas-lms/assets/3965197/98c8efbc-ae92-4c1f-8d66-88cb3cc461ea">

This resets the window and makes the X and cancel buttons work.
<img width="1214" alt="image" src="https://github.com/instructure/canvas-lms/assets/3965197/395b94c8-1c59-4619-8b98-1b1f9b9b7a4d">


Nothing interesting is logged to the console.

changing the inbox react settings doesn't change the behavior.

<img width="1214" alt="image" src="https://github.com/instructure/canvas-lms/assets/3965197/1f14f3ce-7399-4b8a-9287-6139fdf8a3a1">

**Comment by omarpr** [comment]
Seems like you are having a server caching issue when changing the feature flag. That is indeed legacy inbox and we are removing that code very soon so it is a good time to figure out why your feature flag change isn't being recognized and fix it. 

I have heard that you can try restarting your server after you change the feature flag to see if that helps with the caching issue.

**Comment by breiter** [comment]
Yes. It is a caching issue and the React version does work once the cache expires.

<img width="1173" alt="image" src="https://github.com/instructure/canvas-lms/assets/3965197/faabfc1a-2dd4-4174-bfdd-70fa81b01b92">

**Comment by omarpr** [comment]
Awesome. Seems like we are good to close this issue! :)
