### ISSUE TITLE
student discussion comments do not appear in speedgrader stable/2024-09-25

### ISSUE THREAD

**Issue by breiter** [instructure/canvas-lms#2418]
### Summary:

Upon upgrade to origin/stable/2024-09-25 (release/2024-09-25.197) from origin/stable/2024-08-28 (release/2024-08-28.236) we have encountered an issue where student comments on a discussion will submit successfully but do not appear in the Speedgrader. They do however appear in the grading module for the assignments.

### Steps to reproduce:

 1. Create graded discussion
 2. Student submits a comment on the discussion
 3. Comment does not appear in Speedgrader but does appear in the discussion view and in the assignments submission details.

### Expected behavior:

Comment should appear in speedgrader.

### Actual behavior:

Speedgrader shows message "This student does not have a submission for this assignment" message

### Additional notes:

<img width="1297" alt="Screenshot 2024-10-07 at 16 40 37" src="https://github.com/user-attachments/assets/82f21784-c67d-493b-8049-ae9043576e09">
<img width="1297" alt="Screenshot 2024-10-07 at 16 41 09" src="https://github.com/user-attachments/assets/40d9ece9-208e-4658-b097-13faa89580c8">

**Comment by kenxt** [comment]
Has the deadline for the task passed.

**Comment by breiter** [comment]
@kenxt no the deadline was not passed when generating this test submission.

**Comment by breiter** [comment]
This was caused by the job queue being stuck at 100% CPU utilization.
