### ISSUE TITLE
.idml files (Indesign markup language) download as .zip files

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#243]
I have an instructor who has uploaded InDesign .idml files to his course. When users download the file, it changes the file extension to .zip. You can open the file by renaming it and changing the extension back to .idml.

**Comment by claydiffrient** [comment]
@christopher-b Can you verify that this is still happening for you?  I believe it might have been resolved with our newest iteration of files.

**Comment by christopher-b** [comment]
Nope, it appears to be working properly now. Thanks.
