### ISSUE TITLE
Canvas LMS password reset via phpPgAdmin or phpMyAdmin

### ISSUE THREAD

**Issue by EugeneWHZ** [instructure/canvas-lms#249]
Hi,

I am trying to reset password for admin user, but password reset via email is not working for me. How can I reset password via phpPgAdmin or phpMyAdmin?

Thanks!
Eugene

**Comment by jonmjo** [comment]
Can't find console under scripts (canvas/scripts).

**Comment by ccutrer** [comment]
`script/console` is the old name for it from when we were running Rails 2. Under Rails 3 it has been renamed to `script/rails console`

**Comment by johnkarasev** [comment]
`rescue in block in connect': FATAL:  role "root" does not exist (ActiveRecord::NoDatabaseError) I get this error when I try
