### ISSUE TITLE
Clear notifications after deleting course

### ISSUE THREAD

**Issue by checkraiser** [instructure/canvas-lms#272]
Hi.
I'm trying deleting permantly a course in Canvas, but after deleting, the notifications in user dashboard is still there and they were also not expired after 1 day. Do you know how to clear old notifications ?

**Comment by claydiffrient** [comment]
@checkraiser I'm sorry that we haven't responded to you about this sooner.  I haven't been able to come up with a good use case for this happening.  Generally courses that are far enough along to have notifications showing shouldn't be deleted.  I could see this potentially happening for test courses though.  Here's a bit of Rails Console magic that you could apply to get rid of notifications for the course.

```ruby
StreamItem.select { |c| c.context_type == 'Course' && c.context_id == COURSEID }.each { |si| si.destroy() }
```
You would replace `COURSEID` with an actually course id and that would do it.

I'm going to close the issue now, but if you still have problems please let us know.
