### ISSUE TITLE
Preview PDF offline

### ISSUE THREAD

**Issue by tiquay** [instructure/canvas-lms#273]
Hi,

I am trying to build Canvas LMS as our internal training system. Unfortunately, we are not allowed to share our documents on Google Docs,... so I tried to render PDF file with some offline methods PDF.js but I failed. Do you have any experiences in this problem, please share with me, thanks!

Regards,

**Comment by claydiffrient** [comment]
@tiquay I'm sorry that we haven't responded to this sooner. I've used PDF.js on a project with a former employer, but I've got no experience trying to integrate it into Canvas for PDF viewing.  It'd be interesting to know if you made it work and how you did it.  I'm going to close the issue for now.
