### ISSUE TITLE
Unknown column 'user_account_associations.account_id'

### ISSUE THREAD

**Issue by mikerowe81** [instructure/canvas-lms#279]
Just update to latest stable commit:2013-03-09 without any problems and I'm getting the following error when I try to open or send a message through "inbox"

#38918 Mysql::Error: Unknown column 'user_account_associations.account_id' in 'on cl...

account: eCampusWeb
category: default
created at: 2013-03-16 10:17:43 -0400
user: Michael Rowe
url: https://canvas.domain/conversations
request context id: 312ad5c0-7072-0130-c238-525400a507d4 
HTTP_ACCEPT: application/json, text/javascript, */*; q=0.01 
HTTP_ACCEPT_ENCODING: gzip,deflate,sdch 
HTTP_COOKIE: __utma=241681183.24169084.1356455290.1361573921.1361584353.11; __utmb=241681183.33.9.1363443435664; __utmc=241681183; __utmz=241681183.1361323366.9.2.utmcsr=localhost|utmccn=(referral)|utmcmd=referral|utmcct=/; __utmv=241681183.|1=School=unknown=1^3=UserID=1=1; __utma=241681183.24169084.1356455290.1361573921.1361584353.11; __utmb=241681183.33.9.1363443435664; __utmc=241681183; __utmz=241681183.1361323366.9.2.utmcsr=localhost|utmccn=(referral)|utmcmd=referral|utmcct=/; __utmv=241681183.|1=School=unknown=1^3=UserID=1=1; _normandy_session=HqWedSjCL4FYvROQfu1omw+piSowTAb83HXqywO5TJX3RbkICJTKIVAjmHRxVKHGIRfAaCYn36dDU-5eR0Rmef7g4z6S1cIr0FswJOkx4EcVGDif7Cc5-mXCGsqG6LvtqvIKdgGBkNjHjoExDGQ8dPcvx3REoFd7YPsGplbr7jpCaVG7apZLhBurJCqZfsg4X6DGRYKU_GqAZoaso4s4aK_8G97wOB1WPU4SL6z7x5QB8QJcxG-3mSSxOjB-g7BGAaduvC-kaItaIjiMNaqvzkH_cC2DY6LO7dpOG0gpsT8KcJEVcdHcENmvNyARHYxpruPQe8tDhlIC0hapPOt2PTZU6auTbS3qoIDQzUvgfoHUg.j5kImE6wGJWkcau9sDN3BOaQ8Bk.UUR-9A 
HTTP_HOST: canvas.domain 
HTTP_REFERER: https://canvas.domain/conversations 
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.33 Safari/537.31 
PATH_INFO: /conversations 
QUERY_STRING: ? 
REMOTE_ADDR: 173.80.15.25 
REQUEST_METHOD: POST 
REQUEST_URI: /conversations 
SERVER_NAME: canvas.domain 
SERVER_PORT: 443 
SERVER_PROTOCOL: HTTP/1.1 
format: application/json 
path_parameters: {"controller"=>"conversations", "action"=>"create"} 
query_parameters: {} 
request_parameters: {"from_conversation_id"=>"", "filter"=>"", "_method"=>"post", "body"=>"This is a test message.", "recipients"=>["504"], "token_capture"=>"", "authenticity_token"=>"k3xIyCoqbjPdY87Xre6zbG0OylVYQeBehs1hSYavwo8=", "mode"=>"async", "scope"=>""} 
        Mysql::Error: Unknown column 'user_account_associations.account_id' in 'on clause': SELECT users.id, users.short_name, users.name, users.avatar_image_url, users.avatar_image_source, group_concat(0 || ':' ||       (SELECT enrollments.type
      FROM enrollments
      INNER JOIN courses ON courses.id=enrollments.course_id
      INNER JOIN course_account_associations ON
        course_account_associations.course_id=courses.id AND
        course_account_associations.account_id=user_account_associations.account_id
      WHERE enrollments.user_id=user_account_associations.user_id
        AND (( enrollments.workflow_state = 'active' and ((courses.workflow_state = 'claimed' and enrollments.type IN ('TeacherEnrollment', 'TaEnrollment', 'DesignerEnrollment', 'StudentViewEnrollment')) or (courses.workflow_state = 'available')) ) OR ( enrollments.workflow_state = 'invited' and ((courses.workflow_state = 'available' and (enrollments.type = 'StudentEnrollment' or enrollments.type = 'ObserverEnrollment')) or (courses.workflow_state != 'deleted' and (enrollments.type IN ('TeacherEnrollment', 'TaEnrollment', 'DesignerEnrollment', 'StudentViewEnrollment')))))) AND enrollments.type != 'StudentViewEnrollment'
      ORDER BY CASE WHEN enrollments.type IN ('TeacherEnrollment') THEN 0 WHEN enrollments.type IN ('TaEnrollment') THEN 1 WHEN enrollments.type IN ('DesignerEnrollment') THEN 2 WHEN enrollments.type IN ('StudentEnrollment') THEN 3 WHEN enrollments.type IN ('StudentViewEnrollment') THEN 4 WHEN enrollments.type IN ('ObserverEnrollment') THEN 5 ELSE 6 END
      LIMIT 1)
 SEPARATOR ',') AS common_courses, NULL AS common_groups FROM `users`  INNER JOIN user_account_associations ON user_account_associations.user_id=users.id WHERE (((`user_account_associations`.`account_id` IN (1,2) AND `users`.`id` IN (504))) AND (users.workflow_state IN ('registered', 'pre_registered')))  GROUP BY users.id ORDER BY LOWER(COALESCE(users.short_name, users.name)), users.id

        /var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract_adapter.rb:227:in `log'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/connection_adapters/mysql_adapter.rb:324:in `execute'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/connection_adapters/mysql_adapter.rb:639:in `select'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in `select_all_without_query_cache'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract/query_cache.rb:60:in `select_all'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract/query_cache.rb:81:in `cache_sql'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract/query_cache.rb:60:in `select_all'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/base.rb:665:in `find_by_sql'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/base.rb:1582:in `find_every'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/base.rb:619:in `find'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:183:in `send'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:183:in `method_missing'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/base.rb:2186:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `__send__'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:182:in `method_missing'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/base.rb:2186:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `__send__'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:179:in `method_missing'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:186:in `send'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:186:in `method_missing'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/base.rb:2186:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `__send__'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `__send__'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:179:in `method_missing'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:186:in `send'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:186:in `method_missing'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/base.rb:2186:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `__send__'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `__send__'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `__send__'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:118:in `with_scope'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:179:in `method_missing'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:193:in `load_found'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:171:in `proxy_found'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/named_scope.rb:114:in `each'
/var/rails/canvas/lib/messageable_user/calculator.rb:210:in `load_common_courses_with_users'
/var/rails/canvas/lib/stubs/shard.rb:38:in `with_each_shard'
/var/rails/canvas/lib/messageable_user/calculator.rb:206:in `load_common_courses_with_users'
/var/rails/canvas/lib/messageable_user/calculator.rb:93:in `load_messageable_users'
/var/rails/canvas/lib/messageable_user/calculator.rb:35:in `load_messageable_users'
/var/rails/canvas/app/models/user.rb:2369:in `load_messageable_users'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/associations/association_proxy.rb:215:in `send'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/associations/association_proxy.rb:215:in `method_missing'
/var/rails/canvas/app/controllers/conversations_controller.rb:730:in `normalize_recipients'
/var/lib/gems/1.8/gems/activesupport-2.3.17/lib/active_support/callbacks.rb:178:in `send'
/var/lib/gems/1.8/gems/activesupport-2.3.17/lib/active_support/callbacks.rb:178:in `evaluate_method'
/var/lib/gems/1.8/gems/activesupport-2.3.17/lib/active_support/callbacks.rb:166:in `call'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/filters.rb:225:in `call'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/filters.rb:629:in `run_before_filters'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/filters.rb:615:in `call_filters'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/filters.rb:638:in `run_before_filters'
/var/rails/canvas/app/controllers/application_controller.rb:113:in `set_locale'
/var/lib/gems/1.8/gems/activesupport-2.3.17/lib/active_support/callbacks.rb:178:in `send'
/var/lib/gems/1.8/gems/activesupport-2.3.17/lib/active_support/callbacks.rb:178:in `evaluate_method'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/filters.rb:186:in `call'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/filters.rb:635:in `run_before_filters'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/filters.rb:615:in `call_filters'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/var/lib/gems/1.8/gems/activesupport-2.3.17/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/var/lib/gems/1.8/gems/activesupport-2.3.17/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/flash.rb:151:in `perform_action'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/base.rb:532:in `send'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/base.rb:532:in `process_without_filters'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/filters.rb:606:in `process_without_compass'
/var/lib/gems/1.8/gems/compass-rails-1.0.2/lib/compass-rails/railties/2_3.rb:9:in `process'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/base.rb:391:in `process'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/base.rb:386:in `call'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/routing/route_set.rb:438:in `call'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:87:in `dispatch'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:121:in `_call'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:29:in `call'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:29:in `call'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:9:in `cache'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:28:in `call'
/var/lib/gems/1.8/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
/var/lib/gems/1.8/gems/sass-3.2.1/rails/../lib/sass/plugin/rack.rb:54:in `call'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/string_coercion.rb:25:in `call'
/var/lib/gems/1.8/gems/rack-1.1.3/lib/rack/head.rb:9:in `call'
/var/lib/gems/1.8/gems/rack-1.1.3/lib/rack/methodoverride.rb:24:in `call'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/params_parser.rb:15:in `call'
/var/rails/canvas/vendor/plugins/respondus_soap_endpoint/lib/respondus_api_middleware.rb:60:in `call'
/var/rails/canvas/lib/request_context_generator.rb:34:in `call'
/var/rails/canvas/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
/var/rails/canvas/app/middleware/stats_timing.rb:8:in `call'
/var/lib/gems/1.8/gems/activesupport-2.3.17/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/var/lib/gems/1.8/gems/activesupport-2.3.17/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/var/rails/canvas/app/middleware/stats_timing.rb:8:in `call'
/var/rails/canvas/app/middleware/load_account.rb:12:in `call'
/var/rails/canvas/app/middleware/sessions_timeout.rb:24:in `call'
/var/lib/gems/1.8/gems/encrypted_cookie_store-instructure-1.0.2/lib/encrypted_cookie_store.rb:32:in `call'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/failsafe.rb:26:in `call'
/var/lib/gems/1.8/gems/rack-1.1.3/lib/rack/lock.rb:11:in `call'
/var/lib/gems/1.8/gems/rack-1.1.3/lib/rack/lock.rb:11:in `synchronize'
/var/lib/gems/1.8/gems/rack-1.1.3/lib/rack/lock.rb:11:in `call'
/var/lib/gems/1.8/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:106:in `call'
/usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:96:in `process_request'
/usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
/usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
/usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
/usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:171:in `send'
/usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:171:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/utils.rb:470:in `safe_fork'
/usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:357:in `__send__'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:180:in `start'
/usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:129:in `start'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:253:in `spawn_rack_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:246:in `spawn_rack_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:357:in `__send__'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/usr/share/phusion-passenger/helper-scripts/passenger-spawn-server:99

**Comment by claydiffrient** [comment]
I'm going to go ahead and close this ticket because of lack of response from the original reporters.
