### ISSUE TITLE
Feature request - Adobe Connect plugin new users SIS IDs

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#282]
The Adobe Connect plugin will create new user accounts in Connect when the user first enters a meeting created through Canvas. The username for the new user account will be canvas_user_{canvas_user_id}. It would be nice to have the option to use the user's SIS ID instead.

There are a few problems with creating new user accounts, using an arbitrary username: 
* If the user is already logged in with an existing Connect account, when they enter a meeting, they will be added to the metting as participants, even if they are an instructors in the course, and should be added to the room as an admin. 

* If they are not logged in already, they will be logged in under the new username, rather than their existing username. This means that they will enter the meeting room with the correct role, but if they go the Connect dashboard screen, none of their other meetings or other access (admin privs, etc) will be available.

* It creates more connect users than necessary, causes clutter, may cause incorrect information on reports. 

The rationale for using the SIS ID instead is that it's likely that the user's institutional username will be their login for Connect. If they're logging into Canvas with a certain username, it will probably be their Connect username too. 

A simple checkbox on the settings screen would probably do the job :)

**Comment by claydiffrient** [comment]
@christopher-b It looks like this request was completed.  That plugin appears to have a checkbox for it now.  I'm going to go ahead and close the issue.
