### ISSUE TITLE
 ActionView::TemplateError (undefined method `compact' for {}:Hash)

### ISSUE THREAD

**Issue by checkraiser** [instructure/canvas-lms#291]
I have a quiz, which i've created. Then a student took it partly (still not submitted). Then i edited my quiz and re open it for all students. Now when that student continued the quiz, i got the following error:

        
ActionView::TemplateError (undefined method `compact' for {}:Hash) on line #3 of app/views/quizzes/_question_list_right_side.html.erb:
1: <h3 style="margin: 0px;"><%= t('headers.questions', "Questions") %></h3>
2: <ul id="question_list" style="max-height: 200px; overflow: auto;" class="<%= 'read_only' if @quiz_presenter.cant_go_back? %>">
3:   <% @quiz_presenter.all_questions.each do |q| %>
4:     <li id="list_question_<%= q[:id] %>" class="<%= @quiz_presenter.question_class(q) %>">
5:     <% if @quiz_presenter.one_question_at_a_time? %>
6:       <% if @quiz_presenter.cant_go_back? || @quiz_presenter.require_lockdown_browser? %>

    app/presenters/take_quiz_presenter.rb:32:in `all_questions'
    app/views/quizzes/_question_list_right_side.html.erb:3
    app/views/quizzes/_take_quiz_right_side.html.erb:6
    app/views/quizzes/take_quiz.html.erb:4
    app/views/quizzes/take_quiz.html.erb:3
    app/controllers/application_controller.rb:1310:in `render'
    app/controllers/quizzes_controller.rb:589:in `take_quiz'
    app/controllers/quizzes_controller.rb:189:in `show'
    app/controllers/application_controller.rb:117:in `set_locale'
    /home/rev/.rvm/gems/ree-1.8.7-2012.02/gems/compass-rails-1.0.3/lib/compass-rails/railties/2_3.rb:9:in `process'
    sass (3.2.3) rails/./lib/sass/plugin/rack.rb:54:in `call'
    lib/request_context_generator.rb:34:in `call'
    app/middleware/prevent_non_multipart_parse.rb:32:in `call'
    app/middleware/stats_timing.rb:8:in `call'
    app/middleware/stats_timing.rb:8:in `call'
    app/middleware/load_account.rb:12:in `call'
    app/middleware/sessions_timeout.rb:24:in `call'
    puma (0.8.0) lib/puma/server.rb:249:in `handle_request'
    puma (0.8.0) lib/puma/server.rb:145:in `process_client'
    puma (0.8.0) lib/puma/server.rb:81:in `run'
    puma (0.8.0) lib/puma/thread_pool.rb:52:in `call'
    puma (0.8.0) lib/puma/thread_pool.rb:52:in `spawn_thread'
    puma (0.8.0) lib/puma/thread_pool.rb:35:in `initialize'
    puma (0.8.0) lib/puma/thread_pool.rb:35

        On line #3 of app/views/quizzes/_question_list_right_side.html.erb

    1: <h3 style="margin: 0px;"><%= t('headers.questions', "Questions") %></h3>
    2: <ul id="question_list" style="max-height: 200px; overflow: auto;" class="<%= 'read_only' if @quiz_presenter.cant_go_back? %>">
    3:   <% @quiz_presenter.all_questions.each do |q| %>
    4:     <li id="list_question_<%= q[:id] %>" class="<%= @quiz_presenter.question_class(q) %>">
    5:     <% if @quiz_presenter.one_question_at_a_time? %>
    6:       <% if @quiz_presenter.cant_go_back? || @quiz_presenter.require_lockdown_browser? %>

    app/presenters/take_quiz_presenter.rb:32:in `all_questions'
    app/views/quizzes/_question_list_right_side.html.erb:3
    app/views/quizzes/_take_quiz_right_side.html.erb:6
    app/views/quizzes/take_quiz.html.erb:4
    app/views/quizzes/take_quiz.html.erb:3
    app/controllers/application_controller.rb:1310:in `render'
    app/controllers/quizzes_controller.rb:589:in `take_quiz'
    app/controllers/quizzes_controller.rb:189:in `show'
    app/controllers/application_controller.rb:117:in `set_locale'
    /home/rev/.rvm/gems/ree-1.8.7-2012.02/gems/compass-rails-1.0.3/lib/compass-rails/railties/2_3.rb:9:in `process'
    sass (3.2.3) rails/./lib/sass/plugin/rack.rb:54:in `call'
    lib/request_context_generator.rb:34:in `call'
    app/middleware/prevent_non_multipart_parse.rb:32:in `call'
    app/middleware/stats_timing.rb:8:in `call'
    app/middleware/stats_timing.rb:8:in `call'
    app/middleware/load_account.rb:12:in `call'
    app/middleware/sessions_timeout.rb:24:in `call'
    puma (0.8.0) lib/puma/server.rb:249:in `handle_request'
    puma (0.8.0) lib/puma/server.rb:145:in `process_client'
    puma (0.8.0) lib/puma/server.rb:81:in `run'
    puma (0.8.0) lib/puma/thread_pool.rb:52:in `call'
    puma (0.8.0) lib/puma/thread_pool.rb:52:in `spawn_thread'
    puma (0.8.0) lib/puma/thread_pool.rb:35:in `initialize'
    puma (0.8.0) lib/puma/thread_pool.rb:35

Do you know which is this error ? And how to allow that student take the quiz again ?

**Comment by vogelbek** [comment]
Hi All,

Researching this bug a bit, it came up that the Hash Compact method is only valid for >= Rails 4.1:
http://api.rubyonrails.org/v4.0.10/ #=> No compact() or compact!()
http://api.rubyonrails.org/v4.1.9/ #=> compact() and compact!() are now defined.

You might check the rails version your Canvas is running. If you have an older version, you may be able to monkey patch with this approach: http://stackoverflow.com/a/14773555

**Comment by ccutrer** [comment]
It should be noted that you don't get to choose which version of Rails Canvas runs with. It's controlled by the Gemfile - right now it's locked to 3.2.21. So any attempt to use #compact means the code expected an Array, not a Hash.

**Comment by jenseng** [comment]
It shouldn't actually be calling `.compact` on a hash, it should operate on an array. Even on the latest, the code looks problematic... see [here](https://github.com/instructure/canvas-lms/blob/fbec7fa/app/presenters/quizzes/take_quiz_presenter.rb#L37) and [here](https://github.com/instructure/canvas-lms/blob/fbec7fa/app/models/quizzes/quiz_submission.rb#L361). If `QuizSubmission#quiz_data` is set (normally always an array), it works fine. If `#quiz_data` is nil, `QuizSubmission#questions_as_object` returns a hash, and it all blows up. So we should probably change that `{}` to a `[]`

**Comment by simonista** [comment]
Looks like this is now fixed, so I'm closing it out.
