### ISSUE TITLE
Can not add external tools to canvas

### ISSUE THREAD

**Issue by sub2u** [instructure/canvas-lms#295]
Processing ExternalToolsController#create (for 106.66.170.73 at 2013-04-24 21:57:56) [POST]
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368]   Parameters: {"_method"=>"POST", "authenticity_token"=>"/D9jNFiALN+WqX3F/RYVJOneEQnWA/mMBEkJqBeBfgo=", "external_tool"=>{"name"=>"gggggggggggg", "consumer_key"=>"jkkkkkkkkkkkkkkkk", "shared_secret"=>"dfsdfdsf", "config_type"=>"by_url", "config_url"=>"https://lti-examples.heroku.com/tools/youtube/config.xml", "config_xml"=>"", "url"=>"", "domain"=>"", "privacy_level"=>"anonymous", "custom_fields_string"=>"", "description"=>""}, "controller"=>"external_tools", "action"=>"create", "account_id"=>"2"}
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368] No separate files host specified for account id 1.  This is a potential security risk.
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368]   Pseudonym Load (1.0ms)   SELECT * FROM "pseudonyms" WHERE ("pseudonyms"."id" = 1) LIMIT 1
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368]   User Load (0.8ms)   SELECT * FROM "users" WHERE ("users"."id" = 1) 
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368]   Setting Load (0.2ms)   SELECT * FROM "settings" WHERE ("settings"."name" = 'enable_page_views') LIMIT 1
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368]   Account Load (0.4ms)   SELECT * FROM "accounts" WHERE ("accounts"."id" = 2) 
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368]   AccountUser Load (0.3ms)   SELECT * FROM "account_users" WHERE ("account_users"."user_id" = 1) AND ("account_users".account_id = 2) LIMIT 1
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368] Cache miss: context_permissions/accounts/2-20130425024307/users/1-20130425024310 ({:expires_in=>3600 seconds})
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368]   Setting Load (0.3ms)   SELECT * FROM "settings" WHERE ("settings"."name" = 'site_admin_account_id') LIMIT 1
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368] Cache miss: _account_lookup2/2 ({:expires_in=>3600 seconds})
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368]   Account Load (0.3ms)   SELECT * FROM "accounts" WHERE ("accounts"."id" = '2') LIMIT 1
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368] Cache write (will save 0.69ms): _account_lookup2/2
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368] Cache miss: all_site_admin_account_users ({:expires_in=>1800 seconds})
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368]   AccountUser Load (0.2ms)   SELECT * FROM "account_users" WHERE ("account_users".account_id = 2) 
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368] Cache write (will save 0.61ms): all_site_admin_account_users
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368]   RoleOverride Load (0.6ms)   SELECT * FROM "role_overrides" WHERE ("role_overrides"."context_id" IN (2,2) AND "role_overrides"."enrollment_type" = 'AccountAdmin') ORDER BY CASE WHEN context_id='2' THEN 0 WHEN context_id='2' THEN 1 ELSE 9999 END DESC
[223d5e9873a9f80abf6982299db2a45d da170670-8f81-0130-5a64-005056010368] Cache write (will save 15.02ms): context_permissions/accounts/2-20130425024307/users/1-20130425024310
[- -] Cache miss: settings_for_plugin/sessions ({:expires_in=>300 seconds})
[- -]   SQL (0.1ms)   SET client_min_messages TO 'panic'
[- -]   SQL (0.1ms)   SET standard_conforming_strings = on
[- -]   SQL (0.1ms)   SET client_min_messages TO 'notice'
[- -]   PluginSetting Load (0.9ms)   SELECT * FROM "plugin_settings" WHERE ("plugin_settings"."name" = 'sessions') LIMIT 1
[- -] Cache write (will save 13.39ms): settings_for_plugin/sessions
[- -]   Setting Load (0.4ms)   SELECT * FROM "settings" WHERE ("settings"."name" = 'default_account_id') LIMIT 1
[- -] Cache miss: _account_lookup2/1 ({:expires_in=>3600 seconds})
[- -]   Account Load (1.0ms)   SELECT * FROM "accounts" WHERE ("accounts"."id" = '1') LIMIT 1
[- -] Cache write (will save 5.73ms): _account_lookup2/1
[223d5e9873a9f80abf6982299db2a45d db562740-8f81-0130-578d-005056010368] 

Processing ApplicationController#index (for 106.66.170.73 at 2013-04-24 21:57:59) [GET]
[223d5e9873a9f80abf6982299db2a45d db562740-8f81-0130-578d-005056010368] 
ActionController::RoutingError (No route matches "/500.shtml" with {:method=>:get}):
  vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/routing/recognition_optimisation.rb:66:in `recognize_path'
  vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/routing/route_set.rb:442:in `recognize'
  vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/routing/route_set.rb:437:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:87:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:121:in `_call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:130:in `block in build_middleware_stack'
  vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:29:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:29:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
  vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:9:in `cache'
  vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:28:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
  vendor/bundle/ruby/1.9.1/gems/sass-3.2.3/lib/sass/plugin/rack.rb:54:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/string_coercion.rb:25:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/params_parser.rb:15:in `call'
  lib/request_context_generator.rb:34:in `call'
  app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  app/middleware/stats_timing.rb:8:in `block in call'
  app/middleware/stats_timing.rb:8:in `call'
  app/middleware/load_account.rb:12:in `call'
  app/middleware/sessions_timeout.rb:24:in `call'
  vendor/bundle/ruby/1.9.1/gems/encrypted_cookie_store-instructure-1.0.2/lib/encrypted_cookie_store.rb:32:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/failsafe.rb:26:in `call'
  <internal:prelude>:10:in `synchronize'
  vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:106:in `call'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/utils.rb:470:in `safe_fork'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:180:in `start'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in `synchronize'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/helper-scripts/passenger-spawn-server:99:in `<main>'

[223d5e9873a9f80abf6982299db2a45d db562740-8f81-0130-578d-005056010368]   SQL (0.1ms)   BEGIN
[223d5e9873a9f80abf6982299db2a45d db562740-8f81-0130-578d-005056010368]   SQL (1.1ms)   INSERT INTO "error_reports" ("backtrace", "url", "message", "comments", "user_id", "created_at", "updated_at", "email", "during_tests", "user_agent", "request_method", "http_env", "subject", "request_context_id", "account_id", "zendesk_ticket_id", "data", "category") VALUES('/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/routing/recognition_optimisation.rb:66:in `recognize_path''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/routing/route_set.rb:442:in `recognize''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/routing/route_set.rb:437:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:87:in `dispatch''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:121:in `_call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:130:in `block in build_middleware_stack''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:29:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:29:in `block in call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:9:in `cache''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/query_cache.rb:28:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/sass-3.2.3/lib/sass/plugin/rack.rb:54:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/string_coercion.rb:25:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.1.3/lib/rack/head.rb:9:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.1.3/lib/rack/methodoverride.rb:24:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/params_parser.rb:15:in `call''
/var/canvas/vendor/plugins/respondus_soap_endpoint/lib/respondus_api_middleware.rb:60:in `call''
/var/canvas/lib/request_context_generator.rb:34:in `call''
/var/canvas/app/middleware/prevent_non_multipart_parse.rb:32:in `call''
/var/canvas/app/middleware/stats_timing.rb:8:in `block in call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-2.3.17/lib/active_support/core_ext/benchmark.rb:17:in `block in ms''
/home/vsadmin/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/benchmark.rb:295:in `realtime''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-2.3.17/lib/active_support/core_ext/benchmark.rb:17:in `ms''
/var/canvas/app/middleware/stats_timing.rb:8:in `call''
/var/canvas/app/middleware/load_account.rb:12:in `call''
/var/canvas/app/middleware/sessions_timeout.rb:24:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/encrypted_cookie_store-instructure-1.0.2/lib/encrypted_cookie_store.rb:32:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/failsafe.rb:26:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.1.3/lib/rack/lock.rb:11:in `block in call''
<internal:prelude>:10:in `synchronize''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.1.3/lib/rack/lock.rb:11:in `call''
/var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-2.3.17/lib/action_controller/dispatcher.rb:106:in `call''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/utils.rb:470:in `safe_fork''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:180:in `start''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:129:in `start''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize''
<internal:prelude>:10:in `synchronize''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously''
/home/vsadmin/.rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/helper-scripts/passenger-spawn-server:99:in `<main>''', 'http://199.231.231.106/500.shtml', 'No route matches "/500.shtml" with {:method=>:get}', NULL, NULL, '2013-04-25 02:57:59.301595', '2013-04-25 02:57:59.301595', 'unknown-google-com@instructure.example.com', 'f', 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:20.0) Gecko/20100101 Firefox/20.0', '--- :get
', NULL, NULL, 'db562740-8f81-0130-578d-005056010368', NULL, NULL, '--- 
format: !ruby/object:Mime::Type 
 string: application/json
 symbol: :json
 synonyms: 
 - text/x-json
 - application/jsonrequest
HTTP_ACCEPT: application/json, text/javascript, */*; q=0.01
HTTP_ACCEPT_ENCODING: gzip, deflate
HTTP_COOKIE: _normandy_session=phCAOucsv5VqLWaAOfcabw+2azeMCNwRydNPnebP5c92qZzYv4YBTVYMJJa0giTVwuZBe-LefYDwQoVfdstIUQBhE6kWqzcsKNmnE8wNixDmBSpccRw_t7JUX9bIlRb9jR1aXSWpOpajt32VhHsAtvNYoRpjt_uu8rg72DNyhxQtOrTLzSbetHAVcBeTX-n5_W1Hp4jeKRLzr1emJ2hnYqjNMrHwcVxanKUfXalXTVMrxuku6kFcWSDhV8_KCw7xjtB8E87QPqEVmSbqUXOxH8iBntfaws16smRt7N21_uNdN4IAE9T-KOurEE8Iar0D8RynoJe3vbENF9gJx_c1g6vZxzczuxVgoIE_nVKW04itHC3QbOPJulSE79nlELGVFRaWDS3UzYngvv4vc9yoWHZz74BqE4fqE85ZtJUJ39scbPRduUEatdzyPDl4N4VgnI.vZUCxoUKHHEQBC6RixCwgNp9OsI.UXiZgA
HTTP_HOST: 199.231.231.106
HTTP_REFERER: http://199.231.231.106/accounts/2/settings
HTTP_USER_AGENT: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:20.0) Gecko/20100101 Firefox/20.0
PATH_INFO: /500.shtml
QUERY_STRING: "?"
REQUEST_METHOD: GET
REQUEST_URI: /500.shtml
SERVER_NAME: 199.231.231.106
SERVER_PORT: "80"
SERVER_PROTOCOL: HTTP/1.1
REMOTE_ADDR: 106.66.170.73
path_parameters: "{}"
query_parameters: "{}"
request_parameters: "{}"
exception_message: No route matches "/500.shtml" with {:method=>:get}
', '404') RETURNING "id"
[223d5e9873a9f80abf6982299db2a45d db562740-8f81-0130-578d-005056010368]   SQL (1.1ms)   COMMIT
[223d5e9873a9f80abf6982299db2a45d db562740-8f81-0130-578d-005056010368] Created ErrorReport ID 196

**Comment by simonista** [comment]
Hey @sub2u, sorry you never got a response about this.  It looks like there was some sort of error setting up your external tool, which was then masked by an error trying to return a 500 page: `No route matches "/500.shtml"`.  I'm confident that adding an external tool is working, so their may be some configuration issue or maybe custom code that you have added?  Let me know if this is still a problem on the latest stable branch for you.
