### ISSUE TITLE
Full URLs in emails broken

### ISSUE THREAD

**Issue by dmyers** [instructure/canvas-lms#299]
Links with the full URL are broken in emails, but not in the application, screenshots attached.

The link I am referring to is the one that says "Lightning Talk scheduling page".

![screen shot 2013-05-08 at 1 46 51 pm](https://f.cloud.github.com/assets/207171/479929/c7085f5a-b820-11e2-802f-7862cdbd8719.png)

![screen shot 2013-05-08 at 1 50 07 pm](https://f.cloud.github.com/assets/207171/479940/eb920100-b820-11e2-8277-a33d4929b39a.png)

**Comment by claydiffrient** [comment]
@dmyers @Kulgar I'm sorry for the delay in responding to this.  It appears that this bug has been taken care of now.  Please let me know if this is still an issue.
