### ISSUE TITLE
File types for assignment uploads are checked client-side with Javascript, not secure

### ISSUE THREAD

**Issue by ebol4anthr4x** [instructure/canvas-lms#306]
Javascript is editable client-side, students can easily bypass the file type check when uploading files to upload things other than .zips. I have tested this and can upload any files. This could be used to upload trojans and other undesirable things.

File types should be checked server-side.

**Comment by claydiffrient** [comment]
@ebol4anthr4x I'm sorry we haven't responded to you yet.  We are working to get better about responding here.  I believe that this check is now in place on the server.  It will upload the file, but it will not submit the assignment with it attached.  It basically just ends up in the user files.  I'm going to go ahead and close this, but if you find it's still an issue feel free to reopen.
