### ISSUE TITLE
Canvas_init

### ISSUE THREAD

**Issue by hovanessb** [instructure/canvas-lms#307]
sudo /etc/init.d/canvas_init start is returning
"No passwd entry for user 'UNKNOWN'"
Why is it doing this?

**Comment by claydiffrient** [comment]
@hovanessb @McDoku I'm sorry we haven't been responsive.  We're working on getting better.  Have you been able to resolve this issue.  It appears that the canvas_init file is in place with content in it now.  I'm going to close the issue, please let us know if it's not resolved for you though.
