### ISSUE TITLE
Internal Messages 

### ISSUE THREAD

**Issue by danry25** [instructure/canvas-lms#314]
It seems that you can't select multiple messages in your inbox and archive them at once like you can in most email frontends or messaging applications. I'd like to request this feature be added, seeing as it is a core feature of most email like communications systems.

Note: This was tested as a student on an Instructure run instance of Canvas.

**Comment by claydiffrient** [comment]
@danry25 I'm sorry that we haven't responded sooner.  It looks like this is now a feature that is in place.  You can select multiple messages by holding down the Ctrl/Cmd key and clicking each one. Then you can archive all the selected ones at once.  Thanks for letting us know about this.
