### ISSUE TITLE
change_password not working

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#317]
Dear Sir/Madam,

Request Password is not sending email to my email account. This happens after I have added a LDAP authentication service (change_password_url  is not specified). Users cannot reset their passwords now since the Request Password is not sending email. Do you know if this problem is somehow related to the authentication settings. Thanks.

Chi-Hou

**Comment by claydiffrient** [comment]
@cvong I'm sorry we haven't responded sooner.  Is this still happening for you?

**Comment by cvong** [comment]
I think it was fixed. Thanks.
