### ISSUE TITLE
Course import (Content Migration) Error

### ISSUE THREAD

**Issue by samuels410** [instructure/canvas-lms#320]
Hi,

We are not able to import the canvas course as  HTML  pages are formatted wrongly. We have debug the problem and the /spec/models/content_migration_spec.rb test-case are failing with the HTML <p> tag format errors. 

Following are the sample error output from the test.

             expected: "<p>some text</p>",
              got: "<p>[p[some text[/p[</p>" (using ==)
/home/sysadmin/dev/canvas-lms/spec/models/content_migration_spec.rb:88:in `block (3 levels) in <top (required)>'
/home/sysadmin/dev/canvas-lms/script/spec:10:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'

Is it a known issue and How do we fix this error?

**Comment by claydiffrient** [comment]
@samuels410 Sorry for the delayed response.  Is this still happening for you?

**Comment by samuels410** [comment]
@claydiffrient  the current version of the content_migration_spec.rb is 912a2cb date 15/10/14 ,

Finished in 114.259693154 seconds
99 examples, 0 failures, 19 pending,

Its fixed.

**Comment by claydiffrient** [comment]
Awesome great!
