### ISSUE TITLE
graded to ungraded quiz transformation get error

### ISSUE THREAD

**Issue by alekseyl** [instructure/canvas-lms#326]
If you had a graded quiz with an assignment and you change it quiz_type to "practice_quiz" you will get an error trying to save it.

Key to understanding issue ( quiz.rb ):

class Quiz < ...

before_save :set_defaults 
after_save :link_assignment_overrides, :if => :assignment_id_changed?

...

def set_defaults 
....

if (!graded? && self.assignment_id) || (self.assignment_id_was && self.assignment_id != self.assignment_id_was)
      @old_assignment_id = self.assignment_id_was
     #!!!!!!!!!!!!!!!!!! here assignment_id gets its new wonderful nil value
     self.assignment_id = nil
    end
...
end

def link_assignment_overrides
 .....
 fields = [:assignment_version, :assignment_id, :quiz_version, :quiz_id]
 overrides.flatten.each do |override|
      fields.each do |field|
        override.send(:"#{field}=", overrides_params[field])
      end
      # !!!!!!! here we will get an exception Validation failed: Set has already been taken
   
      override.save!
    end

end

possible reason for it ( schema.rb ):
 
add_index "assignment_overrides", ["assignment_id", "set_type", "set_id"], :name => "index_assignment_overrides_on_assignment_and_set", :unique => true

**Comment by claydiffrient** [comment]
@alekseyl Sorry we haven't responded sooner.  We're working to get better at this.  I guess you've probably figured this out or moved on by now.  Is this still and issue for you?
