### ISSUE TITLE
file upload HTTP error 422

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#335]
Dear Sir/Madam,

I can upload files everywhere except the Add Files link in the Files module of a course. I can add files through the rich content editor, uploading a zip file, and using the drag-drop method in Chrome and IE on Windows 7 (Note: I can upload files using Add Files on MacBook Pro). Do you know why the Add Files link works on Mac but not on Windows? Thanks.

Chi-Hou

**Comment by claydiffrient** [comment]
@cvong This issue should be resolved now. I'm going to close the issue.  If you find it's still a problem feel free to reopen it.
