### ISSUE TITLE
Wrong search_controller recipients behavior

### ISSUE THREAD

**Issue by alekseyl** [instructure/canvas-lms#336]
Go to line 94 you will see: 

types = (params[:types] || [] + [params[:type]]).compact

It works like this: (params[:types] ||     ( [] + [params[:type]] )      ).compact

clearly this variant got no sense, because you will always get params[:types] 

and [] + [params[:type]] is always equal to [params[:type]] 

I think you really mean this:

types = ( (params[:types] || []) + [params[:type]]).compact

**Comment by claydiffrient** [comment]
@alekseyl Thanks for letting us know about this.  Sorry for the delay since this.  I agree that the language on that dropdown is unclear.  I'll get a commit in changing the wording to reflect that it is an autocomplete dropdown rather than a list.  Thanks!
