### ISSUE TITLE
Problems with compile_assets on NetBSD

### ISSUE THREAD

**Issue by bugQ** [instructure/canvas-lms#342]
I know you probably don't officially support *BSD, but any ideas on these errors?

    bug$ bundle exec rake --trace canvas:compile_assets 
    ** Invoke canvas:compile_assets (first_time)
    ** Execute canvas:compile_assets
    --> Compiling static assets [css]
    ** Invoke css:generate (first_time)
    ** Execute css:generate
      warning Webkit only supports pixels for the start and end stops for radial gradients. Got: 100%
    ** Invoke css:styleguide (first_time)
    ** Execute css:styleguide
    --> creating styleguide
    /usr/pkg/lib/ruby/gems/1.9.3/gems/dress_code-1.0.2/lib/dress_code/extractor.rb:31:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
            from /usr/pkg/lib/ruby/gems/1.9.3/gems/dress_code-1.0.2/lib/dress_code/extractor.rb:31:in `scan'
            from /usr/pkg/lib/ruby/gems/1.9.3/gems/dress_code-1.0.2/lib/dress_code/extractor.rb:25:in `parse_file'
            from /usr/pkg/lib/ruby/gems/1.9.3/gems/dress_code-1.0.2/lib/dress_code/extractor.rb:20:in `block in parse_files'
            from /usr/pkg/lib/ruby/gems/1.9.3/gems/dress_code-1.0.2/lib/dress_code/extractor.rb:20:in `each'
            from /usr/pkg/lib/ruby/gems/1.9.3/gems/dress_code-1.0.2/lib/dress_code/extractor.rb:20:in `flat_map'
            from /usr/pkg/lib/ruby/gems/1.9.3/gems/dress_code-1.0.2/lib/dress_code/extractor.rb:20:in `parse_files'
            from /usr/pkg/lib/ruby/gems/1.9.3/gems/dress_code-1.0.2/lib/dress_code/extractor.rb:15:in `extract'
            from /usr/pkg/lib/ruby/gems/1.9.3/gems/dress_code-1.0.2/bin/dress_code:88:in `<top (required)>'
            from /usr/pkg/bin/dress_code:23:in `load'
            from /usr/pkg/bin/dress_code:23:in `<main>'
    
    --> Compiling static assets [jammit]
    --> Compiled static assets [css/jammit]
    --> Compiling static assets [javascript]
    ** Invoke js:generate (first_time)
    ** Execute js:generate
    --> Generating plugin extensions
    ** Invoke js:generate_extensions (first_time)
    ** Execute js:generate_extensions
    --> Pre-compiling handlebars templates
    ** Invoke jst:compile (first_time)
    ** Execute jst:compile
    Unknown architecture ( netbsd ) assuming one processor.
    --> Generating plugin extensions finished in 0.005783069
    rake aborted!
    Anonymous modules have no name to be referenced by
    /usr/pkg/lib/ruby/gems/1.9.3/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:611:in `to_constant_name'
    /usr/pkg/lib/ruby/gems/1.9.3/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:417:in `qualified_name_for'
    /usr/pkg/lib/ruby/gems/1.9.3/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:130:in `rescue in const_missing'
    /usr/pkg/lib/ruby/gems/1.9.3/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:120:in `const_missing'
    /home/bug/canvas/lib/handlebars/handlebars.rb:71:in `compile_template'
    /home/bug/canvas/lib/handlebars/handlebars.rb:50:in `compile_file'
    /home/bug/canvas/lib/handlebars/handlebars.rb:32:in `block in compile'
    /usr/pkg/lib/ruby/gems/1.9.3/gems/parallel-0.5.16/lib/parallel.rb:275:in `call'
    /usr/pkg/lib/ruby/gems/1.9.3/gems/parallel-0.5.16/lib/parallel.rb:275:in `call_with_index'
    /usr/pkg/lib/ruby/gems/1.9.3/gems/parallel-0.5.16/lib/parallel.rb:130:in `block (2 levels) in work_in_threads'
    /usr/pkg/lib/ruby/gems/1.9.3/gems/parallel-0.5.16/lib/parallel.rb:123:in `loop'
    /usr/pkg/lib/ruby/gems/1.9.3/gems/parallel-0.5.16/lib/parallel.rb:123:in `block in work_in_threads'
    /usr/pkg/lib/ruby/gems/1.9.3/gems/parallel-0.5.16/lib/parallel.rb:14:in `block (2 levels) in in_threads'
    Tasks: TOP => jst:compile

**Comment by claydiffrient** [comment]
@bugQ Sorry it's been a while since there was any activity here.  I'm assuming you've figured things out by now.  I'm going to go ahead and close the issue, feel free to file another one if this is still causing you issues.  Also, in the future you might get better traction on the mailing list (https://groups.google.com/forum/#!forum/canvas-lms-users) for this sort of thing.
