### ISSUE TITLE
Copy Course & Import Course Export Package Error

### ISSUE THREAD

**Issue by kazhuyo** [instructure/canvas-lms#345]
When copy another course with latest stable release i got this error :

#330 ActionController::InvalidAuthenticityToken

 ActionController::InvalidAuthenticityToken

        /var/www/canvas/app/controllers/application_controller.rb:965:in `verify_authenticity_token'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/callbacks.rb:178:in `evaluate_method'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/callbacks.rb:166:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:225:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:629:in `run_before_filters'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:615:in `call_filters'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:638:in `block in run_before_filters'
/var/www/canvas/app/controllers/application_controller.rb:119:in `set_locale'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/callbacks.rb:178:in `evaluate_method'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:186:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:635:in `run_before_filters'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:615:in `call_filters'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:610:in `perform_action_with_filters'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/benchmarking.rb:68:in `block in perform_action_with_benchmark'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `block in ms'
/usr/local/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/rescue.rb:160:in `perform_action_with_rescue'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/flash.rb:151:in `perform_action_with_flash'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/base.rb:532:in `process'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:606:in `process_with_filters'
/var/www/canvas/vendor/bundle/ruby/1.9.1/gems/compass-rails-1.0.3/lib/compass-rails/railties/2_3.rb:9:in `process_with_compass'
/var/www/canvas/vendor/bundle/ruby/1.9.1/gems/oauth-instructure-0.4.9/lib/oauth/request_proxy/action_controller_request.rb:72:in `process_with_oauth'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/base.rb:391:in `process'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/base.rb:386:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/routing/route_set.rb:438:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/dispatcher.rb:87:in `dispatch'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/dispatcher.rb:121:in `_call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/dispatcher.rb:130:in `block in build_middleware_stack'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/query_cache.rb:29:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/query_cache.rb:29:in `block in call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/query_cache.rb:9:in `cache'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/query_cache.rb:28:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/gems/sass-3.2.3/lib/sass/plugin/rack.rb:54:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/string_coercion.rb:25:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.1.3/lib/rack/head.rb:9:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.1.3/lib/rack/methodoverride.rb:24:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/params_parser.rb:15:in `call'
/var/www/canvas/vendor/plugins/respondus_soap_endpoint/lib/respondus_api_middleware.rb:60:in `call'
/var/www/canvas/lib/request_context_generator.rb:34:in `call'
/var/www/canvas/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
/var/www/canvas/app/middleware/stats_timing.rb:8:in `block in call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `block in ms'
/usr/local/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/var/www/canvas/app/middleware/stats_timing.rb:8:in `call'
/var/www/canvas/app/middleware/load_account.rb:12:in `call'
/var/www/canvas/app/middleware/sessions_timeout.rb:24:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/gems/encrypted_cookie_store-instructure-1.0.4/lib/encrypted_cookie_store.rb:33:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/failsafe.rb:26:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.1.3/lib/rack/lock.rb:11:in `block in call'
<internal:prelude>:10:in `synchronize'
/var/www/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.1.3/lib/rack/lock.rb:11:in `call'
/var/www/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/dispatcher.rb:106:in `call'
/usr/src/passenger-3.0.19/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
/usr/src/passenger-3.0.19/lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
/usr/src/passenger-3.0.19/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
/usr/src/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
/usr/src/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
/usr/src/passenger-3.0.19/lib/phusion_passenger/utils.rb:470:in `safe_fork'
/usr/src/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
/usr/src/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/usr/src/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/usr/src/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:180:in `start'
/usr/src/passenger-3.0.19/lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
/usr/src/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
/usr/src/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
/usr/src/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
/usr/src/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
<internal:prelude>:10:in `synchronize'
/usr/src/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/usr/src/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
/usr/src/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
/usr/src/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
/usr/src/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/usr/src/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/usr/src/passenger-3.0.19/helper-scripts/passenger-spawn-server:99:in `<main>'
      

and when try import course from imscc file :

#334 Delayed Notification processing failed

 can't convert nil into String

        /usr/local/lib/ruby/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
/usr/local/lib/ruby/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
/var/www/canvas/app/models/message.rb:399:in `parse!'
/var/www/canvas/lib/notification_message_creator.rb:152:in `each'
/var/www/canvas/lib/notification_message_creator.rb:152:in `build_immediate_messages_for'
/var/www/canvas/lib/notification_message_creator.rb:89:in `block (3 levels) in create_message'
/var/www/canvas/lib/notification_message_creator.rb:71:in `each'
/var/www/canvas/lib/notification_message_creator.rb:71:in `block (2 levels) in create_message'
/usr/local/lib/ruby/gems/1.9.1/gems/i18n-0.6.0/lib/i18n.rb:245:in `with_locale'
/var/www/canvas/lib/notification_message_creator.rb:70:in `block in create_message'
/var/www/canvas/lib/notification_message_creator.rb:66:in `each'
/var/www/canvas/lib/notification_message_creator.rb:66:in `create_message'
/var/www/canvas/app/models/notification.rb:97:in `create_message'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-2.3.18/lib/active_record/associations/association_proxy.rb:215:in `method_missing'
/var/www/canvas/app/models/delayed_notification.rb:46:in `process'
/var/www/canvas/app/models/delayed_notification.rb:40:in `process'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/performable_method.rb:21:in `perform'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/backend/base.rb:211:in `invoke_job'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:135:in `block (2 levels) in perform'
/usr/local/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:135:in `block in perform'
/usr/local/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:129:in `perform'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:102:in `block in run'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:199:in `block in configure_for_job'
/usr/local/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:197:in `configure_for_job'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:100:in `run'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:75:in `block in start'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:74:in `loop'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:74:in `start'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:155:in `block in spawn_worker'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:151:in `fork'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:151:in `spawn_worker'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:138:in `block (2 levels) in spawn_all_workers'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:138:in `times'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:138:in `block in spawn_all_workers'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:136:in `each'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:136:in `spawn_all_workers'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:98:in `start'
/var/www/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:51:in `run'
/var/www/canvas/script/delayed_job:5:in `<main>'

**Comment by claydiffrient** [comment]
@kazhuyo Sorry for the delayed response.  I believe that this should be working in the latest release.  I'm going to close the issue, but if it is still a problem for you feel free to reopen it.
