### ISSUE TITLE
Install Error: RAILS_ENV=production rake db:initial_setup

### ISSUE THREAD

**Issue by ghost** [instructure/canvas-lms#35]
I have been trying to get this installed for a few weeks now. I have also been documenting my installation procedures and have it down well until I get to this setup. When I run

RAILS_ENV=production rake db:initial_setup

I get the following rake aborted!
You have already activated rake 0.9.2, but your Gemfile requires rake 0.8.7. Consider using bundle exec.

I am using ruby 1.8.7 (2008-05-31 patchlevel 0)
rubygems 1.8.5
rails 2.3.11

Not sure how to proceed with the installation.

**Comment by ZCF1024** [comment]
Git error: command `git clone
'https://github.com/rails-api/active_model_serializers.git'
"/home/canvas/Desktop/canvas/vendor/bundle/ruby/2.5.0/cache/bundler/git/active_model_serializers-510a178f5743dd588f54b8591fd82d287cfc711e"
--bare --no-hardlinks --quiet` in directory /home/canvas/Desktop/canvas has
failed.

这个错是什么

**Comment by ZCF1024** [comment]
Git error: command git clone 'https://github.com/rails-api/active_model_serializers.git' "/home/canvas/Desktop/canvas/vendor/bundle/ruby/2.5.0/cache/bundler/git/active_model_serializers-510a178f5743dd588f54b8591fd82d287cfc711e" --bare --no-hardlinks --quiet in directory /home/canvas/Desktop/canvas has
failed.

What's wrong
