### ISSUE TITLE
Merge conflicts in files that we haven't modified

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#352]
(This is a cross-post from the [Google Group](https://groups.google.com/forum/#!topic/canvas-lms-users/1IxaR-XGdMU), since I'm getting no traction there)

We (SFU) run the open source Canvas in our own data centre. We're trying to keep fairly close to the Canvas cloud release schedule, and to that end I'm trying to come up with an automated process that watches both the Instructure and SFU GitHub repos; when either of them changes (either Instructure's stable branch, or our sfu-develop branch), the process would try to merge instructure/stable into sfu/sfu-develop and deploy to a testing stack. The goal of this is so that we can test any mods we've made to the code against Instructure's latest code, and to spot any merge conflicts ahead of time.

I'm running into a weird issue right now when trying to merge instructure/stable to sfu/sfu-develop. I'm getting merge conflicts in files that we have not changed and have never touched. For completeness, the version of stable I have is as of commit ec269eb (which is what is the current last commit on the repo as of today).

Here's what happens when I try to merge:

```
± sfu on edge(9e67c2d::9 days ago) ✔  git merge stable
… git output indicating a conflict …

± sfu on edge(9e67c2d::9 days ago) ✖ git status

… bunch of unconflicted changes…

# Unmerged paths:
#   (use "git add/rm <file>..." as appropriate to mark resolution)
#
#	deleted by them:    app/views/content_imports/intro.html.erb
#	both modified:      config/locales/ar.yml
#	both modified:      config/locales/es.yml
#	both modified:      config/locales/fr.yml
#	both modified:      config/locales/generated/en.yml
#	both modified:      config/locales/ja.yml
#	both modified:      config/locales/pt.yml
#	both modified:      config/locales/ru.yml
#	both modified:      config/locales/zh.yml
#	both modified:      lib/api/v1/assignment.rb
#	both modified:      lib/event_stream.rb
#	both modified:      public/locales/en.yml
#	both modified:      spec/apis/v1/context_modules_api_spec.rb
#	both modified:      spec/models/content_migration_spec.rb
```
The only "valid" conflict in that list is intro.html.erb – we modified it, and you deleted it, so that's a conflict. Otherwise, we have never touched any of those files. For example, the log for config/locales/fr.yml:

```
± sfu on edge(9e67c2d::9 days ago) ✖  git log -- config/locales/fr.yml
349315c Updated fr translation (6 weeks ago) <Transifreq>
03726e9 Updated fr translation (2 months ago) <Transifreq>
6d80184 update translations (3 months ago) <Duane Johnson>
9dc171a update translation files: ar, es, fr, ja, pt, ru, zh (4 months ago) <Duane Johnson>
53d0b9f9 update languages from transifex translations (5 months ago) <Duane Johnson>
1ed48b1 add french language translation (6 months ago) <Duane Johnson>
8d29f27 Added Arabic, Mandarin, French, Spanish, Russian translations. (8 months ago) <Duane Johnson>
441cbdd adding french beta to canvas (9 months ago) <Amber Taniuchi>
```
A copy of the conflicted config/locales/fr.yml is at https://gist.github.com/grahamb/81633a162af99ef280c3. You can see the conflict markers on lines 7890, 9706 and 10640.

I had the same problem the last time I did a fetch and merge; I ended up resolving it by just accepting all of "their" (Instructure's) changes, but that isn't automatable. I would really like to know why I'm getting conflicts in files we haven't touched.

Any advice?

**Comment by grahamb** [comment]
Well, kinda. We've ended up going with merging in the treesame commits that correspond to a specific release date instead of using the tags. That's worked for us for the last six months, until we tried to bring in the Dec 20 commit and had a couple of conflicts in files we've never touched. I posted about it on IRC, but didn't hear back.

I did try brining in a release tag and had the same problem as noted in the original issue - lots and lots of conflicts. @phinze spent a couple of hours with me at Instructurecon trying to track this down; he seemed to thing that the tags should be pointing at the treesame commits instead of whatever they point at now.

I'm off until the 5th, and my notes on it are in the office.

**Comment by tierra** [comment]
@grahamb Can we close out this issue?

Seems like this is a pretty hairy git workflow trying to keep two long-lived branches merging cleanly. I'm not sure what can really be done with it other than to use a different workflow (which I'm guessing you're already doing by now).

**Comment by grahamb** [comment]
Yeah, go ahead and close it. We've been taking the treesame commits for a
couple of years now and it's working fine.

**Comment by tierra** [comment]
Thanks
