### ISSUE TITLE
[BUG] Duplicate sent mails for announcement notification

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#373]
Hello contributors!

I have found a bug regarding announcement mail notifications, here is the way to reproduce it:

* Create two courses where one of your mails must be enrolled as a student or teacher (in order to receive the notification for the new announcement), 
* Create a new announcement in a course and delay its publication (for 10 minutes for instance),
* In another course, use the import tool to import that new announcement
* Then delete the announcement from the original course
* Wait until the announcement is published in the course where you imported it, 
* Then when the announcement is published you should receive 2 duplicated mails from the course where you imported the announcement. 
* When checking the "Message" model you will see two duplicated messages sent to the same user for the same context. 

I have tested it and managed to reproduce the bug. This bug seems linked to the "import" step - if you create the announcement and delay its publication you receive only one mail as expected. 

We have opened a Google Group subject before submitting this bug: https://groups.google.com/forum/#!topic/canvas-lms-users/tfUsMXc5SDY

It seems that someone else has already experienced this bug - that is why I turned that conversation into a new issue. 

[Edit] I removed "after import" because it also occurs for some announcement on some specific course. I have looked at the DelayedJob logs and it appears that this function: 

```Processing DelayedNotification.process```

Is called twice within 20 secondes for the same announcement, same recipients, same notification. The created_at attribute is the only difference between the two calls: 

```ruby
"created_at":"2013-11-22T13:00:10Z" # for the first one
"created_at":"2013-11-22T13:00:15Z" # for the second one
```

I am ready to give more information if needed.

**Comment by claydiffrient** [comment]
@Kulgar Sorry you haven't seen any activity here.  It looks like things were taken care of in the Google Group though and this bug was fixed with d9146289ae871f3cf8f9e20c6cecd438187fa5a8. I'm going to close the issue, but if it's still a problem please let us know.
