### ISSUE TITLE
Shibboleth integration

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#382]
Dear Sir,

I have been trying to integrate Shibboleth with Canvas SAML authentication system. I have been searching through the internet and found some articles about the Shibboleth integration. They only talk about the saml2:assertion in the IdP response message but our IdP return an encrypted assertions in the response message. Another article says in order to consume encrypted SAML assertions, we need to create a public/private keypair in the saml.yml. Since canvas does not use saml.yml any more, how can I include the public/private keypair in the SAML configuration? Could you tell me how Canvas can accept the encrypted SAML assertions from our IdP? Thank you.

Chi-Hou

**Comment by claydiffrient** [comment]
@cvong I'm sorry for no response on this. I'm sure you've figured this out by now or moved on.  We do support saml.yml though.  Please see saml.yml.example for more details including a command to run which should generate the keypair you need.  I'm going to close the issue, but please let us know if it's still a problem for you.
