### ISSUE TITLE
rich editor removes title attributes in <span> or <p> elements

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#384]
Hi,

I tried to insert title attributes in <span> or <p> elements but the attributes got removed before being saved. I tried to modify the tinyOption in the tinymce.editor_box.js but it did not work. Is that  Canvas' problem or tinymce's issue? Thank you very much for your help.

Chi-Hou

**Comment by simonista** [comment]
This was fixed in 520af093471c868be27ed6bd59fea678565bb18f.  Thanks for the report!
