### ISSUE TITLE
PG::Error: ERROR:  relation "delayed_jobs" does not exist

### ISSUE THREAD

**Issue by nkokkos** [instructure/canvas-lms#397]
Hi, there, thanx for opensourcing this great app. 

I have been trying to no avail, to run the migrations, but it always fails at: 

==  CleanupDelayedJobsIndexes: migrating ======================================
rake aborted!
An error has occurred, this and all later migrations canceled:

PG::Error: ERROR:  relation "delayed_jobs" does not exist
: CREATE INDEX get_delayed_jobs_index ON delayed_jobs (priority, run_at, failed_at nulls first, locked_at nulls first, queue)/home/nikos/rails_projects/canvas-lms/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.15/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `exec'

Have you experienced this before?

I have followed the instructions step by step but can not figure out why it failed at delayed_jobs. 

Delayed_jobs plugin should be loaded from the plugins folder and delayed_jobs table should be created at the very second migration.

Have you any ideas?

**Comment by claydiffrient** [comment]
@nkokkos I'm going to go ahead and close this issue.  It seems you've probably got it figured out.  Also, Rails 3 is now supported by Canvas.  If you have further issues feel free to reopen the issue.
