### ISSUE TITLE
Any user with edit permission can edit quiz instructions, but only an enrolled user (Teacher/Designer) can save them

### ISSUE THREAD

**Issue by davidj-lynxlogic** [instructure/canvas-lms#400]
I, as a designer on a course, can edit instructions on a quiz. However, when I submit the edited text, the changes are discarded and the old instructions re-appear. If I am added as a teacher, I can successfully edit the instructions.

I would expect at best for the quiz instructions to be read-only in the UI if I don't have edit permission, or at worst, to be shown an error when I tried to save the changes.

**Comment by simonista** [comment]
Hey @davidj-lynxlogic, sorry to have never responded to this.  It looks like the permission that controls being able to edit a quiz is "Manage (add / edit / delete) assignments and quizzes".  I just tested with an account admin that ONLY has that permission enabled, and they were successfully able to edit a quiz.
