### ISSUE TITLE
Sort Grade Summary Table by Headers

### ISSUE THREAD

**Issue by sealocal** [instructure/canvas-lms#403]
It would be awesome if a student could sort their grades by the assignments attributes, such as name, grade, out of, and due date.

In other words, the values in the <th> elements from this view:
 app/views/gradebooks/grade_summary.html.erb

**Comment by claydiffrient** [comment]
@sealocal I'm sorry for the delayed response on this.  I've sent the issue over to the product team for prioritization. We'll keep you up to date as things progress.  Remember we love to get pull requests so if you have a fix for this, please send it our way.

**Comment by tierra** [comment]
I'm not sure, but I think this was an old feature request before gradebook was rewritten, and doesn't apply anymore. I'll close out this ticket in the next couple weeks if there's no new feedback.
