### ISSUE TITLE
video object is not displayed in quiz's question 

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#406]
Dear Sir,

I have inserted a video <object> in a quiz's question and can see it when I edit the question. When I tried to take the quiz, I did not see the video object in the question. I used firefox developer tool to find out there was no <object> tag in the frame. I put the same <object> tag in the wiki page and can see it without any problem. Do you know what might cause the problem? Thank you very much for your help.

Chi-Hou

**Comment by simonista** [comment]
Hey @cvong, I'm really sorry we never got back to you about this issue.  I'm assuming you found a solution in the last 2 years, but if not, feel free to re-open and we can look into it more.
