### ISSUE TITLE
(Un)subscribe button on discussion posts not clickable

### ISSUE THREAD

**Issue by CameronNemo** [instructure/canvas-lms#408]
When you scroll down to where the button is almost at the top of the page, or the top of the page, you cannot click the (un)subscribe button. What happens is when you mouse over the button, it tries to display the help text, but does so *on top of* the button, instead of over or under it. You can kind of see the help text flashing, and the button darkens, but you are unable to click.

**Comment by claydiffrient** [comment]
@CameronNemo I'm sorry for the delayed response here.  I believe that this issue is fixed now.  I can't seem to reproduce it at least.  I'm going to close the issue, but if you find it's still happening for you please let us know.
