### ISSUE TITLE
Cannot Log In

### ISSUE THREAD

**Issue by JessieD** [instructure/canvas-lms#415]
Hi everyone,

I am having issues with accessing my instance of canvas. I was in the admin of the site, when I tried to another page I got an error saying "Oops! Looks like something Broke".

There was another tab open in my browser, so I was able to click log out and was returned to the main log in screen. Upon entering my UN and Password, I was brought to the oops screen again. 

I'm now unable to log in at all. Canvas Support team directed me here to seek out help on the issue. Has anyone experienced this, or have any advice on what may be causing it, or how to remedy the issue?

Thanks,
Jessie

**Comment by claydiffrient** [comment]
@JessieD I'm sorry to hear this, and I'm sorry for the delayed response.  You've probably figured things out by now.  I'm going to close the issue, but should you still have problems please let us know.
