### ISSUE TITLE
BUG - Subscribing users to more than one course

### ISSUE THREAD

**Issue by schrink** [instructure/canvas-lms#416]
If you try to subscribe user to more than one course before they accept the invitation for the first one, once they create account, they will get error page. The only way to solve it was to manually delete this user from all the tables in the database.

**Comment by simonista** [comment]
Hey @schrink, thanks for the report and sorry to have never responded.  I'm pretty sure that multiple course invitations work just fine, if you're still seeing this issue could you provide some more detailed reproduction steps?  Thanks!
