### ISSUE TITLE
rake aborted because of `load_missing_constant'

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#418]
Dear Sir,

I tried to upgrade Canvas and got the following errors when I ran the RAILS_ENV=production bundle exec rake db:migrate command.

RAILS_ENV=production bundle exec rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Expected /var/canvas/vendor/plugins/adheres_to_policy/lib/adheres_to_policy.rb to define AdheresToPolicy
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:452:in `load_missing_constant'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:106:in `const_missing_with_dependencies'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:118:in `const_missing'
/var/canvas/config/initializers/adheres_to_policy.rb:2:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:173:in `load'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:173:in `load_with_new_constant_marking'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/railties/lib/initializer.rb:627:in `block in load_application_initializers'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/railties/lib/initializer.rb:626:in `each'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/railties/lib/initializer.rb:626:in `load_application_initializers'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/railties/lib/initializer.rb:179:in `process'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/railties/lib/initializer.rb:114:in `run'
/var/canvas/config/environment.rb:32:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `block in require'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:547:in `new_constants_in'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/railties/lib/tasks/misc.rake:4:in `block in <top (required)>'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:195:in `each'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:195:in `invoke_prerequisites'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/1.9.1/bin/rake:23:in `load'
/var/canvas/vendor/bundle/ruby/1.9.1/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate => environment

Do you know what might be the problem? Thanks.

Chi-Hou

**Comment by claydiffrient** [comment]
@cvong Is this happening for you still?

**Comment by cvong** [comment]
No. Thanks.
