### ISSUE TITLE
Error while doing db:initial_setup 

### ISSUE THREAD

**Issue by adityapn** [instructure/canvas-lms#422]
I was setting up canvas-lms on ubuntu and in the end while populating the database with bundle exec rake db:initial_setup I got "rake aborted! Configuration is not a module" error while "bundle exec rake db:create --trace" was working normally . What should I do to fix this error ? Mu ruby version 1.9.3 and rails version Rails 2.3.18 .

Command : bundle exec rake db:initial_setup --trace

Error :

** Invoke db:initial_setup (first_time)
** Invoke db:generate_security_key (first_time)
** Execute db:generate_security_key
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Configuration is not a module
/usr/lib/ruby/vendor_ruby/rails/configuration.rb:8:in `<module:Rails>'
/usr/lib/ruby/vendor_ruby/rails/configuration.rb:7:in `<top (required)>'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `block in require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:547:in `new_constants_in'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/usr/lib/ruby/vendor_ruby/rails/railtie.rb:2:in `<top (required)>'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `block in require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:547:in `new_constants_in'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:1:in `<top (required)>'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `block in require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:547:in `new_constants_in'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/usr/lib/ruby/vendor_ruby/rails/application.rb:4:in `<top (required)>'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `block in require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:547:in `new_constants_in'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/usr/lib/ruby/vendor_ruby/rails.rb:10:in `<top (required)>'
/var/lib/gems/1.9.1/gems/bundler-1.5.3/lib/bundler/runtime.rb:76:in `require'
/var/lib/gems/1.9.1/gems/bundler-1.5.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/var/lib/gems/1.9.1/gems/bundler-1.5.3/lib/bundler/runtime.rb:72:in `each'
/var/lib/gems/1.9.1/gems/bundler-1.5.3/lib/bundler/runtime.rb:72:in `block in require'
/var/lib/gems/1.9.1/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `each'
/var/lib/gems/1.9.1/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `require'
/var/lib/gems/1.9.1/gems/bundler-1.5.3/lib/bundler.rb:131:in `require'
/home/knolskape/ror/canvas/canvas/config/boot.rb:53:in `load_gems'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/railties/lib/initializer.rb:167:in `process'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/railties/lib/initializer.rb:114:in `run'
/home/knolskape/ror/canvas/canvas/config/environment.rb:32:in `<top (required)>'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `block in require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:547:in `new_constants_in'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/dependencies.rb:182:in `require'
/var/lib/gems/1.9.1/bundler/gems/rails-e86daf8ff727/railties/lib/tasks/misc.rake:4:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:195:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:195:in `invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:195:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:195:in `invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:initial_setup => db:migrate => environment

**Comment by claydiffrient** [comment]
@adityapn I can't seem to reproduce this.  I hope you've managed to figure it out.  In the future the mailing list (https://groups.google.com/forum/#!forum/canvas-lms-users) might be a better venue for issues with deployment/setup.  I'm going to close the issue, but if you find it's still an issue, feel free to reopen it.

**Comment by adityapn** [comment]
I found the solution . Thanks for the reply .
