### ISSUE TITLE
New installation Canvas on Ubuntu 12.04

### ISSUE THREAD

**Issue by willempoort** [instructure/canvas-lms#426]
After a new "production" installation on Ubuntu I can login into canvas but I'm not able to
change any settings. 
I don't get or see any errors or so, it more looks like the links/scripts are not working at all.
I'm also missing some administrative tabs it seems.

Any idea what is wrong?
I would love to set this up for a high school conglomerate.

**Comment by claydiffrient** [comment]
@willempoort It's been a while since you've had any traction here.  I'm sorry about that. I'm assuming you've figured things out by now.  In the future for these sort of deployment issues the mailing list might be a better fit (groups.google.com/forum/#!forum/canvas-lms-users).
