### ISSUE TITLE
GET /api/v1/accounts/:account_id/courses returns 10 or less courses

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#429]
Hi,

I tried to use canvas api to get a list of courses for an account and I could only get 10 or less courses for all accounts. I wonder what I need to do to make Canvas to return all courses for an account? Thanks.

Chi-Hou

**Comment by param1989** [comment]
app.get('api/courses/:id',(req,res)=>
{
res.send(req.params.id);
});

It showing an error 404 can't get

**Comment by simonista** [comment]
@param1989 , probably better to start a new issue and resurrect a 4-year old issue. As for your issue, check your url, it should be `<your-canvas-domain>/api/v1/courses/:id`, replacing `:id` with whatever the numeric id of your course is.

**Comment by param1989** [comment]
Thanks
