### ISSUE TITLE
Copy course loses group assignment flag

### ISSUE THREAD

**Issue by davidj-lynxlogic** [instructure/canvas-lms#432]
We're running the open source Canvas LMS and are consistently seeing that when copying a course, the group assignment setting is lost on all assignments, and we have to edit the copied course and re-specify the group assignment.

**Comment by simonista** [comment]
This has been addressed in this commit: 2ba8f5238b926f22faeef07f017eb862828c4eb9 and should now be fixed.  Thanks for the report!
