### ISSUE TITLE
Essay graded quiz shows up with zero score until graded

### ISSUE THREAD

**Issue by dieseldjango** [instructure/canvas-lms#433]
We're seeing that when a student submits a quiz with essay questions that must be graded by the teacher, the score for the quiz shown to the student in the Assignments list reflects a zero for the essay questions until the quiz has been manually graded. Likewise, the cumulative quiz score in the gradebook reflects the same.

This is causing confusion with both our faculty and students. Would it not be better to not show a score for the quiz until the teacher has reviewed and graded these questions?

**Comment by omarkhan** [comment]
Hi @dieseldjango - sorry for the (very) late reply. If this is still an issue please post on the [mailing list](http://groups.google.com/group/canvas-lms-users) or on [IRC](http://webchat.freenode.net/?channels=canvas-lms). Thanks!
