### ISSUE TITLE
NoMethodError workflow_state in delayed job 

### ISSUE THREAD

**Issue by davidj-lynxlogic** [instructure/canvas-lms#439]
We're getting this warning frequently in the delayed job log:

    Could not check if a record changed state: #<NoMethodError: undefined method 'workflow_state' for nil:NilClass>

The error appears to be originating from changed_state in vendor/plugins/broadcast_policy/lib/broadcast_policy.rb:

    rescue Exception => e
      logger.warn "Could not check if a record changed state: #{e.inspect}"
      false
    end

Any idea why this would be happening?

**Comment by simonista** [comment]
We found and fixed a couple cases of this, and then removed the rescue statement so that introducing a bug like this will fail more loudly and force us to fix it faster (rather than introduce subtle notification issues): 54f284bfb611807a414cd8fc3691aaed0d569999.
