### ISSUE TITLE
Course start_at and conclude_at times are always overridden to 0:00 and 23:55 on settings page

### ISSUE THREAD

**Issue by raffstah** [instructure/canvas-lms#444]
Commit: 8d9d3a09c859d17ef66638c69ae5765d3fcc47e8

The settings page allows you to select a time, but it is always overridden to the default by public/javascripts/course_settings.js in the above commit.  Before this you were able to set the time via the settings page without it being overridden.

**Comment by omarkhan** [comment]
Unable to reproduce, closing
