### ISSUE TITLE
Modifying sis_user_id via API (login)

### ISSUE THREAD

**Issue by conder** [instructure/canvas-lms#449]
I am able to create a new user and login but when I try to update a login's sis_user_id via the REST API I get an unauthorized error (401).  The user has full SIS privileges and can modify the sis_user_id via the user interface-- it only fails when using the API.  I can modify any of the other login attributes using the API.  Why can't I do this with the API?  Does this have something to do with UI stickiness?

**Comment by tierra** [comment]
Setting the `sis_user_id` attribute on a user is only supported during User creation. You can't update this attribute in the User update API endpoint, and I don't believe it's ever been supported there. Closing this out as invalid.

**Comment by ccutrer** [comment]
To expound on this - when you're create a User, you're really creating a User and a Login. The sis_user_id is an attribute of the login. So to modify it, you need to update the login: https://canvas.instructure.com/doc/api/logins.html#method.pseudonyms.update
