### ISSUE TITLE
[Translation issue] Inbox translation is not completely.

### ISSUE THREAD

**Issue by chenshuchuan** [instructure/canvas-lms#452]
In the inbox, when switching to read, unread, archive,Translating other languages  is not successful

**Comment by claydiffrient** [comment]
@chenshuchuan I'm sorry for the delayed response on this.  I can't seem to reproduce this currently.  If you are running a local instance of canvas you'll need to use the optimized JS to be able to see all the translations by setting the `USE_OPTIMIZED_JS` environment variable to `true
