### ISSUE TITLE
coffeescript/ember/screenreader_gradebook/templates/*.hbs files don't generate locations

### ISSUE THREAD

**Issue by jorgevbo** [instructure/canvas-lms#475]
Files in coffeescript/ember/screenreader_gradebook/templates/ don't generate translation keys in /locales/generated/en.yml

To test, go to /courses/:id/gradebook (Individual View) page.
Files are Handlebars Template .hbs

**Comment by simonista** [comment]
This appears to have been fixed at some point in the last 3 years (wow, how embarrassing, sorry for not responding sooner).  Thanks!
