### ISSUE TITLE
Missing "name" for sections when pulling course - API

### ISSUE THREAD

**Issue by Syerram** [instructure/canvas-lms#477]
The course API `courses/` can return sections embedded in each course but the `name` field for each section seems to be incorrect. It returns the name of the course instead of the section name. 
```
...
u'name': u'Calculus 1', //course name
u'sections': [{u'end_at': None,
    u'enrollment_role': u'TeacherEnrollment',
    u'id': 949700,
    u'name': u'Calculus 1', //should be CS-201
    u'start_at': None}],
```

Note this isn't a issue when you just pull the sections via `courses/:courseid/sections`

**Comment by claydiffrient** [comment]
@Syerram Sorry for a bit of a delayed response here.  I can't seem to reproduce this issue on the latest release.  Is it still an issue for you?
