### ISSUE TITLE
No Audio is working with BigBlueButton

### ISSUE THREAD

**Issue by engmsaleh** [instructure/canvas-lms#478]
When I integrate the BBB with Canvas , everything is working nice expect for the audio.

```
Note: Audio is working for the BBB demo which is accessing the BBB server directly and not through the CanvasLMS API.  
```

I have searched for the problem and it seems to be a problem with an attribute called 

```
"voiceBridge"
```

Which it seems to be set incorrectly through the API using CanvasLMS.

**Comment by tkrause** [comment]
Hard coding the voice bridge like this is a bad idea. If you have two conferences going on at the same time, they will be sharing the same voiceBridge meaning people in two different conferences hearing each others audio when they shouldn't be.

The following means convert the global_id to a padded 20 digit number where as BBB accepts 5 digit by default only.

`"%020d" % self.global_id`

Change this line to:

`%05d" % self.global_id`

That will change global_id to be 5 digit max and pad with zeros.

**Comment by simonista** [comment]
We haven't had other reports of this happening, so I'm going to close this for now (and sorry to have never responded!)

**Comment by samuels410** [comment]
Hi @simonista this issue still exists,

For me I did the fix like below,

`:voiceBridge => self.global_id.to_s.last(5),`
