### ISSUE TITLE
[Important BUG] Calendar: items just vanish after editing them

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#479]
Hi! 

Here is a new bug, an important one, related to calendar. 

### BUG number 1:

Set your language to English

* Access your calendar
* Clic on the calendar, some day at some hour to create a new calendar item
* Clic the newly created item to edit it and clic on the "more options" button
* Edit the description and clic "update event" - you are redirected to the calendar but the start / end time disappeared and your event is now at the top of the day (and not at "some hour" as you set it when you created it)

### BUG number 2:

Set your language to French (or anything else than English I think the bug will also show up):

* Do exactly the same as bug 1
* If your language is set to French (for instance) you won't see it in your calendar anymore. It has just vanished!

Let me know if I can help you solving this bug. 
Kulgar.

**Comment by claydiffrient** [comment]
@Kulgar Thanks for your bug report.  I can't seem to reproduce this running on the latest master.  I'm going to close it, but if you still have trouble with it please let us know.
