### ISSUE TITLE
"Register your instance with Google" link sends you to OAuth deprecation notification.

### ISSUE THREAD

**Issue by austinoneil** [instructure/canvas-lms#489]
The first link [here](https://github.com/instructure/canvas-lms/wiki/Canvas-Integration#google-docs) sends you to an OAuth deprecation page.

**Comment by claydiffrient** [comment]
The engineering team is actively working on this issue.  We'll keep you updated as it gets completed.

**Comment by mdaniels5757** [comment]
Any updates on this?

**Comment by ccutrer** [comment]
The Google Drive instructions link to the correct place. It explains to enable the Google Docs plugin as well. I've removed the Google Docs section entirely.
