### ISSUE TITLE
CSV download/upload via API

### ISSUE THREAD

**Issue by madelynnblue** [instructure/canvas-lms#500]
The web interface allows downloading and uploading current gradebooks for courses. I could not find corresponding API requests for these methods, and so tried to emulate the web requests through the browser. Everything looks fine, except that during upload, I get a 500 and a message saying something broke. I've added almost every request header and form data to the multipart data that I can see in chrome's network debug tab, but still can't figure out why it's failing.

It is possible to get an API route for these functions? I suspect that's easier than figuring out what's wrong with the current solution I'm using.

**Comment by eritain** [comment]
Did the upload include numeric values over 999? That is, values that would be rendered with a comma every three decimal places? CSV values **can** contain commas, if they're escaped. Gradebook CSV export even produces them. But as of today, Gradebook CSV import makes hash of them.
