### ISSUE TITLE
Quiz submissions questions_as_object returns a Hash, should be an Array

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#512]
The [`questions_as_object`](https://github.com/instructure/canvas-lms/blob/stable/app/models/quizzes/quiz_submission.rb#L313) method in quiz_submission.rb returns an empty Hash if `self.quiz_data` is empty. This method should probably return an `Array` instead; if `self.quiz_data` wasn't empty but contained actual quiz data, it would be an `Array`.

In [`take_quiz_presenter.rb`](https://github.com/instructure/canvas-lms/blob/stable/app/presenters/quizzes/take_quiz_presenter.rb#L36), `all_questions` calls `submission.questions_as_object.compact`. This fails with an error if `questions_as_object` returns an empty `Hash` as `Hash` has no `compact` method.

**Comment by ryanmt** [comment]
Nice.  We've been talking about this in #291 as well and will have a fix out for it soon.
