### ISSUE TITLE
Unable to annotate documents using canvadocs

### ISSUE THREAD

**Issue by poojabansal** [instructure/canvas-lms#514]
Since Crocodoc is merged with Box View, I cannot create a new Crocodoc account to get a Crocodoc API token.
However, I am able to use the Canvadocs plugin using the Box View API token. But, I cannot annotate my documents using Canvadocs. Is there any workaround for it?

**Comment by simonista** [comment]
This is really unfortunate, but sadly annotations are not yet supported in the box view api.  If box won't give you a crocodoc token, then you aren't going to be able to annotate in canvas.  Sorry! :(
