### ISSUE TITLE
Students can now see unpublished exams on course home page

### ISSUE THREAD

**Issue by artfulhacker** [instructure/canvas-lms#515]
After the last update students are getting very confused, unpublished exams show up in the listing on the course home page and then when they click on it, it says unauthorized.

Teacher View:
![image](https://cloud.githubusercontent.com/assets/3683852/4346779/0e5d50a8-4115-11e4-9864-65580fc142b9.png)

Student View
![image](https://cloud.githubusercontent.com/assets/3683852/4346780/40a98cc0-4115-11e4-88c7-6ba6ff4e3afc.png)

Clicking the link:
![image](https://cloud.githubusercontent.com/assets/3683852/4346782/5dde894e-4115-11e4-8ed2-5d859859b2c0.png)

**Comment by simonista** [comment]
Do they only appear on the assignment index page, or also the quiz index page?  Is it possible that you are looking at the page without being logged in to canvas?  We are in the process of fixing a bug where unpublished content is visible only on the assignment index page for logged out users in public courses.
