### ISSUE TITLE
Course > Files page is blank

### ISSUE THREAD

**Issue by EugeneWHZ** [instructure/canvas-lms#519]
Hi,

When I navigate to Course >> files I am getting a blank page. 

URL is http://example.com/courses/2/files. When I click on the URL I am redirected to http://example.com/courses/1/files/courses/2/files and blank page is displayed.

In Canvas production logs I am getting error below. 

Please advice how can I troubleshoot and solve the issue.

Thanks!
###
[964b211050e9d11b0ee5168199d0c784 13314040-2b6f-0132-1af9-00163eb82db2]   Parameters: {"controller"=>"folders", "action"=>"resolve_path", "format"=>"json", "course_id"=>"2", "full_path"=>["courses", "2", "files"]}
[964b211050e9d11b0ee5168199d0c784 13314040-2b6f-0132-1af9-00163eb82db2]
ActiveRecord::RecordNotFound (ActiveRecord::RecordNotFound):
  app/controllers/folders_controller.rb:167:in `resolve_path'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/base.rb:1333:in `perform_action'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:617:in `call_filters'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:638:in `block in run_before_filters'
  app/controllers/application_controller.rb:172:in `set_locale'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activesupport/lib/active_support/callbacks.rb:178:in `evaluate_method'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:186:in `call'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:635:in `run_before_filters'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:615:in `call_filters'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:610:in `perform_action_with_filters'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/benchmarking.rb:68:in `block in perform_action_with_benchmark'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/rescue.rb:160:in `perform_action_with_rescue'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/flash.rb:151:in `perform_action_with_flash'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/base.rb:532:in `process'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/filters.rb:606:in `process_with_filters'
  vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/mini_profiler/profiling_methods.rb:79:in `block in profile_method'
  vendor/bundle/ruby/1.9.1/gems/oauth-instructure-0.4.10/lib/oauth/request_proxy/action_controller_request.rb:72:in `process_with_oauth'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/base.rb:391:in `process'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/base.rb:386:in `call'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/routing/route_set.rb:438:in `call'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/dispatcher.rb:87:in `dispatch'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/dispatcher.rb:121:in `_call'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/dispatcher.rb:130:in `block in build_middleware_stack'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/query_cache.rb:29:in `call'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/query_cache.rb:29:in `block in call'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/query_cache.rb:9:in `cache'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/query_cache.rb:28:in `call'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/mini_profiler/profiler.rb:193:in `call'
  vendor/bundle/ruby/1.9.1/gems/sass-3.2.18/lib/sass/plugin/rack.rb:54:in `call'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/string_coercion.rb:25:in `call'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/params_parser.rb:15:in `call'
  app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  lib/canvas/request_throttle.rb:58:in `block in call'
  lib/canvas/request_throttle.rb:229:in `reserve_capacity'
  lib/canvas/request_throttle.rb:54:in `call'
  app/middleware/stats_timing.rb:8:in `block in call'
  app/middleware/stats_timing.rb:8:in `call'
  app/middleware/request_context_generator.rb:34:in `call'
  vendor/bundle/ruby/1.9.1/gems/encrypted_cookie_store-instructure-1.0.6/lib/encrypted_cookie_store.rb:36:in `call'
  app/middleware/sessions_timeout.rb:22:in `call'
  app/middleware/load_account.rb:12:in `call'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/failsafe.rb:26:in `call'
  <internal:prelude>:10:in `synchronize'
  vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/actionpack/lib/action_controller/dispatcher.rb:106:in `call'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/request_handler.rb:97:in `process_request'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_request_handler.rb:520:in `accept_and_process_next_request'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/utils.rb:470:in `safe_fork'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:180:in `start'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:129:in `start'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in `synchronize'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/share/phusion-passenger/helper-scripts/passenger-spawn-server:99:in `<main>'

**Comment by simonista** [comment]
Closing due to lack of response from original submitter.
