### ISSUE TITLE
PG::Error: SSL error: no start line

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#524]
Dear Sir,

After doing the Canvas (open source) upgrade on June 12, our server started getting the "ActionView::TemplateError (PG::Error: no connection to the server" and "ActiveRecord::StatementInvalid (PG::Error: SSL error: no start line" in the production log. I wonder if the errors are related to the upgrade on June 12. Can the latest release of the Canvas fix these PG errors? Thanks.

Chi-Hou

**Comment by simonista** [comment]
Hey @cvong, this sounds more like a configuration issue to me.  You might have better luck over on the mailing list.  One thing to double check is that you are running at least Postgres 9.1.  Good luck!
