### ISSUE TITLE
Suggested improvement to Canvas Conference’s Interface: End a session

### ISSUE THREAD

**Issue by jfederico** [instructure/canvas-lms#530]
When a conference is In Progress, add ability to end the conference

![end_conference](https://cloud.githubusercontent.com/assets/578359/4785525/f48f0680-5d7f-11e4-8f3c-d1a1f259f007.PNG)

This allows the teacher the ability to kick everyone out of a session after they have left.

**Comment by simonista** [comment]
Fixed in https://github.com/instructure/canvas-lms/pull/532
