### ISSUE TITLE
Bug on Canvas Conference’s Interface: Students can not end own conference

### ISSUE THREAD

**Issue by jfederico** [instructure/canvas-lms#534]
Students are now able to create conferences and invite participants. This is a great feature for collaboration. The problem is that when students create the conference, even though the End button is shown (right now on 'non time limit' conferences only) , they are not able to end it. An error message is shown.

![conference_cannot_be_ended](https://cloud.githubusercontent.com/assets/578359/4796591/5055f850-5e04-11e4-893c-c0f0dd89504d.PNG)

**Comment by simonista** [comment]
Fixed in https://github.com/instructure/canvas-lms/pull/532
