### ISSUE TITLE
[BUG] Emails seem to be sent in the default locale set

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#537]
Hi :)

A new bug that led me to set the default locale as discussed in this issue: #528 

We noticed that daily emails notifications headers and footers were no longer sent in the locale used by the user but they seem to be sent using the i18n.default_locale set. 

On our application we have 80% of French users and we noticed that if the body of daily email notifications were sent in French, that was not true for their headers and footers, a French user would receive something like this: 

```
You're signed up to receive a daily report of some notifications from your Canvas account. Below is the report for Oct 15:

user@domain a accepté l’invitation au cours

user@domain vient d’accepter l’invitation à participer au cours Cours test en tant qu’étudiant.

Click to view

user@domain a accepté l’invitation au cours

user@domain vient d’accepter l’invitation à participer au cours Cours test en tant qu’étudiant.

Click to view


    Click here to edit your notification preferences    


Canvas Instructure Logo

Click here to edit your notification preferences    |   © 2014 Canvas Instructure
```

When I modified the i18n.default_locale in environments/production.rb config to :fr, everything was in French. But then we tested to use english as a language for a user, and we received everything in French (including the body). 

So that would mean that email locale is not set regarding receiver's configuration? Strange things is that it seems to be true for periodic notifications but not for instant or delayed messages. 

I'm not sure if it is a new issue or not. It would be great if you could try to reproduce this bug. That would tell us if there is something wrong with our app or not. 

Thanks! :)
Regis.

**Comment by claydiffrient** [comment]
@Kulgar I've looked at this and it does indeed seem to be a bug.  I've created a ticket in our internal ticketing system and sent it to the appropriate team.  We'll keep you updated.
