### ISSUE TITLE
canvas quiz statistics

### ISSUE THREAD

**Issue by nanayaw19** [instructure/canvas-lms#552]
after running "bundle exec rake canvas:compile_assets"  rake task aborts and i get the error
"Undumpable Exception -- #<RuntimeError: Build script failed for client app canvas_quiz_statistics>"

**Comment by simonista** [comment]
try removing `client_apps/canvas_quiz_inspector` and `client_apps/canvas_quiz_statistics`, these got moved, but had the possibility of leaving behind some cruft which confuses the javascript build task.  Sorry for the trouble!

**Comment by ridius** [comment]
Hey @simonista,

When I upgraded, I still had `client_apps/canvas_quiz_statistics`. Removing this directory solved the issue for me.
