### ISSUE TITLE
Make additional course attributes available via /api/v1/accounts/{account_id}/courses

### ISSUE THREAD

**Issue by lbjay** [instructure/canvas-lms#555]
I need the **is_public** attribute of a course to be included in the api response for a course listing at the account level, ie, in the response from ```/api/v1/account/{account_id}/courses```. It does seem to be possible to get it from a call to ```/api/v1/courses``` by adding *"&include=is_public"* as a parameter, but that doesn't really help me because the response in that case is limited to the context of the current user. The *"&include=..."* param is not recognized by the account level method (not sure why).

**Comment by claydiffrient** [comment]
@lbjay I'm glad we were able to help you with this.  I'm going to go ahead and close this issue, since it seems that the commit you mentioned takes care of it for you.  If you have further needs please feel free to let us know.
