### ISSUE TITLE
Undumpable Exception with canvas:compile_assets rake task

### ISSUE THREAD

**Issue by redconfetti** [instructure/canvas-lms#559]
Just updated my local development instance of Canvas on master branch, receiving this error when compiling assets. This seems similar to issues reported in #552, #498, and #547, though different errors arose in those reports.

```
$ bundle exec rake canvas:compile_assets
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /Users/jasonmiller/Projects/canvas-lms/Rakefile:11)
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /Users/jasonmiller/Projects/canvas-lms/Rakefile:11)
working in 8 processes
--> Starting: 'Compile sass and make jammit css bundles'
--> Starting: 'npm run compile-sass'
--> Starting: 'css:styleguide'
--> Starting: 'compile coffee, js 18n, and run r.js optimizer'
--> Starting: 'Generate documentation [yardoc]'
--> Starting: 'js:generate'
--> creating styleguide
Building client app 'canvas_quiz_statistics'
    Running 'npm run build'...
/Users/jasonmiller/.rvm/gems/ruby-2.1.3@canvas-lms/bin/rake: No such file or directory - ./script/build
            -------------------------------------------------------------------
            BUILD FAILURE:

            -------------------------------------------------------------------

> canvas-lms@0.0.0 compile-sass /Users/jasonmiller/Projects/canvas-lms
> node script/compile-sass.js

# writing file: app/views/info/styleguide.html.erb
--> Finished: 'css:styleguide' in 6.485412
Files:          91
Modules:         0 (    0 undocumented)
Classes:        90 (   26 undocumented)
Constants:       0 (    0 undocumented)
Methods:       384 (    7 undocumented)
 93.04% documented
API Documentation successfully generated in public/doc/api
See public/doc/api/index.html
--> Finished: 'Generate documentation [yardoc]' in 26.480803
--> Finished: 'npm run compile-sass' in 28.910356
--> Starting: 'Jammit'
--> Finished: 'Jammit' in 0.717718
--> Finished: 'Compile sass and make jammit css bundles' in 29.628696
rake aborted!
Undumpable Exception -- #<RuntimeError: Build script failed for client app canvas_quiz_statistics>
/Users/jasonmiller/.rvm/gems/ruby-2.1.3@canvas-lms/gems/parallel-0.5.16/lib/parallel.rb:173:in `work_in_processes'
/Users/jasonmiller/.rvm/gems/ruby-2.1.3@canvas-lms/gems/parallel-0.5.16/lib/parallel.rb:55:in `map'
/Users/jasonmiller/Projects/canvas-lms/lib/tasks/canvas.rake:167:in `block (3 levels) in <top (required)>'
/Users/jasonmiller/Projects/canvas-lms/lib/tasks/canvas.rake:166:in `block (2 levels) in <top (required)>'
/Users/jasonmiller/.rvm/gems/ruby-2.1.3@canvas-lms/bin/ruby_executable_hooks:15:in `eval'
/Users/jasonmiller/.rvm/gems/ruby-2.1.3@canvas-lms/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
```

Similar error occurring after I switch to stable branch. 

I see that the 'BUILD FAILURE' output is originating from the [js:build_client_apps rake task](https://github.com/instructure/canvas-lms/blob/41274611/lib/tasks/js.rake#L171).

I used Homebrew on my machine to update NodeJS, and also used `npm cache clean` to clear the cache.

**Comment by javawizard** [comment]
A fresh clone or a `rm -r client_apps/canvas_quiz_statistics` should also help.

**Comment by rsaray** [comment]
What is the reason for:
npm WARN package.json canvas_quizzes@1.0.0 No repository field.

**Comment by claydiffrient** [comment]
@rsaray That simply means that in the `package.json` file for `canvas_quizzes` there isn't a repository specified.  It can be completely ignored, as it won't cause any adverse effects.

**Comment by suyogtaksande** [comment]
i am getting this warning. need suggestions

npm WARN package.json canvas_quizzes@1.0.0 No repository field

Files:          97
Modules:         0 (    0 undocumented)
Classes:        96 (   30 undocumented)
Constants:       0 (    0 undocumented)
Methods:       424 (    9 undocumented)
 92.50% documented
API Documentation successfully generated in public/doc/api
See public/doc/api/index.html
--> Finished: 'Generate documentation [yardoc]' in 45.1148107179979
rake aborted!
Undumpable Exception -- #<EOFError: end of file reached>
/home/suyog/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/home/suyog/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/home/suyog/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/home/suyog/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/home/suyog/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/home/suyog/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/home/suyog/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

**Comment by simonista** [comment]
Looks like something about running your rake tasks in parallel is causing problems.  I would try temporarily modifying lines 163 - 169 of `lib/tasks/canvas.rake` from

```ruby
times = nil
real_time = Benchmark.realtime do
  times = Parallel.map(tasks, :in_processes => processes.to_i) do |name, lamduh|
    log_time(name) { lamduh.call }
  end
end
combined_time = times.reduce(:+)
```
to
```ruby
tasks.map do |name, fn|
  puts "running #{name}"
  fn.call
end
```
That will be slower but hopefully will help us narrow down the problem.

**Comment by khoer52** [comment]
Dear Simonista.

i have tested your suggestion. Unfortunately, it causes another problem.
"NameError: undefined local variable or method `real_time' for main:Object".

I hope it can be solved soon.
Thank you

**Comment by simonista** [comment]
That's actually good, hopefully that's the real problem. Do you have the full stacktrace?
