### ISSUE TITLE
Profile pictures not shown after 12/6 upgrade

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#560]
Hi,

After we upgraded our open source Canvas LMS to 12/6 release, all the users' profile pictures are not shown except the default avatar. Users can't upload profile pictures. The developer tools console shows no pic message. Could you tell me what might be the problem? Thanks.

**Comment by simonista** [comment]
Hey @cvong, sorry no one ever responded to you about this.  It looks like you were storing attachments in `/tmp`.  Sounds like they may have been cleaned up.  I'd recommend storing attachments in a more permanent place.
