### ISSUE TITLE
Submissions API Confusion (Bug? live interface differs from correct call)

### ISSUE THREAD

**Issue by cycomachead** [instructure/canvas-lms#564]
I'm trying to use the endpoint to get submissions for multiple assignments. 

Docs:
https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.for_students

It takes in a list of students, and this is where things get a bit confusing:
The live interface gives the following example URL:
https://bcourses.berkeley.edu:443/api/v1/courses/1249054/students/submissions?student_ids=XXXXX&assignment_ids=5179913%2C%205179914&&

However, a correct URL is this:
https://bcourses.berkeley.edu/api/v1/courses/1246916/students/submissions?assignment_ids=51799134&student_ids[]=XXXXXX

The difference is in the `[]`after `student_ids`. This is inconsistent with the Live API interface, and also somewhat inconsistent with the way assignment IDs are handled, which are described in the same way. 
The above URL does work, but specifying multiple IDs must be done in the same way as student IDs. 

Code Docs:
https://github.com/instructure/canvas-lms/blob/master/app/controllers/submissions_api_controller.rb#L207-L232

**Comment by simonista** [comment]
Hey @cycomachead, thanks for the report.  I was able to reproduce it, and @canadaduane, who is our resident live api expert, is going to take a look.  We use a modified version of https://github.com/swagger-api/swagger-js, and in this case it just isn't handling the way rails expects array parameters to come in.  To be clear, both student_ids and assignment_ids, when passing more than one, should be specified as `student_ids[]=X&student_ids[]=Y` or `assignment_ids[]=X&assignment_ids[]=Y`.

**Comment by canadaduane** [comment]
I have a patch for this going through QA now.

**Comment by cycomachead** [comment]
Awesome, thanks all for the help!

I'm continually impressed and excited by what you've done, which isn't too common for a LMS. ;-)

-- 
Michael Ball
From my iPhone
michaelballphoto.com

**Comment by cycomachead** [comment]
:+1:
