### ISSUE TITLE
options cannot be saved on Course Details page

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#567]
I tried to check or uncheck some options at the bottom of the Course Details page. The message showed "Course was successfully saved" but when I opened the page again, options were not saved. Do you know what might be the problem? Thanks.

**Comment by simonista** [comment]
which options specifically did you try?

**Comment by cvong** [comment]
It looks like if I change the "Let students attach files to discussions," other options will get saved. If I only change other options without changing the  "Let students attach files to discussions," the changes will not get saved.

**Comment by simonista** [comment]
Sorry we never got back to you about this, I'm going to assume it's been fixed in the last 3 years.
