### ISSUE TITLE
Unable to complete newly created quiz. 

### ISSUE THREAD

**Issue by wmuengineer** [instructure/canvas-lms#568]
When we create a new module and a new quiz we aren't' able have student complete the quiz. When they submit their answer we receive this:

    PG::SyntaxError: ERROR:  zero-length delimited identifier at or near """"
LINE 37: ' WHERE "versions"."" = 75077
                            ^
: UPDATE "versions" SET "yaml" = '--- 
id: 17455
body: "user: 3568, quiz: 1640, score: 0, time: 2015-01-12 22:12:26 -0800"
url: 
attachment_id: 
grade: "0"
score: !float 0
submitted_at: 2015-01-13 06:12:26.212828 Z
assignment_id: 2697
user_id: 3568
submission_type: online_quiz
workflow_state: pending_review
created_at: 2015-01-13 06:12:11.830780 Z
updated_at: 2015-01-13 06:12:26.475391 Z
group_id: 
attachment_ids: 
processed: 
process_attempts: 0
grade_matches_current_submission: true
published_score: !float 0
published_grade: "0"
graded_at: 2015-01-13 06:12:26.226506 Z
student_entered_score: 
grader_id: -1640
media_comment_id: 
media_comment_type: 
quiz_submission_id: 18001
submission_comments_count: 
has_rubric_assessment: 
attempt: 1
context_code: course_200
media_object_id: 
turnitin_data: {}

has_admin_comment: false
cached_due_date: 
' WHERE "versions"."" = 75077

For the entire stack trace go here: https://www.dropbox.com/s/5fdw2e385e136vw/PG%3ASyntaxError%3A%20ERROR%3A%20%20zero-length%20delim.txt?dl=0

**Comment by simonista** [comment]
Huh, we haven't heard of anyone else with this issue.  It seems like it's failing to interpolate the primary key name ('id') into the sql statement. What version of Postgres are you using? Can you post more detailed reproduction steps?
