### ISSUE TITLE
Moodle course import issue

### ISSUE THREAD

**Issue by edevyatkin** [instructure/canvas-lms#572]
We had tried to import Moodle course archive files in Canvas but every time receive an error:

 unknown mime type application/octet-stream

        /var/canvas/gems/canvas_unzip/lib/canvas_unzip.rb:127:in `each_entry'
/var/canvas/gems/canvas_unzip/lib/canvas_unzip.rb:70:in `extract_archive'
/var/canvas/lib/canvas/migration/archive.rb:73:in `unzip_archive'
/var/canvas/lib/canvas/migration/migrator.rb:54:in `unzip_archive'
/var/canvas/vendor/plugins/moodle2cc/lib/moodle/converter.rb:8:in `export'
/var/canvas/lib/cc/importer/cc_worker.rb:49:in `perform'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/backend/base.rb:224:in `invoke_job'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:136:in `block (2 levels) in perform'
/home/test/.rvm/rubies/ruby-1.9.3-p551/lib64/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:130:in `block in perform'
/var/canvas/config/initializers/delayed_job.rb:68:in `call'
/var/canvas/config/initializers/delayed_job.rb:68:in `block (2 levels) in <top (required)>'
/var/canvas/gems/canvas_statsd/lib/canvas_statsd/statsd.rb:75:in `time'
/var/canvas/config/initializers/delayed_job.rb:67:in `block in <top (required)>'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:78:in `call'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:60:in `call'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:78:in `call'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:78:in `block in add'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:65:in `call'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:65:in `execute'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:127:in `perform'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:102:in `block in run'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:194:in `configure_for_job'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:101:in `run'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:78:in `block in start'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:77:in `loop'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:77:in `start'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:156:in `block in spawn_worker'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:167:in `block in fork_with_reconnects'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:164:in `fork'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:164:in `fork_with_reconnects'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:155:in `spawn_worker'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:143:in `block (2 levels) in spawn_all_workers'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:143:in `times'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:143:in `block in spawn_all_workers'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:141:in `each'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:141:in `spawn_all_workers'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:103:in `start'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:74:in `run'
/var/canvas/script/delayed_job:10:in `<main>'

We have OpenSUSE 13.2, ruby 1.9.3 (through rvm)
How to solve this issue?

Evgeniy

**Comment by ccutrer** [comment]
Canvas uses the `file` command (http://en.wikipedia.org/wiki/File_(command)) to auto-detect what kind of archive an uploaded file is. Give that you're getting "application/octet-stream", the `file` command exists for you, but is unable to identify the archive. You'll need to determine why.
