### ISSUE TITLE
Getting error on migration from scratch

### ISSUE THREAD

**Issue by mico** [instructure/canvas-lms#573]
Hello! I'm trying to execute bundle exec rake db:initial_setup
so i get error:
```
undefined method `shard' for []:Array/Users/mico/Documents/Projects/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.2.22/lib/switchman/active_record/base.rb:8:in `shard'
/Users/mico/Documents/Projects/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.2.22/lib/switchman/active_record/base.rb:90:in `save!'
/Users/mico/Documents/Projects/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/validations.rb:17:in `create!'
/Users/mico/Documents/Projects/canvas/db/migrate/20120717140514_add_file_notifications.rb:7:in `up'
```
I've tried some manipulations with Notification, so it returns empty array [] on :all method
in migration it's doing:
```
    Notification.create!(:name => "New File Added", :category => "Files")
```
irb:
```
2.1.5 :015 > Notification.all
 => [] 
```

**Comment by mico** [comment]
fixed it by patching code:
@@ -68,7 +68,7 @@ class Notification < ActiveRecord::Base
   end
 
   def self.all
-    @all ||= super.to_a.each(&:readonly!)
+    @all ||= super
   end
 
   def self.find(id, options = {})

but at some migrations getting error:
==  PeerReviewInvitationNeedsNotification: migrating ==========================
==  PeerReviewInvitationNeedsNotification: migrated (0.0304s) =================

rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `global_attribute' for #<Notification:0x007fe3b2e7a9a8>/Users/mico/Documents/Projects/canvas/vendor/bundle/ruby/2.1.0/gems/activemodel-4.0.12/lib/active_model/attribute_methods.rb:439:in `method_missing'

after run again, migration continue

**Comment by ccutrer** [comment]
You appear to be running with Rails 4 somehow (`activemodel-4.0.12`). Rails 4 is not yet supported by Canvas.
