### ISSUE TITLE
Quiz statistics for matching

### ISSUE THREAD

**Issue by hugelgupf** [instructure/canvas-lms#574]
Quiz statistic for matching questions don't seem to be compiled correctly:

![canvas](https://cloud.githubusercontent.com/assets/1994130/5950442/73ecf41a-a717-11e4-9559-118e69e0ed41.png)

If I look at this in the speed grader, it tells me that not everyone failed each one of the matching questions; so something is obviously wrong about this.

**Comment by ryanmt** [comment]
Have you tried the new quiz statistics?  They are going to go live soon for production canvas.

**Comment by hugelgupf** [comment]
I have not. My school is using instructure.com hosting, so I have to wait for that.

**Comment by hugelgupf** [comment]
Just noticed it's live. Nevermind, then!
