### ISSUE TITLE
How to cleanup /var/canvas/tmp

### ISSUE THREAD

**Issue by ibnIrshad** [instructure/canvas-lms#577]
/var/canvas/tmp has grown to several gigabytes in size on my machine after many months of use, and I want to know how to purge/cleanup unneeded files. Are attachments and other user data stored there? Is it safe to simple delete the contents of the directory?

**Comment by simonista** [comment]
Hey @ibnIrshad, yes, it's possible that user file attachments are stored in tmp/files.  I'd check out what the makeup of the tmp folder is (which sub-folders are taking up the most space) and also check what the config settings are for file storage in `config/file_store.yml`.
