### ISSUE TITLE
Inconsistent handling of arrays as URL query parameters

### ISSUE THREAD

**Issue by ToeBee** [instructure/canvas-lms#579]
I am trying to use some include options with an API call. The [list users in course](https://canvas.instructure.com/doc/api/courses.html#method.courses.users) API endpoint (in the [courses controller](https://github.com/instructure/canvas-lms/blob/master/app/controllers/courses_controller.rb#L718)) requires the include option to be specified as `include[]=sections` whereas the [list course sections](https://canvas.instructure.com/doc/api/sections.html#method.sections.index) endpoint (in the [sections controller](https://github.com/instructure/canvas-lms/blob/master/app/controllers/sections_controller.rb#L104)) will accept either `include=students` or `include[]=students`

The live API test page (at https://[instance base]/doc/api/live) constructs the URLs without the `[]` in them so selecting anything from the `include` dropdown in the `list users in course` area has no effect and it looks like the API is just ignoring the include parameter.

These are the only two endpoints I have tested. I have no idea which way it is supposed to be or if any other endpoints are affected. Although judging by the fact that the live API test page doesn't use `[]` I'm guessing that the `list users in course` endpoint is in the wrong here and should accept the request with or without them.

**Comment by simonista** [comment]
Hey @ToeBee, actually the list users endpoint is correct here and the live api page is wrong.  We actually already have a commit to fix the live api (67038cf1444a72a717ee0081142b4311d38ed6df) which will go out to production with the 2015-02-21 release.

the include[]=... syntax comes from the way rails handles array parameters.  You can read more about that here: http://guides.rubyonrails.org/action_controller_overview.html#hash-and-array-parameters.  The reason some endpoints like the sections controller works with the brackets is that they wrap the params[:include] variable in `Array(...)` which converts it into an array if it isn't already.  But even so, it will only allow you to pass one include parameter, whereas the bracket syntax allows multiple include parameters in the same request (with `include[]=A&include[]=B`).

Hope that clarifies things!

**Comment by ToeBee** [comment]
*sigh.* So if I had been using the live API page in beta instead of test, I could have saved myself an hour or two of head beating. Oh well. Thanks for the clarification.
