### ISSUE TITLE
Automatic quiz generation through REST API

### ISSUE THREAD

**Issue by jolburns** [instructure/canvas-lms#580]
Howdy,

I've been working on implementing an automatic quiz generator using Ruby. I've been able to successfully generate quizzes and questions using CURL. I've run into an issue creating more complex questions that have included answers. For example this question below was generated from within Canvas, but I cannot recreate it with CURL.

{"assessment_question_id":71181606,
"id":40635545,
"position":2,
"quiz_group_id":null,
"quiz_id":1900474,
"question_name":"Role",
"question_type":"multiple_dropdowns_question",
"question_text":"\u003Cp\u003ERole: I am a [role]\u003C/p\u003E",
"points_possible":1,
"correct_comments":"",
"incorrect_comments":"",
"neutral_comments":"",
"answers":[{"id":9764,"text":"RESIDENT: 1st year","comments":"","weight":100,"blank_id":"role"},
{"id":3807,"text":"RESIDENT: 2nd year","comments":"","weight":0,"blank_id":"role"},
{"id":4230,"text":"RESIDENT: 3rd year","comments":"","weight":0,"blank_id":"role"},
{"id":4586,"text":"RESIDENT: 4th year","comments":"","weight":0,"blank_id":"role"},
{"id":8071,"text":"FELLOW","comments":"","weight":0,"blank_id":"role"},
{"id":676,"text":"FACULTY","comments":"","weight":0,"blank_id":"role"},
{"id":3365,"text":"MED STUDENT","comments":"","weight":0,"blank_id":"role"},
{"id":2728,"text":"Other","comments":"","weight":0,"blank_id":"role"}],
"variables":null,
"formulas":null,
"matches":null,
"matching_answer_incorrect_matches":null}

Using CURL to make a quiz:
curl --request POST https://<site>.instructure.com/api/v1/courses/1423186/quizzes?access_token=<token> --data "quiz[title]=test&quiz[description]=test&quiz[quiz_type]=survey"

Using CURL to make a normal question:
curl --request POST https://<site>.instructure.com/api/v1/courses/1423186/quizzes/1903858/questions?access_token=<token> --data "question[question_name]='Topic'&question[question_text]='Topic:'&question[question_type]=short_answer_question&question[position]=1&question[points_possible]=0"

Thank you for any help you can give!

Copy of question https://help.instructure.com/entries/60155414

**Comment by simonista** [comment]
In the api, it looks like the quiz question creation endpoint does take a [answers] field.  Is there an error that is being returned when you try to include them? Or are they just being silently ignored?

**Comment by simonista** [comment]
Oops, meant to link to the api docs I was looking at: https://canvas.instructure.com/doc/api/quiz_questions.html#method.quizzes/quiz_questions.create
