### ISSUE TITLE
Flash - doesn't get shown

### ISSUE THREAD

**Issue by GildedHonour** [instructure/canvas-lms#581]
When I put an error or a notice in flash, I don't see anything after redirect:

```
flash[:error] = 'Error' # or flash[:notice] = 'Success!'
redirect_to ....
```

**Comment by simonista** [comment]
Which controller action are you adding this to specifically, and where are you redirecting?

**Comment by GildedHonour** [comment]
I'm doing it in my own controller, none of these combinations are working, the flash doesn't display itself on the screen, even so it does exist in the source code of the page  in **javascript** code:

```
  # flash[:notice] = 'Success!'
    flash[:error] = 'Error!'
    # redirect_to home_url
    redirect_to courses_url

```

![screen shot 2015-02-08 at 11 38 31](https://cloud.githubusercontent.com/assets/2032888/6095289/527eb656-af87-11e4-8b0d-bd9518c0cde2.png)
