### ISSUE TITLE
What should be the content of assets_real.yml?

### ISSUE THREAD

**Issue by GildedHonour** [instructure/canvas-lms#583]
What should be the content of assets_real.yml?

```
bundle exec rake canvas:compile_assets
Errno::ENOENT: No such file or directory - config/assets_real.yml
```

**Comment by simonista** [comment]
https://github.com/instructure/canvas-lms/blob/stable/config/assets_real.yml

**Comment by GildedHonour** [comment]
Should I just copy-past it as it is, no changes?

**Comment by jenseng** [comment]
@GildedHonour yes... I'm curious why you don't have that file, as it's part of the repo.

You could dry running `git status` to see if you're missing any other files. The output should be:

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

On the other hand, if it shows you are missing files, you might need to run `git reset --hard HEAD` to restore things

**Comment by jenseng** [comment]
(note that `git reset --hard HEAD` is a bit of a hammer, so if you have files you've intentionally changed, you might want to check in those changes too)
