### ISSUE TITLE
Force the user to authenticate, sending email and the field "email"

### ISSUE THREAD

**Issue by GildedHonour** [instructure/canvas-lms#585]
A few questions:

1) How to force the users authenticate to access a controller? Usually such a method is called "authenticate_user!" and put in "before_filter" at a controller level. 
```
class MyController < ApplicationController
  before_filter :authenticate_user!
  #...
```

But there's "authenticate_user!" in canvas.

2) There's no "email" field in the table users

```
CREATE TABLE users (
    id bigint NOT NULL,
    name character varying(255),
    sortable_name character varying(255),
    workflow_state character varying(255) NOT NULL,
    merge_to integer,
    time_zone character varying(255),
    uuid character varying(255),
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    visibility character varying(255),
    avatar_image_url character varying(255),
    avatar_image_source character varying(255),
    avatar_image_updated_at timestamp without time zone,
    phone character varying(255),
    school_name character varying(255),
    school_position character varying(255),
    short_name character varying(255),
    deleted_at timestamp without time zone,
    show_user_services boolean DEFAULT true,
    gender character varying(255),
    page_views_count integer DEFAULT 0,
    unread_inbox_items_count integer,
    reminder_time_for_due_dates integer DEFAULT 172800,
    reminder_time_for_grading integer DEFAULT 0,
    storage_quota bigint,
    visible_inbox_types character varying(255),
    last_user_note timestamp without time zone,
    subscribe_to_emails boolean,
    features_used text,
    preferences text,
    avatar_state character varying(255),
    locale character varying(255),
    browser_locale character varying(255),
    unread_conversations_count integer DEFAULT 0,
    stuck_sis_fields text,
    public boolean,
    birthdate timestamp without time zone,
    otp_secret_key_enc character varying(255),
    otp_secret_key_salt character varying(255),
    otp_communication_channel_id bigint,
    initial_enrollment_type character varying(255),
    crocodoc_id integer,
    last_logged_out timestamp without time zone,
    days_available character varying(255),
    times_available character varying(255),
    lti_context_id character varying(255),
    uu_idc character varying(255),
    stripe_customer_id character varying(255)
);
```

So where is the user's email stored? How do I get the user's (student's) email when I need to send them an email?

3) And in general what's the easiest way to send an email to the user and admin? I know there's a class Mailer and a method  create_message but it seems tricky. Is there any example? 

I haven't found anything about those topics in the documentation.

**Comment by ccutrer** [comment]
1. `before_filter :require_user`
2. `communication_channels` table, which holds different ways of contacting user. `user.email` returns the first active e-mail communication channel for the user.
3. https://github.com/instructure/canvas-lms/blob/stable/app/models/communication_channel.rb#L208 is about as simple as we can make it.

**Comment by GildedHonour** [comment]
Thanks.
1. And how to get the current user: @current_user or @current_pseudonym?

**Comment by simonista** [comment]
@current_user

**Comment by simonista** [comment]
rather than checking if the user is an admin directly, you'll want to check if they have the appropriate permission to do something on on the object you are interacting with.  These custom permissions show up in the account permissions page, and come from https://github.com/instructure/canvas-lms/blob/stable/app/models/role_override.rb.  You'd query using something like: `@course.grants_right?(@current_user, send_messages_all)` (or @account.grants_right?, or your custom permission, etc)

**Comment by simonista** [comment]
If you really do need to get their account admin relationship directly, it is `user.account_users`

**Comment by GildedHonour** [comment]
I need to allow only admin to visit the certain page(s) I've created myself. What's the best way to accomplish this?

**Comment by simonista** [comment]
I'm assuming these pages live under the context of the account?  If the url is like /accounts/X/your-page then you can use `before_filter :get_context` to preload the @context variable with the appropriate account, and then either reuse an existing permission from above or create your own.  Then at the top of your action, you can just do `return unless authorized_action(@context, @current_user, :whatever_permission)`.  This will return a 401 unauthorized error, or let execution continue.

Check out some actions in the accounts controller (like https://github.com/instructure/canvas-lms/blob/stable/app/controllers/accounts_controller.rb#L655) for examples of this

**Comment by GildedHonour** [comment]
Not only. I need the users can only access the pages at http://domain.com/courses/:course_id/.... if "some_condition" is true for them, I added that condition to User model. But I also need the admin can always access those pages unconditionally. How can I do this?

Right now I'm doing it like this:
```
AppController
  before_action :my_action


  def my_action
     # how to check if @current_user is NOT admin ?
      if @current_user && (@current_user is not admin) && @current_user.some_condition_is_true
        #.....
      end
   end
end
```
