### ISSUE TITLE
Export file

### ISSUE THREAD

**Issue by yongra** [instructure/canvas-lms#588]
Hi. 

I followed the production instruction and have my site running. I can import a course from Moodle or another canvas export course. One thing that is not working is export. When I export a course, I get an empty file (0 bytes). Can anyone help what I have missed?

Thank you.

**Comment by yongra** [comment]
I also notice that the file export file is in the tmp directory and it has data in it. The issue is when the link is click to download on the webpage, the canvas sends the file with 0 bytes. It looks like some sort of apache or permission issue. Can anyone help?

Thanks,

**Comment by juniorojha** [comment]
Facing the same issue now - unable to download any files. But the files are present on the server and scp download works fine.
