### ISSUE TITLE
Is the user admin?

### ISSUE THREAD

**Issue by GildedHonour** [instructure/canvas-lms#589]
How do I check in ApplicationController whether the user is admin or not? ```authorized_action(@account, @current_user, :something)``` isn't what I'm looking for, ```Role.get_built_in_role('AccountAdmin')``` - not sure, it might be.

**Comment by simonista** [comment]
try `@domain_root_account.all_account_users_for(@current_user).exists?`

In the future, please to try restrict creating github issues for reporting real bugs in the canvas code base.  These types of development questions are better answered on the mailing list: https://groups.google.com/forum/#!forum/canvas-lms-users or in IRC, in #canvas-lms on freenode.
