### ISSUE TITLE
Adding a link to the left nav panel

### ISSUE THREAD

**Issue by GildedHonour** [instructure/canvas-lms#591]
How can I add a link to the left navigation panel? Either statically from web panel, or if that's not possible - from the code. I haven't found that in the documentation.

![screen shot 2015-02-13 at 19 28 48](https://cloud.githubusercontent.com/assets/2032888/6187255/df267430-b3b6-11e4-8dc8-1b856d8a89f3.png)

**Comment by jorgevbo** [comment]
Hi Alex,

Use LTI Redirect https://www.eduappcenter.com/apps/63


2015-02-13 8:33 GMT-04:00 Alex Maslakov <notifications@github.com>:

**Comment by GildedHonour** [comment]
Sorry, I don't understand how it can me. I need to add a "text" or "link" to the left nav bar, that's it.

**Comment by simonista** [comment]
@GildedHonour, the linked tool does exactly that.  Go to your account settings page, go to "Apps", search for "redirect", add the tool, choose the text/link you want, choose which navigation you want it to show up in (course, account, and/or user profile), and add it.

**Comment by GildedHonour** [comment]
@simonista, I'll just ask this question here. 

I want to add the link for all the users and admins in one fell swoop, not only for a single account. Or at least, for all the users-students. So that tool can do that?  Moreover, there's no link "Apps" at account settings page.
