### ISSUE TITLE
LTI Variable Substitution Documentation

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#592]
I just discovered the list of [variable substitutions](https://github.com/instructure/canvas-lms/blob/master/lib/lti/variable_expander.rb) that can be placed in an LTI config. 

I'm requesting that this list be added to the [LTI documentation](https://canvas.instructure.com/doc/api/file.tools_intro.html). 

Thanks!

**Comment by bracken** [comment]
Yeah, we've been wanting to get to that for a while. We just did some refactoring on the code side that should make the documentation easier. So hopefully we'll get to it soon.

**Comment by mdefendorf** [comment]
I am curious about this too. We are a tool provider and trying to identify how schools can use this so they can send the section IDs.

**Comment by jcthomsonjr** [comment]
+1
