### ISSUE TITLE
Locked directories in Files are not hidden from students

### ISSUE THREAD

**Issue by simong** [instructure/canvas-lms#593]
I have a simple course with some Files in it. I have a directory called `_thumbnails` that I use to put some thumbnails in via the API. The `_thumbnails` folder is locked and students can't see any of the files in it in the Files tool (though they can download them, which is fine).

However, I'd like the `_thumbnails` folder and all its child directories to be hidden from students as per the docs. Currently, they can navigate the structure which is a bit clumsy:

![](https://s3.amazonaws.com/f.cl.ly/items/2v3j3H1Z1n1J442I1i23/Screen%20Shot%202015-02-12%20at%2016.59.13.png)

Folder lock settings
![](https://s3.amazonaws.com/f.cl.ly/items/2R1W290k2l2j3R35440H/Screen%20Shot%202015-02-13%20at%2007.21.44.png)

**Comment by claydiffrient** [comment]
@simong I believe this problem is resolved when using our new files interface.  Try it out by turning on the Better File Browsing feature flag.  If it is still an issue please let us know.
