### ISSUE TITLE
List submissions for multiple assignments: "user not authorized to perform that action"

### ISSUE THREAD

**Issue by jorgevbo** [instructure/canvas-lms#594]
I'm using Canvas LMS API method:
GET /api/v1/courses/:course_id/students/submissions

But it return unauthorized error:
{"status":"unauthorized","errors":[{"message":"user not authorized to perform that action"}]}

I'm using main Admin Account User Token but I've got same error. Is it a bug? What kind of permissions need the super admin account to make it request?

**Comment by ccutrer** [comment]
As documented at https://canvas.instructure.com/doc/api/all_resources.html#method.submissions_api.for_students, with no student_ids argument, it will attempt to return the submissions for the calling user. Likely your account admin is _not_ enrolled in that course as a student, so will get access denied.

You probably want `GET /api/v1/courses/:course_id/students/submissions?student_ids[]=all` which will return submissions for all students in the course.

**Comment by jorgevbo** [comment]
Thanks!
