### ISSUE TITLE
Error while executing 'bundle exec rake canvas:compile_assets'

### ISSUE THREAD

**Issue by kurapatijayaram** [instructure/canvas-lms#597]
hi
when I execute 'bundle exec rake canvas:compile_assets' I am getting the following error while performing 'js:generate' task in that ....

$ bin/rake js:generate --trace
/home/heresy/canvas_production/gems/utf8_cleaner/lib/utf8_cleaner.rb:20:in `<top (required)>': iconv will be deprecated in the future, use String#encode instead.
** Invoke js:generate (first_time)
** Execute js:generate
** Invoke js:build_client_apps (first_time)
** Execute js:build_client_apps
Building client app 'canvas_quizzes'
	Running 'npm install'...
npm WARN package.json canvas_quizzes@1.0.0 No repository field.
	Running 'npm run build'...
Client app 'canvas_quizzes' was built successfully.
--> Pre-compiling handlebars templates--> Creating ember app bundles--> Compiling React JSX--> Generating plugin extensions
** Invoke js:jsx (first_time)

** Execute js:jsx

** Invoke js:generate_extensions (first_time)
--> Pre-compiling ember handlebars templates
** Invoke jst:ember (first_time)

** Execute jst:ember
** Invoke jst:compile (first_time)
** Execute js:generate_extensions
** Invoke js:bundle_ember_apps (first_time)
** Execute js:bundle_ember_apps
** Execute jst:compile
--> Generating plugin extensions finished in 0.188148294
--> Creating ember app bundles finished in 0.443743354
--> Compiling CoffeeScript with 'coffee' binary

/home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

/home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

/home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/heresy/canvas_production/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
--> Compiling React JSX finished in 4.640155623
rake aborted!
EOFError: end of file reached
/home/heresy/canvas_production/gems/handlebars_tasks/lib/handlebars_tasks/template_precompiler.rb:7:in `readline'
/home/heresy/canvas_production/gems/handlebars_tasks/lib/handlebars_tasks/template_precompiler.rb:7:in `precompile_template'
/home/heresy/canvas_production/gems/handlebars_tasks/lib/handlebars_tasks/handlebars.rb:83:in `compile_template'
/home/heresy/canvas_production/gems/handlebars_tasks/lib/handlebars_tasks/handlebars.rb:51:in `compile_file'
/home/heresy/canvas_production/gems/handlebars_tasks/lib/handlebars_tasks/handlebars.rb:34:in `block in compile'
/home/heresy/canvas_production/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:275:in `call'
/home/heresy/canvas_production/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:275:in `call_with_index'
/home/heresy/canvas_production/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:130:in `block (2 levels) in work_in_threads'
/home/heresy/canvas_production/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:123:in `loop'
/home/heresy/canvas_production/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:123:in `block in work_in_threads'
/home/heresy/canvas_production/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:14:in `block (2 levels) in in_threads'
Tasks: TOP => jst:compile

Please some one help me .... the issue is with jst:compile

Thank u :-)

**Comment by jenseng** [comment]
i think i've seen a similar error (maybe the same one?) before ... you could removing your `gems/canvas_i18nliner/node_modules` directory and then running `npm install` again

another thing you might want to try would be to upgrade your version of node

[this thread](https://github.com/atom/atom/issues/2478) might have some useful info

**Comment by kurapatijayaram** [comment]
I am facing some weird behavior here ... when I am using latest node version ( i.e 0.12 )  my npm installation was not successful I mean I got some errors in building.js etc., but assets precompile was successfull. When I am using node version 0.10 npm installation was successful without any errors but while performing assets precompile I am getting which I mentioned as issue (i.e my first post on issue).


I continued with latest node version with installation error .... now canvas is working fine. Can I face any problems in future ? should I take it seriously or I can eliminate ?

**Comment by jenseng** [comment]
what sort of errors did you get installing the latest version of node? perhaps they were just warnings?

regardless, if assets are compiling correctly now for canvas, i think you should be ok

**Comment by syedzahed** [comment]
Same with me as i tried to install npm i got these errors.. any help would be appreciated

> canvas-lms@0.0.0 preinstall /home/heresy/canvas-lms
> script/gem_npm install

 
> sync-prompt@0.1.0 install /home/heresy/canvas-lms/node_modules/loom/node_modules/sync-prompt
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/heresy/canvas-lms/node_modules/loom/node_modules/sync-prompt/build'
  CXX(target) Release/obj.target/sync_prompt/src/sync_prompt.o
../src/sync_prompt.cc:9:28: error: ‘Arguments’ does not name a type
 Handle<Value> Prompt(const Arguments& args) {
                            ^
../src/sync_prompt.cc:9:39: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Handle<Value> Prompt(const Arguments& args) {
                                       ^
In file included from /home/heresy/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/sync_prompt.cc:1:
/home/heresy/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> Prompt(const int&)’:
/home/heresy/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/sync_prompt.cc:10:15: error: within this context
   HandleScope scope;
               ^
../src/sync_prompt.cc:13:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(String::New(retval.c_str()));
                ^
../src/sync_prompt.cc:13:22: error: ‘New’ is not a member of ‘v8::String’
   return scope.Close(String::New(retval.c_str()));
                      ^
../src/sync_prompt.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/sync_prompt.cc:17:16: error: ‘NewSymbol’ is not a member of ‘v8::String’
   exports->Set(String::NewSymbol("prompt"),
                ^
../src/sync_prompt.cc:18:35: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
       FunctionTemplate::New(Prompt)->GetFunction());
                                   ^
../src/sync_prompt.cc:18:35: note: candidate is:
In file included from /home/heresy/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/sync_prompt.cc:1:
/home/heresy/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/heresy/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../src/sync_prompt.cc: In function ‘v8::Handle<v8::Value> Prompt(const int&)’:
../src/sync_prompt.cc:14:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/sync_prompt/src/sync_prompt.o] Error 1
make: Leaving directory `/home/heresy/canvas-lms/node_modules/loom/node_modules/sync-prompt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/heresy/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/home/heresy/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/heresy/canvas-lms/node_modules/loom/node_modules/sync-prompt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/home/heresy/.nvm/versions/node/v0.12.0/bin/node" "/home/heresy/.nvm/versions/node/v0.12.0/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! sync-prompt@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sync-prompt@0.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sync-prompt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sync-prompt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/heresy/canvas-lms/npm-debug.log

**Comment by simonista** [comment]
I believe canvas does not currently support node 0.12.  We are working on it, but in the meantime, downgrading is probably your best bet.

**Comment by syedzahed** [comment]
thanks for reply simon. i will give a try

**Comment by kurapatijayaram** [comment]
In my case it was different ... When I use node 0.10 my assets were not pre-compiling .
