### ISSUE TITLE
Apps tab is blank when entering it from Settings

### ISSUE THREAD

**Issue by artfulhacker** [instructure/canvas-lms#599]
Easy to replicate, click settings it loads the Apps tab empty DOM.

Click another tab, then back to App and it populates.

![image](https://cloud.githubusercontent.com/assets/3683852/6423007/f8b747a8-be9c-11e4-9b2d-9d4f29120509.png)

**Comment by simonista** [comment]
Thanks for the report, this was fixed by 5f248efb822dd7c74fcd6a739eec25b667eba613 and should be in the stable branch by this coming monday
