### ISSUE TITLE
Issue when compiling

### ISSUE THREAD

**Issue by Portujua** [instructure/canvas-lms#608]
I'm installing canvas from an old script i created which of course was running great.. But now, i decided to make a new canvas from scratch and i'm getting an error when executing this command

bundle exec rake canvas:compile_assets

After npm install...  Here's the error:

root@host:/var/canvas# bundle exec rake canvas:compile_assets
/var/canvas/gems/utf8_cleaner/lib/utf8_cleaner.rb:20:in `<top (required)>': iconv will be deprecated in the future, use String#encode instead.
working in 2 processes
--> Starting: 'Compile sass and make jammit css bundles'
--> Starting: 'npm run compile-sass'
--> Starting: 'css:styleguide'
--> creating styleguide

> canvas-lms@0.0.0 compile-sass /var/canvas
> node script/compile-sass.js

# writing file: app/views/info/styleguide.html.erb
--> Finished: 'css:styleguide' in 4.743359489
--> Starting: 'compile coffee, js 18n, and run r.js optimizer'
--> Starting: 'js:generate'
Building client app 'canvas_quizzes'
        Running 'npm install'...
npm WARN package.json canvas_quizzes@1.0.0 No repository field.
        Running 'npm run build'...
Client app 'canvas_quizzes' was built successfully.
--> Creating ember app bundles
--> Pre-compiling ember handlebars templates
--> Pre-compiling handlebars templates
--> Creating ember app bundles finished in 0.02357178--> Compiling React JSX--> Generating plugin extensions

--> Generating plugin extensions finished in 0.000944345

module.js:340
    throw err;
          ^
Error: Cannot find module 'ember-template-compiler'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/canvas/gems/canvas_i18nliner/bin/prepare_hbs:5:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

module.js:340
    throw err;
          ^
Error: Cannot find module 'ember-template-compiler'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/canvas/gems/canvas_i18nliner/bin/prepare_hbs:5:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

module.js:340
    throw err;
          ^
Error: Cannot find module 'ember-template-compiler'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/canvas/gems/canvas_i18nliner/bin/prepare_hbs:5:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
--> Compiling CoffeeScript with 'coffee' binary
--> Compiling React JSX finished in 4.147459698
--> Finished: 'npm run compile-sass' in 107.680021552
--> Starting: 'Jammit'
--> Finished: 'Jammit' in 1.468411114
--> Finished: 'Compile sass and make jammit css bundles' in 109.148925421
rake aborted!
Undumpable Exception -- #<EOFError: end of file reached>
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:173:in `work_in_processes'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:55:in `map'
/var/canvas/lib/tasks/canvas.rake:167:in `block (3 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:166:in `block (2 levels) in <top (required)>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

**Comment by rohandaxini** [comment]
@Portujua I am facing the exact same issue on my local too while setting up this. Did you found any solution to resolve it ?

**Comment by claydiffrient** [comment]
@Portujua @rohandaxini Did you perform a `npm install` prior to running `bundle exec rake canvas:compile_assets` ?

**Comment by rohandaxini** [comment]
yes @claydiffrient I did. My node version is 0.12.4.
It turns out this latest node version is not supported in canvas ?

Downgrading the node version to 0.10.28 resolved the issues for now. But I did face a lot of errors related to handlebars and ember specific node modules. I will send the trace here.

**Comment by claydiffrient** [comment]
K.  Yeah i meant to mention that you should use node 0.10.x for now until we get it moved up to 0.12 compatible.

**Comment by rohandaxini** [comment]
sure @claydiffrient thanks for your help. I am doing a fresh install of `canvas` using node version `0.10.33` so will keep u posted.

**Comment by jenseng** [comment]
Others have run into similar errors before, and this workaround generally
does the trick:

cd gems/canvas_i18nliner
rm -rf node_modules
npm install

Normally doing `npm install` from the top-level canvas dir is sufficient,
but in some instances it leaves canvas_i18nliner's node_modules in a
weird/broken state.

Jon

**Comment by rohandaxini** [comment]
Thanks @jenseng .... we did the exact same steps few hours back, went to `gems/canvas_i18nliner` and directly ran `npm install` there as `node_modules` folder was not getting created there for some or other reason. After debugging and checking console errors, we thought to run install directly in that `canvas_i18nliner` folder.

**Comment by rohandaxini** [comment]
@jenseng @claydiffrient I still face these issues while doing `rake canvas:compile_assets` and thus I don't have a clean installation. Any thoughts on how to resolved these errors ?


--> Pre-compiling ember handlebars templates finished in 7.051118
(libuv) Failed to create kqueue (24)it_api_controller.rb
(libuv) Failed to create kqueue (24)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EBADF
    at errnoException (net.js:904:11)
    at WriteStream.Socket._write (net.js:645:26)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at WriteStream.Writable.write (_stream_writable.js:182:11)
    at WriteStream.Socket.write (net.js:615:40)
    at printLine (/my-local-folder/canvas-lms/node_modules/coffee-script/lib/coffee-script/command.js:24:27)
    at /my-local-folder/canvas-lms/node_modules/coffee-script/lib/coffee-script/command.js:436:20
    at fs.js:955:21
    at Object.oncomplete (fs.js:107:15)
--> Compiling React JSX finished in 12.988607ontroller.rb.......
--> Pre-compiling handlebars templates finished in 18.521512
[warn]: @param tag has unknown parameter name: conversations 
    in file `app/controllers/quizzes/quiz_submission_users_controller.rb' near line 139



--> Finished: 'Compile sass and make jammit css bundles' in 86.74532
rake aborted!
Undumpable Exception -- #<RuntimeError: Unable to compile coffeescripts in /my-local-folder/canvas-lms/app/coffeescripts/bundles>
/.rvm/gems/ruby-2.0.0-p353/gems/parallel-0.5.16/lib/parallel.rb:173:in `work_in_processes'
/.rvm/gems/ruby-2.0.0-p353/gems/parallel-0.5.16/lib/parallel.rb:55:in `map'
/my-local-folder/canvas-lms/lib/tasks/canvas.rake:167:in `block (3 levels) in <top (required)>'
/my-local-folder/canvas-lms/lib/tasks/canvas.rake:166:in `block (2 levels) in <top (required)>'
/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
bash-3.2# rake canvas:compile_assets

**Comment by ccutrer** [comment]
You need to increase your open file limit (the EBADF error). `ulimit -n 4096` before calling compile_assets should be sufficient.

**Comment by rohandaxini** [comment]
Thanks @ccutrer this helped and fixed the issue :+1: 
Now I am able to run a clean canvas app on local.

**Comment by rohandaxini** [comment]
I am trying to do `rake canvas:compile_assets` for one of my canvas app and these are the errors I  am facing. Could please help me with inputs about what I may be doing wrong ? From the error it  seems few of the node modules are missing on my local while I did `npm install` which I did several times. The `npm install` installs modules gracefully and only after that I try to compile assets. 


Building client app 'canvas_quizzes'
	Running 'npm install'...
[warn]: Unknown tag @total_course_tags

> canvas-lms@0.0.0 compile-sass /Users/Rohan/RubyProjects/canvas-lms
> node script/compile-sass.js

npm WARN package.json canvas_quizzes@1.0.0 No repository field.
	Running 'npm run build'...
# writing file: app/views/info/styleguide.html.erb
--> Finished: 'css:styleguide' in 14.477386
Client app 'canvas_quizzes' was built successfully.
--> Pre-compiling handlebars templates--> Compiling React JSX
--> Creating ember app bundles
--> Pre-compiling ember handlebars templates--> Generating plugin extensions


--> Generating plugin extensions finished in 0.021158
--> Creating ember app bundles finished in 0.20727
--> Compiling CoffeeScript with 'coffee' binary
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/Rohan/RubyProjects/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/Rohan/RubyProjects/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
  Expected in: dynamic lookup

dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/Rohan/RubyProjects/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/Rohan/RubyProjects/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
  Expected in: dynamic lookup

dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/Rohan/RubyProjects/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/Rohan/RubyProjects/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
  Expected in: dynamic lookup

dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/Rohan/RubyProjects/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/Rohan/RubyProjects/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
  Expected in: dynamic lookup

dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/Rohan/RubyProjects/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/Rohan/RubyProjects/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
  Expected in: dynamic lookup

--> Compiling React JSX finished in 4.919026
(libuv) Failed to create kqueue (24)
(libuv) Failed to create kqueue (24)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EBADF
    at errnoException (net.js:904:11)
    at WriteStream.Socket._write (net.js:645:26)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at WriteStream.Writable.write (_stream_writable.js:182:11)
    at WriteStream.Socket.write (net.js:615:40)
    at printLine (/Users/Rohan/RubyProjects/canvas-lms/node_modules/coffee-script/lib/coffee-script/command.js:24:27)
    at /Users/Rohan/RubyProjects/canvas-lms/node_modules/coffee-script/lib/coffee-script/command.js:436:20
    at fs.js:955:21
    at Object.oncomplete (fs.js:107:15)
Files:          91
Modules:         0 (    0 undocumented)
Classes:        90 (   26 undocumented)
Constants:       0 (    0 undocumented)
Methods:       384 (    7 undocumented)
 93.04% documented
API Documentation successfully generated in public/doc/api
See public/doc/api/index.html
--> Finished: 'Generate documentation [yardoc]' in 64.85046
--> Finished: 'npm run compile-sass' in 76.592825
--> Starting: 'Jammit'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_high_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_high_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_normal_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_normal_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_high_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_high_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_normal_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_normal_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/pages/terms.css'
--> Finished: 'Jammit' in 1.35174
--> Finished: 'Compile sass and make jammit css bundles' in 77.945639
rake aborted!
Undumpable Exception -- #<EOFError: end of file reached>
/Users/Rohan/.rvm/gems/ruby-2.0.0-p353/gems/parallel-0.5.16/lib/parallel.rb:173:in `work_in_processes'
/Users/Rohan/.rvm/gems/ruby-2.0.0-p353/gems/parallel-0.5.16/lib/parallel.rb:55:in `map'
/Users/Rohan/RubyProjects/canvas-lms/lib/tasks/canvas.rake:167:in `block (3 levels) in <top (required)>'
/Users/Rohan/RubyProjects/canvas-lms/lib/tasks/canvas.rake:166:in `block (2 levels) in <top (required)>'
/Users/Rohan/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/Users/Rohan/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

**Comment by rohandaxini** [comment]
Ok I was able to resolve these module `/jsdom/node_modules/contextify/build/Release/contextify.node` issue by running npm install again in `gems/canvas_i18nliner`.

But now I face these errors / issues

(libuv) Failed to create kqueue (24)
(libuv) Failed to create kqueue (24)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EBADF
    at errnoException (net.js:904:11)
    at WriteStream.Socket._write (net.js:645:26)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at WriteStream.Writable.write (_stream_writable.js:182:11)
    at WriteStream.Socket.write (net.js:615:40)
    at printLine (/Users/Rohan/RubyProjects/canvas-lms/node_modules/coffee-script/lib/coffee-script/command.js:24:27)
    at /Users/Rohan/RubyProjects/canvas-lms/node_modules/coffee-script/lib/coffee-script/command.js:436:20
    at fs.js:955:21
    at Object.oncomplete (fs.js:107:15)
--> Pre-compiling handlebars templates finished in 15.523963
Files:          91
Modules:         0 (    0 undocumented)
Classes:        90 (   26 undocumented)
Constants:       0 (    0 undocumented)
Methods:       384 (    7 undocumented)
 93.04% documented
API Documentation successfully generated in public/doc/api
See public/doc/api/index.html
--> Finished: 'Generate documentation [yardoc]' in 72.889763
--> Finished: 'npm run compile-sass' in 82.236952
--> Starting: 'Jammit'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_high_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_high_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_normal_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_normal_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_high_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_high_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_normal_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_normal_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/pages/terms.css'
--> Finished: 'Jammit' in 1.980028
--> Finished: 'Compile sass and make jammit css bundles' in 84.217656
rake aborted!
Undumpable Exception -- #<RuntimeError: Unable to compile coffeescripts in /Users/Rohan/RubyProjects/canvas-lms/app/coffeescripts/bundles>
/Users/Rohan/.rvm/gems/ruby-2.0.0-p353/gems/parallel-0.5.16/lib/parallel.rb:173:in `work_in_processes'
/Users/Rohan/.rvm/gems/ruby-2.0.0-p353/gems/parallel-0.5.16/lib/parallel.rb:55:in `map'
/Users/Rohan/RubyProjects/canvas-lms/lib/tasks/canvas.rake:167:in `block (3 levels) in <top (required)>'
/Users/Rohan/RubyProjects/canvas-lms/lib/tasks/canvas.rake:166:in `block (2 levels) in <top (required)>'
/Users/Rohan/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/Users/Rohan/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

**Comment by rohandaxini** [comment]
Ok I was able to resolve these module /jsdom/node_modules/contextify/build/Release/contextify.node issue by doing following things

1) rm -r node_modules
2) npm install -g
3) npm install contextify
4) npm install again in folde `gems/canvas_i18nliner`

But now I am facing these errors.  Could you please help @jenseng @claydiffrient ?

(libuv) Failed to create kqueue (24)
(libuv) Failed to create kqueue (24)

events.js:72
throw er; // Unhandled 'error' event
^
Error: write EBADF
at errnoException (net.js:904:11)
at WriteStream.Socket._write (net.js:645:26)
at doWrite (_stream_writable.js:225:10)
at writeOrBuffer (_stream_writable.js:215:5)
at WriteStream.Writable.write (_stream_writable.js:182:11)
at WriteStream.Socket.write (net.js:615:40)
at printLine (/Users/Rohan/RubyProjects/canvas-lms/node_modules/coffee-script/lib/coffee-script/command.js:24:27)
at /Users/Rohan/RubyProjects/canvas-lms/node_modules/coffee-script/lib/coffee-script/command.js:436:20
at fs.js:955:21
at Object.oncomplete (fs.js:107:15)
--> Pre-compiling handlebars templates finished in 15.523963
Files: 91
Modules: 0 ( 0 undocumented)
Classes: 90 ( 26 undocumented)
Constants: 0 ( 0 undocumented)
Methods: 384 ( 7 undocumented)
93.04% documented
API Documentation successfully generated in public/doc/api
See public/doc/api/index.html
--> Finished: 'Generate documentation [yardoc]' in 72.889763
--> Finished: 'npm run compile-sass' in 82.236952
--> Starting: 'Jammit'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_high_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_high_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_normal_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_normal_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_high_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_high_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_normal_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_normal_contrast/pages/terms.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/pages/course_wizard/compiler-course_wizard.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/pages/terms.css'
--> Finished: 'Jammit' in 1.980028
--> Finished: 'Compile sass and make jammit css bundles' in 84.217656
rake aborted!
Undumpable Exception -- #
/Users/Rohan/.rvm/gems/ruby-2.0.0-p353/gems/parallel-0.5.16/lib/parallel.rb:173:in work_in_processes' /Users/Rohan/.rvm/gems/ruby-2.0.0-p353/gems/parallel-0.5.16/lib/parallel.rb:55:inmap'
/Users/Rohan/RubyProjects/canvas-lms/lib/tasks/canvas.rake:167:in block (3 levels) in <top (required)>' /Users/Rohan/RubyProjects/canvas-lms/lib/tasks/canvas.rake:166:inblock (2 levels) in '
/Users/Rohan/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in eval' /Users/Rohan/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in
'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

**Comment by simonista** [comment]
As @ccutrer mentioned above, you'll want to increase your ulimit (`ulimit -n 4096`) which should get you past that error.  You may want to set that in a startup script like `.bashrc` so that you don't have to set it every time you run the command.

**Comment by rohandaxini** [comment]
what a co-incidence @simonista  ... I was just sending u status for my above errors that I was able to resolve the issue by running `ulimit -n 8192`

Seems the issue was with maximum number of open file descriptors. Yes you are right. I would do so and set it in .bashrc. Sorry for the trouble. And thanks for your help @simonista @ccutrer You all rock :)
