### ISSUE TITLE
When adding a new student, validation fails in a bad way

### ISSUE THREAD

**Issue by krainboltgreene** [instructure/canvas-lms#613]
So I tried to add a student to my system, but because I didn't have the right permissions it wouldn't let me. Instead of saying "Hey, you're not powerful enough" it said "Hey, the email isn't a valid format."

As soon as someone with better permissions did it the student was added just fine.

**Comment by ccutrer** [comment]
Can you give more details about how you attempted to create the student? There are many ways to create users in Canvas.

**Comment by krainboltgreene** [comment]
I believe I went to the course, then students, then pressed the :heavy_plus_sign: Add Student button
