### ISSUE TITLE
Cannot import quiz from another course and cannot import exported quiz...

### ISSUE THREAD

**Issue by jfraboni** [instructure/canvas-lms#614]
When attempting to import quizzes from one course to another via "settings > import course content", the process finishes with no error messages, but all other course material is imported and available, except quizzes.

We've tried exporting quizzes, then importing, but we get errors saying the import is not the right format, even tho the quiz was exported from Canvas, so it's strange that it would not be in the right format, etc.

Anyway, seems like the import-quiz pipeline is just completely broken, and ideas here?  Sharing quizzes across courses for the same material is a must for us - rewriting the quizzes is an enormous waste of time.

Thanks!

**Comment by ryanmt** [comment]
Sorry to hear about your issues.  It is possible something isn't quite handled properly in the import/export pipeline.  If there's a particular quiz that's giving you problems, I bet we can see what we can do to support it.
