### ISSUE TITLE
Update Course - Account ID Required?

### ISSUE THREAD

**Issue by redconfetti** [instructure/canvas-lms#618]
I saw in your API documentation that the account ID is required.

https://canvas.instructure.com/doc/api/courses.html#method.courses.update

> - account_id
>
> Required, Integer
>
> The unique ID of the account to create to course under.

This looks like it was copied and pasted from the [#create documentation](https://canvas.instructure.com/doc/api/courses.html#method.courses.create).

An analysis of the code doesn't indicate that the Account ID is required for an #update API call.

https://github.com/instructure/canvas-lms/blob/218e8395/app/controllers/courses_controller.rb#L1799

**Comment by simonista** [comment]
Yup, I think you're right.  I'll push up a change to remove the required line.

**Comment by claydiffrient** [comment]
Closing since it appears to be resolved.
