### ISSUE TITLE
[Bug SIS:CSV] import of csv sometimes fails

### ISSUE THREAD

**Issue by mylo** [instructure/canvas-lms#619]
csv-import will brake due to splitting of input into chunks of 4kb (UTF-8 testing with iconv) if input data happens to be aligned so that a 16 bit encoded character is split in two. Most likely the same problem for 24 and 32 bits encoding of characters.

It relates to this code:
lib/sis/csv/import.rb: def process_file
```ruby
            Iconv.open('UTF-8', 'UTF-8') do |iconv|
              File.open(csv[:fullpath]) do |file|
                chunk = file.read(4096)
                while chunk
                  iconv.iconv(chunk)
                  chunk = file.read(4096)
                end
                iconv.iconv(nil)
              end
            end
```

a possible quickfix
```ruby
          chunk = ''
          chunk_lines = 0
          File.readlines(csv[:fullpath]).each do |line|
            chunk = chunk + line
            chunk_lines += 1
  
            if (chunk_lines >= 100)
              iconv.iconv(chunk)
              chunk = ''
              chunk_lines = 0
            end
          end
          iconv.iconv(nil)
```

**Comment by 3arrows** [comment]
This bug causes a annoying problem very often for Japanese and Chinese users.
It seems easy to fix, but Instructure spent almost 3 months and still can't fix it...

**Comment by claydiffrient** [comment]
@3arrows @mylo There was fix deployed to our master branch on June 24 (a291a5b560a2d05368cb0ae7490de534ef53cd3b). It should be deployed to stable and our Instructure-hosted Canvas instances this Saturday. I'm going to go ahead and close this issue.

**Comment by 3arrows** [comment]
@claydiffrient Thank you for your quick and thorough response!
