### ISSUE TITLE
[bug] @context_enrollment is not the same between two actions

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#622]
Hello there, 

I've found a bug - but maybe it's not one, you tell me. 

When you access courses show page, the action set @context_enrollment like this: 

``` ruby
@context_enrollment = @context.enrollments.where(user_id: @current_user).except(:includes).first
```

But in your before_filter require_context, you set it like this: 

``` ruby
@context.enrollments.where(user_id: @current_user).sort_by{|e| [e.state_sortable, e.rank_sortable, e.id] }.first if @context && @current_user
```

So! As there is no "sort" function in the show action, you sometimes do not get the same @context_enrollment when you visit this page. 

Isn't it odd? Why don't you use the before filter for this show action?

Thank for your answer :)
Regis.

**Comment by simonista** [comment]
Hey @Kulgar, great question.  Looks like it's been this way for a long time and an initial look at the code doesn't provide any great insight into why.  If I had to guess, I might venture to say that some of the extra work that `get_context` does wasn't wanted here, so it wasn't used.

Seems like at the very least, the code in courses_controller should include the sort, but longer term it would be nice if it could use `get_context`.  That'll probably require some testing and thinking through of the consequences that change.

**Comment by Kulgar** [comment]
I asked that because I had a user with many enrollments (just one but still) that had some strange issues because of that, something like he wasn't seeing things he should have on the course page... (like events or stuff like that, I don't remember well as it was some time ago ^^').
