### ISSUE TITLE
When assignment display is set to "Complete/Incomplete" CSV upload silently drops data

### ISSUE THREAD

**Issue by apoelstra** [instructure/canvas-lms#624]
If an assignment's grade display is set to "Complete/Incomplete", this appears to restrict the possible grades to 0% or 100%. This is a UI bug since "display" implies a purely cosmetic change.

More seriously, after doing this, if you upload a CSV grade file with grades differing from 0%/100%, it will appear to succeed but actually drop all the offending grades. This is a silent data loss bug.

**Comment by claydiffrient** [comment]
@apoelstra Sorry for the delay on this.  I have confirmed the issue with our gradebook team and it has been assigned a ticket in our internal ticketing system.  As progress is made, I'll keep you up to date.
