### ISSUE TITLE
LDAP Test Returns [object Object] - Can't Sign In

### ISSUE THREAD

**Issue by ridius** [instructure/canvas-lms#626]
Hello all,
When trying to setup LDAP for my Canvas instance (open source version), I'm getting weird results in the test. I have the server, port, Base DN, Filter, Login Attribute, and Bind user information all set correctly. I can use the same info in an interactive shell and get successful LDAP queries. But when I go to test the lookup, I get a weird ```[object Object]``` result and can't successfully login. I turned on Debug logging and went looking through ```production.log```, but can't find any reference to the LDAP errors. Here is a screenshot:
![ldap](https://cloud.githubusercontent.com/assets/1209402/7484000/e157c012-f338-11e4-8d6d-9748bf1057fb.PNG)

**Comment by rdev5** [comment]
Possibly related to this line that should be `$server_error.html()` instead of `$server_error` in:
````
$("#ldap_" + test.test_type + "_help").append($server_error)
````

https://github.com/instructure/canvas-lms/blob/1ce6f1ddfaf0d1cc9864309f2500f2ee194d50bb/public/javascripts/ldap_settings_test.js#L54

**Comment by ridius** [comment]
@rdev5 
Thanks for the suggestion. I made the change and restarted the app (I even restarted the server just to be sure) and it's still doing the same thing.

**Comment by ridius** [comment]
Ok, total PEBKAC error.

I forgot that the tooltips are BELOW the fields, not above them. Was putting the login mapping into the wrong field. It's up and working for me now.
