### ISSUE TITLE
Install Error: RAILS_ENV=production bundle exec rake db:initial_setup

### ISSUE THREAD

**Issue by TheDannyBoy** [instructure/canvas-lms#628]
Hi, I've been trying to install Canvas Production Start but when I execute this in the terminal I get this:
Ruby 2.0 support is untested
Ruby 2.0 support is untested
rake aborted!
LoadError: dlopen(/Library/Ruby/Gems/2.0.0/gems/syck-1.0.4/lib/syck.bundle, 9): Library not loaded: /usr/local/lib/libjemalloc.1.dylib
  Referenced from: /Library/Ruby/Gems/2.0.0/gems/syck-1.0.4/lib/syck.bundle
  Reason: image not found - /Library/Ruby/Gems/2.0.0/gems/syck-1.0.4/lib/syck.bundle
/Library/Ruby/Gems/2.0.0/gems/syck-1.0.4/lib/yaml/syck.rb:7:in `require'
/Library/Ruby/Gems/2.0.0/gems/syck-1.0.4/lib/yaml/syck.rb:7:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/syck-1.0.4/lib/syck.rb:9:in `require'
/Library/Ruby/Gems/2.0.0/gems/syck-1.0.4/lib/syck.rb:9:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:76:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:72:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:72:in `block in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:61:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:61:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.7.10/lib/bundler.rb:134:in `require'
/Users/Dany/canvas/config/application.rb:12:in `<top (required)>'
/Users/Dany/canvas/Rakefile:4:in `require'
/Users/Dany/canvas/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

I don't know if I must update or downgrade the ruby version.
My ruby version is: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
And I am using Mac OS X Yosemite v. 10.10.2

**Comment by jorgevbo** [comment]
Use ruby 1.9.3. Version 2+ is not supported

**Comment by TheDannyBoy** [comment]
Thank you, I'm gonna downgrade it.
