### ISSUE TITLE
Quiz Question Submission API problem

### ISSUE THREAD

**Issue by Drakengard** [instructure/canvas-lms#629]
I've been debugging the reason as to why my http request to submit quiz question answers has been failing for days. And I'm at a point where I don't know if its my fault, or if its because this functionality is still in beta phase. Right now the only problem stopping is that it says it can't convert a "Symbol" to an "Integer" in the "quiz_submission_controller.rb" on line 152. I don't know if its the way I'm constructing the json string for the answers or if its how I'm sending it, or if its a server side issue. Bottom line is I need help, because I'm at a major roadblock and don't have a clue as to what's causing it. I wouldn't be surprised if it was something minuscule or stupid.

PS. Here are some log snippets from my console application and canvas terminal.

![console_application_log](https://cloud.githubusercontent.com/assets/12396945/7568504/2fa2f902-f7d1-11e4-9ace-348b8883cb03.PNG)

![canvas_error](https://cloud.githubusercontent.com/assets/12396945/7568511/376b2e70-f7d1-11e4-927c-65e2b9a947a8.PNG)

**Comment by Drakengard** [comment]
I think it may be interpreting the quiz_questions hash and converting it to an array. And arrays expect an integer index, while its written to use a hash key as an index. I believe this is the issue and seeing how I can fix it in the meantime.

**Comment by simonista** [comment]
If you haven't already, you can go look at ErrorReport.find(77) (or /error_reports/77) to get more information about the error.

**Comment by simonista** [comment]
I'm going to close this since we haven't heard from you in 2 months.  Feel free to re-open if you can get back to us with more information about the error.
