### ISSUE TITLE
Jammit errors in bundle exec rake canvas:compile_assets 

### ISSUE THREAD

**Issue by jorgevbo** [instructure/canvas-lms#631]
I'm upgrading to release 2015-04-25 and I have Errno::EPERM: Operation not permitted when compile assets 

--> Starting: 'Jammit'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_high_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_normal_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_high_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_normal_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/bundles/facebook.css'
rake aborted!
Errno::EPERM: Operation not permitted - /var/canvas/public/assets/course_wizard_legacy_normal_contrast.css
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/jammit-98b50a67029c/lib/jammit/packager.rb:65:in `utime'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/jammit-98b50a67029c/lib/jammit/packager.rb:65:in `cache'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/jammit-98b50a67029c/lib/jammit/packager.rb:38:in `block in precache_all'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/jammit-98b50a67029c/lib/jammit/packager.rb:37:in `each'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/jammit-98b50a67029c/lib/jammit/packager.rb:37:in `precache_all'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/jammit-98b50a67029c/lib/jammit.rb:146:in `package!'
/var/canvas/lib/tasks/canvas.rake:131:in `block (4 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:7:in `log_time'
/var/canvas/lib/tasks/canvas.rake:129:in `block (3 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:168:in `call'
/var/canvas/lib/tasks/canvas.rake:168:in `block (5 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:7:in `log_time'
/var/canvas/lib/tasks/canvas.rake:168:in `block (4 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:275:in `call'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:275:in `call_with_index'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:225:in `process_incoming_jobs'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:203:in `block in worker'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:196:in `fork'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:196:in `worker'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:181:in `block in create_workers'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:180:in `each'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:180:in `create_workers'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:144:in `work_in_processes'
/var/canvas/vendor/bundle/ruby/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:55:in `map'
/var/canvas/lib/tasks/canvas.rake:167:in `block (3 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:166:in `block (2 levels) in <top (required)>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

**Comment by ccutrer** [comment]
You should check ownership of all files in your canvas directory. They should all be owned by the same user that you're running compile_assets as, which is preferably _not_ root.
