### ISSUE TITLE
Can't copy course or import content

### ISSUE THREAD

**Issue by maxgaudin** [instructure/canvas-lms#632]
When I try to copy an existing course it just says that the current job failed.

There doesn't seem to be anything relevant in production.log. This is what I have from delayed_job.log:

D locked_at IS NULL AND next_in_strand='t') AND ("delayed_jobs"."priority" BETWEEN 0 AND 1000000) ORDER BY priority ASC, run_at ASC LIMIT 5  [shard 1 master]
[- -]   SQL Delayed::Backend::ActiveRecord::Job Load (0.7ms)  SELECT "delayed_jobs".* FROM "delayed_jobs" WHERE "delayed_jobs"."queue" = 'canvas_queue' AND (run_at<='2015-05-13 21:23:24.954680' AND locked_at IS NULL AND next_in_strand='t') AND ("delayed_jobs"."priority" BETWEEN 0 AND 1000000) ORDER BY priority ASC, run_at ASC LIMIT 5  [shard 1 master]
[- -]   SQL Delayed::Backend::ActiveRecord::Job Load (0.7ms)  SELECT "delayed_jobs".* FROM "delayed_jobs" WHERE "delayed_jobs"."queue" = 'canvas_queue' AND (run_at<='2015-05-13 21:23:26.838392' AND locked_at IS NULL AND next_in_strand='t') AND ("delayed_jobs"."priority" BETWEEN 0 AND 10) ORDER BY priority ASC, run_at ASC LIMIT 5  [shard 1 master]
[- -]   SQL Delayed::Backend::ActiveRecord::Job Load (0.7ms)  SELECT "delayed_jobs".* FROM "delayed_jobs" WHERE "delayed_jobs"."queue" = 'canvas_queue' AND (run_at<='2015-05-13 21:23:26.926121' AND locked_at IS NULL AND next_in_strand='t') AND ("delayed_jobs"."priority" BETWEEN 0 AND 1000000) ORDER BY priority ASC, run_at ASC LIMIT 5  [shard 1 master]
[- -]   SQL Delayed::Backend::ActiveRecord::Job Load (0.6ms)  SELECT "delayed_jobs".* FROM "delayed_jobs" WHERE "delayed_jobs"."queue" = 'canvas_queue' AND (run_at<='2015-05-13 21:23:27.050942' AND locked_at IS NULL AND next_in_strand='t') AND ("delayed_jobs"."priority" BETWEEN 0 AND 1000000) ORDER BY priority ASC, run_at ASC LIMIT 5  [shard 1 master]
[- -]   SQL Delayed::Backend::ActiveRecord::Job Load (0.7ms)  SELECT "delayed_jobs".* FROM "delayed_jobs" WHERE "delayed_jobs"."queue" = 'canvas_queue' AND (run_at<='2015-05-13 21:23:27.263087' AND locked_at IS NULL AND next_in_strand='t') AND ("delayed_jobs"."priority" BETWEEN 0 AND 10) ORDER BY priority ASC, run_at ASC LIMIT 5  [shard 1 master]

Help?

**Comment by claydiffrient** [comment]
@maxgaudin I'm sorry to hear about this issue, and I'm sorry we haven't been more responsive.  I hope you've managed to figure out what's going on with it.  If you are still having issues, you might want to try out the mailing list: https://groups.google.com/forum/#!forum/canvas-lms-users
