### ISSUE TITLE
rake db:initial_setup failes with "NoMethodError: undefined method `config' for nil:NilClass"

### ISSUE THREAD

**Issue by karlwilbur** [instructure/canvas-lms#633]
I have followed the instructions for [Quick Setup](https://github.com/instructure/canvas-lms/wiki/Quick-Start) as well as [Production Setup](https://github.com/instructure/canvas-lms/wiki/Production-Start) but get to the point where I need to run `RAILS_ENV=production bundle exec rake db:initial_setup` it fails with the following error message ( `RAILS_ENV=production bundle exec rake db:migrate` fails with the same error, FWIW):
```
NoMethodError: undefined method `config' for nil:NilClass
/srv/app/shared/bundle/ruby/2.0.0/gems/switchman-1.2.33/lib/switchman/active_record/connection_handler.rb:61:in `establish_connection_with_sharding'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/abstract/connection_specification.rb:137:in `establish_connection'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/railtie.rb:88:in `block (2 levels) in <class:Railtie>'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/lazy_load_hooks.rb:25:in `each'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/railtie.rb:80:in `block in <class:Railtie>'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:30:in `instance_exec'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:30:in `run'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:55:in `block in run_initializers'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:54:in `each'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:54:in `run_initializers'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/application.rb:136:in `initialize!'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/railtie/configurable.rb:30:in `method_missing'
/srv/app/releases/20150529174930/config/environment.rb:11:in `<top (required)>'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:251:in `require'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:251:in `block in require'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:236:in `load_dependency'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:251:in `require'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/application.rb:103:in `require_environment!'
/srv/app/shared/bundle/ruby/2.0.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
Tasks: TOP => db:initial_setup => db:migrate => environment
(See full trace by running task with --trace)
```

From what I have seen, it appears that Switchman is trying to load the DefaultShard information from the database ...that doesn't exist yet. Thus it cannot get the config form the default Shard because `establish_connection_with_sharding` is Nil. This smells like a bug; some kind of logic failure, requiring a database read before we have even loaded the database schema.

What might I need to do to fix this? There is nothing in the setup process about sharding configuration.

Better yet, is there a way to just bypass sharding altogether?

**Comment by ccutrer** [comment]
Switchman is well-equipped to handle creation of new databases. The error on that line is that `Shard.default.database_server` is nil. If this is truly a fresh database, `Shard.default` will be a `DefaultShard` object (the failsafe implementation when the database doesn't exist or something is otherwise wrong with sharding). `DefaultShard#database_server` always returns `DatabaseServer.find(nil)`, which essentially returns `ActiveRecord::Base.configurations[Rails.env]`. If sharding is partially setup, it returns `DatabaseServer.find(database_server_id)`, where database_server_id is almost always nil. So, either you have a problem with your `database.yml`, or sharding was partially set up, and you have a problem with the data in the `switchman_shards` table.

**Comment by karlwilbur** [comment]
It is a completely new database and `Shard.default` is definitely a `DefaultShard`. I've even dropped and re-created the database just to be sure.

What could be wrong with my `database.yml`?

```
production:
  adapter: postgresql
  database: prod_database
  username: prod_db_user
  password: prod_db_pass
  host: prod_db_host
  port: 5432
  reaping_frequency: 60 
  pool: 5
  timeout: 5000
  encoding: utf8
```

**Comment by ccutrer** [comment]
Are you sure you're running under the production environment for rails? I'm unable to reproduce your error, though, even using a dummy environment name. Could you possibly debug into the `Switchman::DatabaseServer.find` call, and print out the contents of the `@database_servers` hash, and `::Rails.env` (using inspect so that we can tell if things are strings or symbols).

**Comment by simonista** [comment]
@karlwilbur, I'm going to close this due to lack of response, but this is still an issue, please feel free to re-open with more details.

**Comment by karlwilbur** [comment]
I ended up making significant changes to get the app running which included installing the Choices gem and completely rewriting the `database.yml ` file to parse `Rail.configuration.database_url` and use it to write out YML.

FWIW, I have encountered numerous issues that make me believe that it is impossible to have this app work as expected "out of the box" without significant modification.
