### ISSUE TITLE
[Translation bug] Daily/Weekly message notifications never translated

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#634]
Hello everyone, 

I don't think this has already been reported? But it seems to be a quite ancient bug. 
Notifications sent using app/messages/summaries.* don't seem to be translated (like: https://github.com/instructure/canvas-lms/blob/stable/app/messages/summaries.email.erb). For instance the "daily_body" is always in English no matter what locale we set in the application at any level (including the user's one). Strange thing is that the included notification summaries (such as discussion entry summary) are translated. 

Moreover I've looked in some locales file, if I was able to find the i18n keys for the summaries notification in en-GB or generated en.yml, I wasn't able to find them in fr.yml or de.yml. In fr.yml those keys just disappeared between https://github.com/instructure/canvas-lms/blob/f95cd7bd822dae87205c83e47f17622a47cf05c6/config/locales/fr.yml and https://github.com/instructure/canvas-lms/blob/fdd4a42a26bc6657d38be971515e3174863619f0/config/locales/fr.yml

It is quite a big issue I think as those daily/weekly notifications are important in the Canvas LMS application.

Thanks if you can do anything to solve this :)
Regis

**Comment by claydiffrient** [comment]
@Kulgar Thanks for sending us the bug report.  I'm sending this over to @mcwqy9 on our communications team.  I'll see if we can get this taken care of for you.

**Comment by claydiffrient** [comment]
@Kulgar This report has made it into our internal ticketing system.  As it gets worked I'll keep you up to date.

**Comment by Kulgar** [comment]
@claydiffrient : Great, thanks! :)

**Comment by claydiffrient** [comment]
@Kulgar I believe that this was fixed in 0eda147

**Comment by Kulgar** [comment]
@claydiffrient : Yeah, it seems so, thanks! I did not update my app yet, so if I keep having this problem I'll let you know.
