### ISSUE TITLE
Quick start script fails (Ubunt 14.04.2 - Desktop)

### ISSUE THREAD

**Issue by Thoughtfulmonkey** [instructure/canvas-lms#635]
The quick start script repeatedly loads current version of bundler (1.10.3) and then fails because the version is not supported (_before.rb seems to be limited to between 1.7.10 and 1.9.6).

Script:
https://raw.githubusercontent.com/FreedomBen/canvas-development-tools/master/CODES.sh

Referenced on page:
https://github.com/instructure/canvas-lms/wiki/Quick-Start

**Comment by claydiffrient** [comment]
Hey @Thoughtfulmonkey I'm sorry for your troubles.  That script is supported independently by @FreedomBen.  I'll make sure he hears about it, but in the future filing an issue at  https://github.com/FreedomBen/canvas-development-tools/issues might be a better option.

**Comment by FreedomBen** [comment]
Thanks @Thoughtfulmonkey and @claydiffrient , I'll take a look at it

**Comment by FreedomBen** [comment]
@Thoughtfulmonkey: I just pushed https://github.com/FreedomBen/canvas-development-tools/commit/e8f537b1e36287b1d8a239f20a723adcf11a2fe6 .  Please let me know if you're still having a problem

**Comment by Thoughtfulmonkey** [comment]
Thanks @FreedomBen.  That particular issue is now resolved.  There is another small issue, but I'll raise it in the appropriate place.
