### ISSUE TITLE
google document preview no file downloaded in speed grader

### ISSUE THREAD

**Issue by shawniverson** [instructure/canvas-lms#636]
Not sure if this is an old issue or new issue...

Error_Report, first line:

No route matches [GET] "/assignments/6/files/26/download" | /srv/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-b344986bc3d9/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'

Had to add this to routes.rb inside outer block to work around:

get "assignments/:assignment_id/files/:id/download" => 'files#show', download: '1'

**Comment by simonista** [comment]
@shawniverson, can you comment back with reproduction steps for how you generated this error please?

**Comment by shawniverson** [comment]
1)  Install Canvas Stable using Production Start from wiki
2)  Enable Google Drive/Docs plugins only
3)  Create a course, teacher, student, and assignment
4)  Upload a document with student 
5)  Access speed grader with teacher
6)  Preview of document fails with above error report

**Comment by shawniverson** [comment]
Additional info on this issue.  

In routes.rb, there is a note about assignments w/o a context:
# assignments at the top level (without a context) -- we have some specs that
# assert these routes exist, but just 404. I'm not sure we ever actually want
# top-level assignments available, maybe we should change the specs instead.
resources :assignments, only: [:index, :show] 

So, I'm looking for the spec that asserts this route in the SpeedGrader

**Comment by shawniverson** [comment]
Doesn't appear to be a spec, but is definitely an issue specific to local storage

**Comment by shawniverson** [comment]
The URL is constructed here when local storage is used

```
def local_storage_path
    "#{HostUrl.context_host(context)}/#{context_type.underscore.pluralize}/#{context_id}/files/#{id}/download?verifier=#{uuid}"
```

Where context_type is an assignment in this case.
