### ISSUE TITLE
Canvadocs preview fails on first hit

### ISSUE THREAD

**Issue by shawniverson** [instructure/canvas-lms#638]
while(1);{"errors":[{"message":"An error occurred.","error_code":"internal_server_error"}],"error_report_id":596}
#596: A JSON text must at least contain two octets!

account: My Site
category: JSON::ParserError
created at: 2015-06-14 08:56:56 -0600
user: myadmin@mydomain
request context id: fdbc1567-0e03-4220-863c-628f59e06353 
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8 
HTTP_ACCEPT_ENCODING: gzip, deflate, sdch 
HTTP_HOST: mycanvas.mydomain
HTTP_REFERER: https://mycanvas.mydomain/courses/11/files/?preview=85 
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36 
PATH_INFO: /api/v1/canvadoc_session 
QUERY_STRING: ?blob=%7B%22user_id%22:10000000000001,%22attachment_id%22:85,%22type%22:%22canvadoc%22%7D&hmac=6833b934978e10b50e0ea3509e1aed619b6f3627 
REMOTE_ADDR:  myip
REQUEST_METHOD: GET 
REQUEST_URI: https://mycanvas.mydomain/api/v1/canvadoc_session?blob=%7B%22user_id%22:10000000000001,%22attachment_id%22:85,%22type%22:%22canvadoc%22%7D&hmac=6833b934978e10b50e0ea3509e1aed619b6f3627 
SERVER_NAME: mycanvas.mydomain
SERVER_PORT: 443 
SERVER_PROTOCOL: HTTP/1.1 
format: application/json 
hostname: canvas1 
path_parameters: {:controller=>"canvadoc_sessions", :action=>"show", :format=>"json"} 
pid: 11921 
query_parameters: {"blob"=>"{\"user_id\":10000000000001,\"attachment_id\":85,\"type\":\"canvadoc\"}", "hmac"=>"6833b934978e10b50e0ea3509e1aed619b6f3627"} 
request_parameters: {} 

Refresh the page and it works on subsequent hits

to reproduce:

(Using Production Start and current canvas stable build with local storage with canvadocs plugin)

1) Upload documents (such as docx) to Files repository in a course
2a) Try to preview document.  In Files view it is blank on first hit
2b) If linked to a module, the above similar message appears

Wondering if there is a bit of a timing issue in Canvadocs plugin.

**Comment by claydiffrient** [comment]
@shawniverson Thanks for this bug report.  We'll look into this and see what's going on.

**Comment by shawniverson** [comment]
In lib/canvadocs.rb, I placed a while loop around this in this session method as a workaround for now.  Turns out that the raw_body is coming back empty prior to JSON parsing on the first try.

   begin
        raw_body = api_call(:post, "sessions",
          opts.merge(:document_id => document_id))
      end while raw_body.to_s.strip.length == 0

**Comment by cmatheson** [comment]
@shawniverson, you are right that the document may not be ready by the time the first viewing session has been made (We don't have this particular issue at Instructure because of a proxying service we use to talk to Box View).  Your fix will certainly work, but if you are interested, it might be better to handle the HTTP 202 response directly in `api_call` so you can respect the `Retry-After` header documented here: https://developers.box.com/view/#post-sessions
