### ISSUE TITLE
missing Media Comment Tool icon in TinyMCE

### ISSUE THREAD

**Issue by frinux** [instructure/canvas-lms#641]
The documentation speaks about a way to upload videos using the Media Comment Tool. It seems an icon showing a video should be available in the TinyMCE icons. I just installed a fresh version of Canvas and this icon is missing when I edit a new page:

![capture d ecran 2015-06-16 a 16 08 09](https://cloud.githubusercontent.com/assets/636404/8185013/ede1c2cc-1441-11e5-9668-f53141578e14.png)

Is there a configuration to do or is it a bug?

Thanks

**Comment by remedy9** [comment]
frinux,

Please see the following documentation regarding the configuration needed for the inquired functionality to be available within our TinyMCE implementation.

https://github.com/instructure/canvas-lms/wiki/Canvas-Integration (Kaltura)

https://github.com/instructure/canvas-lms/wiki/Kaltura-setup-instructions

Best,

August

**Comment by frinux** [comment]
Thanks remedy9.

I was looking at this feature to be able to host and embed videos directly from the CanvasLMS server. Is there a way to do it without depending on another server (or a SaaS)?

**Comment by claydiffrient** [comment]
@frinux Thanks for filing this issue.  I think you might be better served by asking this question on our mailing list at https://groups.google.com/forum/#!forum/canvas-lms-users.  We have a pretty active community of people there that are hosting Canvas on their own and might have some insight into how they have done it in the past.

**Comment by frinux** [comment]
OK thanks it's more appropriate on the mailing list.
The subject has been posted here: https://groups.google.com/forum/#!topic/canvas-lms-users/7Y7cFdM0r_c
