### ISSUE TITLE
Canvadocs support for xlsx

### ISSUE THREAD

**Issue by shawniverson** [instructure/canvas-lms#642]
Appears that canvadocs supports xlsx

application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

add to app/models/canvadoc.rb?

**Comment by claydiffrient** [comment]
@shawniverson Thanks for filing the issue, I'm reaching out to an engineer more familiar to Canvadocs to confirm this.  

Also, just so you know we're happy to take a look at pull requests that come our way for code changes.  Just take a look https://github.com/instructure/canvas-lms/wiki/Coding-Guidelines and have at it :)

**Comment by cmatheson** [comment]
@shawniverson thanks, we should add that to the list.  In the mean-time, you can always add more content-types yourself by adjusting the "canvadoc_mime_types" `Setting` in the rails console

**Comment by simonista** [comment]
Hey @shawniverson, thanks for the suggestion, I've pushed up a commit to our internal review system that adds this mime type, I'll let you know when it's merged.
