### ISSUE TITLE
SASS step of rake canvas:compile-assets never completes

### ISSUE THREAD

**Issue by qrntz** [instructure/canvas-lms#649]
Hello,

«node script/compile-sass.js», a part of the assets compiling process, never seems to terminate.

[strace output (SIGINT is from me sending ^C)](https://gist.github.com/qrntz/0bc30666e50f2ec05cc9)

**Comment by simonista** [comment]
Hey @qrntz, I'm not sure what would be causing that, unfortunately.  We try to reserver github issues for reporting bugs and defects in end-user functionality, but you might have some luck trying to ask on our mailing list: https://groups.google.com/forum/#!forum/canvas-lms-users. Sorry to not be more help.
