### ISSUE TITLE
Docs: Querying Course for Multiple Enrollment Types

### ISSUE THREAD

**Issue by cycomachead** [instructure/canvas-lms#653]
The current docs suggest that an API call can only request a single enrollment type at a time:

https://github.com/instructure/canvas-lms/blob/stable/app/controllers/courses_controller.rb#L290

However, in my current course the following command works:

`https://bcourses.berkeley.edu/api/v1/courses/1348652/users/?enrollment_type[]=teacher&enrollment_type[]=ta` -- and correctly returns the users in both types. 

Is this expected? (and thus a doc error) or is it something I can't rely on?

If it's the latter, then I'll turn this into a feature request because it's really handy to be able to build a query across multiple types, especially for something like "any user who can edit grades in this course".

**Comment by jeffw16** [comment]
FWIW, this is what happens on my course page (https://canvas.mckinneyisd.net/api/v1/courses/831/users/?enrollment_type[]=teacher):
```
while(1);{"status":"unauthorized","errors":[{"message":"user not authorized to perform that action"}]}
```

**Comment by simonista** [comment]
@jeffw16 that's a different issue than @cycomachead is reporting.  sounds like you're hitting pagination limits.  Check out how that works here: https://canvas.instructure.com/doc/api/file.pagination.html

**Comment by cycomachead** [comment]
@simonista Thanks for the fix! :+1:
