### ISSUE TITLE
passenger-common1.9.1 is no longer available

### ISSUE THREAD

**Issue by jhoerr** [instructure/canvas-lms#658]
The Production Start guide includes a [step](https://github.com/instructure/canvas-lms/wiki/Production-Start#installation) that installs `passenger-common1.9.1`. As of 7/8/15 this package is not available from either the `ruby-ng` or `ruby-ng-experimental` package repositories.

**Comment by fvazquez0506** [comment]
I was having the same issue with a Ubuntu 14.04 installation:
```
E: Unable to locate package passenger-common1.9.1
E: Couldn't find any package by regex 'passenger-common1.9.1'
```
I had to add a new key, get a couple of packages and then add a new repo source, after which i could install passenger, but not by calling it `passenger-common1.9.1`, instead i needed to use `passenger`

Here are the steps I followed:
```
~$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
~$ sudo apt-get install -y apt-transport-https ca-certificates
~$ sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main > /etc/apt/sources.list.d/passenger.list'
~$ sudo apt-get update
~$ sudo apt-get install -y passenger libapache2-mod-passenger
```

**Comment by jhoerr** [comment]
That's a good workaround. Thank you!

**Comment by FreedomBen** [comment]
The production start guide has been updated.  Thanks!
