### ISSUE TITLE
Not able to get Postgres SQL script

### ISSUE THREAD

**Issue by padmanabhantr** [instructure/canvas-lms#659]
Hi, 

Could you please provide canvas database SQL script.We can able to see only ro files in database folder.

**Comment by simonista** [comment]
Hey @padmanabhantr,

I'm not sure exactly what you are looking for.  Canvas uses the concept of database migrations (specifically, the flavor used in Ruby on Rails applications, you can read more here: http://edgeguides.rubyonrails.org/active_record_migrations.html). Which represent point-in-time iterations in the database schema.

From a canvas checkout, you can run `bundle exec rake db:initial_setup` which will run those migration files and populate the database with a schema and some initial data. (as described here: https://github.com/instructure/canvas-lms/wiki/Quick-Start#database-population).  If you just wanted an empty schema, you could run `bundle exec rake db:migrate`.

Also, for questions like this (not representing specific defects in the canvas application code), our mailing list is a better place to ask: https://groups.google.com/forum/#!forum/canvas-lms-users

Hope that helps!
Simon
