### ISSUE TITLE
Problems working with a subdirectory URL

### ISSUE THREAD

**Issue by Ferkaz** [instructure/canvas-lms#660]
Hi!

I am trying to set my canvas installation work on domain.com/canvas but I can't make it work 100%. As the Passenger documentation says (https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#deploying_rails_to_sub_uri) I wrote these lines on my apache configuration files:

```
<Directory "canvas_ins_dir/public">
Options -MultiViews
AllowOverride None
<IfVersion < 2.3 >
Order allow,deny
Allow from all
</IfVersion>
<IfVersion >= 2.3>
Require all granted
</IfVersion>
PassengerEnabled on
SetEnv RAILS_RELATIVE_URL_ROOT "/canvas"
</Directory>

Alias /canvas "canvas_ins_dir/public"

<Location /canvas>
PassengerBaseURI "/canvas"
PassengerAppRoot "canvas_ins_dir/"
</Location>
```

I make it to the log in screen and I can log in but some images and some links aren't ok because they don't include the subdir (for instance the Inbox link is domain.com/conversations? instead of domain.com/canvas/converstations? ). So it is working but with bad redirecting.

I checked a thousand of things, as changing the config/domain.yml file adding the subdir or changing some ruby files but I am not able to fix this issue.

Could someone help me?

Thank you!

**Comment by ccutrer** [comment]
Canvas does not support running under a sub-URI.
