### ISSUE TITLE
Unable to 'bundle install'

### ISSUE THREAD

**Issue by amulgarg** [instructure/canvas-lms#661]
I'm setting up canvas-lms on my machine using the instructions I found at - https://github.com/instructure/canvas-lms/wiki/Production-Start

After setting up bundler version 1.7.11, I run the command -  
```
bundle install --path vendor/bundle --without=sqlite mysql 
```
and get this error

```
Your Ruby version is 1.9.3, but your Gemfile specified 2.1.6"
```
How do I resolve this and proceed?

**Comment by ccutrer** [comment]
I'm sorry, but it looks like the production start tutorial has not been update. Canvas now requires Ruby 2.1. You should follow the dependencies on the quick start at https://github.com/instructure/canvas-lms/wiki/Quick-Start#dependency-installation before going back to the production start.
