### ISSUE TITLE
LMS Setup : Could not find module handlebars

### ISSUE THREAD

**Issue by amulgarg** [instructure/canvas-lms#662]
I was able to setup canvas-lms on my machine till the point where you compile assets

But while compiling assets using 
```
bundle exec rake canvas:compile_assets
```
I get the error
```
Could not find module handlebars
```

Somehow I moved ahead using 
```
npm install --save handlebars
```
But got stuck with a similar error - 
```
Cannot find module 'ember-template-compiler'
```
How to solve this?

**Comment by simonista** [comment]
Hey @amulgarg, sorry this isn't working for you.  I'm guessing here, but I think what probably happened is that when you ran `npm install` it failed, and so then you got a message about something missing from the install, and then when you ran `npm install --save handlebars` it ONLY installed handlebars (not everything that is needed).  I'd try `npm install` again and see if you can spot an error happening.

By the way, this kind of question fits better on our mailing list: https://groups.google.com/forum/#!forum/canvas-lms-users.  We try to reserve github issues for end user bugs and functionality issues in the app itself.

Good luck!

**Comment by ryankshaw** [comment]
when in doubt with npm modules always do:
`rm -rf node_modules && npm cache clear && npm install`

**Comment by amulgarg** [comment]
Hi @simonista and @ryankshaw - I was able to move forward after using the statements -
```
cd gems/canvas_i18nliner
rm -rf node_modules
npm install
```
I found this solution in another of the issues raised on this page.
@simonista - Thanks for letting me know about the mailing list! Will post such queries there in the future!
