### ISSUE TITLE
 Canvas production mode redirecting to UsersController#api_show after initial login

### ISSUE THREAD

**Issue by chrisjoywebb** [instructure/canvas-lms#663]
Hey,

I've successfully set up Canvas in production mode locally, but after signing in and accepting the Terms of Use, I'm redirected to this url:

```
http://localhost:3000/api/v1/users/self?user%5Bterms_of_use%5D=1
```

which just shows the JSON API output of the admin account that I set up during installation:

```
while(1);{"id":1,"name":"chris@epicodus.com","sortable_name":"chris@epicodus.com","short_name":"chris@epicodus.com","login_id":"chris@epicodus.com","locale":null,"permissions":{"can_update_name":true,"can_update_avatar":false}}
```

Is this normal for the production build?

Thanks!
Chris

**Comment by simonista** [comment]
Hey @chrisjoywebb, glad you got things running successfully.  No, that is not normal, it's a bug that happens occasionally for reasons that aren't entirely clear to us.  There's a config workaround you can use here: https://groups.google.com/forum/#!topic/canvas-lms-users/olLiBu3jQEE, or there's a code workaround that will hit the stable branch on August 8th (a96b40c5bd2447878c2ccb9d5953586300377727) that you could cherry-pick

**Comment by chrisjoywebb** [comment]
Thanks @simonista! August 8th isn't far away so we may just wait for that.
