### ISSUE TITLE
Site doesn't support smaller screen sizes

### ISSUE THREAD

**Issue by 10by10pixel** [instructure/canvas-lms#664]
I noticed some issues while on a small screen. It appears the site needs to be a little more responsive. According to the phone emulator there also is no mobile site and I feel that mobile is a very important platform especially for schools.

**Comment by jeffw16** [comment]
@10by10pixel , there is an app for Canvas at least for iOS.

**Comment by 10by10pixel** [comment]
@jeffw16 That really only helps iOS (and also Android) users. The problem is there are still screens at that size that aren't running either of those OS's. Google the phrase "Windows Phone" and you'll find a whole bunch of phones independent of those two OS's. If you think that's an isolated case try just googling "Mobile phone operating systems" you'd really be surprised by how many are out there.

**Comment by jeffw16** [comment]
@10by10pixel 

Take a look at the market share for iOS and Android:
https://www.netmarketshare.com/

92.63% of mobile OSes are either iOS or Android, both of which are supported.

![screen shot 2015-08-07 at 9 27 44 am](https://cloud.githubusercontent.com/assets/11380894/9137939/9e967d20-3ce6-11e5-9aa8-022509f2a03a.png)

I do not think Instructure thinks of WP or other OSes as an issue and they are concentrating on the development of those apps only.

I believe there are two factors behind Instructure not developing a mobile version of the website. One, the company has limited resources and their own development plans, probably not including yet another mobile website. Two, schools prefer their students to use larger screens to do coursework on Canvas. My ISD uses Canvas and gave us MacBook Airs. I highly doubt schools want their students to use their mobile devices to view assignments, download PDF and Word files, submit text, etc.

However, I am not exactly clear what Instructure's policy for 3rd party freelancers volunteering work. In addition, I'm not sure what underlying frameworks Canvas uses. If the software used, say, Twitter Bootstrap, then responsive design could be made easier.

By the way, on my iPhone 6 Plus, when I visit Canvas the desktop version displays with minimal issues in zooming in.

**Comment by claydiffrient** [comment]
@10by10pixel @jeffw16 Thanks for the conversation about this.  Just to let you know we do care about how well our web application renders on mobile devices.  If you enable the 'Use New Styles' feature flag in your instance you will get a much more responsive experience.  Eventually this new UI will roll out to all users as the default UI. The new UI has been designed from a mobile first perspective.  We support as low as 768px screen width which is the resolution for a portrait oriented iPad.

So enjoy the new UI and all the responsiveness that it brings.  I'm going to go ahead and close this issue, but thanks for bringing it up.
