### ISSUE TITLE
brandable_css 

### ISSUE THREAD

**Issue by AndranikMarkosyan** [instructure/canvas-lms#668]
Blank screen after initial install July version Canvas install. Found this error in the log 
```'/var/canvas/public/dist/brandable_css/brandable_css_bundles_with_deps.jsoncompressed does not exist. You need to run ./node_modules/.bin/brandable_css before you can serve css.```
However when running ```/node_modules/.bin/brandable_css``` does not create "brandable_css_bundles_with_deps.jsoncompressed" file

**Comment by Ferkaz** [comment]
I am having the same issue when I run the ```bundle exec rake canvas:compile_assets``` command. I didn't get that error on the previous July version.

On this post https://github.com/instructure/canvas-lms/issues/666 an user solved it upgrading his memory, but that doesn't seem to be my problem.

Can anyone help us?

**Comment by chrisjoywebb** [comment]
See [this](https://github.com/instructure/canvas-lms/issues/666) issue. You need to be running on a server with minimum 2GB or RAM.

**Comment by Ferkaz** [comment]
I am running a server with more than 2GB of RAM and still fails. Couldn't it be another issue since more than one user are having it, and it happened just after the new release?

Thanks

**Comment by chrisjoywebb** [comment]
Very possible. I'll leave that up to the core Canvas team to sort out. I was able to successfully get around this issue yesterday by using a clean EC2 Ubuntu 14.04 instance with 2GB of RAM.

**Comment by ccutrer** [comment]
BrandableCSS is a new thing with this release, which is why you have not seen it previously. What happens when you run `./node_modules/.bin/brandable_css` directly?

**Comment by AndranikMarkosyan** [comment]
when I run ./node_modules/.bin/brandable_css it generates a lot files however brandable_css_bundles_with_deps.jsoncompressed does not exist still does not exist!

here is  ./node_modules/.bin/brandable_css  output

compiled bundles/attendance.scss new_styles_normal_contrast  in 1220 ms
compiled bundles/all_courses.scss new_styles_normal_contrast  in 1253 ms
canvas_css warning app/stylesheets/bundles/canvas_quizzes.scss has an external url() to: #default#VML that's not a problem but normally our css only links to files in our repo
compiled bundles/alerts.scss new_styles_normal_contrast  in 2769 ms
compiled bundles/account_admin_tools.scss new_styles_normal_contrast  in 2772 ms
compiled bundles/assignments_edit.scss new_styles_normal_contrast  in 2767 ms
compiled bundles/assignments.scss new_styles_normal_contrast  in 2768 ms
compiled bundles/content_next.scss new_styles_normal_contrast  in 2725 ms
compiled bundles/agenda_view.scss new_styles_normal_contrast  in 2771 ms
compiled bundles/canvas_quizzes.scss new_styles_normal_contrast  in 2765 ms
compiled bundles/account_settings.scss new_styles_normal_contrast  in 4547 ms
compiled bundles/calendar2.scss new_styles_normal_contrast  in 4545 ms
compiled bundles/conferences.scss new_styles_normal_contrast  in 4547 ms
compiled bundles/content_migrations.scss new_styles_normal_contrast  in 4555 ms
compiled bundles/context_list.scss new_styles_normal_contrast  in 4518 ms
compiled bundles/course_show.scss new_styles_normal_contrast  in 4518 ms
compiled bundles/context_modules.scss new_styles_normal_contrast  in 4519 ms
compiled bundles/context_module_progressions.scss new_styles_normal_contrast  in 4519 ms
compiled bundles/context_modules2.scss new_styles_normal_contrast  in 4519 ms
compiled bundles/datagrid.scss new_styles_normal_contrast  in 4485 ms
compiled bundles/course_list.scss new_styles_normal_contrast  in 4521 ms
compiled bundles/course_wizard.scss new_styles_normal_contrast  in 4520 ms
compiled bundles/dashboard_card.scss new_styles_normal_contrast  in 4490 ms
compiled bundles/dashboard.scss new_styles_normal_contrast  in 4521 ms
compiled bundles/external_tool_full_width.scss new_styles_normal_contrast  in 4450 ms
compiled bundles/conversations_new.scss new_styles_normal_contrast  in 4525 ms
compiled bundles/developer_keys.scss new_styles_normal_contrast  in 4454 ms
compiled bundles/course_settings.scss new_styles_normal_contrast  in 5649 ms
compiled bundles/discussions.scss new_styles_normal_contrast  in 5610 ms
compiled bundles/edit_calendar_event_full.scss new_styles_normal_contrast  in 5610 ms
compiled bundles/discussions_list.scss new_styles_normal_contrast  in 5610 ms
compiled bundles/grade_summary.scss new_styles_normal_contrast  in 5609 ms
compiled bundles/gradebook2.scss new_styles_normal_contrast  in 5611 ms
compiled bundles/gradebook_history.scss new_styles_normal_contrast  in 5611 ms
compiled bundles/gradebook_uploads.scss new_styles_normal_contrast  in 5575 ms
compiled bundles/grading_periods.scss new_styles_normal_contrast  in 5574 ms
compiled bundles/grading_standards.scss new_styles_normal_contrast  in 5574 ms
compiled bundles/imports.scss new_styles_normal_contrast  in 5574 ms
compiled bundles/moderate_quiz.scss new_styles_normal_contrast  in 5572 ms
compiled bundles/instructure_eportfolio.scss new_styles_normal_contrast  in 5574 ms
compiled bundles/learning_outcomes.scss new_styles_normal_contrast  in 5577 ms
compiled bundles/locale.scss new_styles_normal_contrast  in 5581 ms
compiled bundles/login.scss new_styles_normal_contrast  in 5582 ms
compiled bundles/page_views.scss new_styles_normal_contrast  in 5554 ms
compiled bundles/prior_users.scss new_styles_normal_contrast  in 5554 ms
compiled bundles/messages.scss new_styles_normal_contrast  in 5582 ms
compiled bundles/modules_next.scss new_styles_normal_contrast  in 5557 ms
canvas_css warning app/stylesheets/bundles/smartbanner.scss new_styles_normal_contrast contains a url() to: dark_background_stripes.gif which doesn't exist on disk
compiled bundles/new_assignments.scss new_styles_normal_contrast  in 7276 ms
compiled bundles/mobile_auth.scss new_styles_normal_contrast  in 7304 ms
compiled bundles/notification_preferences.scss new_styles_normal_contrast  in 7280 ms
compiled bundles/otp_login.scss new_styles_normal_contrast  in 7279 ms
compiled bundles/profile_edit.scss new_styles_normal_contrast  in 7281 ms
compiled bundles/registration.scss new_styles_normal_contrast  in 7284 ms
compiled bundles/profile_show.scss new_styles_normal_contrast  in 7289 ms
compiled bundles/saml_fields.scss new_styles_normal_contrast  in 7252 ms
compiled bundles/reports.scss new_styles_normal_contrast  in 7253 ms
compiled bundles/react_files.scss new_styles_normal_contrast  in 7289 ms
compiled bundles/slickgrid.scss new_styles_normal_contrast  in 7254 ms
compiled bundles/smartbanner.scss new_styles_normal_contrast  in 7255 ms
compiled bundles/quizzes.scss new_styles_normal_contrast  in 7294 ms
compiled bundles/statistics.scss new_styles_normal_contrast  in 7253 ms
canvas_css warning app/stylesheets/bundles/common.scss new_styles_normal_contrast contains a url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
canvas_css warning app/stylesheets/bundles/common.scss has an external url() to:  that's not a problem but normally our css only links to files in our repo
canvas_css warning app/stylesheets/bundles/common.scss new_styles_normal_contrast contains a url() to: /images/mediaelement/skipback.png which doesn't exist on disk
compiled bundles/quizzes_ember.scss new_styles_normal_contrast  in 8617 ms
compiled bundles/roster.scss new_styles_normal_contrast  in 8580 ms
compiled bundles/roster_user.scss new_styles_normal_contrast  in 8580 ms
compiled bundles/terms.scss new_styles_normal_contrast  in 8544 ms
compiled bundles/select_content_dialog.scss new_styles_normal_contrast  in 8580 ms
compiled bundles/screenreader_gradebook.scss new_styles_normal_contrast  in 8581 ms
compiled bundles/styleguide.scss new_styles_normal_contrast  in 8578 ms
compiled bundles/user_logins.scss new_styles_normal_contrast  in 8542 ms
compiled bundles/speed_grader.scss new_styles_normal_contrast  in 8579 ms
compiled bundles/sub_accounts.scss new_styles_normal_contrast  in 8545 ms
compiled bundles/theme_preview.scss new_styles_normal_contrast  in 8544 ms
compiled bundles/wiki_page.scss new_styles_normal_contrast  in 8518 ms
compiled jst/AssignmentGroupWeightsDialog.scss new_styles_normal_contrast  in 8518 ms
compiled jst/AssignmentDetailsDialog.scss new_styles_normal_contrast  in 8518 ms
compiled bundles/theme_editor.scss new_styles_normal_contrast  in 8545 ms
compiled bundles/user_grades.scss new_styles_normal_contrast  in 8543 ms
compiled jst/PaginatedView.scss new_styles_normal_contrast  in 8517 ms
compiled jst/SubmissionDetailsDialog.scss new_styles_normal_contrast  in 8517 ms
compiled bundles/tinymce.scss new_styles_normal_contrast  in 8546 ms
compiled bundles/user_notes.scss new_styles_normal_contrast  in 8544 ms
compiled jst/announcements/IndexView.scss new_styles_normal_contrast  in 8508 ms
compiled bundles/common.scss new_styles_normal_contrast  in 8803 ms
compiled jst/DiscussionTopics/IndexView.scss new_styles_normal_contrast  in 8520 ms
compiled jst/FindFlickrImageView.scss new_styles_normal_contrast  in 8520 ms
compiled jst/editor/KeyboardShortcuts.scss new_styles_normal_contrast  in 8508 ms
compiled bundles/what_gets_loaded_inside_the_tinymce_editor.scss new_styles_normal_contrast  in 8545 ms
compiled jst/groups/manage/addUnassignedMenu.scss new_styles_normal_contrast  in 8508 ms
compiled jst/groups/manage/assignToGroupMenu.scss new_styles_normal_contrast  in 8507 ms
compiled jst/groups/manage/groupCategories.scss new_styles_normal_contrast  in 8507 ms
compiled jst/MoveOutcomeDialog.scss new_styles_normal_contrast  in 8607 ms
compiled jst/groups/manage/groupCategoryCreate.scss new_styles_normal_contrast  in 8594 ms
compiled jst/groups/manage/groupUsers.scss new_styles_normal_contrast  in 8594 ms
compiled jst/messageStudentsDialog.scss new_styles_normal_contrast  in 8594 ms
compiled jst/TreeBrowser.scss new_styles_normal_contrast  in 8608 ms
compiled jst/roles/newRole.scss new_styles_normal_contrast  in 8561 ms
compiled jst/roles/permissionButton.scss new_styles_normal_contrast  in 8561 ms
compiled jst/roles/rolesOverrideIndex.scss new_styles_normal_contrast  in 8561 ms
compiled jst/tinymce/EquationEditorView.scss new_styles_normal_contrast  in 8561 ms
compiled jst/UserObservees.scss new_styles_normal_contrast  in 8608 ms
compiled jst/tinymce/InsertUpdateImageView.scss new_styles_normal_contrast  in 8561 ms
compiled jst/widget/UploadMediaTrackForm.scss new_styles_normal_contrast  in 8561 ms
compiled jst/assignments/DueDateOverride.scss new_styles_normal_contrast  in 8598 ms
compiled jst/groups/manage/group.scss new_styles_normal_contrast  in 8597 ms
compiled jst/groups/manage/editGroupAssignment.scss new_styles_normal_contrast  in 8597 ms
compiled jst/calendar/calendarApp.scss new_styles_normal_contrast  in 8599 ms
compiled jst/groups/manage/groupCategory.scss new_styles_normal_contrast  in 8598 ms
compiled jst/outcomes/outcomePopover.scss new_styles_normal_contrast  in 8563 ms
compiled bundles/conferences.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 656 ms
compiled bundles/alerts.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 697 ms
compiled bundles/assignments_edit.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 730 ms
compiled bundles/account_admin_tools.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 730 ms
compiled bundles/assignments.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 773 ms
canvas_css warning app/stylesheets/bundles/canvas_quizzes.scss has an external url() to: #default#VML that's not a problem but normally our css only links to files in our repo
compiled bundles/canvas_quizzes.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 921 ms
compiled bundles/agenda_view.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 970 ms
compiled bundles/calendar2.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 1317 ms
compiled bundles/context_list.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 1363 ms
compiled bundles/context_modules.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 1364 ms
compiled bundles/context_module_progressions.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 1367 ms
compiled bundles/content_migrations.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 1372 ms
compiled bundles/course_list.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 1446 ms
compiled bundles/context_modules2.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 1568 ms
compiled bundles/course_wizard.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 1661 ms
compiled bundles/dashboard_card.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 1895 ms
compiled bundles/developer_keys.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 2016 ms
compiled bundles/dashboard.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 2134 ms
compiled bundles/edit_calendar_event_full.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 2193 ms
compiled bundles/discussions.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 2311 ms
compiled bundles/conversations_new.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 2665 ms
compiled bundles/account_settings.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3258 ms
compiled bundles/discussions_list.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3282 ms
compiled bundles/course_settings.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3283 ms
compiled bundles/grade_summary.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3654 ms
compiled bundles/gradebook_uploads.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3682 ms
compiled bundles/gradebook_history.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3685 ms
compiled bundles/gradebook2.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3686 ms
compiled bundles/grading_standards.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3688 ms
compiled bundles/grading_periods.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3689 ms
compiled bundles/imports.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3822 ms
compiled bundles/instructure_eportfolio.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3841 ms
compiled bundles/learning_outcomes.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3841 ms
compiled bundles/locale.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3841 ms
compiled bundles/login.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3848 ms
compiled bundles/messages.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3808 ms
compiled bundles/new_assignments.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3846 ms
compiled bundles/modules_next.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3855 ms
compiled bundles/notification_preferences.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 4046 ms
compiled bundles/otp_login.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 4325 ms
compiled bundles/mobile_auth.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 4458 ms
compiled bundles/registration.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 4483 ms
compiled bundles/reports.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 4485 ms
compiled bundles/profile_edit.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 4631 ms
compiled bundles/react_files.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 4848 ms
compiled bundles/profile_show.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 5141 ms
compiled bundles/roster_user.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 5272 ms
compiled bundles/roster.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 5287 ms
compiled bundles/select_content_dialog.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 5287 ms
compiled bundles/quizzes.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 5612 ms
compiled bundles/styleguide.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 6025 ms
compiled bundles/sub_accounts.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 6051 ms
compiled bundles/speed_grader.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 6056 ms
compiled bundles/theme_preview.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 6056 ms
compiled bundles/quizzes_ember.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 6596 ms
compiled bundles/user_grades.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 6610 ms
compiled bundles/theme_editor.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 6610 ms
compiled bundles/user_notes.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 7016 ms
compiled jst/DiscussionTopics/IndexView.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 7016 ms
compiled jst/FindFlickrImageView.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 7016 ms
compiled bundles/tinymce.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 7016 ms
compiled jst/MoveOutcomeDialog.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3700 ms
compiled jst/TreeBrowser.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3872 ms
compiled bundles/what_gets_loaded_inside_the_tinymce_editor.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 7197 ms
compiled jst/UserObservees.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3877 ms
compiled jst/groups/manage/group.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3877 ms
compiled jst/groups/manage/editGroupAssignment.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3877 ms
compiled jst/assignments/DueDateOverride.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3877 ms
compiled jst/calendar/calendarApp.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3931 ms
compiled jst/groups/manage/groupCategory.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3900 ms
compiled jst/outcomes/outcomePopover.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 3900 ms
canvas_css warning app/stylesheets/bundles/common.scss new_styles_normal_contrast contains a url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
canvas_css warning app/stylesheets/bundles/common.scss has an external url() to:  that's not a problem but normally our css only links to files in our repo
canvas_css warning app/stylesheets/bundles/common.scss new_styles_normal_contrast contains a url() to: /images/mediaelement/skipback.png which doesn't exist on disk
compiled bundles/common.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 in 8060 ms

**Comment by AndranikMarkosyan** [comment]
I run canvas on EC2 server with 2GB of RAM ubuntu 14.04 lTS, Previous canvas version  works fine!

**Comment by ryankshaw** [comment]
what version of node are you using? make sure it is at least 0.12. also, after you make sure 0.12 is installed do a `rm -rf node_modules gems/*/node_modules && npm cache clear && npm install` to make sure everything there is right. 

if it still doesn't work after that, my next guess it that maybe an oomkiller is killing the process. check: `egrep -i 'killed process' /var/log/messages`

**Comment by ryankshaw** [comment]
if it is indeed an out of memory problem, you could maybe manually edit node_modules/.bin/brandable_css line 5 so it looks like:
`process.env.UV_THREADPOOL_SIZE = 1` (instead of the 8 it had)

if that does fix your problem, be aware that I'm changing that code so in future releases you'll be able to just set the UV_THREADPOOL_SIZE environment variable and it will honor it. eg: `UV_THREADPOOL_SIZE=1 ./node_modules/.bin/brandable_css`

**Comment by AndranikMarkosyan** [comment]
nodejs --version
v0.12.7

**Comment by AndranikMarkosyan** [comment]
this the output of 
rm -rf node_modules gems/*/node_modules && npm cache clear && npm ins

npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /home/ubuntu/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

> canvas-lms@0.0.0 preinstall /var/canvas
> script/gem_npm install

npm WARN peerDependencies The peer dependency jsdom@~0.8.10 included from i18nliner-handlebars w
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> contextify@0.1.14 install /var/canvas/gems/canvas_i18nliner/node_modules/jsdom/node_modules/co
> node-gyp rebuild

-

**Comment by AndranikMarkosyan** [comment]
egrep -i 'killed process' /var/log/syslog
Aug 12 04:03:04 canvas kernel: [  907.339230] Killed process 1347 (ruby) total-vm:715468kB, anon-rss:366696kB, file-rss:0kB
Aug 12 04:13:16 canvas kernel: [  315.546165] Killed process 1479 (ruby) total-vm:717620kB, anon-rss:388584kB, file-rss:0kB
Aug 12 04:28:17 canvas kernel: [ 1215.821730] Killed process 2308 (ruby) total-vm:708792kB, anon-rss:372632kB, file-rss:80kB
Aug 12 04:31:41 canvas kernel: [ 1419.745820] Killed process 1638 (ruby) total-vm:717620kB, anon-rss:390932kB, file-rss:0kB
Aug 12 05:09:52 canvas kernel: [ 3710.822106] Killed process 2917 (ruby) total-vm:717704kB, anon-rss:391472kB, file-rss:0kB
Aug 12 15:15:00 canvas kernel: [ 1294.134522] Killed process 1374 (ruby) total-vm:710112kB, anon-rss:367244kB, file-rss:44kB
Aug 12 15:15:34 canvas kernel: [ 1328.634458] Killed process 2329 (ruby) total-vm:716036kB, anon-rss:367284kB, file-rss:32kB
Aug 12 15:16:30 canvas kernel: [ 1384.052719] Killed process 2610 (ruby) total-vm:709776kB, anon-rss:366940kB, file-rss:0kB
Aug 13 01:02:52 canvas kernel: [ 1346.819993] Killed process 1389 (ruby) total-vm:715784kB, anon-rss:366976kB, file-rss:0kB
Aug 13 01:06:20 canvas kernel: [ 1555.059337] Killed process 3098 (ruby) total-vm:717712kB, anon-rss:388824kB, file-rss:0kB
Aug 13 01:06:21 canvas kernel: [ 1555.864001] Killed process 3017 (ruby) total-vm:716688kB, anon-rss:368620kB, file-rss:4kB

**Comment by AndranikMarkosyan** [comment]
./node_modules/.bin/brandable_css    does not exist

 bundle exec rake canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
--> Finished: 'Making sure node_modules are up to date' in 4.385054907
--> Starting: 'compile css (including custom brands)'
sh: 1: ./node_modules/.bin/brandable_css: not found
rake aborted!
Error: running BrandableCSS CLI: ./node_modules/.bin/brandable_css 2>&1

**Comment by AndranikMarkosyan** [comment]
instead ibrandable_css located in  ./node_modules/.brandable_css/bin/

**Comment by ryankshaw** [comment]
if you did `rm -rf node_modules gems/*/node_modules && npm cache clear && npm install` then it should exist. did you get an error when running that?

**Comment by AndranikMarkosyan** [comment]
yes it exist now,
however still have an error in log  and blank page instead of login page
exception_message: 
/var/canvas/public/dist/brandable_css/brandable_css_bundles_with_deps.jsoncompressed does not exist. You need to run ./node_modules/.bin/brandable_css before you can serve css.

**Comment by ryankshaw** [comment]
Run RAILS_ENV=production bundle exec rake canvas:compile_assets

**Comment by AndranikMarkosyan** [comment]
Yes it works!!! thanks a lot!

**Comment by Ferkaz** [comment]
Brandable_css is still failing for me on the `npm install` step. I am using OS X v10.6.8. When I remove brandable_css dependency from package.json the installation goes ok. 

This is what I get after I run `rm -rf node_modules gems/*/node_modules && npm cache clear && npm install`

```
Binary downloaded and installed at /home/user/canvaslms/htdocs/node_modules/brandable_css/node_modules/node-sass/vendor/darwin-x64-14/binding.node

> node-sass@3.2.0 postinstall /home/user/canvaslms/htdocs/node_modules/brandable_css/node_modules/node-sass
> node scripts/build.js

` /home/user/canvaslms/htdocs/node_modules/brandable_css/node_modules/node-sass/vendor/darwin-x64-14/binding.node ` exists.
 testing binary.
Problem with the binary.
Manual build incoming.
Building: /home/user/nodejs/bin/.node.bin node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
xcodebuild: error: Initialization failed.
	Reason: Scanning for plug-ins failed.

  CXX(target) Release/obj.target/libsass/src/libsass/ast.o
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-stdlib=libc++"
make: *** [Release/obj.target/libsass/src/libsass/ast.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/canvaslms/htdocs/node_modules/brandable_css/node_modules/node-sass/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 10.0.0
gyp ERR! command "/home/user/nodejs/bin/.node.bin" "/home/user/canvaslms/htdocs/node_modules/brandable_css/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/user/canvaslms/htdocs/node_modules/brandable_css/node_modules/node-sass
gyp ERR! node -v v0.12.6
gyp ERR! pangyp -v v2.3.0
gyp ERR! not ok
Build failed
npm ERR! Darwin 10.0.0
npm ERR! argv "/home/user/nodejs/bin/.node.bin" "/home/user/nodejs/bin/npm" "install"
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/canvaslms/htdocs/npm-debug.log
```

And when I check on `node_modules/` directory I don't get any brandable_css folder so I can try to change `process.env.UV_THREADPOOL_SIZE`.

```
$ ls node_modules/
babel			fleck			gulp-load-plugins	karma-qunit		react-tools		vinyl-fs
babel-core		gglobby			gulp-rev		karma-requirejs		requirejs		xsslint
coffee-script		glob			karma			lodash			testem
compute-cluster		gulp			karma-firework-reporter	qunitjs			uglify-js
```

Someone can help? It is very painful that I could install the July version perfectly but this one is failing because of this new dependency.

Thank you!

**Comment by ccutrer** [comment]
@Ferkaz it looks like the problem is that your compiler doesn't support 4+ year old standards. It's coming from the node-sass component which is not written by Instructure. My recommendations would be first to see if you can install a newer version of Xcode, and if not upgrade from Snow Leopard to either Mavericks or Yosemite. Apple provides their operating systems as free upgrades, and you are 4 major releases behind.

**Comment by rivernate** [comment]
I'm going to mark this as closed, if you are still having problems feel free to start a discussion on: https://groups.google.com/forum/#!forum/canvas-lms-users
