### ISSUE TITLE
Content migration, File upload not possible after publication

### ISSUE THREAD

**Issue by fred-bict** [instructure/canvas-lms#670]
Hi,
Module: content_migration
18-07-2015
Issue: If a course has been publiced, a file upload is no longer possible. Select 'chooseMigrationConverter' -> options: course copy importer, canvas cartridge importer, moodle.
Options: qti converter and zip file importer seem to look well.

**Comment by rivernate** [comment]
Can you provide some more details about the issue your encountering? I tried to reproduce it from the information provided but was not able to see any issues. If you can provide some more detailed steps, as well as any errors you are seeing that would be helpful.

The preferred format (found here: https://github.com/instructure/canvas-lms/blob/master/CONTRIBUTING.md ) for an issue is:

    Summary:
    Steps to reproduce:
    Expected behavior:
    Additional notes:

**Comment by fred-bict** [comment]
Steps to reproduce:
> select a course that's been publiced, go to Settings 
> Click on Import button (content_migrations)
> From module Content Migrations, choose Option  'canvas_cartridge_importer' (from list ChooseMigrationConverter), Image is showing the result:
![canvas migrationconverter](https://cloud.githubusercontent.com/assets/9447563/9282743/ea991b9a-42ce-11e5-92f2-f9a691fa0490.png)
> Only the Cancel and Import buttons are displayed.

Expected behavior:
> Choose option 'canvas_cartridge_importer'
> Show button 'migrationFileupload' and others. See image (when a course is not yet publiced)
![canvas migrationconverter2](https://cloud.githubusercontent.com/assets/9447563/9282977/5f6b1fee-42d0-11e5-9548-09c41a6cc876.png)

Additional notes:
Canvas GitHub Check out: 18-07-2015
Server specs: Ubuntu 14.04, Passenger 5.0.13, Ruby 2.1 (on two different servers, Test and Production)
Browsers: FireFox 39 on Ubuntu 12.04 desktop, IE11 on Windows7, FireFox 40 on Windows7

Fred

**Comment by fred-bict** [comment]
I have just add some more details.
Fred

Op 14-08-15 om 20:19 schreef Nathan Mills:

**Comment by rivernate** [comment]
I tried to duplicate the problem on the 'release/2015-07-18.01' but was unable to do so.  Can you try compiling assets and report back if you see any errors? (see https://github.com/instructure/canvas-lms/wiki/Production-Start#file-generation for details on how to do it)

Also are there any errors in your javascript console?

**Comment by fred-bict** [comment]
Thanks, I will recompile the assests.
Javascript console gives only one Warning. Translated from Dutch something like: 
Do not use getPreventDefault() ..... use defaultPrevented.

**Comment by fred-bict** [comment]
Just recompiled the Assests in a Test environment. (Sorry for the delay.)
Can't find any Error, only some Warnings. See below the log (screen ouput).
After compiling the Assests, restarted the Ubuntu 14.04 server.
The behavior is still the same.

Log ouput:
fred@herft:/var/canvas/current$ bundle exec rake canvas:compile_assets
working in 4 processes
--> Starting: 'Compile sass and make jammit css bundles'
--> Starting: 'npm run compile-sass'
--> Starting: 'css:styleguide'--> Starting: 'compile coffee, js 18n, and run r.js optimizer'
--> Starting: 'Generate documentation [yardoc]'

--> Starting: 'js:generate'
--> creating styleguide
Building client app 'canvas_quizzes'
	Running 'npm install'...

> canvas-lms@0.0.0 compile-sass /var/canvas/releases/20150718test
> node script/compile-sass.js

npm WARN package.json canvas_quizzes@1.0.0 No repository field.
npm WARN package.json canvas_quizzes@1.0.0 No license field.
	Running 'npm run build'...
# writing file: app/views/info/styleguide.html.erb
--> Finished: 'css:styleguide' in 8.08135266
Client app 'canvas_quizzes' was built successfully.oller.rb
--> Creating ember app bundles
--> Creating ember app bundles finished in 0.009498628
--> Pre-compiling ember handlebars templates
--> Pre-compiling handlebars templates--> Compiling React JSX--> Generating plugin extensions
--> Generating plugin extensions finished in 0.001045656
⌎ Parsing app/controllers/quizzes/quiz_reports_controller.rb

--> Compiling CoffeeScript with 'coffee' binarycontroller.rb
--> Pre-compiling ember handlebars templates finished in 4.156243143b
[warn]: @param tag has unknown parameter name: conversations 
    in file `app/controllers/quizzes/quiz_submission_users_controller.rb' near line 139
--> Compiling React JSX finished in 9.81903368
--> Pre-compiling handlebars templates finished in 15.343298968
⌎ Generating /var/canvas/releases/20150718test/public/doc/api/all_resources.html............................................................................................................................⌏ Generating /var/canvas/releases/20150718test/public/doc/api/all_resources.html............................................................................................................................⌌ Generating /var/canvas/releases/20150718test/public/doc/api/all_resources.html............................................................................................................................⌍ Generating /var/canvas/releases/20150718test/public/doc/api/all_resources.html............................................................................................................................--> Compiling CoffeeScript finished in 39.719868151
etc....

--> Finished: 'js:generate' in 51.599082491
--> Starting: 'i18n:generate_js'
.Files:          96
Modules:         0 (    0 undocumented)
Classes:        95 (   31 undocumented)
Constants:       0 (    0 undocumented)
Methods:       412 (    7 undocumented)
 92.50% documented
API Documentation successfully generated in public/doc/api
See public/doc/api/index.html
--> Finished: 'Generate documentation [yardoc]' in 56.774429996
.................................................................................................................................................................................................................................................................................... etc.

Finished in 9.525 seconds

2040 files, 4511 strings, 0 failures
--> Finished: 'i18n:generate_js' in 15.129534215
--> Starting: 'js:build'
--> Concatenating JavaScript bundles with r.js
--> Finished: 'npm run compile-sass' in 70.698672885
--> Starting: 'Jammit'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/bundles/full_files.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_high_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_high_contrast/bundles/full_files.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_normal_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_normal_contrast/bundles/full_files.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_high_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/new_styles_high_contrast/bundles/full_files.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_normal_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_normal_contrast/bundles/full_files.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/bundles/facebook.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/bundles/full_files.css'
--> Finished: 'Jammit' in 0.356585065
--> Finished: 'Compile sass and make jammit css bundles' in 71.055463646
--> Concatenated JavaScript bundles in 90.200804487
--> Compressing JavaScript with UglifyJS
--> Compressed JavaScript in 45.876231346
--> Finished: 'js:build' in 136.089489558
--> Finished: 'compile coffee, js 18n, and run r.js optimizer' in 202.818573648
Finished compiling assets in 203.167601965. parallelism saved 135.562217985 (59.97924894684195%)

**Comment by fred-bict** [comment]
This problem is related to "localize values in datetime picker fields" see:
https://github.com/instructure/canvas-lms/commit/d79ccc78d97e30951292115822896dda08f169b1 

Workaround if a course is published.
If a course is published Canvas gets the current datetime stamp as value of "courses.start_at".
If the time stamp is not equal to 00:00 UTC,  the above-mentioned problem occurs.
To restore it, for using the Content Migration module, first:
- change the value of "start_at"; use "Edit course" clear datetime and add the same date without the time
- save changes
- open Content Migration, and everything works ok. 

Fred
