### ISSUE TITLE
Apache error log shows dozens of errors starting with "Error during failsafe response: undefined method `'data'

### ISSUE THREAD

**Issue by bmurry** [instructure/canvas-lms#672]
Just finished the canvas production installation. When I try to visit the site I get a 500 Internal Service Error and when I go check the apache2.4 error log there are ruby errors all over the place. The first "App 2093 stderr:" line says "Error during failsafe response: undefined method `'data' for #<ErrorReport:0x00...".

I figure something went wrong during the installation process. For one, the brightbox ppa did not work, although I was able to install all the packages and they seem to be the proper versions.

I'm running on a Debian 8.1 Jessie home server with Apache 2.4.
Any help would be appreciated!

**Comment by sciosciap** [comment]
Hello!

 

Important message, visit http://constructionmaisonambares.com/calling.php?qi4

 

sciosciap@mail.montclair.edu

**Comment by sciosciap** [comment]
Hey friend!

 

Check it out http://gssupplys.com/ways.php?c4j

 

sciosciap@mail.montclair.edu
