### ISSUE TITLE
Possible invalid associations

### ISSUE THREAD

**Issue by kachroosneha** [instructure/canvas-lms#673]
I used rails-erd gem in the application. Then followed http://voormedia.github.io/rails-erd/install.html link for the installation.
After that did bundle exec erd. In the output I can see the ER diagram is generated but can't see where it got saved as nothing is coming when I do git status.
The output is coming as:
Loading application in 'canvas-lms'...
Generating entity-relationship diagram for 199 models...
Warning: Ignoring invalid model Tableless (table tablelesses does not exist)
Warning: Ignoring invalid model ContextModuleSubHeader (table tablelesses does not exist)
Warning: Ignoring invalid model ExternalUrl (table tablelesses does not exist)
Warning: Ignoring invalid association :sub_context on AppointmentGroupSubContext (polymorphic interface SubContext does not exist)
Warning: Ignoring invalid association :asset_access_ranges on AssetUserAccess (uninitialized constant AssetUserAccess::AssetAccessRange)
Warning: Ignoring invalid association :original_item on ClonedItem (polymorphic interface OriginalItem does not exist)
Warning: Ignoring invalid association :crocodoc_annotations on CrocodocDocument (uninitialized constant CrocodocDocument::CrocodocAnnotation)
Warning: Ignoring invalid association :asset_context on DelayedNotification (polymorphic interface AssetContext does not exist)
Warning: Ignoring invalid association :association_object on LearningOutcomeResult (polymorphic interface AssociationObject does not exist)
Warning: Ignoring invalid association :links on Lti::MessageHandler (uninitialized constant Lti::MessageHandler::Lti::LtiLink)
Warning: Ignoring invalid association :links on Lti::ToolProxyBinding (uninitialized constant Lti::ToolProxyBinding::Lti::LtiLink)
Warning: Ignoring invalid association :asset_context on Message (polymorphic interface AssetContext does not exist)
Warning: Ignoring invalid association :association_object on RubricAssociation (polymorphic interface AssociationObject does not exist)
Diagram saved to 'erd.pdf'.

**Comment by rivernate** [comment]
@kachroosneha, I've just take a preliminary look at this.  I'm able to generate a .dot file with rails-erd, but when I try to convert it to a pdf graphiz segfaults.  I'm guessing that is why you are not seeing the pdf output.  

I'll look into the associations a bit, but you may want to reach out to the maintainer of rails-erd as well.

**Comment by rivernate** [comment]
I'm closing this since the issue seems to be with the rails-erd gem / graphiz.
