### ISSUE TITLE
[Bug] Styleguide tells we can use "forms" but we can't

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#674]
Hello everyone, 

Perhaps it is meant to be, but, in the styleguide of Canvas LMS (for instance, here: https://canvas.instructure.com/styleguide#forms) it is said that we can use forms in textarea within the application (like in an assignment description or a wiki page). 

I tried to add a simple form in a wiki page:

```html
<div class="content-box">
  <form class="ic-Form-group ic-Form-group--inline">
    <div class="ic-Form-control">
      <label for="demo-text-input-5" class="ic-Label">Enter your email address</label>
      <div class="ic-Input-group">
        <div class="ic-Input-group__add-on" role="presentation" aria-hidden="true" tabindex="-1">
          <i class="icon-email"></i>
        </div>
        <input id="demo-text-input-5" class="ic-Input" placeholder="e.g., joe@site.com" type="email">
      </div>
    </div>
    <div class="ic-Form-actions">
      <button class="Button" type="button">Cancel</button>
      <button class="Button Button--primary" type="submit">Submit</button>
    </div>
  </form>
</div>
```

It did not work, because the form / input / button tags are filtered when we save the page. 

I found out that you're using your CanvasSanitize gem to sanitize the body of wiki page. Which is really good I think, but when you look at the code of the gem, you can see that form / input / button tags are not allowed tags. 

As you are using CanvasSanitize almost everywhere, it means that we just can't add forms in our apps. 

So... as I said perhaps it is meant to be, but if it is so, why does the styleguide speak about the possibility to create forms? Is this only for app developers (I thought the styleguide was created for teachers and editors)? Would it be unsafe to allow form / input / button tags in the CanvasSanitize gem?

Thanks in advance for your answer, 
Regis.

**Comment by claydiffrient** [comment]
@Kulgar I'm sorry you've run into some trouble with this.  The styleguide is primarily meant to to be used internally by our engineering teams to help us have a consistent UI throughout Canvas.  We can't guarantee behavior pulling those styles into Canvas pages.  There have been requests for a user-facing styleguide and our UI team is working to vet out what that would look like.

As far as the CanvasSanitize gem we use it to make sure that certain elements aren't able to be used that may cause security issues.  Having forms on pages can open up a myriad of security concerns. Buttons could be used to perform arbitrary tasks as an elevated user.  We like to keep things locked down for that sort of thing.

I would suggest creating an LTI tool to handle forms if that is something you want to do.

**Comment by Kulgar** [comment]
Ok, so, this was meant to be :)
Thanks!
