### ISSUE TITLE
verify email loop

### ISSUE THREAD

**Issue by artfulhacker** [instructure/canvas-lms#679]
we are seeing something really strange with accounts created via the api
they see the blue ribbon saying they need to verify the email address

![image](https://cloud.githubusercontent.com/assets/3683852/9492433/42478e22-4bac-11e5-8cd1-98338510c073.png)

the api though says it is active:

![image](https://cloud.githubusercontent.com/assets/3683852/9492399/02dd4cb8-4bac-11e5-80a4-1b598d085f3b.png)

if we click the send me the email, when we click the link instead we get this:

![image](https://cloud.githubusercontent.com/assets/3683852/9492443/66b1f018-4bac-11e5-9837-f46efb5d982c.png)

going back to the account it has the blue ribbon

**Comment by artfulhacker** [comment]
I should also let you know, these are the parameters we send:

![image](https://cloud.githubusercontent.com/assets/3683852/9492469/c55850d0-4bac-11e5-87d5-66f30018603f.png)

and the other part that is broken it seems is no matter what value I use for user[terms_of_use] they always get the Terms of Use agreement on first authentication

**Comment by rivernate** [comment]
@artfulhacker I wasn't able to duplicate the "verify loop". A great place to get get additional support is to in the mailing list http://groups.google.com/group/canvas-lms-users, if you are using cloud canvas you can report it through our support team.

For the issue with terms_of_use you can create a separate issue for that following the guidelines found here: http://groups.google.com/group/canvas-lms-users, or if you are a canvas could customer through the support team.

**Comment by artfulhacker** [comment]
@rivernate were you able to override the terms of use by sending true via the api?

**Comment by rivernate** [comment]
@artfulhacker: I was able to duplicate that, If you want to create a separate github issue for that I can create an internal ticket that is linked to the gh issue.  I posted the wrong link for the issue guidelines in the previous post. I updated the link, but here it is again for convenience: https://github.com/instructure/canvas-lms/blob/stable/CONTRIBUTING.md

**Comment by artfulhacker** [comment]
well there is a piece I left out, this user is signing in using single sign on (openid connect). maybe the broken "already verified email" is related to that?

**Comment by artfulhacker** [comment]
created #681

**Comment by artfulhacker** [comment]
also, it seems like support disagrees with your assessment of my issue:

Hi Mike,

Thanks for contacting Canvas Support. I believe you are experiencing a documented issue with the user creation API endpoint. When a user is created, there is currently no way to skip the registration part of the user creation process. Registration is basically the same thing as confirmation, so it's a little silly. Our engineers have already pushed a fix for this issue to the Beta environment. It should be deployed to production this Saturday. We'll let you know as soon as this is resolved.

Thanks,

Spencer Miller
L3 Support

Closing an issue and then editing your comment to make it look it you addressed the terms of use issue in the original response is shady. Come on, you didn't test it fully and just closed my issue and assumed I am an idiot. I figured that since terms of use wasn't working it could be related to this "verify loop" issue.

**Comment by ccutrer** [comment]
@artfulhacker: I apologize for the abruptness of the ticket close. We're still working on our community processes, and we're used to tickets that have languished for months, with no hope of response from the OP. I assure you @rivernate did at least try to reproduce your issue. Likely he was testing on his local development machine, where it has already been fixed (https://github.com/instructure/canvas-lms/commit/fe1594f9496c7309c33cc94b40b6b6c1c8ac796e). I also see no evidence the _content_ of his original comment was changed (just the link to the CONTRIBUTING.md), so the attacks on him are uncalled for (see also https://github.com/instructure/canvas-lms/blob/stable/code_of_conduct.md). I'm glad to see that you did file a separate ticket for terms_of_use, and hope you can continue to participate in the community. Based on the interactions I've already had with you on the OpenID issue (https://github.com/instructure/canvas-lms/issues/678), I'm confident that you are technically adept, and would love for you to continue to contribute and benefit from the open source side of the Canvas community. If you have any other suggestions for how we could have better handled this issue, you can e-mail me directly at cody@instructure.com.
