### ISSUE TITLE
Nodejs is not installed error

### ISSUE THREAD

**Issue by DonRichards** [instructure/canvas-lms#685]
I keep get this error: 
> Nodejs is NOT installed
> Error installing Node.js on your system. Please install manually and try again

I've tried manually installing and even completely purging the app and its legacy stuff. Still nothing

**Comment by grahamb** [comment]
Can you be more specific? What are you doing that generates the error? What does `which node` and `node --version` output?

**Comment by DonRichards** [comment]
Following the instructions it installed v0.10.25. I spun up a new virtual server and started following the "Quick Start" instructions step by step. It defaulted to development mode I believe.

**Comment by grahamb** [comment]
@DonRichards: where are you seeing that error message?

**Comment by DonRichards** [comment]
When I run the #3 step "./CODES.sh --full" from the Quick start guide

**Comment by grahamb** [comment]
I've never used the codes script, but a quick look at it shows:

```
    if $(which $NODE >/dev/null 2>&1) && $(which $NPM >/dev/null 2>&1); then
        green "Nodejs is installed\n"
        return 0
    else
        yellow "Nodejs is NOT installed\n"
        return 1
    fi
```

So, what does `which node` and `which npm` show?

**Comment by DonRichards** [comment]
Not sure how this worked but I reinstalled npm and tried a 3rd time and it worked. I did get a mess of errors from the npm install command when I ran it with the /canvas-lms folder directly. But that's for another string. So to fix

> sudo apt-get purge nodejs
> sudo apt-get install nodejs
> sudo apt-get install npm 

Not completely sure why this took multiple time. I was doing it again so I could screen record so I could post it here for you. 

To be clear, I don't know yet if it worked. I'm just not getting the original error any more.

**Comment by simonista** [comment]
Hey @DonRichards, we've been trying to keep github issues reserved for bug reports in the functionality of the app.  Hopefully you got this issue resolved, but if not, you might try our google group: https://groups.google.com/forum/#!forum/canvas-lms-users
