### ISSUE TITLE
Quickstart canvas:compile_assets killed running BrandableCSS CLI

### ISSUE THREAD

**Issue by jd555** [instructure/canvas-lms#687]
I am trying to do a test Quickstart install on an AWS instance running Ubuntu 14.04. Everything went smoothly until I got to the step to build the file assets, using this command:

$GEM_HOME/bin/bundle exec rake canvas:compile_assets

The process dies with the error (and trace results): 

Killed
rake aborted!
Error: running BrandableCSS CLI: ./node_modules/.bin/brandable_css 2>&1
/home/ubuntu/canvas/lib/brandable_css.rb:102:in `run_cli!'
/home/ubuntu/canvas/lib/brandable_css.rb:85:in `compile_all!'
/home/ubuntu/canvas/lib/tasks/canvas.rake:121:in `block (3 levels) in <top (required)>'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/ubuntu/canvas/lib/tasks/canvas.rake:7:in `log_time'
/home/ubuntu/canvas/lib/tasks/canvas.rake:121:in `block (2 levels) in <top (required)>'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/.gems/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/ubuntu/.gems/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/ubuntu/.gems/bin/rake:23:in `load'
/home/ubuntu/.gems/bin/rake:23:in `<main>'
Tasks: TOP => canvas:compile_assets

Suggestions?

jd

**Comment by ccutrer** [comment]
My guess is that the process was killed because you ran out of memory. In the future, we try to reserve GitHub issues for bugs with the code. You can get help setting Canvas up on the mailing list, or in IRC. You can find details at https://github.com/instructure/canvas-lms/wiki#getting-help.

**Comment by jd555** [comment]
Sorry -- thanks for the reply.
