### ISSUE TITLE
Question: What is on production?

### ISSUE THREAD

**Issue by ArtskydJ** [instructure/canvas-lms#690]
What is on production? The stable branch? The latest release?

I'm wondering specifically about this commit: 6a9825d9a67f259862b8f95d25a40705f4592ea6.

Thanks!

**Comment by roor0** [comment]
the stable branch is what we run on production, that specific commit is just on master. We can pick that commit to our beta branch and it would hit production on 9/19

**Comment by ArtskydJ** [comment]
Cool; thanks for the info!
