### ISSUE TITLE
[Bug - notifications] - segmentation fault with too many recipients for announcements

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#693]
Hello everyone, 

I wanted to know if anyone else had a segmentation fault in delayed job logs when publishing a new announcements to a course with a lot of active students (15 000 to 20 000 students). 

I had this problem, the delayed job process just crashed because of a segmentation fault at the Nokogiri level. 

In order to solve this I created a small fix in the Notifier class, creating a new DelayedNotification every 5000 recipients. It seems to work pretty well but I'm not sure about other bugs that may rise because of this fix. 

Well, as always, if you have any clue on what is going on or a better way to solve this, I'll be glad to help you debugging it. :)

Regis

**Comment by codekitchen** [comment]
Hey @Kulgar , we fixed this a few releases back, are you on the latest Canvas stable branch?

**Comment by Kulgar** [comment]
@codekitchen : Oh! That is really great to know. In fact I was just planning to update my version tomorrow... 

 Could you point me to the fix please? :)

**Comment by codekitchen** [comment]
It took quite a few commits, so it's hard to point to one specific fix commit. This commit: https://github.com/instructure/canvas-lms/commit/c9973bfa656a56f4bd61b36dab6c1f2e51284fb6 is the one that makes sure `libxml-ruby` never comes back, as that was the root cause of the segfaults.

**Comment by Kulgar** [comment]
A big hug to you. It seems that I don't have this commit in my current version. 
I'll close this issue and will reopen it if I have the problem again.
