### ISSUE TITLE
File upload hangs on trying to upload a 0Kb file

### ISSUE THREAD

**Issue by DhruvKalaria** [instructure/canvas-lms#694]
_Steps to Reproduce:_
1. Go to any assignment submission page.
2. Upload multiple files
3. Of the several files keep one file of 0kb.
4. Click on Submit Assignment
5. The submit button will gray out and the canvas will remain in that state undefinitely.
6. The exact same behavior is observed when you just have a single file.

_Expected Result:_
The file upload should be successful and user should be redirected successfully to the assignment page.

_Actual Resut:_
The file upload stuck for indefinite time.

**Comment by DhruvKalaria** [comment]
This issue is seen cross browser. I have tried with IE11 and Chrome.

**Comment by ccutrer** [comment]
Confirmed that the error we're getting from S3 is:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>EntityTooSmall</Code>
  <Message>Your proposed upload is smaller than the minimum allowed size</Message>
  <ProposedSize>0</ProposedSize>
  <MinSizeAllowed>1</MinSizeAllowed>
  [..snip..]
</Error>
```
