### ISSUE TITLE
DELETE /api/v1/groups/:group_id/users/:user_id doesn't respect sis_user_id parameter

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#695]
When making a request to DELETE /api/v1/groups/:group_id/users/:user_id, using the SIS parameter "sis_user_id:1234567" as the user_id doesn't work. Canvas return a 404 Resource not found error. Using the user's Canvas ID in the same request does work. 

I'm running the most recent release as of August 18th.

**Comment by ccutrer** [comment]
submitted on master

**Comment by christopher-b** [comment]
Thanks Cody!
