### ISSUE TITLE
Kaltura video audio recording showing always connecting

### ISSUE THREAD

**Issue by omerpucit** [instructure/canvas-lms#705]
Hi,

I have configured kaltura as well as red5 streaming server correctly according to documents but the thing is when i click on recording it asks about allow. After that its working fine like i recorded for few seconds but after stop recording it should show auto play recording as well as save button but instead of this it always show connecting.... It never return back, well i have updated KRecord.swf file with this one link provided http://2017261.mediaspace.kaltura.com/upload/webcam/catid/35852001 where it works fine but when i click on save it uses some other way to import video. Can any one help me out.

Thanks.

**Comment by EugeneWHZ** [comment]
I have the same issue on my Canvas/Kaltura/Red5 setup.

 - webcam recording in Kaltura works well
 - webcam recording in Canvas starts, but when I stop recording it says "Connecting" and playback does not start.

Canvas/Kaltura logs are empty (or I am checking wrong log files).

Did you find a solution?

**Comment by omerpucit** [comment]
Hi,

Actually this issue is relate to Krecord.swf i have already reported their
issue, but no response, you should move to adobe media player or Wowza,
currently we have moved to adobe media server which is working perfect for
us.

Thanks.

On Tue, Oct 27, 2015 at 3:22 PM, Eugene <notifications@github.com> wrote:

> I have the same issue on my Canvas/Kaltura/Red5 setup.
>
>    - webcam recording in Kaltura works well
>    - webcam recording in Canvas starts, but when I stop recording it says
>    "Connecting" and playback does not start.
>
> Canvas/Kaltura logs are empty (or I am checking wrong log files).
>
> Did you find a solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/instructure/canvas-lms/issues/705#issuecomment-151445049>
> .
>



-- 

-- 
Regards,

Umer Bilal
Senior Software Engineer


UnlockTech
Contact: (+92) 313 4487430, 321 9898229
Skype: omer.afzaal
Email: omerpucit@gmail.com, sams.solutionz@gmail.com <omerpucit@gmail.com>
