### ISSUE TITLE
passenger-common1.9.1 unable to locate

### ISSUE THREAD

**Issue by lisandi** [instructure/canvas-lms#707]
"sysadmin@appserver:/var/canvas$ sudo apt-get install passenger-common1.9.1 libapache2-mod-passenger apache2"

is no more working as 
E: Unable to locate package passenger-common1.9.1
E: Couldn't find any package by regex 'passenger-common1.9.1'

**Comment by lisandi** [comment]
#658 
This was months ago - please change it in the tutorial that others won't struggle here to in future
The work around from Issue #658 is working just fine

**Comment by wizkid686** [comment]
Production start instructions were updated.

**Comment by FreedomBen** [comment]
thanks @wizkid686

**Comment by beado** [comment]
‫أُرسلت من الـ iPhone‬

‫في ١٩‏/١١‏/٢٠١٥ الساعة ١:٥٢ ص، كتب/كتبت ‏wizkid686 ***@***.***>:‬

﻿

Production start instructions were updated.

**Comment by beado** [comment]
﻿
﻿
﻿
C
‫أُرسلت من الـ iPhone‬

‫في ١٩‏/١١‏/٢٠١٥ الساعة ١:٥٢ ص، كتب/كتبت ‏wizkid686 ***@***.***>:‬

﻿

Production start instructions were updated.
