### ISSUE TITLE
Account Group invitation email contains incorrect link

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#709]
When a user is invited to an account group, Canvas will send out an email invitation with a link to the group, which looks like: https://[canvas]/accounts/[account_id]/groups

This link doesn't lead to the group page itself, but more importantly, leads to a page that most users won't have access to, and would result in a permission denied error, leading users to think that they don't have permission to access the group they were just invited too. 

The link should be https://[canvas]/groups/[group_id]

**Comment by simonista** [comment]
Yup, this seems wrong.  Thanks for the bug report.
