### ISSUE TITLE
Error in LTI Application

### ISSUE THREAD

**Issue by amulgarg** [instructure/canvas-lms#710]
Hi

We are trying to integrate an app through LTI. When this app submits the score we get an error -

```
"Duplicate nonce detected" . 
```

This error is triggered in LtiApiController.rb. 

```
unless Canvas::Redis.lock("nonce:#{@tool.asset_string}:#{nonce}", allowed_delta)
      raise BasicLTI::BasicOutcomes::Unauthorized, "Duplicate nonce detected"
end
```

These guys posted a similar issue here - https://groups.google.com/forum/#!topic/canvas-lms-users/-Q4Y_sV7EKE and were able to solve their problem by dealing with Redis overflow.

We checked Redis on our server and found Redis cache is enabled and works properly. So that is not the issue AFAIK.
 
How do we solve this?

TIA

**Comment by arunkumargit** [comment]
Hi 
I'm facing the same issue with my app. How would I go about diagnosing this problem ?

**Comment by simonista** [comment]
Sounds like you may need to do some spelunking in Redis to see why the lock isn't getting released? Or maybe the nonce really is getting duplicated?  Sorry to not have a better suggestion than that. I'd try asking again on the mailing list, maybe start a new thread.
