### ISSUE TITLE
Broken symlinks in client_apps/canvas_quizzes

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#713]
There's a couple of broken symlinks in the canvas_quizzes client app:

* `client_apps/canvas_quizzes/vendor/canvas_app`: 
  * current: `../../app` (which translates to `$CANVAS_ROOT/client_apps/app`)
  * should be: `../../../app` (`$CANVAS_ROOT/app`)
* `client_apps/canvas_quizzes/www/font`
  * current: `../../../public/font`
  * should be `../../../public/fonts`

Happy to do a pull request to fix these if you like.

**Comment by simonista** [comment]
Per conversation in IRC, this does indeed look broken.  I'll watch for the PR.  Thanks!

**Comment by claydiffrient** [comment]
Closing, explanation is found with #714
