### ISSUE TITLE
Canvas Commons Setup

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#716]
Hello, 

Is it possible to configure Commons in Canvas installed from git repository? Or it is benefits of using just paid version of Canvas?

I have tried to use this tutorial:
https://community.canvaslms.com/servlet/JiveServlet/previewBody/4473-102-1-15014/InstructureSelfHostedCanvasCommonsSetup.pdf

but faced with the error "We were unable to add the app." when tried to add new  App in Canvas LMS.

Thanks for the advice.

**Comment by brentburg** [comment]
It looks like the dashes in the Config URL found the setup document got converted to unicode soft hyphens. So if you copy directly from the setup document the url is wrong. I will investigate how the document is being published and get that corrected, but for now try using the following for the Config URL:

`https://lor.instructure.com/api/v1/self-hosted-setup/tool-config`

**Comment by ally1** [comment]
Hello,

Thanks brentburg ! This step was passed.
Bet the new issue appeared.

When I entered:
"Client ID" and "Client Secret (Key)" as it showed in screenshot:
https://www.dropbox.com/s/kv62pg9npz6t2nn/2015-11-03_16-59_Account%20Settings.jpg?dl=0
next click "Continue setup".

New window appears: https://www.dropbox.com/s/v54xnqi3w6iqcqi/2015-11-03_17-01_Account%20Settings.jpg?dl=0
As manual says we need log in to the Commons via Canvas if it asks. When I click to he "Authorize" I get:
https://www.dropbox.com/s/3wazuas99z8ljip/2015-11-03_17-01_Account%20Settings%282%29.jpg?dl=0

Did you meet similar problem? Thanks.

**Comment by wizkid686** [comment]
I'm adding the app using the URL above and I'm still getting a Couldn't add app error. When I paste the URL in the browser I get: Cannot GET /api/v1/self-hosted-setup/tool-config .

What's going on?

**Comment by wizkid686** [comment]
Nevermind. Strip out the v1 part of the URL, that is no longer valid.

**Comment by simonista** [comment]
Sounds like you got things figured out?  If not, feel free to reopen.

**Comment by travestynv** [comment]
High Everyone! 
I am having a related issue. I can get through to authorizing. but I just get a token failed JSON response.  I authenticated through a cloud site that has access to commons.  I added that email to my site admin and tried again and still this is what I get.  Thanks in advance.
{"errors":[{"msg":"Token request failed"}]}

**Comment by shantinath** [comment]
Hi

When I clicked on configure i am getting following issue

Sorry, there is a problem in your Canvas/Commons configuration.

Please notify your Canvas administrator.

**Comment by KiranPurbey1993** [comment]
Hello All

**Comment by KiranPurbey1993** [comment]
When i clicked on continue setup, i found error ie...Unable to connect...can anyone solve these

**Comment by Paktusin** [comment]
Hi everyone. I have issue when enter ID and Client Sectr key, if press 'Continue Install', next page does not load. 

We have 2 errors:
```
Request URL:https://lor.instructure.com/api/courses
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:52.3.138.230:443
Response:{"errors":[{"param":"server-error","msg":"There was an error"}]}
```

`https://localhost:3000/login/oauth2/auth?client_id=10000000000002&redirect_uri=https%3A%2F%2Flor.instructure.com%2Fapi%2Foauth%2Fcanvas%2Faccount-setup-callback&state=aed9e4a91b624c598903978475dba60a%2Csetup&response_type=code
net::ERR_SSL_PROTOCOL_ERROR
`

**Comment by ivanovv** [comment]
@shantinath were you able to fix the error you had?

**Comment by Revelation1714** [comment]
I know this thread is little old, but I am running into similar issue. When I click Configure on step 19 in [this PDF](http://www.peru.k12.in.us/canvaslti/InstructureSelfHostedCanvasCommonsSetup.pdf), I am getting this error:
Configuration Error
Sorry, there is a problem in your Canvas/Commons configuration.
Please notify your Canvas administrator.
