### ISSUE TITLE
Theme editor preview not working

### ISSUE THREAD

**Issue by samuels410** [instructure/canvas-lms#717]
Hi,
I have installed latest canvas in Centos 6.7 with Ruby 2.1.6p336 using rvm.
Every things works fine but the theme editor preview not working,
Error report,
category: RuntimeError
created at: 2015-11-04 16:16:13 +0100
attempts: 0 
handler: --- !ruby/struct:Progress::Work object: !ruby/ActiveRecord:BrandConfig f7ac3fbdee13ed1aa0c66c363357b846 method: :save_and_sync_to_s3! args: - &id001 !ruby/ActiveRecord:Progress 20 :@progress: *id001 
job_tag: BrandConfig#save_and_sync_to_s3! 
max_attempts: 1 
pid: 3573 
priority: 0 
process_type: BackgroundJob 
run_at: 2015-11-04 15:16:12 UTC 
source: 
strand: 
        Error running BrandableCSS CLI: ./node_modules/.bin/brandable_css --brand-id f7ac3fbdee13ed1aa0c66c363357b846

/var/deploy/canvas/lib/brandable_css.rb:120:in `block in run_cli!'
/usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/open3.rb:199:in `popen_run'
/usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/open3.rb:188:in `popen2e'
/var/deploy/canvas/lib/brandable_css.rb:106:in `run_cli!'
/var/deploy/canvas/lib/brandable_css.rb:90:in `compile_brand!'
/var/deploy/canvas/app/models/brand_config.rb:144:in `compile_css!'
/var/deploy/canvas/app/models/brand_config.rb:160:in `save_and_sync_to_s3!'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/performable_method.rb:21:in `perform'
/var/deploy/canvas/app/models/progress.rb:100:in `perform'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/backend/base.rb:225:in `block in invoke_job'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:63:in `call'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:63:in `block in initialize'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:68:in `call'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:68:in `execute'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:41:in `run_callbacks'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/backend/base.rb:222:in `invoke_job'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/worker.rb:142:in `block (2 levels) in perform'
/usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/worker.rb:136:in `block in perform'
/var/deploy/canvas/config/initializers/delayed_job.rb:75:in `call'
/var/deploy/canvas/config/initializers/delayed_job.rb:75:in `block (2 levels) in <top (required)>'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas_statsd-1.0.3/lib/canvas_statsd/statsd.rb:75:in `time'
/var/deploy/canvas/config/initializers/delayed_job.rb:74:in `block in <top (required)>'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:81:in `call'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:81:in `block (2 levels) in add'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:63:in `call'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:63:in `block in initialize'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:81:in `call'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:81:in `block in add'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:68:in `call'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:68:in `execute'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/lifecycle.rb:41:in `run_callbacks'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/worker.rb:133:in `perform'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/worker.rb:108:in `block in run'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/worker.rb:202:in `configure_for_job'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/worker.rb:107:in `run'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/worker.rb:84:in `block in start'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/worker.rb:83:in `loop'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/worker.rb:83:in `start'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:161:in `block in spawn_worker'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:172:in `block in fork_with_reconnects'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:169:in `fork'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:169:in `fork_with_reconnects'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:160:in `spawn_worker'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:148:in `block (2 levels) in spawn_all_workers'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:148:in `times'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:148:in `block in spawn_all_workers'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:146:in `each'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:146:in `spawn_all_workers'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:108:in `start'
/var/deploy/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.9.15/lib/delayed/pool.rb:57:in `run'
script/delayed_job:10:in `<main>'

**Comment by FreedomBen** [comment]
Hi @samuels410.  Which version of node are you using?  Also, when you ran `bundle install`, `npm install`, and `bundle exec rake canvas:compile_assets`, did you encounter any errors?

**Comment by samuels410** [comment]
Hi @FreedomBen ,

Node : v0.12.5
Npm :  2.11.2

I don't face any issues when install bundle & npm install.
But compile time I faced lot of issues related to npm packages,

handlebars not found so I did npm install --save handlebars@~1
ember-template-compiler not found so I did npm install --save  ember-template-compiler,
i18nliner-handlebars not found so I did npm install --save i18nliner-handlebars/
And I got error in the /gems/canvas_i18nliner so I went to the directory and did npm install

These things sorted out and compilation completed with the one error invalid byte sequence in US-ASCII (ArgumentError)  from the dress_code gem.

After started nginx I got error telling that run gulp rev,
So I have ran npm install -g gulp the gulp rev.

**Comment by FreedomBen** [comment]
Hi @samuels410 ,

This question might be better suited for our mailing list.  You can find it at https://groups.google.com/forum/#!forum/canvas-lms-users

When you get it fixed, please come back and share your solution so that others can benefit from it.  Good luck!  I'll let you know if I find anything on my end.

Ben

**Comment by candidosales** [comment]
I have the same problem: #700 

When I pre-visualize the theme displays an alert and this error in ajax:

![Error ajax](http://i.snag.gy/DuHHR.jpg)

It is mandatory to file storage be the S3 to preview the editor work?

**Comment by candidosales** [comment]
@samuels410 solved the problem, follows this thread: #722 

The problem in compile assets affect the preview editor.

**Comment by simonista** [comment]
Sounds like this is now solved, so I'm going to close this out.
