### ISSUE TITLE
API: Passing parameters to objects which are `include[]`ed

### ISSUE THREAD

**Issue by cycomachead** [instructure/canvas-lms#718]
Let's say I'm making a request to to `/api/..../submissions/?...include[]=assignments`.

There should be a way to pass parameters to the assignments request, as I would if I were going to make a request to `/api/.../assignments/:id/?all_dates=true&override_assignment_dates=false`

Without that functionality, there are cases where you could use an include, but will still need to make all the individual requests because you can't get the data you want.

**Comment by FreedomBen** [comment]
@cycomachead I'll pass this on the the product manager for assignments to see if it is something they want to do.  Thanks!

**Comment by cycomachead** [comment]
Thanks! I also have a related post in the Canvas Community, which I'll add for reference:
https://community.canvaslms.com/thread/7269
