### ISSUE TITLE
i am not getting the proper ui

### ISSUE THREAD

**Issue by suyogtaksande** [instructure/canvas-lms#719]
i have just installed canvas lms but i am not getting the proper ui.

**Comment by FreedomBen** [comment]
Hi @suyogtaksande .  Unfortunately there isn't enough actionable information in your bug report.  Did `bundle install`, `npm install`, and `bundle exec rake canvas:compile_assets` finish successfully?

**Comment by suyogtaksande** [comment]
Thanks for your response freedom ben. I have solved this issue. And now everything is working nicely but i the icons are broken and the logos are not visible

**Comment by suyogtaksande** [comment]
i am facing this issue not getting proper ui in canvas. please help

--> Starting: 'Making sure node_modules are up to date'
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm ERR! Linux 3.13.0-67-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /home/suyog/Documents/my_work_space/canvas/canvas-lms/gems/canvas_i18nliner/node_modules/.bin/cake
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/home/suyog/Documents/my_work_space/canvas/canvas-lms/gems/canvas_i18nliner/node_modules/.bin/cake'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/home/suyog/Documents/my_work_space/canvas/canvas-lms/gems/canvas_i18nliner/node_modules/.bin/cake']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/suyog/Documents/my_work_space/canvas/canvas-lms/gems/canvas_i18nliner/node_modules/.bin/cake' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/suyog/Documents/my_work_space/canvas/canvas-lms/gems/canvas_i18nliner/npm-debug.log
--> Finished: 'Making sure node_modules are up to date' in 25.509546325000088
--> Starting: 'compile css (including custom brands)'
rake aborted!
Errno::ENOENT: No such file or directory - ./node_modules/.bin/brandable_css
/home/suyog/Documents/my_work_space/canvas/canvas-lms/lib/brandable_css.rb:106:in `run_cli!'
/home/suyog/Documents/my_work_space/canvas/canvas-lms/lib/brandable_css.rb:86:in `compile_all!'
/home/suyog/Documents/my_work_space/canvas/canvas-lms/lib/tasks/canvas.rake:121:in `block (3 levels) in <top (required)>'
/home/suyog/Documents/my_work_space/canvas/canvas-lms/lib/tasks/canvas.rake:7:in `log_time'
/home/suyog/Documents/my_work_space/canvas/canvas-lms/lib/tasks/canvas.rake:121:in `block (2 levels) in <top (required)>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

**Comment by wizkid686** [comment]
Looks like a permissions error. Try This: 
sudo chown -R canvasuser config/environment.rb log tmp public/assets \
                              public/stylesheets/compiled Gemfile.lock config.ru

It looks like your using a different directory than the default, so you might have to make some adjustments to the above command to reflect that. Also, try running npm install before you do the compile assets. Run npm install normal (not sudo), then try running the compile assets command as root.

**Comment by suyogtaksande** [comment]
thanks for your reply @wizkid686 . Installing npm solved my problem.
