### ISSUE TITLE
LTI viewport maximum without scroll

### ISSUE THREAD

**Issue by ryanhiebert** [instructure/canvas-lms#720]
LTI tools currently have the ability to tell the parent window to resize the viewport to the size of it's content by using `parent.postMessage` with a subject of `lti.frameResize`. I'm finding the special need to have the parent viewport become whatever size the viewport will allow without scrolling the parent viewport. This is so that I can implement a scrolling interface of my own, inside the LTI tool.

So, the outer would be Canvas. The LTI tool would send a message to resize the iframe to as big as it can without causing scrolling inside Canvas. The LTI tool would then use 100% of the size of the iframe to implement it's own scrolling.

In my case, the inner scrolling interface is a two-pane side-by-side independent scroll, with drag-and-drop between the sides. The iframe's document itself makes sure to use exactly 100% of the iframe, and no more (because it would cause scrolling). Then inside that are two side-by-side divs that implement scrolling.

Perhaps the `lti.frameResize` method could be extended to allow `null` as the height and/or width values, and that would be a special indicator which would indicate that it should take all available space in the viewport.

This is an enhancement to an existing feature, so I'm not sure where the best place to put this is. I suspect it would not be much work for somebody familiar with the `lti.frameResize` message, though that's only speculation.

**Comment by ToeBee** [comment]
If our beta instance is any indication, once the [new UI](https://guides.instructure.com/m/4214/l/418268-what-is-the-new-canvas-user-interface) goes live, the LTI iframe will no longer be a hard-coded size and will take as much room as is available in the browser by default.

**Comment by ryanhiebert** [comment]
That good to know, and may alleviate the concern somewhat. For my purposes, if still like to be able to signal that manually, because it may come after I've already resized it differently.
