### ISSUE TITLE
Unable to use grade passback feature.

### ISSUE THREAD

**Issue by IvanMyers1982** [instructure/canvas-lms#721]
We are currently writing an embedded app for canvas that contains a mini-game and a quiz. The quiz grade needs to be passed back to canvas as it's finished. The part we're running into trouble on is the oAuth signing process that prevents us from posting the grade to the passback url (we are getting a "(401) Unauthorized" web error). However, it looks like our oAuth header data has been filled out according to spec. How do you diagnose these unauthorized errors?

**Comment by IvanMyers1982** [comment]
Figured it out: wasn't converting the body hash to a base64 string. Making sure the conversion was done properly fixed the issue.

**Comment by FreedomBen** [comment]
Thanks for the followup @IvanMyers1982 :+1:
