### ISSUE TITLE
Canvas emails me with my own discussion replies

### ISSUE THREAD

**Issue by ctag** [instructure/canvas-lms#726]
After submitting a reply to a discussion in Canvas, I'm alerted that the discussion has been updated... With my own reply.

I just wrote the reply, I know what it says. My desire to be emailed when a discussion is updated tracks the operation of every other forum system I've encountered: update me when someone *else* posts.

**Comment by FreedomBen** [comment]
Hi @ctag .  We were unable to reproduce this on our end.  Are you a paying customer (or a student at a school who pays) or an open source contributor?

**Comment by ctag** [comment]
Hi @FreedomBen,

I'm a student at a school which is using Canvas through Instructure. I'm surprised but glad to hear that I'm not experiencing the default behaviour.

**Comment by simonista** [comment]
@ctag: sounds like the right next course of action is to use the help link in the app to report this issue, there may be something specific with your user account that is causing the problem (see http://guides.instructure.com/m/8470/l/41954-how-do-i-get-help-with-canvas). Submitting the issue that way will capture all the metadata we need (institution, user account, etc) to try to track down the issue.

Thanks for getting in touch, and good luck!
