### ISSUE TITLE
Because the new login page is not internationalized?

### ISSUE THREAD

**Issue by candidosales** [instructure/canvas-lms#729]
I put in PT-BR and still remains in EN, what's the problem?

**Comment by ccutrer** [comment]
I'm able to reproduce this on the current stable branch, though I'm pretty sure it's due to a problem we've had with importing new translations (we recently redesigned the login screen) than a problem with not actually switching to pt-BR (the links at the bottom of the screen _are_ translated).

**Comment by simonista** [comment]
@candidosales, we've fixed our importing problem with new translations, can you try this again with the latest master branch and see if it fixes the issue you were seeing?
