### ISSUE TITLE
Chat to canvas

### ISSUE THREAD

**Issue by candidosales** [instructure/canvas-lms#730]
Is there any plugin or free chat api to the canvas?

**Comment by wizkid686** [comment]
There was at one time but it was removed because the provider deprecated their api. You could look for an LTI app that does that and add that at the account level, I believe I saw a few last time I checked.

**Comment by kachroosneha** [comment]
You can check for Big Blue Button

**Comment by simonista** [comment]
You might also want to try searching or asking on the mailing list: https://groups.google.com/forum/#!forum/canvas-lms-users
