### ISSUE TITLE
Undumpable Exception with canvas:compile_assets rake task

### ISSUE THREAD

**Issue by AndranikMarkosyan** [instructure/canvas-lms#732]
During installation perform following command and rake aborted during r.js optimizer while ruuning RAILS_ENV=production bundle exec rake canvas:compile_assets

here is the output
```
--> Finished: 'compile coffee, js 18n, and run r.js optimizer' in 356.961886344
rake aborted!
Undumpable Exception -- #<RuntimeError: error running dress_code>
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets```(See full trace by running task with --trace)

**Comment by djbender** [comment]
What happens when you run `dress_code config/styleguide.yml` ?

**Comment by ravistm** [comment]
#dress_code config/styleguide.yml
-bash: dress_code: command not found

the above error showing

**Comment by csparx** [comment]
I'm having the same issue. Did you have any luck resolving this one?
`rails aborted!
Parallel::UndumpableException: RuntimeError: error running dress_code
/Users/christysparks/Documents/ReadyToWork/canvas/lib/tasks/css.rake:6:in `block (2 levels) in <top (required)>'
/Users/christysparks/Documents/ReadyToWork/canvas/lib/tasks/canvas.rake:48:in `block (3 levels) in <top (required)>'
/Users/christysparks/Documents/ReadyToWork/canvas/lib/tasks/canvas.rake:90:in `block (5 levels) in <top (required)>'
/Users/christysparks/Documents/ReadyToWork/canvas/lib/tasks/canvas.rake:7:in `log_time'
/Users/christysparks/Documents/ReadyToWork/canvas/lib/tasks/canvas.rake:90:in `block (4 levels) in <top (required)>'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:507:in `call_with_index'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:471:in `process_incoming_jobs'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:453:in `block in worker'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:444:in `fork'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:444:in `worker'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:435:in `block in create_workers'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:434:in `each'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:434:in `each_with_index'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:434:in `create_workers'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:373:in `work_in_processes'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/parallel-1.19.1/lib/parallel.rb:277:in `map'
/Users/christysparks/Documents/ReadyToWork/canvas/lib/tasks/canvas.rake:89:in `block (3 levels) in <top (required)>'
/Users/christysparks/Documents/ReadyToWork/canvas/lib/tasks/canvas.rake:88:in `block (2 levels) in <top (required)>'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
/Users/christysparks/Documents/ReadyToWork/canvas/bin/rails:9:in `require'
/Users/christysparks/Documents/ReadyToWork/canvas/bin/rails:9:in `<top (required)>'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/Users/christysparks/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/christysparks/Documents/ReadyToWork/canvas/bin/spring:13:in `require'
/Users/christysparks/Documents/ReadyToWork/canvas/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)`
