### ISSUE TITLE
Workflow state in messages table

### ISSUE THREAD

**Issue by kachroosneha** [instructure/canvas-lms#733]
Can someone please help me understanding how the workflow_state in messages table is saved. I can see  'State machine ' code in message.rb file but I am not getting from where the state is updated to sent, cancelled etc.

**Comment by stderr** [comment]
@kachroosneha The workflow state behavior is provided by the `workflow` gem in `gems/workflow`.

**Comment by kachroosneha** [comment]
@stderr I mean to say I am getting the code from where the workflow_state in messages table is updated to sent, staged or cancelled. What is the difference between staged and cancelled.

**Comment by ccutrer** [comment]
Staged means the message is ready to send. Cancelled means it was, well, cancelled. It is set to staged from https://github.com/instructure/canvas-lms/blob/48dbfad327f6185762e52ac8b82eb8c975799876/app/models/message.rb#L310 (which is an `after_save` callback). There are several lines that call `cancel` in message.rb - they all seem to be handling errors trying to deliver the message.
