### ISSUE TITLE
permisssions, is this a bug?

### ISSUE THREAD

**Issue by adamdruppe** [instructure/canvas-lms#736]
On this line:

https://github.com/instructure/canvas-lms/blob/stable/app/controllers/courses_controller.rb#L1535

I don't see the three s's anywhere else, looks like a typo... but nothing seems broken either.

**Comment by claydiffrient** [comment]
@adamdruppe Thanks for finding that typo... Ashamed to say that I'm the one who made it.

The corresponding place it's used also has the typo: https://github.com/instructure/canvas-lms/blob/stable/app/jsx/course_wizard/InfoFrame.jsx#L95

If you'd like to submit a PR to fix the typo we'd be happy to accept it.

**Comment by simonista** [comment]
Closing since your pull request has been merged.
