### ISSUE TITLE
Canvas Commons Tool does not scale to fill screen 

### ISSUE THREAD

**Issue by wizkid686** [instructure/canvas-lms#737]
Hello, 

when we setup canvas commons, we find that the tool does not resize to fill the browser window as it does on canvas.instructure.com

Upon closer inspection, we found that this CSS, which was present on canvas.instructure.com, but not on our instance, was responsible for rescaling the content. Why it was not present we do not know, but for now we placed it in a custom CSS and uploaded it via theme editor to fix.

Here is the CSS that was missing:

body.ic-full-screen-lti-tool .tool_content_wrapper {
    overflow-y: hidden;
    height: 100vh;
}

**Comment by simonista** [comment]
This may be a difference in old ui vs new ui.  If you want to share this information with other open source users, the open source mailing list (https://groups.google.com/forum/#!forum/canvas-lms-users) might be more appropriate, we try to reserve github issues for bug reports.

Glad you got things figured out though!
