### ISSUE TITLE
REST API Quiz Submission Question fails with 500

### ISSUE THREAD

**Issue by rodogir** [instructure/canvas-lms#740]
Hi,

Summary:
I'm currently evaluating the Canvas LMS REST API and encountered a problem with the Quiz Submission Question API. When trying to answer a multiple answers question the server responds with  500 Internal Server Error.

I followed the instructions from the API doc here:
https://canvas.instructure.com/doc/api/quiz_submission_questions.html#method.quizzes/quiz_submission_questions.answer

Is this API supposed to work or ist it related to the comments made in this post?
https://community.canvaslms.com/ideas/2348

Steps to reproduce:
1. Start a new quiz submission => 200 OK
`POST /api/v1/courses/96/quizzes/56/submissions?as_user_id=17`
2. Retrieve all questions  => 200 OK
`GET /courses/96/quizzes/56/questions? as_user_id=17&quiz_submission_id=21&quiz_submission_attempt=4`
3. Answer question => 500
`POST /api/v1/quiz_submissions/21?as_user_id=17`
```
{
  "attempt": 4,
  "validation_token": "15baaa646f1802ccf0b95211e9d379ebcee8abfc46c8872676dbb9eb9534a1e9",
  "quiz_questions": [{
    "id": "557",
    "answer": ["3977"]
  }]
}
```

Expected behavior:
Answer submission should be accepted.

Additional notes: see summary

Thank you for your help!

**Comment by claydiffrient** [comment]
Thanks for filing this issue @rodogir!  We'll take a look at it and see what's going on.

**Comment by ryanmt** [comment]
@rodogir I'm sorry for any confusion, but these endpoints seem to be working fine for me. 

Let me walk you through my validation steps and point out a key difference I noticed.

1. Open a new submission by POST to `api/v1/courses/:course_id/quizzes/:quiz_id/submissions` either as the user or by masquerading as a different user, as you've done above.

2. Retrieve all questions from one of two endpoints: the one you've used, or this one (which is easier in my book) `GET api/v1/quiz_submissions/:id/questions`.

3. Post answers to `api/v1/quiz_submissions/:id/questions`.  The root quiz_submission endpoint will not accept answers.  This was the only issue in what you've done above, it must be the **questions** endpoint.  

In each of the question types, the data you post must be formatted correctly.  The API returns errors to guide you to proper formatting.  

As an example, I answered a multiple choice question with this data JSON:
```json
{
    "attempt": 1,
    "validation_token": "tokenstringhere",
    "quiz_questions": [{
        "id": "121",
        "answer": 8147
    }]
}
```

4. Complete the submission by `POST /api/v1/courses/:course_id/quizzes/:quiz_id/submissions/:id/complete`


If you have any more questions, feel free to get back with us on it.

**Comment by rodogir** [comment]
@ryanmt 
I had misread the API for answering quiz questions and got confused with the resulting server error. Tried again with your instructions and everything worked as expected.

Thank you for the support! Canvas looks like a great product.
