### ISSUE TITLE
Accessing variable defined in initializer file from .handlebar, .jsx and .coffee files

### ISSUE THREAD

**Issue by kachroosneha** [instructure/canvas-lms#743]
I have defined my variable in initializers file as : $name = 'Abc'.

In my .html.erb files I accessed it using "#{$name}".

How can I access this variable in .handlebar, .jsx and .coffee files.

**Comment by simonista** [comment]
in application_controller.rb, add a before_filter to add it to js_env (or directly modify https://github.com/instructure/canvas-lms/blob/stable/app/controllers/application_controller.rb#L101) and then it will be available in the `ENV` hash from javascript.
