### ISSUE TITLE
Error installing nokogiri El Capitan OSX v10.11.2

### ISSUE THREAD

**Issue by vancooten** [instructure/canvas-lms#745]
I'm getting an error installing gems while installing Nokogiri (1.6.6.2.20150813143452).  Eventmachine didn't install either.

**Comment by ccutrer** [comment]
@vancooten do you have the actual errors you saw? The most common problem is you don't have Xcode and the command line tools installed (and the license accepted).

**Comment by vancooten** [comment]
No I don't have the errors, I worked around it by commenting out Nokogiri in the gemfile and installing the latest version of Nokogiri instead. For Eventmachine I ran ` bundle config build.eventmachine --with-cppflags=-I/usr/local/opt/openssl/include` then ran bundler again and it installed fine. I do have Xcode and command line tools installed with the license agreement accepted.

**Comment by simonista** [comment]
fwiw, I just ran into this as well (setting up a new machine) and I had a stray `BUNDLE_BUILD__NOKOGIRI: "--use-system-libraries"` in my global bundle config file.  Even with libxml2 and libxslt from brew this wasn't working, but removing that flag (going back to letting nokogiri use it's built-in versions of those libraries) solved it for me.
