### ISSUE TITLE
rake aborted for canvas:compile_assets

### ISSUE THREAD

**Issue by PiyushKukkar** [instructure/canvas-lms#747]
I have pasted the logs here

--> Starting: 'Making sure node_modules are up to date'
--> Finished: 'Making sure node_modules are up to date' in 11.045809279999958
--> Starting: 'compile css (including custom brands)'
no sass changes detected
--> Finished: 'compile css (including custom brands)' in 1.7820030740003858
working in 1 processes
--> Starting: 'css:styleguide'
--> creating styleguide
# writing file: app/views/info/styleguide.html.erb
--> Finished: 'css:styleguide' in 5.056762302996503
--> Starting: 'compile coffee, js 18n, and run r.js optimizer'
--> Starting: 'js:generate'
Building client app 'canvas_quizzes'
	Running 'npm install'...
npm WARN package.json canvas_quizzes@1.0.0 No repository field.
npm WARN package.json canvas_quizzes@1.0.0 No license field.
	Running 'npm run build'...
Client app 'canvas_quizzes' was built successfully.
--> Creating ember app bundles
--> Compiling React JSX
--> Pre-compiling handlebars templates
--> Generating plugin extensions
--> Pre-compiling ember handlebars templates
--> Generating plugin extensions finished in 0.3692134499979147
--> Creating ember app bundles finished in 0.6492952750013501
--> Compiling CoffeeScript with 'coffee' binary
/home/piyush/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/piyush/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/piyush/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
/home/piyush/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/piyush/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/piyush/canvas-lms/gems/canvas_i18nliner/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
--> Compiling React JSX finished in 49.23119270200186
rake aborted!
Undumpable Exception -- #<EOFError: end of file reached>
/home/piyush/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/home/piyush/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/home/piyush/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/home/piyush/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/home/piyush/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/home/piyush/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/home/piyush/.rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

node -v
v0.12.9
npm -v
2.14.9
node-gyp -v
v0.10.10

**Comment by amulgarg** [comment]
Hey @PiyushKukkar 

Try using the following commands -
````
cd gems/canvas_i18nliner
rm -rf node_modules
npm install

```

**Comment by nkokkos** [comment]
@amulgarg 
I had the same exact problem and I confirm your suggestion works !
Thanx!!

**Comment by PiyushKukkar** [comment]
Yeah... it worked for me...Thanks a lot guys...

**Comment by nathanhamilton** [comment]
This worked beautifully! Spent hours trying to figure it out. Might I suggest putting this solution in the Quick Start guide?

**Comment by i2097i** [comment]
:+1 @nathanhamilton

**Comment by ravistm** [comment]
on canvas:compile_assets - i am getting following error:

DEPRECATION WARNING: Syck is deprecated and support for serialization has been removed. ActiveRecord::Core#yaml_initialize will be removed in 4.1 which will break deserialization support with Syck. (called from require at /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77)
** Invoke canvas:compile_assets (first_time)
** Execute canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
npm WARN lifecycle canvas-lms@0.0.0~preinstall: cannot run in wd %s %s (wd=%s) canvas-lms@0.0.0 script/gem_npm install /usr/local/canvaslms/canvaslms
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
--> Finished: 'Making sure node_modules are up to date' in 13.050046369
--> Starting: 'compile css (including custom brands)'
no sass changes detected
--> Finished: 'compile css (including custom brands)' in 1.387879775
working in 1 processes
--> Starting: 'css:styleguide'
** Invoke css:styleguide (first_time)
** Execute css:styleguide
--> creating styleguide
/bin/sh: which: command not found
# writing file: app/views/info/styleguide.html.erb
--> Finished: 'css:styleguide' in 4.186309029
--> Starting: 'compile coffee, js 18n, run r.js optimizer, and webpack'
--> Starting: 'js:generate'
** Invoke js:generate (first_time)
** Execute js:generate
** Invoke js:build_client_apps (first_time)
** Execute js:build_client_apps
Building client app 'canvas_quizzes'
        Running 'npm install'...
npm WARN react@0.10.0 requires a peer of envify@~1.2.0 but none was installed.
npm WARN canvas_quizzes@1.0.0 No license field.
        Running 'npm run build'...
Client app 'canvas_quizzes' was built successfully.
--> Generating plugin extensions
** Invoke js:generate_extensions (first_time)
--> Compiling React JSX
** Invoke js:jsx (first_time)
** Execute js:jsx
--> Pre-compiling handlebars templates
** Invoke jst:compile (first_time)
** Execute js:generate_extensions
--> Generating plugin extensions finished in 0.010606297
--> Creating ember app bundles** Execute jst:compile

** Invoke js:bundle_ember_apps (first_time)
--> Pre-compiling ember handlebars templates** Execute js:bundle_ember_apps

** Invoke jst:ember (first_time)
** Execute jst:ember
--> Creating ember app bundles finished in 0.152961634
--> Compiling CoffeeScript with 'coffee' binary
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
rake aborted!
Undumpable Exception -- #<RuntimeError: SyntaxError: /usr/local/canvaslms/canvaslms/app/jsx/account_course_user_search/CoursesList.jsx: Unexpected token (19:8)
  17 |       return (
  18 |
> 19 |         ltdiv className="content-box" role='grid'>
     |         ^
  20 |           ltdiv role='row' className="grid-row border border-b pad-box-mini"gt
  21 |             ltdiv className="col-md-3"gt
  22 |               ltdiv className="grid-row"gt
>
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
[root@UKSMYS04 canvaslms]# events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)

**Comment by PiyushKukkar** [comment]
@ravistm I got the same error just now....I reran the script and cloned it again(it asks you whether to get code from git again or not)... it worked fine for me... hope this helps..

**Comment by ravistm** [comment]
@PiyushKukkar thanks, 
I was actually required to install npm completely, that was the issue.Now i am getting the below issue:
# bundle exec rake canvas:compile_assets
...
92.94% documented
API Documentation successfully generated in public/doc/api
See public/doc/api/index.html
--> Finished: 'Generate documentation [yardoc]' in 30.964070399
rake aborted!
Undumpable Exception -- #<RuntimeError: SyntaxError: /usr/local/canvaslms/canvaslms/app/jsx/account_course_user_search/CoursesList.jsx: Unexpected token (19:8)
  17 |       return (
  18 |
 19 |         div className="content-box" role='grid'
     |         
  20 |           div role='row' className="grid-row border border-b pad-box-mini"
  21 |            div className="col-md-3"
  22 |               div className="grid-row"

/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

**Comment by thomas-siimpl** [comment]
+1
