### ISSUE TITLE
Can't See a Favorite Star for a course on :hover

### ISSUE THREAD

**Issue by cycomachead** [instructure/canvas-lms#749]
See this screenshot:
<img width="1193" alt="screen shot 2016-01-19 at 1 33 27 pm" src="https://cloud.githubusercontent.com/assets/1505907/12432678/7ab457e0-beb1-11e5-836b-ab8ef3b479c0.png">

When hovering over a course to add it as a favorites, it's impossible to see the Star icon, this makes it hard to select it.

(Edit: Sorry I hit enter too soon!)

**Comment by claydiffrient** [comment]
Thanks for filing this issue @cycomachead we'll make sure to get this on our roadmap to fix it.  We'll keep you up to date here.

**Comment by billgoad** [comment]
https://github.com/instructure/canvas-lms/pull/792
