### ISSUE TITLE
Increase time limit of message displayed on the top in IE9

### ISSUE THREAD

**Issue by kachroosneha** [instructure/canvas-lms#750]
If the new user logs into the system in IE9 then the message is displayed that "Your browser does not meet the minimum requirements for...." How can we increase its time limit.

**Comment by ccutrer** [comment]
That box is controlled by https://github.com/instructure/canvas-lms/blob/stable/app/coffeescripts/jquery.rails_flash_notifications.coffee.  The timeouts appear to be hardcoded in the file (and differ depending on the source of the message).
