### ISSUE TITLE
Dinghy/Docker instructions broken.

### ISSUE THREAD

**Issue by preston** [instructure/canvas-lms#754]
The first part of doc/development_with_docker.mddoc/development_with_docker.md references installation of "dinghy" via https://github.com/codekitchen/dinghy/raw/latest/dinghy.rb , which is broken. Are these instructions still relevant? ...or is there a different authoritative document?

**Comment by claydiffrient** [comment]
@preston Thanks for filling the issue!  We should likely update the docs just to specify that installing dinghy can make things easier and point to the dinghy documentation.  If you'd like to send a PR for that we'd be happy to accept it.  Otherwise, we'll do it when we get a moment.

**Comment by simonista** [comment]
sounds like we should probably just point to https://github.com/codekitchen/dinghy#install

**Comment by preston** [comment]
Given that there are so many existing Docker projects, I'd suggest just removing it completely and pointing to one of the community projects on Docker Hub. Or, if the docker-compose.yml is intended for non-Instructure users, there's that, too :) At the moment I'm working on a fat container version for LTI testing purposes, and am happy to provide that and a documentation patch next week if that would make sense?
