### ISSUE TITLE
Box View plugin not working in Canvas

### ISSUE THREAD

**Issue by lloonngg** [instructure/canvas-lms#755]
I am trying both the Bitnami and Turnkey VMs running CanvasLMS (version 2015.09.19.18).  I have set up my developer account and View app in Box, input the API key and base url in the plugins/canvadocs page in my Canvas instance.  I am able to view jpg files which does not rely on the Box Viewer.  However, viewing pdf and pptx files does not work.  I'm getting the error report below.  Seems like my files are there and I am able to access jpg documents.   I am able to see the metadata for the pdf and pptx files but cannot render them for viewing via Box View in Canvas.  Is it a cross domain issue between http protocol on my Canvas instance vs. https api access via Box?  Any help will be appreciated.

Thanks,

Long

HTTP Error 400: {"message": "Bad request", "type": "error", "details": [{"field": "document_id", "message": "The document cannot be retrieved. The GET operation on the URL returned an error."}]}

account: TurnKey Canvas
category: Canvadocs::Error
created at: 2016-01-29 05:15:53 -0500
user: Long Phi Le
request context id: ba33b7ff-5593-49bf-ba42-0afbc60aaaf7 
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8 
HTTP_ACCEPT_ENCODING: gzip, deflate, sdch 
HTTP_HOST: 172.20.174.90 
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36 
PATH_INFO: /api/v1/canvadoc_session 
QUERY_STRING: ?blob=%7B%22user_id%22:10000000000001,%22attachment_id%22:3,%22type%22:%22canvadoc%22%7D&hmac=7f96411be791a659f44373f96a62809ee5b36946 
REMOTE_ADDR: 172.20.174.86 
REQUEST_METHOD: GET 
REQUEST_URI: http://172.20.174.90/api/v1/canvadoc_session?blob=%7B%22user_id%22:10000000000001,%22attachment_id%22:3,%22type%22:%22canvadoc%22%7D&hmac=7f96411be791a659f44373f96a62809ee5b36946 
SERVER_NAME: 172.20.174.90 
SERVER_PORT: 80 
SERVER_PROTOCOL: HTTP/1.1 
format: application/json 
hostname: canvas 
path_parameters: {:controller=>"canvadoc_sessions", :action=>"show", :format=>"json"} 
pid: 8181 
query_parameters: {"blob"=>"{\"user_id\":10000000000001,\"attachment_id\":3,\"type\":\"canvadoc\"}", "hmac"=>"7f96411be791a659f44373f96a62809ee5b36946"} 
request_parameters: {} 
response_code: 500 
type: 
        HTTP Error 400: {"message": "Bad request", "type": "error", "details": [{"field": "document_id", "message": "The document cannot be retrieved. The GET operation on the URL returned an error."}]}

```
    /var/www/canvas/lib/canvadocs.rb:123:in `api_call'
```

/var/www/canvas/lib/canvadocs.rb:79:in `session'
/var/www/canvas/app/models/canvadoc.rb:44:in`block in session_url'
/usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/usr/lib/ruby/2.1.0/timeout.rb:35:in`block in catch'
/usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
/usr/lib/ruby/2.1.0/timeout.rb:35:in`catch'
/usr/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
/var/www/canvas/lib/canvas.rb:207:in`short_circuit_timeout'
/var/www/canvas/lib/canvas.rb:186:in `timeout_protection'
/var/www/canvas/app/models/canvadoc.rb:43:in`session_url'
/var/www/canvas/app/controllers/canvadoc_sessions_controller.rb:34:in `show'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_controller/metal/implicit_render.rb:4:in`send_action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/base.rb:167:in `process_action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_controller/metal/rendering.rb:10:in`process_action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:592:in`block (2 levels) in _run__4222425818972551460__process_action__2702025642082257551__callbacks'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_11557'
/var/www/canvas/app/controllers/application_controller.rb:265:in`block in enable_request_cache'
/var/www/canvas/lib/temp_cache.rb:7:in `enable'
/var/www/canvas/app/controllers/application_controller.rb:264:in`enable_request_cache'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_11557'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:459:in`block in _run__4222425818972551460__process_action__2702025642082257551__callbacks'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_11556'
/var/www/canvas/app/controllers/application_controller.rb:258:in`set_locale'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_11556'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:458:in`_run__4222425818972551460__process_action__2702025642082257551__callbacks'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/callbacks.rb:17:in`process_action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `block in instrument'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `instrument'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:29:in`process_action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/railties/controller_runtime.rb:18:in`process_action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/base.rb:121:in `process'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:45:in`process'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiling_methods.rb:79:in `block in profile_method'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_controller/metal.rb:203:in`dispatch'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_controller/metal.rb:246:in`block in action'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:73:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:36:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/journey-1.0.4/lib/journey/router.rb:68:in`block in call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/journey-1.0.4/lib/journey/router.rb:56:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:608:in `call'
/var/www/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:61:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/etag.rb:23:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/head.rb:14:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/var/www/canvas/lib/canvas/request_throttle.rb:60:in`block in call'
/var/www/canvas/lib/canvas/request_throttle.rb:258:in `reserve_capacity'
/var/www/canvas/lib/canvas/request_throttle.rb:55:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/flash.rb:242:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in`context'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/encrypted_cookie_store-instructure-1.1.11/lib/encrypted_cookie_store.rb:47:in`call'
/var/www/canvas/app/middleware/sessions_timeout.rb:22:in `call'
/var/www/canvas/app/middleware/load_account.rb:12:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/query_cache.rb:64:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in `_run__471525868875754940__call__3993935159080238404__callbacks'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in`__run_callback'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81:in`run_callbacks'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/rack/logger.rb:32:in `call_app'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/rack/logger.rb:18:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/request_store-1.2.0/lib/request_store/middleware.rb:8:in `call'
/var/www/canvas/app/middleware/request_context_generator.rb:36:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
/var/www/canvas/app/middleware/prevent_non_multipart_parse.rb:32:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/lock.rb:15:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in`fetch'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in`call!'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiler.rb:193:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/engine.rb:484:in `call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/application.rb:231:in`call'
/var/www/canvas/vendor/bundle/ruby/2.1.0/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/lib/gems/2.1.0/gems/passenger-5.0.17/lib/phusion_passenger/rack/thread_handler_extension.rb:94:in`process_request'
/var/lib/gems/2.1.0/gems/passenger-5.0.17/lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/var/lib/gems/2.1.0/gems/passenger-5.0.17/lib/phusion_passenger/request_handler/thread_handler.rb:110:in`main_loop'
/var/lib/gems/2.1.0/gems/passenger-5.0.17/lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/var/lib/gems/2.1.0/gems/passenger-5.0.17/lib/phusion_passenger/utils.rb:112:in`block in create_thread_and_abort_on_exception'

**Comment by simonista** [comment]
Hey @lloonngg, are you still experiencing this issue?  One thing to double check is that you're hosting files s3.  If you're hosting them locally, box may not be able to download them (we send box a url to the file, and then they download it, rather than sending the file directly in the request).
