### ISSUE TITLE
Deploy Canvas LMS to Digital Ocean -  a large flood of traffic is detected

### ISSUE THREAD

**Issue by truongduyng** [instructure/canvas-lms#756]
Does anyone meet this problem? I deployed Canvas to Digital Ocean. After a few days, they have detected a large flood of traffic from our server and blocked network interface. Does Canvas have any parts that automatically send data to outside? Please help me if you have any experiences with this. Thanks

**Comment by Kulgar** [comment]
Did you opt-in to this: 

> To help our developers better serve you, Instructure would like to collect some usage data about your Canvas installation. You can change this setting at any time.

Maybe that's what made that flood?

**Comment by ccutrer** [comment]
https://github.com/instructure/canvas-lms/blob/stable/app/models/report_snapshot.rb#L82 is what gets sent to Instructure (generated by https://github.com/instructure/canvas-lms/blob/stable/lib/reporting/counts_report.rb run as a daily periodic job). The data should be far less than 1kB per day.

**Comment by Kulgar** [comment]
Hmm you're right, that shouldn't be that. Any other ideas then?

**Comment by FreedomBen** [comment]
@truongduyng this sounds to me like you might have been pwned.  If it were me, I'd nuke that droplet and rebuild.  Me shooting from the hip, make sure you've done the following (from a new, clean droplet):

1.  Deploy a strict firewall (don't forget about IPv6!)
2.  Disable password based SSH access (use public/private key)
3.  Disable root SSH access (use sudo from a regular user)
4.  Run the latest version of Canvas.  We rarely encounter security issues, but when we do we fix them right away.
5.  Don't run any unnecessary services
6.  Consider running fail2ban or something similar.  Same with tripwire.

**Comment by truongduyng** [comment]
Thanks @Kulgar @FreedomBen @Kulgar . I will try to rebuild it from a new and clean droplet with @FreedomBen  advice.
