### ISSUE TITLE
How to implement resend invitation functionality

### ISSUE THREAD

**Issue by kachroosneha** [instructure/canvas-lms#758]
I am able to see "Resend" link in People tab for a particular course. So I was trying to debug the exact code from where it has been implemented. Was able to see certain files but couldn't get the exact code from where the mails are sent. Can you please help me in this.

**Comment by ccutrer** [comment]
Messages are actually delivered in https://github.com/instructure/canvas-lms/blob/master/app/models/mailer.rb (they get there from https://github.com/instructure/canvas-lms/blob/master/app/models/message.rb from the deliver_via_email method). I'll leave it as an exercise to the reader to connect the dots through BroadcastPolicy and friends for how the message gets created.
