### ISSUE TITLE
Undumpable Exception -- #<RuntimeError: error running dress_code> - centos

### ISSUE THREAD

**Issue by thiyagarajan** [instructure/canvas-lms#761]
[root@centos-512mb-sfo1-01 canvas]# RAILS_ENV=production bundle exec rake canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
npm WARN package.json Dependency 'gulp-install' exists in both dependencies and devDependencies, using 'gulp-install@^0.6.0' from dependencies
npm WARN cannot run in wd canvas-lms@0.0.0 script/gem_npm install (wd=/home/deploy/canvas)
npm WARN unmet dependency /home/deploy/canvas/node_modules/brandable_css requires glob@'^5.0.15' but will load
npm WARN unmet dependency /home/deploy/canvas/node_modules/glob,
npm WARN unmet dependency which is version 6.0.4
npm WARN unmet dependency /home/deploy/canvas/node_modules/babel requires glob@'^5.0.5' but will load
npm WARN unmet dependency /home/deploy/canvas/node_modules/glob,
npm WARN unmet dependency which is version 6.0.4
npm WARN unmet dependency /home/deploy/canvas/node_modules/brandable_css/node_modules/node-sass requires glob@'^5.0.14' but will load
npm WARN unmet dependency /home/deploy/canvas/node_modules/glob,
npm WARN unmet dependency which is version 6.0.4
npm WARN unmet dependency /home/deploy/canvas/node_modules/babel-core/node_modules/regenerator/node_modules/commoner requires glob@'^5.0.15' but will load
npm WARN unmet dependency /home/deploy/canvas/node_modules/glob,
npm WARN unmet dependency which is version 6.0.4
--> Finished: 'Making sure node_modules are up to date' in 6.554942012007814
--> Starting: 'compile css (including custom brands)'
no sass changes detected
--> Finished: 'compile css (including custom brands)' in 2.093580036977073
working in 1 processes
--> Starting: 'css:styleguide'
--> creating styleguide
rake aborted!
Undumpable Exception -- #<RuntimeError: error running dress_code>
/usr/local/rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/usr/local/rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/usr/local/rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/usr/local/rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/usr/local/rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/usr/local/rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/usr/local/rvm/gems/ruby-2.2.1/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
[root@centos-512mb-sfo1-01 canvas]#

**Comment by Kulgar** [comment]
Hi @thiyagarajan 
Have you tried running: bin/dress_code within your Rails project?
Check your bin directory. There should be a dress_code file. 

That one disappeared for me during last update. Don't know why... I just had to readd the file there from Instructure repo: https://github.com/instructure/canvas-lms/tree/stable/bin

**Comment by sudhirrs** [comment]
In my case running sudo apt install python-pygments resolved the issue. dress_code can fail if pygments is missing.

**Comment by Kulgar** [comment]
Just another thing that you should think of (for other that would have this bug): your OS must have an UTF-8 language installed. 
I've also had a problem saying "invalid ASCII symbol..." when dress_code was running. That was because I've had no UTF-8 language installed on my OS. After installing it, dress_code was running fine.

**Comment by UniWrighte** [comment]
It's hilarious that I'm running into this problem in 2021

**Comment by damianoognissanti** [comment]
I ran into this problem today (on a redhat 7 server).

Running bin/dress_code on config/styleguide.yml showed that i had to have Python 3 installed (I had previously tried to install Python 2.7), so :

`sudo yum install python36 python36-pygments`

fixed it for me.
