### ISSUE TITLE
problem with db migration

### ISSUE THREAD

**Issue by kinezu** [instructure/canvas-lms#763]
Sup yal,

I am trying to run db:initial_setup and am getting an error when doing migrations:

Error dumping database
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:236:in `structure_dump'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/activerecord-4.0.13/lib/active_record/tasks/database_tasks.rb:143:in `structure_dump'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/activerecord-4.0.13/lib/active_record/railties/databases.rake:289:in `block (3 levels) in <top (required)>'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/activerecord-4.0.13/lib/active_record/railties/databases.rake:51:in `block (2 levels) in <top (required)>'
/Users/derek.hansen/code/personal/canvas-lms/lib/tasks/canvas.rake:225:in `call'
/Users/derek.hansen/code/personal/canvas-lms/lib/tasks/canvas.rake:225:in `each'
/Users/derek.hansen/code/personal/canvas-lms/lib/tasks/canvas.rake:225:in `block in <top (required)>'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/activerecord-4.0.13/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <top (required)>'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `call'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `each'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `block (4 levels) in shardify_task'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/lib/switchman/database_server.rb:93:in `unshackle'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:58:in `block (3 levels) in shardify_task'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/app/models/switchman/shard.rb:340:in `block (2 levels) in with_each_shard'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/app/models/switchman/shard.rb:68:in `activate'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/app/models/switchman/shard.rb:527:in `activate'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/app/models/switchman/shard.rb:338:in `block in with_each_shard'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:13:in `each'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:13:in `each'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/app/models/switchman/shard.rb:334:in `with_each_shard'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:53:in `block (2 levels) in shardify_task'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/lib/switchman/shackles.rb:22:in `activate'
/Users/derek.hansen/.gem/ruby/2.1.6/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:52:in `block in shardify_task'
/Users/derek.hansen/code/personal/canvas-lms/lib/tasks/db_load_data.rake:239:in `block (2 levels) in <top (required)>'
/Users/derek.hansen/.gem/ruby/2.1.6/bin/ruby_executable_hooks:15:in `eval'
/Users/derek.hansen/.gem/ruby/2.1.6/bin/ruby_executable_hooks:15:in `<main>'

This happens on the last migration, 20160120201216_remove_problem_fks_from_canvadocs_submissions.rb (assumed based on the fact that the last one to complete was 'ClearRailsCache').

Sorry if that has already been reported/fixed.

Also, thanks Simon for https://github.com/instructure/canvas-lms/issues/712

https://cloud.githubusercontent.com/assets/10159219/12877205/8a781d52-cdc4-11e5-8513-da6167171738.png

**Comment by ccutrer** [comment]
It's actually happening _after_ the last migration, trying to call `pg_dump` to create `db/structure.sql`. Are you sure `pg_dump` is installed, and is the correct version?

**Comment by kinezu** [comment]
I have 9.5.0 installed. When I do it, it is outputing it to the console but not creating the file.

**Comment by ccutrer** [comment]
Hmm I wonder if it's an incompatibility with the recently released 9.5.

**Comment by mnaberez** [comment]
See rails/rails#21931.

**Comment by ccutrer** [comment]
Oh hey, here it is. I knew someone was wondering about this problem, but couldn't remember where. It was fixed in https://github.com/instructure/switchman/commit/05dbd6243a0cd374ca30816f983472043aa5abde, and will be in the next stable release next week.
