### ISSUE TITLE
[Bug] deadlock; recursive locking

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#764]
Hmm, still have a similar issue than #762 with last master version (as of today): 

Refresh after editing any ruby file:

```ruby
undefined method `default_pool' for #<ActiveRecord::ConnectionAdapters::ConnectionPool:0x00000004db55e8>

Extracted source (around line #193):         
  Delayed::Backend::ActiveRecord::Job.class_eval do
    self.shard_category = :delayed_jobs
  end

  Shard.default.delayed_jobs_shard.activate!(:delayed_jobs)

Rails.root: /home/regmillet/Workspace/RailsProjects/canvas-lms

Application Trace | Framework Trace | Full Trace
config/initializers/switchman.rb:193:in `block (2 levels) in <top (required)>'
config/initializers/switchman.rb:192:in `class_eval'
config/initializers/switchman.rb:192:in `block in <top (required)>'
app/middleware/request_context_generator.rb:49:in `call'
app/middleware/prevent_non_multipart_parse.rb:32:in `call'
```

Refresh after editing routes.rb file:

```ruby
deadlock; recursive locking

Extracted source (around line #122):
  def self.columns_with_remove_dropped_columns
    @columns_with_dropped ||= self.columns_without_remove_dropped_columns.reject { |c|
      (DROPPED_COLUMNS[self.table_name] || []).include?(c.name)
    }
  end


config/initializers/dropped_columns.rb:122:in `columns_with_remove_dropped_columns'
config/initializers/dropped_columns.rb:129:in `reset_column_information_with_remove_dropped_columns'
config/initializers/switchman.rb:92:in `block (2 levels) in <top (required)>'
config/initializers/switchman.rb:90:in `class_eval'
config/initializers/switchman.rb:90:in `block in <top (required)>'
app/middleware/request_context_generator.rb:49:in `call'
app/middleware/prevent_non_multipart_parse.rb:32:in `call'
```

**Comment by Kulgar** [comment]
Ok solved first issue by deactivating delayed job (just removed the database connexion to delayed jobs in dev). Don't you use delayed jobs in development? How do you test periodic tasks in dev while developing if you don't use delayed jobs?

**Comment by ccutrer** [comment]
Removing the queue section from database.yml doesn't disable delayed_jobs, it stops using a separate database specifically for delayed jobs. Your first error is a problem with reloading that is actively being worked on (see https://github.com/instructure/switchman/pull/11). The deadlock error is from Ruby, not from Postgres, and is likely also fixed by the switchman pull request. In either case, a full restart of your web server should fix it.

**Comment by Kulgar** [comment]
Cool. So I just have to wait then... Can we let this issue opened until it is completely solved? 
Is there anything I can do to help?

**Comment by ccutrer** [comment]
Yup, that's fine. I just pushed the commit up for internal review to change the switchman initializer, so it should be fixed by tomorrow.

**Comment by Kulgar** [comment]
It seems to work fine now. Thanks :)
