### ISSUE TITLE
How is left hand menu displayed in the application

### ISSUE THREAD

**Issue by kachroosneha** [instructure/canvas-lms#765]
Where is the code to show left hand menu in the application: Home, Announcement, People, Settings etc.. How can we show people and settings tab to the observer?

Can someone please help in this?

**Comment by ccutrer** [comment]
https://github.com/instructure/canvas-lms/blob/stable/app/models/course.rb#L2323 (Course#tabs_available).

**Comment by kachroosneha** [comment]
@ccutrer How can we show people and settings tab to the observer?

**Comment by simonista** [comment]
for people, give them one of these permissions: [:read_roster, :manage_students, :manage_admin_users] or change this logic: https://github.com/instructure/canvas-lms/blob/stable/app/models/course.rb#L2411

for settings, give them :read_as_admin permission or change this logic: https://github.com/instructure/canvas-lms/blob/stable/app/models/course.rb#L2417

**Comment by kachroosneha** [comment]
@simonista I changed tabs.delete_if { |t| t[:id] == TAB_SETTINGS } unless self.grants_right?(user, opts[:session], :read_as_admin)
 to tabs.delete_if { |t| t[:id] == TAB_SETTINGS } unless !self.grants_right?(user, opts[:session], :participate_as_student) and the settings tab is visible for all except the students. But when I click on that tab using the observer role it gives permission issue. Where exactly do I need to change the permission for observer. I checked in permission role matrix table using admin login but I couldn't see any permission related to settings tab.

**Comment by ccutrer** [comment]
So just changing what's returned from tabs_available won't skip the permission check when you actually visit the page. In this case, CoursesController#settings is still checking the read_as_admin permission. Alternatively, you could modify the Course.set_policy block, adding a line that grants :read_as_admin to observers.

**Comment by kachroosneha** [comment]
I added participating_observer? in set_policy block but still the permission issue is coming.
