### ISSUE TITLE
[Question] Password grant? 

### ISSUE THREAD

**Issue by matixmatix** [instructure/canvas-lms#766]
I'd like to create a client in a form of a single page app, hook it into Canvas API and enable users to log in with their username and passwords (preferably with OAuth2 password grant - exchanging credentials for an access token). Is that possible with Canvas LMS?

**Comment by ccutrer** [comment]
As this is not an actual problem with Canvas, this question is better suited for one of the avenues in our Getting Help section of the wiki: https://github.com/instructure/canvas-lms/wiki#getting-help
