### ISSUE TITLE
ERROR: relation "delayed_jobs" does not exist LINE 5: WHERE a.attrelid = '"delayed_jobs"'::regclass ^

### ISSUE THREAD

**Issue by ricardojrsr** [instructure/canvas-lms#772]
Hi guys, 

Recently we made 2 canvas installation (a fresh install and the other one was an upgrade), release/2016-01-30.07-6061-g8d59c4b.

Everything seems to be ok, but when we look the error reports, it suggest an error with delayed_jobs database.

ERROR:  relation "delayed_jobs" does not exist
LINE 5:                WHERE a.attrelid = '"delayed_jobs"'::regclass
                                          ^

        /var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-mini-profiler-0.9.2/lib/patches/sql_patches.rb:160:in `exec'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-mini-profiler-0.9.2/lib/patches/sql_patches.rb:160:in `async_exec'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:798:in `exec_no_cache'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `block in exec_query'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/sharded_instrumenter.rb:20:in `instrument'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/active_record/abstract_adapter.rb:20:in `log'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:937:in `column_definitions'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/schema_statements.rb:187:in `columns'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/schema_cache.rb:114:in `block in prepare_default_proc'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/schema_cache.rb:56:in `yield'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/schema_cache.rb:56:in `columns'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/model_schema.rb:208:in `columns'
/var/canvas2/config/initializers/dropped_columns.rb:122:in `columns_with_remove_dropped_columns'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/model_schema.rb:217:in `columns_hash'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation/calculations.rb:365:in `column_for'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/active_record/calculations.rb:117:in `column_or_type_for'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/active_record/calculations.rb:135:in `block in grouped_calculation_options'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/active_record/calculations.rb:134:in `map'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/active_record/calculations.rb:134:in `grouped_calculation_options'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/active_record/calculations.rb:77:in `execute_grouped_calculation'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation/calculations.rb:222:in `perform_calculation'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation/calculations.rb:108:in `calculate'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-deprecated_finders-1.0.4/lib/active_record/deprecated_finders/relation.rb:84:in `calculate'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation/calculations.rb:24:in `count'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/backend/active_record.rb:190:in `tag_counts'
/var/canvas2/app/controllers/jobs_controller.rb:31:in `block (3 levels) in index'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/mime_responds.rb:191:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/mime_responds.rb:191:in `respond_to'
/var/canvas2/app/controllers/jobs_controller.rb:20:in `block in index'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/shackles.rb:22:in `activate'
/var/canvas2/app/controllers/jobs_controller.rb:19:in `index'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:189:in `process_action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:585:in `block (2 levels) in _run__882893901137266660__process_action__callbacks'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:212:in `block in _conditional_callback_around_541'
/var/canvas2/app/controllers/application_controller.rb:285:in `block in enable_request_cache'
/var/canvas2/lib/temp_cache.rb:7:in `enable'
/var/canvas2/app/controllers/application_controller.rb:284:in `enable_request_cache'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:211:in `_conditional_callback_around_541'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:424:in `block in _run__882893901137266660__process_action__callbacks'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:212:in `block in _conditional_callback_around_542'
/var/canvas2/app/controllers/application_controller.rb:278:in `set_locale'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:211:in `_conditional_callback_around_542'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:423:in `_run__882893901137266660__process_action__callbacks'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:136:in `process'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:44:in `process'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiling_methods.rb:79:in `block in profile_method'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:195:in `dispatch'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:231:in `block in action'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:50:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:71:in `block in call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `each'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:676:in `call'
/var/canvas2/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:61:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/etag.rb:23:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/conditionalget.rb:25:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/head.rb:11:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/canvas2/lib/canvas/request_throttle.rb:60:in `block in call'
/var/canvas2/lib/canvas/request_throttle.rb:258:in `reserve_capacity'
/var/canvas2/lib/canvas/request_throttle.rb:55:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/flash.rb:241:in `call'
/var/canvas2/app/middleware/request_context_session.rb:25:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/session/abstract/id.rb:225:in `context'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/session/abstract/id.rb:220:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/encrypted_cookie_store-instructure-1.1.12/lib/encrypted_cookie_store.rb:47:in `call'
/var/canvas2/app/middleware/sessions_timeout.rb:22:in `call'
/var/canvas2/app/middleware/load_account.rb:12:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/cookies.rb:486:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/query_cache.rb:36:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:373:in `_run__3201149735720521089__call__callbacks'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:38:in `call_app'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:22:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/request_store-1.3.0/lib/request_store/middleware.rb:9:in `call'
/var/canvas2/app/middleware/request_context_generator.rb:49:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/methodoverride.rb:21:in `call'
/var/canvas2/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/runtime.rb:17:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/sendfile.rb:112:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiler.rb:193:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:97:in `call'
/var/canvas2/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

**Comment by ccutrer** [comment]
This is a problem with Rails 4 that we're working on fixing. If you want to try out the fix before it makes it through the full test and review cycle at Instructure, you can see it at https://github.com/ccutrer/canvas-lms/commit/ed0816950559e521d09321eed06c8b10ac207ad7.

**Comment by ricardojrsr** [comment]
Problem solved!

Thanks.
