### ISSUE TITLE
Fingerprint not found

### ISSUE THREAD

**Issue by amulgarg** [instructure/canvas-lms#775]
Hi

We upgraded canvas to production release (Monday, Jan 4, 2016). After the upgrade, I tried running the app rails server but encountered the following error.

```
'Fingerprint not found. bundles/animate legacy_normal_contrast', '0701a16a-ba4a-47a7-a7f4-9f79f85d8e32', 'get', '2016-02-22 09:12:47.108285', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36') RETURNING "id"  [development:1 master]
```

This error occurs in	*lib/brandable_css.rb@cache_for*
````
def cache_for(bundle_path, variant)
  key = ["#{bundle_path}.scss", variant].join(CONFIG['manifest_key_seperator'])
  fingerprint = combined_checksums[key]
  raise "Fingerprint not found. #{bundle_path} #{variant}" unless fingerprint
 fingerprint
end
````

How do I fix it?

Thanks
Amul

**Comment by jenseng** [comment]
@amulgarg have you recompiled all assets? Try running `bundle exec rake canvas:compile_assets`

**Comment by amulgarg** [comment]
@jenseng Hi! I have recompiled the assets. But I still get the same error.

**Comment by wizkid686** [comment]
Hi, try this command: `bundle exec rake canvas:compile_assets RAILS_ENV=production`. It looks like your instance "thinks" its in development mode, and since you are running in production, you need to specify that in your bundle exec commands.

**Comment by simonista** [comment]
Hey @amulgarg, are you still experiencing this issue, or did you get it resolved?
