### ISSUE TITLE
File Storage bug

### ISSUE THREAD

**Issue by shubhangi-jadhav** [instructure/canvas-lms#778]
When a student submitted a file attachment as part of an assignment submission, the file size was applied to the user’s quota, instead of course quota, causing users with limited file space to exceed their quota. Additionally, any users who tried to delete a profile picture were unable to update their profile pictures. 
Can someone please assist me how to go ahead with issue. I want assignment submissions to be stored in course quota.

**Comment by jenseng** [comment]
Hi @shubhangi-jadhav, 

The course quota is intended for course materials (created by the course designer or instructor). More generally, files count toward the quota of the owner of the file. But assignment submissions are unique in that they should not actually count toward either the course or user quotas.

Can you provide a failing test that demonstrates the problem you describe? If it is in fact a bug, we can reopen this ticket. [This test](https://github.com/instructure/canvas-lms/blob/ab5f58635bfe2cd0e3f927ccb9230cc459205340/spec/models/attachment_spec.rb#L1249) should ensure submissions *don't* count toward user quotas, and [this is the code in question](https://github.com/instructure/canvas-lms/blob/ab5f58635bfe2cd0e3f927ccb9230cc459205340/app/models/attachment.rb#L583).

As for making the submissions count toward the course quota, that would be a new feature, and I suspect it would be met with considerable resistance from other customers (unless it were opt-in). You might want to float the idea on the Canvas [feature forums](https://community.canvaslms.com/community/ideas/feature-ideas) to see if it's tenable. Alternatively if you're running your own Canvas (not cloud), you might try implementing it on your own fork of Canvas.
