### ISSUE TITLE
Canvas Import with ( Common Cartridge 1.x Package imscc ) quizzes disappeared with open source ( self hosted )

### ISSUE THREAD

**Issue by omerpucit** [instructure/canvas-lms#779]
### Summary:

Hi,

I am going to attach some screen shots with the help of that you will be able to help me out.

I have installed Canvas open source on my local machine ( OS X ) as well as on ubuntu amazon server. When i am trying to import ( Common Cartridge 1.x Package imscc ) file into any course then the quizzes section is not importing to my local/self hosted canvas open source. But when same file i am importing it into Canvas Official ( https://canvas.instructure.com/courses/1010704/content_migrations ) it is importing quizzes fine.

Some screen shots:

My Local configured canvas open source behaviour.
![localhost_canvas_import_section](https://cloud.githubusercontent.com/assets/743199/13423362/3df885b6-dfbc-11e5-8356-b2bf3ac463aa.png)

![local_canvas_import_selection](https://cloud.githubusercontent.com/assets/743199/13423378/5a8ef750-dfbc-11e5-8fbb-8c3a00e775be.png)

Canvas Official images:

![canvas instructure com canvas_import_sections](https://cloud.githubusercontent.com/assets/743199/13423382/63882aa2-dfbc-11e5-8af5-70224900aade.png)
![canvas official site_ import_selection](https://cloud.githubusercontent.com/assets/743199/13423383/657fa86c-dfbc-11e5-92bb-f9dd112edb5e.png)
![canvas official site_ import_ quiz_selection](https://cloud.githubusercontent.com/assets/743199/13423385/674b2982-dfbc-11e5-972c-5572eaa836b0.png)

Canvas ( Common Cartridge 1.x Package imscc ) file:
canvas package file:
[test-ss-export.imscc.zip](https://github.com/instructure/canvas-lms/files/152498/test-ss-export.imscc.zip)

### Steps to reproduce:

 1. Please unzip canvas package file which is uploaded.
 2. Please open this url ( https://canvas.instructure.com/courses/1010704/content_migrations ) i hope i don't need to share my credentials.
 3. You can upload this unzipped file in that area using ( Common Cartridge 1.x Package ) option. Using ( Select specific content ) checkbox option.
 4. On 'Waiting for select' you will be able to see what package includes in file.
 5. Now please configured Canvas open source with branch 'stable/beta' on any server if you have or on localhost.
 6. With same steps on content migrations you can import this package again and you will see quizzes will not showing in imported file.

### Expected behavior:

It should import quizzes in open source same like 'https://canvas.instructure.com' Canvas Official site.

### Additional notes:
Is your Canvas Official site is using same code like open source. I hope so.

Thanks.

**Comment by marklocklear** [comment]
FYI. I was not able to access the page in step 2. You probably want to upload the file to some common file sharing platform like dropbox.

**Comment by omerpucit** [comment]
Thanks for your feedback, i have fixed the issue by mine self.

**Comment by omerpucit** [comment]
issue is fixed by just installing qti plugin
