### ISSUE TITLE
API: sis_course_id with slashes cause error

### ISSUE THREAD

**Issue by anagp** [instructure/canvas-lms#780]
### Summary:

When using a UTF-8 encoded sis_course_id as part of a url request, the request fails if there is any text after the id. This error only affects sis_course_id and not other ids. For example sis_user_id

This was tested in revision: "2016-01-30.17"

**These work**
sis_course_id at the end of the request
_.../api/v1/courses/sis_course_id:test%2Fcourse_

sis_user_id in any part of the request
_.../api/v1/users/sis_user_id:test%2Fuser/settings_
_.../api/v1/users/sis_user_id:test%2Fuser_

**This does not**
_.../api/v1/courses/sis_course_id:test%2Fcourse/users_

**The error report message is**:
        No route matches {:action=>"users", :controller=>"courses", :course_id=>"sis_course_id:test/course", :format=>"json"} missing required keys: [:course_id]

```
    /opt/canvas-ruby/embedded/lib/ruby/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/formatter.rb:39:in `generate'
```

As a temporary solution we are using hexadecimal:
https://canvas.krsu.edu.kg/doc/api/file.object_ids.html

**Comment by ccutrer** [comment]
This is a problem with the webserver you're using prematurely decoding the slash. Please see https://canvas.instructure.com/doc/api/file.object_ids.html for suggestions on how to fix it (for some reason your copy of the API docs is wildly out of date. It's been several years since the change).

**Comment by ccutrer** [comment]
... And now that I re-read your issue, I see that some end points are working for you, but not others. I'll see what I can do to reproduce.
