### ISSUE TITLE
LTI 2.0 ToolProxy.item endpoint missing closing brace

### ISSUE THREAD

**Issue by MartinLenord** [instructure/canvas-lms#783]
### Summary:
The LTI consumer profile generated by canvas returns the ToolProxy.item service endpoint with a missing closing brace

### Steps to reproduce:

 1. Set up a new LTI 2.0 app
 2. The LTI 2.0 consumer profile gets generated and sent to the LTI provider
 3. See https://turnitin2.instructure.com/api/lti/accounts/1/tool_consumer_profile/339b6700-e4cb-47c5-a54f-3ee0064921a9#ToolProxy.item
 4. See `json.service_offered[1].endpoint` the url is `https://turnitin2.instructure.com:443/api/lti/tool_proxy/{tool_proxy_guid`

### Expected behavior:

endpoint should be `https://turnitin2.instructure.com:443/api/lti/tool_proxy/{tool_proxy_guid}`

### Additional notes:

code location:
https://github.com/instructure/canvas-lms/blob/stable/app/models/lti/tool_consumer_profile_creator.rb#L41

**Comment by rivernate** [comment]
thanks for the bug report, this has already been fixed here: https://github.com/instructure/canvas-lms/commit/69b8bb7a0b277c82f17dcfc83e77fd6c73a89781
