### ISSUE TITLE
Broken link to IRC chat in wiki

### ISSUE THREAD

**Issue by dillon9693** [instructure/canvas-lms#787]
The 'Freenode' link in the 'Getting Help' section of the wiki currently redirects to an in development page for the Freenode website. On the Canvas dev & friends site,however, the IRC points to the correct url, which is http://webchat.freenode.net/?channels=canvas-lms&uio=d4 .

This should be corrected so those looking for help through IRC are directed to the correct location.

**Comment by ccutrer** [comment]
Thanks for pointing that out. Looks like the entire Freenode website is currently being revamped. I've updated the link to go to web chat for now.
