### ISSUE TITLE
canvas_quizzes client relies on removed npm module version

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#791]
### Summary:

The canvas_quizzes client app has a dependency on grunt-contrib-jasmine, which in turn has a dependency on [es5-shim](https://www.npmjs.com/package/es5-shim). canvas_quizzes is [shrinkwrapped](https://github.com/instructure/canvas-lms/blob/6061a744be115dd7e49ddb10fa61f70c62e4a706/client_apps/canvas_quizzes/npm-shrinkwrap.json), and the es5-shim version is [pinned at 4.0.3](https://github.com/instructure/canvas-lms/blob/6061a744be115dd7e49ddb10fa61f70c62e4a706/client_apps/canvas_quizzes/npm-shrinkwrap.json#L1147), which seems to have been removed from npmjs.org. Thus, the compile_assets rake task fails when it attempts to `npm install` in canvas_quizzes.
### Steps to reproduce:

 1. Check out canvas
 2. bundle install, npm install, etc
 3. bundle exec rake canvas:compile_assets

### Expected behavior:

Assets should compile without failure.

### Actual behavior: 

Asset compilation fails, and I am sad.

### Additional notes:

I have a build running now that removes the [npm-shrinkwrap](https://github.com/instructure/canvas-lms/blob/6061a744be115dd7e49ddb10fa61f70c62e4a706/client_apps/canvas_quizzes/npm-shrinkwrap.json) file before running compile_assets.

**Comment by yiori-s** [comment]
I had the same issue, and replaced the version of es5-ahim(4.0.3) to new version 4.0.5 in npm-shrinkwrap.json file. 
I got build successful.

**Comment by efren-oneill** [comment]
Same issue here. The source should be changed to avoid this error.

Thank you grahamb and yiori-s for pointing out the file and the fix. Updated the version of es5-shim to the latest one and now I have a working development environment.

**Comment by ccutrer** [comment]
An update for those curious - this is definitely blocking Instructure people too. The commit referenced above allows most builds to pass, but the tests for canvas_quizzes still aren't passing. We're working on that as fast as we can.

**Comment by claydiffrient** [comment]
Ooops... didn't mean to close that :)

**Comment by grahamb** [comment]
Thanks, gents!
