### ISSUE TITLE
Rich Content Service Triggers Page Errors when enabled in Production

### ISSUE THREAD

**Issue by wizkid686** [instructure/canvas-lms#795]
### Summary:
When you enable the rich content service feature flag in a production environment, page errors are triggered in several areas:

1. Account settings of the root account
2. Several pages of the site-admin account

This issue prevents the feature from being disabled through the standard UI, and you must manually edit the feature.rb file to disable the feature in order to force the pages to render normally.
### Steps to reproduce:

 1. In a production environment, activate the Rich content service feature flag
 2. Navigate to any other page in canvas, then attempt to access the root account settings page again
 3. You receive a page error and cannot access the page to disable the feature.

### Expected behavior:
Page navigation should not be impacted and the feature flag should be able to be toggled without issue.

**Comment by claydiffrient** [comment]
@wizkid686 Thanks for opening the issue.  Just so you are aware, the RCS isn't production ready at the moment, so we'd recommend against it's use at this time.  We tried to reproduce your issue with several different variations on our `master` branch to try and force the issue and were unable to do so.

A couple relevant commits are e95cf449fe1e076e5b9c43d2489e54b2471c9373 and 2999576bdc97816fe6961289a14409320bbf2adf which aren't currently on `stable` at this time.  We've seen the issue you described in the past, but we think that those commits fix issues like the one you are seeing.

If you wouldn't mind giving it a shot on the `master` branch, and seeing if it's fixed there, that would be awesome!  If it does cause an issue for you then please send us a stack trace and we'll work on figuring things out.

**Comment by wizkid686** [comment]
The fix was pushed to stable on last release, not seeing the issue anymore.
