### ISSUE TITLE
RAILS_ENV=production bundle exec rake canvas:compile_assets

### ISSUE THREAD

**Issue by josephmokenela** [instructure/canvas-lms#796]
I am installing canvas on ubuntu 14.04.4

I am getting stuck when running the following command after installing npm

RAILS_ENV=production bundle exec rake canvas:compile_assets

The error that is showing is as follows

npm ERR! fetch failed https://registry.npmjs.org/es5-shim/-/es5-shim-4.0.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/es5-shim/-/es5-shim-4.0.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/es5-shim/-/es5-shim-4.0.3.tgz
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.12
npm ERR! npm  v2.14.9
â
npm ERR! fetch failed with status code 504
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
â
npm ERR! Please include the following file with any support request:
npm ERR!     /var/canvas/client_apps/canvas_quizzes/npm-debug.log
            -------------------------------------------------------------------
            INSTALL FAILURE:

            -------------------------------------------------------------------
rake aborted!
Undumpable Exception -- #<RuntimeError: Package installation failure for client app canvas_quizzes>
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets

Thanks in advance

**Comment by claydiffrient** [comment]
@josephmokenela This problem is because a package was unpublished from the npm system.  The latest stable branch has 299eacadf4a6f56651dbe841b36b00b03b7dd0fd which fixes the error.

**Comment by josephmokenela** [comment]
Thank you @claydiffrient
