### ISSUE TITLE
API Documentation not complete Get Single Course

### ISSUE THREAD

**Issue by svrooij** [instructure/canvas-lms#798]
### Summary:
The [documentation about fetching a single course](https://canvas.instructure.com/doc/api/courses.html#method.courses.show) is missing an include parameter. 
``?include[]=public_description`` also works

### Expected behavior:
I expect the documentation to match the running code.
### Easy fix:
This [file](
https://github.com/instructure/canvas-lms/blob/master/app/controllers/courses_controller.rb#L1472) should be changed from:
```
  # @argument include[] [String, "all_courses"|"permissions"|"observed_users"]
  #   - "all_courses": Also search recently deleted courses.
  #   - "permissions": Include permissions the current user has
  #     for the course.
  #   - "observed_users": include observed users in the enrollments
  #
```
to:
```
  # @argument include[] [String, "all_courses"|"permissions"|"observed_users"|"public_description"]
  #   - "all_courses": Also search recently deleted courses.
  #   - "permissions": Include permissions the current user has
  #     for the course.
  #   - "observed_users": include observed users in the enrollments
  #   - "public_description": Show the public course description.
```
This parameter is also not specified at the List Courses call on [this](https://github.com/instructure/canvas-lms/blob/master/app/controllers/courses_controller.rb#L322) row

**Comment by simonista** [comment]
Thanks for reporting this, I'll push up a commit to add these docs shortly.

**Comment by svrooij** [comment]
Hello guys,

Thanks for this fix, but I found an other parameter that is missing.
`include[]=indexed` this fetches if the course is in the public course index.

Maybe you guys could check all the new parameters?

**Comment by simonista** [comment]
Ah, I thought I had checked all the parameters, thanks for the heads up.
