### ISSUE TITLE
Error access canvas lms instance after installation

### ISSUE THREAD

**Issue by josephmokenela** [instructure/canvas-lms#800]
I just finished installing canvas lms on digital ocean.

However when I trying to access the web application from the browser, I get the following error as depicted below in the stack-trace. 

[ 2016-03-31 00:13:27.0879 17587/7fc7b6d1f700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 05d21bbb. Please see earlier logs for details about the error.
App 17716 stdout:
App 17716 stderr:  [passenger_native_support.so] trying to compile for the current user (mmjdev) and Ruby interpreter...
App 17716 stderr:
App 17716 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 17716 stderr:
App 17716 stderr:      Warning: compilation didn't succeed. To learn why, read this file:
App 17716 stderr:      /tmp/passenger_native_support-1koj6dz.log
App 17716 stderr:  [passenger_native_support.so] not downloading because passenger wasn't installed from a release package
App 17716 stderr:  [passenger_native_support.so] will not be used (can't compile or download)
App 17716 stderr:   --> Passenger will still operate normally.
App 17716 stderr: DEPRECATION WARNING: Syck is deprecated and support for serialization has been removed. ActiveRecord::Core#yaml_initialize will be removed in 4.1 which will break deserialization support with Syck. (called from require at /var/lib/gems/2.1.0/gems/bundler-1.8.0/lib/bundler/runtime.rb:76)
App 17716 stderr:
App 17716 stdout:
[ 2016-03-31 00:13:42.5704 17587/7fc7bdb5a700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/canvas: An error occurred while starting up the preloader.
  Error ID: 90a67120
  Error details saved to: /tmp/passenger-error-R6JVtc.html
  Message from application: syntax error on line 14, col 0: `test:' (ArgumentError)
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/syck-1.0.4/lib/syck.rb:188:in `load'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/syck-1.0.4/lib/syck.rb:188:in `parse'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:173:in `load'
  /var/canvas/config/application.rb:146:in `load'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb:29:in `safe_load'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb:12:in `load_with_options'
  /var/canvas/lib/config_file.rb:45:in `load'
  /var/canvas/lib/canvas.rb:102:in `block in cache_stores'
  /var/canvas/lib/canvas.rb:73:in `each'
  /var/canvas/lib/canvas.rb:73:in `cache_stores'
  /var/canvas/config/environments/cache_store.rb:11:in `block in <top (required)>'
  /var/canvas/config/environments/production.rb:18:in `eval'
  /var/canvas/config/environments/production.rb:18:in `block in <top (required)>'
  /var/canvas/config/environment.rb:3:in `block in environment_configuration'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:24:in `class_eval'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:24:in `configure'
  /var/canvas/config/environment.rb:2:in `environment_configuration'
  /var/canvas/config/environments/production.rb:1:in `<top (required)>'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:591:in `block (2 levels) in <class:Engine>'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:590:in `each'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:590:in `block in <class:Engine>'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `instance_exec'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
  /usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:44:in `each'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/lib/ruby/2.1.0/tsort.rb:411:in `call'
  /usr/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
  /usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
  /usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
  /usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
  /usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:215:in `initialize!'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /var/canvas/config/environment.rb:11:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/builder.rb:55:in `instance_eval'
  /var/canvas/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

Thanks in advance,

Kind Regards,
Joseph

**Comment by simonista** [comment]
Kind of a hard error to read, but the import part is `Message from application: syntax error on line 14, col 0: test:' (ArgumentError)`, and then if you trace back in the backtrace you get to this line: https://github.com/instructure/canvas-lms/blob/stable/lib/canvas.rb#L102.  Which means you've got a syntax error in your config/redis.yml file
