### ISSUE TITLE
All CSS disappers when trying to preview a theme change in the Theme Editor

### ISSUE THREAD

**Issue by jcingraham** [instructure/canvas-lms#802]
### Summary:

I am trying to edit a theme in the new UI, but if I change anything and go to preview image it will either say "An error occurred trying to generate this theme, please try again." or it will go through, but all stylesheets are missing (just a white background/times new roman font etc.)
### Steps to reproduce:
1. Edit a theme
2. Click Preview Changes
### Additional notes:

I get these errors logged in the db.

Permission denied @ dir_s_mkdir - app/stylesheets/brandable_css_brands/a646ae0c0f04814dcfbf57aec7ff04b7

No route matches [GET] "/dist/brandable_css/a646ae0c0f04814dcfbf57aec7ff04b7/new_styles_normal_contrast/bundles/common-ca18df7562.css"

**Comment by shawniverson** [comment]
Not a bug but a permissions problem.

I'm still working through this, but so far...

Your Phusion Passenger canvas user must have access to brandable_css_brands and write access to _brandable_variables_defaults_autogenterated.scss in app/stylesheets.

**Comment by simonista** [comment]
Hey @shawniverson, sorry for not responding sooner, did you get this squared away?

**Comment by jcingraham** [comment]
No, I still have the issue. I put it aside for a bit, but would love a solution.

**Comment by simonista** [comment]
How far did you get in debugging?  Seems like it'd be worth looking at the delayed_job logs after you hit preview.  It might also be worth watching public/dist/brandable_css to see if "something" is getting generated, and maybe the hash is just not matching somehow?
