### ISSUE TITLE
Asset compilation fails in the compress phase

### ISSUE THREAD

**Issue by judell** [instructure/canvas-lms#806]
### Steps to reproduce:

$GEM_HOME/bin/bundle exec rake canvas:compile_assets

### Additional notes:

This is a 2GB Digital Ocean droplet, maybe too small?

Console output:

--> Compressing JavaScript with UglifyJS
rake aborted!
Undumpable Exception -- #<RuntimeError: Error running js:build:

> canvas-lms@0.0.0 compress /home/jon/canvas
> node script/compress.js

an error occured: compute process (30199) dies with code: null
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at ComputeCluster.emit (events.js:87:13)
    at ChildProcess.<anonymous> (/home/jon/canvas/node_modules/compute-cluster/lib/compute-cluster.js:58:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1078:12)

npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "compress"
npm ERR! node v0.12.13

Debug log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compress' ]
2 info using npm@2.15.0
3 info using node@v0.12.13
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'precompress', 'compress', 'postcompress' ]
6 info precompress canvas-lms@0.0.0
7 info compress canvas-lms@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info canvas-lms@0.0.0 Failed to exec compress script
10 verbose stack Error: canvas-lms@0.0.0 compress: `node script/compress.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1019:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
11 verbose pkgid canvas-lms@0.0.0
12 verbose cwd /home/jon/canvas
13 error Linux 3.13.0-43-generic
14 error argv "/usr/bin/node" "/usr/bin/npm" "run" "compress"
15 error node v0.12.13
16 error npm  v2.15.0
17 error code ELIFECYCLE
18 error canvas-lms@0.0.0 compress: `node script/compress.js`
18 error Exit status 1
19 error Failed at the canvas-lms@0.0.0 compress script 'node script/compress.js'.
19 error This is most likely a problem with the canvas-lms package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node script/compress.js
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs canvas-lms
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls canvas-lms
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by dgynn** [comment]
Compiling assets does take a lot of memory. You can try running that task with environment variables to disable parallel builds and to skip the UglifyJS step with...
```
CANVAS_BUILD_CONCURRENCY=1 JS_BUILD_NO_UGLIFY=true bundle exec rake --trace canvas:compile_assets[false,false]
```
The `[false,false]` rake params skip API docs generation and syntax checking too.

**Comment by judell** [comment]
That did the trick. Thanks very much!

**Comment by ravistm** [comment]
It worked almost, now i can see the login page but style sheet not showing and getting following error:
====================================
--> Compiling CoffeeScript with 'coffee' binary
rake aborted!
Undumpable Exception -- #<RuntimeError: SyntaxError: /usr/local/canvaslms/canvaslms/app/jsx/account_course_user_search/CoursesList.jsx: Unexpected token (19:8)
  17 |       return (
  18 |
> 19 |         ltdiv className="content-box" role='grid'gt
     |         ^
  20 |           ltdiv role='row' className="grid-row border border-b pad-box-mini"gt
  21 |             ltdiv className="col-md-3"gt
  22 |               ltdiv className="grid-row"gt
>
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)

**Comment by gebetix** [comment]
+1
