### ISSUE TITLE
RoutingError problem

### ISSUE THREAD

**Issue by Vic-Song** [instructure/canvas-lms#808]
### Summary:
Hi, I have download and deploy the canvas files on my local server by following the quickstart instructions, but when I started the server and tried to log in through port 3000, I just found something is wrong with the layout (logging in part works normally)and when I check the server log it shows the error information below
  ActionController::RoutingError (No route matches [GET] "/dist/images/canvas/header_canvas_logo-9151504473.png"):
  app/middleware/request_context_generator.rb:49:in `call'
  app/middleware/prevent_non_multipart_parse.rb:32:in `call'
I can't see the files or directory naming /dist/... on my server, did I miss some files or something else? thanks

**Comment by ccutrer** [comment]
Did you run `bundle exec rake canvas:compile_assets`? That should generate the files in `public/dist/`

**Comment by Vic-Song** [comment]
@ccutrer yes I did run it but it did not work and showing the message: Undumpable Exception -- #<RuntimeError: error running dress_code> . Then I found the same problem which emerged before in the issue section and tried to run bin/dress_code, then it came with:  Bundler version 1.8.0 is required; you're currently running 1.3.5. Maybe try `gem install bundler -v 1.11.2`, or `gem uninstall bundler -v 1.3.5`. And now I am in the loop of installing and uninstalling gem bundler again and again with or without whichever version... and the problem still there...

**Comment by ravistm** [comment]
Hi Guys,

I have some errors which i am not able to fix while installing canvas lms, please help
Below is the error while doing
#bundle exec rake canvas:compile_assets
92.94% documented
API Documentation successfully generated in public/doc/api
See public/doc/api/index.html
--> Finished: 'Generate documentation [yardoc]' in 30.964070399
rake aborted!
Undumpable Exception -- #<RuntimeError: SyntaxError: /usr/local/canvaslms/canvaslms/app/jsx/account_course_user_search/CoursesList.jsx: Unexpected token (19:8)
  17 |       return (
  18 |
> 19 |         <div className="content-box" role='grid'>
     |         ^
  20 |           <div role='row' className="grid-row border border-b pad-box-mini">
  21 |             <div className="col-md-3">
  22 |               <div className="grid-row">
>
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/usr/local/canvaslms/canvaslms/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

**Comment by claydiffrient** [comment]
@ravistm That's a separate issue, #817 to be precise.  The solution for now at least is to do a `npm install babel@5`

**Comment by ravistm** [comment]
@claydiffrient Thanks for sharing.
