### ISSUE TITLE
Can't submit file uploads in firefox

### ISSUE THREAD

**Issue by benwaffle** [instructure/canvas-lms#813]
### Summary:

The workaround is to upload, refresh, then choose from your uploaded files folder
### Steps to reproduce:
1. go to an instance on instructure.com using firefox
2. try to upload a submission to an assignment

**Comment by claydiffrient** [comment]
@benwaffle I wasn't able to reproduce this problem.  I followed the reproduction steps as you've outlined.  Am I perhaps missing something?

**Comment by benwaffle** [comment]
Maybe it's because I'm using firefox developer edition?

**Comment by geekx1** [comment]
unable to upload files to courses?i met the same problem.

**Comment by illegalnumbers** [comment]
Were you using Developer Edition as well?

**Comment by benwaffle** [comment]
Seems to be working ok now
