### ISSUE TITLE
Warnings in log when previewing changes in the Theme Editor

### ISSUE THREAD

**Issue by bermudezjd** [instructure/canvas-lms#816]
### Summary:

With the new UI enabled and the Theme Editor loaded, previewing changes results in a `WARNING` message being displayed in the production log file.  Looks something like:

```
WARNING: Can't mass-assign protected attributes for BrandConfig: parent_md5
    lib/canvas_logger.rb:19:in `call'
    lib/canvas_logger.rb:19:in `add'
    config/initializers/strong_parameters.rb:40:in `sanitize_for_mass_assignment'
    app/models/brand_config.rb:37:in `for'
    app/controllers/brand_configs_controller.rb:79:in `create'
    app/controllers/application_controller.rb:287:in `block in enable_request_cache'
    lib/temp_cache.rb:7:in `enable'
    app/controllers/application_controller.rb:286:in `enable_request_cache'
    app/controllers/application_controller.rb:280:in `set_locale'
    app/middleware/request_throttle.rb:59:in `block in call'
    app/middleware/request_throttle.rb:257:in `reserve_capacity'
    app/middleware/request_throttle.rb:54:in `call'
    app/middleware/request_context_session.rb:25:in `call'
    app/middleware/sessions_timeout.rb:22:in `call'
    app/middleware/load_account.rb:12:in `call'
    app/middleware/request_context_generator.rb:49:in `call'
    app/middleware/prevent_non_multipart_parse.rb:32:in `call'
```
### Steps to reproduce:
1.  Enable the new UI
2.  Bring up the Theme Editor for an account
3.  Go into any section and update a style.
4.  Click the "Preview Your Changes" modal button that appears.
### Expected behavior:

No warnings should appear in the production.log file.
### Additional notes:

Running the open-source version of Canvas LMS on a single Ubuntu 14.04 server, with the `release/2016-04-02.22` code checked out.

**Comment by bespaloff** [comment]
I have got the same issue plus theme editor doesn't work. New brandable css's are not creating.

**Comment by buffcleb** [comment]
running into this same issue... can't use the preview your changes button...

**Comment by manish310794** [comment]
Does it get stuck for you people as well? For me it makes repeated calls to 
`Started GET /api/v1/progress/`
But it doesn't generate the brandable css.

**Comment by buffcleb** [comment]
Mine loops on /api/v1/progress/59

the response is 

{"id":"59","context_id":"5","context_type":"User","user_id":"5","tag":"brand_config_save_and_sync_to_s3","completion":0,"workflow_state":"queued","created_at":"2016-05-31T13:24:34Z","updated_at":"2016-05-31T13:24:34Z","message":null,"url":"http://XXXXXX/api/v1/progress/59"}

I'm not using s3...

looking in the error reports I get this : 

category: NoMethodError
created at: 2016-05-31 09:28:29 -0400

hostname: XXXXXXXXX 
pid: 29435 
process_type: BackgroundJob 
worker_name: XXXXXXX:29435 
        undefined method `message=' for nil:NilClass

        /app/itx/canvas/app/models/progress.rb:102:in `on_permanent_failure'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/backend/base.rb:182:in `permanent_failure'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/backend/base.rb:167:in `reschedule'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:174:in `handle_failed_job'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:152:in `block in perform'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:63:in `call'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:63:in `block in initialize'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:68:in `call'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:68:in `execute'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:41:in `run_callbacks'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:151:in `rescue in perform'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:132:in `perform'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:108:in `block in run'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:203:in `configure_for_job'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:107:in `run'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:84:in `block in start'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:83:in `loop'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:83:in `start'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:161:in `block in spawn_worker'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:172:in `block in fork_with_reconnects'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:169:in `fork'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:169:in `fork_with_reconnects'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:160:in `spawn_worker'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:215:in `block in join'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:202:in `loop'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:202:in `join'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:110:in `start'
/app/itx/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:57:in `run'
/app/itx/canvas/script/delayed_job:11:in `<main>'

**Comment by Validateme-DevopsQainfotech** [comment]
Any update on previewing changes in the Theme Editor
