### ISSUE TITLE
bundle exec rake js:jsx failed

### ISSUE THREAD

**Issue by loganfreeman** [instructure/canvas-lms#817]
### Summary:
`bundle exec rake js:jsx` failed
### Steps to reproduce:

 1.
`RAILS_ENV=development bundle exec rake js:jsx`
 2.
 3.

### Expected behavior:
```
DEPRECATION WARNING: Syck is deprecated and support for serialization has been removed. ActiveRecord::Core#yaml_initialize will be removed in 4.1 which will break deserialization support with Syck. (called from <top (required)> at /Users/xxx/projects/ruby/canvas-lms/config/application.rb:19)
rake aborted!
SyntaxError: /Users/xxx/projects/ruby/canvas-lms/app/jsx/account_course_user_search/CoursesList.jsx: Unexpected token (19:8)
  17 |       return (
  18 |
> 19 |         <div className="content-box" role='grid'>
     |         ^
  20 |           <div role='row' className="grid-row border border-b pad-box-mini">
  21 |             <div className="col-md-3">
  22 |               <div className="grid-row">
```
### Additional notes:
```
node_modules/.bin/babel --version
6.7.7 (babel-core 6.7.7)
```

**Comment by loganfreeman** [comment]
```
npm shrinkwrap
```

**Comment by claydiffrient** [comment]
@loganfreeman Thanks for the bug report.  I've noticed this happening with several other people, but I haven't successfully reproduced it.  This report definitely contained more information than the others that I have seen, so I definitely appreciate that.  

It's odd that you would get Babel v6 installed when we specify `"babel": "^5.8.23"` in our `package.json`.

The steps to try and reproduce have been as follows with node v0.12.7 and npm v2.15.1:

1. `rm -rf node_modules/`
2. `npm cache clear`
3. `npm install`
4. `bundle exec rake js:jsx`

And it successfully completes.  Is there anything special about your environment that might account for the difference?

**Comment by loganfreeman** [comment]
I remove the node_modules directory, reinstall bable with the exact version 5.8.23. then it works.

I guess when running 'npm install', it chooses to install a different version. 

why it didn't obey the caret range when running `npm install`, I don't know. 

But I think you can use `npm shrinkwrap` to fix the version

**Comment by claydiffrient** [comment]
@loganfreeman Thanks for the additional information.  I'm so confused by the caret range problem.  In any case, we've been wanting to move up to Babel 6 for a bit now anyways.  I've got a commit that does that going through our internal testing and review process now.  

We're also looking into shrinkwrapping the dev dependencies but that leads to some complications around native extensions for developers on Mac vs. Linux and what not.  Hopefully we'll have a solution to that soon.

**Comment by claydiffrient** [comment]
@loganfreeman I've seen this problem rear it's head a few more times now.  I'm still not sure why, but the workaround for now is to manually do `npm install babel@5` which explicitly install Babel 5 rather than Babel 6.

The commit upgrading to Babel 6 itself has run into some problems, but we still anticipate getting a fix out.
