### ISSUE TITLE
error with "javascripts/locale_converter.js"

### ISSUE THREAD

**Issue by Vic-Song** [instructure/canvas-lms#821]
### Summary:

Hello guys, I just finished the compile_assets part of canvas, but when the server starts, I log in to find that some functions are just not working well, like settings=>edit settings, and the logfile shows error information below:
ActionController::RoutingError (No route matches [GET] "/javascripts/locale_converter.js"):
  app/middleware/request_context_generator.rb:49:in `call'
  app/middleware/prevent_non_multipart_parse.rb:32:in`call'

I wonder where does it go wrong and how can I solve the problem? Thanks in advance.

**Comment by ccutrer** [comment]
Are you sure you're not loading old javascript in your browser somehow? locale_converter.js does not exist in the latest stable version of Canvas (or master), and the javascript should not be trying to load it.

**Comment by Vic-Song** [comment]
@ccutrer Sure I am! Thank you so much! My system is Ubuntu 14.04 LTS and the error occurs when I use Chromium but it works well with Firefox so it should be something wrong with the browser, thanks again~~
