### ISSUE TITLE
API: enrollment_type parameter for favorites/courses

### ISSUE THREAD

**Issue by dahlbyk** [instructure/canvas-lms#823]
### Summary:

[`/api/v1/users/self/favorites/courses`](https://canvas.instructure.com/doc/api/favorites.html#method.favorites.list_favorite_courses) cannot be filtered by `enrollment_type`.
### Expected behavior:

`enrollment_type` parameter is accepted, matching behavior of [`/api/v1/courses`](https://canvas.instructure.com/doc/api/courses.html#method.courses.index).

`enrollment_role_id` should probably work, too.
### Additional notes:

If you would accept this addition, I would be glad to submit a PR. I believe the fix largely consists of implementing [this filter from `CoursesController`](https://github.com/instructure/canvas-lms/blob/3d4c5681118783c8cbce58b90af1d70177786f6f/app/controllers/courses_controller.rb#L2444-L2449) in [`FavoritesController#list_favorite_courses`](https://github.com/instructure/canvas-lms/blob/3d4c5681118783c8cbce58b90af1d70177786f6f/app/controllers/favorites_controller.rb#L66).

**Comment by ccutrer** [comment]
I'm not opposed to this change.

**Comment by javawizard** [comment]
I'm making some changes in the general area right now that will probably conflict with a PR for this issue. I'll post back once they're on `master`. I don't see why we wouldn't accept a PR after that.
