### ISSUE TITLE
error installing gems

### ISSUE THREAD

**Issue by kinsomicrote** [instructure/canvas-lms#825]
I get this error when I try to install gems:

```
NoMethodError: undefined method `spec' for nil:NilClass
Did you mean?  inspect
An error occurred while installing academic_benchmark
(1.1.0), and Bundler cannot continue.
Make sure that `gem install academic_benchmark -v
'1.1.0'` succeeds before bundling.
```

**Comment by illegalnumbers** [comment]
Have you tried running that command? What error do you get when installing academic_benchmark alone?

**Comment by kinsomicrote** [comment]
It gives me this:

```
ERROR:  Could not find a valid gem 'academic_benchmark' (>= 0) in any repository
ERROR:  Possible alternatives: academic_benchmarks, sidekiq-benchmark, adlint-benchmark, rake-benchmark, rspec-benchmark
```

**Comment by FreedomBen** [comment]
academic_benchmark (no ending `s`) is an internal gem built from the `gems` subdirectory.  a bare `gem install academic_benchmark` won't work therefeore, since it isn't published.  I believe the error message is a red herring and only points to `academic_benchmark` due to alphabetical order.  Sorry to not have the full answer, but hopefully that helps narrow it down better.

**Comment by kinsomicrote** [comment]
It warns of an undefined method `spec` method, one I am having a hard time locating.

https://github.com/instructure/canvas-lms/tree/stable/gems/plugins/academic_benchmark

**Comment by kinsomicrote** [comment]
This is not just an issue with `academic_benmark`, I removed `academic_benchmark` folder and tried installing the gems. This is the error I got.

```
NoMethodError: undefined method `spec' for nil:NilClass
Did you mean?  inspect
An error occurred while installing account_reports
(1.1.0), and Bundler cannot continue.
Make sure that `gem install account_reports -v '1.1.0'`
succeeds before bundling.
```

**Comment by kinsomicrote** [comment]
Issue resolved.
The error was produced because I was using `bundler 1.8.0`, I switched to `1.11.2` and the gems installed.
