### ISSUE TITLE
explanation needed for documentation

### ISSUE THREAD

**Issue by kinsomicrote** [instructure/canvas-lms#826]
Hello, I need a little explanation on this part of the documentation:

```
sysadmin@appserver:~$ sudo mkdir -p /var/canvas
sysadmin@appserver:~$ sudo chown -R sysadmin /var/canvas
sysadmin@appserver:~$ cd canvas
sysadmin@appserver:~/canvas$ ls
app     db   Gemfile  log     Rakefile  spec  tmp
config  doc  lib      public  script    test  vendor
sysadmin@appserver:~/canvas$ sudo cp -av * /var/canvas
sysadmin@appserver:~/canvas$ cd /var/canvas
sysadmin@appserver:/var/canvas$ ls
app     db   Gemfile  log     Rakefile  spec  tmp
config  doc  lib      public  script    test  vendor
sysadmin@appserver:/var/canvas$
```

First the folder I got from cloning the repo involves some files and folders not listed in the above code. Example: client_apps, frontend_build etc. When I run the command to copy the supposed rails application into another folder, all these files get copied too. I tried copying only the files and folders mentioned in the code above and the gems needs to work with the application could not be installed.
What could I be doing wrong?

**Comment by manish310794** [comment]
The above commands create for you a new directory structure with appropriate user permissions. These steps are optional. Just ensure that the directory containing your canvas code has appropriate permissions.
As for the copy command, you need to copy everything that is there inside cloned repository; not just the files that are shown by the `ls` command.

**Comment by simonista** [comment]
@manish310794 is right, that is just an example, taken from when there were fewer top-level files/folders, but you'll want to copy everything, like the commands show.
