### ISSUE TITLE
About locale

### ISSUE THREAD

**Issue by Vic-Song** [instructure/canvas-lms#831]
### Summary:
Hi guys, I have installed the canvaslms under the instruction of quick start, when I started the server and logged in my account I tried to change the language of the system through Settings >>Edit Settings>>language, I chose my native language of Chinese Simplified, and then Update Settings, but it seems not working and even I restart the server and re-compile the assets, it still shows in English, what should I do to figure the problem out? Thanks in advance!

**Comment by simonista** [comment]
Hi @Vic-Song, check out this section of the wiki, it should explain the issue: https://github.com/instructure/canvas-lms/wiki/I18n#local-localization
