### ISSUE TITLE
[Bug] URLs with accents are not considered as valid url 

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#836]
### Summary:

Sometimes our students submit urls with accents as submission for online url assignment type. Canvas just sends them a generic error "Assignment failed to submit". 
### Steps to reproduce:

(Tested with last master version)
1. Create an assignment, select online as submission type and "website url". Publish it
2. Use the student view, submit the assignment with a url containing accent: https://www.example.com/url-déjà-vu
3. The submission shouldn't be saved and you should see the generic error message. 
### Expected behavior:

This should not happen as we can't control what students submit as online url and we can't ask them to encode their urls before submitting. Canvas should encode url before validating it. 
### Additional notes:

I have found that urls are validated through this function: validate_url which can be found here [gems/canvas_http/lib/canvas_http.rb](https://github.com/instructure/canvas-lms/blob/master/gems/canvas_http/lib/canvas_http.rb#L80)

As a quick fix for our own Canvas I added this: `value = URI.encode(value)` line 83, before `uri = URI.parse(value)`. Is it a good solution? Can I PR it? 

Thanks! :)

**Comment by ccutrer** [comment]
Naively encoding a full URL is not a good solution. For example, if I encode https://somesite.com/page?stuff=stuff&, the ampersand would get encoded, but it would be impossible to know if the & was meant to be a separator between query string arguments, or a literal &.

That said, I don't see any problems with automatically encoding any characters that are never allowed in any part of a URL (such as accented characters).

**Comment by Kulgar** [comment]
You are right, I did not think about the "&"... 

So what would you suggest? A specific little function that encode any unallowed characters in the url?

**Comment by ccutrer** [comment]
That constant comes from section 2.2 of https://www.ietf.org/rfc/rfc2396.txt. Looking at the method in more detail, escape by default escapes UNSAFE characters, which is constructed as anything that's _not_ UNRESERVED or RESERVED (i.e. invalid URI characters). Notably, this leaves out ESCAPED. 

This is a problem, because:
```
URI.escape('https://somesite.com/page?stuff=stuff&%20')
=> "https://somesite.com/page?stuff=stuff&%2520"
```

The percent got double escaped.

Ideally you want to pass a regex to escape that is `!(RESERVED | UNRESERVED | ESCAPED)`. Unfortunately, I don't know how to easily do this. You can do `Regexp.union("[#{URI::Parser::PATTERN::RESERVED}]", "[#{URI::Parser::PATTERN::UNRESERVED}]", URI::Parser::PATTERN::ESCAPED)`, but that matches all valid sequences in a URI, not invalid ones that `URI.escape` is expecting. Passing `/[^%#{URI::Parser::PATTERN::RESERVED}#{URI::Parser::PATTERN::UNRESERVED}]/` would be sufficient (notice the literal %). It won't escape invalid percent characters (ones not used to represent an escape sequence), but should be sufficient. If you want to go for the ideal solution, you'll have to figure out how to do the proper negative lookahead assertion.

As for specs - gems/canvas_http/spec/canvas_http_spec.rb is the proper location.

**Comment by Kulgar** [comment]
Then maybe, couldn't we decode it first and then rencode it? 
```ruby
URI.encode(URI.decode('https://somesite.com/page?stuff=stuff&%20'))
 => "https://somesite.com/page?stuff=stuff&%20"

# And:
URI.encode(URI.decode('https://somesite.com/page?stuff=stuff&%20&accents=é'))
 => "https://somesite.com/page?stuff=stuff&%20&accents=%C3%A9"
```

Would you see a problem solving this that way?

**Comment by ccutrer** [comment]
Yes:

```
irb(main):003:0> URI.encode(URI.decode('http://example.com/a%2fb'))
=> "http://example.com/a/b"
```

The slash that was previously percent encoded (so should be interpreted as a single path component "a/b" was decoded and not re-encoded, thus destroying the meaning of the original URI.

**Comment by Kulgar** [comment]
And do you see any problems with any other characters? Because it may be simpler to just ignore %2fb in the decode function rather than targeting all characters that should be encoded in the encode function, don't you think? 

I'll also try to ask on stackoverflow, maybe some people will have a better idea. :)

**Comment by ccutrer** [comment]
Yes, pretty much any reserved character will have problems:

```
irb(main):002:0> URI.encode(URI.decode('https://example.com/a%3fb'))
=> "https://example.com/a?b
```

Doing a direct URI.decode is an absolute non-starter. You need to just do an encode of completely invalid URI characters, as previously discussed (either naively, never encoding %s, or more intelligently, only encoding %s that don't form a valid escape sequence).

**Comment by Kulgar** [comment]
Someone actually offered a solution on stackoverflow: 

> URI.escape appears to work the way you want in all cases except when characters are already encoded. With that in mind we can take the result of URI.encode and use String#gsub to "un-encode" only those characters.

> The below regular expression looks for %25 (an encoded %) followed by two hex digits, turning e.g. %252f back into %2f:

```ruby
require "uri"

DOUBLE_ESCAPED_EXPR = /%25([0-9a-f]{2})/i

def escape_uri(uri)
  URI.encode(uri).gsub(DOUBLE_ESCAPED_EXPR, '%\1')
end

puts escape_uri("https://www.example.com/url-déjà-vu")
# => https://www.example.com/url-d%C3%A9j%C3%A0-vu

puts escape_uri("https://somesite.com/page?stuff=stuff&%20")
# => https://somesite.com/page?stuff=stuff&%20

puts escape_uri("http://example.com/a%2fb")
# => http://example.com/a%2fb
```

I don't see any drawbacks... Do you?

**Comment by ccutrer** [comment]
Yes, I am absolutely opposed to purposely over-encoding something just to munge it later. In this case I can't find a counter-example, but taking an approach like this is very prone to errors (as you saw in our previous conversations where I was easily able to come up with counter examples that changed the meaning of the URL). Just do what you're trying to do (escape completely invalid URI characters), and don't try to hack around some funny thing (over-encode and then decode, or decode then encode).

**Comment by Kulgar** [comment]
You are right. I also do have the feeling that one day it may causes problems. Ok, I'll go along with your initial proposal. :)
