### ISSUE TITLE
"What-If" grades cannot be checked if teacher is "working on grading."

### ISSUE THREAD

**Issue by patthekenny** [instructure/canvas-lms#840]
### Summary:

If there is an assignment where a teacher is currently grading, than a student won't be able to use the "what-if" grade feature. Not sure if this is a bug or an option, as I am not familiar with the code base, but figured it was worth reporting.
### Steps to reproduce:
1. Go to "grades" tab of any class.
2. Attempt to view "what-if" grade for an assignment that is flagged as "being graded."
### Expected behavior:

What-If grade shows in the top right corner of the page.
### Additional notes:

N/A.

**Comment by VagishVela** [comment]
It also is a problem when the student has taken a quiz that has parts which need to be manually graded, then it shows the 'currently grading' thing and this happens.
