### ISSUE TITLE
API: Calculated Question Error Margin

### ISSUE THREAD

**Issue by dahlbyk** [instructure/canvas-lms#844]
### Summary:

Calculated question answers can allow a margin of error, but this value is not exposed in either [`QuizQuestion`](https://canvas.instructure.com/doc/api/quiz_questions.html#QuizQuestion) or [`Answer`](https://canvas.instructure.com/doc/api/quiz_questions.html#Answer).
### Steps to reproduce:
1. Create a Formula Question
2. Generate Possible Solutions using a nonzero error margin
3. Observe the margin of error, which persists through Save
   <img width="460" alt="firefox_2016-06-13_23-20-41" src="https://cloud.githubusercontent.com/assets/133987/16031136/8f6de172-31bd-11e6-93fc-4fef9231b70f.png">
### Expected behavior:

API exposes this value, possibly using the existing `Answer.margin` key that is used with "numerical questions of type 'exact_answer'."
### Additional notes:

I know the API is still in beta, but this is the only completely missing data point I've noticed so far.

Other [`QuizQuestion`](https://canvas.instructure.com/doc/api/quiz_questions.html#QuizQuestion) documentation gaps I noticed (mostly self-explanatory), of which you're probably aware, but just to confirm...
- `quiz_group_id`
- `assessment_question_id` (perhaps not self explantary, i.e. why `null` for `question_type: text_only_question`?)
- `*_comments_html`
- `variables`, `formulas`
- `matches`, `matching_answer_incorrect_matches`

**Comment by dahlbyk** [comment]
> `assessment_question_id` (perhaps not self explantary, i.e. why `null` for `question_type: text_only_question`?)

Another seemingly related quirk: questions of type `text_only_question` do not appear to be included in `question_count`, causing a mismatch with the record count returned from `.../quizzes/:quiz_id/questions`.

**Comment by ryanmt** [comment]
Hey @dahlbyk, It sounds like we'll need to open a ticket to add that to the Answer endpoint.  We do accept pull requests. 😄 

Thank you for noting the documentation weaknesses, I'll also open a ticket internally for that. 

`text_only_question` is what we call the spacers from the UI as we store them, as such, they aren't really questions.  They don't count in the question counts, nor do they reference `assessment_question_id` as you can't put them in question banks.

**Comment by dahlbyk** [comment]
> It sounds like we'll need to open a ticket to add that to the Answer endpoint. We do accept pull requests.

This isn't blocking me, more just making sure you're aware of the gap. Is there a better place for me to report such findings?

If it does end up a blocker, you just might be getting a PR. :sunglasses: 

> `text_only_question` is what we call the spacers from the UI as we store them, as such, they aren't really questions. They don't count in the question counts, nor do they reference `assessment_question_id` as you can't put them in question banks.

Thanks for this clarification. I have since noticed their special treatment in the UI, so this makes sense.
