### ISSUE TITLE
Check checkbox in handlebars

### ISSUE THREAD

**Issue by kachroosneha** [instructure/canvas-lms#846]
I added a checkbox in my discussions form. Its saving the value properly in the database. But if I try to edit the discussion the checkbox is not displaying checked and after updating the form, FALSE value is set in the database. I had referred the code in the same file: app/views/jst/DiscussionTopics/EditView.handlebars but no luck. 

Can someone please help me for the same  and also for other checkboxes in the same form how is the value displayed properly in edit. I am not able to get code for the same.

**Comment by simonista** [comment]
It's hard without looking at the code to know what might be going on.  One idea I had was that you might look through f5276f7a7812cc711fc63ab20e2e711bfc0ef1d8, which added a couple checkboxes to that form, as an example of how to thread the data all the way to/from the server.  Hope that helps!  You may also want to ask on the mailing list: https://groups.google.com/forum/#!forum/canvas-lms-users, we try to reserve github issues for bugs in the existing codebase.
