### ISSUE TITLE
API documentation for creating sub-accounts doesn't match actual return type

### ISSUE THREAD

**Issue by ToeBee** [instructure/canvas-lms#847]
The API documentation for creating sub-accounts (https://canvas.instructure.com/doc/api/accounts.html#method.sub_accounts.create) says that it returns a list of accounts. However when I hit this end point it actually returns just a single Account object. Returning the object that was just created makes more sense so I'm guessing this is just a documentation change.

**Comment by roor0** [comment]
yes, just a doc change. waiting for ci build and code review
