### ISSUE TITLE
How can I access to canvas_development database

### ISSUE THREAD

**Issue by AngeleMM** [instructure/canvas-lms#848]
Please ask me How can I access to canvas_development database. I install my canvas with CODES.sh file, but I don't write username and password wor database.

Thanks.

**Comment by FreedomBen** [comment]
Hi @AngeleMM CODES.sh is a community maintained tool (tho I happen to be the maintainer so I'll help you :smile: ).

The database user has no password, and the username is equivalent to your username if on OS X, or it is 'postgres' if on Linux.  On OS X the user creation is handled by the Postgres installer.  On Linux CODES.sh creates the postgres user like this:

    if ! $(sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$(whoami)'" | grep "1" >/dev/null); then 
        sudo -u postgres createuser --createdb --login --createrole --superuser --replication $(whoami)
    fi

**Comment by AngeleMM** [comment]
Thanks for the help :)
