### ISSUE TITLE
How courses and quizes are connected with each other in DataBase

### ISSUE THREAD

**Issue by AngeleMM** [instructure/canvas-lms#849]
Hi,

In Canvas, we have tables for courses and quizes. With which fields are the courses connected with quizes? 

Thanks.

**Comment by simonista** [comment]
Hey @AngeleMM, the columns you want to look at in the quizzes table are context_type and context_id.  when context_type = 'Course', context_id will be a id that points to the courses.id column.

Hope that helps!

**Comment by AngeleMM** [comment]
Thanks for the help.
