### ISSUE TITLE
How I can get quizzes created between some dates from API

### ISSUE THREAD

**Issue by AngeleMM** [instructure/canvas-lms#850]
Hi,

Please say me how I can get quizzes created between some dates from canvas API ?

Thanks.

**Comment by simonista** [comment]
Hey @AngeleMM, it's not currently possible to filter by date in the api, you'll just have to query for all quizzes and filter the result set.  For future reference, we try to reserve github issues for bugs in the code, questions like this are better suited for our mailing list: https://groups.google.com/forum/#!forum/canvas-lms-users
