### ISSUE TITLE
Cannot complete canvas setup

### ISSUE THREAD

**Issue by nnimis** [instructure/canvas-lms#852]
### Summary:

I went all the way through the quick setup with no luck. Then I moved to the production start guide to figure out where is the actual issue. I have it almost done, is a fresh ubuntu 16.04 installation.
I have completed the steps to a production setup, but I just cannot start the application.
When I run 'sudo /etc/init.d/canvas_init start' I got the message:
"your ruby version is 2.3.0 but your gemfile specified 2.1.6"

The output of ruby --version is the following:
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]

I just don't know how to workaround this error, I'm trying to have a canvas instance working for almost 2 days. I'm a beginner with ruby, rails and bundler, any help will be really appreciated.
### Steps to reproduce:

Go through the production start guide on a fresh ubuntu 16.04
### Expected behavior:

Just get the application working
### Additional notes:

Some steps of the guide needs an update. I have installed ruby by using rvm instead of apt-get install ruby2.1 ruby2.1-dev, this way does not seems to work anymore.

**Comment by nnimis** [comment]
Anybody? :(

**Comment by FreedomBen** [comment]
@nnimis sorry you were ignored :disappointed: 

We do have a mailing list that is pretty active that can often help with things like this.  For installing a certain version of ruby, I usually build and install from source using something like https://github.com/postmodern/ruby-install .  you can also use https://github.com/postmodern/chruby with it.

Here's a link to the mailing list:  https://groups.google.com/forum/#!forum/canvas-lms-users

**Comment by rwstauner** [comment]
@nnimis If you've installed ruby with `rvm` that PATH isn't propagating through `sudo`.
To confirm that it's a PATH problem, compare the output of `ruby --version` to `sudo ruby --version`.

If that is the issue, you could try `sudo env PATH=$PATH /etc/init.d/canvas_init start`.
That embeds your current PATH (which should be where your desired ruby is coming from) into the sudo command so it can find the right ruby.

**Comment by nnimis** [comment]
Thanks for the replies guys!

@rwstauner effectively, ruby --version says I'm using 2.1.6 and sudo ruby --version says 2.3.0
Unfortunatelly, sudo env PATH=$PATH /etc/init.d/canvas_init start didn't worked, same exception (using 2.3.0 and Gemfile specified 2.1.6)

**Comment by rwstauner** [comment]
Sorry, passing PATH isn't enough because `canvas_init` does an `su` which cleans the env.

You could symlink your rvm ruby into a standard directory:
`sudo ln -s $(which ruby) /usr/local/bin/ruby`

and then try the original command again (`sudo /etc/init.d/canvas_init start`).
