### ISSUE TITLE
bundle install fails

### ISSUE THREAD

**Issue by qx** [instructure/canvas-lms#855]
### Summary:
bundle install fails
### Steps to reproduce:

 1.bundle install
 2.
 3.

### Expected behavior:
[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `_before.rb`: exit. Bundler cannot continue.

 #  from /Users/ok/canvas-lms/Gemfile.d/_before.rb:40
 #  -------------------------------------------
 #         "`gem uninstall bundler -v #{Bundler::VERSION}`."
 >    exit 1
 #  end
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /Users/ok/canvas-lms/Gemfile.d/_before.rb:40
 #  -------------------------------------------
 #   >   #
 #  -------------------------------------------
### Additional notes:
ruby version 2.1.6.  use rbenv

**Comment by rwstauner** [comment]
@qx It's a bundler version problem.  You can install a specific (supported) version of bundler and use it specifically like so: 

```
gem install bundler -v 1.11.2
bundle _1.11.2_ install
```

But be aware you'll have to add the `_1.11.2_` arg to every `bundle` call, so you might want to try the uninstall command:
```
gem uninstall bundler -v 1.12.5
```

**Comment by qx** [comment]
@rwstauner   It works  ,thanks
