### ISSUE TITLE
Why Open Theme Editor removed from Site settings ?

### ISSUE THREAD

**Issue by sharathkumar** [instructure/canvas-lms#856]
### Summary:
We could see that the link for open theme editor has been removed from the site settings page.
### Steps to reproduce:

 1. Log in as admin
 2. Go to Admin >> Site Admin >> Users 
 3. A month ago I was able to use open theme editor on this area. But could not see the link now.

**Comment by claydiffrient** [comment]
@sharathkumar The link was moved to the Account Navigation rather than under settings.  Check out the [guide for the Theme Editor](https://guides.instructure.com/m/4214/l/418311-how-do-i-use-the-theme-editor-as-an-admin).

**Comment by sharathkumar** [comment]
@claydiffrient Please see the Site Admin settings page. In that page I could not  be able to see any link for themes in navigation. Can you please review that ?

![site admin settings](https://cloud.githubusercontent.com/assets/3734452/16755811/1a4f596c-481e-11e6-8f7c-992702fdaac2.png)
