### ISSUE TITLE
Installation of Node 0.12 on Ubuntu 14 LTS produces deprecation warning

### ISSUE THREAD

**Issue by englishmatt** [instructure/canvas-lms#857]
### Summary:
The current [Quick start installation wiki](https://github.com/instructure/canvas-lms/wiki/Quick-Start) recommends installing nodejs v0.12 when installing for Ubuntu 14 LTS. This produces a deprecation warning as follows.

### Steps to reproduce:

 1. Follow the Quick start installation instructions for Ubuntu 14 LTS
 2. Issue `curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -`
 3. See deprecation warning as follows:
    ```
NODE.JS v0.12 DEPRECATION WARNING                      

Node.js v0.12 will cease to be actively supported at the end of 2016.

This means you will not continue to receive security or critical stability
updates for this version of Node.js beyond that time.

You should begin migration to a newer version of Node.js as soon as
possible. Use the installation script that corresponds to the version of
Node.js you wish to install. e.g.

* https://deb.nodesource.com/setup_4.x — Node.js v4 LTS "Argon" (recommended)
* https://deb.nodesource.com/setup_6.x — Node.js v6 Current

Please see https://github.com/nodejs/LTS/ for details about which version
may be appropriate for you.

The NodeSource Node.js Linux distributions GitHub repository contains
information about which versions of Node.js and which Linux distributions
are supported and how to use the install scripts.
    https://github.com/nodesource/distributions
```

### Expected behavior:
No deprecation warning; a new enough version of node to not produce a deprecation warning.

**Comment by simonista** [comment]
Hey @englishmatt, thanks for taking the time to file this.  We're well aware that we're on an old version of Node, and are hoping to be off 0.12 by the end of the year.  As you can imagine, it's quite a process to upgrade node versions, but we're currently working through the dependencies.  Keep an eye on https://groups.google.com/forum/#!forum/canvas-lms-users, we'll announce there when we're ready for open source users to migrate.

**Comment by englishmatt** [comment]
Great! Good to know you guys are on top of things. Thanks.
