### ISSUE TITLE
Why Open Theme Editor removed from Site settings ? 

### ISSUE THREAD

**Issue by sharathkumar** [instructure/canvas-lms#859]
### Summary:
#856 related issue

@claydiffrient  In this [guide](https://guides.instructure.com/m/4214/l/418311-how-do-i-use-the-theme-editor-as-an-admin) mentioned about the accounts not about site admin.

Please see the Site Admin settings page. In that page I could not  be able to see any link for themes in navigation. Can you please review it ?

![site admin settings](https://cloud.githubusercontent.com/assets/3734452/16755811/1a4f596c-481e-11e6-8f7c-992702fdaac2.png)

**Comment by claydiffrient** [comment]
@sharathkumar Sorry for the misunderstanding.  Theme Editor support at the Site Admin level is coming soon. I'll update back here when the commit lands in master.

**Comment by simonista** [comment]
This commit is now in master: 544282af02ba11f7a9c9401609e9f910ac9773e6

**Comment by sharathkumar** [comment]
Thank you @simonista
