### ISSUE TITLE
Feature: Videos without Kaltura

### ISSUE THREAD

**Issue by Schniz** [instructure/canvas-lms#860]
### Summary:
Kaltura integration works for version 3, and haven't updated since 2014 or even before.

Canvas already implements a file upload form for each course, and we can use the same method of inserting inline `img` tags with `video` and `audio`, by changing a small portion of the file tree sidebar implementation.

What do you think about it?

Thanks!

**Comment by Schniz** [comment]
We need to stream the video and audio files for supporting streaming 😄

**Comment by simonista** [comment]
Hey @Schniz, thanks for dropping us a note.  We try to reserve github issues for bugs people have run into while running the canvas-lms app.  You'll probably have better luck getting your feature idea in front of the right eyes if you submit it here: https://community.canvaslms.com/
