### ISSUE TITLE
Development Email sender not work.

### ISSUE THREAD

**Issue by qx** [instructure/canvas-lms#861]
### Steps to reproduce:

 1.choose Account
 2.Add new user
 3.new user's email get nothing email inbox ,and the account of admin's email have nothing email in outbox.
### Expected behavior:

received a register email in new user's email inbox
### Additional notes:

I followed this https://github.com/instructure/canvas-lms/wiki/Troubleshooting, but nothing to help. I still can't find where is wrong.nothing error show in website or database.
I don't know how to show you more usefull detail about emal? plz tell me what's more should I do for this issue

**Comment by amulgarg** [comment]
Is your delayed_job server running??

Is your outgoing_mail.yml file configured with the config from your SMTP server?

**Comment by qx** [comment]
Yes,I'm sure .@amulgarg. The problem is how can I get email log?I'm so puzzled why I got send success notification while email send nothing!

**Comment by qx** [comment]
I finally have found log in delayed_job.log.
You may need add more detail about outgoing_mail.yml config 
`From: Instructure Canvas <notifications@mail.[domain]>`
There is an error,because I don't have this email account. Usually I thought I'll will user_name,
but not, so why I need user_name????? It replaced by outgoing_address without any document, if I missed it?

**Comment by simonista** [comment]
Hey @qx, I'm struggling to understand exactly what the error you found in the delayed_job.log is.  Could you post it here?

**Comment by qx** [comment]
@simonista , the sender email is combinated with domain, I think it should be user_name,  so the sender acount  is not exist. 

` eg: domain: gmail.com   Not  smtp.gmail.com`

**Comment by bindmisson** [comment]
Outgoing email is not working for me also!!!

Any fix ? Please check my error


', 'unknown-smtp-gmail-com@instructure.example.com', NULL, 'Message delivery failed', '2016-08-21 18:02:26.140752') RETURNING "id"
