### ISSUE TITLE
Getting user analytics assignments routing error

### ISSUE THREAD

**Issue by ghost** [instructure/canvas-lms#862]
Hello.
please can you help me
I am getting a routing error when I am trying to get user analytics assignments by this request
https://my_website/api/v1/courses/7/analytics/users/18/assignments?access_token=xqSxcWjDhqnRtnR73uU85YvVk4SBLYtEAzBW3mhJU7Eu26BoZsO6ngA5D8XP0sLl
it returns this http://prntscr.com/bsqakx
can you please say me what I'm doing wrong?
I have intsalled  the canvas lms on my server by CODES.sh, can it cause the problem?

**Comment by simonista** [comment]
Have you installed the analytics plugin? https://github.com/instructure/analytics
