### ISSUE TITLE
Rake migration and initialization task failed

### ISSUE THREAD

**Issue by gbyg** [instructure/canvas-lms#866]
### Summary:

I tried to install the production version of Canvas on my laptop using virtualbox but I got this error when I tried to populate the database i created.

 RAILS_ENV=production bundle exec rake db:initial_setup
rake aborted!
LoadError: cannot load such file -- respondus_soap_endpoint/urn:RespondusAPIMappingRegistry.rb
/var/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in`block in require'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in`require'
/var/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint.rb:6:in `<top (required)>'
/var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in`require'
/var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in`each'
/var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in`each'
/var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:99:in`require'
/var/canvas/config/application.rb:19:in `<top (required)>'
/var/canvas/Rakefile:4:in`require'
/var/canvas/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
### Steps to reproduce:

 1.sysadmin@appserver:/var/canvas$ RAILS_ENV=production bundle exec rake db:initial_setup

 2.
 3.
### Expected behavior:

To successfully deploy Canvas

**Comment by simonista** [comment]
Hey @gbyg, sorry you're running into this.  What version of ruby / bundler are you using?  Can you verify that the file `gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/urn:RespondusAPIMappingRegistry.rb` exists?

**Comment by gbyg** [comment]
Yes the file gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/urn:RespondusAPIMappingRegistry.rb exist. My ruby version is 2.1.9 and my bundler version is 1.11.2.

**Comment by slartimitvar** [comment]
I hope you got this sorted gbyg.
I ran into this error today and the issue was that the three files starting with "urn:RespondusAPI..." had the colon replaced with an underscore like "urn_RespondusAPI...".
I renamed them and it worked fine.
Weird.
