### ISSUE TITLE
Upstream bug in gulp@3.9.1 causes asset compilation to fail

### ISSUE THREAD

**Issue by englishmatt** [instructure/canvas-lms#867]
### Summary:

Upstream bug in gulp@3.9.1 causes asset compilation to fail. After downgrading to 3.9.0 asset compilation is successful.

### Steps to reproduce:

 1. Follow [Quick Start installation instructions](https://github.com/instructure/canvas-lms/wiki/Quick-Start).
 2. Issue `$GEM_HOME/bin/bundle exec rake canvas:compile_assets --trace`
 3. Receive following error:
        
        [00:09:02] Failed to load external module babel-register
        [00:09:02] Requiring external module babel-core/register
        [00:09:03] Using gulpfile /var/www/canvas/gulpfile.babel.js
        [00:09:03] Starting 'rev'...
        [00:09:03] Finished 'rev' after 298 ms

### Expected behavior:

For the `compile_assets` task to complete successfully.

### Additional notes:

Fixed issue by downgrading Gulp from 3.9.1 to 3.9.0: issued `npm install --save-dev gulp@3.9.0`. Gulp 3.9.1 is initially installed due to this line in `package.json`:

    "devDependencies": {
        ...
        "gulp": "^3.9"
        ...
     },

Recommend setting this to `"gulp": "^3.9.0"` until upstream Gulp issue is resolved. I have not filed an issue with Gulp as I have not be able to identify the most simple case. Perhaps you might have better luck/more time.

### Additional Resources:

[Stackoverflow: Error with gulp serve: Requiring external module babel-register](http://stackoverflow.com/questions/35832739/error-with-gulp-serve-requiring-external-module-babel-register)

**Comment by claydiffrient** [comment]
@englishmatt This isn't an actual problem.  Asset compilation will complete successfully even if that line prints out.  Gulp basically attempts to support several Babel versions.  When it doesn't find the module `babel-register` it falls back to trying `babel-core/register`. There are a few more details about this "error" here: https://github.com/gulpjs/gulp/issues/830#issuecomment-131099037

In any case, if your assets aren't compiling properly, this isn't the issue.  Thanks for filing the issue with us though and good luck as you use Canvas.

**Comment by englishmatt** [comment]
Thanks for clarifying!
