### ISSUE TITLE
Create a root account

### ISSUE THREAD

**Issue by harut-hokhanyan** [instructure/canvas-lms#868]
Hi.
I want to create a root account using api, but he returns me the NULL result.
I sent this tada:

{
"account" : {
"name" : "Admin Account1",
"domain" : "http:\/\/ec2-52-39-228-8.us-west-2.compute.amazonaws.com",
"settings" : {
"users_can_edit_name" : 0
},
"services" : {
"avatars":1
},
"external_integration_keys" : {
"salesforce_account_id" : 1
}
}

and access_token with header
to the urls:   
http://ec2-52-39-228-8.us-west-2.compute.amazonaws.com/api/v1/accounts
http://ec2-52-39-228-8.us-west-2.compute.amazonaws.com/api/v1/accounts/1/root_accounts

Please tell me what I'm doing wrong?
Thanks

**Comment by simonista** [comment]
Hi @harut-hokhanyan, creating more than 1 root account is not available in the open source version of the code, that is custom for our hosted offering.  You may want to refer to your own copy of the api docs (at /doc/api/index.html) for which endpoints are available for you.

Sorry for the trouble,
Simon

**Comment by harut-hokhanyan** [comment]
Thanks for answer
