### ISSUE TITLE
No compatible version found: tough-cookie@'>=2.3.0 <2.4.0' in a new Canvas installation

### ISSUE THREAD

**Issue by jorgevbo** [instructure/canvas-lms#870]
### Summary:

When I execute step "npm install" after "bundle install" npm not found a version of tough-cookie. It show error message:
No compatible version found: tough-cookie@'>=2.3.0 <2.4.0'

### Steps to reproduce:

 1. Clone canvas-lms repository
 2. Install prerequisites software.
 3. Execute bundle install
 4. Execute npm install

### Expected behavior:

Download and Install npm dependencies

### Additional notes:

Ruby version: 2.1.5
NodeJS: 0.12.15
NPM: 2.15.1
OS: Ubuntu 14.04 TLS

Stack trace:

npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.15
npm ERR! npm  v2.15.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: tough-cookie@'>=2.3.0 <2.4.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.9.0","0.9.1","0.9.3","0.9.4","0.9.5","0.9.6","0.9.7","0.9.8","0.9.9","0.9.11","0.9.12","0.9.13","0.9.14","0.9.15","0.10.0","0.11.0","0.12.0","0.12.1","0.13.0","1.0.0","1.1.0","1.2.0","2.0.0","2.1.0","2.2.0","2.2.1","2.2.2"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'request'
npm ERR! notarget

**Comment by jorgevbo** [comment]
I tried to install only tough-cookie@2.3.0 and npm said 2.3.0 not soported in nodejs 0.12. (4.0 >=)
So, I upgraded node:

curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by claydiffrient** [comment]
@jorgevbo Thanks for reporting the issue!  We are having problems with this internally as well.  We are working quickly to resolve it as soon as possible.
