### ISSUE TITLE
Canvas LMS installation Failed due to thrift error

### ISSUE THREAD

**Issue by therimalaya** [instructure/canvas-lms#872]
I am trying to install Canvas LMS following the production start instructions. At the point of bundle install, it failed on Thrift installation. I am using Ubuntu 16.04 on a docker in a Mac System. Everything was working fine, but this error has stopped me to start the system. Please help me!

```
Installing thrift 0.8.0 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/canvas/vendor/bundle/ruby/2.3.0/gems/thrift-0.8.0/ext
/usr/bin/ruby2.3 -r ./siteconf20160802-8582-f93j3i.rb extconf.rb --with-cppflags=-D_FORTIFY_SOURCE=0
checking for strlcpy() in string.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
        from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
        from /usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
        from /usr/lib/ruby/2.3.0/mkmf.rb:1051:in `block in have_func'
        from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from /usr/lib/ruby/2.3.0/mkmf.rb:1050:in `have_func'
        from extconf.rb:27:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/canvas/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/thrift-0.8.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/canvas/vendor/bundle/ruby/2.3.0/gems/thrift-0.8.0 for inspection.
Results logged to /var/canvas/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/thrift-0.8.0/gem_make.out
```

The output from mkmf.log is,

```
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.3.0 -I/usr/include/ruby-2.3.0/ruby/backward -I/usr/include/ruby-2.3.0 -I. -D_FORTIFY_SOURCE=0 -g -O2 -Wall -Werror conftest.c  -L. -L/usr/lib/x86_64-linux-\
gnu -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby-2.3  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
<command-line>:0:0: error: "_FORTIFY_SOURCE" redefined [-Werror]
<built-in>: note: this is the location of the previous definition
cc1: all warnings being treated as errors
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by simonista** [comment]
I think the key line is "You have to install development tools first."   I'm not sure exactly what this would entail in Ubuntu, but I image if you search for it, you'll find it.

You could also try using our Dockerfile that we include in the repo: https://github.com/instructure/canvas-lms/blob/stable/docker-compose/Dockerfile

Hope that helps!

**Comment by FreedomBen** [comment]
On Ubuntu, make sure `build-essential` is installed:

    apt-get install build-essential

Even tho your host is a Mac, you are effectively installing on Ubuntu.  There's several packages you need.  Some of these may already be installed:

        sudo apt-get -y install ruby-dev
        sudo apt-get -y install zlib1g-dev
        sudo apt-get -y install rubygems1.9.1
        sudo apt-get -y install libxml2-dev
        sudo apt-get -y install libxslt1-dev
        sudo apt-get -y install libsqlite3-dev
        sudo apt-get -y install libhttpclient-ruby
        sudo apt-get -y install imagemagick
        sudo apt-get -y install libxmlsec1-dev
        sudo apt-get -y install python-software-properties
        sudo apt-get -y install postgresql
        sudo apt-get -y install postgresql-contrib
        sudo apt-get -y install libpq-dev
        sudo apt-get -y install libpqxx-dev
        sudo apt-get -y install ruby-pg
        sudo apt-get -y install build-essential
        sudo apt-get -y install libglib2.0
  
There's a script that does a lot of setup here, but currently has known issues with node on ubuntu.  It might be a good reference for you tho, and if you do the node part manually, it can help with the rest.  https://github.com/FreedomBen/canvas-development-tools/blob/master/CODES.sh

Good luck!

**Comment by FreedomBen** [comment]
Oh I might add that if it were me I would definitely check out the Dockerfile that @simonista mentioned.  It is Ubuntu-based so installs everything it needs and gets Canvas tidied up for Docker.

**Comment by therimalaya** [comment]
Actually, I was following the instruction by @simonista. I tried both Quick install (using CODES.sh) and production ready install. I have already installed all the packages you have listed above and are up-to-date. The problem I am getting is after all this attempts.

**Comment by FreedomBen** [comment]
Oh I see.  You might try just starting over (I know, it sucks), and following these instructions:

https://github.com/instructure/canvas-lms/blob/stable/doc/development_with_docker.md

I did this like a day or two ago and had no issues.
