### ISSUE TITLE
canvas_init issue

### ISSUE THREAD

**Issue by lunalunaki** [instructure/canvas-lms#873]
I have been trying to take a stab at the production start process on a VM and I'm stuck at the very end where the following takes place:

sysadmin@appserver:/var/canvas$ sudo ln -s /var/canvas/script/canvas_init /etc/init.d/canvas_init

sysadmin@appserver:/var/canvas$ sudo update-rc.d canvas_init defaults

sysadmin@appserver:/var/canvas$ sudo /etc/init.d/canvas_init start

It just states that: update-rc.d: initscript does not exist. What am I missing?

**Comment by simonista** [comment]
Hey @lunalunaki, sorry you never got a response on this. We try to keep github issues specific to bugs in the app, you might have more luck with this type of question on our mailing list: groups.google.com/forum/#!forum/canvas-lms-users.  Hope you got it worked out!
