### ISSUE TITLE
LTI variable substituion for 'Canvas.externalTool.url' seems incorrect

### ISSUE THREAD

**Issue by putmanb** [instructure/canvas-lms#880]
### Summary:

The data that is produced on a LTI launch request when the LTI custom variable 'Canvas.externalTool.url' is expanded seems incorrect to me in our hosted Canvas instance.  The use case is for a tool launched from a course navigation link.

For example in a test tool I see the following expanded parameter value:

https://georgetown.test.instructure.com/api/v1/courses/1382/external_tools/112

It's not clear whether the endpoint URL here is supposed to be:

1) the URL of the tool in the user-facing Canvas web application. For this tool that would be

https://georgetown.test.instructure.com/courses/1382/external_tools/112

So the leading part of the path '/api/v1' would be wrong in this case.

2) the API endpoint for the tool for use with the External Tools API.  In this case the value is still incorrect, because this particular tool is not defined on the course, but rather on a sub-account.  So it ought to be:

https://georgetown.test.instructure.com/api/v1/accounts/41/external_tools/112

An API call using the actual produced URL value (with the tool subordinate to the course in which the course navigation appears) as expected produces an error  "The specified resource does not exist".

### Steps to reproduce:

 1.  Configure an external tool with a course navigation.
 2.  Configure on the external tool a custom LTI launch param with value '$Canvas.externalTool.url'  
 3. Examine the value of the custom launch param, via request tracing or application logging.

### Expected behavior:

Base on the docs for this variable:

https://canvas.instructure.com/doc/api/file.tools_variable_substitutions.html

"returns the URL for the external tool that was launched. Only available for LTI 1."

it is unclear which of the two variants above is the expected output.  But the actual output is neither.

**Comment by claydiffrient** [comment]
@putmanb Thanks for filing the issue!  We'll have someone look into this soon.

**Comment by rivernate** [comment]
@putmanb Thanks for finding that, it does indeed look like a bug.  It should be returning the api endpoint for the tool.  I've created a internal ticket to fix this, and update the documentation to be more helpful.
