### ISSUE TITLE
Question about assigning Teachers to an account

### ISSUE THREAD

**Issue by gpinkham** [instructure/canvas-lms#883]
Maybe I am missing this but can I assign a user the teacher role for an account?   I ask because I can see the account setting "Who Can Create New Courses"..  I have selected Teachers..    but I can only assign a Teacher role to a user for a course enrollment..   so does this mean I need to create a course first and assign a teacher to it so that they can in turn create their own courses?  

Thanks in advance
Gary

**Comment by ccutrer** [comment]
That is correct. There is no account level role of "Teacher", and the setting you referred to implies users that are already teachers in one (or more) course, can create new courses.

If you need to have select users that can create courses without having an existing enrollment, you can create a custom admin role, and only grant the create courses permission.
