### ISSUE TITLE
API for /v1/courses incorrectly documented

### ISSUE THREAD

**Issue by nijssen** [instructure/canvas-lms#888]
### Summary:

Two attributes, `offer` and `event` should be written as `course[offer]` and `course[event]`, for all occurrences.
### Steps to reproduce:
1. Try to make a call using just `offer` and/or `event`
2. Observe that no action has taken place

**Comment by jenseng** [comment]
@nijssen are you sure? Based on a reading of the code and looking at various specs in [this file](https://github.com/instructure/canvas-lms/blob/96138b9f01272cb5aa1f8275847cffa6b6c71c1d/spec/apis/v1/courses_api_spec.rb), the documentation appears to be correct. Perhaps something else is going on (e.g. your API user doesn't have appropriate permissions)?

Can you provide specs demonstrating both `offer` and `event` not working and `course[offer]` and `course[event]` working?

**Comment by jenseng** [comment]
I stand partially corrected, `course[event]` is indeed the correct parameter for `PUT /api/v1/courses/:id`, and the documentation was [recently fixed](https://github.com/instructure/canvas-lms/commit/d681dd3775b1c7abdad67646c936de0042873204) on master. That said, it appears that `event` is the correct parameter for the other endpoints, and `offer` is used exclusively. Which endpoint(s) are you referring to specifically?

**Comment by nijssen** [comment]
I only tried the `PUT /v1/courses/:id` and I assumed that this mistake would be consistent throughout.

**Comment by simonista** [comment]
Sounds like this was fixed in d681dd3775b1c7abdad67646c936de0042873204. Closing.
