### ISSUE TITLE
Errors running Docker image on Ubuntu 14

### ISSUE THREAD

**Issue by jeff303** [instructure/canvas-lms#891]
Hi,

I am attempting to run the Canvas LMS Docker image, using the instructions at doc/development_with_docker.md.  I have included a file that shows the output, from `docker-compose run --rm web script/docker_first_time_build.sh`.  This is from the master branch, checked out today.  Any ideas?

[docker_compose.txt](https://github.com/instructure/canvas-lms/files/475564/docker_compose.txt)

**Comment by codekitchen** [comment]
There are quite a few `Cannot allocate memory` errors in that output. It looks like your host machine needs more memory, or isn't giving enough memory to the docker container. I'd recommend at least 4 GB, ideally 8 GB or more.

**Comment by jeff303** [comment]
@codekitchen , thanks, I should have noticed that.  I previously got this running on a t2.micro EC2 instance (1GB RAM) a few months ago, so I assumed it should still work, but maybe something changed in the latest code.  It appears to be going fine on a t2.medium (4GB).
