### ISSUE TITLE
Error when running canvas_init for the last step in the installation

### ISSUE THREAD

**Issue by johndecola** [instructure/canvas-lms#893]
Hi,

I have been attempting to complete the Canvas production installation on a clean Rackspace server running Ubuntu 16.04 LTS. I exactly followed all of the steps in the production installation guide: https://github.com/instructure/canvas-lms/wiki/Production-Start. When I tried to run the "sudo /etc/init.d/canvas_init start" command for the very last step, I got the following error messages:

sysadmin@server-05:/var/canvas$ sudo /etc/init.d/canvas_init start

/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)

```
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/canvas/script/delayed_job:7:in `<main>'
```

sysadmin@server-05:/var/canvas$

I don't see how I could have done anything wrong during the installation since I followed all of the steps exactly. I have spent a couple of days troubleshooting this but could not get anywhere. Can you please provide some suggestions on how to fix this?  

Thanks,
John

**Comment by tierra** [comment]
It sounds like you haven't installed bundler correctly:
https://github.com/instructure/canvas-lms/wiki/Production-Start#bundler-and-canvas-dependencies

**Comment by johndecola** [comment]
I am very sure that I did entered these two bundle install commands during the installation:

sysadmin@appserver:/var/canvas$ sudo gem install bundler --version 1.11.2
sysadmin@appserver:/var/canvas$ bundle install --path vendor/bundle

However I skipped the commands under "Note on Mac OS X Mavericks" since my server is running Ubuntu rather than Mac OS X. Is there any more that needs to be done for installing bundle that is not already in the production installation instruction?

**Comment by johndecola** [comment]
Here's some more screen output from the command console of my server: 

sysadmin@server-05:/$ bundler -v
Bundler version 1.11.2
sysadmin@server-05:/$ cd var/canvas/vendor/bundle/ruby/2.1.0
sysadmin@server-05:/var/canvas/vendor/bundle/ruby/2.1.0$ ls
bin  build_info  bundler  cache  doc  extensions  gems  specifications
sysadmin@server-05:/var/canvas/vendor/bundle/ruby/2.1.0$ cd bundler/gems
sysadmin@server-05:/var/canvas/vendor/bundle/ruby/2.1.0/bundler/gems$ ls
active_model_serializers-61882e1e4127     mocha-bb8813fbb4cc
cassandra-cql-beed72e249d0                    nokogiri-d47e53f885c9
dress_code-574382160ee4                         nokogiri-xmlsec-me-harder-3236a2499864
extensions                                                   redis-store-72db36c56c65

The console does indicate that the bundler version is 1.11.2 after entering the "bundler -v" command.

**Comment by johndecola** [comment]
Bryan,

Do you have any further suggestions or feedback? It looks like I did installed bundler correctly based on the output from my command console.

John

**Comment by johnnaegle** [comment]
What is the output if you do `sudo bundler -v`

You are using `sudo /etc/init.d/canvas_init start` but your bundler output is as the sysadmin user, not root.

**Comment by wizkid686** [comment]
You are using ruby 2.3, which has not been fully tested/certified with Canvas yet, and has a few glitches with Canvas right now. You should downgrade to ruby 2.2, we've been using that version of ruby on our system without incident for over a year. You'll need to reinstall bundler after removing ruby 2.3 and installig 2.2. Canvas can run with a newer bundler version that the one in production guides, here is the command that loads the latest bundler canvas can use:

sudo gem install bundler --version 1.12.5

After that, recompile your assets (there are other issues with ruby 2.3 there), and try to start-up canvas init again.

**Comment by wizkid686** [comment]
@johndecola Have you had any success with install after switching to ruby 2.2?

**Comment by johndecola** [comment]
wizkid686,

Thanks for your help. I started the installation over again and ended up with ruby 2.1. In the end, I got canvas working on my system. Besides ruby, I found a few issues with the installation instruction where I believe things could have been clarified better:

1. Bundle Installation:
Do not run the command:  bundle install --path vendor/bundle using sudo. However some people might be tempted to do so because the var/canvas directory is owned by the root user by default if you follow the installation instruction exactly to create the directory and transfer all of the setup files to this directory. Without using sudo, this bundle command would not have sufficient file permissions. However it is necessary to make sure that the var/canvas directory is owned by the sysadmin user (or whoever user you use to install canvas) first and then run the bundle install command without using sudo. None of these are stated in the instruction.

2. Apache Installation
The apache installation command from the instruction: sudo apt-get install passenger-common1.9.1 libapache2-mod-passenger apache2 would not have worked if you have Ubuntu 16 since its repository no longer offers Passenger 1.9.1. However the instruction did state that some users may need to add a new passenger apt repository and use the command: sudo apt-get install passenger libapache2-mod-passenger apache2. At first, I did not realize that I also have to add this repository in Ubuntu 16 and only called the command:  sudo apt-get install passenger libapache2-mod-passenger apache2. Without adding the repository, that command forces a ruby upgrade to version 2.3. The instruction should have indicated that Ubuntu 16 users (maybe Ubuntu 14 as well) need to add this repository rather than only for some users. It should also include the command for adding this repository.

I found the installation instruction seriously outdated and confusing. The top of the page still states that the tutorial was written and tested using Ubuntu's latest LTS 12.04. This OS was released four years ago and it will no longer be supported after April of next year. Somebody needs to repeat the installation in the latest version of Ubuntu LTS (currently 16.04) and rewrite the whole instruction from scratch. It will also be great if there is a “well written” installation instruction for CentOS as well.

John

**Comment by wizkid686** [comment]
We've done deployments on Canvas on Ubuntu 14.04, and with a couple tweaks, we have been able to use the instructions. However, we've not tested with 16.04 yet, although when I have some time I do plan to.

In regards to your specific install concerns for future reference:
1. Here are the steps I do for directory creation (this is bundler friendly):
~~~~
sudo mkdir /var/canvas
sudo chown -R sysadmin:sysadmin /var/canvas
cd /var
git clone https://github.com/instructure/canvas-lms.git canvas
cd canvas
git branch --set-upstream-to origin/stable
~~~~
These steps pull the canvas code directly into the hosting directory, so you can just do `git fetch && git reset --hard origin/stable` to upgrade the canvas code.
2. The docs are maintained to keep pace with the changes in Canvas code, the Ubuntu 12.04 bit was something that was missed. I'll admit that the Passenger instructions are in need of an update though. 

I noticed that you mentioned you are using Ruby 2.1 now. Did you try Ruby 2.2? It has some performance improvements over 2.1, and works fine with Canvas in my experience. Aside from this, I'm glad you were able to get Canvas working.

**Comment by johndecola** [comment]
wizkid686,

I have one more issue. When I attempt to make a color or logo change in the Theme Editor, the progress bar only proceeds a little and I get the error message "An error occurred trying to generate this theme, please try again." after clicking the "Preview Your Changes" bottom. Have you also experienced this issue? Do you have any suggestions on this as well?

Thanks,
John

![screen1](https://cloud.githubusercontent.com/assets/3630468/19176353/de8655ba-8c0c-11e6-87f1-c7c37d8f1ac6.png)

**Comment by johnnaegle** [comment]
Are you running the delayed job process? Theme css is generated by delayed job.  If you are running delayed job on a different server, you will need to use a CDN to distribute the CSS.

**Comment by johndecola** [comment]
We run everything on the same server. The problem with our delayed job process is that it I can start it by entering the command "/etc/init.d/canvas_init start" command. That generates the output "Daemonizing...". But it seems that it cannot kept itself running because I got the output "No delayed jobs pool running" after I enter the command "/etc/init.d/canvas_init status". 

It still sends emails out when I setup new users to the system and invite people to the courses. Before you bring this up, I initially thought delayed jobs have always been running because the email function is working. I don't think running out of memory is the issue because I am now running a 4GB RAM Server with 2 GM of swap file. I am really getting stuck here and would like to get this fully working since I spent so much time on this installation. Thanks.

**Comment by johndecola** [comment]
Just an update. I got delayed jobs fully running now but I am still getting the same issue with the Template Editor. I don't this issue has to do with delayed jobs.

**Comment by johndecola** [comment]
Right after clicking the "Preview Your Changes", I also checked the delayed_job.log and production.log files and did not find any error messages.

**Comment by wizkid686** [comment]
@johndecola, check your other open issue (#912) regarding the theme editor, I posted some steps there which should help.

**Comment by simonista** [comment]
Closing, since conversation moved to #912
