### ISSUE TITLE
Collaboration is missing from API documentation

### ISSUE THREAD

**Issue by johnnaegle** [instructure/canvas-lms#895]
### Summary:

If you try to regenerate the API definition in Pandarus, the Collaboration objection is missing
### Steps to reproduce:
1. uncomment the API documentation generation and re-population steps in pandarus/build-all
2. perform a build-all with canvas-lms/stable
3. Observe missing modules build failure with Collaboration
### Expected behavior:

The Collaboration object should be defined.
### Additional notes:

Collaborator is defined, but Collaboration is not

**Comment by simonista** [comment]
Thanks @johnnaegle, I'll push up a commit to document this object.
