### ISSUE TITLE
Quiz reports controller has invalid return type, breaks pandarus

### ISSUE THREAD

**Issue by johnnaegle** [instructure/canvas-lms#898]
### Summary:

The return type for `QuizReportsController#index` is `[ QuizReport ]` it should be `[QuizReport]` with no spaces
### Steps to reproduce:
1. Try to regenerate the pandarus API
### Expected behavior:

The API builds

**Comment by simonista** [comment]
Thanks, this is an easy fix, I'll push something up to address it.
