### ISSUE TITLE
NotificationPreferencesController#category_index has invalid return type in API documentation

### ISSUE THREAD

**Issue by johnnaegle** [instructure/canvas-lms#899]
### Summary:

`NotificationPreferencesController#category_index` has a documented return value of `# @returns []`.  This breaks pandarus API generation
### Steps to reproduce:
1. Try to rebuild pandarus
### Expected behavior:

Doesn't Fail
### Additional notes:

Worked around by commenting out the method

**Comment by simonista** [comment]
Yikes, this api is a mess.  It's not just that endpoint, the index action says `@returns [NotificationPreference]`, but it actually returns an object that references the array `{ notification_preferences: [...] }`.  We'll need to think about how to address this.
