### ISSUE TITLE
Microsoft Authentication Provider does not Populate Profile Information

### ISSUE THREAD

**Issue by wizkid686** [instructure/canvas-lms#902]
### Summary:

When using the Microsoft Account provider for authentication, if JIT provisioning is enabled, the user account created is not populated with attributes from the Microsoft Account, instead populating with the display name set to the login attribute, and no email set.
### Steps to reproduce:
1. Add the Microsoft Authentication Provider for an Account, and turn on JIT provisioning
2. Login with Microsoft through an account that does not exist
3. Go to the profile of the user
### Expected behavior:

A new account is created with the display_name attribute equal to the one on the Microsoft Account, and the email attribute equal to the one on the Microsoft account.
### Additional notes:

The Microsoft login request includes the required scope parameter (profile) to get the name, but it does not appear that Canvas is actually using it. The scope needed for getting the email address (email) is not present, so the email in the account is blank. This also makes the profile impossible to edit, since you can't confirm a null email address. This problem is also present on canvas.instructure.com when using the Microsoft Authentication Provider there.

**Comment by ccutrer** [comment]
This functionality has already been written, and just pending QA.

**Comment by ccutrer** [comment]
It was just merged to master: https://github.com/instructure/canvas-lms/commit/e6ab6564fcb7afdfac8fe896b5b1b5d36244152f

It will be in the 10/29 stable release.
