### ISSUE TITLE
Install Questions

### ISSUE THREAD

**Issue by Jeffyoung1990** [instructure/canvas-lms#905]
This probably isn't a good place to post this, however I am finding installation documentation to be a little confusing.  I see that Ruby 2.1.6 is the minimum requirement, however does Ruby 2.3.1 fulfill this requirement, or is it too new.  Thank you for your time!

-Jeff Young

P.S. - I am running Fedora 24 with the dnf package manager if anyone cares.

**Comment by wizkid686** [comment]
No, Ruby 2.3 is not supported by Canvas (yet). You can give it a try, but that's probably not the best idea.

You can use Ruby 2.2 with canvas though. It works perfectly fine, and our environment has been using it for over a year. Stay away from 2.3 for now though.

**Comment by johnnaegle** [comment]
2.3 broke specifically for us on file uploads.  2.2.2 worked great.

**Comment by ccutrer** [comment]
You have good timing for your question. As of a few minutes ago, Canvas is now passing all tests on ruby 2.3.1 on the master branch, so it's now supported. It won't become the _recommended_ version of ruby until it's running in Instructure's production environment, which will be no earlier than the 2016-11-19 release (which will be the first stable version to officially support ruby 2.3.1).

**Comment by ccutrer** [comment]
@johnnaegle: https://github.com/instructure/canvas-lms/commit/4f7db6301723c76cd640bf7d0748cab735cb92de is probably the issue you were referring to. There were a few other minor issues with ruby 2.3.1, mostly with specs.
