### ISSUE TITLE
Cannot Retrieve Access Token using authorization code

### ISSUE THREAD

**Issue by ranacseruet** [instructure/canvas-lms#908]
### Steps to reproduce:
1. Create a test `developer key` from administration
2. Use new generated client id/secret credential to authorize a user
3. Use the provided code to generate `access token` (API End: `https://<local-ip>/login/oauth2/token`).
### Expected behavior:

Should provide something like this:

```
{
    access_token: "1/fFAGRNJru1FTz70BzhT3Zg",
    refresh_token: "tIh2YBWGiC0GgGRglT9Ylwv2MnTvy8csfGyfK2PqZmkFYYqYZ0wui4tzI7uBwnN2"
    expires_in: 3600
}
```
### Original Output:

```
{
  "error": "invalid_request",
  "error_description": "client does not have access to specified account",
  "message": "invalid code"
}
```
### Additional notes:

used this VM to spin up the local test server: https://bitnami.com/stack/canvaslms/virtual-machine . Open to suggestion if I can try with some other test server

**Comment by ccutrer** [comment]
According to that link, you're running Canvas 2016.04.23, which is nearly 6 months old. Can you update to the latest stable version of Canvas, and try again?
