### ISSUE TITLE
Canvas Template Editor Preview Error

### ISSUE THREAD

**Issue by johndecola** [instructure/canvas-lms#912]
Hi,

When I attempt to make a color or logo change in the Theme Editor, the progress bar only proceeds a little and I get the error message "An error occurred trying to generate this theme, please try again." after clicking the "Preview Your Changes" bottom. Have any of you here also experienced this issue and willing to give me some suggestions?

Thanks,
John

![screen1](https://cloud.githubusercontent.com/assets/3630468/19176461/0071bf56-8c0e-11e6-9ef7-e284d17cea0a.png)

**Comment by johndecola** [comment]
Right after clicking the "Preview Your Changes", I also checked the delayed_job.log and production.log files and did not find any error messages.

**Comment by wizkid686** [comment]
This is probably a permissions error on the folders canvas uses for theme generation. 
Cd to your canvas application root (I'm assuming /var/canvas), and run the following commands
~~~
sudo chmod 777 -R public/dist/brandable_css
sudo chmod 777 -R public/stylesheets
sudo service canvas_init restart
sudo service apache2 restart
~~~
After that, close and reopen your browser and try again.

**Comment by johndecola** [comment]
I entered all of the commands that you suggested and still run into the issue.

**Comment by johndecola** [comment]
I just got a little further by also changing the permission setting of the var/canvas/app/stylesheets folder to 777. I am now able to get through the Preview mode and make color changes. But my custom branding logo image is still not loading. Instead only a small square box with an x in the middle is displayed.  

In other words, I can now make color changes but still not able to change the logos. Do you have any suggestions? Thanks.

**Comment by simonista** [comment]
Hey @johndecola, did you get this working?  You'll want to dig into `<your-canvas>/error_reports` or your production.log file and see if you can find a stacktrace for the error.
