### ISSUE TITLE
After OAuth User acceptance page not getting opened to Redirect URL 

### ISSUE THREAD

**Issue by raveendrau** [instructure/canvas-lms#913]
### Summary:
when we are testing OAuth first step , after accepting by user it is not getting forwarded to Redirect URL 
### Steps to reproduce:

 1. We did setp Canvas LMS site on local host
 2. Created developer key with redirect URL , and same thing we used in while testing with restclient
 3. pasted the following URL in browser :
http://192.168.25.133:3000/login/oauth2/auth?client_id=10000000000003&response_type=code&redirect_uri=http://www.google.com/oauth_complete&state=YYY
4. and user did accepted to authorize

### Expected behavior:
asper redirect url browser should open www.google.com , but it didn't. it has opened the attached error page, 

### Additional notes:

Please see the attached images one is with developer keys pages and another one with after authorising by user 
![4](https://cloud.githubusercontent.com/assets/12049918/19189130/d41d23fe-8cb3-11e6-83d8-3f7608968cb5.png)
![5](https://cloud.githubusercontent.com/assets/12049918/19189170/056d1856-8cb4-11e6-99b9-a19bbf5181dc.png)

**Comment by ccutrer** [comment]
Can you go to /error_reports and find the error?

**Comment by raveendrau** [comment]
Hi @ccutrer ,

Thanks for your response !

I bit new to dev tools and web programming. Can you please let me know, How to go to /error reports?

Sorry about that.

**Comment by ccutrer** [comment]
http://192.168.25.133:3000/error_reports assuming your server hasn't changed locations from your initial report

**Comment by raveendrau** [comment]
Hi @ccutrer ,

Thanks very much for your help !

here the same error report 18 times, but copied 18th one only
------------------------------------------------------------------------
#18 Redis is not enabled for this install
account: Bimarian
category: RuntimeError
created at: 2016-10-07 10:37:46 -0600
request context id: b7654076-3ebb-47ee-90f8-30b80c84346f 
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 
HTTP_ACCEPT_ENCODING: gzip, deflate 
HTTP_HOST: 192.168.25.133:3000 
HTTP_REFERER: http://192.168.25.133:3000/login/oauth2/confirm 
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0 
PATH_INFO: /login/oauth2/accept 
QUERY_STRING: ? 
REMOTE_ADDR: 192.168.25.1 
REQUEST_METHOD: POST 
REQUEST_PATH: /login/oauth2/accept 
REQUEST_URI: http://192.168.25.133:3000/login/oauth2/accept 
SERVER_NAME: 192.168.25.133 
SERVER_PORT: 3000 
SERVER_PROTOCOL: HTTP/1.1 
format: text/html 
hostname: ubuntu 
path_parameters: {:controller=>"oauth2_provider", :action=>"accept"} 
pid: 3244 
query_parameters: {} 
request_parameters: {"utf8"=>"✓", "authenticity_token"=>"FUmC3xanfFuqoczdCHWsam+7bzPIJ+DkWTaLr3j8n+tBD+SIWs0Qb+WRtI1AQMc4Ls4tQJF2h4I0DufaT6+tjA=="} 
response_code: 500 
type: 
        Redis is not enabled for this install

        /home/bimarian/canvas-lms/lib/canvas.rb:19:in `redis'
/home/bimarian/canvas-lms/lib/canvas/oauth/token.rb:122:in `generate_code_for'
/home/bimarian/canvas-lms/lib/canvas/oauth/provider.rb:96:in `final_redirect_params'
/home/bimarian/canvas-lms/app/controllers/oauth2_provider_controller.rb:80:in `accept'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:189:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:545:in `block (2 levels) in _run__1767395951439951835__process_action__callbacks'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:212:in `block in _conditional_callback_around_143'
/home/bimarian/canvas-lms/app/controllers/application_controller.rb:333:in `block in enable_request_cache'
/home/bimarian/canvas-lms/lib/temp_cache.rb:7:in `enable'
/home/bimarian/canvas-lms/app/controllers/application_controller.rb:332:in `enable_request_cache'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:211:in `_conditional_callback_around_143'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:424:in `block in _run__1767395951439951835__process_action__callbacks'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:212:in `block in _conditional_callback_around_144'
/home/bimarian/canvas-lms/app/controllers/application_controller.rb:326:in `set_locale'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:211:in `_conditional_callback_around_144'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:423:in `_run__1767395951439951835__process_action__callbacks'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/lib/gems/2.1.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:136:in `process'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:44:in `process'
/var/lib/gems/2.1.0/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiling_methods.rb:79:in `block in profile_method'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:195:in `dispatch'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:231:in `block in action'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:50:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:71:in `block in call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `each'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:676:in `call'
/home/bimarian/canvas-lms/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:61:in `call'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/etag.rb:23:in `call'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/conditionalget.rb:35:in `call'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/head.rb:11:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home/bimarian/canvas-lms/app/middleware/request_throttle.rb:59:in `block in call'
/home/bimarian/canvas-lms/app/middleware/request_throttle.rb:257:in `reserve_capacity'
/home/bimarian/canvas-lms/app/middleware/request_throttle.rb:54:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/flash.rb:241:in `call'
/home/bimarian/canvas-lms/app/middleware/request_context_session.rb:25:in `call'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/session/abstract/id.rb:225:in `context'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/session/abstract/id.rb:220:in `call'
/var/lib/gems/2.1.0/gems/encrypted_cookie_store-instructure-1.1.12/lib/encrypted_cookie_store.rb:47:in `call'
/home/bimarian/canvas-lms/app/middleware/sessions_timeout.rb:22:in `call'
/home/bimarian/canvas-lms/app/middleware/load_account.rb:12:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/cookies.rb:486:in `call'
/var/lib/gems/2.1.0/gems/activerecord-4.0.13/lib/active_record/query_cache.rb:36:in `call'
/var/lib/gems/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:373:in `_run__4219599044840859119__call__callbacks'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/reloader.rb:64:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:38:in `call_app'
/var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:22:in `call'
/var/lib/gems/2.1.0/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'
/home/bimarian/canvas-lms/app/middleware/request_context_generator.rb:49:in `call'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/methodoverride.rb:21:in `call'
/home/bimarian/canvas-lms/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/runtime.rb:17:in `call'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/lock.rb:17:in `call'
/var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/static.rb:84:in `call'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/sendfile.rb:112:in `call'
/var/lib/gems/2.1.0/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiler.rb:193:in `call'
/var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'
/var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:97:in `call'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/content_length.rb:14:in `call'
/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
/var/lib/gems/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
/var/lib/gems/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
/var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/handler/thin.rb:16:in `run'
/var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/server.rb:264:in `start'
/var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/commands/server.rb:84:in `start'
/var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/commands.rb:76:in `block in <top (required)>'
/var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/commands.rb:71:in `tap'
/var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/commands.rb:71:in `<top (required)>'
/home/bimarian/canvas-lms/bin/rails:9:in `require'
/home/bimarian/canvas-lms/bin/rails:9:in `<top (required)>'
/var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
/var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
/var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
/var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
/var/lib/gems/2.1.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
/var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
/var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
/home/bimarian/canvas-lms/bin/spring:16:in `require'
/home/bimarian/canvas-lms/bin/spring:16:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

**Comment by ccutrer** [comment]
Ah, at least that's easy enough to diagnose. Using OAuth with Canvas requires a Redis server (an otherwise optional component). You'll need to install redis server, and then tell Canvas how to connect to it by editing config/redis.yml in your Canvas install directly (you can look at redis.yml.example in that same directory for the format).

**Comment by raveendrau** [comment]
Hi @ccutrer 
my redis version installed as follows: 
```
bimarian@ubuntu:~/canvas-lms$ redis-server --version
Redis server v=3.0.7 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=869e89100d5ea8c2
```
I have installed started using 
````
redis-server /etc/redis/redis.conf
````

[redis.txt](https://github.com/instructure/canvas-lms/files/519081/redis.txt)
[cache_store.txt](https://github.com/instructure/canvas-lms/files/519082/cache_store.txt)

and please find attached `redis.yml` and `cache_store.yml`
But still nochange in error in development.log says
````
RuntimeError (Redis is not enabled for this install):
  /home/bimarian/canvas-lms/lib/canvas.rb:19:in `redis'
  /home/bimarian/canvas-lms/lib/canvas/oauth/token.rb:122:in `generate_code_for'
  /home/bimarian/canvas-lms/lib/canvas/oauth/provider.rb:96:in `final_redirect_params'
  /home/bimarian/canvas-lms/app/controllers/oauth2_provider_controller.rb:80:in `accept'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:189:in `process_action'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:545:in `block (2 levels) in _run__3258986629140977324__process_action__callbacks'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:212:in `block in _conditional_callback_around_248'
  /home/bimarian/canvas-lms/app/controllers/application_controller.rb:333:in `block in enable_request_cache'
  /home/bimarian/canvas-lms/lib/temp_cache.rb:7:in `enable'
  /home/bimarian/canvas-lms/app/controllers/application_controller.rb:332:in `enable_request_cache'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:211:in `_conditional_callback_around_248'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:424:in `block in _run__3258986629140977324__process_action__callbacks'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:212:in `block in _conditional_callback_around_249'
  /home/bimarian/canvas-lms/app/controllers/application_controller.rb:326:in `set_locale'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:211:in `_conditional_callback_around_249'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:423:in `_run__3258986629140977324__process_action__callbacks'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /var/lib/gems/2.1.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:136:in `process'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:44:in `process'
  /var/lib/gems/2.1.0/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiling_methods.rb:79:in `block in profile_method'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:195:in `dispatch'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:231:in `block in action'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:50:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:71:in `block in call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `each'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:676:in `call'
  /home/bimarian/canvas-lms/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:61:in `call'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/etag.rb:23:in `call'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/conditionalget.rb:35:in `call'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/head.rb:11:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /home/bimarian/canvas-lms/app/middleware/request_throttle.rb:59:in `block in call'
  /home/bimarian/canvas-lms/app/middleware/request_throttle.rb:257:in `reserve_capacity'
  /home/bimarian/canvas-lms/app/middleware/request_throttle.rb:54:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/flash.rb:241:in `call'
  /home/bimarian/canvas-lms/app/middleware/request_context_session.rb:25:in `call'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/session/abstract/id.rb:225:in `context'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/session/abstract/id.rb:220:in `call'
  /var/lib/gems/2.1.0/gems/encrypted_cookie_store-instructure-1.1.12/lib/encrypted_cookie_store.rb:47:in `call'
  /home/bimarian/canvas-lms/app/middleware/sessions_timeout.rb:22:in `call'
  /home/bimarian/canvas-lms/app/middleware/load_account.rb:12:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/cookies.rb:486:in `call'
  /var/lib/gems/2.1.0/gems/activerecord-4.0.13/lib/active_record/query_cache.rb:36:in `call'
  /var/lib/gems/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:373:in `_run__1799446620544023260__call__callbacks'
  /var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/reloader.rb:64:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:38:in `call_app'
  /var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:22:in `call'
  /var/lib/gems/2.1.0/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'
  /home/bimarian/canvas-lms/app/middleware/request_context_generator.rb:49:in `call'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/methodoverride.rb:21:in `call'
  /home/bimarian/canvas-lms/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/runtime.rb:17:in `call'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/lock.rb:17:in `call'
  /var/lib/gems/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/static.rb:84:in `call'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/sendfile.rb:112:in `call'
  /var/lib/gems/2.1.0/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiler.rb:193:in `call'
  /var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'
  /var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:97:in `call'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/content_length.rb:14:in `call'
  /var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
  /var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
  /var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
  /var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
  /var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
  /var/lib/gems/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
  /var/lib/gems/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
  /var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
  /var/lib/gems/2.1.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/handler/thin.rb:16:in `run'
  /var/lib/gems/2.1.0/gems/rack-1.5.4/lib/rack/server.rb:264:in `start'
  /var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/commands/server.rb:84:in `start'
  /var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/commands.rb:76:in `block in <top (required)>'
  /var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/commands.rb:71:in `tap'
  /var/lib/gems/2.1.0/gems/railties-4.0.13/lib/rails/commands.rb:71:in `<top (required)>'
  /home/bimarian/canvas-lms/bin/rails:9:in `require'
  /home/bimarian/canvas-lms/bin/rails:9:in `<top (required)>'
  /var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
  /var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
  /var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
  /var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
  /var/lib/gems/2.1.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
  /var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
  /var/lib/gems/2.1.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
  /home/bimarian/canvas-lms/bin/spring:16:in `require'
  /home/bimarian/canvas-lms/bin/spring:16:in `<top (required)>'
  bin/rails:3:in `load'
  bin/rails:3:in `<main>'

```

**Comment by tierra** [comment]
Your `redis.yml` (attached txt above) doesn't look like valid YML. You have some hard tabs in there, along with incorrectly indented settings. It looks like this:

```
development:
	servers:
    	- redis://localhost
```

But it should look like this:

```
development:
  servers:
    - redis://localhost
```

**Comment by raveendrau** [comment]
Thank you friends
