### ISSUE TITLE
Some links don't work

### ISSUE THREAD

**Issue by arshie92** [instructure/canvas-lms#916]
Hi.
I have done a quick start installation of canvas-lms. It works well, but when I want to access to some links like edit settings of the user, it doesn't work.

![edit_settings](https://cloud.githubusercontent.com/assets/19706604/19235599/3805378c-8ee2-11e6-801a-b2bd27a8eec9.png)

**Comment by tierra** [comment]
Considering that the icons aren't rendering in your screenshot, I'm guessing that you haven't successfully compiled the assets entirely. Clearly the CSS compiled, but fonts and likely Javascript didn't. This is probably one such action that requires Javascript to handle some of the interaction with those buttons.

Try running this again, and posting any errors to help debug:

```
bundle exec rake canvas:compile_assets
```

**Comment by simonista** [comment]
Closing due to lack of response.
