### ISSUE TITLE
Ubuntu 16.04 support - Undumpable Exception -- #<RuntimeError: error running dress_code>

### ISSUE THREAD

**Issue by sibil** [instructure/canvas-lms#917]
### Summary:

https://github.com/instructure/canvas-lms/wiki/Production-Start recommends latest Ubuntu LTS.
I'm trying to install open source Canvas on Ubuntu 16.04. Got errors when compiling assets.

Setting locale/encoding didn't help.
Tried setting  RUBYOPT as recommended by another thread. Didn't help as well.
export RUBYOPT="-KU -E utf-8:utf-8"
Has anyone faced this? Any suggestions on how to proceed?

$$ RAILS_ENV=production bundle exec rake canvas:compile_assets
Error messages:
Building client app 'canvas_quizzes'
        Running 'npm install'...
/var/canvas/vendor/bundle/ruby/2.2.0/gems/pygments.rb-0.5.4/lib/pygments/popen.rb:261:in `rescue in mentos': EPIPE (MentosError)
        from /var/canvas/vendor/bundle/ruby/2.2.0/gems/pygments.rb-0.5.4/lib/pygments/popen.rb:213:in`mentos'
        from /var/canvas/vendor/bundle/ruby/2.2.0/gems/pygments.rb-0.5.4/lib/pygments/popen.rb:202:in `highlight'
        from /var/canvas/vendor/bundle/ruby/2.2.0/bundler/gems/dress_code-574382160ee4/lib/dress_code/renderer.rb:8:in`block_code'
        from /var/canvas/vendor/bundle/ruby/2.2.0/bundler/gems/dress_code-574382160ee4/lib/dress_code/document.rb:23:in `render'
        from /var/canvas/vendor/bundle/ruby/2.2.0/bundler/gems/dress_code-574382160ee4/lib/dress_code/document.rb:23:in`to_html'
        from /var/canvas/vendor/bundle/ruby/2.2.0/bundler/gems/dress_code-574382160ee4/lib/dress_code/generator.rb:47:in `map_doc'
        from /var/canvas/vendor/bundle/ruby/2.2.0/bundler/gems/dress_code-574382160ee4/lib/dress_code/generator.rb:41:in`block in map_docs'
        from /var/canvas/vendor/bundle/ruby/2.2.0/bundler/gems/dress_code-574382160ee4/lib/dress_code/generator.rb:41:in `map'
        from /var/canvas/vendor/bundle/ruby/2.2.0/bundler/gems/dress_code-574382160ee4/lib/dress_code/generator.rb:41:in`map_docs'
        from /var/canvas/vendor/bundle/ruby/2.2.0/bundler/gems/dress_code-574382160ee4/lib/dress_code/generator.rb:22:in `generate'
        from /var/canvas/vendor/bundle/ruby/2.2.0/bundler/gems/dress_code-574382160ee4/bin/dress_code:95:in`<top (required)>'
        from bin/dress_code:16:in `load'
        from bin/dress_code:16:in`<main>'
npm WARN canvas_quizzes@1.0.0 No license field.
++++++++++++++++++++
--> Finished: 'js:build' in 143.55170389500017
--> Finished: 'compile coffee, js 18n, run r.js optimizer, and webpack' in 222.42746450699997
rake aborted!
Undumpable Exception -- #<RuntimeError: error running dress_code>
/var/canvas/vendor/bundle/ruby/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/var/canvas/vendor/bundle/ruby/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:280:in`block (4 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/var/canvas/vendor/bundle/ruby/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:279:in`block (3 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/var/canvas/vendor/bundle/ruby/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:273:in`block (2 levels) in work_in_processes'
/var/canvas/vendor/bundle/ruby/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
### Steps to reproduce:
1. Use Ubuntu 16.04
2. Follow instructions at https://github.com/instructure/canvas-lms/wiki/Production-Start
3. "RAILS_ENV=production bundle exec rake canvas:compile_assets" gives errors.

**Comment by slartimitvar** [comment]
I ran into several undumpable "rake aborted" exceptions while trying to compile assets.
Most of them I was able to remedy by setting the executable permission on the script which it halted at.

One was a little more strange in that a javascript file simply contained a file path reference to another file. I had to replace that with a symbolic link and it all worked from there. The file was /var/canvas/public/javascripts/InstUI.js

**Comment by simonista** [comment]
Hey @sibil, did you ever get this resolved?

**Comment by sibil** [comment]
@simonista - Yes.  Installing python-software-properties fixed the problem.
sudo apt-get -y install python-software-properties

Switched to Ruby 2.2 as well.
//Switch to Ruby 2.2 (Canvas does not support 2.3)
sudo rm /usr/bin/ruby
sudo ln -s /usr/bin/ruby2.2 /usr/bin/ruby

Thanks.
