### ISSUE TITLE
Privacy Level defaults to anonymous for LTI 2.0 proxies 

### ISSUE THREAD

**Issue by MartinLenord** [instructure/canvas-lms#918]
### Summary:

Despite the canvas consumer profile claiming that the `Person.email.primary` capability is offered, the `lis_person_contact_email_primary` is never passed on an LTI launch. This appears to be because there is no way of specifying the privacy level so "anonymous" is assumed.
### Steps to reproduce:
1. Log in as an account admin
2. Go to `Admin > Account > Settings > Apps > View App Configurations`
3. Click `+ App` And use the `LTI 2 Registration URL` Configuration Type
4. Set up an LTI 2.0 tool that requires the `Person.email.primary` capability in the proxy
5. Create a new assignment with the submission type of external tool and find the proxy that was just set up
6. Save and publish the assignment
7. The launch won't include the `lis_person_contact_email_primary` parameter
### Expected behavior:

The LTI launch honors the contract of the tool proxy and sends the `lis_person_contact_email_primary` parameter.
### Additional notes:

The capabilities offered by canvas in their tool consumer profile are 

```
    "capability_offered": [
        "basic-lti-launch-request",
        "User.id",
        "Canvas.api.domain",
        "LtiLink.custom.url",
        "ToolProxyBinding.custom.url",
        "ToolProxy.custom.url",
        "Canvas.placements.accountNavigation",
        "Canvas.placements.courseNavigation",
        "Canvas.placements.assignmentSelection",
        "Canvas.placements.linkSelection",
        "Canvas.placements.postGrades",
        "User.username",
        "Person.email.primary",
        "Person.name.given",
        "Person.name.family",
        "Person.name.full",
        "CourseSection.sourcedId",
        "Person.sourcedId",
        "Membership.role",
        "ToolConsumerProfile.url",
        "OAuth.splitSecret"
    ],
```

Resource handler message in the tool proxy used to register the LTI tool proxy

```
"message": [
    {
        "path": "test/endpoint",
        "parameter": [],
        "message_type": "basic-lti-launch-request",
        "enabled_capability": [
            "Membership.role",
            "Person.email.primary",
            "Person.name.family",
            "Person.name.full",
            "Person.name.given",
            "User.id"
        ]
    }
],
```

**Comment by MartinLenord** [comment]
Interesting note:
If you use the email address as a custom parameter in the proxy by adding 
```
"parameter":[
    {
        "name":"email_address",
        "variable":"Person.email.primary"
    }
],
```
the email address is passed.

So it is only the default lis parameter that doesn't get passed

**Comment by rivernate** [comment]
@MartinLenord thanks for reporting this, we have a fix in the works for it.  I'll give you and update once it is merged.
