### ISSUE TITLE
Context.id not listed as an LTI capability despite it being passed on every launch

### ISSUE THREAD

**Issue by MartinLenord** [instructure/canvas-lms#919]
### Summary:

In the capabilities offered by canvas (defined here https://github.com/instructure/canvas-lms/blob/2f7557fc4580893dcec3689d5c5720d2935e74e7/app/models/lti/tool_consumer_profile_creator.rb#L8) the `Context.id` capability is not included, but is always sent as a parameter when a launch is done 
### Steps to reproduce:
1. Log in as an account admin
2. Go to `Admin > Account > Settings > Apps > View App Configurations`
3. Click `+ App` And use the `LTI 2 Registration URL` Configuration Type
4. View the consumer profile that is generated (it won't contain `Context.id`)
5. Set up an LTI 2.0 tool
6. Create a new assignment with the submission type of external tool and find the proxy that was just set up
7. Save and publish the assignment
8. The launch will include the `context_id` parameter
### Expected behavior:

The consumer profile provided by canvas should include "Context.id"
### Additional notes:

The LTI 2.0 spec labels context_id as recommended so a tool setting up a proxy cannot assume that it will receive it, causing issues if it is a requirement of the side of the tool https://www.imsglobal.org/specs/ltiv2p0/implementation-guide#toc-42

**Comment by rivernate** [comment]
@MartinLenord thanks for reporting this, we are working on fixing this.  Most likely we will stop sending it by default, and add it to the capabilities list. Then to receive it you will have to include it in your enabled capabilities.  I will give you an update once that change is released.
