### ISSUE TITLE
Canvas local build not able Access Token Request 401 Unautherised

### ISSUE THREAD

**Issue by raveendrau** [instructure/canvas-lms#928]
### Steps to reproduce:

 1. Using local build created developer and redis installed successfully and achieving along with `code`.
 2.  When I am trying for next step POST in RESTClient addon in mozzilla fire fox I entered following     URL:http://localhost:3000/login/oauth2/token
body: grant_type=authorization_code&client_id=10000000000001&client_secret=wYKMKCigqhDpPS2fsJNRT6wp8DuBBAoRwhhZhP1adDidMWt8dYcxkfpaCfQzmzI2&redirect_uri=http://localhost:8080&code=5e2651f7549b6de2b6cae1aeb96708d070ea2bb24d11931cf1842250be387e5075c99579a57428a2ab733c0fa502546bcbd758fcd96318ee2a55a2bc5f7714b8#

 3. 

### Expected behavior:
Access Token should be  returned

### Additional notes:
In RESTClient Response Headers , Response body and some restclient screenshots

 as follows:

Response Headers :

````
   Status Code: 401 Unauthorized
    Cache-Control: no-cache
    Connection: close
    Content-Type: application/json; charset=utf-8
    Server: thin
    Set-Cookie: _csrf_token=g%2BAYSkJZJt2gwJeC8jw%2F3ADk8XZqGjsJL%2Fo4VI0IffrMgigIGxR8jsiJ0uqnBGvpV4GaEBx7TjkAzU5muVAUtg%3D%3D; path=/
    WWW-Authenticate: Canvas OAuth 2.0
    X-Canvas-Meta: b=715420;m=715420;u=0.02;y=0.00;d=0.02;
    X-Canvas-User-Id: 10000000000003
    X-Rate-Limit-Remaining: 600.0
    X-Request-Context-Id: cbc98ae2-a203-4b73-b9ed-a1844761069c
    X-Request-Cost: 0.036257784000003124
    X-Runtime: 0.123701
    X-Session-Id: 6c4f94706954f5d1ba5212bc4850aaf5
    X-UA-Compatible: IE=Edge,chrome=1
    X-XSS-Protection: 1; mode=block
    x-content-type-options: nosniff
```

Response body: 

```
{
  "error": "invalid_client",
  "error_description": "unknown client"
}

```
And some screen shots of rest client:
![6](https://cloud.githubusercontent.com/assets/12049918/19440490/bc4d2316-949f-11e6-8bfb-84e23a1d02c1.png)
![7](https://cloud.githubusercontent.com/assets/12049918/19440496/c2f25768-949f-11e6-83ba-b1e303d80c6c.png)
![8](https://cloud.githubusercontent.com/assets/12049918/19440504/c8024312-949f-11e6-8cb6-8918b431527f.png)

**Comment by bertop89** [comment]
Did you manage to get a solution for this?

**Comment by tierra** [comment]
In the issue description here, @raveendrau says they entered `grant_type=authorization_code` in the URL, however, the screenshots say otherwise, and that would trigger an `invalid_client` error code. I'm fairly certain this is an invalid issue.

**Comment by NSExceptional** [comment]
I'm also having this issue. Can't even get it to work in Postman's automated Authorization flow.
