### ISSUE TITLE
Text descriptions longer than 256 characters cause 500 error on LTI 2.0 registration

### ISSUE THREAD

**Issue by MartinLenord** [instructure/canvas-lms#931]
### Summary:

The `tool_profile.product_instance.product_info.description.default_value` causes a 500 error if its value is longer than 256 characters.
### Steps to reproduce:
1. Log in as an account admin
2. Go to `Admin > Account > Settings > Apps > View App Configurations`
3. Click `+ App` And use the `LTI 2 Registration URL` Configuration Type
4. Try and register a tool that returns a proxy with a description with more than 256 characters
5. Registration will return a 500 error
### Expected behavior:

The proxy should register successfully
### Additional notes:

I can't find anywhere in the LTI spec that specifically states the max length of a description, but either way this should not result in a 500 error

**Comment by rivernate** [comment]
@MartinLenord thanks for reporting this.  We should have a fix released shortly.  I'll give you an update once  this is released.
