### ISSUE TITLE
Trailing slashes dropped from LTI launch URLs

### ISSUE THREAD

**Issue by cjford** [instructure/canvas-lms#935]
### Summary:

When entering a launch URL for an LTI app, inputs with trailing slashes are accepted, but when the request is made, the trailing slash is absent.
### Steps to reproduce:
1. Navigate to /accounts/{id}/settings/configurations -> "Apps" tab -> "+ App" button
2. Enter valid LTI app configuration, with the "Launch URL" field value including a trailing slash (e.g. "http://www.example.com/", as opposed to "http://www.example.com")
3. Launch the app, and observe via network tab or server logs that the request is made without the trailing slash
### Expected behavior:

LTI launch requests should either honor trailing slashes (and lack thereof), or at least have consistency between displayed tool settings and tool behavior . 
### Additional notes:

While this rarely makes much difference, I did run into trouble when upgrading from Phusion Passenger 4.0.53 to 5.0.30 on the server running an LTI app. Previously Passenger would set the PATH_INFO environment variable to an empty string for requests with no trailing slash. After the upgrade, PATH_INFO gets set to "/" instead. As a result, when using the [ims-lti gem](https://github.com/instructure/ims-lti) to validate OAuth signatures, requests from Canvas missing the trailing slash will never be valid. Canvas signs the request with the slashless URL, whereas the gem, having received "/" as PATH_INFO, calculates a different signature. 

This very well may be a Passenger issue, but it's tricky to tell from a web server perspective if this is intended, technically correct, or not. It's also not particularly hard for an LTI app to work around the issue, by stripping trailing slashes before validating the signature. 

By allowing trailing slashes in launch URLs, Canvas could add the flexibility to accommodate potentially variable web server methods of handling path info. Although I realize the tradeoff there may be a more error-prone process for end users setting up LTI tools. Ultimately, the problem is not that trailing slashes aren't allowed, but that it's not clear they will be ignored. Currently, tool creation will accept, store, and continue to display a trailing slash in settings, but still makes requests without it. At the very least, the behavior of the tool launch should be consistent with the settings shown in Canvas.

I can only hope I've correctly diagnosed the situation here. It may not warrant a change but I would be interested in hearing thoughts on it. In any case, may this issue save another developer from some rather painful OAuth signature debugging.

**Comment by ccutrer** [comment]
When doing an HTTP request, it's impossible to do one with "http://someserver" and no trailing slash, because HTTP doesn't send the full URI. It uses the scheme to determine if it should use SSL or not, the authority to know which server to connect to (and to set the Host header to), and the remainder is an _absolute_ path sent in the request line. So yes, it's definitely incorrect for Canvas to calculate the signature based on a full URI with no path component whatsoever, and is not a problem with your web server, or your signature validation.

**Comment by cjford** [comment]
Sorry, not sure I follow. I fear I may have overly convoluted things by bringing up OAuth - ultimately the only relevance of it was to show an example where the presence or absence of the trailing slash actually matters. 

What I mean by trailing slash is the one following the absolute path sent in the request line. 

So, for example, if I type into my browser:
http://www.someserver.com/lti_path

The relevant parts of my HTTP request should look something like this, correct?
GET /lti_path HTTP/1.1
Host: someserver.com


If I instead type the same but with a trailing slash:
http://www.someserver.com/lti_path/

I get this:
GET /lti_path/ HTTP/1.1
Host: someserver.com


So the crux of the issue is simply this. My LTI configuration shows this:
http://www.someserver.com/lti_path/

When launching, my request looks like this:
GET /lti_path HTTP/1.1
Host: someserver.com

But it should look like this
GET /lti_path/ HTTP/1.1
Host: someserver.com

The only real problem here is the inconsistency between what the LTI settings show for the launch URL (notably, the path portion of that), and the path to which the request is actually made when launching it. I don't think Canvas is calculating the signature incorrectly at all, it's just a problem with the misleading nature that launch URLs are stored and displayed in external tool configs.

**Comment by ccutrer** [comment]
Right, sorry for going too deep into the technical details. Short version: yes, this should be fixed.
