### ISSUE TITLE
API has_submitted_submissions always returns true and cannot access submissions

### ISSUE THREAD

**Issue by jackhughesweb** [instructure/canvas-lms#936]
### Summary:
When calling the API from a student account to an assignment, has_submitted_submissions always returns true and and the submissions endpoint returns 401

### Steps to reproduce:

 1. Create an assignment for a file upload
 2. Create a student user who is enrolled onto the course and is required to complete the assignment
 3. Without uploading anything, call the API endpoint for the assignment using a token generated by the student account
4. The attribute for has_submitted_submissions returns true
5. Access the submissions endpoint for the assignment to check the value of this, but 401 Unauthorized is returned

### Expected behavior:
has_submitted_submissions is true or false dependant in a file uploaded or a quiz completed etc., and the submissions endpoint returns the user's submission details for the assignment.

**Comment by jackhughesweb** [comment]
I think for the first part, I may be misunderstanding 'has_submitted_submissions' as "I have submitted the required submissions" instead of it possibly actually meaning "This assignment requires a submission to be submitted to it", however the problem of not being able to access a student's submissions from their own account via the API still exists.

**Comment by simonista** [comment]
`has_submitted_submissions` actually means "this assignment has been submitted to (by anyone), at least once.  it does seem a little weird that this field is available to students, I believe it is meant as a flag for teachers.

https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.show should allow a student to view their submission to an assignment.
