### ISSUE TITLE
Install error message on  "rake db:initial_setup"

### ISSUE THREAD

**Issue by llliii** [instructure/canvas-lms#955]
### Summary:
I try setup production canvas on ubuntu-14.05,
got some error after  last undate.

### Steps to reproduce:

1. Database population
`RAILS_ENV=production bundle exec rake db:initial_setup`

2. get message: 
rake aborted!
Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 12 column 16
/var/canvas/vendor/bundle/ruby/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:149:in `load'
/var/canvas/config/application.rb:164:in `load'
/var/canvas/vendor/bundle/ruby/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb:29:in `safe_load'
/var/canvas/vendor/bundle/ruby/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml.rb:12:in `load_with_options'
/var/canvas/lib/config_file.rb:45:in `load'
/var/canvas/lib/host_url.rb:34:in `domain_config'
/var/canvas/lib/host_url.rb:67:in `default_host'
/var/canvas/lib/tasks/db_load_data.rake:31:in `block (2 levels) in <top (required)>'
/var/canvas/lib/tasks/db_load_data.rake:246:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.2.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:load_initial_data => db:configure_admin => db:load_environment
(See full trace by running task with --trace)

### Expected behavior:
Does anyone know how to fixed it?  Many thanks
### Additional notes:

**Comment by tierra** [comment]
Sounds like you have a syntax error in one of your YML config files, most likely `config/domain.yml`

**Comment by llliii** [comment]
yes, I off the "filesname".
I don't know why will be that.    
Thanks.
