### ISSUE TITLE
Can u support file upload for aliyun?

### ISSUE THREAD

**Issue by qx** [instructure/canvas-lms#956]
https://oss.console.aliyun.com/index#/  like amazon's s3.

**Comment by ccutrer** [comment]
I can't find a definitive answer to this, but if Aliyun is truly API compatible with S3, then it should be as simple as changing your amazon_s3.yml to point to an Aliyun endpoint. Otherwise, no, we do not plan on adding additional code to support niche Amazon clones.

**Comment by qx** [comment]
I'd like to use amazon,but can't, because GFW in china. It's pity.

**Comment by kenxt** [comment]
I think that aliyun s3 will work well, our own self-hosted canvas works well with local S3 compatible system.
