### ISSUE TITLE
[Time Sensitive] Quick Start: Database population - Incompatible library version with nokogiri

### ISSUE THREAD

**Issue by phxlin** [instructure/canvas-lms#957]
While I was following the "Quick Start" instruction, I got stuck at the "Database population" step. I think I got everything above correctly. But when I typed in `$GEM_HOME/bin/bundle exec rake db:initial_setup`, I got this error:

> rake aborted!
LoadError: dlopen(/Users/Yufan/.rvm/gems/ruby-2.1.6/bundler/gems/nokogiri-xmlsec-me-harder-57d071040cc4/lib/nokogiri_ext_xmlsec.bundle, 9): Library not loaded: libxml2.2.dylib
  Referenced from: /Users/Yufan/.rvm/gems/ruby-2.1.6/bundler/gems/nokogiri-xmlsec-me-harder-57d071040cc4/lib/nokogiri_ext_xmlsec.bundle
  Reason: Incompatible library version: nokogiri_ext_xmlsec.bundle requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0 - /Users/Yufan/.rvm/gems/ruby-2.1.6/bundler/gems/nokogiri-xmlsec-me-harder-57d071040cc4/lib/nokogiri_ext_xmlsec.bundle

I've tried `gem uninstall nokogiri`, then `NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install nokogiri`   
[https://github.com/sparklemotion/nokogiri/wiki/What-to-do-if-libxml2-is-being-a-jerk](url)

But it still doesn't work for me.

**Comment by tierra** [comment]
It's definitely still trying to link with your system-provided (OSX) libxml2, so it doesn't look like you tried installing a compatible version of libxml2 from brew, as shown in the page you linked.

Another approach is to skip any OSX native libraries, and use Canvas from Docker:
https://github.com/instructure/canvas-lms/tree/master/doc/docker

**Comment by phxlin** [comment]
@tierra Thanks for your suggestion. I followed the Docker installation, and I got an error like this: 

> ERROR: Service 'web' failed to build: The command '/bin/sh -c if [ -e /var/lib/gems/$RUBY_MAJOR.0/gems/bundler-* ]; then BUNDLER_INSTALL="-i /var/lib/gems/$RUBY_MAJOR.0"; fi   && curl -O http://people.mozilla.org/~jkew/woff/woff-code-latest.zip   && unzip woff-code-latest.zip   && make   && cp sfnt2woff /usr/local/bin   && gem uninstall --all --ignore-dependencies --force $BUNDLER_INSTALL bundler   && gem install bundler --no-document -v 1.12.5   && find $GEM_HOME ! -user docker | xargs chown docker:docker' returned a non-zero code: 9

I don't even know how to google for the solution for this one...

**Comment by simonista** [comment]
Hey @phxlin, hopefully you got this sorted out, but if not, I'd try posting over on our google group: groups.google.com/forum/#!forum/canvas-lms-users.  We try to reserve github issues for bugs in the running software, so install issues like this are usually better handled over there.  Thanks!
