### ISSUE TITLE
On paper submissions makred as TurnItIn enabled

### ISSUE THREAD

**Issue by raonath** [instructure/canvas-lms#964]
### Summary:
Canvas has marked a number of homework assignments (in a Math class) with paper submissions as being checked with TurnItIn, apparently because the assignment I created just before (in the same session) was a short history paper that is to be routed thru TurnItIn.

### Steps to reproduce:

 1. First create as assignment with online submission and check the box to enable TurnItIn
 2. Immediately afterwards, create a new assignment with paper submission. Note that the box to enable/disable TurnItIn is not available.
 3. Stop creating assignments and click on the second assginment created on the list of assignments. It will say that TurnItIn is enabled.
Now the only way to fix this is to edit the assignment, change it to online submission, uncheck the TurnItIn box, and change the submission type back to paper.

### Expected behavior:
Paper submissions should not say anything out TurnItIn, that is Canvas should not look at this data field except for online submissions.
<img width="1207" alt="screen shot 2016-12-17 at 7 00 15 am" src="https://cloud.githubusercontent.com/assets/1826580/21286677/6b309928-c428-11e6-9593-b3677ee0b2b7.png">

Alternately, it should have a checkbox for TurnItIn, if Canvas is going to check this data bit.

### Additional notes:

**Comment by simonista** [comment]
Hey @raonath good find!  You may have already discovered this, but you can probably work around this by temporarily changing the submission type to online long enough to un-check the turnitin box.  But you're right that this should be handled for you.
