### ISSUE TITLE
Keep Getting 502 with Self Hosted Canvas when Connecting to Commons 

### ISSUE THREAD

**Issue by aitor-mir** [instructure/canvas-lms#966]
When trying to connect my self hosted installation of Canvas with Commons I keep getting an Nginx 502 error message. I have been following the instructions in https://community.canvaslms.com/docs/DOC-4473 without a problem, but in the last step, when Commons asks for user authorization it always returns this error.

These are the parameters that I am using:

Consumer key: N/A

launch URL: https://lor.instructure.com/api/lti/self-hosted-setup

Custom fields:

name=commons_account_setup
canvas_root_account_id=$Canvas.root_account.id
canvas_parent_account_id=$Canvas.account.id
lis_person_contact_email_primary=$Person.email.primary
canvas_user_id=$Canvas.user.id
canvas_api_domain=$Canvas.api.domain
update_external_tool_url=$Canvas.externalTool.url

Any ideas what could be going wrong in here?

Thanks

**Comment by simonista** [comment]
Hey @aitorclt, did you get this worked out, or are you still having issues?

**Comment by llcit** [comment]
Still getting this error. Haven't had the time yet to debug in depth, but seems like the service is not accepting my connection. It happens at the very last GET

POST 
https://myurl/login/oauth2/accept [HTTP/1.1 302 Found 105ms]
GET 
https://lor.instructure.com/api/oauth/canvas/account-setup-callback  [HTTP/1.1 502 Bad Gateway 32119ms]

**Comment by aitorclt** [comment]
Still getting this error. Haven't had the time yet to debug in depth, but seems like the service is not accepting my connection. It happens at the very last GET

POST
https://myurl/login/oauth2/accept [HTTP/1.1 302 Found 105ms]
GET
https://lor.instructure.com/api/oauth/canvas/account-setup-callback [HTTP/1.1 502 Bad Gateway 32119ms]

**Comment by Revelation1714** [comment]
I know this thread is little old, but I am running into similar issue. When I click Configure, I am getting the error 
Configuration Error
Sorry, there is a problem in your Canvas/Commons configuration.
Please notify your Canvas administrator.
