### ISSUE TITLE
Undated calendar item getting added to calendar

### ISSUE THREAD

**Issue by TheNytangel** [instructure/canvas-lms#970]
### Summary:
When dragging an undated item onto the calendar, the names of all current items displayed on the calendar get changed to the undated item's name

### Images:
Dragging "Internship Evaluation" to the calendar turns the upper image into the lower image

![Before](https://cloud.githubusercontent.com/assets/1778823/21918179/dc64e296-d90b-11e6-8e0c-54a2ae334f2e.png)

---

![After](https://cloud.githubusercontent.com/assets/1778823/21918187/f7d5d184-d90b-11e6-90ad-f1bcf739f37b.png)

### Steps to reproduce:

 1. Go to calendar view
 2. Expand the list of "UNDATED" calendar items
 3. Drag an item onto the calendar

### Expected behavior:
Item gets added to the calendar on the hovered-over date

### Additional notes:
Role: student

**Comment by simonista** [comment]
hey @TheNytangel, thanks for the report.  I can't reproduce this on the current stable branch, can you still?
