### ISSUE TITLE
rake canvas:compile_assets failing

### ISSUE THREAD

**Issue by KasifAdnan** [instructure/canvas-lms#971]
### Summary:
I am trying to compile the assets, but it is failing ,
node -v 
v0.12.18

Note: I have tried reinstalling node . I have tried almost all the solutions out there.
### Steps to reproduce:

 1.rake canvas:compile_assets

### Additional notes:
The complete error log is as follows : 

error compiling sass { [Error: Import directives may not be used within control directives or mixins.]
  cause: 
   { [Error: Import directives may not be used within control directives or mixins.]
     status: 1,
     file: 'app/stylesheets/base/_variables.scss',
     line: 32,
     column: 3,
     message: 'Import directives may not be used within control directives or mixins.',
     formatted: 'Error: Import directives may not be used within control directives or mixins.\n        on line 32 of app/stylesheets/base/_variables.scss\n>>   @import "brand_variables";\n   --^\n' },
  isOperational: true,
  status: 1,
  file: 'app/stylesheets/base/_variables.scss',
  line: 32,
  column: 3,
  formatted: 'Error: Import directives may not be used within control directives or mixins.\n        on line 32 of app/stylesheets/base/_variables.scss\n>>   @import "brand_variables";\n   --^\n' } Error: Import directives may not be used within control directives or mixins.
    at options.error (/home/kasif/Documents/LSI/lms/node_modules/brandable_css/node_modules/node-sass/lib/index.js:286:26) Import directives may not be used within control directives or mixins.
rake aborted!
Error: running BrandableCSS CLI: ./node_modules/.bin/brandable_css 2>&1
/home/kasif/Documents/LSI/lms/lib/brandable_css.rb:102:in `run_cli!'
/home/kasif/Documents/LSI/lms/lib/brandable_css.rb:85:in `compile_all!'
/home/kasif/Documents/LSI/lms/lib/tasks/canvas.rake:121:in `block (3 levels) in <top (required)>'
/home/kasif/Documents/LSI/lms/lib/tasks/canvas.rake:7:in `log_time'
/home/kasif/Documents/LSI/lms/lib/tasks/canvas.rake:121:in `block (2 levels) in <top (required)>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

**Comment by wizkid686** [comment]
Your node version is most likely the issue. Canvas uses node v6 now (not 0.12 anymore). You'll need to uninstall node 0.12, and follow the instructions here (Node v6 is the LTS release): https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

After you reinstall node, delete the node-modules folder and run npm install again. Then try to compile your assets. This should correct the problem.

**Comment by KasifAdnan** [comment]
Thanks for the above steps Ben. However, i am still getting the same error.

**Comment by simonista** [comment]
Hey @KasifAdnan, did you ever get this sorted out or are you still having issues?

**Comment by mominzahid** [comment]
@KasifAdnan  Did you get to solve this issue? I am installing Canvas LMS and I am having a similar problem. However, I was first stuck at npm install. My process was being killed again and again. After trying numerous times, I finally got ahead. But then rake canvas:compile_assets started failing at 'compile css'. 

Please please let me know if you found a solution. I think we have the same issue.

**Comment by mominzahid** [comment]
@simonista If you could, can you please help me with this issue?

**Comment by simonista** [comment]
can you post your ruby/node/npm versions?  you need to be on node 6.9

**Comment by simonista** [comment]
Discussion moved to https://groups.google.com/forum/#!topic/canvas-lms-users/La9hJW_6WqM
