### ISSUE TITLE
Course list sorting does not work when filtered by a search term

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#977]
### Summary:

The account course listing page allows a user to sort the list of courses, and filter the list by a search term. Sorting does not work when the list is filtered by a search term; it works fine when all courses are displayed.

### Steps to reproduce:

 1. Go to your account course list (/accounts/:account_id/courses)
 2. Enter a search term under "Find a Course" and click "Go".
 3. When the search returns, change the sort order under the "Sort" drop-down.

### Expected behavior:

The list should sort according to the user's selection in the Sort drop-down.

### Actual behavior:

The list doesn't sort. :(

### Additional notes:

Verified in production Canvas cloud and open-source stable.

**Comment by simonista** [comment]
Hm, this is working fine for me if I press the "Filter" button after step 3, which it seems like you always have to press after changing the sort order dropdown... maybe it already got fixed by something in the last 14 days...?

**Comment by grahamb** [comment]
I just tested this on the 2017-01-28 release and it's working as expected now. The only recent commit I can see would be 3f99841 but that only seems to apply to environments with master/slave databases, which we don't have.

In any event, looks like this is fixed.
