### ISSUE TITLE
Canvas LMS vs Google Drive integration issue.

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#978]
### Summary:
I met an next error during trying to integrate the Google Drive Vs Canvas LMS: 
"while(1);{"error":"invalid_client","error_description":"unknown client","message":"invalid client_id"}"

### Steps to reproduce:
I have based on this tutorial:  https://github.com/instructure/canvas-lms/wiki/Canvas-Integration#google-drive 

On console.developers.google.com page:
- Google Drive API was enabled and required settings was configured.  
- the client_secrets.json was downloaded.

on the Canvas LMS side.
- navigated to Google Drive plugin and applied the client_secrets.json there and enabled plugin;
- Goes to my profile configuration and authorized the "Google Drive" so it appears at Registered services section like:
https://www.screencast.com/t/ejIp7wpe

After this I navigated to one my course and clicked on "Google Drive" button and got the error:
https://www.screencast.com/t/XPwaUNN9

Perhaps someone could shed some light to me.
Thanks.

**Comment by noriando** [comment]
Hi,

I encounter the same issue.
Google drive is working from collaboration but face the same error when I click google drive set up from external app.

Did you find any solution?

**Comment by ally1** [comment]
Hi there,

Unfortunately we stuck on this issue and were forced to drop idea.
