### ISSUE TITLE
API: Edit assignment call incorrectly returns HTTP 201 response code

### ISSUE THREAD

**Issue by ToeBee** [instructure/canvas-lms#979]
The [Edit an assignment](https://canvas.instructure.com/doc/api/assignments.html#method.assignments_api.update) API call is returning an HTTP 201 "Created" response code. This makes no sense for an edit call. It should be returning 200.

**Comment by ToeBee** [comment]
We received a response on this when we opened up support tickets for all of my GitHub issues. The response was that basically the same function gets called for create and edit and it returns a 201. So while they acknowledged that this is technically incorrect, they aren't going to fix it because it's been this way for a long time and something may be depending on it.

**Comment by ToeBee** [comment]
Got another update. Instructure has reconsidered this and will be fixing it after all. No ETA but our ticket did at least get sent to engineering.

**Comment by simonista** [comment]
Fixed, see above
