### ISSUE TITLE
Responsive Email Notifications

### ISSUE THREAD

**Issue by johndyer** [instructure/canvas-lms#981]
### Summary:
Current emails sent for Canvas notifications (Discussions, etc.) have a fixed width, so they do not scale for mobile phones

### Steps to reproduce:

 1. Receive an email from Canvas
 2. Try to read it on your phone
 3. Pinch, zoom, cry

### Expected behavior:
The email template should have responsive HTML/CSS so it displays well on all email clients and mobile devices. I will submit a pull request with a new template.

### Additional notes:
There have been several requests for branded notifications (https://community.canvaslms.com/ideas/1171, https://community.canvaslms.com/ideas/2734, https://community.canvaslms.com/ideas/6843) but they did not receive enough votes. I see a stub for `custom_logo` so if this is accepted it might be nice to also implement that. I would probably move the logo up to the top if it were branded.

**Comment by johndyer** [comment]
Here is the potential update I've built that I can put in a pull request as soon as my username is approved. I personally like the logo at the top, but probably only if it is customizable. You might also consider removing the light gray background since that is a major change from current design:

<img width="732" alt="canvas-responsive-1-desktop" src="https://cloud.githubusercontent.com/assets/214227/22595570/a10612d6-e9ed-11e6-8a4c-6d03122d4a2e.png">
<img width="400" alt="canvas-responsive-1-mobile" src="https://cloud.githubusercontent.com/assets/214227/22595569/a102b938-e9ed-11e6-8f31-75a31a9cb003.png">
<img width="706" alt="canvas-responsive-2-desktop" src="https://cloud.githubusercontent.com/assets/214227/22595571/a1082a58-e9ed-11e6-940d-9a7321ab498a.png">

**Comment by simonista** [comment]
Thanks for the report @johndyer, i'm going to continue the conversation over on the pull request you sent.

Here's an example of an existing notification, for reference: <img width="1009" alt="screenshot 2017-02-06 12 59 18" src="https://cloud.githubusercontent.com/assets/60822/22664027/2ba9650c-ec6c-11e6-90ea-c47f6de3b9f3.png">
