### ISSUE TITLE
Issue with Bundler

### ISSUE THREAD

**Issue by clnetowner** [instructure/canvas-lms#982]
### Summary
Hello! I'm a beginner with many of the languages used by Canvas so I apologize if this may seem a bit nieve of a question, but I hope you all can help. I am trying to install Canvas Quick Start on a box with Ubuntu 16.04 Desktop LTS and I keep running into the same message. Can anyone please show me how to get past this issue?

Thanks!

Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.................
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (<= 1.13.7, >= 1.10.3)

    rails (= 4.2.7.1) was resolved to 4.2.7.1, which depends on
      bundler (< 2.0, >= 1.3.0)

  Current Bundler version:
    bundler (1.14.3)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (<= 1.13.7, >= 1.10.3)', which is required by gem
'rails (= 4.2.7.1)', in any of the sources.
Error installing required gems.  Please run 'bundle install' manually and try again

**Comment by ccutrer** [comment]
The error is that you're using bundler 1.14.3, and Canvas will not allow anything newer than 1.13.7 (as of the stable release you're using). You need to uninstall bundler, and install an acceptable version with `gem install bundler -v 1.13.7`
