### ISSUE TITLE
Simple documentation error

### ISSUE THREAD

**Issue by JohnKacz** [instructure/canvas-lms#985]
### Summary: 
I believe there is a documentation error [here](https://github.com/instructure/canvas-lms/blob/2f7557fc4580893dcec3689d5c5720d2935e74e7/app/controllers/peer_reviews_api_controller.rb#L120). 

### Steps to reproduce:

 1. Go to line 120 of the peer review api controller
 2. See that it says create instead of delete on the destroy method 
 3. PROFIT!!!

### Expected behavior:
"@API Create Peer Review" should be "@API Delete Peer Review"

### Additional notes:
Sorry, this isn't a PR :)

**Comment by simonista** [comment]
Heh, good catch @JohnKacz, i'll push up a fix!
