### ISSUE TITLE
Quick Question about Canvas Integrations

### ISSUE THREAD

**Issue by SCKelemen** [instructure/canvas-lms#986]
Is it possible for users (students and teachers) to add integrations, or are extensions only for the institution side?

**Comment by simonista** [comment]
Students cannot add integrations.  Teachers, by default, can add LTI tool integrations, but some accounts may have this more locked down.  See http://guides.instructure.com/m/4152/c/34222 for more details.

**Comment by SCKelemen** [comment]
Thanks.
