### ISSUE TITLE
Problem adding items to a course module list

### ISSUE THREAD

**Issue by jamgregory** [instructure/canvas-lms#987]
### Summary:

Our courses on our self-hosted Canvas are laid out using the 'course module' format. Since upgrading to the 2017-01-09 stable release, whenever a new file is uploaded to a module, the upload dialog hangs with a 'progress' indicator and does not add the item to the list. "Uncaught TypeError: Cannot read property 'errors' of undefined" is displayed in the JavaScript console.

### Steps to reproduce:

 1. Go to a course on Canvas
 2. Add a new item to the module, but choose to upload a new file
 3. Click 'Add Item'

### Expected behavior:

The dialog should disappear and the item should be present in the module list. Instead, the dialog hangs indefinitely and "Uncaught TypeError: Cannot read property 'errors' of undefined" is displayed in the JavaScript console.

**Comment by simonista** [comment]
Hey @jamgregory, I just tried reproducing this in our production account, and can't.  That means it either is fixed in the latest stable (2017-01-28), or could be a problem with your setup somehow.

Are you using local or s3 file storage?  Is there anything relevant in `/error_reports` or in your `production.log` file?

**Comment by jamgregory** [comment]
Hi @simonista, thanks for your reply. We're using local storage, and I can't see anything relevant in `/error_reports` unfortunately. I'll look at getting our site updated to stable in the near future and see if that fixes it.

**Comment by simonista** [comment]
Sounds good, I'm going to close this for now but feel free to reopen if you're still seeing it after getting to latest stable.  Good luck!
