### ISSUE TITLE
Canvas API doesn't accept files with % in contents

### ISSUE THREAD

**Issue by wspr** [instructure/canvas-lms#989]
I’m trying to add content to Canvas using its API.
After much frustration (probably due to ignorance) I discovered that a file or command being sent via PUT cannot contain a % symbol.
 
Example that shows the system working:
 
> curl -X PUT -H "Authorization: Bearer \<TOKEN\>" "https://myuni.adelaide.edu.au/api/v1/courses/24570/pages/project-charter" -d "wiki_page[body]=hello”

This produces output:
 
> {"title":"Project Charter","created_at":"2016-12-15T22:43:01Z","url":"project-charter","editing_roles":"teachers","page_id":597217,"last_edited_by":{"id":2898,"display_name":"Will Robertson","avatar_image_url":"https://secure.gravatar.com/avatar/ea4cabae31a573127d27ec4fd0670680?s=50\u0026d=https%3A%2F%2Fmyuni.adelaide.edu.au%2Fimages%2Fmessages%2Favatar-50.png","html_url":"https://myuni.adelaide.edu.au/courses/24570/users/2898"},"published":true,"hide_from_students":false,"front_page":false,"html_url":"https://myuni.adelaide.edu.au/courses/24570/pages/project-charter","updated_at":"2017-02-08T02:55:15Z","locked_for_user":false,"body":"hello”}
 
 
Example that shows the system not working:
 
> curl -X PUT -H "Authorization: Bearer \<TOKEN\>" "https://myuni.adelaide.edu.au/api/v1/courses/24570/pages/project-charter" -d "wiki_page[body]=hello%”

 
I don’t seem to be able to work around the problem by inserting &#37; but I might be having other “escape” problems there too...

**Comment by simonista** [comment]
Hey @wspr, https://curl.haxx.se/mail/archive-2007-10/0147.html worked for me (changing the % to an escaped %25).  Does that fix it for you as well?

**Comment by wspr** [comment]
@simonista — Sorry for the slow reply. Ah, strange! I'm not on Windows but that indeed fixes the problem. I'm still not sure whether it's Curl's or Canvas's fault, because:

1.  % doesn't need to be escaped in HTML,
1.  the issue still exists if the data is in a file instead of an argument in the shell, and
1.  after the successful upload with `%25`, the content in the body of the Canvas HTML is back to `%`

Here's an example:

    curl -X PUT -H "$CANVASAUTH" $CANVASCOURSE/pages/test-page \
      --data "wiki_page[body]=hello %25 there" | python -m json.tool

With output:

    {
        "body": "hello % there",
        ...

Finally, it turns out that Curl is able to work around / fix this problem using `--data-urlencode` instead of `-d`:

    curl -X PUT -H "$CANVASAUTH" $CANVASCOURSE/pages/test-page --data-urlencode "hello %"

I suppose this does mean it's nothing to do with Canvas; do you agree?

**Comment by simonista** [comment]
Can you give me the full curl request for the last file example?

**Comment by wspr** [comment]
Sure, something like:

    echo "hello % there" > test.canvas
    curl -X PUT -H "Authorization: Bearer <TOKEN>" \ 
      https://myuni.adelaide.edu.au/api/v1/courses/24570/pages/test-page \ 
      --data-urlencode @test.canvas | python -m json.tool

**Comment by ToeBee** [comment]
There are two different encoding schemes at work here. The PUT operation has nothing to do with HTML. It is a URL-encoded form submission, not HTML. [URL encoding rules](https://www.w3schools.com/tags/ref_urlencode.asp) apply and `%` needs to be encoded.

When being displayed back to the browser after a successful submission, it is HTML so HTML encoding rules apply and `%` does not need to be encoded.

**Comment by ToeBee** [comment]
There is also JSON in the mix I guess. `%` does not need encoding there either. And actually, you could get around encoding it while doing the PUT by sending a JSON payload instead of a URL-encoded form. Your PUT payload would look like this:

`{ "wiki_page": { "body": "hello % there"}}`

So your whole curl command would look like this (I did actually run this against a page to verify it works):

    curl -H 'Content-Type: application/json' \
         -H 'Authorization: Bearer <token>'\
         -X PUT -d '{ "wiki_page": { "body": "hello % there"}}'\
         https://myuni.adelaide.edu.au/api/v1/courses/24570/pages/test-page

The JSON format for PUT/POST requests is talked about on the [welcome](https://canvas.instructure.com/doc/api/index.html) page of the API docs.

**Comment by wspr** [comment]
Hmm, this does work, although it's pretty annoying to have to escape all the `"` in the HTML; defining `test.canvas` as:

```
{ "wiki_page": { "body": "
<p class=\"ltx_p\">
It is not expected to be a large document, but some projects may find that they can include considerable detail.
Some projects (especially small ones) may find that their charter is rather small.
As long as justification is made, a sincere effort in either case will yield similar outcomes (i.e., marks).</p>
"}}
```

I can confirm that the `curl` argument in the form `--data @test.canvas` does indeed do the right thing for escaping.

This is rapidly getting off-topic now, but this highlights yet another problem -- the text in the example above contains newlines, and when they're concatenated it strips out spaces that are otherwise legal in the HTML. E.g.,

```
<p>a.
b.
c</p>
```
will render as `a. b. c` in HTML, but when transmitted via PUT this becomes `<p>a.b.c</p> . I guess the only way to fix this problem is to add trailing spaces to all the lines in the HTML file.

So I guess this issue has morphed into more of a request for a saner approach for uploading HTML files to become pages… I guess this is why there are numerous libraries around to wrap the Canvas APIs in a higher-level format?

Thanks for all the advice here; unless you'd like to keep the issue open I guess we can close it now.

**Comment by ToeBee** [comment]
> I guess this is why there are numerous libraries around to wrap the Canvas APIs in a higher-level format

Yep, pretty much. Encoding strings for sending across the network is not always easy but there are existing libraries dedicated to doing it right. 

I did just come across a utility named [jq](https://stedolan.github.io/jq/) that might interest you if you are trying to manipulate JSON on the command line.

Shameless plug: Or if you are into Java, you can see the [API library](https://github.com/kstateome/canvas-api) we here at K-State have recently released. It isn't complete but I **have** used it to manipulate pages before :)
