### ISSUE TITLE
Local file storage only: Fix IE file upload bug by nulling Content-Type header in GET request

### ISSUE THREAD

**Issue by simonista** [instructure/canvas-lms#990]
### Summary:

See https://github.com/instructure/canvas-lms/pull/728 for more information

from @codekitchen:

I was able to dig into this a bit more, and found the relevant difference between s3 and local file uploads. The Canvas web UI uses an undocumented api parameter no_redirect to tell the file uploads API that it doesn't want to be redirected, which causes the preflight request to set success_action_status: 201 in the upload params that are sent along with the file upload.

S3 reads this param and responds with a 201 instead of a 303, and then the web UI manually calls create_success. So IE never even gets a redirect from S3. However, the local files endpoint FilesController#api_create doesn't look for success_action_status, so it always redirects.

If we modify the api_create action to look for the success_action_status parameter and respond with 201 instead of redirecting when it's provided, I think that should solve the IE problem.

Whether this was the best way to work around this issue in the first place is another question, but seeing as how the undocumented parameter is already in place, I think it's fine to use it to solve this bug.

**Comment by patchin** [comment]
Thanks! 👍
