### ISSUE TITLE
 Media comment uploading has not been set up properly. Please contact your administrator.

### ISSUE THREAD

**Issue by AjayDhande** [instructure/canvas-lms#994]
### Summary:
I have a stand alone canvas installation on AWS. On another AWS instance I have Kaltura installed. I have followed all the steps to integrate Kaltura with canvas.
I am using rich text editor and when I click on record/media upload option in the menu it gives me error  Media comment uploading has not been set up properly. Please contact your administrator.  
### Steps to reproduce:

 1. Goto any assignment
 2. Click on edit assignment on the right top corner
 3. Click on the option record/media upload in the menu
 4. Select upload media tab
 5. Select any file and try to upload.
### Expected behavior:
The file should be uploaded properly 
### Additional notes:

**Comment by simonista** [comment]
Hey @AjayDhande, you might have more luck asking about something like this on our mailing list: groups.google.com/forum/#!forum/canvas-lms-users.  Media comments are working fine for us, so I have to guess this is a configuration issue.  I'd try to trace the request and see if you can find any extra info that way, or try manually making requests in a rails console and seeing if you can get any additional info that way. Good luck!

**Comment by stieuquy** [comment]
Hi @simonista, 
I also face this problem, it take 2 days already :(.
Do you have any solution for this.
