### ISSUE TITLE
No file preview

### ISSUE THREAD

**Issue by JuergenHeym** [instructure/canvas-lms#996]
### Summary: I installed canvas lms freshly on an Ubuntu 16.04 server system. I can upload files, I can download them, but I get no file preview for pdf, doc, docx, txt, ...

Any idea what's missing in my installation and / or config's?

**Comment by simonista** [comment]
You'll need to enable google docs previews in your root account settings page (`/accounts/self/settings`):
<img width="542" alt="previews" src="https://cloud.githubusercontent.com/assets/60822/26263658/e0dd3fbe-3c96-11e7-8b1e-1efc266d92eb.png">

**Comment by fdebotts** [comment]
I just installed Canvas as well and with this fresh install I can not preview anything even images....any clue?
