### ISSUE TITLE
Files upload to an "unfiled" folder

### ISSUE THREAD

**Issue by asynchrony-ringo** [instructure/canvas-lms#998]
### Summary:
Files are uploaded to a folder `unfiled` even when I specify a `parent_folder_path` in the API request.

### Steps to reproduce:

Through the API:
 1. Upload a file to a course and set a `parent_folder_path`
```javascript
request({
  method: 'POST',
  url: `${canvasApiUrl}/courses/${courseId}/files`,
  qs: {
    name: 'snapshot',
    parent_folder_path: 'my-snapshots',
    size: imageBuffer.length,
    content_type: 'image/png',
    on_duplicate: 'rename'
  }
});
```
 2. Force delete the folder
```javascript
request({
  method: 'DELETE',
  url: `${canvasApiUrl}/folders/${folderId}`,
  qs: {
    force: true
  }
})
```
 3. Upload a file to the course again using the same `parent_folder_path`

### Expected behavior:
The image should be in the `parent_folder_path` but the second time it is in a folder called "unfiled".

### Additional notes:

If you rename "unfiled" to something else and then upload again, it works.

**Comment by simonista** [comment]
Interesting.  I haven't quite proved this all the way, but I think what's going on is that the the class var caching in this method: https://github.com/instructure/canvas-lms/blob/stable/app/models/folder.rb#L332, is remembering the folder after the first upload, and it's not getting cleared when the folder is deleted.  Then the second upload tries to upload to a deleted folder, and hits https://github.com/instructure/canvas-lms/blob/stable/app/models/attachment.rb#L423 which resets the folder to the "unfiled" folder.
