### ISSUE TITLE
Process killed when running npm install during file generation step of production guide

### ISSUE THREAD

**Issue by mominzahid** [instructure/canvas-lms#999]
### Summary:
I am trying to set up a canvas lms on an amazon ec2 Ubuntu environment. I've gone so far until the file generation step of the production environment guide.  I've been able to successfully follow the steps until this point.
### Steps to reproduce:

 1.
 I was successful in making the asset directories and taking their ownership as directed in this step: 
`sysadmin@appserver:~$ cd /var/canvas
sysadmin@appserver:/var/canvas$ mkdir -p log tmp/pids public/assets public/stylesheets/compiled
sysadmin@appserver:/var/canvas$ touch Gemfile.lock
sysadmin@appserver:/var/canvas$ sudo chown -R canvasuser config/environment.rb log tmp public/assets \
                              public/stylesheets/compiled Gemfile.lock config.ru`

 2. After this, I run `npm install`
 3. It is at this point that after getting some deprecated warnings I get stuck at this line: 

`canvas-lms@0.0.0 preinstall /home/ubuntu/canvas`
`script/gem_npm install`
`running npm install for gems/canvas_i18nliner/package.json`
`running npm install for gems/selinimum/package.json`
`Killed [          ..] / extract:lodash: sill gunzTarPerm modified mode [ 'fp/getOr.js', 420, 436 ]'
`

### What I've already tried:
First I thought it was an error with the port 9418/tcp not being open. I opened this port through amazon ec2 security group inbound rules. This did not work. Then I tried opening all the ports 1-65000 to fix this. It still did not work. 
### Additional notes:
From the looks of it, it does not looks like a port issue because the script is able to fetch data in the previous steps. Also from the progress bar it can be seen that the extract is failing only when the last 2 dots are left as the progress bar is shows like this: [          ..]. I'm guessing this is a .js creation erorr. 

The documentation provides a link to fix those issues but the description of the steps to follow are not very elaborate there as I can't understand what exactly i need to do. Can someone please look into this and help me? Any help is much appreciated.

**Comment by mominzahid** [comment]
The [File Generation ]https://github.com/instructure/canvas-lms/wiki/Production-Start#file-generation) section in the production guide says to follow this [link to fix ,js creation issues](https://groups.google.com/forum/#!searchin/canvas-lms-users/empty%2420css%2420files/canvas-lms-users/-miJsiuK1rA/q1GasvXzUDwJ). The solution I found in this link was to add the following code to the compile_template function found in lib/handlebars/handlebars.rb file. The directory lib/handlebars does not exist in /lib

`def compile_template(source, id, plugin=nil)`
     `     require 'execjs'`
  `    require 'multi_json'`

P.S. I downloaded my installation directly from the git repository so no chance of this being missing for some reason :/

**Comment by simonista** [comment]
Hey @mominzahid, sorry for the delay in responding, these types of issues usually get a better response in IRC our on our mailing list.  That suggestion in the production start looks really old (almost 4 years!), so I just removed it.

As for why npm is hanging, I'm really not sure.  I'd try running in a more verbose mode, or try install with [Yarn](https://yarnpkg.com) instead to see if that helps.
